### DISCUSSION TITLE
(macOS) Tag a folder with Finder after beets moves an album to it

### DISCUSSION THREAD

**Discussion by 2V3EvG4LMJFdRe** [beetbox/beets#3947] [Q&A]
I want beets to add the Finder tag "Organized" to the artist folder an album is added to, after its import to the library.

![Wed May 19 15:23:05 -04 2021](https://user-images.githubusercontent.com/11010067/118872280-6439cb80-b8b6-11eb-93b9-fdf6fe709068.png)

From the terminal, I can use the following to tag a given file as "Organized" (not a native command, I installed this from somewhere):
`$tag --add "Organized" "filepath"`

Now I need a way to append this process to beets, and have beets provide `filepath`. The [hook plugin](https://beets.readthedocs.io/en/stable/plugins/hook.html#individual-hook-configuration) offers a command after a beets event. I've found a [beets event](https://beets.readthedocs.io/en/stable/dev/plugins.html#plugin-events) called `item_moved`. Assuming an "item" is a song, then I need to reference the folder that song is moved to, go up one folder, and retrieve that path to the command above.

**here**\album\item.moved

I'm not a programmer so this is all I've been able to figure out by myself. I'd appreciate any help. I'm publishing this as an idea because I think it could be useful to have a simpler workaround. Currently I have a folder with all files that haven't been tagged and another for those "Organized", but I think structurally we are moving to a point were using folders to make these type of divisions doesn't make as much sense as using tags.

**Comment by jackwilsdon** [comment]
You should be able to use `dirname` to get the parent of a directory, so nesting two `dirname`s should give the album directory provided your paths are in the form `Artist/Album/Song.ext`:

```text
$ dirname "Music/Artist/Album/Song.ext"
Music/Artist/Album
$ dirname "Music/Artist/Album"
Music/Artist
$ dirname "$(dirname "Music/Artist/Album/Song.ext")"
Music/Artist
```

You can create a wrapper shell script using this, and save it somewhere such as `/Users/your-name/.config/beets/tag.sh`:
```bash
#!/bin/bash
your-tagging-command --add "$1" "$(dirname "$(dirname "$2")")"
```

You can then run it from a hook:
```yaml
hook:
  hooks:
    - event: item_moved
      command: '/Users/your-name/.config/beets/tag.sh Organized {destination}'
```

You might need to `chmod` the script (`chmod 777 tag.sh`) or run it with `bash`, I don't quite recall how well `hook` works with shell scripts.

```yaml
hook:
  hooks:
    - event: item_moved
      command: 'bash /Users/your-name/.config/beets/tag.sh Organized {destination}'
```
