### DISCUSSION TITLE
Always force fetchart

### DISCUSSION THREAD

**Discussion by 2V3EvG4LMJFdRe** [beetbox/beets#3952] [Q&A] [answered]
I'd like to know how can I make beets to always import albums downloading a new cover with fetchart, ignoring cover.* and embedded artwork alike. I have fetchart set to `auto: yes`, and essentially would like to apply an -f flag to its config:

```
fetchart:
    -f
    auto: yes
    sources: fanarttv itunes amazon coverart albumart google
    fanarttv_key: redacted
    google_API_key: redacted
```

Is that okay?
