### DISCUSSION TITLE
Issue when importing files with non-number year tags

### DISCUSSION THREAD

**Discussion by Auranium64** [beetbox/beets#3971] [Q&A]
Hello. I'm having issues regarding my music library which I have recently brought over from MusicBee. With my personal tagging system, albums by the same album artist that were released in the same year have a letter added to them. For instance, The Beatles' Sgt. Pepper's Lonely Heart Club Band is tagged with the year "1967a" while Magical Mystery Tour is tagged with "1967b", this is to guarantee chronological organization without having to input exact release dates for every album in my collection.

MusicBee, while showing my a tiny warning about how the year tag was "invalid", accepted it anyways, organizing the folders in the following way for the above example:
```
The Beatles/(1967a) - Sgt. Pepper's Lonely Hearts Club Band
The Beatles/(1967b) - Magical Mystery Tour
```
However, with beets, the "unorthodox" year tags are being seemingly ignored, and being organized as follows:
```
The Beatles/(0000) - Sgt. Pepper's Lonely Hearts Club Band
The Beatles/(0000) - Magical Mystery Tour
```
What could I do about this? Here's my current configuration:
```
plugins: vtalbumartist inline

directory: /home/auran/drive/Music
library: /home/auran/Music/musiclibrary.db
import:
    move: no
    copy: yes
    write: yes
    autotag: no
    log: beetslog.txt
art_filename: Cover

paths:
    default: $albumartist/($year) - $album/$disc_and_track. $title

format_item: $albumartist - $album - $title
format_album: $albumartist - $album - $year

sort_item: albumartist+ year+ album+ disc+ track+
sort_album: albumartist+ year+ album+

per_disc_number: yes

item_fields:
    disc_and_track: u'%02i-%02i' % (disc, track) if
                    disctotal > 1 else u'%02i' % (track)
```
Thank you in advance.
