### DISCUSSION TITLE
Importing incomplete albums / Completing albums w singleton tracks

### DISCUSSION THREAD

**Discussion by JOJ0** [beetbox/beets#4211] [Q&A] [answered]
I want to import and move an old and very badly tagged big bunch of mp3 files into beets. I often have the situation that files are in a folder called <artist> and there is no further subfolders, and no good tagging to what albums those files belong. Files belong to random albums of this artist but most of those albums would be incomplete if ordered back together. Something like 3 tracks from and ablum out of 15 tracks is a rough standard here.

I played around with the "group_albums: yes" option but I am not sure if it does what I want / if I understand correctly. After endless tries of reimports with one single "artist folder" I realized that the only way to get beets halfway to recognize tracks on the same album was to initially manually moving files to "album folders" before starting `beets import`. This worked but can't be the proper solution for what I am trying to achieve.

Before I am posting my rather lengthy already beets config file I'd like to ask what would be the essential settings to achieve the following:

- On import it should be tried to find files belonging to the same albums as good as possible
- Singleton import should be avoided
- Finding incomplete albums should not be considered a problem and still provide strong matches
- My highest priority is to get each file tagged with an album and not leaving out the album information - as I understand its done using the singleton option (I might be wrong and confused of what's happening already after a couple of days playing around with beets ;-)))
- I don't care about incomplete albums as long as files belonging to an album will be tagged and filed into the same album directory.
- In the end I would like to have a directory structure like where each and every file is residing in an `<artist>/<album>/` folder
- Since I think each and every file is actually corresponding to an album/single/release/youname it, there should not be the need for a folder called Non-Album in my collection.
- A nice to have thing certainly would be to have an incomplete search, but I think I already found that. The "incomplete" plugin does that already. Nice! :-)

Thanks for any workflow and config hints, I can certainly post my config here but at the moment I am not sure if it adds to clarity of what I want to achieve, thus let's wait until someone asks for set options explicitely.

**Comment by JOJ0** [comment]
This would be my configuration:
```
directory: ~/Music/
library: ~/jtbeets.db
asciify_paths: yes
threaded: no

import:
    log: ~/jtbeets-import.log
    copy: yes
    move: no
    write: yes
    resume: yes
    from_scratch: yes
    default_action: apply
    detail: yes
    non_rec_action: ask
    duplicate_action: skip
    group_albums: no
    autotag: yes
    bell: yes

match:
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD',
                    'VCD', 'SVCD', 'UMD', 'VHS']
    strong_rec_thresh: 0.80
    medium_rec_thresh: 0.50
    max_rec:
        missing_tracks: medium
        #unmatched_tracks: medium
    preferred:
        #countries: ['GB|UK', 'US']
        media: ['CD', 'LP', 'Digital Media|File', 'Cassette']
        original_year: yes

paths:
    default: $albumartist/$year - $albumartist - $album%aunique{}/$track - $artist - $album - $title ($year)
    singleton: $artist/$artist - $album - $title ($year)
    comp: Compilations/$album%aunique{}/$track - $artist - $title ($year)

plugins: fromfilename chroma discogs importadded web info acousticbrainz missing unimported mbsync duplicates fetchart thumbnails edit

musicbrainz:
    source_weight: 1.0
    #extra_tags: [year, catalognum, country, media, label]
    genres: yes

chroma:
    source_weight: 0.8
    auto: yes

discogs:
    source_weight: 0.6

fromfilename:
    source_weight: 0.4

importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes
```
