### DISCUSSION TITLE
How to configure preferred media properly

### DISCUSSION THREAD

**Discussion by JOJ0** [beetbox/beets#4217] [Q&A] [answered]
I'd like to get beets to prefer CD over Cassette media during import. This is the relevant piece in the configuration. Is this correct? Is there a typo?

```
preferred:
    countries: ['GB|UK', 'US']
    media: ['CD', 'LP', 'Digital Media|File', 'Cassette']
    original_year: yes
```

This is what happens. It still takes the Cassette release (which would be automatically applied if I hadn't chosen --timid option):

```
    ~  beet -v import -t  smb4k/DS/data/music-archive/DowntempoTriphopDubAcidjazz/0-ALBUMS/Asian\ Dub\ Foundation\ Discography/1998\ -\ Asian\ Dub\ Foundation\ -\ Rafis\ Revenge                                   ✔ 
user configuration: /home/jojo/.config/beets/config.yaml
data directory: /home/jojo/.config/beets
plugin paths: 
artresizer: method is (2, (7, 1, 0), False)
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
Sending event: pluginload
library database: /home/jojo/jtbeets.db
library directory: /home/jojo/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/jojo/smb4k/DS/data/music-archive/DowntempoTriphopDubAcidjazz/0-ALBUMS/Asian Dub Foundation Discography/1998 - Asian Dub Foundation - Rafis Revenge
Tagging Asian Dub Foundation - Rafi's Revenge
No album ID found.
Search terms: Asian Dub Foundation - Rafi's Revenge
Album might be VA: False
Searching for MusicBrainz releases with: {'release': "rafi's revenge", 'artist': 'asian dub foundation', 'tracks': '12'}
Requesting MusicBrainz release f9b128d0-3bd0-47a3-8646-cf63d794d48c
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi's Revenge (f9b128d0-3bd0-47a3-8646-cf63d794d48c)
Computing track assignment...
...done.
Success. Distance: 0.03
Requesting MusicBrainz release ee6048dc-8daf-4042-a098-5ccf5b42bd5f
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi’s Revenge (ee6048dc-8daf-4042-a098-5ccf5b42bd5f)
Computing track assignment...
...done.
Success. Distance: 0.03
Requesting MusicBrainz release ac0ca145-2170-4817-a057-868da329ff23
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi’s Revenge (ac0ca145-2170-4817-a057-868da329ff23)
Computing track assignment...
...done.
Success. Distance: 0.03
Requesting MusicBrainz release 70eabfa6-e06a-4dbb-8e51-c84fc6e77dae
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi's Revenge (70eabfa6-e06a-4dbb-8e51-c84fc6e77dae)
Computing track assignment...
...done.
Success. Distance: 0.09
Requesting MusicBrainz release 18215b35-46e0-4d30-bef0-f4ab0bc8bbdb
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi's Revenge (18215b35-46e0-4d30-bef0-f4ab0bc8bbdb)
Computing track assignment...
...done.
Success. Distance: 0.13
Requesting MusicBrainz release ac0ca145-2170-4817-a057-868da329ff23
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Requesting MusicBrainz release ee6048dc-8daf-4042-a098-5ccf5b42bd5f
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Requesting MusicBrainz release f9b128d0-3bd0-47a3-8646-cf63d794d48c
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Requesting MusicBrainz release 70eabfa6-e06a-4dbb-8e51-c84fc6e77dae
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Requesting MusicBrainz release 1eeef41d-93dc-4393-ae33-462c2a8604ed
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
chroma: acoustid album candidates: 5
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi’s Revenge (ac0ca145-2170-4817-a057-868da329ff23)
Duplicate.
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi’s Revenge (ee6048dc-8daf-4042-a098-5ccf5b42bd5f)
Duplicate.
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi's Revenge (f9b128d0-3bd0-47a3-8646-cf63d794d48c)
Duplicate.
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi's Revenge (70eabfa6-e06a-4dbb-8e51-c84fc6e77dae)
Duplicate.
Sending event: albuminfo_received
Candidate: Asian Dub Foundation - Rafi's Revenge (1eeef41d-93dc-4393-ae33-462c2a8604ed)
Computing track assignment...
...done.
Success. Distance: 0.27
Evaluating 6 candidates.

/home/jojo/smb4k/DS/data/music-archive/DowntempoTriphopDubAcidjazz/0-ALBUMS/Asian Dub Foundation Discography/1998 - Asian Dub Foundation - Rafis Revenge (12 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
Tagging:
    Asian Dub Foundation - Rafi's Revenge
URL:
    https://musicbrainz.org/release/f9b128d0-3bd0-47a3-8646-cf63d794d48c
(Similarity: 96.8%) (tracks) (Cassette, 1998, GB, London Records 90, 314-556-006-4)
 * Naxalite
 * Buzzin'                 -> Buzzin’
 * Black White
 * Assassin
 * Hypocrite
 * Charge
 * Free Saptal Ram         -> Free Satpal Ram (title)
 * Dub Mentality
 * Culture Move
 * Operation Eagle Lie
 * Change
 * Tribute To John Stevens -> Tribute to John Stevens (id)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? m
Finding tags for album "Asian Dub Foundation - Rafi's Revenge".
Candidates:
1. Asian Dub Foundation - Rafi's Revenge (96.8%) (tracks) (Cassette, 1998, GB, London Records 90, 314-556-006-4)
2. Asian Dub Foundation - Rafi’s Revenge (96.8%) (tracks) (CD, 1998, GB, London Records 90, FFRR / 556 006-2)
3. Asian Dub Foundation - Rafi’s Revenge (96.8%) (tracks) (CD, 1998, CA, FFRR, 314 556 006-2)
4. Asian Dub Foundation - Rafi's Revenge (91.5%) (missing tracks, tracks) (CD, 1998, US, Slash, 314-556 053-2)
5. Asian Dub Foundation - Rafi's Revenge (86.7%) (missing tracks, tracks) (CD, 1999, DE, FFRR, 3984 28193-2)
6. Asian Dub Foundation - Rafi's Revenge (73.4%) (missing tracks, tracks) (2xCD, 2019, XE, London Records, LMS5521229)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 
```

**Comment by JOJ0** [comment]
This would be my whole config:
```
directory: ~/Music/
library: ~/jtbeets.db
asciify_paths: yes
threaded: no

import:
    log: ~/jtbeets-import.log
    copy: yes
    move: no
    write: yes
    resume: yes
    from_scratch: yes
    default_action: apply
    detail: yes
    non_rec_action: ask
    duplicate_action: skip
    group_albums: no
    autotag: yes
    bell: yes

match:
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD',
                    'VCD', 'SVCD', 'UMD', 'VHS']
    strong_rec_thresh: 0.80
    medium_rec_thresh: 0.50
    max_rec:
        missing_tracks: medium
        #unmatched_tracks: medium

preferred:
    countries: ['GB|UK', 'US']
    media: ['CD', 'LP', 'Digital Media|File', 'Cassette']
    original_year: yes

paths:
    default: $albumartist/$year - $albumartist - $album%aunique{}/$track - $artist - $album - $title ($year)
    singleton: $artist/$artist - $album - $title ($year)
    comp: Compilations/$album%aunique{}/$track - $artist - $title ($year)

plugins: fromfilename chroma discogs importadded web info acousticbrainz missing unimported mbsync duplicates fetchart thumbnails edit

musicbrainz:
    source_weight: 1.0
    #extra_tags: [year, catalognum, country, media, label]
    genres: yes

chroma:
    source_weight: 0.8
    auto: yes

discogs:
    source_weight: 0.6

fromfilename:
    source_weight: 0.4

importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes
```
