### DISCUSSION TITLE
Default config macOS 10.13

### DISCUSSION THREAD

**Discussion by JOJ0** [beetbox/beets#4248] [Q&A] [answered]
Hi,
I just installed beets from git on a second computer and realized that the default config I initially get looks like this:
```
directory: ~/music/
library: ~/.beet/musiclibrary.db
log: ~/.beet/import.log
resume: ask
default_action: asis
```

From reading beets.readthedocs.io it seems options `log`, `resume` and `default_action` should be set on the `import` level rather than on the root level.

I assume actually it should be like that:
```
directory: ~/Music/
library: ~/.beet/musiclibrary.db
import:
  log: ~/.beet/import.log
  resume: ask
  default_action: asis
```

So is the default config I got correct or is this considered a bug? Didn't look at the config-generating code yet...
