### DISCUSSION TITLE
What are distance_weight id and source

### DISCUSSION THREAD

**Discussion by JOJ0** [beetbox/beets#4297] [Q&A] [answered]
In the importer: What is ment by source and id in an output like that:

```
(beets) jojo@gin ~/git/beets (skip_write) $ beet import ~/Music/Techno/015-spin_12-03/Oliver\ Deutschmann\ -\ Darkroom\ Tales\ \[Aim\ X01\]\ \(2012\)\ FLAC/

/Users/jojo/Music/Techno/015-spin_12-03/Oliver Deutschmann - Darkroom Tales [Aim X01] (2012) FLAC (2 items)
Tagging:
    Oliver Deutschmann - Darkroom Tales
URL:
    https://www.discogs.com/release/3424470-Oliver-Deutschmann-Darkroom-Tales
(Similarity: 72.4%) (id, source) (Discogs, Vinyl, 2012, Germany, Aim (3), Aim X01)
 * Darkroom Tales feat. Loganic FLAC - Bm - 62    -> Darkroom Tales
 * Darkroom Tales (Tristen Edit) FLAC - Ebm - 123 -> Darkroom Tales (Tristen Edit)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, plaY, eDit, edit Candidates?
```

- Is `source` the tagging source? Eg. MusicBrainz, Discogs, ...
- Is `id` the track id's not matching Eg. A1 vs 1, 1 vs. 2, etc ? Or is it the MusicBrainz Release ID or the Discogs Release ID?

**Comment by JOJ0** [comment]
To give some context what I am aiming for. I am playing around with distance_weights. I want to get higher scores, closer to strong_rec_thresh, I'd like to ignore things I don't consider important like country and media the entry is from. I prefer MusicBrainz over Discogs as a source (source_weights there are configured accordingly). This is my current match config:
```
match:
    strong_rec_thresh: 0.12
    medium_rec_thresh: 0.50
    rec_gap_thresh: 0.2
    max_rec:
        missing_tracks: strong
        unmatched_tracks: medium
     distance_weights:
        source: 0.0  # Default 2.0
        country: 0.0  # Default 0.5
        media: 0.0  # Default 1.0
        #mediums: 0.0  # Default 1.0
        track_title: 0.0  # Default 3.0
        album: 4.0  # Default 3.0
        catalognum: 4.0  # Default 0.5
        track_id: 2.0 # Default 5.0
```

Also there is one major problem in this collection: I used a third party tool that manipulates the track title, thus it is never 100% correct (adds `- Key - BPM`), also sometimes I wrote in stuff into the title field myself. Like FLAC in above's example.

Question on this regard: How exactly does the title matching work? Is it comparing 1:1 or does it any fuzzy regexing thing? A link to code where this happens would be interesting.

What is the mediums setting? I understand that media is wether the source provides the info of the same release from a vinyl or CD or Digital Media. What is mediums then?.........Ah now that I write it: It might be the count of the mediums the record was put out. E.g 2xCD, 3xLP, is that right?
