### DISCUSSION TITLE
Help with last genre plugin: throwing me an error every time

### DISCUSSION THREAD

**Discussion by fabiendostie** [beetbox/beets#4311] [Q&A] [answered]
I am using my own genre tree and database 
and it just stopped working, I havent changed anything in my config of python... that i know or remember of.

here is the last genre section of my config.yaml
```
# Last.fm #########################################################################################

lastimport:
  per_page: 500              # The number of tracks to request from the API at once. Default: 500.
  retry_limit: 3             # How many times should we re-send requests to Last.fm on failure? Default: 3.
lastfm:
  user: REDACTED
  api_key: REDACTED
types:
  play_count: int
  rating: float

lastgenre:
                             # Fetches tags from Last.fm and assigns them as genres to your albums and items.
  auto: yes                  # Fetch genres automatically during import. Default: yes.
                             # Use a canonicalization tree. Setting this to yes will use a built-in tree.
  canonical: ~/.config/beets/genres/genres-tree.yaml 
                             # The filename of a custom genre list, yes to use the internal whitelist, or no to consider all genres valid.
                             # Default: yes.
  whitelist: ~/.config/beets/genres/genres.txt
                             
                             
  count: 2                   # Number of genres to fetch. Default: 1
  fallback: 'No_Genre'       # A string if to use a fallback genre when no genre is found.
                             # You can use the empty string '' to reset the genre.
                             # Default: None.
  separator: ', '
  force: yes                 # By default, beets will always fetch new genres, even if the files already have one.
                             # To instead leave genres in place in when they pass the #whitelist: ~/.config/beets/genres.txt,
                             # set the force option to no.
  min_weight: 10             # Minimum popularity factor below which genres are discarded. Default: 10.
  prefer_specific: no        # Sort genres by the most to least specific, rather than most to least popular. Default: no.
  source: album              # Which entity to look up in Last.fm. Can be either artist, album or track. Default: album. 
  title_case: yes            # Convert the new tags to TitleCase before saving. Default: yes.
```
and here's my terminal output from a basic beet lastgenre command:

➜  music beet lastgenre /Volumes/music/CleanBeet/B
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1285, in main
    _raw_main(args)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beetsplug/lastgenre/__init__.py", line 400, in lastgenre_func
    for album in lib.albums(ui.decargs(args)):
  File "/usr/local/lib/python3.9/site-packages/beets/dbcore/db.py", line 714, in _get_objects
    if not self.query or self.query.match(obj):
  File "/usr/local/lib/python3.9/site-packages/beets/dbcore/query.py", line 446, in match
    return all(q.match(item) for q in self.subqueries)
  File "/usr/local/lib/python3.9/site-packages/beets/dbcore/query.py", line 446, in <genexpr>
    return all(q.match(item) for q in self.subqueries)
  File "/usr/local/lib/python3.9/site-packages/beets/library.py", line 99, in match
    path = item.path if self.case_sensitive else item.path.lower()
  File "/usr/local/lib/python3.9/site-packages/beets/dbcore/db.py", line 483, in __getattr__
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/beets/dbcore/db.py", line 390, in __getitem__
    return self._get(key, raise_=True)
  File "/usr/local/lib/python3.9/site-packages/beets/dbcore/db.py", line 371, in _get
    return getters[key](self)
  File "/usr/local/lib/python3.9/site-packages/beets/library.py", line 1238, in item_dir
    raise ValueError('empty album for album id %d' % self.id)
ValueError: empty album for album id 1
➜  music
```

anyone has a clue what I have to do to fix this?
I actually marked out all the "non-essential" plugins and configs from my config.yaml to just keep the minimum + last genre... but I still get the error.

Getting really frustrated with this!
