### DISCUSSION TITLE
Autotag existing music library and mark duplicates in Android

### DISCUSSION THREAD

**Discussion by SoumyBhow** [beetbox/beets#4350] [Q&A]
Hello all. As the title suggests I'd like to autotag and mark duplicates in my existing music library. I'm on Android and I've installed beets in Termux. I got all of my mp3s in a folder (/sdcard/Music) and they're not organized into sub folders by album. This is the content of my config.yaml so far:
```
directory: /sdcard/Music
library: /sdcard/Music/musiclibrary.db
import:
   copy: no
   write: yes
 ```
I haven't ran any commands yet since I'd like to confirm here before doing so. Should I just run ``` beets import /sdcard/Music```?
