### DISCUSSION TITLE
Creating directories from the Convert plugin

### DISCUSSION THREAD

**Discussion by AndrewGibb** [beetbox/beets#4378] [Q&A]
My first time using beets, so probably a misconfiguration:

When I try to run `beet convert` for the first time, album directories are not created, for albums which require conversion. This causes ffmpeg to crash for these tracks, as it expects the destination directory to exist, I am using `never_convert_lossy_files: yes` in my config so that compressed files are copied. Those are copied to the destination as expected.

This is possibly a threading problem: If I set `threads: 1` in the config, then the album directories are created correctly.

Here's my config in full:
```
directory: /Volumes/Red1/beetz/testlibrary

replace:
    \/\\\/\\: M
    \/\\: A
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
    ^\s+: ''
    ^-: _
id3v23: yes
log: /Volumes/Red1/beetz/importlog.txt
languages: en

plugins: info convert
convert:
    #    threads: 1
    never_convert_lossy_files: yes
    copy_album_art: yes
    dest: /Volumes/Red1/beetz/carchoonz
    format: aac
    formats:
        aac:
            command: ffmpeg -i $source -ar 44100 -ab 16 -c:a libfdk_aac -b:a 128k -cutoff 20000 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    pretend: no
    link: no
    hardlink: no
    id3v23: inherit
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    album_art_maxwidth: 0
    delete_originals: no
```
