### DISCUSSION TITLE
Adding album name to singletons

### DISCUSSION THREAD

**Discussion by arsaboo** [beetbox/beets#4398] [Ideas]
I was looking at the code and could not figure out why we are not adding `album` (or release) information when importing singletons. It appears to me that we can pass `self.match.info.album` value in the return object [here](https://github.com/beetbox/beets/blob/master/beets/importer.py#L900).  This value can then be applied in the `apply_item_metadata` function [here](https://github.com/beetbox/beets/blob/master/beets/autotag/__init__.py#L74). 

Not sure if this is just an oversight or if I am missing something.

**Comment by arsaboo** [comment]
Did a little more digging and looks like the [TrackMatch](https://github.com/beetbox/beets/blob/master/beets/autotag/hooks.py#L548) object does not include album information. Here's the information contained in `self.match.info` object:

`info={'title': 'Baila Baila (From "Khwahish")', 'track_id': '1xZdiuCLPekiYf8N6njbWC', 'release_track_id': None, 'artist': 'Milind Sagar, Asha Bhosle', 'artist_id': '2oIJxb6sTNTbErx3Pt38qp', 'length': 257.7, 'index': 11, 'media': None, 'medium': 1, 'medium_index': 11, 'medium_total': 14, 'artist_sort': None, 'disctitle': None, 'artist_credit': None, 'data_source': 'Spotify', 'data_url': 'https://open.spotify.com/track/1xZdiuCLPekiYf8N6njbWC', 'lyricist': None, 'composer': None, 'composer_sort': None, 'arranger': None, 'track_alt': None, 'work': None, 'mb_workid': None, 'work_disambig': None, 'bpm': None, 'initial_key': None, 'genre': None, 'spotify_track_id': '1xZdiuCLPekiYf8N6njbWC', 'spotify_artist_id': '2oIJxb6sTNTbErx3Pt38qp'}`

**Comment by sampsyo** [comment]
Unfortunately, this information is not readily available—and it's not clear how to get it. #229 discusses the issues—namely, it's not clear which album we should be pulling the information from (in MB, recordings can appear on multiple releases).

**Reply by arsaboo** [reply]
I was using it with Spotify, where we explicitly provide the track id (track link). Why can't we just use that album information. Even for MB, we can start with the album with highest popularity (or some other disambiguation approach)?

**Reply by sampsyo** [reply]
Ah, maybe adding this in for Spotify makes sense! I'd support exploring that. It would just require adding additional fields to the `TrackInfo` object in the plugin, I think.

The MusicBrainz thing is trickier… we could cook up heuristics, but it seems like they would inevitably do the wrong thing for some people, so it's not clear how valuable they would be.

**Reply by arsaboo** [reply]
Quite honestly, any album information will be better than the current approach of not adding any album information. Given that the user has requested the singleton to be imported, it is fair to include some album information (even though it may be less than ideal).

**Reply by wisp3rwind** [reply]
I strongly disagree — I much prefer having no album information in that case than something (slightly or completely) wrong.

If you want album information for single tracks, wouldn't it be possible to import in album mode, which can handle missing tracks?

**Reply by JOJ0** [reply]
The odd thing here is that the only tagging source on earth following the concept of recordings being a thing of their own and possibly appearing on multiple releases, is musicbrainz. I am not saying this concept is bad or wrong at all but any other source like spotify and discogs dont work like that. I you eg select a track from discogs, it always comes with an album attached. The user chooses for the album plus the track, so to say. So also in this source plugin album should be populated on singleton imports.

Correct me if I'm wrong please: Which tagging sources follow a rec/release concept similar to musicbrainz?

Musicbrainz was the source beets was initially built for so it's obvious that it followed the concept, nothing wrong with that but I think all other sources should now be thought over wheter singleton imports should populate album field or not.

**Reply by arsaboo** [reply]
> I strongly disagree — I much prefer having no album information in that case than something (slightly or completely) wrong.
> 
> If you want album information for single tracks, wouldn't it be possible to import in album mode, which can handle missing tracks?


I don't see the downside of including the album name either way. Worst case scenario, you can always ignore the album name or re-import. However, for those who are importing singletons or a jumbled library, it is a valuable piece of information. I definitely find it valuable.

**Comment by arsaboo** [comment]
So, I was able to get this working and it works after I add `album` to the `TrackInfo` object in [hooks.py](https://github.com/arsaboo/beets/blob/spotify_track/beets/autotag/hooks.py#L145) and passing the `album` information in `_get_track` function [here](https://github.com/arsaboo/beets/blob/spotify_track/beetsplug/spotify.py#L295). It only works for Spotify tracks for now - the behavior is unchanged for other sources. 

Let me know if this approach is acceptable and I can create a PR.

**Reply by sampsyo** [reply]
Seems OK to me! Except that you shouldn't need to change `hooks.py`—adding any information via `**kwargs` there should work the same way.

**Comment by arsaboo** [comment]
Just to close this out - https://github.com/beetbox/beets/pull/4405 adds this feature for Spotify tagger.

**Reply by jo-chemla** [reply]
Hi there, out of curiosity, what is the recommended way to have the spotify tagger embed the album metadata for the singleton imports? 
 - I've looked at the issue thread [here](https://github.com/beetbox/beets/pull/4405), 
 - I am running nightly 1.6.1 - thoughts the latest `spotifysync` might be useful, especially this in the changelog: `We now import and tag the album information when importing singletons using Spotify source`
 - I have the following spotify configuration and tested the below commands
 
But they show no spotify-id in the metadata, and album metadata (like album title) is still the old one. The `spotifysync` command probably did not update the file metadata because it is still lacking the `spotify-id`. Looking for advice here, thanks for your help!

```yml
spotify:
    source_weight: 0.8
    tiebreak: popularity   
    mode: list
    region_filter: FR
    show_failures: on
    # 
    client_id: xyz
    client_secret: xyz
```

```sh
beet import /music/all-tracks-single-directory/test-music.opus -s -C
beet info query
beet spotifysync query
beet info query
```

PS: if useful to anyone passing by, seems like album metadata imports for singletons has also be added to Discogs as seen here: https://github.com/beetbox/beets/pull/4854 (could not test because of login issues on the discogs server right now)

**Reply by arsaboo** [reply]
Just use `beet import -C /music/all-tracks-single-directory/` and when it prompts you for matches, use [T]racks. That is how I use it.

**Reply by JOJ0** [reply]
interesting @arsaboo the import cmd being used https://github.com/beetbox/beets/discussions/4398#discussioncomment-8126064

includes -s option already which should switch to tracks/singleton mode already

**Reply by arsaboo** [reply]
Sure, `-s` can turn to singleton mode already. My point was pointing to the folder instead of the actual file.

**Reply by jo-chemla** [reply]
Thanks both for replying, I'm indeed using the -s singleton mode and tried importing both the folder as well as single track files. It seems that the tagger used is not `spotify` but the default `musicbrainz` one. I did set 0.7 `source_weight` for spotify but am using the unknown default source weight for musicbrainz tagger.

**Reply by JOJ0** [reply]
try setting musicbrainz.enabled to "no", look it up in the config ref docs. hth

https://beets.readthedocs.io/en/latest/reference/config.html#musicbrainz-options

**Reply by JOJ0** [reply]
and btw you can also use this  setting for musicbrainz

source_weight: 0.1

I 'm also not sure what the default is, I think 0.5??

**Reply by jo-chemla** [reply]
Thanks again for getting back. I've tried everything, and it seems like the spotify tagger is never used, and musicbrainz tagger is used instead. Also tried doing so with discogs. It seems that since there are `mb_xyz` fields then the tagger used is musicbrainz, although it is disabled in the config. Should I open a dedicated issue/discussion instead? 

Here is the last config I've tried: 

<details>
  <summary>config.yml</summary>

```yml

chroma:
    auto: no
 
import:
    incremental: no # yes no # to reimport already imported files: no
    quiet: yes
    log: /config/beet.log
    # incremental skip importing any directories that have been imported in the past 
    # quiet avoids asking you any questions
    write: yes
    copy: yes
    move: no
    resume: ask
    quiet_fallback: skip
    timid: no

spotify:
    source_weight: 0.8
    tiebreak: popularity   
    mode: list
    region_filter: FR
    show_failures: on
    # 
    client_id: REDACTED
    client_secret: REDACTED

musicbrainz:                                                                        
     enabled: no                           
     source_weight: 0.0

discogs:
   user_token: REDACTED
   source_weight: 0.9

```

</details>

<details>
  <summary>And resulting import logs</summary>

```sh

 # beet -vvvv import -s -C /music_ytdlsub/test-music-songs-vs-video/\[2023\]\ test/02\ -\ Nocturne.opus 
user configuration: /config/config.yaml
data directory: /config
plugin paths: 
lyrics: Disabling google source: no API key configured.
fetchart: google: Disabling art source due to missing key
Sending event: pluginload
library database: /config/musiclibrary.blb
library directory: /music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /music_ytdlsub/test-music-songs-vs-video/[2023] test/02 - Nocturne.opus
Searching for track ID: a41ac9f5-74c6-42a7-b0b2-acc0dfb2d581
Sending event: mb_track_extract
Sending event: trackinfo_received
Track ID match.

/music_ytdlsub/test-music-songs-vs-video/[2023] test/02 - Nocturne.opus

  Match (100.0%):
  Worakls - Nocturne
  MusicBrainz, Index None, Track None, 
  https://musicbrainz.org/recording/a41ac9f5-74c6-42a7-b0b2-acc0dfb2d581
  * Artist: Worakls
  * Title: Nocturne
Sending event: import_task_choice
Sending event: import_task_apply
Replacing item 56: /music_ytdlsub/test-music-songs-vs-video/[2023] test/02 - Nocturne.opus
Sending event: database_change
Sending event: item_removed
1 of 1 items replaced
Sending event: database_change
Sending event: database_change
Reimported item 56. Preserving attribute ['added']. Path: /music_ytdlsub/test-music-songs-vs-video/[2023] test/02 - Nocturne.opus
Reimported item 56. Preserving flexible attributes ['data_source']. Path: /music_ytdlsub/test-music-songs-vs-video/[2023] test/02 - Nocturne.opus
Sending event: database_change
lyrics: lyrics already present: Worakls - test - Nocturne
lastgenre: last.fm error: Album not found
lastgenre: added last.fm item genre (artist): Techno
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: import_task_files
scrub: auto-scrubbing /music_ytdlsub/test-music-songs-vs-video/[2023] test/02 - Nocturne.opus
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
Sending event: item_imported
Sending event: import
Sending event: cli_exit
```

</details>

Note the info of this file returns multiple mb_ fields: 
 ```
   mb_albumartistid: 
   mb_albumartistids: 
   mb_albumid: 
   mb_artistid: 272deaa4-4699-46ee-abe8-c63f495142d7
   mb_artistids: 272deaa4-4699-46ee-abe8-c63f495142d7
   mb_releasegroupid: 
   mb_releasetrackid: 
   mb_trackid: a41ac9f5-74c6-42a7-b0b2-acc0dfb2d581
   mb_workid:
```
