### DISCUSSION TITLE
"Item not found" for every song

### DISCUSSION THREAD

**Discussion by IcyAlmond** [beetbox/beets#4425] [Q&A] [answered]
I'm not sure what's wrong or if this is a problem at all, but with the mpdstats plugin, i keep getting "item not found"
```sh
$ beet -vv mpdstats
user configuration: /home/user/.config/beets/config.yaml
data directory: /home/user/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/user/config/beets/library.db
library directory: /home/user/Music
Sending event: library_opened
mpdstats: music_directory: /home/user/Music
mpdstats: strip_path: /
mpdstats: connecting to localhost:6600
mpdstats: returning: /home/user/Music/out.flac
mpdstats: playing /home/user/Music/out.flac
mpdstats: item not found: /home/user/Music/out.flac
```
this is my config file
```yaml
directory: /home/user/Music
plugins: mpdstats
mpd:
  music_directory: /home/user/Music
```
