### DISCUSSION TITLE
How do I make beets use musicbrainz tags and ignore everything else?

### DISCUSSION THREAD

**Discussion by sdfg2** [beetbox/beets#4482] [Q&A] [answered]
I use Lidarr to sort a canonical set of lossless media, including Musicbrainz tagging and so on.  It then calls a script which normalizes and transcodes to lossless, that then calls `beet import` so that beets managed my lossy media.

Beets keeps asking me questions, and telling me about missing tracks and so on!

I had a look through the issues, and found #3548, I've set `album_id` to 1000 and yet it still does it on some albums.  What else do I need to configure to make it forget about searching any other details and _only_ using the MB ID it's been given?  Do I need to set (all!) the other weights to zero?  Or is there a shorthand way of doing this?  I've already gone through curating the release information with lidarr.

**Comment by sampsyo** [comment]
> Do I need to set (all!) the other weights to zero?

That would certainly do it! You could also consider using quiet mode, and perhaps adjusting `strong_rec_thresh` to make the importer automatically apply matches above a given threshold:
https://beets.readthedocs.io/en/stable/reference/config.html#autotagger-matching-options

**Reply by sdfg2** [reply]
Well, I guess what I'm looking for is the results to always be 100%.  Adjusting `strong_rec_thresh` won't stop beets from processing the other means of identifying.  Same with using quiet.

Will setting the other weights to 0 mean that they won't even be processed, or will they be processed and just multiplied by the weight?

**Reply by sampsyo** [reply]
Yep, multiplied by the weight.

Another approach you might consider could be importing _as-is_ (by disabling the autotagger with `-A`), and then using the `mbsync` plugin. `mbsync` trusts IDs blindly, but otherwise works a little like an import, which may be what you want.

**Reply by sdfg2** [reply]
I set all the others to 0, and it seems to do what I want.  I know it's probably an edge case, but if a weight is zero, it seems to me like there's no point processing that information in the first place - just skip that calculation, get through the rest quicker!

**Comment by sdfg2** [comment, marked as answer]
Answer: set all other weights to zero.

```
match:
    distance_weights:
        source: 0
        artist: 0
        album: 0
        media: 0
        mediums: 0
        year: 0
        country: 0
        label: 0
        catalognum: 0
        albumdisambig: 0
        album_id: 5.0
        tracks: 0
        missing_tracks: 0
        unmatched_tracks: 0
        track_title: 0
        track_artist: 0
        track_index: 0
        track_length: 0
        track_id: 0
```
