### DISCUSSION TITLE
Beets not moving my files

### DISCUSSION THREAD

**Discussion by hamaryns** [beetbox/beets#4494] [Q&A]
Hi, I have a folder which got mixed up with all kinds of tracks.  I let beets sort it out with the group option.  I let it recognize some tracks.  They are categorized.  Beets continues.

However, when I later close it off (with abort, since it is a lot and I want it to continue a next time) and restart the next time, the same songs are still in that folder and recognized all over again etc.  If I wait with the folder open (just let beets stall on a track, I do not answer what to do), I can see the tracks that it just recognized, they are still there, not being moved.
The source and target directory are on an external usb drive.

It used to work fine before, with exactly this command and settings, but with single folders, without the group option.

I attach my config and a log file, hope you can help me solving this issue.

command:
$ beet -vv import -p /media/hendrik2/Scharnier/Muziek\ te\ sorteren/ 2> beet5.log

log file:
[beet5.log](https://github.com/beetbox/beets/files/9599477/beet5.log)

config.yaml:
```yaml
directory: /media/hendrik2/Scharnier/Muziek
library: ~/.beets/musiclibrary.db
import:
    move: yes
log: beetslog.txt
art_filename: $albumartist – $album
plugins: fetchart lastgenre chroma fromfilename mbsync
paths:
    default: Albums/$albumartist/$album%aunique{}/$artist – $title
    singleton: Losse nummers/$artist/$artist – $title
    comp: Compilaties/$album%aunique{}/$artist – $title
acoustid:
    apikey: uqolV41Xwc
```
