### DISCUSSION TITLE
Strange behaviour with `album_id` - need help tracking it down

### DISCUSSION THREAD

**Discussion by sdfg2** [beetbox/beets#4552] [Q&A]
This is a weird one, it's really confusing me and I need a place to start investigating before putting in a bug report.

I've got an album in Lidarr with the MB tags all correct.  I double check the file itself, the tags are correct.

`MusicBrainz Album Id: c68379be-11ee-4fe6-9dc3-6ff25c1a4edf`

In `beets-config.yaml`:

```
# Tagging
match:
    distance_weights:
        source: 0
        artist: 0
        album: 0
        media: 0
        mediums: 0
        year: 0
        country: 0
        label: 0
        catalognum: 0
        albumdisambig: 0
        album_id: 5.0
        tracks: 0
        missing_tracks: 0
        unmatched_tracks: 0
        track_title: 0
        track_artist: 0
        track_index: 0
        track_length: 0
        track_id: 0
```

So it should only use `album_id` for identification.  This works wonderfully in most cases, but in this case I am so very confused:

```
/store/.trans/music/Alter Bridge/AB III (17 items)                                                                                      
Tagging:                                                                                                                                
    Alter Bridge - AB III                                                                                                               
URL:                                                                                                                                    
    https://musicbrainz.org/release/7fad3fc1-ff57-4df8-8a33-c32fae9a580f                                                                
(Similarity: 100.0%) (2010, AU, Roadrunner Records)                                                                                     
 * Coeur d’Alene -> Coeur D'Alene                                                                                                       
Unmatched tracks (3):                                                                                                                   
 ! Zero                 (#15) (4:39)                                                                                                    
 ! Home                 (#16) (3:28)                                                                                                    
 ! Never Born to Follow (#17) (4:06)
```

I have absolutely no idea where it's getting this album ID from.  It cannot be picking it up from the metadata in the files, because it's not in any of them.

I have other albums that this is happening with as well.  Not many, but a few.

Any idea where to start looking for this?
