### DISCUSSION TITLE
beets.media file is deprecated; use mediafile instead

### DISCUSSION THREAD

**Discussion by deepgreens** [beetbox/beets#4578] [Q&A] [answered]
Getting this error when I run an import:

```
`root@beets:/# beet import /music                                                
/usr/lib/python3.9/site-packages/beets/mediafile.py:19: UserWarning: beets.media 
file is deprecated; use mediafile instead                                       
  warnings.warn("beets.mediafile is deprecated; use mediafile instead)`
```

Some other posts about this error seem to be due to the extrafiles plugin, but I would like to use that plugin to move extrafiles over during import. These include multiple pics of liner note booklets, recording details, etc. Everything seems to be working as expected in my test environment but want to figure this out before importing my library. 

I'm running beets in a docker on my synology nas.

Can I safely ignore this error?

**Comment by wisp3rwind** [comment, marked as answer]
Even when you suspect a plugin being the issue, please provide the full context with such issue reports: Unfortunately, I don't have a crystal ball to figure out  your setup here (beets version, plugins, configuration).

That being said, should be safe to ignore, beets re-exports that library to provide some backwards-compatibility for outdated plugins. IIRC, with recent beets, the error message should be more meaningful and tell the actual origin. Otherwise, I can't comment on the safety of `extrafiles`, it hasn't been updated in a while, you'll have to ask the author. Last time I checked for my own usage.

**Reply by deepgreens** [reply]
I'm running beets 1.6.0 and python 3.9.15, according to the beets version command. My config is below. 

```
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web discogs plexupdate duplicates extrafiles inline edit
directory: /music
library: /config/musiclibrary.blb
art_filename: cover
threaded: yes
original_date: no
per_disc_numbering: yes

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    
paths:
    default: $albumartist/$album ($original_year) - $format $bitdepth-$album_samplerate $media [$year $label $albumdisambig$catalognum]%aunique{}/%if{$multidisc,$disc-}$track - $title
    # default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/%asciify{$year - $album ($label) $albumdisambig %aunique{albumdisambig}}/$track - %asciify{$title}
    comp: Various Artists/$album ($year $format $bitdepth-$album_samplerate $media) [$label $albumdisambig $catalognum] %aunique{}/%if{$multidisc,$disc-}$track - $title ($artist)
    albumtype:soundtrack: Soundtracks/$album ($year $format $bitdepth-$album_samplerate $media) [$label $albumdisambig $catalognum] %aunique{}/%if{$multidisc,$disc-}$track - $title ($artist)

    
    
# original paths:
#    default: $albumartist/$album%aunique{} $original_year $label $format/$track - $title
#    singleton: Non-Album/$artist - $title
#    comp: Compilations/$album%aunique{}/$track - $title
#    albumtype_soundtrack: Soundtracks/$album/$track $title 

# Inline plugin template
item_fields:
  multidisc: 1 if disctotal > 1 else 0
  my_samplerate: round(samplerate / 1000)
  #my_samplerate: str(int(samplerate / 1000))
  is_flac: 1 if format == "FLAC" else 0
album_fields:  
  format: |
       formatList = []
       for item in items:
           formatList.append(item.format)
       return formatList
  av_bitrate: |
       total = 0
       for item in items:
           total += item.bitrate
       return round(total / len(items) / 1000)
  album_bitdepth:  |
       total = 0
       for item in items:
           total += item.bitdepth
       return round(total / len(items))
  album_samplerate:  |
       maxsamplerate = 0
       for item in items:
            if item.samplerate > maxsamplerate:
                 maxsamplerate = item.samplerate
       return round(maxsamplerate / 1000)
       #total = 0
       #for item in items:
       #    total += item.samplerate
       #return round(total / len(items) / 1000)
       #return str(int(total / len(items) / 1000))
  is_1644: |
       bd = 0
       sr = 0
       br = 0
       for item in items:
           bd += item.bitdepth
           sr += item.samplerate
           br += item.bitrate
       bd = round(bd / len(items))
       sr = round(sr / len(items) / 1000)
       br = round(br / len(items) / 1000)
       return 1 if bd == 16 and sr == 44 and br > 320 else 0
  display_year: |
       if original_year != year:
          return str(year) + '(' + str(original_year) + ')'
       else:
          return str(year)
        
        
import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album
    count: 3

embedart:
    auto: yes

fetchart:
  auto: yes                  # Enable automatic album art fetching during import.
  cautious: no               # Pick only trusted album art by ignoring filenames that do not contain one of the keywords in "cover_names".
  enforce_ratio: yes         # Only allow images with 1:1 aspect ratio
  minwidth: 1000             # Only images with a width bigger or equal to minwidth are considered as valid album art candidates.
  maxwidth: 3000             # A maximum image width to downscale fetched images if they are too big.
                             # The height is recomputed so that the aspect ratio is preserved.
  sources:                   # An asterisk * expands to all available sources.
    - filesystem             # No remote art sources are queried if local art is found in the filesystem.
    - coverart
    - albumart
#   - fanarttv
    - bandcamp
#  fanarttv_key: REDACTED     # API key to use for the fanart API.
  store_source: yes          # Store the art source (e.g. filesystem) in the beets database as art_source.

#match:
#    #strong_rec_thresh: 0.05      # should be 95% according to docs 0.10 = 90%
#    strong_rec_thresh: 0.15
#    preferred:
#        countries: ['US', 'JP', 'GB|UK']
#        media: ['CD', 'Digital Media|File'] # Use CD fist processing standard rez and Digital Media first for HighRe
#        #media: ['Digital Media|File', 'CD']
#        original_year: no
#    ignored: missing_tracks

match:
    strong_rec_thresh: 0.05
    #medium_rec_thresh: 0.25
    #rec_gap_thresh: 0.25
    #max_rec:
    #    missing_tracks: low
    #    unmatched_tracks: low
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        #media: 1.0
        media: 0.5
        # mediums: 1.0
        mediums: 0.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.1
        albumdisambig: 0.1
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.1
        track_title: 2.0
        track_artist: 2.0
        track_index: 0.3
        track_length: 2.0
        track_id: 0.3
    preferred:
        countries: ['US', 'XE', 'JP', 'GB|UK']
        media: ['CD', 'SACD', 'Digital Media|File'] # Use CD fist processing standard rez and Digital Media first for HighRe
#        #media: ['Digital Media|File', 'CD']
        original_year: no
#    ignored: missing_tracks

musicbrainz:
     extra_tags: [year, country, media]   
    
replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: REDACTED

discogs:
    source_weight: 0.0

plexupdate: 
    host: localhost 
    port: REDACTED
    token: token

extrafiles:
    patterns:
        all: '*.*'

#this plugin does not work dec 22          
#copyartifacts:
#    extensions: .*

# Configure the edit plugin. Defines which fields are available for editing.
# To choose your favorite editor change the $EDITOR environment variable
edit:
  itemfields:
    - album
    - albumartist
    - artist
    - track 
    - title
    - year
  albumfields:
    - albumartist
    - album
    - year
    - albumtype
    
#colours for the ui
ui:
    color: yes
    colors:
        text_success: green
        text_warning: blue
        text_error: red
        text_highlight: blue
        text_highlight_minor: lightgray
        action_default: darkblue
        action: purple

```
