### DISCUSSION TITLE
No results from Discogs on singletons

### DISCUSSION THREAD

**Discussion by ghbrown** [beetbox/beets#4629] [Q&A] [answered]
I don't get any results from the Discogs plugin when running on singletons like `beet import -s track.mp3`.

Does the Discogs plugin have the ability to search for single tracks using the Discogs API? I can enter search mode and successfully find the album to which a track belongs when messing around with `beet import dir_containing_only_track`, but entering search mode from a singleton call (`-s`) doesn't yield any results from Discogs.

I see from the `python3-discogs-client` that tracklist of a release is exposed, so if its not implemented right now I think it should be possible (right?).

My config is below, most notable is probably that **I only receive results from Discogs since I've turned off Musicbrainz**

```yaml

directory: '~/Temporary/Beets Sandbox/Music Library'
library: ~/.config/beets/library.db

plugins: convert discogs fetchart embedart

import:
    move:  yes # move files into destination directory
    write: yes # permit editing of file tags

paths:
  singleton: $artist - $title

convert:
    format: mp3 # convert to MP3
    auto:   yes # automatically convert
    delete_originals: true

musicbrainz:
    enabled: no # disables Musicbrainz for releases after March 2022

discogs:
    source_weight: 0.0
    index_tracks: yes
```
