### DISCUSSION TITLE
please help with config: artist first letter in front of artist folder?

### DISCUSSION THREAD

**Discussion by prankousky** [beetbox/beets#4683] [Q&A] [answered]
Hi everybody,

I have to move my entire audio collection due to a new setup, so I thought I'd change the naming system as well.

### current

pattern `/mnt/nas/audio/beets/<artist>/<album>`
example `/mnt/nas/audio/beets/Misfits/Walk Amoung Us`

### wanted

pattern `/mnt/nas/audio/beets/<artist first letter>/<artist>/<album>`
example `/mnt/nas/audio/beets/M/Misfits/Walk Amoung Us`

Can beets do this? It does **not** have to do this to existing files; I need to copy them manually, so I can create the folder structure myself. But when adding new media, it'd be great if beets could take care of this.

Thank you in advance for your help :)

### ~/.config/beets/config.yaml

```yaml
directory: /mnt/ds918/audio/music/beets
library: ~/.config/beets/library.db
# asciify_paths: yes

import:
  move: yes
  copy: no
  write: yes
  from_scratch: yes

ui:
  color: yes

art_filename: cover

plugins: fetchart embedart fromfilename bandcamp

bandcamp:
  lyrics: true
  art: true

fetchart:
  cautious: true
  cover_names: cover front
  sources: filesystem coverart amazon albumart

embedart:
  auto: yes
  # ifempty: yes

fromfilename:
  auto: yes
```
