### DISCUSSION TITLE
Beets not writing metadata tags to music even thought it's configured to do that and also re-writing metadata when it probably shouldn't

### DISCUSSION THREAD

**Discussion by Stampede** [beetbox/beets#4720] [Q&A]
I'm just starting to import my collection and this is confusing to me. I would like Beets to update the metadata tags in the music files. I'm pretty sure I have it configured to do so, but the files aren't changed until I  `$ beet write`. And the odd thing is that that when I type `$ beet write`, then Beets will re-write metadata to the tracks, even when it had already applied the metadata previously. According to the [docs](https://beets.readthedocs.io/en/stable/reference/cli.html#write), it should not be doing that: 

> By default, this writes the changes only if there is a difference between the database and the tags in the file.

As for Beets not writing metadata during the initial import, I'm running the import in incremental mode and when I want to pause and do something else, I wait for the next prompt from Beets and the choose the a[B]ort option. Maybe "abort" makes it stop without writing metadata? Is there a better way to pause importing to go do something else for while?

To start the import sessions, I first cd into the parent music directory and then run `beet import -i  .`

Here is the import section of my config file. Thanks for any help!

```
import:
    move: no
    copy: no
    log: /home/USERNAME/Music Intake Directory/beet.log
    write: yes
    resume: ask
    incremental: yes
    incremental_skip_later: yes 
```

Other info:
It's been a couple of months, but I'm pretty sure that I installed beets with pip.
```
$ beet --version
beets version 1.6.0
Python version 3.10.6
plugins: bandcamp, chroma, ftintitle, lastgenre, lyrics, zero
```
