### DISCUSSION TITLE
Only tag spesific fields of tracks

### DISCUSSION THREAD

**Discussion by alexe0506** [beetbox/beets#4721] [Q&A]
Hi!

I am completly new to beets and using cmd.
My goal is to use Beetw to update the genre tags of my collection, but not any of the other tags in my music collection.
SInce i am new to this field i am at a lack of what to search for to find any answers to my question and am hoping that any of you can help me. 
My simple config file is pasted under:
```
directory: ~/Music/Musikk
Library: ~Music/Lib/Librarydb

import:
    move: yes
    copy: no
    write: no
    
plugins: discogs lastgenre

discogs:
    source_weight: 0.0
    
lastgenre:
    count: 3
```
