### DISCUSSION TITLE
My path config doesnt work

### DISCUSSION THREAD

**Discussion by alexe0506** [beetbox/beets#4729] [Q&A] [answered]
Hi!

I am having trouble with configuring beets such that the folders are named as i want them.
My goal is to have albumartist/[year] albumartist - album/track - title, but i always get the default albumartist/album/track - title. 
Am i missing a plugin for my config to work or is there some code i need to rewrite? 
My config file is as follows:
```
directory: C:\Users\alex1\Music\beets
Library: C:\Users\alex1\Music\lib\lib.db


original_date: no
per_disc_numbering: yes
resume: ask

import:
    move: yes
    write: yes
    autotag: yes
    duplicate_action: ask
    bell: yes
    log: ~/Music/import.log
    
   
path:
    default: $albumartist/$[$year$] $albumartist - $album%aunique{} ($media $format $mb_albumid})/$track $title
    singleton: Singles/$[$year$] $artist - $title
    comp: Various_Artist/$[$year$] $album%aunique{}/$track $title


plugins: discogs lastgenre

discogs:
    source_weight: 0.0
    
lastgenre:
    auto: yes
    count: 3
    force: force
    source: album
```

**Comment by arogl** [comment]
I think beets might be trying to evaluate these two items ```$[``` and ```$]``` around your ```$[$year$]``` part of the path, and fails, so falls back to the default.

you could try ```\[$year\]``` or even just ```[year]```

my config for paths:
```yaml
paths:
  default: %upper{%asciify{%left{$albumartist,1}}}/$albumartist/($year) $album%aunique{}/$album - $track - $artist - $title
  singleton: Singles/$artist - $title
  albumtype:soundtrack: Soundtracks/($year) $album%aunique{}/$album - $track - $artist - $title
  albumartist:various\ artists: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
  albumartist:various: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
  comp: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
```
