### DISCUSSION TITLE
Organization problems with multiple album artists

### DISCUSSION THREAD

**Discussion by auranunderscore** [beetbox/beets#4777] [Q&A]
(This is a repost from the Discourse because I didn't get much of a response there)
Hi! I’m having some issues with albums that include more than one album artist.
For the sake of an example, I’m going to use the album Pullhair Rubeye by Avey Tare and Kría Brekkan. The files are tagged with both Avey Tare and Kría Brekken as album artists, as shown here in Puddletag:
![image](https://user-images.githubusercontent.com/126738276/235548888-d473c1b4-c144-4a05-999c-ed53d67c2da1.png)
However, when importing the album into my library, it seems to only acknowledge Avey Tare:
![image](https://user-images.githubusercontent.com/126738276/235548912-d3df7829-407d-43d9-a7a2-8fd6a66e7ebc.png)
How do I fix this?
Here’s my config:

```
directory: /media/DRIVE2/organizedmusic
library: ~/Music/musiclibrary.db
asciify_paths: yes
artist_credit: yes
per_disc_numbering: yes
clutter: ["Thumbs.DB","DS_Store",".m3u",".cue",".pls",".jpg",".png",".url",".nfo", "Cover.jpg", "Cover.png"]

#importer options

import:
    move: yes
    autotag: no
    bell: yes

#path format configuration

paths:
    default:  %the{$albumartist}/($year%if{$day,-$month-$day,%if{$month,-$month}}) - $album/%if{$disc,Disc $disc %if{$disctitle,- $disctitle}/,%if{$disctitle,$disctitle/}}%if{$disc,$disc-}$track - $title
    singleton: %the{$albumartist}/($year%if{$day,-$month-$day,%if{$month,-$month}}) - $title/$title
    comp: Various Artists/($year%if{$day,-$month-$day,%if{$month,-$month}}) - $album/%if{$disc,Disc $disc %if{$disctitle,- $disctitle}/,%if{$disctitle,$disctitle/}}%if{$artist,$artist - }%if{$disc,$disc-}$track - $title

#plugins
plugins: the zero

the:
    patterns: [^Os ^As ^O ^A ^El ^La ^Lo ^Los ^Les ^Der ^Die ^Das ^Des ^Dem ^Den ^Le ^La ^Les]

zero:
    keep_fields: day month year genre disc disctitle track title albumartist artist images
    update_database: true
```
