### DISCUSSION TITLE
Beetcamp questions: Capitalize genre names / Catalognumber missing

### DISCUSSION THREAD

**Discussion by JOJ0** [beetbox/beets#4795] [Q&A] [answered]
Hi @snejus, before I open an issue in the beetcamp repo I wanted to make sure it's not user error and clarify what the expected behaviour / current implementation of beetcamp is. Two things:

I'm not yet sure if it's configurable but I see genres coming from beetcamp/bandcamp seem to be all lower case. Genre plugins like `lastgenre` have a capitalize option. This is how genres from bandcamp look for me:

`LMajor - Can't Do It - 01 - Can't Do It (2021/GB)  [] f:FLAC a:23-05/bandcamp |2-step, breaks, jungle, techno`

lastgenre would give me something like this even though it might have received it in non-caps from last.fm: `2-step, Breaks, Jungle, Techno`, providing the `title_case` option is set: https://beets.readthedocs.io/en/stable/plugins/lastgenre.html#configuration

Does such an option exist in beetcamp? If not, I would open a feature request over at the repo and hope someone picks it up :-)

Another thing we see in the output above: I often (but not always) miss the catalog number in bandcamp-tagged albums (The empty square brackets above, the actual catno of this release on Discogs or MusicBrainz is `APHA025`, which means: There is one, it's not a release that doesn't have one - I guess stuff like that exists in the world ;-))

I fear this is due to lacking information in the bandcamp database. Can you confirm this or tell me how to doublecheck if for this particular release (https://lmajormusic.bandcamp.com/album/cant-do-it) bandcamp/the bandcamp api has a catalog number?

**Comment by snejus** [comment, marked as answer]
hi @JOJ0, 

1. Capitalisation: use `bandcamp.genre.capitalize = yes` [configuration option](https://github.com/snejus/beetcamp#genre-new-since-0110)

2. Catalogue numbers: `beetcamp` has a fairly advanced catalogue number parser which checks album name, description, media information and even track titles, but often the catalogue number is simply missing. Have just checked the album page for your example and unfortunately the catalogue number does not get mentioned 😞. `beetcamp` only checks the bandcamp page for information and does not query any external sources.

You can use the `url2json` script [from the repository root](https://github.com/snejus/beetcamp/blob/main/url2json) to obtain the JSON data that it works with
```sh
url2json https://lmajormusic.bandcamp.com/album/cant-do-it
```

you will find that most of that information gets displayed on the screen, and that the catalogue number does not have its own field.

**Reply by JOJ0** [reply]
Oh my gosh! So sorry for not reading your awesome docs in the first place! Those genre features are awesome!

And I just realise that it's even possible to exclude comments tag, which I always cleaned out with a beet mod command manually (seems often there is a whole lot of information about the whole release or label which disturbs beets queries)

Thanks again, awesome stuff 🤩

**Reply by snejus** [reply]
No worries!

Regarding cleaning things up, you may find [beets-importreplace](https://github.com/edgars-supe/beets-importreplace) useful. I have a separate configuration file for it where I do a fair bit of clean-up:

```yaml
# config.yaml
---
directory: /run/media/sarunas/music/Music
library: library.db
include:
  - replacements.yaml
...
```

```yaml
# replacements.yaml
---
.albumreplace: &albumreplace
  "𝙐𝙕𝙑𝘼": "UZVA"
  "𝙏𝙧𝙖𝙣𝙨𝙢𝙪𝙩𝙖𝙧": "Transmutar"
  "₀₃": "03"
  "₀₄": "04"

.artistreplace: &artistreplace
  "Dj ": "DJ "
  ".*Acolytes Of.*": "Acolytes Of Yama"
  1LUU: 1luu
  Alya7h: ALYA7H
  Chane: Chané
  Clair: CLAIR
  "(?i:Die+rich)": "Die+Rich"
  DJLOSER: "DJ LOSER"
  "DJ mantis": "DJ Mantis"
  DJSUPER: "DJ SUPER"
...

importreplace:
  replacements:
    - album_fields: album
      replace:
        <<: *albumreplace
    - album_fields: artist
      replace:
        <<: *artistreplace

    - item_fields: album
      replace:
        <<: *albumreplace
        <<: *artistreplace
    - item_fields: artist
      replace:
        <<: *artistreplace
```
