### DISCUSSION TITLE
%if{} in my path spec not working for multidisc albums

### DISCUSSION THREAD

**Discussion by plenaerts** [beetbox/beets#4806] [Q&A] [answered]
Hi! I can't get beets to move my multidisc album files into 'Disc N' dirs.

I've used the basic FAQ config:
```
plugins: inline
paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
item_fields:
    multidisc: 1 if disctotal > 1 else 0
```

Beet list seems to get it right, including the %if{}:
```
% beet ls -f '$album - %if{$multidisc,Multi} - $disc/$disctotal - $track - $title' elisabeth disc+ track+
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 01/03 - 01 - Piano Concerto no. 3 in D minor, op. 30: I. Allegro ma non tanto
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 01/03 - 02 - Piano Concerto no. 3 in D minor, op. 30: II. Intermezzo. Adagio
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 01/03 - 03 - Piano Concerto no. 3 in D minor, op. 30: III. Finale. Alla breve
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 01/03 - 04 - Rotations ндрей Владимирович Никольский
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 02/03 - 01 - Piano Concerto no. 2 in G minor, op. 16: I. Andantino - Allegretto
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 02/03 - 02 - Piano Concerto no. 2 in G minor, op. 16: II. Scherzo. Vivace
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 02/03 - 03 - Piano Concerto no. 2 in G minor, op. 16: III. Intermezzo. Allegro moderato
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 02/03 - 04 - Piano Concerto no. 2 in G minor, op. 16: IV. Finale. Allegro tempestoso
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 02/03 - 05 - Rotations Johan
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 03/03 - 01 - Concerto for Piano and Orchestra no. 4 in G major, op. 58: I. Allegro moderato
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 03/03 - 02 - Concerto for Piano and Orchestra no. 4 in G major, op. 58: II. Andante con moto
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 03/03 - 03 - Concerto for Piano and Orchestra no. 4 in G major, op. 58: III. Rondo. Vivace
The Queen Elisabeth International Music Competition of Belgium: Piano 1987 - Multi - 03/03 - 04 - Rotations 仲道郁代
```

But then beet move does nothing:
```
% beet move elisabeth
Moving 0 items (13 already in place).
```

And files remain in one directory:
```
% beet ls -p elisabeth
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/01 Concerto for Piano and Orchestra no. 4 in G major, op. 58_ I. Allegro moderato.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/02 Concerto for Piano and Orchestra no. 4 in G major, op. 58_ II. Andante con moto.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/03 Concerto for Piano and Orchestra no. 4 in G major, op. 58_ III. Rondo. Vivace.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/04 Rotations 仲道郁代.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/01 Piano Concerto no. 3 in D minor, op. 30_ I. Allegro ma non tanto.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/02 Piano Concerto no. 3 in D minor, op. 30_ II. Intermezzo. Adagio.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/03 Piano Concerto no. 3 in D minor, op. 30_ III. Finale. Alla breve.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/04 Rotations ндрей Владимирович Никольский.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/01 Piano Concerto no. 2 in G minor, op. 16_ I. Andantino - Allegretto.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/02 Piano Concerto no. 2 in G minor, op. 16_ II. Scherzo. Vivace.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/03 Piano Concerto no. 2 in G minor, op. 16_ III. Intermezzo. Allegro moderato.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/04 Piano Concerto no. 2 in G minor, op. 16_ IV. Finale. Allegro tempestoso.flac
<libdir>/Compilations/The Queen Elisabeth International Music Competition of Belgium_ Piano 1987/05 Rotations Johan.flac
```

Why might the %if{} in my path spec not be matching the CLI list behaviour?

**Comment by govynnus** [comment]
Hello!

I really have no idea, that snippet works perfectly in my config. The only thing I can think of is to check that `paths` is not being overwritten later in the file.

**Reply by plenaerts** [reply]
Well, this is my whole config file below. Is there any other info I can provide?

```
% less config.yaml 
plugins: fetchart missing lastgenre web inline 

directory: <libdir removed>
library: ~/.config/beets/library.db

import:
  move: yes

fetchart:
  cautious: true
  cover_names: front back
    #  sources: *

web:
  host: 0.0.0.0

# See https://beets.readthedocs.io/en/stable/faq.html?highlight=multiple%20disc#create-disc-n-directories-for-multi-disc-albums
# Use a subdirectory for albums with multiple discs.
per_disc_numbering: yes
paths:
  default: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
item_fields:
  multidisc: 1 if disctotal > 1 else 0

# Refer to https://beets.readthedocs.io/en/stable/plugins/missing.html
# Shows missing files from albums.
missing:
  format: $albumartist - $album - $title
  count: no
  total: no
```
