### DISCUSSION TITLE
beet import and 'ignore_video_tracks’ behavior

### DISCUSSION THREAD

**Discussion by apnea** [beetbox/beets#4911] [Q&A] [answered]
Hi all,

Just came across beets and was blown away by the complex flavor and deep red color of this super food. I mean the sheer scope and flexibility of this super tool. Testing it out on a minimal set up before let loose for real I noticed the following:

config (v 1.6.0):

```
directory: /media/foo/music
library: /home/foo/.config/beets/library.db

import:
    move: yes
    copy: no
    write: no
    ignore_video_tracks: no
```

So, beet import is ignoring an album ripped into ogg format. `  -vv`  and `logfile` options are not  providing any info or errors. After much faffing around with forum posts, permissions, file name character escaping etc. it occurred to me to look into the ogg container, and sure enough it has a video stream in it (the album cover)…

When I remove the theora stream with ffmpeg so only the vorbis stream remains in the ogg container beets is happy.

Reading docs again, there is the [‘ignore_video_tracks’](https://beets.readthedocs.io/en/stable/reference/config.html?highlight=video#ignore-video-tracks) option, but setting that to ‘no’ still ignores the offending ogg files. What about mkv? If I put both streams, or just the audio stream, into an mkv container both versions also get ignored.

So I’m a bit confused now. Removing the video streams is not an issue as it’s very fast and and simple, but am I mssing something here?

Thanks a lot for looking!
