### DISCUSSION TITLE
Might be a feature request for new ui

### DISCUSSION THREAD

**Discussion by arogl** [beetbox/beets#4959] [General]
Currently when I have multiple matches for an album, it prints the album over 3 lines, rather than the previous 1 line.

Is it possible to replace that functionality?

I have added the following to my `config.yaml`, basically the defaults but a very wide cmd line:

```yaml
ui:
  color: yes
  colors:
    text_success: ['bold', 'green']
    text_warning: ['bold', 'yellow']
    text_error: ['bold', 'red']
    text_highlight: ['bold', 'red']
    text_highlight_minor: ['white']
    action_default: ['bold', 'cyan']
    action: ['bold', 'cyan']
    # New colors after UI overhaul
    text: ['normal']
    text_faint: ['faint']
    import_path: ['bold', 'blue']
    import_path_items: ['bold', 'blue']
    added:   ['green']
    removed: ['red']
    changed: ['yellow']
    added_highlight:   ['bold', 'green']
    removed_highlight: ['bold', 'red']
    changed_highlight: ['bold', 'yellow']
    text_diff_added:   ['bold', 'red']
    text_diff_removed: ['bold', 'red']
    text_diff_changed: ['bold', 'red']
    action_description: ['white']
  terminal_width: 200
```
