### DISCUSSION TITLE
Check secondary albumtype for paths config

### DISCUSSION THREAD

**Discussion by celynw** [beetbox/beets#4978] [Q&A] [answered]
I have an album which has `ep; soundtrack` in the albumtypes field (from MusicBrainz).
The albumtypes plugin seems to consider the primary albumtype, and so the album is treated as an EP, despite my setting for soundtracks.

```yml
paths:
  default: $albumartist/$year - $album%aunique{}/%if{$multidisc,$paddisc-}$padtrack $title
  albumtype:soundtrack: Soundtracks/$album/%if{$multidisc,$paddisc-}$padtrack $title
```

Is there a way to apply a paths rule if, for instance, ANY of the album types are soundtrack?
I'd be happy to try tackling this myself, but I'm not convinced there's not already a way to do it.

**Comment by wisp3rwind** [comment, marked as answer]
No idea whether this has a chance of working (since I didn't actually follow the `albumtypes` development), but maybe simply querying the `albumtypes` field instead could work:

```yaml
paths:
  default: $albumartist/$year - $album%aunique{}/%if{$multidisc,$paddisc-}$padtrack $title
  albumtype:soundtrack: Soundtracks/$album/%if{$multidisc,$paddisc-}$padtrack $title
  albumtypes:soundtrack: Soundtracks/$album/%if{$multidisc,$paddisc-}$padtrack $title
```
