### DISCUSSION TITLE
Extrafiles and item-fields multidisc not working together

### DISCUSSION THREAD

**Discussion by paulmcrules** [beetbox/beets#4985] [Q&A]
Hi, just wondering if anyone could help me fix this.

So I had extrafiles working perfectly but when adding item_fields in, it stops copying the files over. As soon as I comment these two lines out it works again. Do you think there is a fix or will I just have to lose one feature and go with the more convenient one?

Here is the part of my config file which deals with both:
```
extrafiles:
    patterns:
        all: ['*.log', '*.cue', '*.m3u', '*.LOG', '*.CUE', '*.M3U']

paths:
    default: $albumartist/$albumartist - $original_year - $album%aunique{} [$media] [$format $samplerate $bitdepth-bit] ($catalognum)/%if{$multidisc,Disc $disc/}$track - $title
    singleton: $artist/$title [$media] [$format $samplerate $bitdepth]
    comp: VA/$original_year - $albumartist - $album%aunique{} [$media] [$format $samplerate $bitdepth-bit] ($catalognum)/%if{$multidisc,Disc $disc/}$track - $title
    albumtype_soundtrack: Soundtracks/$original_year - $album%unique{} [$media] [$format $samplerate $bitdepth-bit] ($catalognum)/%if{$multidisc,Disc $disc/}$track - $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0
```

I am running beets from linuxserver docker image:
```
beets version 1.6.0                                                                                   
Python version 3.11.6                                                                                 
plugins: chroma, convert, discogs, embedart, extrafiles, fetchart, inline, lastgenre, replaygain, scru
b, web
```

And my whole config just in case this helps:

```
plugins: [fetchart, embedart, convert, scrub, replaygain, lastgenre, chroma, web, extrafiles, discogs, inline]
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

#convert:
#    auto: no
#    ffmpeg: /usr/bin/ffmpeg
#    opts: -ab 320k -ac 2 -ar 48000
#    max_bitrate: 320
#    threads: 1
    
extrafiles:
    patterns:
        all: ['*.log', '*.cue', '*.m3u', '*.LOG', '*.CUE', '*.M3U']

paths:
    default: $albumartist/$albumartist - $original_year - $album%aunique{} [$media] [$format $samplerate $bitdepth-bit] ($catalognum)/%if{$multidisc,Disc $disc/}$track - $title
    singleton: $artist/$title [$media] [$format $samplerate $bitdepth]
    comp: VA/$original_year - $albumartist - $album%aunique{} [$media] [$format $samplerate $bitdepth-bit] ($catalognum)/%if{$multidisc,Disc $disc/}$track - $title
    albumtype_soundtrack: Soundtracks/$original_year - $album%unique{} [$media] [$format $samplerate $bitdepth-bit] ($catalognum)/%if{$multidisc,Disc $disc/}$track - $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0

import:
    write: yes
    copy: yes
    resume: yes
    delete: yes
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log
    bell: yes

clutter: ["Thumbs.DB", ".DS_Store"]
ignore: [".*", "*~", "System Volume Information", "lost+found"]
ignore_hidden: yes

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    
replaygain:
    auto: no

scrub:
    auto: yes

match:
    preferred:
        media: cd

per_disc_numbering: yes
va_name: "Various Artists"

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

discogs:
    source_weight: 0.0

musicbrainz:
    source_weight: 0.5

web:
    host: 0.0.0.0
    port: 8337

ui:
    terminal_width: 80
    length_diff_thresh: 10.0
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
```
