### DISCUSSION TITLE
organize songs under artist/albums/?

### DISCUSSION THREAD

**Discussion by Szparki** [beetbox/beets#5009] [Q&A] [answered]
I'd like organize songs under albums, but how?

Expected output:
Artist/Album/track title

Actual output:
Artist/track title

I wonder what am I doing wrong? I tried two different settings, I got the same result with both. As steps, after updating config.yaml I ran `beet update` or even tried re-importing the full directory `beet import -A ~/music/`
I'm also attaching two screen shots with the output.

config.yaml - v1
```
directory: ~/beets
library: ~/beets/data/musiclibrary.db

plugins: discogs inline

discogs:
   source_weight: 0.0

paths:
    #default: $albumartist/$album%aunique{}/$track $title
    default: $albumartist/$album/$track $title
    singleton: Non-Album/$artist/$album/$title
    comp: Compilations/$album%aunique{}/$track $title
```
config.yaml - v2
```
directory: ~/beets
library: ~/beets/data/musiclibrary.db

plugins: discogs

discogs:
   source_weight: 0.0

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$album/$title
    comp: Compilations/$album%aunique{}/$track $title
```

![Screenshot 2023-11-26 at 21 15 58](https://github.com/beetbox/beets/assets/8669658/52d6e051-e52d-4980-8acf-3cea6ff99e35)
![Screenshot 2023-11-26 at 21 16 11](https://github.com/beetbox/beets/assets/8669658/d6703323-bd86-442e-9a44-9465450e32eb)

**Comment by arsaboo** [comment]
Can you try `default: /$albumartist/$album/$track $title`?

Also, `beet update` does not move the files. You should use `beet move` after changing the paths.

**Reply by Szparki** [reply]
This moved most of the songs under one directory, the ones under "____", indeed have no ID3 tags, I'm not worried about them.

```
directory: ~/beets
library: ~/beets/data/musiclibrary.db

#plugins: discogs

discogs:
   source_weight: 0.0

paths:
    default: /$albumartist/$album/$track $title
    singleton: Non-Album/$artist/$album/$title
    comp: Compilations/$album%aunique{}/$track $title
```
```
~ ❯ beet move                                                                                                                                   4s 18:56
Moving 2199 items (4493 already in place).
~ ❯ ls beets                                                                                                                                  
Compilations _            ___          data
~ ❯ ls beets/Compilations                                                                                                                                
It Ain't Safe No More
~ ❯ ls beets/Compilations/It\ Ain\'t\ Safe\ No\ More| egrep "mp3|m4a"|wc -l                                                                              
    4616
```
Some have no albums, most do:
```
~/beets/Compilations/It Ain't Safe No More ❯ id3tool * | grep Album | more
Album:          Themes
Album:          Tekno 34
Album:          Man in the rain
Album:          Dj Ionel's Collections
Album:          Viva la fiesta '99
Album:
Album:          Stray Tracks
Album:          Event of Excellence (Live)
Album:          Event of Excellence (Live)
Album:          Ali G Indahouse OST
Album:          Themes
Album:          Cats OST
Album:          Timisoara
Album:
Album:          Page Of Life
Album:          Page Of Life
Album:          Moonlight Shadow
Album:
Album:          The City
Album:          American Life
Album:          Tracy Chapman
Album:
Album:          Song of baby Jane
Album:          Live bites
Album:          Nem vagyok tokeletes
Album:          Evergreen Melodies VI
Album:          Love Deluxe
...
```

![Screenshot 2023-11-28 at 18 58 33](https://github.com/beetbox/beets/assets/8669658/ccf6c0b4-adc8-466d-ae6d-a04ee31136c2)
 
Note: I commented out _discogs plugin_ because:
```
~ ❯ beet move                                                                                                                                            18:47
** error loading plugin discogs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/beetsplug/discogs.py", line 24, in <module>
    from discogs_client import Release, Master, Client
ModuleNotFoundError: No module named 'discogs_client'
```
But I don't think this is the issue. 

btw, beet version:
```
~ ❯ beet --version                                                                                                                                       19:02
beets version 1.6.0
Python version 3.11.6
no plugins loaded
```

**Reply by DjSlash** [reply]
Better not to start the path with an slash, I *think* it's fine, but just to be on the safe side I wouldn't use it.

But these results are way off. Does `beet config` reflect the configuration file as you have pasted here?

What does `beet ls -f "$album -$albumartist - $artist - $data_source - $path" album:Themes` output?

**Reply by arsaboo** [reply]
Can you also update beets. You will have to install it directly from GitHub

**Reply by Szparki** [reply]
I removed the slash, thank you @DjSlash 

```
~ ❯ beet config                                                                                                                                       
directory: ~/beets
library: ~/beets/data/musiclibrary.db
discogs:
    source_weight: 0.0

paths:
    default: $albumartist/$album/$track $title
    singleton: Non-Album/$artist/$album/$title
    comp: Compilations/$album%aunique{}/$track $title
```

The output of `beet ls -f "$album -$albumartist - $artist - $data_source - $path" album:Themes `, is a longer one, I created a bastebin for it: https://pastebin.com/2zLmHs46.
I also created a [pastebin](https://pastebin.com/) for `beet ls`

@arsaboo just to check if I got it right, instead of installing it with pip I should [install it from source](https://beets.readthedocs.io/en/latest/faq.html#run-the-latest-source-version-of-beets) (2)? - Install from source
