### DISCUSSION TITLE
Copy, Auto Tag, Convert, Delete Copied Data, Add Converted Data to Library

### DISCUSSION THREAD

**Discussion by ayushnix** [beetbox/beets#5083] [Q&A] [answered]
I’m trying to convert my FLAC music files to OPUS. I want to auto-tag the OPUS files and add those OPUS files to my beets library. However, I’m not able to configure beets to do this.

Here’s the `config.yaml` file that I’m using:

```yaml
---
library: "~/.local/share/beets/library.db"
directory: "/data/music/opus"
asciify_paths: true

import:
  write: true
  copy: true
  move: false
  log: "~/.cache/beets/import.log"

musicbrainz:
    extra_tags: [year]
    https: yes

plugins: [convert]
convert:
    auto: true
    format: opus
    formats:
        opus:
            command: opusenc --quiet --bitrate 160 --vbr $source $dest
            extension: opus
    never_convert_lossy_files: true
    dest: "/data/music/opus"
```

My FLAC music collection is in the `/data/music/flac` directory. I want to
1. copy the FLAC albums inside `/data/music/flac` to `/data/music/opus`
2. convert the those copied files to OPUS
3. auto-tag those OPUS files
4. add those OPUS files to my library `directory`
5. remove the copied FLAC files in `/data/music/opus`

Alternatively,
1. copy the FLAC albums inside `/data/music/flac` to `/data/music/opus`
2. auto-tag those FLAC files
3. convert those FLAC files to OPUS files
4. add those OPUS files to my library `directory`
5. remove the copied FLAC files in `/data/music/opus`

Is it possible to configure beets to do this in a single beets command?
