### DISCUSSION TITLE
beet write not working?

### DISCUSSION THREAD

**Discussion by krp312** [beetbox/beets#5093] [Q&A]
Greetings,

I have files affected by [this issue](https://github.com/beetbox/beets/issues/4528) so I've attempted the [manual intervention](https://github.com/beetbox/beets/pull/4582/#issuecomment-1445023493).

For the track _Adding N To X_, here are the values for `albumtype` and `albumtypes` in beets' db (the selected row):

<img width="1462" alt="Screenshot 2024-02-01 at 9 51 15 AM" src="https://github.com/beetbox/beets/assets/16083866/2050d609-9828-4a08-91de-ddf89684f442">

I issue the write, but it doesn't work:

```
abc@DockSTARTer:/$ beet info -i 'albumtype,albumtypes' 'title:adding n to x'
/storage/music/library/Add N to (X)/Add Insult to Injury/01 - Adding N To X.flac
 albumtype: a
albumtypes: a; l; b; u; m
abc@DockSTARTer:/$ beet write 'title:adding n to x'
Add N to (X) - Add Insult to Injury - Adding N To X
  albumtype: a -> album
  albumtypes: ['a', 'l', 'b', 'u', 'm'] -> album
abc@DockSTARTer:/$ beet info -i 'albumtype,albumtypes' 'title:adding n to x'
/storage/music/library/Add N to (X)/Add Insult to Injury/01 - Adding N To X.flac
 albumtype: a
albumtypes: a; l; b; u; m
abc@DockSTARTer:/$
```

Here's my config:

```
plugins: fetchart scrub lastgenre web deezer info embedart chroma duplicates mbsync
directory: /storage/music/library
library: /config/musiclibrary.blb
threaded: yes
original_date: no
per_disc_numbering: no

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

fetchart:
    auto: yes
    minwidth: 500
    cautious: yes

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337

deezer:
    source_weight: 0.0

embedart:
    auto: no
```

I'm using [Beets via dockstarter](https://dockstarter.com/apps/beets/), which uses [this image](https://hub.docker.com/r/linuxserver/beets) (latest v1.6.0).

Any help is greatly appreciated. Many thanks in advance.
