### DISCUSSION TITLE
Ignore existing tags, file and folder names when tagging- only use acoustic id

### DISCUSSION THREAD

**Discussion by LordJABA** [beetbox/beets#5109] [Q&A]
Some time ago autottagging messed up my library. Folders, filenames and tags are completely wrong. Can I force beets to completely ignore them and use only acoustic id ? Any suggestion that takes existing things to account will be wrong.
I was thinking about just making all the names of files and folders a random strings but there must be a better way

Edit: Also I rarely have more than one song from an album - will this complicate it?

**Comment by LordJABA** [comment]
Tried removing the tags, moving all the files to one folder and renaming the files with random uuid
in effect beets still seems to ignore the audio and suggest the closest uuid to the random file name from music brains library

**Comment by arsaboo** [comment]
I just want to make sure that you have installed and configured the `chromaprint` plugin. Does it show up in logs? You can increase the penalty for other attributes using `distance_weights` (see discussion [here](https://github.com/beetbox/beets/discussions/4297)).

**Comment by arogl** [comment]
@LordJABA What plugins are enabled? Can you list out that part of your config, and if you have changed any of the `distance_weights` as @arsaboo has indicated

**Comment by LordJABA** [comment]
```
cat .config/beets/config.yaml
directory: /mnt/hdd/music/
library: ~/musiclibrary.blb
import:
  write: yes
  copy: no
  move: yes
  fromfilename: no
plugins: discogs chroma fetchart embedart lastgenre duplicates
fetchart:
  auto: yes
embedart:
  auto: yes
match:
  strong_rec_thresh: 0.1  # Lower value means stricter matching
chroma:
    auto: yes

```

tried with only chroma plugin and with/without strong_rec_thresh
using -s in command
