### DISCUSSION TITLE
hook plugin basics

### DISCUSSION THREAD

**Discussion by JOJ0** [beetbox/beets#5137] [Q&A] [answered]
Hi,
embarrassing but it's the first time I'm using the hooks plugin :-O

I simply want to write something after an album has been imported:

```
hook:
    hooks:
      - event: album_imported
        command: >
            echo {album.id} >> /Users/jojo/tmp.x
```

The problem is, I kind of only get the echo in my beets output, but the file tmp.x is not written:

```
➜ [A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates, Print tracks,
Open files with Picard? a
7 >> /Users/jojo/tmp.x
```

I'm using zsh, and I suppose this is some kind of yaml/shell/escaping problem, but I don't see it ATM.

Help! :-)
Cheers!

**Comment by arsaboo** [comment, marked as answer]
try:

```yaml
hook:
  hooks:
    - event: album_imported
      command: "sh -c 'echo {album.id} >> /Users/jojo/tmp.x'"
```

**Reply by JOJ0** [reply]
Thank you so much @arsaboo, that was driving me crazy! Did some more experiments and I think most importantly the `sh -c` and wrapping into single quotes does the trick:

```
hook:
    hooks:
      - event: album_imported
        command: >
            sh -c 'echo {album.id} >> /Users/jojo/tmp.x'
```
or

```
        command: sh -c 'echo {album.id} >> /Users/jojo/tmp.x'
            
```

Thanks again! I can finally move on with my idea here .... :-)
