### DISCUSSION TITLE
Apply actions not definitive?

### DISCUSSION THREAD

**Discussion by n1els** [beetbox/beets#5143] [Q&A]
I'm building my library with beets at the moment, and while playing around with various plugins to get more metadata and so on I noticed that every time I run

`beet import -s -L -p`

There are a number of songs that keep asking me for confirmation no matter how many times I confirm that I want to apply or take any other kind of action.

`/media/music/Library/House/&ME - Garden - 122 320kbps 44kHz.mp3
Tagging track: &ME - Garden
URL:
    https://open.spotify.com/track/00cJqEccK1XmxioVYcbQPs
(Similarity: 88.0%) (index, source) (Spotify)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort,
Print tracks, eDit, edit Candidates?`

In the example above, the match on spotify is correct. I am not sure why it only scores 88% similarity, but I would like to commit to this match and not have beets ask me again about this file, unless something about it has changed.

I'm running repeated imports and beet update commands, as well as others while getting genre identification and tagging to work correctly so I am not sure if I am inadvertently triggering beets to keep ask me about the same songs every time. 

When I run exactly the same command after it finishes the first time, it starts immediately by asking me about the same song again.

**Comment by arsaboo** [comment]
I'm not sure what you are trying to do here, but your flags do not look right. `-s` is for singleton imports, which should only be used as a last resort (you should normally import albums); `-L` reimports from the library; and `-p` is for pretend, so nothing gets written. 

If you are just trying to import your library, start with `beet import`. To get the confirmation prompt, add the `-t` flag (for timid).

**Comment by n1els** [comment]
Thanks for the quick response, I have just started out with beets so it is very likely that I am doing multiple things wrong. I have mostly single tracks as opposed to albums and `beet help import` shows that `-p` is the short form of the `--resume` flag (although I have seen `-p` used to mean pretend mode in other commands), see output and version below.

I need to use resume because gstreamer, which is used by bpmanalyser and replaygain, keeps crashing after about a hundred or so tracks. I'm using this library as a base library for DJ'ing, so right now I have just shy of 7K tracks in either MP3, Flac or AIFF format and they are almost exlusively single tracks. 

My goal is, after the first large batch import is complete, to have an input directory with music. The contents of this directory will then be moved to the library during import. The genre is part of the file structure, and bpm and quality data is part of the file name. It seems to me therefore that after the initial import a second move or update or import -L cycle is needed in order to reflect the newly discovered metadata in the path and filenames.


config.yaml:
```
directory: /media/music/Library
library: /media/music/musiclibrary.db
plugins: duplicates embedart fetchart inline convert web chroma fromfilename info lyrics replaygain describe discogs bpmanalyser edit spotify bandcamp mbsubmit lastgenre beatport4

edit:
  itemfields: track title artist album genre
  albumfields: album albumartist

chroma:
  auto: yes

discogs:
  source_weight: 0.5
  index_tracks: yes

spotify:
    source_weight: 0.4
    mode: list
    show_failures: on
    tiebreak: first

fromfilename:
  source_weight: 0.5

beatport4:
    art: yes
    art_overwrite: no
    username: REDACTED
    password: REDACTED
bpmanalyser:
  auto: yes
  dry-run: no
  write: yes
  threads: 2
  force: yes
  quiet: no

autobpm:
  auto: yes
  overwrite: yes

bandcamp:
  include_digital_only_tracks: true
  search_max: 4
  art: yes
  comments_separator: "\n---\n"
  exclude_extra_fields: []
  genre:
    capitalize: yes
    maximum: 0
    always_include: []
    mode: progressive

lastgenre:
  auto: no
  canonical: yes
  count: 1
  fallback: ''
  force: yes
  min_weight: 10
  prefer_specific: no
  source: track
  whitelist: /media/music/genre.whitelist
  title_case: yes

duplicates:
  album: no
  move: /media/music/duplicates
  count: yes
  path: yes
  checksum: ffmpeg -i {file} -f crc -

mbsubmit:
  format: $track. $title - $artist ($length)
  threshold: medium

embedart:
  auto: yes

fetchart:
  auto: yes

lyrics:
  auto: yes

replaygain:
  backend: gstreamer
  auto: yes

web:
  host: 0.0.0.0
  port: 8337

import:
  write: yes
  move: yes
  resume: yes
  log: /media/music/beets.log
  languages: en nl
  bell: yes
  quiet_fallback: asis

match:
  strong_rec_thresh: 0.06

paths:
  default: $genre/$artist - $title - $bpm $bitrate $samplerate
  singleton: $genre/$artist - $title - $bpm $bitrate $samplerate
  comp: $genre/$artist - $title - $bpm - $bitrate $samplerate
```
```
music@music:/media/music/Library$ beet help import
Usage: beet import [options]

Options:
  -h, --help            show this help message and exit
[...]
  **-p, --resume          resume importing if interrupted**
  -P, --noresume        do not try to resume importing
  -q, --quiet           never prompt for input: skip albums instead
[...]
  -s, --singletons      import individual tracks instead of full albums

[...]
  --pretend             just print the files to import
[...]
```

```
music@music:/media/music/Library$ beet version
beets version 1.6.0
Python version 3.10.12
plugins: bandcamp, beatport4, bpmanalyser, chroma, convert, describe, discogs, duplicates, edit, embedart, fetchart, fromfilename, info, inline, lastgenre, lyrics, mbsubmit, replaygain, spotify, web
```
