### DISCUSSION TITLE
What to do with  V.A_ , Various Artists,  Compilations ,  Various folders ?

### DISCUSSION THREAD

**Discussion by nodecentral** [beetbox/beets#5146] [Q&A] [answered]
Hi I was just going through the resulting music folder Beets created after weeks of importing and I can see some strange ‘compilation’ groupings - is this normal..

* V.A_
* Various Artists
* Compilations
* Various

As my OCD is now kicking in, is there something I can do to get them all into the one folder?  I don’t think I can I just lift and shift as it would likely effect the Beets library. 

Any advice really appreciated.

**Comment by arsaboo** [comment]
You probably use `$artist` or `$albumartist` in our path. Since those fields have many variations, this is expected. I organize my music using the first alphabets of the album.

**Reply by nodecentral** [reply]
Hi @arsaboo , thanks for responding, although I’m not sure what you mean ?

**Comment by benpage2** [comment, marked as answer]
To expand on @arsaboo 

The folders are organized based on the `paths:` in your config. You can find info on it here: https://beets.readthedocs.io/en/v1.6.0/reference/config.html#path-format-configuration

The default values are as follows:
```
paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
```
In short, the albums are placed into these paths based on the values the auto-tagger grabbed. Most albums will be filed based on the "default" path format `default: $albumartist/$album%aunique{}/$track $title`. This will make folders by the albumartist tag, then subfolders for each album tag. So, if you use $albumartist in your path format and the autotager threw "Various Artists" in the $albumartist field then it will get filed in a "Various Artists" folder

There is also a specific path for compilations included by default `comp: Compilations/$album%aunique{}/$track $title` since compilations usually have various artists. Although, the docs point out that albums only get placed here when $comp field is set to "True". I know from experience that this isn't always the case for compilations or other albums with V.A. 

Your options are to manually set the comp field to "true" for each album you want there using `beet modify` or you can change your path formats.

I decided to change my path formats and did the following:
```
paths:
    default: $albumtype/$albumartist/$album%aunique{}/$track $title
    singleton: non-album/$albumartist/$year/$title
    comp: $albumtype/$albumartist/$album%aunique{}/$track $title
```

I doubt my config will solve the problem as you want it to be, but once you get the hang of it you can organize stuff any way you like.

Hope this helps

**Reply by nodecentral** [reply]
Thanks for the additional clarity @benpage2

**Comment by adamjakab** [comment]
Hi @nodecentral,

Here are some more examples to help you with organizing your folders:
```
# See also "inline" plugin configuration for custom fields
paths:
  albumartist:"Various Artists": V/Various Artists/$album/${disc_num_prefix}${track}. ${title}
  singleton: V/Various Artists/$album/${disc_num_prefix}${track}. ${title}
  comp: V/Various Artists/$album/${disc_num_prefix}${track}. ${title}
  default: $initial_letter/%the{$albumartist}/$album%aunique{}/${disc_num_prefix}${track}. ${title}
```
I force all my various artists stuff in "V/Various Artists" folder together with singletons and compilations.
Check especially the first line. The key `albumartist:"Various Artists":` will use that naming pattern on all music files were you set the album artist to "Various Artists". You can set up multiple rules to do the same for "VA" and similar.
I hope this helps.
