### DISCUSSION TITLE
Working Command to convert to AAC

### DISCUSSION THREAD

**Discussion by sly-fox-git** [beetbox/beets#5154] [Q&A]
I want to convert FLAC files in my beets library to aac m4a 320 kb 

I cannot figure out a working command for the Convert plugin. Converting 

```
formats:
    aac:
      command: ffmpeg -i $source -codec:a aac -b:a 320k $dest
      extension: m4a
```

Edit: I think I figured out a working solution. With this config, the default conversion becomes aac 256 bitrate

```
convert:
  auto: no
  embed: yes 
  no_convert: path::\.(m4a)$
  never_convert_lossy_files: yes
  dest: "/music/converted"
  max_bitrate: 256
  threads: 4
  command: ffmpeg -i $source -y -vn -acodec aac -ab 256k $dest
  extension: m4a
```
