### DISCUSSION TITLE
Auto Approve

### DISCUSSION THREAD

**Discussion by TheMarstonConnell** [beetbox/beets#5199] [Ideas]
Piggybacking off of #3522, I'd like to see something more automatic than even quiet mode, realistically it would be great to have a flag like `-q` that auto approved everything instead of skipping it. Say, any album with over 80% confidence would be automatically approved instead of skipped.

**Comment by Serene-Arc** [comment]
This is possible using the configuration! What you want here are the options in the [autotagger](https://beets.readthedocs.io/en/stable/reference/config.html#autotagger-matching-options) section of the docs, specifically `strong_rec_thresh`, `medium_rec_thresh`, and `rec_gap_thresh`.

If you're looking for the everything over 80% match to be accepted, and everything else to be skipped, then you're configuration would look like this:

```yaml
import:    
  none_rec_action: skip    

match:    
  strong_rec_thresh: 0.20    
  medium_rec_thresh: 0.00    
  rec_gap_thresh: 0.80    
```

When you run this on quiet mode with the `-q` flag, it will accept everything that has an 80% match or higher, and everything else will be skipped. This is because of the `none_rec_action`, and that the strong match threshold is set to 0.2, so 80% or higher.
