### DISCUSSION TITLE
How do people create paths for libraries with album artists with non-Latin characters and names that start with "The"?

### DISCUSSION THREAD

**Discussion by shimizurei** [beetbox/beets#5209] [Q&A]
```yaml
paths:
    # DEFAULT: A/Artist/Album [YEAR]/Disc 01/01-01. Track Name.ext
    default: %bucket{$albumartist,alpha}/$albumartist/$album%aunique{} %if{$year,($year),0000}$atypes/%if{$multidisc,Disc $disk_num/}$disc_and_track $title
```

Let's say I have the artists

- 和楽器バンド ==> Romanized: Wagakki Band
- Angela Aki
- The Beatles
- 汪東城 ==> Romanized: Jiro Wang
- GYROAXIA

to be sorted.

How does the program sort them into buckets?

My ideal:

- A => Angela Aki
- B => The Beatles
- G => GYROXIA
- J => Jiro Wang
- W => Wagakki Band
