### DISCUSSION TITLE
Path config for custom field + albumtype

### DISCUSSION THREAD

**Discussion by BigBoyBarney** [beetbox/beets#5245] [Q&A] [answered]
Hey guys!

I'm trying to sort all songs with the custom field `Category` in this case, which works using
```crystal
paths:
	category:nikke: Nikke OST/$albumartist/$album%aunique{}/$track $title
```
However, this pools Singles with them as well.
Normally, I have:
```crystal
paths:
	albumtype:single: $albumartist/Singles/$album%aunique{}/$track $title
```
to sort singles into a `Singles` folder.

------
My question would be, how would I achieve this with the Category tag?
I tried the following, but it moved everything to `Singles`, as apparently `%if` only checks whether a field is empty or not.
```crystal
paths:
    category:nikke: Nikke OST/$albumartist/%if{$albumtype=single,Singles/}$album%aunique{}/$track $title
```

Thanks in advance!!

**Comment by DjSlash** [comment, marked as answer]
`%if` checks if the condition is nonempty or nonzero if the condition is a number.

use the `inline` plugin:
```yaml
album_fields:
  isSingle: 0 if albumtype != single else 1

paths:
    category:nikke: Nikke OST/$albumartist/%if{$isSingle,Singles/}$album%aunique{}/$track $title
```
