### DISCUSSION TITLE
Why would inline run no matter whether condition is true or false?

### DISCUSSION THREAD

**Discussion by swills1** [beetbox/beets#5263] [Q&A] [answered]
I have the followig and it should only add [RE-year] if year is greater than original_year. However, it adds [RE-year] to the path even when the year and original_year match.

```
# inline
inline:
  album_fields:
    rerelease: 1 if $year > $original_year else 0

# tagging
paths:
  default: %the{$albumartist}/$album - [$original_year] [$catalognum] [$media-$format] [${bitdepth}bit] %if{$rerelease, [RE-$year]}/$albumartist - $album - $track - $title
```

**Comment by swills1** [comment]
It behaves the same way when trying to detect multi disc. If there is one disc, this still puts the files in a disc sub folder.
```
# inline
inline:
  album_fields:
    rerelease: 1 if $year > $original_year else 0
  item_fields:
    multidisc: 1 if disctotal > 1 else 0

# tagging
paths:
  default: %the{$albumartist}/$album - [$original_year] [$label] [$catalognum] [$media-$format] [${bitdepth}bit]/%if{$multidisc,$disc/}$albumartist - $album - $track - $title
```

**Comment by DjSlash** [comment]
> `rerelease: 1 if $year > $original_year else 0`

should be: `rerelease: 1 if year > original_year else 0`

But I don't see why it adds the disc sub folder. Seems to me it should work like expected.

**Reply by swills1** [reply]
Tried that already and no go. See `multidisc`. It doesn't have `$` and also ignores the else.

**Comment by DjSlash** [comment]
Could you paste the output of `beet config`?

**Reply by swills1** [reply]
I took the inline pieces out of my path format.

```
library: library.db
directory: \\REDACTED\main\Media\Music\Music

statefile: state.pickle

plugins: the filetote inline rewrite discogs
pluginpath: []

import:
    write: yes
    copy: yes
    move: no
    timid: no
    quiet: no
filetote:

    paths:
        pattern:scans: $albumpath/scans/$old_filename
        pattern:cue: $albumpath/${album}_cue
        pattern:log: $albumpath/${album}_log
        pattern:m3u: $albumpath/${album}_m3u
    patterns:
        scans: ['[sS]cans/']
        cue: ['*.cue']
        log: ['*.log']
        m3u: ['*.m3u']
    session:
        operation:
        beets_lib:
        import_path:
    extensions: ''
    filenames: ''
    exclude: ''
    pairing:
        enabled: no
        pairing_only: no
        extensions: .*
    print_ignored: no
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    separator: ', '
    index_tracks: no
rewrite:
    media Digital Media: Web
inline:
    album_fields:
        rerelease: 1 if year > original_year else 0
    item_fields:
        multidisc: 1 if disctotal > 1 else 0

paths:
    default: '%the{$albumartist}/$album - [$original_year] [$label] [$catalognum] [$media-$format] [${bitdepth}bit]/$albumartist - $album - $track - $title'
pathfields: {}
item_fields: {}
album_fields: {}
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
```
