### DISCUSSION TITLE
Duplicates plugin: Output duplicated files in groups

### DISCUSSION THREAD

**Discussion by add-n2x** [beetbox/beets#5271] [Q&A] [answered]
The duplicates plugin outputs a list of files, like this:

```bash
$ beet duplicates  --full --strict
/music/track_1.mp3
/music/track_1_copy.mp3
/music/track_1_copy_2.mp3
/music/different_track_a.mp3
/music/different_track_a_copy.mp3
```

Now I want to build some script, to decide which of the duplicates to keep or not. To process the duplicates, I need some sort of grouping or delimiter between duplicate blocks.

For example rendering duplicates as JSON arrays would help a lot:

```json
[[
  "/music/track_1.mp3",
  "/music/track_1_copy.mp3",
  "/music/track_1_copy_2.mp3"
],
[
  "/music/different_track_a.mp3",
  "/music/different_track_a_copy.mp3"
]]
```

Or some other kind of raw group delimiter like `###` would also be sufficient:

```bash
/music/track_1.mp3
/music/track_1_copy.mp3
/music/track_1_copy_2.mp3
###
/music/different_track_a.mp3
/music/different_track_a_copy.mp3
```

Is there some simple way to achieve this?

**Comment by add-n2x** [comment]
Now, I tried the idea to kinda fake a grouping, using a custom format which includes the MusicBrainz ID:

```shell
$ beet ls -f '$mb_trackid $path'
763cbf0a-ec5d-4739-87fb-c03306c0b65a /music/Venetian Snares/rossz csillag allat szuletett/oengyilkos vasarnap.mp3
```

But it looks like this does not work on the duplicates plugin:

```shell
$ beet duplicates  -f '$mb_trackid $path'
/music/Venetian Snares/rossz csillag allat szuletett/oengyilkos vasarnap.mp3
```

Any tips are highly appreciated!

**Reply by arogl** [reply]
Try setting in `config.yaml`

```yaml
duplicates:
  album: no
  checksum: ffmpeg -i {file} -f crc -
  copy: none
  count: no
  delete: no
  format: $album - $track - $artist - $title
  full: no
  strict: no
  move: none
  keys: [ffmpeg]
  #    keys: [mb_trackid, mb_albumid]
  path: no
```

**Reply by add-n2x** [reply]
Thank you @arogl.

This is not exactly what I was aiming for. Since it outputs each duplicate in the same format, it makes identifying groups of duplicates not possible. Also I need the path for identification of duplicates in Navidrome. This I'm planing to do with some external script. 

But your example on the config options for the duplicates plugin hinted some possible direction. This is what I'm currently using:

```yaml
duplicates:
  album: no
  copy: none
  count: no
  delete: no
  format: $mb_trackid - $mb_albumid | $path
  full: yes
  strict: yes
  move: none
  keys: [mb_trackid, mb_albumid]
  path: no
  group: no
```

This outputs duplicated tracks like that:

```bash
$ beet dup
763cbf0a-ec5d-4739-87fb-c03306c0b65a - dc350920-b1fd-4b70-b2c5-96fc8eba944a | /music/Venetian Snares/rossz csillag allat szuletett/oengyilkos vasarnap.mp3
763cbf0a-ec5d-4739-87fb-c03306c0b65a - dc350920-b1fd-4b70-b2c5-96fc8eba944a | /music/Venetian Snares/Rossz csillag alatt született [2]/03 Öngyilkos vasárnap.mp3
```

These are not real separated groups of duplicates though, but with the printed IDs I can build the aggregations using my external script.

Another options could be extending the Beets Duplicates Plugin with some grouping and JSON output logic.
