### DISCUSSION TITLE
Renaming songs with __

### DISCUSSION THREAD

**Discussion by willtham1** [beetbox/beets#5286] [Q&A] [answered]
I love this script 10/10 but real quick. I have songs that I get from soundcloud and when i import them its renaming them with __ in front of there name. What does that typically mean and can i prevent this.
In-addition all those songs from soundcloud have metadata only for title.

```
directory: ~D:\Music
import:
    move: yes
    copy: no
    write: no

paths:
    default: $albumartist/$album%aunique{}/$title
    singleton: Non-Album/%if{$albumartist,$albumartist,$artist}/$title
    comp: Compilations/$album%aunique{}/$title


## Resources
# https://github.com/beetbox/beets/discussions/5009
```
Heres an example of one of my song
`__Travis Scott - Butterfly Effect (Jamek Ortega Remix)`

Thank you in advance!

**Comment by DjSlash** [comment]
Without knowing your config nor how the songs are called, my best guess would be that the artist/title contains characters that are being [replaced](https://beets.readthedocs.io/en/stable/reference/config.html#replace).

**Reply by willtham1** [reply]
Ooops heres a bit more
```
directory: ~D:\Music
import:
    move: yes
    copy: no
    write: no

paths:
    default: $albumartist/$album%aunique{}/$title
    singleton: Non-Album/%if{$albumartist,$albumartist,$artist}/$title
    comp: Compilations/$album%aunique{}/$title


## Resources
# https://github.com/beetbox/beets/discussions/5009
```
