### DISCUSSION TITLE
No Release option (Release Group only) on import?

### DISCUSSION THREAD

**Discussion by michaelkrieger** [beetbox/beets#5355] [Ideas]
Picard has the 'no_release' plugin.  Its documentation states "_do not store specific release information in releases of unknown origin_". 
 Effectively, after tagging, this strips a list of tags, by default: asin,barcode,catalognumber,label,media,releasecountry,releasestatus when it is flagged as such.

In some cases you have a release but don't know its origin.  You want to sort it, but you don't really know if it's a digital download, CD release, vinyl rip, US or UK or Canadian or Japanese version.  But it most certainly is a 15-track version of the album within the release group.

Is there any way to accomplish this in Beets?

I don't want to guess, but do want to get the metadata from the release itself and tag the RELEASE_GROUP without tagging the RELEASE itself.

**Comment by RollingStar** [comment]
I don't think it exists, but I've wanted it.

**Comment by Serene-Arc** [comment]
I don't think this is possible in the current beets tool. Perhaps you could open an enhancement request?

**Reply by michaelkrieger** [reply]
Where would I do that?  I assumed this "Ideas" discussion was just that?

I guess the idea is to add a prompt on import that may show the available matching releases (vs just the album) if there are multiple ones and one of the options will be "unknown" release of album ____ based on ____, which would then clear those specific release information items (but leave the release group), but use the information to tag.

Bonus points if it uses a ripping log file in the same folder to determine the [disc ID](https://musicbrainz.org/doc/Disc_ID_Calculation) and use that to match confidence and skip the prompt if there is only one matching discID.

**Comment by kergoth** [comment]
This is a good suggestion. Of course you can always do it after import with `beet modify`. I use the [alias](https://github.com/kergoth/beets-alias) plugin to have a `beet norelease` command for this. But having it on import would absolutely be more convenient. I'd expect someone could potentially create a plugin for this functionality.

**Reply by michaelkrieger** [reply]
> This is a good suggestion. Of course you can always do it after import with `beet modify`. I use the [alias](https://github.com/kergoth/beets-alias) plugin to have a `beet norelease` command for this. But having it on import would absolutely be more convenient. I'd expect someone could potentially create a plugin for this functionality.

I would love to see the function your alias calls if you’re willing to share it @kergoth

**Reply by kergoth** [reply]
Of course. I don't often use it, so let me know if any of the fields are missing, but this is [what I have now](https://github.com/kergoth/Beets-Library/blob/main/config.d/plugins/mine.yaml#L322):

```yaml
aliases:
  # Useful in cases where the precise release is unknown, or is not in
  # MusicBrainz yet.
  norelease:
    help: Strip release-specific tags
    command: modify 'asin!' 'isrc!' 'barcode!' 'catalognumber!' 'label!' 'media!' 'releasecountry!' 'releasestatus!' 'mb_albumid!' 'mb_workid!' 'mb_trackid!' 'mb_releasetrackid!' 'mb_releasegroupid!'
```
