### DISCUSSION TITLE
A Couple of Small Questions

### DISCUSSION THREAD

**Discussion by 2cin** [beetbox/beets#5384] [Q&A] [answered]
Hey yall! I'm brand new-ish to beets and have been recently trying to import my 1TB collection. I started with a small batch to try things out and I have a couple questions about some cases I ran into. Apologizes if there are easy answers for any of these again I'm quite new and I've done my best to search the docs and the various discussion boards around but came up without answers so I'm asking here. I will say that other than these small cases beets has been working excellently so far and has been very accurately scanning my collection! (Note: see my config at the bottom in case my settings have anything to do with what I'm seeing)

Question 1 - When running mbsync featured (“Feat. “) artists are added back despite ftintitle plugin being enabled. After running ftintitle these are fixed but is there a way to just prevent this as not to waste time running the two commands?

Question 2 - On the topic of ftintitle it seems to not work when there are multiple artists. For example I am still left with

Blood Orange feat. A$AP Rocky & Project Pat

Relevant metadata example and MusicBrainz page

https://musicbrainz.org/release-group/f72eb094-2b00-417c-a598-553143cd91b0

How my metadata looks

ARTISTS                                  : Summrs
ALBUMARTISTS                             : Summrs
ARTISTS_SORT                             : Summrs
ALBUM_ARTISTS                            : Summrs
ARTISTS_CREDIT                           : Summrs
ALBUMARTISTS_SORT                        : Summrs
ALBUMARTISTS_CREDIT                      : Summrs
Artist Credit                            : Summrs feat. 279tyler & Ethan2K
ALBUMARTISTSORT                          : Summrs feat. 279tyler & Ethan2K
Performer                                : Summrs feat. 279tyler & Ethan2K
Performer/Sorted by                      : Summrs feat. 279tyler & Ethan2K
Album/Performer                          : Summrs feat. 279tyler & Ethan2K
Album Artist Credit                      : Summrs feat. 279tyler & Ethan2K

Is this intentional? If so is there a way to change this automatically or do I just need to keep an eye out for it and manually change it?

Question 3 - When using “bad” to check for bad files any file without MD5 STREAMINFO will result in a warning being printed

“WARNING, cannot check MD5 signature since it was unset in the STREAMINFO”

This fills up a lot of my collection (probably from downloading from streaming like Qobuz). Is there a way to either

A. Add these MD5 signatures?
B. Ignore these errors and focus on all the other ones?

Question 4 - Is there a way to “resync” or do some sort of sanity check on the database? I know about “beet rm” however lets say I remove a folder from my set directory (For context I do an import from a file path and have beets move all the files to an organized directory. I understand if this isn’t possible in which case I’ll stick with “beet rm”) is there a way to do a rescan to update the database to reflect these changes?

Question 5 - Instead of skipping a lot of my albums that were not in MusicBrainz, I opted for “Use As Is”. Is there a way to go back to just these imported albums sometime in the future? I’d like to if possible submit these albums to MusicBrainz via “mbsubmit” (preferably automated going through each to get their raw track parser data). Additionally is there a way to submit the fingerprints if I have chroma enabled?

CONFIG:

```
directory: /web/music/musicclean
library: ~/beets/musiclibrary.db

plugins: chroma badfiles albumtypes fetchart embedart lastgenre ftintitle replaygain the mbsync

paths:
    default: %the{$albumartist}/$album%aunique{} ($year) [$format]/$track - $title
    singleton: %the{$artist}/_Singles/$title
    albumtype:soundtrack: _Soundtracks/$album%aunique{} ($year) [$format]/$track - %the{$artist} - $title
    comp: _Compilations/$album%aunique{} ($year) [$format]/$track - %the{$artist} - $title

import:
    move: yes

chroma:
    auto: yes

fetchart:
    art_filename: cover.png
    maxwidth: 3000
    minwidth: 100
    quality: 100
    high_resolution: yes
    sources: filesystem coverart itunes amazon albumart lastfm
    lastfm_key: 172e9f58c42e056c6bc31e08096ead04
    cover_format: PNG

embedart:
    auto: yes
    maxwidth: 500

lastgenre:
    count: 100
    min_weight: 1
    source: track

replaygain:
    backend: ffmpeg
```
