### DISCUSSION TITLE
mp3val equivalent for m4a?

### DISCUSSION THREAD

**Discussion by Gwouigwoui** [beetbox/beets#5417] [Q&A]
Hi!
Is there an equivalent to mp3val for m4a files?
Thanks!

**Comment by kergoth** [comment]
I don't know if it's correct, but I copied this from someone:

```yaml
badfiles:
  check_on_import: yes
  commands:
    m4a: ffmpeg -v error -f null - -i
    mp4: ffmpeg -v error -f null - -i
    ogg: oggz-validate
```
