### DISCUSSION TITLE
convert: does auto_keep ignore all other options?

### DISCUSSION THREAD

**Discussion by frigginbrownie** [beetbox/beets#5427] [Q&A] [answered]
Hey y'all,

Big fan of beets. Am working on moving my music to a NAS and refactoring how I store my music. My want is:

1. One database, storing the highest quality version that I have.
2. If the file is lossy, import into beets and copy to the \music directory.
3. If the file is lossless, import into beets, copy to the \lossless-music directory, and convert to lossy into the \music directory (for easy playback on devices which don't support higher bitrates/codecs and archiving purposes).

I've played around with the config file for a few days and have half a solution - using the convert plugin with auto: no, auto_keep: yes, and default path set to \music. Importing flac files results in the lossless version being imported into beets, copied to \lossless-music, and converted into a lossy version stored in \music (perfect!). However, lossy files are still being converted by convert on import, resulting in \music having duplicate versions of lossy files.

I've tried setting never_convert_lossy_files and no_convert, but these don't seem to be followed if auto_keep is set to yes.

So.. is something wrong with my config file? Is this a bug regarding the convert plugin? Am I doing something with beets that can't be done? 

Included is a snip of my config file and what my current output is. Thanks for any suggestions in advance.

config.yaml:
```
directory: /audio
library: /config/musiclibrary.db
threaded: yes
asciify_paths: yes
original_date: yes
per_disc_numbering: yes

import:
    write: yes
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet-import.log
    
default: music/%bucket{%left{$albumartist,1}}/$albumartist/%title{%asciify{$album%aunique{} ($year)}}/%if{$multidisc,$disc-}$track - %title{$title}
format:flac: lossless-music/%bucket{%left{$albumartist,1}}/$albumartist/%title{%asciify{$album%aunique{} ($year)}}/%if{$multidisc,$disc-}$track - %title{$title}
    
 convert:
    auto: no
    auto_keep: yes
    copy_album_art: yes
    dest: /audio
    ffmpeg: /usr/bin/ffmpeg
    paths:
        default: music/%bucket{%left{$albumartist,1}}/$albumartist/%title{%asciify{$album%aunique{} ($year)}}/%if{$multidisc,$disc-}$track - %title{$title}
    never_convert_lossy_files: no
    no_convert: format:MP3
    threads: 5
    format: mp3
    formats:
        mp3:
            command: ffmpeg -i $source -c:a libmp3lame -q:a 0 -ar 48000 $dest
            extension: mp3
```

importing "My Artist - My Album [FLAC] (2024)"
```
\audio\lossless-music\M\My Artist\My Album (2024)\
    - 01 - My Song.flac
    - 02 - My Other Song.flac
 
 \audio\music\M\My Artist\My Album (2024)\
    - 01 - My Song.mp3
    - 02 - My Other Song.mp3
```

importing "My Artist - My Album [MP3] (2024)"
```
 \audio\music\M\My Artist\My Album (2024)\
    - 01 - My Song.mp3
    - 01 - My Song.1.mp3
    - 02 - My Other Song.mp3
    - 02 - My Other Song.1.mp3
````
