### DISCUSSION TITLE
How to have beets segregate files based on albums.

### DISCUSSION THREAD

**Discussion by EchoShauf** [beetbox/beets#5435] [Q&A] [answered]
Hello, I have music that are categorized as best top hits of August, September, etc, Basically its a compilation of hits on a specific month or time. 

These music files are in no way related to each other and is basically just done as a repack because of the monthly compilation. 

When I import this using Beets import "C:\Users\Jericho\Downloads\Music\Best Hits of August". It gives me an option saying it could not detect album and suggest me to keep as a group , as is, as tracks. This only happens when I import folders like these.

How do I have beets, read everything as tracks, and automatically make a folder with the correct album the track is in and not have everything just under one folder. 

picture included below. 
 
<img width="852" alt="{7229CF29-40E6-4DF0-9B7F-45A7A054D337}" src="https://github.com/user-attachments/assets/98180ff1-0b8f-4f60-a14b-e73f1a6bd9e1">

**Comment by arogl** [comment]
You could use as-is, but you may want to add some meta data to the files for album and year so that beets can then put all the files into the folder.

You may just want to define a path like:

```yaml
paths:
  default: ($year) $album/$artist - $title
```

It all depends on how you want your music stored.

**Reply by EchoShauf** [reply]
Sorry, I tried the as is but it put everything in one folder saying non album. what I want is something like this picture below.  Where some of these songs also came from a collection of sort but it individually put them in their own folder like Artist>Album>Track while writing the metadata and albumart. 

just cant figure out why some folders like the monthly ones are all in one album called non album or i guess singletons? if that is the right term. 

<img width="332" alt="{F0F9F366-76EB-45DE-830F-EF0EF9839D85}" src="https://github.com/user-attachments/assets/9341d4d6-4dbf-4a63-b9bf-977177f20f64">



```
plugins: fetchart embedart info scrub edit fromfilename chroma web missing lastgenre duplicates
directory: D:\Beets\Music
library: C:\Users\Jericho\AppData\Roaming\beets\library.db
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no
verbose: 0
asciify_paths: no
max_filename_length: 0

ignore_hidden: yes

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title
 

import:
    write: yes
    copy: yes
    move: no
    link: no
    delete: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
    autotag: yes
    duplicate_action: ask
    
      

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    cautious: yes
    cover_names: cover front art album folder back
    minwidth: 0
    enforce_ratio: 5%
    sources: filesystem coverart amazon albumart
    google_key: None.
    store_source: no

replaygain:
backend: gstreamer
auto: no

scrub:
    auto: yes

missing:
    count: no
    total: no
    album: no

duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''

pathfields: {}
album_fields: {}

edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''

web:
    host: 0.0.0.0
    port: 8337
    
    ```
