### DISCUSSION TITLE
Adding to Grouping & Comments tag within Itunes/Apple Music

### DISCUSSION THREAD

**Discussion by coldjim** [beetbox/beets#5438] [Q&A]
Hi,
I am finally getting around to sorting my music collection, and I am messing with Beets to get this done on my Unraid server (runs in docker).

I understand it to an extent, and have got it working well for paths, embedding data from Discogs/Bandcamp & others.

However for the life of me, i can't figure out how to embed metadata into the Grouping & Comments fields so this show up in Itunes/Apple Music under those fields.

Ideally I would like the Record Label & Catalog number to appear under Grouping, and not figured out what i want under comments yet but i want to make use of it.

It works under the software, MP3TAG, when I add this so i can't see why Beets can't do this automatically? I don't want to make this a manual process.

Any help i'd appreciate, thanks!

My current config file looks like this:

```yaml
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

plugins: web discogs bandcamp fetchart embedart smartplaylist permissions albumtypes

albumtypes:
    types:
        - album: 'Album'
        - ep: 'EP'
        - single: 'Single'
        - soundtrack: 'Soundtracks'
        - live: 'Live'
        - compilation: 'Compilation'
        - remix: 'Remix'
        - DJ-mix: 'DJ-mix'
        - Mixtape/Street: 'Mixtape'
        - Demo: 'Demo'
    ignore_va: compilation
    bracket: '[]'

permissions:
    file: 644
    dir: 755

smartplaylist:
    relative_to: /music
    playlist_dir: /music
    forward_slash: no
    playlists:
        - name: _all.m3u
          query: ''

discogs:
   source_weight: 0.0
   append_style_genre: true

bandcamp:
  include_digital_only_tracks: true
  search_max: 2
  art: yes
  comments_separator: "\n---\n"
  exclude_extra_fields: []
  genre:
    capitalize: no
    maximum: 0
    always_include: []
    mode: progressive # classical, progressive or psychedelic

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    
paths:
    default: Artists/%left{$albumartist,1}/$albumartist/EP/$album%aunique{} [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    album: Artists/%left{$albumartist,1}/$albumartist/Album/$album%aunique{}  [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    single: Artists/%left{$albumartist,1}/$albumartist/Single/$artist - $title
    ep: Artists/%left{$albumartist,1}/$albumartist/EP/$album%aunique{} [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    live: Artists/%left{$albumartist,1}/$albumartist/Live/$album%aunique{} [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    remix: Artists/%left{$albumartist,1}/$albumartist/Remix/$album%aunique{} [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    DJ-Mix: Artists/%left{$albumartist,1}/$albumartist/DJ-Mix/$album%aunique{} [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    Mixtape/Street: Artists/%left{$albumartist,1}/$albumartist/Mixtape/$album%aunique{} [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    Demo: Artists/%left{$albumartist,1}/$albumartist/Demo/$album%aunique{} [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    compilation: Compilations/$album%aunique{} [%if{$label,%if{$catalognum,$label - $catalognum,$label},$catalognum}] ($year)/$track - $title
    soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log
    from_scratch: yes

lastgenre:
    auto: yes
    source: track

embedart:
    auto: yes

fetchart:
    auto: yes
    
replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337
```
