### DISCUSSION TITLE
Sort singletons into first charatcer folders

### DISCUSSION THREAD

**Discussion by tarz4n** [beetbox/beets#5444] [Q&A]
Two questions i hope to get some help with:

Im sorting my collection of singletons into first letter. How can i set it to always sort into an upcase first letter, and prevent having folders called both "A" and "a" ?

`    singleton: %left{$artist,1}/$artist - $title | $year, $genre`

Also, im looking into grouping anything else (0-9) into the folder "#" can this be done?

**Comment by arogl** [comment]
> Two questions i hope to get some help with:
> 
> Im sorting my collection of singletons into first letter. How can i set it to always sort into an upcase first letter, and prevent having folders called both "A" and "a" ?
> 
> ` singleton: %left{$artist,1}/$artist - $title | $year, $genre`
> 
> Also, im looking into grouping anything else (0-9) into the folder "#" can this be done?

Try this
` singleton: %upper{%left{$artist,1}}/$artist - $title | $year, $genre`

And look at the [bucket](https://beets.readthedocs.io/en/stable/plugins/bucket.html) plugin.
or via the [inline](https://beets.readthedocs.io/en/stable/plugins/inline.html)

```yaml
plugins: inline

item_fields:
  dirfield: |
    nme = artist[0].upper()
    if artist[0].isdigit(): 
      nme = "#"
    return nme

paths:
 singleton: $dirfield/$artist - $title | $year, $genre
```
or 
```yaml
plugins: inline

item_fields:
  dirfield: |
    nme = artist[0].upper()
    if artist[0].isdigit(): 
      if int(artist[0]) in range(0,9):
        nme = "#"
    return ```yaml
plugins: inline

item_fields:
  dirfield: |
    return "#" if artist[0].isdigit() else artist[0].upper()

paths:
 singleton: $dirfield/$artist - $title | $year, $genre
```

play around with the inline code above, I may have it wrong.
