### DISCUSSION TITLE
Beet dosent recognise my config file

### DISCUSSION THREAD

**Discussion by amitbrown21** [beetbox/beets#5466] [General]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (beet config -e
error: Could not edit configuration: [Errno 2] No such file or directory)
```

### Setup

* OS: Windows 11 pro
* Python version: 3.11
* beets version: 2.00
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: F:\Tagged
library: ~/data/musiclibrary.db
import:
    write: yes
    move: yes
plugins: inline convert web
lyrics: yes
```
