### DISCUSSION TITLE
How does the languages setting work?

### DISCUSSION THREAD

**Discussion by Gwouigwoui** [beetbox/beets#5489] [Q&A]
Hi! I have in my config file
```
import:
  write: yes
  copy: no
  move: no
  resume: ask
  incremental: yes
  languages: fr en
  bell: yes
```
When importing [this](https://musicbrainz.org/release/2314a71a-0769-4f9f-8480-c23c59995c11) album, beets wants to write the artists' names in arabic script.

The alias of the artists is non-localised, as it's written the same in multiple countries. The aliases style guidelines states that "the locale should not be more specific than it needs to be", so in that case no countries are tied to the alias.

In that situation, how do I tell beets to write the names in latin script?

Thanks!

**Comment by snejus** [comment]
Have just tried importing this album: to confirm, I am indeed seeing arabic script:

![image](https://github.com/user-attachments/assets/82d39970-4c14-4e88-8552-eab9508576e6)

On the other hand, confusingly, if I press **C** and inspect the data (see [edit](https://beets.readthedocs.io/en/stable/plugins/edit.html) plugin), I see that artist names are in latin script:

```yaml
album: Iran 3 & 4
album_id: ''
albumartist: Mahmud Karimi Et Mohammad Musavi
albumstatus: Official
albumtype: album
albumtypes: album
artist: Mahmud Karimi Et Mohammad Musavi
artist_sort: Karimi, Mahmoud Et Musavi, Mohammad
...
```

If I go ahead and import it, I see that all data has been written in latin script:

```yaml
$ beet info mahmud
              album: Iran 3 & 4
        albumartist: Mahmud Karimi Et Mohammad Musavi
 albumartist_credit: Mahmud Karimi Et Mohammad Musavi
   albumartist_sort: Karimi, Mahmoud Et Musavi, Mohammad
       albumartists: Mahmud Karimi; Mohammad Musavi
albumartists_credit: Mahmud Karimi; Mohammad Musavi
  albumartists_sort: Karimi, Mahmoud; Musavi, Mohammad
        albumstatus: Official
          albumtype: album
         albumtypes: album
           arranger: 
                art: True
             artist: Mahmud Karimi Et Mohammad Musavi
      artist_credit: Mahmud Karimi Et Mohammad Musavi
        artist_sort: Karimi, Mahmoud Et Musavi, Mohammad
            artists: Mahmud Karimi; Mohammad Musavi
     artists_credit: Mahmud Karimi; Mohammad Musavi
       artists_sort: Karimi, Mahmoud; Musavi, Mohammad
            barcode: 859778991221
           bitdepth: 0
            bitrate: 128000
       bitrate_mode: CBR
                bpm: 123
         catalognum: 558562/63
        catalognums: 558562/63
           channels: 2
               comp: False
            country: FR
               date: 1981-06-01
               disc: 1
          disctitle: Iran 3
          disctotal: 2
       encoder_info: 
   encoder_settings: 
             format: MP3
               isrc: TCAHM2374419
              label: Ocora
           language: fra
          languages: fra
             length: 249.6261224489796
             lyrics: 
   mb_albumartistid: bd23b25e-0838-4a50-9e93-1e879471855e
  mb_albumartistids: bd23b25e-0838-4a50-9e93-1e879471855e; b0949d88-55b7-4214-b868-6c4867e0fa54
         mb_albumid: 2314a71a-0769-4f9f-8480-c23c59995c11
        mb_artistid: bd23b25e-0838-4a50-9e93-1e879471855e
       mb_artistids: bd23b25e-0838-4a50-9e93-1e879471855e; b0949d88-55b7-4214-b868-6c4867e0fa54
  mb_releasegroupid: a85c8aa2-6a3e-4d10-83f0-c5793a90eb27
  mb_releasetrackid: 77435a1b-e526-47f1-bb84-23d3895a7f69
         mb_trackid: 31be928a-edfc-421f-88de-113c64956fd2
              media: 12" Vinyl
              month: 6
      original_date: 1981-06-01
     original_month: 6
      original_year: 1981
         samplerate: 44100
             script: Latn
              title: Dashti
              track: 1
         tracktotal: 3
               year: 1981
```

Could you check whether you're seeing the same behaviour? I've got these languages in my configuration:

```yaml
import:
  ...
  languages:
    - jp
    - en
  ...
```

I'm not entirely sure why does the importer print the artist in arabic script - that's very confusing.
