### DISCUSSION TITLE
Multiple attributes paths (i.e Bad:1 and singleton)

### DISCUSSION THREAD

**Discussion by laurent-lao** [beetbox/beets#5497] [Q&A] [answered]
Hi,

I am trying to use the flexible attributes feature to create a separate folder for songs I dislike, but still want to keep.

The use of `beet modify bad=1 christmas` and

```
paths:
    bad:1: Bad/$artist/$title
```

will correctly move songs containing `christmas` in the title to the `Bad` folder.

However, I wish to keep the same structure of "bad" `singleton` in `Bad/Non-Album/`, "bad" `compilation` in `Bad/Compitations`, and "bad" `albumtype:soundtrack` in `Bad/Soundtracks`.

Is there anyway of specifying multiple attributes for a path? I tried `bad:1+singleton: Bad/Non-Album/$artist - $title`, but it did not work.

What I am currently doing is using separate flexible attributes like `beet modify bad-singleton=1 $nameOfSong`, but that wouldn't work for a general query like `christmas` which would have some singletons, some from compilations and some from soundtracks.

Thank you for your help

**Comment by snejus** [comment, marked as answer]
Yes, it is possible to do so using [inline](https://beets.readthedocs.io/en/latest/plugins/inline.html) plugin and template functions. Try the following configuration


```yaml
...
plugins:
  ...
  inline
...
item_fields:
  # use 'globals().get' to default to '0' for items which do not have 'bad' set
  is_bad: return globals().get("bad", "0") == "1"
paths:
  # use '%if{cond,then,else}' path function with the variable above
  # to conditionally set the path. You can leave 'else' empty in this case
  singleton: "%if{$is_bad,Bad/}Non-Album/$artist/$title"
  compilation: "%if{$is_bad,Bad/}Compilations/$artist/$title"
  ...
...
```

* `inline` plugin allows you to define custom variables under `item_fields` configuration
* define a custom boolean variable `is_bad` which checks whether `bad` is set to **1** for an item 
* conditionally prepend **Bad/** to your paths with `%if{$is_bad,Bad/}` making use of the `%if{cond,then,else}` template function
