### DISCUSSION TITLE
How to use beets to manage music on an iPod?

### DISCUSSION THREAD

**Discussion by rnkn** [beetbox/beets#5506] [Q&A] [answered]
I just got an iPod classic and installed Rockbox, which allows music management with just the file system. At the moment I'm using rsync to transfer music, but I'd love to use beets.

I tried `beet mv -cd /path/to/IPOD/music QUERY` but that changes the `path` in the database to the iPod, which is not good.

Another option is to use `beet convert` but I don't actually want to convert the files (the iPod uses USB 2.0 which is already slow enough).

Can anyone think of a way I can use beets to manage music on my shiny new iPod?

**Comment by InvisibleFunction** [comment, marked as answer]
I've got a bigger library than can fit on my ipod, so I use alternatives and convert like so:

```
convert:
  format: aac
  formats:
    aac:
      command: ffmpeg -i $source -y -vn -c:a aac_at -ar 44100 -sample_fmt s16 -b:a 160k $dest
      extension: m4a
alternatives:
  ipodmini:
    directory: /Volumes/SSD/iPod
    formats: aac mp3
    query: "ipodmini:true"
    removeable: true
```

I tag everything I want on there with ipodmini:true then it will convert it all and I put it on there with whatever iTunes is called now.
