### DISCUSSION TITLE
How do I make a smart playlist on beets that's compatible with navidrome on windows?

### DISCUSSION THREAD

**Discussion by robuck86** [beetbox/beets#5522] [Q&A] [answered]
I've been trying to create a smart playlist that works in navidrome. I can create the playlists, but I can't figure what path I'm supposed to be using.  Does anyone know how to do it?

My music is in this path:
`T:\navidrome\music\beets\`
I've tried a bunch of things, but this is the not-working config I have now.
```
smartplaylist:
    relative_to: T:/navidrome/music
    playlist_dir: T:/navidrome/music
    forward_slash: yes
```

and an example of the error I get in navidrome logs: 

`level=warning msg="Path in playlist not found" path="/music/beets/XMAS/The Three Tenors/The Three Tenors Christmas/La Virgen lava pañales.mp3" playlist=xmas`
