### DISCUSSION TITLE
Beets doesn't use Chroma or FromFilename to match track

### DISCUSSION THREAD

**Discussion by Ifiht** [beetbox/beets#5530] [Q&A]
I've been trying to import my music library for years, and keep coming back to beets but every time the import fails on the very first song:

```
Match (79.8%):
  +44 - When Your Heart Stops Beating
  ≠ tracks, label
  MusicBrainz, Digital Media, 2006, US, Interscope Records, None, None
  https://musicbrainz.org/release/b6953a94-3efc-481b-85d1-bc9c17aec41b
  ≠ Artist: (+44) -> +44
  * Album: When Your Heart Stops Beating
     ≠ (#11) Make You Smile (3:44) -> (#1) When Your Heart Stops Beating (3:19)
➜ [A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? E
Artist: +44
Album: When Your Heart Stops Beating
```

This has caused me to quit every time until now I've finally decided to ask for help. I've read all of the [Tagger](https://beets.readthedocs.io/en/stable/guides/tagger.html) docs, I've added both Chroma and FromFilename plugins, I'm listening to this track and the filename is correct, I've checked MusicBrainz and the track is in the album,

WHY can't beets find the right track here? I don't want to manually edit this bc there are for sure others like it in my library, I want to be able to rely on Chroma and FromFilename to find the correct tracks but don't know how...

**Comment by tomauty** [comment]
Any reason you want to rely specifically on Chroma and FromFilename? Do the files not have metadata embedded?

**Reply by Ifiht** [reply]
The reason is because beets is incorrectly renaming a song that is already 100% correct. I've also put a lot of effort over the years into making sure the filenames are correct, but I've never messed with any of the metadata (or tried to correct it).

But I might have found a workaround with this config:
```
musicbrainz:
    enabled: no

chroma:
    source_weight: 1.0
    auto: yes

fromfilename:
    source_weight: 0.9

metasync:
    source: itunes
    itunes:
        library: /zshares/mimisbrunnr/media/Library/iTunes Library.itl

match:
    strong_rec_thresh: 0.05
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: strong
        unmatched_tracks: strong
    distance_weights:
        artist: 3.0
        album: 3.0
        missing_tracks: 0.0
        track_id: 0.0
```

it would just help for someone to verify I'm doing things right - based on having a music library where both track name and audio fingerprint are probably the two most accurate identifiers for my files?

**Reply by Ifiht** [reply]
Nevermind... it's still getting it wrong even with Musicbrainz disabled (in the example below the filename is literally `02 Here Without You.m4a` and it wants to rename it)...
```
Match (85.1%):
  3 Doors Down - The Better Life
  ≠ mediums, tracks
  MusicBrainz, 2xCD, 2001, AU, None, None, Australian Import Edition
  https://musicbrainz.org/release/9380e43c-2dc8-4f4b-b179-7edbb7d63895
  * Artist: 3 Doors Down
  * Album: The Better Life
  * CD 1
  * CD 2
     ≠ (#2) Here Without You (4:02) -> (#13) Kryptonite (acoustic) (3:52)
```
Please if anyone has suggestions I'd love to get this working.

**Reply by arsaboo** [reply]
How are the songs organized? Beets word best when you have one folder per album. Also, please provide the verbose logs (beets -v).

**Reply by arsaboo** [reply]
Also, for starters disable chroma and fromfilename for troubleshooting.

**Reply by Ifiht** [reply]
I can't disable chroma and fromfilename, I have musicbrainz turned off so then there would be nothing to look up meta..

Is there maybe a specific thing in the logs that would help? Turning on the `-v` flag gives me _pages_ of 
```
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
```

But the organization is typical of most libraries I'd guess? It came from old-school iTunes (circa 2013), so artist/album/tracks layout.  One issue that I seem to be hitting is I have a LOT of incomplete albums, I've never had any issue deleting tracks I don't enjoy.

**Reply by Ifiht** [reply]
I isolated one of the files, turned off all meta plugins except fromfilename and chroma, and ran import on that file by itself.  The verbose log is below (actually this one was right! The track here was labelled wrong..)

```
plugin paths:
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
Sending event: pluginload
library database: /zshares/mimisbrunnr/media/Music/musiclibrary.db
library directory: /zshares/mimisbrunnr/media/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
fromfilename: Artist replaced with: Johnny Lang
fromfilename: Title replaced with:  Paint It Black
Looking up: /zshares/mimisbrunnr/media/Media_to_be_added/Unsort_Music/Johnny Lang - Paint It Black.mp3
Item search terms: Johnny Lang  -  Paint It Black
Sending event: mb_track_extract
Sending event: trackinfo_received
Sending event: mb_track_extract
Sending event: trackinfo_received
chroma: acoustid item candidates: 2
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 1 candidates.

/zshares/mimisbrunnr/media/Media_to_be_added/Unsort_Music/Johnny Lang - Paint It Black.mp3
Sending event: before_choose_candidate

  Match (73.5%):
  Vanessa Carlton - Paint It Black
  ≠ artist
  MusicBrainz, Index None, Track None,
  https://musicbrainz.org/recording/6fc9a835-4ef4-48a5-9e46-8aa6fda0ff6a
  ≠ Artist: Johnny Lang  -> Vanessa Carlton
  ≠ Title:  Paint It Black -> Paint It Black
➜ Apply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort,
eDit, edit Candidates? B
Sending event: import
Sending event: cli_exit
```

**Reply by arsaboo** [reply]
Can you manually check if the track exists on musicbrainz? It looks like beets is working fine.

**Reply by Ifiht** [reply]
It is now. Here's the final weights and settings that worked for my library, in case it helps anyone in posterity:

```
directory: /zshares/mimisbrunnr/media/Music
library: /zshares/mimisbrunnr/media/Music/musiclibrary.db

import:
    write: yes
    copy: yes
    resume: ask
    log: beetslog.txt

preferred:
    countries: ['US', 'JP', 'GB|UK']
    media: ['Digital Media|File', 'CD', 'LP']
    original_year: yes

plugins: chroma fromfilename fetchart metasync edit duplicates discogs spotify

musicbrainz:
    source_weight: 0.9
    genres: yes
    searchlimit: 8
    extra_tags: [year, country]
    external_ids:
        discogs: yes

chroma:
    source_weight: 0.0
    auto: yes

spotify:
    source_weight: 0.8

discogs:
    source_weight: 0.7
    user_token: "BuNgfuIDjyNIwzqCCqykaONntchMXFibTlVeIAEv"

fromfilename:
    source_weight: 0.2

fetchart:
    auto: yes
    cautious: true
    cover_names: front album cover
    sources: itunes spotify filesystem coverart

metasync:
    source: itunes
    itunes:
        library: /zshares/mimisbrunnr/media/Library/iTunes Library.itl

match:
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD', 'VCD', 'SVCD', 'UMD', 'VHS']
    strong_rec_thresh: 0.02
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: strong
        unmatched_tracks: strong
    distance_weights:
        artist: 3.0
        album: 3.0
        missing_tracks: 0.0
        track_id: 0.0
```

**Comment by Ifiht** [comment]
Not an answer, just my full config file currently..

```
directory: /zshares/mimisbrunnr/media/Music
library: /zshares/mimisbrunnr/media/Music/musiclibrary.db

import:
    write: yes
    copy: yes
    resume: ask
    log: beetslog.txt

preferred:
    countries: ['US', 'JP', 'GB|UK']
    media: ['Digital Media|File', 'CD', 'LP']
    original_year: yes

plugins: chroma fromfilename fetchart metasync edit duplicates
#discogs spotify

musicbrainz:
    enabled: no
    source_weight: 0.9
    genres: yes
    searchlimit: 8
    extra_tags: [year, country]
    external_ids:
        discogs: yes

chroma:
    source_weight: 0.2
    auto: yes

#spotify:
#    source_weight: 0.8

#discogs:
#    source_weight: 0.7
#    user_token: "BuNgfuIDjyNIwzqCCqykaONntchMXFibTlVeIAEv"

fromfilename:
    source_weight: 0.0

fetchart:
    auto: yes
    cautious: true
    cover_names: front album cover
    sources: itunes spotify filesystem coverart

metasync:
    source: itunes
    itunes:
        library: /zshares/mimisbrunnr/media/Library/iTunes Library.itl

match:
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD', 'VCD', 'SVCD', 'UMD', 'VHS']
    strong_rec_thresh: 0.02
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: strong
        unmatched_tracks: strong
    distance_weights:
        artist: 3.0
        album: 3.0
        missing_tracks: 0.0
        track_id: 0.0
```
