### DISCUSSION TITLE
Beets in quiet mode skipping recommendations that are over 90%

### DISCUSSION THREAD

**Discussion by tzachyb** [beetbox/beets#5557] [Q&A]
I am trying to automate beets but having the darndest time. For example, importing the 2 tracks I have from 3 Doors Down's The Better Life:  When I run it manually it shows a 97% match, but  when I run in quiet mode it skips it. 

I do have incremental turned on **however** I delete the database before each run (until I solve this issue).

I am sure I'm doing something wrong but have gone through documentation several times and reviewed other's config files. my Config file and output from manual run and quiet run follow.

Configuration:
```
# based on https://randomgeekery.org/post/2017/10/beets-and-itunes/
directory: ~/Music/beet-import

library: ~/Music/beet-musiclibrary.db
art_filename: Folder                # Follow same convention as iTunes
ignore: Album Artwork               # ignore directory that contains no music files
id3v23: true                        # generate id3v23 tags instead of the newer v24
per_disc_numbering: yes             # Number tracks per disc not across the release
import:
  incremental: yes                  # Don't reimport a directory we already imported
  incremental_skip_later: yes       # Try again on skipped items
  quiet: no
  resume: ask                       # Resume interrupted imports?
  languages: en he jp               # Translate any langauges other than these
  log: ~/Music/beets.log            # Where should we write what we do?

per_disc_numbering: yes             # support breaking multidisc into seperate directories

match:
  ignored_media:                    # Media to ignore for matching candidates
    - Data CD
    - DVD
    - DVD-Video
    - Blu-ray
    - HD-DVD
    - VCD
    - SVCD
    - UMD
    - VHS
  distance_weights:
    missing_tracks: 0.05            # reduce penelty for missing tracks, I think
    tracks: 3.0                     # increase penanlty if the track numbers are different
  preferred:                        # Put these at the top of recommendations
    countries: [US, GB|UK,IL]       # My favorite music publishing countries
    media: [CD, Digital Media|File] # My favorite music sources
    original_year: yes              # entry year is close to entry original_year
  strong_rec_thresh: 0.10           # Any difference less than this is a strong recommendation
  max_rec_thresh: 0.20              # Don't recommend anything below a 80% match (instead of default of 75%)

plugins: chroma edit embedart fetchart ftintitle fromfilename hook inline lastgenre lyrics zero

acoustid:
  apikey: REDUCTED                 # My personal key for submitting fingerprints

fetchart:
  enforce_ratio: yes                # Only square cover art
  sources:                          # Prioritize itunes over others
    - filesystem
    - itunes
    - coverart: release
    - coverart: releasegroup
    - '*'

ftintitle:
  format: (feat {0})                # Match iTunes format

embedart:
  ifempty: yes                      # only embedded cover art if missing

inline:
  paths:
    default: $albumartist/$album%aunique{}%if{$multidisc, (Disc $disc)}/$track $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0

zero:
  fields: comments
  comments:                         # Remove obsolete and garbage comments
    - Cleaned by TuneUp!
    - codec v1.063 by Radium
    - Cold.s new single.*
    - Encoded with EC.s MPEG Suite - 96
    - If you like.*
    - kewl21 is elite
    - kocham to - AnGeL
    - Made with RealJukebox (tm).*
    - MusicMatch_.*
    - PrivatePigg
    - Suspect freebie from orientaltradingcompany.com
    - '0'
    - 00000.*
```

Quiet run output:
```
 C:\Users\Jason\Music\iTunes\iTunes Media\Music\3 Doors Down\The Better Life (2 items)
 Skipping
```

Manual run output:
```
   Match (97.0%):
   3 Doors Down - The Better Life
   ≠ missing tracks
   MusicBrainz, CD, 2000, US, Republic Records, 012 153 920-2, None
   https://musicbrainz.org/release/717b5af5-3552-450e-8505-732872c2fe32
   * Artist: 3 Doors Down
   * Album: The Better Life
 Missing tracks (9/11 - 81.8%):
  ! Duck and Run (#3) (3:50)
  ! Not Enough (#4) (3:14)
  ! Be Like That (#5) (4:25)
  ! Life of My Own (#6) (3:58)
  ! Better Life (#7) (3:07)
  ! Down Poison (#8) (4:21)
  ! By My Side (#9) (3:16)
  ! Smack (#10) (2:29)
  ! So I Need You (#11) (3:47)
 ➜ [A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
 Enter search, enter Id, aBort, eDit, edit Candidates?
```

**Comment by Thijxx** [comment]
Quiet mode does nothing. There is no match percentage it will ever match on. I can set it to 10% and then it still skips 96% matches. There is no config setting that changes this, I have tried every possible combination of every import setting there is. I use version 2.5.1. Maybe version 2.6.0 brings back quiet mode.

**Comment by snejus** [comment]
My suspicion is that this is the result of two default configuration options:

```yaml
import:
    quiet_fallback: skip
match:
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
```

In this case, `match.max_rec.missing_tracks` **caps** the maximum recommendation to `medium`, whereas a quiet import _only imports **strong** recommendations_. You probably want to set `match.max_rec.missing_tracks: strong` here, but note that doing so will make quiet mode auto-accept partial-album matches with less evidence, so wrong release/edition matches become easier.


**Note** `max_rec_thresh` does not exist - use `medium_rec_thresh`.
