### DISCUSSION TITLE
Potential issues / can not add "mood" tag to files

### DISCUSSION THREAD

**Discussion by ionlyaskforeden** [beetbox/beets#5573] [General]
Hi,

i've tried to add the mood tag for a few files, including FLACs, m4a's and mp3s yet none of them worked.
Adding to the same files worked with quod libet.

Is this a known issue?

**Comment by arsaboo** [comment]
How are you adding the tag? This should word - https://beets.io/blog/flexattr.html

**Reply by ionlyaskforeden** [reply]
Thanks for the reply.
I did "beed mod songtitle mood=test" - also tried with "modify" instead of mod

However it seems that the mood is written only into the database and not the file itself because when i do "beet ls mood:test" then it does appear, but it does not appear in the file metadata, see below:

```
eden@vega:~$ beet modify theintro mood=test
Modifying 1 items.
Greaf - TheWitch&TheWizard - TheIntro
  mood: test1 -> test
Really modify and write tags? (Yes/no/select) yes

eden@vega:~$ beet info theintro
/media/storage/media/Music/BONES/[2023-03-10] TheWitch&TheWizard/01 TheIntro.flac
acoustid_fingerprint: 
         acoustid_id: 
               album: TheWitch&TheWizard
         albumartist: BONES;Greaf
  albumartist_credit: Bones & Greaf
    albumartist_sort: Bones & Greaf
       albumdisambig: 
         albumstatus: Official
            arranger: 
                 art: True
              artist: Greaf
       artist_credit: GREAF
         artist_sort: Greaf
                asin: 
            bitdepth: 16
             bitrate: 568369
        bitrate_mode: 
                 bpm: 0
         catalognums: 
            channels: 2
            comments: 
                comp: False
            composer: 
       composer_sort: 
             country: XW
                date: 2023-01-01
                disc: 1
           disctitle: 
           disctotal: 1
             encoder: 
        encoder_info: 
    encoder_settings: 
              format: FLAC
               genre: Underground;SESH
              genres: Underground;SESH
            grouping: 
                isrc: USUYG1471440
               label: EMPIRE
            language: eng
           languages: eng
              length: 46.18448979591837
            lyricist: 
              lyrics: 
    mb_albumartistid: 
   mb_albumartistids: 
          mb_albumid: 
         mb_artistid: 
        mb_artistids: 
   mb_releasegroupid: 
   mb_releasetrackid: 
          mb_trackid: 
           mb_workid: 
               media: Digital Media
       original_date: 2023-03-10
        original_day: 10
      original_month: 3
       original_year: 2023
          samplerate: 44100
              script: Latn
               title: TheIntro
               track: 1
          tracktotal: 15
                year: 2023
eden@vega:~$ beet ls mood:test
Aero Chord - Time Leap - Time Leap
BEBLIONTIY - Last Chance - Last Chance
Greaf - TheWitch&TheWizard - TheIntro
```

Am i missing something or is this a bug?

EDIT: formatting
