### DISCUSSION TITLE
Importing multidisc fails

### DISCUSSION THREAD

**Discussion by clmbmb** [beetbox/beets#5576] [General]
I'm trying to import a multidisc album and beets fails in weird ways:
- The files to be imported are in a folder and they look like this:
```
1-01 Alone.flac
1-02 And Nothing Is Forever.flac
1-03 A Fragile Thing.flac
1-04 Warsong.flac
1-05 Drone： Nodrone.flac
1-06 I Can Never Say Goodbye.flac
1-07 All I Ever Am.flac
1-08 Endsong.flac
2-01 Alone.flac
2-02 And Nothing Is Forever.flac
2-03 A Fragile Thing.flac
2-04 Warsong.flac
2-05 Drone： Nodrone.flac
2-06 I Can Never Say Goodbye.flac
2-07 All I Ever Am.flac
2-08 Endsong.flac
```
- beets doesn't recognize the correct release, so I set the ID `70aff3ae-0d5c-4f33-b519-6b4a4e3ec0c7` from https://musicbrainz.org/release/70aff3ae-0d5c-4f33-b519-6b4a4e3ec0c7
- now beets recognizes that there are only two discs instead of three, but it will import some files from CD1 into CD2 and the other way around:
```shell
Enter release ID: 70aff3ae-0d5c-4f33-b519-6b4a4e3ec0c7

  Match (69.3%):
  The Cure - Songs of a Lost World
  ≠ missing tracks, tracks, mediums
  MusicBrainz, 3xMedia, 2024, XE, Fiction, 7503679, deluxe edition
  https://musicbrainz.org/release/70aff3ae-0d5c-4f33-b519-6b4a4e3ec0c7
  * Artist: The Cure
  ≠ Album: Songs Of A Lost World -> Songs of a Lost World
  * CD 1
     ≠ (#2-2) And Nothing Is Forever (6:53) -> (#1-2) And Nothing Is Forever (6:53)
     ≠ (#2-4) Warsong (4:17) -> (#1-4) Warsong (4:17)
     ≠ (#1-5) Drone: Nodrone (4:45) -> (#1-5) Drone:Nodrone (4:45)
     ≠ (#2-8) Endsong (10:25) -> (#1-8) Endsong (10:25)
  * CD 2: Instrumentals
     ≠ (#2-1) Alone (6:49) -> (#2-1) Alone (instrumental) (6:49)
     ≠ (#1-2) And Nothing Is Forever (6:53) -> (#2-2) And Nothing Is Forever (instrumental) (6:53)
     ≠ (#2-3) A Fragile Thing (4:43) -> (#2-3) A Fragile Thing (instrumental) (4:43)
     ≠ (#1-4) Warsong (4:17) -> (#2-4) Warsong (instrumental) (4:17)
     ≠ (#2-5) Drone: Nodrone (4:45) -> (#2-5) Drone:Nodrone (instrumental) (4:45)
     ≠ (#2-6) I Can Never Say Goodbye (6:03) -> (#2-6) I Can Never Say Goodbye (instrumental) (6:03)
     ≠ (#2-7) All I Ever Am (5:21) -> (#2-7) All I Ever Am (instrumental) (5:21)
     ≠ (#1-8) Endsong (10:25) -> (#2-8) Endsong (instrumental) (10:25)
```
- I tried importing one disc at a time, using the same release ID, but beets sees only one song in CD1 (`#5`)  and all songs in CD2 are imported as CD1.

So, my question is: what do I have to do to import all files as coming from the release I linked above?

**Comment by jackwilsdon** [comment]
You might have better luck putting each disc in its own directory, as the importer can recognise this:

```
Disc 1/
  01 Alone.flac
  02 And Nothing Is Forever.flac
  03 A Fragile Thing.flac
  04 Warsong.flac
  05 Drone： Nodrone.flac
  06 I Can Never Say Goodbye.flac
  07 All I Ever Am.flac
  08 Endsong.flac
Disc 2/
  01 Alone.flac
  02 And Nothing Is Forever.flac
  03 A Fragile Thing.flac
  04 Warsong.flac
  05 Drone： Nodrone.flac
  06 I Can Never Say Goodbye.flac
  07 All I Ever Am.flac
  08 Endsong.flac
```

**Reply by clmbmb** [reply]
The files are already in their own directories, just that they're named CD1 and CD2. Would that matter? (I'll test)

LE: I tried renaming the directories to 'Disc X'. No change.

**Reply by jackwilsdon** [reply]
Beets accepts `Disc N`, `Disk N` and `CD N` for directory names. CD 3 isn't an audio CD, so I wouldn't expect beets to try and match that. Could you post your configuration? Also, what tags are in the files currently? Do they contain the CD and track number?

**Comment by clmbmb** [comment]
@jackwilsdon here's my config:

```yaml
directory: /zet/Muzica
library: /zet/Muzica/database.db

per_disc_numbering: yes

plugins:
  - inline
  - discogs
  # - extrafiles
  - copyartifacts
  - fetchart
  - fish
  - mbsubmit
#  - mpdupdate

import:
  move: no
  copy: yes
  timid: yes

item_fields:
  mygenre: |
    import os
    #mypath = os.path.abspath(path)
    #return str(mypath).split("/")[3]
    return os.environ.get("MYGEN")
  multidisc: 1 if disctotal > 1 else 0

paths:
  default: $mygenre/$albumartist/$original_year - $album%aunique{} [%upper{$format}]/%if{$multidisc,CD$disc}/%if{$multidisc,$disc-}$track - $title
  mygenre:Film: $mygenre/$album%aunique{} ($original_year)/$albumartist - $album%aunique{} [%upper{$format}]/%if{$multidisc,CD$disc/}$track - $title
  mygenre:Jocuri: $mygenre/$album%aunique{} ($original_year)/$albumartist - $album%aunique{} [%upper{$format}]/%if{$multidisc,CD$disc/}$track - $title
  singleton: Non-Album/$artist/$title
  comp: $mygenre/Compilations/$album%aunique{}/$track $title

fetchart:
  art_filename: cover.jpg
  cautious: yes
  minwidth: 800
  enforce_ratio: yes
  sources: filesystem coverart itunes amazon albumart
  cover_format: JPEG

scrub:
  auto: yes

    #extrafiles:
    #  patterns:
    #    all:
    #    - '*.jpg'
    #    - '*.png'
    #    - '*.log'
    #    - '*.txt'
    #    - '*.pdf'

copyartifacts:
  extensions: .jpg .png .log .txt .pdf
#mpd:
#  host: sufra.home
#  port: 6600

ui:
  color: yes

ftintitle:
    auto: yes
    format: "feat. {0}"

clutter: ['*.jpg','*.png','*.cue','*.txt','*.log','*.pdf']
```

and here are the tags for the same song on the different discs:

Song 1 - Disc 1
```
General
Complete name                            : Disc 1/1-01 Alone.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 42.7 MiB
Duration                                 : 6 min 49 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 874 kb/s
Album                                    : Songs Of A Lost World
Album/Performer                          : The Cure
Part                                     : 1
Part/Total                               : 2
Track name                               : Alone
Track name/Position                      : 1
Track name/Total                         : 8
Performer                                : The Cure
Genre                                    : Rock
Recorded date                            : 2024-11-01
Writing application                      : X Lossless Decoder 20240511
ISRC                                     : GBUM72403962
Cover                                    : Yes
Cover type                               : Cover (front)
Cover MIME                               : image/jpeg
MCN                                      : 0602475036746
iTunes_CDDB_1                            : 4D0B8E08+222026+8+150+30880+61860+83091+102398+123782+151042+175125

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 6 min 49 s
Bit rate mode                            : Variable
Bit rate                                 : 873 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 42.6 MiB (100%)
Writing library                          : libFLAC 1.4.3 (2023-06-23)
MD5 of the unencoded content             : 6FDF2C4E2414F47BC3E54637826C7493
```

Song 1 - Disc 2
```
General
Complete name                            : Disc 2/2-01 Alone.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 41.3 MiB
Duration                                 : 6 min 49 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 846 kb/s
Album                                    : Songs Of A Lost World
Album/Performer                          : The Cure
Part                                     : 2
Part/Total                               : 2
Track name                               : Alone
Track name/Position                      : 1
Track name/Total                         : 8
Performer                                : The Cure
Genre                                    : Rock
Recorded date                            : 2024-11-01
Writing application                      : X Lossless Decoder 20240511
ISRC                                     : GBUM72405208
Cover                                    : Yes
Cover type                               : Cover (front)
Cover MIME                               : image/jpeg
MCN                                      : 0602475157175
iTunes_CDDB_1                            : 4D0B8E08+222026+8+150+30880+61860+83091+102398+123782+151042+175125

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 6 min 49 s
Bit rate mode                            : Variable
Bit rate                                 : 845 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 41.3 MiB (100%)
Writing library                          : libFLAC 1.4.3 (2023-06-23)
MD5 of the unencoded content             : C2A2178D5C64EC1D0567C8CAA725D30F
```
