### DISCUSSION TITLE
Include MusicBrainz Release ID

### DISCUSSION THREAD

**Discussion by klavierworks** [beetbox/beets#5632] [General]
I'm wondering if I'm overlooking something. When I tag a track with MusicBrainz's fields:

```
    mb_albumartistid: e5479b91-5a7a-4c65-bd09-df6a308f8bc0
   mb_albumartistids: e5479b91-5a7a-4c65-bd09-df6a308f8bc0
          mb_albumid: 1d0285b8-2026-47e5-9166-aee9dc4f5083
         mb_artistid: e5479b91-5a7a-4c65-bd09-df6a308f8bc0
        mb_artistids: e5479b91-5a7a-4c65-bd09-df6a308f8bc0
   mb_releasegroupid: 810a11cb-2129-4e9b-a0a2-3a28bcee26d9
   mb_releasetrackid: 2214419f-165a-3001-88be-dfb76c145284
          mb_trackid: 87479491-2d1c-4c33-8f45-dc42c85bab44
           mb_workid: 
```

I don't see the release ID. Was this an intentional omission (eg: it conflicts with something) or just wasn't seen as necessary? Is it possible to configure Beets to include this?

For reference, as I understand it, release group ID would cover all releases and remasters of an album. ReleaseID would cover all releases of a specific version of the album (eg: CD, vinyl, Japanese CD of a 1999 remaster)
