### DISCUSSION TITLE
Completely Wiped Metadata on Import

### DISCUSSION THREAD

**Discussion by AzureWolf** [beetbox/beets#5642] [Q&A]
Hi there, I just started using beets on  M1 macbook running Sequoia; installed using pip. I have huffed and puffed and I don't know what is going on, but everything I import is completely empty of all metadata. If it has metadata already, it is wiped clean.

Here is my current config, which "works" in the sense that files are moved correctly and renamed correctly. I had originally just had "move: yes" in import, which worked in terms of "moving", but for troubleshooting, this is the current settings where I even go so far as to turn off tagging:

```
directory: ~/Music
library: ~/Music/musiclibrary.db

import:
  write: no
  autotag: no

paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: $artist/$title
  comp: $album%aunique{}/$track - $title
```

This is a file's metadata before import:
<img width="263" alt="image" src="https://github.com/user-attachments/assets/6fcee5ff-bbc6-485a-bbdb-88ddba843bd0" />

This is after importing (right):
<img width="548" alt="image" src="https://github.com/user-attachments/assets/a1f3d353-e731-49e3-a60d-a63d30b17c5d" />

Every bit of metadata is completely scrubbed, even the song name, album, and artist!

Thanks in advance for any help you can provide. I tried my darnedest to search but couldn't find anyone who had a similar issue.

---

EDIT: So far the only "solution" I've found is using MusicBrainz Picard which tags things appropriately. :(
