### DISCUSSION TITLE
Different file name convention for single disc vs. multidisc files

### DISCUSSION THREAD

**Discussion by xtop** [beetbox/beets#5645] [Q&A]
I'm trying to have a file name as track# - title when the release is a single disc and d(disc#)t(track#) - title when the release is multidisc.  However, it looks like everything is defaulting to the multidisc naming convention.

For example, I'm trying to import "Hunky Dory" by David Bowie - specifically, this release https://musicbrainz.org/release/86c0600c-4098-4f7a-8651-c6e271d7d9d8.  I don't see any entries in Disc ID on musicbrainz, so I would assume that the filenames would follow my single disc format.

Here's my config.yaml

```
directory:  <redacted>
library: <redacted>\musiclibrary.db
plugins: fetchart discogs

per_disc_numbering: yes

itemfields:
    multidisc: 1 if disctotal > 1 else 0

import:
    # copy: yes
    write: yes
    # move: yes 
    # autotag: yes -- default
    log: ./$album%aunique{}.log
    
paths:
    default: $format/$albumartist/$original_year - $album%aunique{}/%if{$multidisc,d$disc}%if{$multidisc,t}$track - $title
    singleton: $format/Non-Album/$artist/$title
    comp: $format/Compilations/$album%aunique{}/%if{$multidisc,d$disc}%if{$multidisc,t}$track - $title

musicbrainz:
    enabled: yes
    host: musicbrainz.org
    https: no
    ratelimit: 1
    ratelimit_interval: 1.0
    searchlimit: 5
    extra_tags: []
    genres: no
    external_ids:
        discogs: yes
        bandcamp: yes
        spotify: no
        deezer: no
        beatport: no
        tidal: no
```

After looking at similar items, I thought I had the right setup with creating a multidisc variable and the %if statements, but I must be missing a step somewhere.
