### DISCUSSION TITLE
Multiple "destinations" for different conversion formats.

### DISCUSSION THREAD

**Discussion by GrandMasterHokage** [beetbox/beets#5653] [Q&A] [answered]
I've been doing a bit of research and playing around with the `paths:` variable in the `convert` plugin.

I utilize 2 different file formats `OPUS` (for my mobile devices) and `AAC` (for my relatively old head units in my vehicles).  I'd like to have entire library in those 2 formats, but in separate folders.

Beets does not allow me to specify a `dest:` for each of the formats.
I've tried using `$format` in the paths field but that simply uses the format of the source file.

Some alternatives I've considered:
- using a separate `config.yaml`, specifying a destination for AAC and OPUS convert options
- using `beet modify -a covert=convert_format` to add a custom field to all my songs, them using that custom `$field` in the paths configuration of convert.

I'm sure there's a much simpler way to do this and I'm overlooking it. I'd appreciate any help

**Comment by GrandMasterHokage** [comment, marked as answer]
Well... There was an oversight on my end... I forgot that I can specify the destination with the `beet convert -d <conversion folder> -f <codec> -y` command.

I will however appreciate a feature which allows me to specific a destination per codec though, so I'll close this discussion as resolved and place this request in feature requests.

Here's my config in case anyone is curious about this in the future:
```
directory: /mnt/hdd1/Music/FLAC
import:
    move: yes
    write: yes
    log: beetslog.txt
art_filename: cover
plugins: bpd ftintitle lyrics convert fetchart
pluginpath: ~/beets/myplugins
ui:
    color: yes

paths:
    default: $albumartist/$album/$track - $title
    singleton: $artist/Singletons/$artist - $title
    comp: $album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title

ftintitle:
    auto: yes
    format: (feat. {0})

lyrics:
    auto: yes
    force: yes
    synced: yes
    sources: lrclib

convert:
    never_convert_lossy_files: yes
    formats:
        aac:
            command: ffmpeg -i $source -y -c:v copy -c:a libfdk_aac -vbr 5 $dest
            extension: m4a
        opus:
            command: opusenc --music --vbr $source $dest
            extension: ogg
```
