### DISCUSSION TITLE
Please help: Import Problems

### DISCUSSION THREAD

**Discussion by LeftAtThePool** [beetbox/beets#5655] [Q&A]
```
% beet import -s '/Users/user1/Music/Musik/06.-Odyssee Of Noises - Firedance (The Sunrise).aiff'

/Users/user1/Music/Musik/06.-Odyssee Of Noises - Firedance (The Sunrise).aiff

Finding tags for track "06. - Odyssee Of Noises ".
```

Somehow the track number is identified as the artist when importing. What am I doing wrong?
It is extremely frustrating to import like this.
Im very new to beets, and have struggled with this problem before and quit trying to learn beets for a few months.
Id be very grateful for your help as I can't imaging beets failing with something like this

This is my config file:
```
import:
    copy: yes
    write: yes
plugins: edit fromfilename fetchart embedart bandcamp discogs beatport4 lastgen$
original_date: yes
fetchart:
    auto: yes
    high_resolution: yes
    sources:
        - filesytem
        - coverart
        - bandcamp
        - itunes
        - discogs
        - spotify
embedart:
    ifempty: yes
lastgenre:
    source: track
    count: 3
    seperator: "/ "
musicbrainz:
    extra_tags: [year, catalognum, label]
    external_ids:
        discogs: yes
        bandcamp: yes
        beatport: yes
bandcamp:
    include_digital_only_tracks: true
    search_max: 10
    exclude_extra_fields:
        - comments
        - lyrics
beatport4:
    source_weight: 0.2

```

Thanks! :)
