### DISCUSSION TITLE
beetz upd moves unchanged music around incorrectly.

### DISCUSSION THREAD

**Discussion by MrDowntempo** [beetbox/beets#5661] [Q&A]
First day using beets. Mostly happy so far, but still getting the hang of things. Spent a chunk of time getting my config and plugins setup but decided to wait on things like spotify and lyrics for later. My hope was I could get things imported, then add the API keys and then do an update. Reading through the docs, I added the bit that sends soundtracks to their own folder. Worked great first go! However after I made a couple mistakes with some other albums, I deleted them and ran beetz upd to clean up the database before re-importing them correctly. HOWEVER, the soundtracks all got relabeled as compilations and moved out of the soundtrack folder, leaving it empty. I've seen similar behavior with some albums being labeled as remix on first import, but then switched to album on an update. How can I fix/prevent these reclassifications?

Here's my current config:

```
# Final folder
directory: /mnt/BigVault/Music/

reflink: auto

log: /mnt/BigVault/beetlog.txt

# Preferred language precedence
languages: en jp es

plugins: chroma badfiles fetchart fish fromfilename ftintitle missing scrub the web albumtypes 

ui:
    color: yes

# Musicbrainz options
musicbrainz:
    # Add these tags when searching musicbrainz
    extra_tags: [year]

# The default paths for different types of albums
# soundtracks worked, but then got converted back on an update. Perhaps because of scrub
paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    albumtype:soundtrack: Soundtracks/$album%aunique{}/$track $title
    comp: Compilations/$album%aunique{}/$track $title

```
