### DISCUSSION TITLE
First Setup Help

### DISCUSSION THREAD

**Discussion by panzli** [beetbox/beets#5665] [Q&A]
Hello everybody,

today I tried to use this tool, but it's not finding any matches.

*my config:*

```musicbrainz:
    enabled: no
discogs:
    user_token: 
    source_weight: 0.9
```

```
(venv) amnesia@elitebook:~/Music/test$ ll
total 9368
drwxrwxr-x 2 amnesia amnesia    4096 Mär 11 19:50  ./
drwxr-xr-x 6 amnesia amnesia    4096 Mär 11 19:50  ../
-rw-rw-r-- 1 amnesia amnesia 9584445 Mai 27  2022 'System Faith – Path Of God (B1 New Cut) (2002).mp3'
(venv) amnesia@elitebook:~/Music/test$ beet -v import . 
user configuration: /home/amnesia/.config/beets/config.yaml
data directory: /home/amnesia/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/amnesia/.config/beets/library.db
library directory: /home/amnesia/Music
Sending event: library_opened
Sending event: import_begin
state file could not be read: [Errno 2] No such file or directory: '/home/amnesia/.config/beets/state.pickle'
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/amnesia/Music/test
Tagging  - 
No album ID found.
Search terms:  - 
Album might be VA: True
Evaluating 0 candidates.

/home/amnesia/Music/test (1 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
No matching release found for 1 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
➜ [S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort? 
```

I mainly want to use discogs and therefore I disabled musicbrainz, but the Song exists on discogs: https://www.discogs.com/release/175259-System-Faith-Path-Of-God

Could anybody please help me to troubleshoot this user problem further?

Regards

**Comment by DjSlash** [comment]
You only shared a snippet from your config. From what you pasted, it seems your config is not correct. The `enabled` directive should be put below `musicbrainz`. Like so:

```yaml
musicbrainz:
    enabled: no
```

Furthermore, you do an import on one file, where it seems from the output, that there is not metadata available in it. So beets has nothing to work on. You can try to enable the `fromfilename` plugin.

**Reply by panzli** [reply]
Thank you for your help unfortunately the config was cut at the top

Yesterday I already discovered the fromfilename plugin, but the is still not detected.

Could you please check my config ?

```
(venv) amnesia@elitebook:~/Music$ beet config

# --------------- Plugins ---------------

plugins: discogs fromfilename
musicbrainz:
    enabled: no
discogs:
    user_token: REDACTED
    source_weight: 0.9
    index_tracks: no
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    separator: ', '
    append_style_genre: no

```
