### DISCUSSION TITLE
How to only write disc number to filename if the album contains multiple discs?

### DISCUSSION THREAD

**Discussion by SpencerDub** [beetbox/beets#5670] [Q&A] [answered]
I've been happily using Beets for a couple days to ingest and tag music. I'd like to tweak its configuration just a little. Currently, this is my `paths:` config:

```
paths:
    default: $albumartist/$album%aunique{}/$albumartist - $disc-$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$artist - $track - $title
    albumtype_soundtrack: Soundtracks/$album/$disc-$track - $artist - $title
```

That results in an extraneous `01-` on the track number for _most_ albums, however, since most albums are only a single disc. I would like Beets to only write the disc number to the filename if the total number of discs in the album is greater than one.

However, this config isn't working:
```
paths:
    default: $albumartist/$album%aunique{}/$albumartist - %if{$disctotal > 1,$disc-}$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$artist - $track - $title
    albumtype_soundtrack: Soundtracks/$album/%if{$disctotal > 1,$disc-}$track - $artist - $title
```

When I try to [`update`](https://beets.readthedocs.io/en/stable/reference/cli.html#update) my library or import new files with the `$disctotal > 1` config above, I still get the same double-number filename (`01-01`).

I'm sure I'm missing something very simple. How can I only write the disc number to the filename on multi-disc albums?
