### DISCUSSION TITLE
How to make sure albums are never distributed over multiple directories even though the normal paths rules would say so

### DISCUSSION THREAD

**Discussion by halloleo** [beetbox/beets#5697] [Q&A] [answered]
I like to have my classical albums under the composer instead of the artist. For this I have the following paths rules in my config:

```
paths:
    default: $albumartist/$album%aunique{}/$track $title
    comp: Compilations/$album%aunique{}/$track $title
    genre:classical: $composer//$album%aunique{}/$track $title
```

This config however implies that albums where different tracks are by different composers are split over multiple directories. 

One solution can be that I _manually_ set `albumtype` to "compilation", but I don't want to do this, because normally "compilation" stands for  "compilation of different _artists_".

So I am looking for another solution where the tracks are (preferably  _automatically_) filed under a directory like`MultipleComposers`. 

Is this possible?

**Comment by DjSlash** [comment, marked as answer]
Although that might not always be true with classical music, in many cases composer has multiple composers. So it might be better to have composer in the filename, rather than in the directoryname. At least, that is what I would do if I would want to have that info in my path, it would be lost otherwise.

Anyway, I think the solution for this is using the `inline` plugin and count the number of composers in that field. Something like:

```yaml
plugins:
    - inline

item_fields:
     multicomposer: 1 if len(composer.split(", ")) > 1 else 0

paths:
    genre:classical: %if(multicomposer,MultipleComposer,$composer)/$album/$track $title
```

Test it on a small set of files before applying on your whole collection.
