### DISCUSSION TITLE
How to share code logic for two fields when using the inline plugin?

### DISCUSSION THREAD

**Discussion by halloleo** [beetbox/beets#5720] [Q&A] [answered]
I have a question about how custom album fields can refer to each other when using the `inline` plugin.

Let's look at a  minimal example. In my config I could have something like:

```
album_fields:
  myfield: |
    # Assume here a lengthy calculation
	res = "AnArtist"
	# ...
    return res

  myotherfield: |
    return myfield.upper()

format_album: $myotherfield - $album [$genre]

paths:
    default: $myfield/$track $title
```

When running beets with this config I get a "Name error: 'myfield' not found." This means that in the definition of `myotherfield` I'm apparently not allowed to refer to `myfield`.

Now, assuming `myfield` is calculated in a slightly laborious way, then it would be very desirable to reuse the value of `myfield` in the definition of `myotherfield`. But how to do it? I tried using a _function_ to share the code:

```
album_fields:
  myfield: |
    def anartist():
      return "AnArtist"
    return anartist()

  myotherfield: |
    return anartist().upper()
```

However, the function `anartist()` is not available in `myotherfield`.

What else _does_ work to share code logic for two fields?

Thanks heaps for any suggestions!
