### DISCUSSION TITLE
lastgenre fetching tags that aren't on last.fm?

### DISCUSSION THREAD

**Discussion by negativeten** [beetbox/beets#5742] [Q&A]
so if i use lastgenre on my library for all albums by bandetto, i'll get 
```
lastgenre: genre for album Bandetto - *.WAV SLAVE (artist): Speedcore, Gabber, Breakcore, Hardcore
lastgenre: genre for album Bandetto - BAD_COMMAND (artist): Speedcore, Gabber, Breakcore, Hardcore
lastgenre: genre for album Bandetto - SLIP'N'SLIDE (artist): Speedcore, Gabber, Breakcore, Hardcore
```
but the issue is, neither bandetto, nor .wav slave, nor any of the tracks on that album are tagged as speedcore on last.fm, as far as i can tell. idk where it's getting speedcore from. i have even tried zeroing the genre tags on these albums and they still get tagged as speedcore after doing so. no clue what i'm missing here. if it's helpful, my config is
```
directory: /music
library: /config/musiclibrary.db
import:
  move: yes
  copy: no
  write: yes
plugins: fetchart replaygain lastgenre lyrics fromfilename albumtypes mbsync zero
ui:
  color: yes

original_date: yes

lyrics:
  auto: yes
  sources: [lrclib, google, genius, tekstowo]
  google_API_key: [REDACTED]
replaygain:
  auto: yes
  backend: ffmpeg
  targetlevel: 89
  r128_targetlevel: 89
fetchart:
  auto: yes
  enforce_ratio: 0.5%
lastgenre:
  auto: yes
  canonical: yes
  count: 4
  whitelist: /config/whitelist.txt
  prefer_specific: yes
  force: yes
  keep_existing: no
  source: album
zero:
  auto: no
  fields: album
  update_database: true
```
and my whitelist is 
```
african
c-pop
j-pop
k-pop
indian pop
lo-fi
experimental music
blues
bossa nova
samba
mambo
merengue
salsa
reggaeton
classical
orchestra
comedy
country
bluegrass
progressive bluegrass
elevator music
ambient
breakbeat
chiptune
disco
downtempo
acid jazz
drum and bass
electro
electronic rock
electronica
eurodance
hardcore
breakcore
gabber
speedcore
hardstyle
house
industrial
noise
techno
trance
trap
folk
hip hop
rap
jazz
dixieland
jazz fusion
ragtime
smooth jazz
swing
soft rock
funk
soul
rock
alternative rock
grunge
indie rock
shoegaze
heavy metal
post-punk
progressive rock
punk rock
emo
hardcore punk
riot grrrl
sock and roll
rockabilly
southern rock
hard rock
surf rock
reggae
ska
```
what am i doing wrong (if anything)?
