### DISCUSSION TITLE
Exclude DVDs from Multidisclogic

### DISCUSSION THREAD

**Discussion by mangix0815** [beetbox/beets#5758] [Q&A]
Hey there, maybe someone can help me with my problem—I just can’t figure it out:

Some releases include both CDs and DVDs. I’ve only saved the CDs, yet the $disc field still appears because beets correctly detects multiple discs. In these cases, I want the $disc field to be omitted—I only want it to appear when a release actually has multiple CDs, not when it’s one CD plus one or more DVDs.

For a single-CD release (or a release with one CD and one or more DVDs), the format should be:

`$artist – $album – $track – $title
`

For a multi-CD release:

`$artist – $album – Disc $disc – $track – $title`

This is my config:

```
item_fields:
    initial: "(u'#' if albumartist[0].isdigit() else albumartist[0].upper())"
    disc_label: "(u' – Disc %02i' % disc) if disctotal > 1 else u''"

paths:
  default: "$initial/$albumartist/$original_year – $albumartist%aunique{}/$artist – $album$disc_label – $track – $title"
```

(Full config: https://pastebin.com/Jv1755Pu)

This works for releases which only contain CDs but not, if a release contains CDs and DVDs. Is there a way to detect if a release contains both CDs and DVDs, and only include the “Disc –” label when there are multiple CDs (ignoring DVDs in the count)?

Thank you!
