### DISCUSSION TITLE
Can I conditionally write the discnum tag?

### DISCUSSION THREAD

**Discussion by cccslater** [beetbox/beets#5816] [Q&A] [answered]
Hi!

I have an mp3 player that likes to show discnum in front of tracknum even for albums with only 1 disc.

Can I configure beets to only write the discnum tag if there are multiple discs?

Thank you :-)

**Comment by cccslater** [comment]
Done it!
```
import:
    set_fields:
        disc: %if{$multidisc,$disc,"0"}
per_disc_numbering: yes
item_fields:
    multidisc: 1 if disctotal > 1 else 0
```
Possible that it'll infinitely recurse on an actual multi-disc album, but I don't think that'll be too hard to fix.

**Comment by cccslater** [comment]
Not done it! I suspect due to infinite recursion or to `multidisc` initially equalling 0 -- all albums are given a 0 disc number :-(

**Comment by cccslater** [comment, marked as answer]
Done it!
```
item_fields:
    multidisc: 1 if disctotal > 1 else 0
paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc,$disc-}$track - $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/%if{$multidisc,$disc-}$track - $title
alternatives:
    converted:
        directory: ~/Music/Lossy/Converted
        formats: opus
        query: ""
hook:
    hooks:
    - event: import
      command: sh -c "beet --config /home/ccc/Music/Lossless/config.yaml modify -y multidisc:0 disc=0 >/dev/null"
    - event: import
      command: sh -c "beet --config /home/ccc/Music/Lossless/config.yaml alt update converted >/dev/null"
```
Essentially using `alternatives` instead of `convert`.
