### DISCUSSION TITLE
Using advancedrewrite only on singletons doesn't work when importing

### DISCUSSION THREAD

**Discussion by mattijsbliek** [beetbox/beets#5827] [Q&A]
The way I handle my music organization for singletons is by putting them into a single album. I set the album artist to "Various artists", and the album to "Singles". This way all my singles are grouped in a single album in all my media players.

Now I was hoping to achieve this by letting advancedrewrite set these fields on import, and using `match: "singleton:true"` to make sure it doesn't do this for album imports.

This doesn't work however, advancedrewrite is trying to rewrite everything I import, also albums. My theory is that perhaps advancedrewrite runs before beets had a chance to tag the import as a singleton. I don't this for sure however.

Any solutions or workarounds would be much appreciated 🙏 

This is my config:
```yaml
directory: /mnt/media/Music/Library
import:
  move: yes
  incremental: no
plugins: convert embedart fetchart info scrub zero importadded advancedrewrite 
convert: 
  format: "mp3"
  auto: true
  never_convert_lossy_files: true
  delete_originals: true
paths:
  singleton: Singles/$artist - $title
advancedrewrite:
  - match: "singleton:true"
    replacements:
      album: Singles
      albumartist: Various Artists
      disc: '1'
      track: '0'
      comments: ''
      mb_albumid: ''
zero:
  fields: date catalognum copyright
```
