### DISCUSSION TITLE
Album disambiguation does not work

### DISCUSSION THREAD

**Discussion by justjakka** [beetbox/beets#5842] [Q&A]
i have different editions of a release:
```
'[M3-44] REFRAKT LP {RFKV-001}'
'[M3-44] REFRAKT LP {RFKV-001} [Vinyl]'
```

paths are configured like this:
```yaml
paths:
    default: %if{$label,$label,$albumartist}/$event_pretty%if{$label,,$albumartist — }$album%if{$catalognum, {$catalognum$}, {[none]$}}%aunique{albumartist album catalognum, media, []}/$disc_and_track. %if{$artist_credit,$artist_credit,$artist} — $title
    comp: %if{$label,$label,Various Artists}/$event_pretty$album%if{$catalognum, {$catalognum$}, {[none]$}}%aunique{albumartist album catalognum, media, []}/$disc_and_track. %if{$artist_credit,$artist_credit,$artist} — $title
```
and beets still moves the vinyl into digital edition folder

can anything be done to fix this?
