### ISSUE TITLE
It doesn't create log file 

### ISSUE THREAD

**Issue by simonbcn** [beetbox/beets#1005]
```
$ beet -v version 
user configuration: /home/simon/.config/beets/config.yaml
data directory: /home/simon/.config/beets
Sending event: pluginload
artresizer: method is (2, (6, 7, 7))
no config file found at /home/simon/.beetsconfig
library database: /home/simon/.beets/musiclibrary.blb
library directory: /home/simon/Música
Sending event: library_opened
beets version 1.3.9
plugins: fetchart, info, scrub, beatport, embedart, lastgenre, web, discogs, convert, replaygain, chroma, duplicates
Sending event: cli_exit
```

Config file:

```
directory: "/home/simon/M\xFAsica/"
library: /home/simon/.beets/musiclibrary.blb
threaded: no
color: yes
plugins: convert chroma replaygain fetchart lastgenre scrub embedart beatport discogs web duplicates info
art_filename: cover
languages: es
log: /home/simon/.beets/import.log

fetchart:
   maxwidth: 300
   cover_names: front folder cover 

embedart:
   maxwidth: 300

match:
    strong_rec_thresh: 0.20

import:
   art: yes

paths:
   default: $albumartist/$album/$track - $title
   singleton: $artist - $title
   comp: Varios/$album/$track - $title

replaygain:
   auto: yes
   backend: command
   overwrite: yes
   apply: yes

lastgenre:
   canonical: ''
   fallback: ''
   multiple: yes
   force: no

convert:
   auto: yes
   command: ffmpeg -i $source -y -codec:a libmp3lame -vn -qscale:a 1 $dest
   extension: mp3
   max_bitrate: 250
   embed: yes
   quiet: yes

duplicates:
   path: yes
```

I have done several imports but `beets` doesn't create the log file.
