### ISSUE TITLE
smartplaylist: Respect sort terms in queries

### ISSUE THREAD

**Issue by djl** [beetbox/beets#1137]
It would be nice to be able sort items in smart playlists, like so:

```
smartplaylist:
  relative_to: ~/music
  playlist_dir: ~/.mpd/playlists
  playlists:
    - name: '2014.m3u'
      query: 'year:2014 added+'
    - name: 'imported-%time{$added,%Y-%m}.m3u'
      query: "added:: path+"
```

I'm unfamiliar with the code but it looks like the smartplaylist plugin [discards the query `sort` field](https://github.com/sampsyo/beets/blob/master/beetsplug/smartplaylist.py#L45) when building playlists. Would it be possible to keep the custom sort?
