### ISSUE TITLE
lost library file

### ISSUE THREAD

**Issue by euri10** [beetbox/beets#1149]
hdd crashed, realized I backup my Beets folder / config, but not the library file musiclibrary.blb

is there a "smart" way to rebuild it ?

here is my config file :

```
➜  ~  cat .config/beets/config.yaml
directory: /media/raid5/BEETS
library: /media/raid5/musiclibrary.blb
import:
    write: yes
    move: no
    timid: yes
list_format_item: $artist - $album - $title - $danceability
plugins: discogs fetchart echonest
fetchart:
    auto: no
echonest:
    apikey: myapikey
```
