### ISSUE TITLE
`beet import --library` adds numbers to album directories

### ISSUE THREAD

**Issue by denisdefreyne** [beetbox/beets#1379]
When I run `beet import --library`, beets renames album directories:

```
% ls -l Library/Legowelt
…
drwxr-xr-x  7 ddfreyne staff 238 Mar 25 18:05 The Liechtenstein Account 1550
drwxr-xr-x 16 ddfreyne staff 544 Mar 25 18:07 The Rise and Fall of Manuel Noriega 1565
drwxr-xr-x 16 ddfreyne staff 544 Mar 25 18:07 The Teac Life 1566
drwxr-xr-x  7 ddfreyne staff 238 Mar 25 18:05 Tracks From The Tube 1552
drwxr-xr-x 15 ddfreyne staff 510 Mar 25 18:07 Vatos Locos 1568
drwxr-xr-x  8 ddfreyne staff 272 Mar 25 18:05 Wirtschaftswunder 1554
```

The numbers 1550, 1565, …, 1554 were not there before.

**Comment by djl** [comment]
I had the same thing happen to me with one when I tried to retag them. The albums had to be `beet remove`d and reimported before the numbers went away.

Since this only happened once I wasn't able to track it down but I think this might be a bug related to duplicate albums and the `aunique{}` template function. The numbers are the end are the beets album ID and the `aunique{}` function [does use the album ID](https://github.com/sampsyo/beets/blob/4bfa439ee14decfb9d690260f1de435508b63711/beets/library.py#L1368).

**Comment by amishb** [comment]
Can you post your config file please?

**Comment by ddfreyne** [comment]
@djl That makes sense. Strange that it wouldn’t undo the rename, though.

Here is my config file:

```yaml
directory: "/Volumes/Erie/Music/Beets/Library"
library: "/Volumes/Erie/Music/Beets/beets.db"
paths:
        default: $albumartist/$album%aunique{}/$disc-$track $title
        comp: Compilations/$album%aunique{}/$disc-$track $title
import:
        copy: no
        move: yes
plugins: web discogs mbsync chroma info
per_disc_numbering: yes
```
