### ISSUE TITLE
convert: Originals left behind on import when transcoding with "move: yes" 

### ISSUE THREAD

**Issue by steveh** [beetbox/beets#1464]
Given the following configuration, when importing a directory of ALAC albums:

```
convert:
  format: flac
  auto: yes
import:
  write: yes
  move: yes
```

`beet import` will convert imported files to FLAC as expected, but will leave behind the originals. I want it to delete the originals when files are imported successfully.

From google group: https://groups.google.com/forum/#!topic/beets-users/WvTmPWnmyrk
