### ISSUE TITLE
fetchart and thumbnails: When `remove_art_file` is enabled, image is deleted before thumbnail hook runs

### ISSUE THREAD

**Issue by simonbcn** [beetbox/beets#1695]
```
Ubuntu 14.04 64 bits
beets git version 1.3.16
Nautilus 3.10.1
```
```
directory: "/home/simon/M\xFAsica/"
library: /home/simon/.beets/musiclibrary.blb
threaded: no

plugins: convert fetchart info duplicates badfiles zero replaygain embedart lastgenre scrub chroma discogs thumbnails

fetchart:
  auto: yes
  maxwidth: 300

embedart:
  auto: yes
  maxwidth: 300
  remove_art_file: yes

match:
  strong_rec_thresh: 0.30
  max_rec:
    missing_tracks: strong
    
import:
  art: yes
  languages: es en

paths:
  default: $albumartist/$album/$track - $title
  singleton: $artist - $title
  comp: Varios/$album/$track - $title

replaygain:
  backend: bs1770gain
  overwrite: yes

lastgenre:
  canonical: yes
   
convert:
  auto: yes
  tmpdir: /tmp
  command: ffmpeg -i $source -y -codec:a libmp3lame -vn -qscale:a 1 $dest
  extension: mp3
  quiet: yes
  never_convert_lossy_files: yes
   
duplicates:
  path: yes

thumbnails:
  auto: yes
  force: yes

scrub: 
  auto: yes  

zero:
  fields: comments
  update_database: true
```
The image (`cover.jpg`) is in folder with mp3 files:
```
$ ls Música/Lana\ Del\ Rey/Honeymoon/
01 - Honeymoon.mp3               06 - Freak.mp3                     11 - The Blackest Day.mp3
02 - Music to Watch Boys To.mp3  07 - Art Deco.mp3                  12 - 24.mp3
03 - Terrence Loves You.mp3      08 - Burnt Norton (interlude).mp3  13 - Swan Song.mp3
04 - God Knows I Tried.mp3       09 - Religion.mp3                  14 - Don’t Let Me Be Misunderstood.mp3
05 - High by the Beach.mp3       10 - Salvatore.mp3                 cover.jpg
```
...but `beet thumbnails` doesn't find it:
```
$ beet -vv thumbnails 'lana del rey'
user configuration: /home/simon/.config/beets/config.yaml
data directory: /home/simon/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 7, 7))
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
library database: /home/simon/.beets/musiclibrary.blb
library directory: /home/simon/Música
Sending event: library_opened
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
thumbnails: generating thumbnail for Lana Del Rey - Honeymoon
thumbnails: album Lana Del Rey - Honeymoon has no art
Sending event: cli_exit
```
