### ISSUE TITLE
thumbnails plugin crashes on Fedora 23

### ISSUE THREAD

**Issue by nurbo** [beetbox/beets#1703]
I recently updated my Fedora 22 to 23. After the update, the thumbnails plugin segfaults. I have tested this issue in fresh VM installation of Fedora 22 and Fedora 23 – the same issue occurred on the newer OS.

Both VMs ran newest beets and had ImageMagick installed (`6.8.8.10` on Fedora 22, `6.9.1.3` on Fedora 23):

```
[bruno@localhost ~]$ beet version
beets version 1.3.15
plugins: embedart, fetchart, fuzzy, thumbnails
```

…and the same config (output of `beet config`:

``` yaml
fetchart:
    cautious: yes
    sources: coverart albumart google
    auto: no
    minwidth: 0
    maxwidth: 0
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    remote_priority: no
    enforce_ratio: no
thumbnails:
    auto: no
    dolphin: no
    force: no
embedart:
    auto: no
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    maxwidth: 0

plugins: fuzzy fetchart embedart thumbnails
fuzzy:
    threshold: 0.7
    prefix: '~'
```

On Fedora 22 the thumbnails plugin works correctly and the folder thumbnails are present in Nautilus:

```
[bruno@fedora22 ~]$ beet -vv thumbnails -f
user configuration: /home/bruno/.config/beets/config.yaml
data directory: /home/bruno/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/bruno/.config/beets/library.db
library directory: /home/bruno/Music
Sending event: library_opened
artresizer: method is (2, (6, 8, 8))
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
thumbnails: generating thumbnail for Wojciech Bąkowski - Kształt
thumbnails: found a suitable 256x256 thumbnail for Wojciech Bąkowski - Kształt, forcing regeneration
artresizer: ImageMagick resizing /home/bruno/Music/Wojciech Bąkowski/Kształt/cover.jpg to /home/bruno/.cache/thumbnails/large/76177378dc73dd856f8a83e758662b68.png
thumbnails: found a suitable 128x128 thumbnail for Wojciech Bąkowski - Kształt, forcing regeneration
artresizer: ImageMagick resizing /home/bruno/Music/Wojciech Bąkowski/Kształt/cover.jpg to /home/bruno/.cache/thumbnails/normal/76177378dc73dd856f8a83e758662b68.png
thumbnails: wrote thumbnail for Wojciech Bąkowski - Kształt
Sending event: cli_exit
```

On Fedora 23 the thumbnails plugin causes segmentation fault:

```
[bruno@fedora23 ~]$ beet -vv thumbnails -f
user configuration: /home/bruno/.config/beets/config.yaml
data directory: /home/bruno/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/bruno/.config/beets/library.db
library directory: /home/bruno/Music
Sending event: library_opened
artresizer: method is (2, (6, 9, 1))
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
thumbnails: generating thumbnail for Wojciech Bąkowski - Kształt
Segmentation fault (core dumped)
```

---

PIP version and installed packages on
- Fedora 22:

```
[bruno@fedora22 ~]$ pip -V
pip 7.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
[bruno@fedora22 ~]$ pip list
backports.ssl-match-hostname (3.4.0.2)
beets (1.3.15)
blivet (1.0.9)
chardet (2.2.1)
coverage (4.0a5)
decorator (3.4.0)
di (0.3)
dnf-langpacks (0.9.1)
enum34 (1.0.4)
iniparse (0.4)
initial-setup (0.3.31)
IPy (0.81)
jellyfish (0.5.1)
kitchen (1.2.1)
langtable (0.0.31)
munkres (1.0.7)
musicbrainzngs (0.5)
mutagen (1.31)
ntplib (0.3.2)
pathlib (1.0.1)
pexpect (3.1)
pip (7.1.2)
pwquality (1.2.4)
pycurl (7.19.5.1)
pygobject (3.16.1)
pygpgme (0.3)
PyIscsi (1.0)
pykickstart (1.99.66)
pyliblzma (0.5.3)
pyparted (3.10.3)
python-augeas (0.5.0)
python-dmidecode (3.10.13)
python-meh (0.38)
pytz (2012d)
pyudev (0.16.1)
pyxattr (0.5.3)
pyxdg (0.25)
PyYAML (3.11)
requests (2.6.2)
rpm-python (4.12.0.1)
setuptools (12.0.3)
six (1.9.0)
slip (0.6.1)
slip.dbus (0.6.1)
SSSDConfig (1.12.4)
Unidecode (0.4.18)
urlgrabber (3.10.1)
urllib3 (1.10.2)
yum-metadata-parser (1.1.4)
[bruno@localhost ~]$ 
```
- Fedora 23:

```
[bruno@fedora23 ~]$ pip -V
pip 7.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
[bruno@fedora23 ~]$ pip list
beets (1.3.15)
chardet (2.2.1)
enum34 (1.0.4)
iniparse (0.4)
jellyfish (0.5.1)
kitchen (1.2.1)
munkres (1.0.7)
musicbrainzngs (0.5)
mutagen (1.31)
pathlib (1.0.1)
pexpect (3.1)
pip (7.1.2)
pycurl (7.19.5.1)
pygobject (3.18.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pyxattr (0.5.3)
pyxdg (0.25)
PyYAML (3.11)
requests (2.8.1)
rpm-python (4.13.0rc1)
setuptools (18.0.1)
six (1.9.0)
Unidecode (0.4.18)
urlgrabber (3.10.1)
yum-metadata-parser (1.1.4)
```

The core dump is available at https://www.dropbox.com/s/sl2i3hs62fx7gi1/beets-coredump.zip?dl=0 . Unfortunately, I don't have the experience to debug this myself. Could this be related to the migration to Python 3 as the default in the newest release?
