### ISSUE TITLE
Beet convert only non-mp3s

### ISSUE THREAD

**Issue by jackwilsdon** [beetbox/beets#1713]
Is it possible to tell convert to only encode non-mp3s? If I set `never_convert_lossy_files` to `yes`, m4a files are not encoded, however if I set it to `no`, then all mp3 files are encoded. What's the best way to ensure all of my media is converted to mp3?

**Comment by sampsyo** [comment]
Are you converting *to* MP3 also? If so, the plugin shouldn't convert MP3s by default, unless you've configured a maximum bitrate. https://github.com/sampsyo/beets/blob/master/beetsplug/convert.py#L95

**Comment by jackwilsdon** [comment]
I am looking to convert all *non*-mp3 files to mp3. I have some songs in m4a format and when using `beet convert -d Converted`, it just copies the m4a files;

<img width="769" alt="screen shot 2015-11-13 at 18 33 53" src="https://cloud.githubusercontent.com/assets/1843197/11154146/8992629e-8a35-11e5-90ef-b3aaea2a3e0e.png">

Here is my configuration:

```yaml
directory: ~/Music/Music

plugins: info convert

convert:
  max_bitrate: 320
  never_convert_lossy_files: yes
  copy_album_art: no
  format: mp3
  formats:
    mp3:
      command: ffmpeg -i $source -ab 320k -map_metadata 0 $dest
      extension: mp3
```

It looks like it's due to the  `never_convert_lossy_files` setting. is there a setting that makes it so that it will only transcode *non*-mp3s to mp3, while copying mp3s as they are?
