### ISSUE TITLE
ftintitle does move featured artists to title or drop

### ISSUE THREAD

**Issue by magnumdoomguy** [beetbox/beets#1814]
When running beets 1.3.16 and with the ftintitle plugin enabled, no changes are made to either the artist field or album artist field.  I tested on two machines (with two different OSes -- one debian and one Windows 10), and can't get it to work on either.

Here is the config.yaml I used:

```
directory: /media/b1df2091-533b-4c95-9c19-bd9689b275bf/Beets
library: /beets/music.blb
pluginpath: /beets/plugins
plugins: embedart fetchart ftintitle inline 

art_filename: folder
original_date: yes
per_disc_numbering: yes

ui:
   color: yes

import:
   write: yes
   copy: yes
   move: no
   languages: en

paths:
    default: $albumartist - $album/%if{$multidisc,Disc $disc/}$track $title
item_fields:
    multidisc: 1 if disctotal > 1 else 0

embedart:
   auto: yes
   ifempty: no
   maxwidth: 1000

fetchart:
   auto: yes
   cautious: yes
   maxwidth: 1000
   enforce_ratio: yes
   remote_priority: no

ftintitle:
   auto: yes
   drop: no
```

**Comment by sampsyo** [comment]
Can you please provide complete details about what went wrong? For example, you could show the metadata of a file you want changed (using the `info` plugin), show the output of `beet -vv ftintitle [QUERY]`, and then show the metadata again (to confirm it's unchanged).

**Comment by amishb** [comment]
I think the issue was that running this function on import works as expected. However if you already have imported music and rerun the command, it will not change the title fields.

If that wasn't the issue, then its something I was fixing before i got side tracked. :)

**Comment by afonso360** [comment]
I think i have the same issue ab623 described, running `ftintitle` on a already imported song doesen't update the metadata.

I ran these commands in order:

`beet info "WRLD Feat. As"`
```
/home/afonso/Music/EDM/Monstercat/Monstercat 030 - Finale/WRLD Feat. Ashdown - Everything.mp3
<snip>
            artist: WRLD feat. Ashdown
     artist_credit: WRLD feat. Ashdown
       artist_sort: WRLD feat. Ashdown
<snip>
             title: Everything
<snip>
```


`beet -vv ftintitle "WRLD Feat. As"`
```
user configuration: /home/afonso/.config/beets/config.yaml
data directory: /home/afonso/.config/beets
plugin paths:
Sending event: pluginload
artresizer: method is (2, (6, 9, 8))
library database: /home/afonso/.config/beets/library.db
library directory: /home/afonso/Music
Sending event: library_opened
ftintitle: /home/afonso/Music/EDM/Monstercat/Monstercat 030 - Finale/WRLD Feat. Ashdown - Everything.mp3
ftintitle: no featuring artists found
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: cli_exit
```

`beet info "WRLD Feat. As"`
```
/home/afonso/Music/EDM/Monstercat/Monstercat 030 - Finale/WRLD Feat. Ashdown - Everything.mp3
<snip>
            artist: WRLD feat. Ashdown
     artist_credit: WRLD feat. Ashdown
       artist_sort: WRLD feat. Ashdown
<snip>
             title: Everything
<snip>
```

config:
```
plugins: [
  ftintitle,
  fetchart,
  lastgenre,
  missing,
  badfiles,
  duplicates,
  info,
  permissions,
  embedart,
  scrub
]

directory: ~/Music/
import:
  copy: no

ui:
  color: yes

ftintitle:
  auto: yes

fetchart:
  auto: yes

lastgenre:
  auto: yes

missing:
  format: $albumartist - $album - $title
  count: no
  total: no

permissions:
  file: 644
  dir: 755

embedart:
  compare_threshold: 10
```

**Comment by sampsyo** [comment]
Hmm, interesting… thanks for following up! Can you also include the bit of the `info` output that shows the `albumartist` and related fields? That's used as a signal too to determine whether the featuring artist should be moved.

**Comment by afonso360** [comment]
sure, here is the full output

`beet info "WRLD Feat. As"`
```
/home/afonso/Music/EDM/Monstercat/Monstercat 030 - Finale/WRLD Feat. Ashdown - Everything.mp3
             album: Monstercat 030: Finale
       albumartist: Various Artists
albumartist_credit: Various Artists
  albumartist_sort: Various Artists
       albumstatus: Official
         albumtype: compilation
          arranger:
               art: True
            artist: WRLD feat. Ashdown
     artist_credit: WRLD feat. Ashdown
       artist_sort: WRLD feat. Ashdown
              asin: B06VX54R8R
          bitdepth: 0
           bitrate: 320080
               bpm: 0
        catalognum: MC030
          channels: 2
              comp: True
           country: XW
              date: 2017-02-22
               day: 22
              disc: 1
         disctotal: 1
            format: MP3
             genre: Electronic
            genres: Electronic
             label: Monstercat
          language: eng
            length: 259.2
            lyrics:
  mb_albumartistid: 89ad4ac3-39f7-470e-963a-56509c546377
        mb_albumid: b4036049-e9ab-4174-a409-9f5b057d2577
       mb_artistid: c25a98a2-fa8a-4c7a-a55e-b384234a0e03
 mb_releasegroupid: 713e2720-d25a-4ff0-adef-190e0074b11e
        mb_trackid: 6b952334-9607-4ea2-82cf-3ff9a52309a0
             media: Digital Media
             month: 2
     original_date: 2017-02-22
      original_day: 22
    original_month: 2
     original_year: 2017
        samplerate: 44100
            script: Latn
             title: Everything
             track: 19
        tracktotal: 32
              year: 2017
```
