### ISSUE TITLE
symlinks not created

### ISSUE THREAD

**Issue by dimatter** [beetbox/beets#1820]
```
directory: /media/sf_media/music
library: /root/musiclibrary.blb
import:
    move: no
    copy: no
    link: yes
    write: no
    autotag: yes
    quiet_fallback: asis
plugins: web duplicates fetchart discogs lastgenre
```
what is wrong with the config above?
expected behavior: symlinks of the imported music files inside of /media/sf_media/music
