### ISSUE TITLE
update doesn't actually update

### ISSUE THREAD

**Issue by wrigleyster** [beetbox/beets#1837]
After a fresh timid import without autotagging, running `beet update` reveals a number of entries that need updating. Running `beet update` again reveals that those entries weren't actually updated on the first run of the command.

Doing a new fresh timid import without autotagging, then running `beet update` reveals a different list of entries in need of updating.

'fresh' in this context meaning using a new empty music library database.

I run the newest (1.3.16) version of beets.

**Comment by sampsyo** [comment]
Can you please put together a reproducible test case that we can run locally to see exactly what's going on?

**Comment by wrigleyster** [comment]
I take it that means, beets updates properly when you try? I have attached the config I use... maybe that helps

```
# ~/.config/beets/config.yaml
directory: ~/music
library: ~/.config/beets/musiclib.blb
import:
    move: yes
    timid: yes
    autotag: no
paths:
    albumtype:soundtrack: Soundtracks/$album/$track. $title
    media:podcast: Podcasts/$album/$title
    default: $albumartist/$album%aunique{}/$track. $title
    singleton: Non-Album/$artist/$title%aunique{}
    comp: Compilations/$album%aunique{}/$track. $title
plugins: web bpd duplicates ftintitle
format_item: "$path\n$albumartist : $album : $track/$tracktotal $title"
```
