### ISSUE TITLE
convert: In auto mode, option to keep originals instead of converted files

### ISSUE THREAD

**Issue by carpenike** [beetbox/beets#1840]
Hey All,

I'm looking to use beets to manage my lossless library, but I have devices in the house that do not support high bit-rate formats (Sonos devices). So I'm looking to use Beets to import music into it's database and at the same time create a copy of the Lossless files, convert them into lossy/.mp3 and store in a different location.

Couple questions:
1. Can this all be done with one Beets instance / database or should I use one for the lossy and one for the lossless?
2. How would this be configured? I'm using the below configuration and it only keeps the MP3 version and ignores the FLACs.

```
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: yes
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 5
    copy_album_art: yes
    dest: /music/lossy

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes

replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337
```
