### ISSUE TITLE
lyrics: Use hyphens in place spaces, not underscores, to construct URL for Musixmatch

### ISSUE THREAD

**Issue by Oyashirox** [beetbox/beets#1880]
Hi,

I try to get lyrics for some songs. I know they exist on musixmatch (i.e https://www.musixmatch.com/lyrics/Dead-Astronauts/Part-Two) but beets says : 
> lyrics: lyrics not found: Dead Astronauts - Constellations - Part Two

**Comment by sampsyo** [comment]
Can you please include your configuration and the verbose output?

**Comment by Oyashirox** [comment]
Config.yaml

```
directory: /mnt/MyBook/Musique/beet
library: /mnt/MyBook/Musique/beets-database.db
import:
    link: yes
    write: yes
paths:
    singleton: $artist/Non-Album/$title
plugins: inline web lyrics
lyrics:
    sources: musixmatch

```

Ouput : 
```
beet -v lyrics Part Two
user configuration: /home/pi/.config/beets/config.yaml
data directory: /home/pi/.config/beets
plugin paths:
Sending event: pluginload
library database: /mnt/MyBook/Musique/beets-database.db
library directory: /mnt/MyBook/Musique/beet
Sending event: library_opened
lyrics: failed to fetch: https://www.musixmatch.com/lyrics/Dead_Astronauts/Part_Two (404)
lyrics: lyrics not found: Dead Astronauts - Constellations - Part Two
Sending event: cli_exit
```

So it seems thats spaces should be replace by '-' instead of '_'
