### ISSUE TITLE
Album art left behind in old directory when importing

### ISSUE THREAD

**Issue by AlyxM** [beetbox/beets#1892]
When move-importing, and encountering a directory name that does not match the requirements in my config file, beets will move the music files to a correct path, but leave behind the album art in the old path.

For example, the directory `WRONGDIRNAME 2007 - The Destruction of Small Ideas` contains music and one album art image `cover.jpg`. According to my config file, the directory name should be `2007 - The Destruction of Small Ideas`. When beets imports this directory, it moves all of the music to the correct directory, but leaves behind `cover.jpg` in `WRONGDIRNAME 2007 - The Destruction of Small Ideas`.

```
alyx@shire ~> beet import -P -A ~/Dropbox/media_music/65daysofstatic/
/home/alyx/Dropbox/media_music/65daysofstatic/2004 - The Fall of Math
/home/alyx/Dropbox/media_music/65daysofstatic/WRONGDIRNAME 2007 - The Destruction of Small Ideas
alyx@shire ~> ls -1 Dropbox/media_music/65daysofstatic/
2004 - The Fall of Math/
2007 - The Destruction of Small Ideas/
WRONGDIRNAME 2007 - The Destruction of Small Ideas/
alyx@shire ~> ls Dropbox/media_music/65daysofstatic/WRONGDIRNAME\ 2007\ -\ The\ Destruction\ of\ Small\ Ideas/
cover.jpg
alyx@shire ~> 
```

Config:

```
directory: ~/Dropbox/media_music/
library: ~/.beets.blb

import:
    move: yes

original_date: yes

plugins: inline

paths:
    default: ${albumartist}/${year} - ${album}/%if{$multidisc,CD$disc/}${track} - ${title}

item_fields:
    multidisc: 1 if disctotal > 1 else 0
```

Beets version: 1.3.17
