### ISSUE TITLE
edit plugin fires write events for all tracks in query

### ISSUE THREAD

**Issue by tylerball** [beetbox/beets#1906]
### Problem

I have [a plugin](https://github.com/tylerball/dotfiles/blob/master/home/.config/beets/plugins/git_annex.py) that listens to the `write` event. When I use the `edit` plugin, it fires that event for every track in the query, not just the ones that are actually modified.

Running this command in verbose (`-vv`) mode:

```sh
❯ beet -vv edit todd terje spiral            # some album with two tracks
user configuration: /Users/tball/.config/beets/config.yaml
data directory: /Users/tball/.config/beets
plugin paths: /Users/tball/.config/beets/plugins
Sending event: pluginload
library database: /Users/tball/tunes/beets.db
library directory: /Users/tball/tunes
Sending event: library_opened
Todd Terje - Spiral - Spiral                 # make an edit to a single track
  dj: True
continue [E]diting, Apply, Cancel? a
edit: saving changes to Todd Terje - Spiral - Spiral
Sending event: write
Sending event: after_write
moving /Users/tball/tunes/Todd Terje/Spiral/01 Spiral.m4a to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
edit: saving changes to Todd Terje - Spiral - Q
Sending event: write
Sending event: after_write
moving /Users/tball/tunes/Todd Terje/Spiral/02 Q.mp3 to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: cli_exit
```

### Setup

* OS: El Capitan
* Python version: 2.7.10
* beets version: 1.3.17
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: [
  edit,
]

import:
  move: yes
  incremental: yes

library: ~/tunes/beets.db
directory: ~/tunes/
pluginpath:
  - ~/.config/beets/plugins

embedart:
  auto: yes

convert:
  dest: ~/Downloads

replaygain:
  overwrite: yes

smartplaylist:
  relative_to: ~/tunes
  playlist_dir: ~/.mpd/playlists
  playlists:
    - name: "1-added_this_week.m3u"
      album_query: added:@{1w}..
    - name: "2-added_this_month.m3u"
      album_query: added:@{1m}..

itunescopy:
  auto: yes
  dest: ~/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized

lastgenre:
  count: 3

duplicates:
  keys: [track, title, mb_albumid]

git_annex:
  directory: ~/tunes
```
