### ISSUE TITLE
tmpfs and /tmp complications

### ISSUE THREAD

**Issue by ndouglas** [beetbox/beets#1910]
Related to #1067 and (somewhat) #1382.

I'm importing a pretty large library (~2 TB) on a Synology NAS, which is taking a while.  I've seen this particular issue crop up twice in the course of doing so.

Performance slows to a near standstill.  It'll take twenty minutes to process a single album, and the time will gradually increase.  System load reaches very high levels (10-11 on a 2-core machine).  Beets is stuck in I/O.  Top says kswapd is munching up a whole lot of CPU time.

The issue is resolved essentially instantaneously by removing all cover images from /tmp.  Because #YOLO, I just `rm *.jpg` and boom, Beets starts churning through albums once more, at one a minute or so.

Note that Beets encounters exceptions somewhat often -- 503 status codes from musicbrainz, EOFs to SSL connections, etc.  When this happens, I figure the temp files aren't cleaned up, so they just accumulate.

The problem seems to be that this is an issue with tmpfs and /tmp.  I suspect that, although I have ~500MB free of RAM, the tmpfs RAM disk is causing swapping.  This then results in a performance nightmare.  I'm fuzzy on the details, but this is my best guess.  Obviously this isn't an issue with Beets, but a configuration issue or a clash with the use of tmpfs.

My tentative suggestion is to allow specifying the temporary directory for cover images and so forth.  

This may or may not be worth the time and effort, though -- either no one else has encountered this, or they didn't think it was worth reporting.  I myself hesitated.  But I did want to mention it and see what you thought.

**Comment by sampsyo** [comment]
Whoa, that's certainly a strange issue.

I assume you have `fetchart` enabled, right? Could you please paste your configuration?

It may be as simple as having forgotten to clean up downloaded images in `fetchart`, in which case we should fix that directly—no need to keep those around at all after the album finishes importing.

**Comment by ndouglas** [comment]
Yeah, sorry -- I was filling out the template and managed to accidentally delete it, so I didn't provide all of the relevant information.

````
library: /volume1/music/Beets/library.blb
directory: /volume1/music/
plugins: acousticbrainz badfiles discogs duplicates edit embedart fetchart ftintitle fuzzy info inline lastgenre lyrics mbcollection mbsync missing random smartplaylist the thumbnails types
paths:
        default: Main/%upper{%left{$albumartist_sort,1}}/$albumartist_sort/$original_year - $album%aunique{}/%if{$disc,$disc,01} $track $title
        "comp:true ^albumtype:soundtrack": Compilations/$original_year - $album%aunique{}/%if{$disc,$disc,01} $track $title
        "albumtype:soundtrack": Soundtracks/$original_year - $album%aunique{}/%if{$disc,$disc,01} $track $title
asciify_paths: yes
duplicates:
        album: no
embedart:
        auto: yes
        ifempty: no
fetchart:
        auto: yes
        enforce_ratio: yes
        sources: coverart itunes amazon albumart wikipedia
ftintitle:
        auto: yes
        drop: yes
import:
        move: yes
        write: yes
        log: /volume1/music/Beets/log.txt
        languages: en
        timid: no
lastgenre:
        auto: yes
        count: 5
        force: yes
lyrics:
        auto: yes
        force: yes
        sources: google lyricwiki lyrics.com musixmatch genius
        google_API_key: REDACTED
match:
        strong_rec_thresh: 0.0001
mbcollection:
        auto: yes
musicbrainz:
        user: REDACTED
        pass: REDACTED
original_date: yes
per_disc_numbering: yes
smartplaylist:
        relative_to: /volume1/music
        playlist_dir: /volume1/music/playlists
        playlists:
                - name: all.m3u
                  query: ''
                - name: 'ReleasedIn$year.m3u'
                  query: 'year::[0-9]{4}'
thumbnails:
        auto: yes
        force: yes
types:
        rating: int
````
