### ISSUE TITLE
lyricwiki fails with IndexError: list index out of range

### ISSUE THREAD

**Issue by arogl** [beetbox/beets#1914]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
C:\>beet -vv lyrics artist:"10,000 Maniacs" album:"The Earth Pressed Flat"
user configuration: C:\Users\Andre\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Andre\AppData\Roaming\beets
plugin paths: C:\Users\Andre\AppData\Roaming\beets\beetsplug
Sending event: pluginload
in init Searching amazon
library database: C:\Users\Andre\AppData\Roaming\beets\library.db
library directory: F:\Music\
Sending event: library_opened
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - The Earth Pressed Flat
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Ellen
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Once a City
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Glow
lyrics: failed to fetch: http://lyrics.wikia.com/10%2C000_Maniacs:On_%26_On_%28Mersey_Song%29 (404)
lyrics: failed to fetch: http://lyrics.wikia.com/10%2C000_Maniacs:On_%26_On (404)
lyrics: lyrics not found: 10,000 Maniacs - The Earth Pressed Flat - On & On (Mersey Song)
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Somebody's Heaven
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Cabaret
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Beyond the Blue
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Smallest Step
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - In the Quiet Morning
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Time Turns
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Hidden in My Heart
lyrics: lyrics already present: 10,000 Maniacs - The Earth Pressed Flat - Who Knows Where the Time Goes?
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.18', 'console_scripts', 'beet')()
  File "c:\python27\lib\site-packages\beets\ui\__init__.py", line 1238, in main
    _raw_main(args)
  File "c:\python27\lib\site-packages\beets\ui\__init__.py", line 1228, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "c:\python27\lib\site-packages\beetsplug\lyrics.py", line 607, in func
    opts.force_refetch or self.config['force'],
  File "c:\python27\lib\site-packages\beetsplug\lyrics.py", line 633, in fetch_item_lyrics
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "c:\python27\lib\site-packages\beetsplug\lyrics.py", line 660, in get_lyrics
    lyrics = backend.fetch(artist, title)
  File "c:\python27\lib\site-packages\beetsplug\lyrics.py", line 335, in fetch
    lyrics = scrape_lyrics_from_html(lyrics)
  File "c:\python27\lib\site-packages\beetsplug\lyrics.py", line 433, in scrape_lyrics_from_html
    soup = sorted(soup.stripped_strings, key=len)[-1]
IndexError: list index out of range

```

Led to this problem:

In theory only opening 1 connection to http://lyrics.wikia.com/

```sh
C:\>beet -vv lyrics artist:"10,000 Maniacs" album:"The Earth Pressed Flat" title:"On & On (Mersey Song)"
user configuration: C:\Users\Andre\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Andre\AppData\Roaming\beets
plugin paths: C:\Users\Andre\AppData\Roaming\beets\beetsplug
Sending event: pluginload
in init Searching amazon
library database: C:\Users\Andre\AppData\Roaming\beets\library.db
library directory: F:\Music\
Sending event: library_opened
lyrics: failed to fetch: http://lyrics.wikia.com/10%2C000_Maniacs:On_%26_On_%28Mersey_Song%29 (404)
lyrics: failed to fetch: http://lyrics.wikia.com/10%2C000_Maniacs:On_%26_On (404)
lyrics: lyrics not found: 10,000 Maniacs - The Earth Pressed Flat - On & On (Mersey Song)
Sending event: cli_exit
```

### Setup

* OS: win10_x64
* Python version: 2.7.11
* beets version: GIt as of c9be5bc7d14865ff3d00628dc0cc7e07d71ed1c3
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    sources: [lyricwiki]
    fallback: ''
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    force: no
    auto: yes
    genius_api_key: REDACTED
importadded:
    preserve_mtimes: yes
fetchart:
    auto: yes
    cautious: yes
    cover_names: cover front art album folder
    google_search: no
    minwidth: 0
    enforce_ratio: no
    remote_priority: no
    sources: coverart itunes albumart amazon google wikipedia
    google_engine: REDACTED
    maxwidth: 0
    google_key: REDACTED
duplicates:
    album: no
    checksum: ffmpeg -i {file} -f crc -
    copy: none
    count: no
    delete: no
    format: $albumartist - $album - $title
    full: no
    strict: no
    keys: [mb_trackid, mb_albumid]
    move: none
    path: no
    tag: ''
    tiebreak: {}
    merge: no
embedart:
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    maxwidth: 0
replace:
    '[\\/]': ''
    ^\.: ''
    '[\x00-\x1f]': ''
    '[<>:\"\?\*\|]': ''
    \.$: ''
    \s+$: ''
    ^\s+: ''
    "\\\u201C": ''
    "\\\u201D": ''
    \`: ''''
    "\\\u2019": ''''
replaygain:
    overwrite: no
    auto: yes
    command: c:\agrbin\aacgain.exe
    targetlevel: 89
    backend: command
    noclip: yes
copyartifacts:
    extensions: .pdf
    print_ignored: no
pluginpath: C:\Users\Andre\AppData\Roaming\beets\beetsplug

plugins: chroma discogs lastgenre mbsync fetchart embedart replaygain duplicates missing info scrub zero fromfilename amazon ftintitle copyartifacts importadded lyrics
scrub:
    auto: yes
check:

    import: yes
    write-check: yes
    write-update: yes
    convert-update: yes
    threads: 4

paths:
    default: '%upper{%left{$albumartist,1}}/$albumartist/($year) $album%aunique{}/$album - $track - $artist - $title'
    singleton: Singles/$artist - $title
    albumtype:soundtrack: Soundtracks/($year) $album%aunique{}/$album - $track - $artist - $title
    albumartist:various\ artists: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
    albumartist:various: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
    comp: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
convert:
    ffmpeg: c:\agrbin\bin\ffmpeg.exe
    embed: yes
    format: mp3
    max_bitrate: 192
    dest: '%upper{%left{$albumartist,1}}/$albumartist/($year) $album%aunique{}/$album - $track - $artist - $title'
    threads: 4

    paths:
        default: '%upper{%left{$albumartist,1}}/$albumartist/($year) $album%aunique{}/$album - $track - $artist - $title'
threaded: no
art_filename: cover
id3v23: no
zero:
    fields: month day genre comments
    comments:
    - EAC
    - LAME
    - from.+collection
    - ripped by
    update_database: no
    keep_fields: []
amazon:
    Access_Key_ID:  REDACTED
    Secret_Access_Key:  REDACTED
    asso_tag: beets
    source_weight: 0.3
ignore: .AppleDouble ._* *~ .DS_Store *.sfv *.srr *.nfo *.m3u

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: yellow
directory: \\?\F:\Music\

import:
    copy: no
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: F:\new_Music\beetslog.txt
    languages: en
acoustid:
    apikey: REDACTED
lastgenre:
    count: 1
    source: album
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
chroma:
    auto: yes
missing:
    count: no
    total: no
```
