### ISSUE TITLE
Beets incorrectly renames tracks

### ISSUE THREAD

**Issue by mjepronk** [beetbox/beets#1923]
### Problem

Beets automatically renamed two tracks, altough both already had the correct name (see output of Beets below).

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import Sound\ Tribe\ Sector\ 9 
```

Led to this problem:

```
/run/media/mp/External Storage/Music to Import/Electronic/Sound Tribe Sector 9/Peaceblaster (15 items)
Tagging:
    Sound Tribe Sector 9 - Peaceblaster
URL:
    http://musicbrainz.org/release/e3faf46c-d242-480e-b4ec-e8b5ed00a974
(Similarity: 97.9%) (tracks) (2008)
 * Peaceblaster '08 (#2) -> Peaceblaster '68 (#1) (index, title)
 * Peaceblaster '68 (#1) -> Peaceblaster '08 (#2) (index, title)
```

### Setup

* OS: Fedora release 23
* Python version: 2.7.10
* beets version: 1.3.17
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /run/media/mp/External Storage/Music/
library: ~/.config/beets/library.db
import:
  move: yes
  log: ~/.config/beets/import.log
plugins: missing info web
convert:
  auto: no
paths:
  singleton: $artist/Non-Album/$title
  comp:      1_Compilations/$album%aunique{}/$title
clutter:
  - Thumbs.DB
  - Desktop.ini
  - .mediaartlocal
  - .DS_Store
  - .AppleDouble
  - '*.jpg'
  - '*.jpeg'
  - '*.m3u'
  - '*.cue'
  - '*.nfo'
  - '*.txt'
  - '*.sfv'
  - '*.log'
```
