### ISSUE TITLE
Folders are not being created with album names

### ISSUE THREAD

**Issue by zbaylin** [beetbox/beets#1931]
### Problem

I organize my beets library with the -A tag when importing. My music is organized by artist -> album -> songs. Many of my album folders are being named "artist - Disk#". When I lookup the album names within "beet ls", the actual album name is displayed.

Here's a link to the music files that trigger the bug (if relevant): 
[http://zbaylin.duckdns.org/01%20Black%20Cow.flac](url)
### Setup
- OS: Ubuntu Server 14.04
- Python version: 2.7.6
- beets version: 1.3.17
- Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

``` yaml
plugins: fetchart

directory: /home/zbaylin/Music/
library: /home/zbaylin//Music/blibrary.blb
import:
    move: no
    copy: no
    write: no
    link: yes
```

**Comment by sampsyo** [comment]
Can you please include the exact filenames you're seeing? Use `beet list -p` to get filenames.

**Comment by lordfiend** [comment]
I can confirm that I am having a similar issue. When I try to import, I just see the files with no or incomplete names. Files are not placed in directory either. For example:

If I run import on "1967 - fred neil", the destination folder has all the tracks, all are incompletely labelled and are not in directory.

`beet list -p` yields:

> 01 The .mp3
> 02 I've Got a Secret (Didn't We Shake That .mp3
> 03 That's the Ba.mp3
> 04 .mp3
> 05 Faretheewell (Fred.mp3
> 06 Everybody's.mp3
> 07 Everything.mp3
> 08 Sweet.mp3
> 09 Green R.mp3
> 10 Cynicrustpetefred.mp3

My config file for reference reads:
```
ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: darkred
        text_highlight_minor: lightgray
        action_default: magenta
        action: teal
directory: ~/Music
library: ~/.config/beets/library.db
import:
  copy: yes
plugins: lastgenre chroma
chroma:
    auto: yes
```
