### ISSUE TITLE
ReplayGain backend bs1770gain is not supported

### ISSUE THREAD

**Issue by mcrozz** [beetbox/beets#1932]
### Why bs1770gain isn't supported?

```sh
$ beet -vv replaygain
```

Led to this problem:

```
user configuration: /home/rozz/.config/beets/config.yaml
data directory: /home/rozz/.config/beets
Sending event: pluginload
error: Selected ReplayGain backend bs1770gain is not supported. Please select one of: gstreamer, command
```

### Setup

* OS: Ubuntu (as server)
* Python version: 2.7
* beets version: 1.3.8
* Turning off plugins made problem go away: yes
* bs1770gain version: 0.4.9

### Config

```yaml
directory: /home/rozz/music
library: /home/rozz/music/indexedMusic.blb
import:
  copy: no
replaygain:
#  backend: bs1770gain
  auto: yes
  overwrite: yes
  albumgain: yes
plugins: spotify keyfinder bpm replaygain
spotify:
  mode: open
  region_filter: US
keyfinder:
  auto: yes
  overwrite: yes
art_filename: folder
original_date: yes
threaded: yes
id3v23: yes
```
