### ISSUE TITLE
Feature request: beet command line should work with unix pipes

### ISSUE THREAD

**Issue by moorepants** [beetbox/beets#1952]
### Problem

I expected this to work:

```
(beets)moorepants@parvati:~$ find ~/music-src -name "*Spotless*"
/home/moorepants/music-src/E.L.O_/Eternal Sunshine Of The Spotless Mind
/home/moorepants/music-src/Lata Mangeshkar/Eternal Sunshine Of The Spotless Mind
(beets)moorepants@parvati:~$ find ~/music-src -name "*Spotless*" | beet import
error: no path specified
```

but it doesn't.

### Setup

* OS: Ubuntu 16.04
* Python version: 2.7.11
* beets version: 1.3.17
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
(beets)moorepants@parvati:~$ beet config
directory: ~/Music

import:
    write: yes
    move: yes

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
library: ~/Music/beets-library.db

plugins: chroma fetchart lastgenre fromfilename duplicates
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
lastgenre:
    count: 1
    source: album
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
chroma:
    auto: yes
fetchart:
    minwidth: 0
    sources:
    - coverart
    - itunes
    - amazon
    - albumart
    cautious: no
    google_engine: 001442825323518660753:hrh5ch1gjzm
    maxwidth: 0
    google_key: REDACTED
    auto: yes
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    remote_priority: no
    enforce_ratio: no


```
