### ISSUE TITLE
convert: can't pipe the command

### ISSUE THREAD

**Issue by xeverse** [beetbox/beets#1971]
### Problem

Can't pipe the convert command.
https://stackoverflow.com/questions/2475843/pipe-ffmpeg-to-oggenc2-with-net#2475843

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv convert rising 
```

Led to this problem:

```
convert: Command ffmpeg -i /home/xxx/Music/ElectricUniverse/1997Stardiver/04TheRisingSun.mp3 -y -vn -f flac - | oggenc - -o /home/xxx/Music/conv/ElectricUniverse/1997Stardiver/04TheRisingSun.ogg -q-1 exited with status 1
```

### Setup

* OS: Linux 4.4.0-4-ARCH
* Python version: Python 2.7.11
* beets version: beets version 1.3.17
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
plugins: replaygain convert
convert:
    formats:
        ogg:  ffmpeg -i $source -y -vn -f flac - | oggenc - -o $dest -q-1
```
