### ISSUE TITLE
Very slow on mounted volume on Mac (due to SQLite)

### ISSUE THREAD

**Issue by zzolo** [beetbox/beets#1976]
First let me just say that `beets` is amazing.  I just started using it a few days ago and am totally in love.

### Problem

Not sure this is really specific to beets, but running beets with a mounted volume is extremely slow on a Mac, due to SQLite slowness.  I have my music library, database, and config on a NAS that gets mounted to my Mac and am running the `beet` command locally on the Mac.  It is extremely slower than if the library is local.

```sh
$ time beet -c /Volumes/Multimedia/tunes/beets.conf -vv import /Volumes/Multimedia/tunes-old/albums/W/Wilco/Summer\ Teeth/
[...]
real	7m35.727s
```

```sh
$ time beet -l ./test-beets.db -d ./test-beets-lib/ -vv import /Volumes/Multimedia/tunes-old/albums/W/Wilco/Summer\ Teeth/ -I
[...]
real	0m47.539s
```

So, I am wondering if anyone else has run into this (I don't think this is a really weird situation)?  And if so, is there a work around that doesn't involve storing my beets database locally.  And if not, there is some threads on the internet suggesting that some SQLite config might be able to get things going a bit fast, so any pointers on where I might try to put those for a pull request would be helpful.

Thanks!

### Setup

* OS: Mac OSX 10.11.4 and QNAP NAS
* Python version: 2.7.10
* beets version: 1.3.17
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

As you can see, there are plugins installed that fetch other stuff, but that would not explain an almost 10x increase in speed.
```yaml
directory: /Volumes/Multimedia/tunes/
library: /Volumes/Multimedia/tunes/beets.db

import:
  move: no
  incremental: yes

paths:
  default: albums/%upper{%left{$artist_ranked,1}}/$artist_ranked/$album%aunique{}/$track - %if{$different_artist,$artist - }$title
  singleton: loose/$artist - $title
  comp: compilations/$album%aunique{}/$track - $artist - $title
  albumtype:soundtrack: soundtracks/$album%aunique{}/$track - $artist - $title

plugins: acousticbrainz fetchart lyrics lastgenre inline embedart

item_fields:
  artist_ranked: albumartist_sort if albumartist_sort else albumartist if albumartist else artist
  different_artist: True if albumartist != artist and not comp else False

embedart:
  maxwidth: 800
```
