### ISSUE TITLE
ftintitle does not seem to work anymore

### ISSUE THREAD

**Issue by arogl** [beetbox/beets#1983]
### Problem

When enabling the ftintitle plugin the featured artist is not moved to the title 

Running this command in verbose (`-vv`) mode:

``` sh
C:\>beet -vv ls artist:feat
user configuration: C:\Users\Andre\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Andre\AppData\Roaming\beets
plugin paths: C:\Users\Andre\AppData\Roaming\beets\beetsplug
Sending event: pluginload
in init Searching amazon
library database: C:\Users\Andre\AppData\Roaming\beets\library.db
library directory: F:\Music\
Sending event: library_opened
Betatraxx feat. Marina and the Diamonds - Electra Heart - Electra Heart
Ariana Grande feat. Iggy Azalea - Problem - Problem
Austin Mahone feat. Pitbull - Mmm Yeah - Mmm Yeah
Sending event: cli_exit

C:\>beet -vv ls artist:feat -f $artist
user configuration: C:\Users\Andre\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Andre\AppData\Roaming\beets
plugin paths: C:\Users\Andre\AppData\Roaming\beets\beetsplug
Sending event: pluginload
in init Searching amazon
library database: C:\Users\Andre\AppData\Roaming\beets\library.db
library directory: F:\Music\
Sending event: library_opened
Betatraxx feat. Marina and the Diamonds
Ariana Grande feat. Iggy Azalea
Austin Mahone feat. Pitbull
Sending event: cli_exit

C:\>beet -vv ftintitle artist:feat
user configuration: C:\Users\Andre\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Andre\AppData\Roaming\beets
plugin paths: C:\Users\Andre\AppData\Roaming\beets\beetsplug
Sending event: pluginload
in init Searching amazon
library database: C:\Users\Andre\AppData\Roaming\beets\library.db
library directory: F:\Music\
Sending event: library_opened
Sending event: database_change
Sending event: write
Sending event: after_write
importadded: Write of item 'F:\Music\B\Betatraxx feat. Marina and the Diamonds\(2014) Electra Heart\Electra Heart - 01 - Betatraxx feat. Marina and the Diamonds - Electra Heart.m4a', selected item.added
=1461902893.24
Sending event: database_change
Sending event: write
Sending event: after_write
importadded: Write of item 'F:\Music\A\Ariana Grande feat. Iggy Azalea\(2014) Problem\Problem - 01 - Ariana Grande feat. Iggy Azalea - Problem.mp3', selected item.added=1458646013.22
Sending event: database_change
Sending event: write
Sending event: after_write
importadded: Write of item 'F:\Music\A\Austin Mahone feat. Pitbull\(2014) Mmm Yeah\Mmm Yeah - 01 - Austin Mahone feat. Pitbull - Mmm Yeah.mp3', selected item.added=1461907788.15
Sending event: cli_exit

C:\>beet -vv ls artist:feat -f $artist
user configuration: C:\Users\Andre\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Andre\AppData\Roaming\beets
plugin paths: C:\Users\Andre\AppData\Roaming\beets\beetsplug
Sending event: pluginload
in init Searching amazon
library database: C:\Users\Andre\AppData\Roaming\beets\library.db
library directory: F:\Music\
Sending event: library_opened
Betatraxx feat. Marina and the Diamonds
Ariana Grande feat. Iggy Azalea
Austin Mahone feat. Pitbull
Sending event: cli_exit

```

Led to this problem:

The final ls shoud have lead to this output

No artists listed

``` shell

C:\>beet -vv ls artist:feat -f $artist
user configuration: C:\Users\Andre\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Andre\AppData\Roaming\beets
plugin paths: C:\Users\Andre\AppData\Roaming\beets\beetsplug
Sending event: pluginload
in init Searching amazon
library database: C:\Users\Andre\AppData\Roaming\beets\library.db
library directory: F:\Music\
Sending event: library_opened
Sending event: cli_exit
```
### Setup
- OS: Windows 10_x64
- Python version: 2.7.11
- beets version: bf29c24
- Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

``` yaml
importadded:
    preserve_mtimes: yes
lyrics:
    fallback: ''
    sources: musixmatch lyrics.com lyricwiki
    google_API_key: REDACTED
    google_engine_ID: REDACTED
fetchart:
    auto: yes
    cautious: yes
    cover_names: cover front art album folder
    google_search: no
    minwidth: 0
    enforce_ratio: no
    sources: coverart itunes albumart amazon google wikipedia
duplicates:
    album: no
    checksum: ffmpeg -i {file} -f crc -
    copy: none
    count: no
    delete: no
    format: $albumartist - $album - $title
    full: no
    strict: no
    keys: [mb_trackid, mb_albumid]
    move: none
    path: no
embedart:
    auto: yes
replace:
    '[\\/]': ''
    ^\.: ''
    '[\x00-\x1f]': ''
    '[<>:\"\?\*\|]': ''
    \.$: ''
    \s+$: ''
    ^\s+: ''
    "\\\u201C": ''
    "\\\u201D": ''
    \`: ''''
    "\\\u2019": ''''
replaygain:
    overwrite: no
    auto: yes
    command: c:\agrbin\aacgain.exe
copyartifacts:
    extensions: .pdf
    print_ignored: no
pluginpath: C:\Users\Andre\AppData\Roaming\beets\beetsplug

plugins: ftintitle
scrub:
    auto: yes
check:

    import: yes
    write-check: yes
    write-update: yes
    convert-update: yes
    threads: 4
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}

paths:
    default: '%upper{%left{$albumartist,1}}/$artist/($year) $album%aunique{}/$album - $track - $artist - $title'
    singleton: Singles/$artist - $title
    "albumartist:\\\u201CWeird Al\\\u201D Yankovic": W/Weird Al Yankovic/($year) $album%aunique{}/$album - $track - $artist - $title
    albumtype:soundtrack: Soundtracks/($year) $album%aunique{}/$album - $track - $artist - $title
    albumartist:various\ artists: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
    albumartist:various: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
    comp: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
threaded: no
art_filename: cover
id3v23: no
zero:
    fields: comments
    comments:
    - EAC
    - LAME
    - from.+collection
    - ripped by
amazon:
    Access_Key_ID: REDACTED
    Secret_Access_Key: REDACTED
    asso_tag: beets
ignore: .AppleDouble ._* *~ .DS_Store *.sfv *.srr *.nfo *.m3u *.ini

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: yellow
directory: \\?\F:\Music\

import:
    copy: no
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: F:\new_Music\beetslog.txt
    languages: en
acoustid:
    apikey: REDACTED

```
