### ISSUE TITLE
Question about iHate plugin

### ISSUE THREAD

**Issue by JokerQyou** [beetbox/beets#2003]
### Problem

When I was reading the documentation I did see a statement like this: `The plugin trusts your decision in “as-is” imports.` ([iHate plugin](http://beets.readthedocs.io/en/v1.3.17/plugins/ihate.html#configuration)) However I don't think I fully understand it.

When unning this command in verbose (`-vv`) mode:

```zsh
$ beet -vv import -A --pretend ~/Downloads
```

Led to this problem:

```
user configuration: /Users/joker/.config/beets/config.yaml
data directory: /Users/joker/.config/beets
plugin paths: /Users/joker/Library/Python/2.7/lib/python/site-packages/beetsplug
Sending event: pluginload
library database: /Users/joker/Documents/MusicLibrary.blb
library directory: /Users/joker/Music/Library
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Album: /Users/joker/Downloads
  /Users/joker/Downloads/待到出梅后.mp3
Sending event: import
Sending event: cli_exit
```

### Setup

* OS: Mac OS X 10.11.4
* Python version: Python 2.7.10 (shipped from Apple)
* beets version: 1.3.17
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml

paths:
    default: $albumartist - $album%aunique{}/$track $title
    singleton: $artist - $title [EP]%aunique{}/$title
    comp: $albumartist -$album%aunique{}/$track $title

format_item: "$title - \u300C$album\u300Dby $artist"
library: ~/Documents/MusicLibrary.blb
replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
    ^\s+: ''
ignore:
- .*
- '*~'
- System Volume Information
- '*.mp4'
- '*.ogg'
- '*.mov'
- '*.3gp'
- '*.avi'
- '*.webm'
- '*.mkv'
ihate:
    skip: ['title::^$', 'artist::^$', 'album::^$']
    warn: []
pluginpath: [/Users/joker/Library/Python/2.7/lib/python/site-packages/beetsplug]

plugins: ihate
directory: ~/Music/Library

import:
    timeid: yes
    group_albums: yes
    resume: ask
```

Now, my problem is, I'm trying to find a way to prevent beet from importing any music file which lacks any of these basic metadata: title, artist and title. I roughly read the source code of iHate plugin and saw it registered a listener for `import_task_choice` event but not for other events.
And my questions are:
- Is my goal achievable?
- If so, how should I use iHate plugin to do this?
- If not, is it that I'm using iHate the wrong way?

Thanks.
