### ISSUE TITLE
`beet rm -d` supports only removal of one album at the time when passing dirpaths 

### ISSUE THREAD

**Issue by bartkl** [beetbox/beets#2009]
### `beet rm -d` supports only removal of one album at the time when passing dirpaths 

Running this command in verbose (`-vv`) mode:

```sh
$ cd /volume1/music/beets
$ beet -vv rm -d Bert\ Jansch/ Shirley\ Collins\ \&\ The\ Albion\ Band/
```

Led to this problem:

```sh
user configuration: /var/services/homes/bart/.config/beets/config.yaml
data directory: /var/services/homes/bart/.config/beets
plugin paths: 
Sending event: pluginload
library database: /var/services/homes/bart/.config/beets/library.blb
library directory: /volume1/music/beets
Sending event: library_opened
error: No matching items found.
```

Passing a single path argument works just fine:

```sh
NastyNAS> beet -vv rm -d Shirley\ Collins\ \&\ The\ Albion\ Band/
```

Result:

```sh
user configuration: /var/services/homes/bart/.config/beets/config.yaml
data directory: /var/services/homes/bart/.config/beets
plugin paths: 
Sending event: pluginload
library database: /var/services/homes/bart/.config/beets/library.blb
library directory: /volume1/music/beets
Sending event: library_opened

/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/01 - Claudy Banks.flac - Claudy Banks
/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/02 - The Little Gypsy Girl.flac - The Little Gypsy Girl
/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/03 - Banks of the Bann.flac - Banks of the Bann
/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/04 - Murder of Maria Marten.flac - Murder of Maria Marten
/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/05 - Van Dieman's Land.flac - Van Dieman's Land
/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/06 - Just as the Tide Was A'Flowing.flac - Just as the Tide Was A'Flowing
/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/07 - The White Hare.flac - The White Hare
/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/08 - Hal-An-Tow.flac - Hal-An-Tow
/volume1/music/beets/Shirley Collins & The Albion Band/1971 - No Roses/09 - Poor Murdered Woman.flac - Poor Murdered Woman
Really DELETE 9 files (y/n)? 
```

Would come in handy if this got fixed, since sometimes good ol' bash globbing and _TAB_ completion beats querying in terms of ease of use.

Thanks!

### Setup
* System: Synology DS214 (cpu architecture: armv7l)
* OS: DSM 6.0-7321 Update 6
* Python version: 2.7.11
* beets version: 1.3.17
* Turning off plugins made problem go away (yes/no): no 

My configuration (output of `beet config`) is:

```yaml
directory: /volume1/music/beets
library: ~/.config/beets/library.blb
original_date: yes
per_disc_numbering: no
art_filename: folder
va_name: 'Various Artists'

import:
    copy: yes
    write: true
    resume: true
    quiet_fallback: skip
    log: /var/log/beets/beets.log

match:
    strong_rec_thresh: 0.96

paths:
    default: $albumartist/$year - %title{$album %aunique{albumartist album year, albumtype label catalognum albumdisambig}}/$track - $title
    singleton: __Loose Songs__/$artist - $title
    comp: __Various Artists__/$year - %title{$album %aunique{album year, label catalognum albumdisambig}}/$track - $artist - $title
```
