### ISSUE TITLE
incorrect FLAC tracknumbers

### ISSUE THREAD

**Issue by sentriz** [beetbox/beets#2073]
### Problem

FLAC albums seem to show incorrect tracknumbers in software such as ncmpcpp.

* OS: Manjaro Linux
* Python version: Python 2.7.9
* beets version: version 1.3.18 w/ plugins: edit, embedart, fetchart, info, inline, mpdupdate, smartplaylist, the, zero
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /media/dynamic
ignore_hidden: yes
per_disc_numbering: yes
art_filename: folder
original_date: yes
asciify_paths: yes

format_item: $album / $track($tracktotal) $artist - $title
format_album: ($year) $albumartist - $album

import:
    copy: no
    write: yes
    resume: ask
    move: yes
    detail: yes

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue


replace:
    '\s/\s': ' and '
    '[\\/]': ' '
    '^\.': ''
    '[\x00-\x1f]': ''
    '[<>:"\?\*\|]': ''
    '\.$': ''
    '\s+$': ''
    '^\s+': ''


paths:
    singleton:True: music_singles/[$bitrate] $artist - $title
    comp: music_compilation/($year) $album%if{$multidisc, (disc $disc)}/$track($tracktotal) $title
    synced:True: music_synced/$albumartist/($year) $album%if{$multidisc, (disc $disc)}/$track($tracktotal) $title
    default: music_nonsynced/$albumartist/($year) $album%if{$multidisc, (disc $disc)}/$track($tracktotal) $title

plugins:
    - the
    - zero
    - mpdupdate
    - fetchart
    - embedart
    - inline
    - smartplaylist
    - edit
    - info

lastfm:
    user: sentriz

mpd:
    host: 10.0.0.2
    port: 6600

smartplaylist:
    playlist_dir: /media/dynamic/music_playlists/
    playlists:
        - name: sixty_seven.m3u
          query: 'year:1967 singleton: albumartist+ album+ track+'
        - name: recently_added.m3u
          query: 'added:2016-06-14.. singleton: added- album+ track+'
        - name: synced_60s.m3u
          query: 'year:1960..1969 singleton: synced:True year+ album+ albumartist+ track+'
        - name: synced_70s.m3u
          query: 'year:1970..1979 singleton: synced:True year+ album+ albumartist+ track+'
        - name: synced_80s.m3u
          query: 'year:1980..1989 singleton: synced:True year+ album+ albumartist+ track+'
        - name: synced_90s.m3u
          query: 'year:1990..1999 singleton: synced:True year+ album+ albumartist+ track+'
        - name: synced_100s.m3u
          query: 'year:2000..2009 singleton: synced:True year+ album+ albumartist+ track+'
        - name: synced_110s.m3u
          query: 'year:2010..2019 singleton: synced:True year+ album+ albumartist+ track+'

item_fields:
    multidisc: 1 if disctotal > 1 else 0

fetchart:
    art_filename: folder.jpeg
    maxwidth: 400
    minwidth: 400

edit:
    itemfields: track tracktotal title artist album
    albumfields: album albumartist year
    ignore_fields: id path

zero:
    update_database: true
    keep_fields:
        - title
        - artist
        - albumartist
        - album
        - year
        - track
        - tracktotal
        - disc
        - disctotal
        # extra
        - bpm
        - comp
```

screenshot of an mp3 album: 
![20160622_120939](https://cloud.githubusercontent.com/assets/6832539/16264764/43f4be16-3873-11e6-9950-c33f9d8fdf58.png)

screenshot of a FLAC album:
![20160622_120935](https://cloud.githubusercontent.com/assets/6832539/16264773/4f8db08e-3873-11e6-8891-5741a65005af.png)

note that FLAC tracknumbers appear as "tracknumber | tracknumber", instead of "tracknumber" like the mp3s.

beet ls of of those two albums:
![20160622_121255](https://cloud.githubusercontent.com/assets/6832539/16264809/80fc940a-3873-11e6-9b2a-3fad67f7fda3.png)

Thank you,
Senan.
