### ISSUE TITLE
Unable to select choice on input

### ISSUE THREAD

**Issue by mtompkins** [beetbox/beets#2079]
### Problem

After initial configuration, I am unable to make a choice when presented the candidates. I've tried this in terminal, terminal in screen, and various users with permissions.

I tried installing through apt as well as pip.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (import /music/path.. )
```

Led to this problem:

```
Initial install and import.
```

### Setup

* OS: Ubuntu 16.04
* Python version: 2.7.11+
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/volume/media/music

import:
    copy: no
library: ~/.beetdata/musiclibrary.blb

plugins: chroma duplicates
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
chroma:
    auto: yes

```
