### ISSUE TITLE
Beets shows the wrong config file in verbose mode when it is specified from the command line

### ISSUE THREAD

**Issue by MolarAmbiguity** [beetbox/beets#2084]
### Problem

Running this command in verbose (`-vv`) mode:

``` sh
$ beet -vv -c /home/jack/Music/config.yaml ls
user configuration: /home/jack/.config/beets/config.yaml
data directory: /home/jack/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/jack/Music/library.blb
library directory: /home/jack/Music
Sending event: library_opened
Sending event: cli_exit
```

(`beet ls` doesn't output anything because this testing library is empty)
The issue is not beets loading the wrong config file. I verified this by turning off colour in my test config and doing `beet import`. What each config file is named doesn't affect the issue.
### Setup
- OS: Korora 23
- Python version: 2.7.11
- beets version: 1.3.18
- Turning off plugins made problem go away (yes/no): 
  no 

Main config (in /home/jack/.config/beets/config.yaml):

``` yaml
plugins: fetchart duplicates play web acousticbrainz
directory: /mnt/usb-Seagate_Expansion_Desk_NA4M79J2-0:0-part1/Musak
library: /mnt/usb-Seagate_Expansion_Desk_NA4M79J2-0:0-part1/Musak/newLibrary.blb
import:
    move: yes
per_disc_numbering: yes 

paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
    singleton: $albumartist/$title
musicbrainz:
    searchlimit: 10

match:
    preferred:
        countries: ['AU']
        media: ['CD', 'Digital Media|File']

```

Test config (in /home/jack/Music/config.yaml):

``` yaml
directory: /home/jack/Music/
library: /home/jack/Music/library.blb
import:
    move: yes
paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
    singleton: $albumartist/$title

ui:
    color: no
```
