### ISSUE TITLE
Lower accuracy with additions files

### ISSUE THREAD

**Issue by BlackLotus** [beetbox/beets#2100]
### Problem
When additional files exist in a directory the similarity decreases, even if 100% of the album exists.
Led to this problem:
Many things one of which was an old beets setup that added files renamed (replaced ' through ´) and added tracks twice (selected keep both) left the library in a state with duplicates.

### Setup
beet version 1.3.18
My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    bing_client_secret: REDACTED
    google_API_key: REDACTED
    force: no
    google_engine_ID: REDACTED
    sources:
    - google
    - lyricwiki
    - lyrics.com
    - musixmatch
    auto: yes
    fallback:
    genius_api_key: REDACTED
    bing_lang_to:

paths:
    default: $albumartist/$album/$track - $title
    singleton: Singletons/$artist - $title
    comp: $genre/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
threaded: yes
art_filename: albumart
chroma:
    auto: yes
library: /mnt2/beets-music.blb

ui:
    color: yes

plugins: bpd web chroma fromfilename embedart fetchart lyrics replaygain scrub duplicates
directory: /mnt2/Musik

import:
    copy: no
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
    art: yes
group_albums: yes

match:
    strong_rec_thresh: 0.05
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
scrub:
    auto: yes
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
replaygain:
    targetlevel: 89
    auto: yes
    overwrite: no
    backend: command
    command: ''
    noclip: yes
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
bpd:
    volume: 100
    host: ''
    password: REDACTED
    port: 6600
```
Here is an example
```
[thomas@GamePi Music-new]$ beet import NOFX/

/mnt2/Meine Musik/Music-new/NOFX/The Greatest Songs Ever Written (By Us) (30 items)
Tagging:
    NOFX - The Greatest Songs Ever Written (By Us)
URL:
    http://musicbrainz.org/release/093e6d8b-bfc0-4ea3-bcd1-9a3f30d5cdc1
(Similarity: 97.5%) (unmatched tracks) (CD, 2004, US, Epitaph)
 * It’s My Job to Keep Punk Rock Elite -> It’s My Job to Keep Punkrock Elite
Unmatched tracks (3):
 ! The Separation of Church and Skate (#4) (2:50)
 ! What’s the Matter With Kids Today? (#10) (1:14)
 ! It’s My Job to Keep Punkrock Elite (#24) (1:24)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? B
[thomas@GamePi Music-new]$ ls NOFX/The\ Greatest\ Songs\ Ever\ Written\ \(By\ Us\)/
'01 - Dinosaurs Will Die.mp3'                  '08 - 180 Degrees.mp3'                         '15 - Green Corn.mp3'                  '23 - Shut Up Already.mp3'
'02 - Linoleum.mp3'                            '09 - Party Enema.mp3'                         '16 - The Longest Line.mp3'            '24 - It’s My Job to Keep Punkrock Elite.mp3'
'03 - Bob.mp3'                                 '10 - What’s the Matter With Kids Today_.mp3'  '17 - Thank God It’s Monday.mp3'       '24 - It’s My Job to Keep Punk Rock Elite.mp3'
'04 - The Separation of Church and Skate.mp3'  '10 - What’s the Matter With Kids Today.mp3'   '18 - The Idiots Are Taking Over.mp3'  '25 - Franco Un-American.mp3'
'04 - The Seperation of Church & Skate.mp3'    '11 - Reeko.mp3'                               '19 - Don’t Call Me White.mp3'         '26 - Kill All the White Man.mp3'
'05 - Murder the Government.mp3'               '12 - Stickin’ in My Eye.mp3'                  '20 - Day to Daze.mp3'                 '27 - Wore Out the Soles of My Party Boots.mp3'
'06 - Bleeding Heart Disease.mp3'              '13 - All Outta Angst.mp3'                     '21 - Soul Doubt.mp3'                  cover.jpg
'07 - Bottles to the Ground.mp3'               '14 - Leave It Alone.mp3'                      '22 - Philthy Phil Philantropist.mp3'
[thomas@GamePi Music-new]$ mv NOFX/The\ Greatest\ Songs\ Ever\ Written\ \(By\ Us\)/10\ -\ What’s\ the\ Matter\ With\ Kids\ Today_.mp3 NOFX/The\ Greatest\ Songs\ Ever\ Written\ \(By\ Us\)/04\ -\ The\ Seperation\ of\ Church\ \&\ Skate.mp3 NOFX/The\ Greatest\ Songs\ Ever\ Written\ \(By\ Us\)/24\ -\ It’s\ My\ Job\ to\ Keep\ Punk\ Rock\ Elite.mp3 backup/
[thomas@GamePi Music-new]$ beet import NOFX/

/mnt2/Meine Musik/Music-new/NOFX/The Greatest Songs Ever Written (By Us) (27 items)
Tagging:
    NOFX - The Greatest Songs Ever Written (By Us)
URL:
    http://musicbrainz.org/release/093e6d8b-bfc0-4ea3-bcd1-9a3f30d5cdc1
(Similarity: 100.0%) (tracks) (CD, 2004, US, Epitaph)
 * The Separation of Church and Skate -> The Seperation of Church & Skate (title)
```
