### ISSUE TITLE
convert: Respect `album_art_maxwidth` in conjunction with `embed`

### ISSUE THREAD

**Issue by broddo** [beetbox/beets#2116]
### Problem

Hey guys, I think I've spotted a bug - like the title says. I noticed that my converted files have the full size images rather than my requested maxwidth of 600. 

However, if I just use beet embedart QUERY, the resize works fine and I can see the temporary images of the correct resolution being created in /tmp. So this tells me that its not a problem with imagemagick.

``` sh
$ beet -vv convert AURORA runaway
```

Led to this problem:

```
user configuration: /home/barry/.config/beets/config.yaml
data directory: /home/barry/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 9, 4))
library database: /home/barry/.config/beets/musiclibrary.blb
library directory: /home/barry/Music/lossless
Sending event: library_opened
AURORA - All My Demons Greeting Me as a Friend - Runaway
Convert? (Y/n) Y
convert: Encoding /home/barry/Music/lossless/AURORA/All My Demons Greeting Me as a Friend/01 Runaway.flac
convert: Finished encoding /home/barry/Music/lossless/AURORA/All My Demons Greeting Me as a Friend/01 Runaway.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /home/barry/Music/lossless/AURORA/All My Demons Greeting Me as a Friend/cover.jpg
convert: embedding /home/barry/Music/lossless/AURORA/All My Demons Greeting Me as a Friend/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
Sending event: cli_exit

```

I would have expected to see a line like:

```
artresizer: ImageMagick resizing /home/barry/Music/lossless/AURORA/All My Demons Greeting Me as a Friend/cover.jpg to /tmp/tmp5vch3h.jpg
```
### Setup
- OS: Arch Linux
- Python version: 2.7.12
- beets version: 1.3.18
- Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

``` yaml
convert:
    never_convert_lossy_files: yes
    dest: ~/Music/lossy
    embed: yes
    album_art_maxwidth: 600
    format: aac
    formats:
        aac:
            command: ffmpeg -i $source -y -c:a libfdk_aac -vbr 3 $dest
            extension: m4a

```
