### ISSUE TITLE
Fetchart failing with ImageMagick when getting size of image

### ISSUE THREAD

**Issue by Tstassin** [beetbox/beets#2121]
### Problem

Beets 1.3.19, was previously on 1.3.?, haven't change my config file for months (think so), and now beets crashes when using fetchart plugin while importing.

Running this command in verbose (`-vv`) mode:

``` sh
$ beet -vv import /volume1/downloads/transmission/complete/\!\!\!\ -\ \!\!\!\ \(2000\)\ \[FLAC\]/
```

Led to this problem (happens with every single album I try to import) :

```
user configuration: /usr/local/transmission/var/.config/beets/config.yaml
data directory: /usr/local/transmission/var/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 9, 1))
library database: /volume1/SharedMusic/.config/global/library.blb
library directory: /volume1/SharedMusic
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /volume1/downloads/transmission/complete/!!! - !!! (2000) [FLAC]
Tagging !!! - !!!
No album IDs found.
Search terms: !!! - !!!
Album might be VA: False
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Evaluating 5 candidates.
Candidate: !!! - !!!
Success. Distance: 0.00
Candidate: !!! - R!M!X!S
Success. Distance: 0.64
Candidate: Die drei !!! - Die drei !!! Fall 19: Teuflisches Handy
Success. Distance: 0.78
Candidate: Die drei !!! - Die drei !!! Fall 18: VIP-Alarm
Success. Distance: 0.74
Candidate: Die drei !!! - Die drei !!! Fall 17: Gefährliche Fracht
Success. Distance: 0.77

/volume1/downloads/transmission/complete/!!! - !!! (2000) [FLAC] (7 items)
Sending event: before_choose_candidate
Tagging:
    !!! - !!!
URL:
    http://musicbrainz.org/release/1b105601-d2d3-4da2-a7d9-114f981b1766
(Similarity: 99.7%) (year) (CD, 2001, US, Gold Standard Laboratories)
 * Storm The Legion          -> Storm the Legion
 * Feel Good Hit Of The Fall -> Feel Good Hit of the Fall
Sending event: import_task_choice
found duplicates: [6]
default action for duplicates: a
This album is already in the library!
Old: 7 items, FLAC, 1026kbps, 45:28, 337.1 MiB
New: 7 items, FLAC, 1026kbps, 45:28, 333.6 MiB
[S]kip new, Keep both, Remove old? r
Sending event: import_task_apply
0 of 7 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
lastgenre: added last.fm album genre (album): Dance, Electronica, Electronic
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
fetchart: trying source filesystem for album !!! - !!!
fetchart: trying source coverart for album !!! - !!!
fetchart: downloading image: http://coverartarchive.org/release/1b105601-d2d3-4da2-a7d9-114f981b1766/front
fetchart: downloaded art to: /tmp/tmp_p79KG.jpg
Traceback (most recent call last):
  File "/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 967, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 944, in import_files
    session.run()
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1395, in plugin_stage
    func(session, task)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/beetsplug/fetchart.py", line 791, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/usr/lib/python2.7/site-packages/beetsplug/fetchart.py", line 863, in art_for_album
    if candidate.validate(extra):
  File "/usr/lib/python2.7/site-packages/beetsplug/fetchart.py", line 139, in validate
    self.check = self._validate(extra)
  File "/usr/lib/python2.7/site-packages/beetsplug/fetchart.py", line 89, in _validate
    self.size = ArtResizer.shared.get_size(self.path)
  File "/usr/lib/python2.7/site-packages/beets/util/artresizer.py", line 211, in get_size
    return func(path_in)
  File "/usr/lib/python2.7/site-packages/beets/util/artresizer.py", line 125, in im_getsize
    out = util.command_output(cmd)
  File "/usr/lib/python2.7/site-packages/beets/util/__init__.py", line 702, in command_output
    shell=shell
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Here's a link to the music files that trigger the bug (if relevant): not relevant, happens with all music I try to import
### Setup
- OS: Synology DSM 6
- Python version: Python 2.7
- beets version: 1.3.19
- Turning off plugins made problem go away (yes/no): turning fetchart off removes the problem

My configuration (output of `beet config`) is:

``` yaml
paths:
    default: '%left{$albumartist,1}/$albumartist/$albumartist - $album%aunique{} ($original_year) [$format]/$track $title'
fetchart:
    minwidth: 1000
    sources: filesystem coverart itunes amazon albumart google wikipedia
    google_key: REDACTED
    auto: yes
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
library: /volume1/SharedMusic/.config/global/library.blb
lastgenre:
    count: 3
    source: album
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
embedart:
    maxwidth: 1000
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no

plugins: fetchart copyartifacts embedart lastgenre
directory: /volume1/SharedMusic

import:
    copy: yes
    log: /volume1/SharedMusic/.config/global/beets.log
copyartifacts:
    print_ignored: no
    extensions: .*
```

ImageMagick version

```
Version: ImageMagick 6.9.1-9 Q8 armle 2016-05-31 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC OpenMP 
Delegates (built-in): bzlib fontconfig freetype jng jpeg lzma png tiff xml zlib
```

``` sh
sh-4.3$ which convert
/bin/convert
sh-4.3$ echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin:/var/packages/Java8/target/j2sdk-image/bin:/var/packages/Java8/target/j2sdk-image/jre/bin:/var/packages/Java8/target/j2sdk-image/bin:/var/packages/Java8/target/j2sdk-image/jre/bin
```
