### ISSUE TITLE
"Better" support for Album metadata

### ISSUE THREAD

**Issue by Joshfindit** [beetbox/beets#2132]
### "Problem" (This is kind of a cross between a bug report and a feature request, as it's really only for hard-core users)

Album metadata is a second-class citizen:
- There doesn't seem to be support for anything like `beet info -a`
- Album/release-specific data like `$media`,  are not carried from the tracks to the album
- When adding metadata to all the tracks in an album, there's no mention that album metadata is separate (ok; low quality problem - this only stung me when I first started out)
### Setup
- OS: 10.9.5
- Python version: 2.7.5
- beets version: beets version 1.3.18 w/plugins: chroma, convert, copyartifacts, duplicates, importadded, info, inline, missing, smartplaylist
- Turning off plugins made problem go away (yes/no): NA

My configuration (output of `beet config`) is:

``` yaml

paths:
    default: $albumartist/$albumartist - $album [$year]%aunique{,albumtype media mastering label catalognum albumdisambig}/%if{$multidisc,Disc $disc/}$track $artist - $title
    singleton: Non-Album/$artist/$artist - $title
    comp: Various Artists/$albumartist - $album [$year]%aunique{}/%if{$multidisc,Disc $disc/}$track $artist - $title
    albumtype:soundtrack: Soundtracks/$album [$year]%aunique{,albumtype mastering label catalognum albumdisambig}/%if{$multidisc,Disc $disc/}$track $title
convert:
    copy_album_art: no
    embed: yes
    formats:
        mp3:
            command: lame -V0 --vbr-new "$source" "$dest"
            extension: mp3
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    dest:
    auto: no
    threads: 4
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: no
missing:
    filter: ^Guaguanco
    count: no
    total: no
smartplaylist:
    playlists: [{name: MyTravelPlaylist.m3u, album_query: 'for_travel:1', query: 'for_travel:1'}, {name: beatles.m3u, query: 'artist:Beatles'}]
    auto: yes
    playlist_dir: .
    relative_to:
chroma:
    auto: yes
library: /Volumes/Personal/Shared/Music/beetsconfig/beetsmusiclibrary.blb
ignore: .AppleDouble ._* *~ .DS_Store desktop.ini AlbumArtSmall.jpg AlbumArt_*_Small.jpg *.mood .directory *Demonoid.com.txt

ui:
    color: yes
copyartifacts:
    extensions: .*
    print_ignored: yes
pluginpath: /Volumes/Personal/Shared/Music/beetsconfig/plugins

plugins: info copyartifacts chroma importadded convert duplicates smartplaylist missing inline
directory: /Volumes/Personal/Shared/Music/beets

import:
    write: yes
    copy: yes
    resume: no
item_fields:
    multidisc: 1 if disctotal > 1 else 0
pathfields: {}
album_fields: {}
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
```
