### ISSUE TITLE
PyGIDeprecationWarning with chroma plugin

### ISSUE THREAD

**Issue by Honigmelone** [beetbox/beets#2142]
### Problem
Hey I get a strange warning message when re importing library with the chroma plugin enabled.  The import operation continues after these two warning. However the `-p` option has no effect.

Running this command in verbose (`-vv`) mode:

```sh
$  beet -vv import -Lp
```

Led to this problem:

```
user configuration: /home/ash1125/.config/beets/config.yaml
data directory: /home/ash1125/.config/beets
plugin paths: /home/ash1125/.config/beets/myplugins
Sending event: pluginload
library database: /home/ash1125/.config/beets/musiclibrary.blb
library directory: /home/ash1125/Music
Sending event: library_opened
Sending event: import_begin
yielding album 249: Anajo - Nah bei mir
Sending event: import_task_created
Sending event: import_task_start
yielding album 250: Anathema - A Fine Day to Exit
Sending event: import_task_created
yielding album 251: Anathema - A Natural Disaster
Sending event: import_task_created
yielding album 252: Anathema - Alternative 4
/usr/lib/python2.7/site-packages/audioread/gstdec.py:126: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
Sending event: import_task_created
yielding album 253: Anathema - Eternity
Sending event: import_task_created
yielding album 254: Anathema - Falling Deeper
Sending event: import_task_created
yielding album 203: Anathema - Hindsight
Sending event: import_task_created
yielding album 204: Anathema - Judgement
/usr/lib/python2.7/site-packages/audioread/gstdec.py:146: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  self.loop = GObject.MainLoop()
Sending event: import_task_created
yielding album 205: Anathema - Serenades
Sending event: import_task_created
yielding album 206: Anathema - The Silent Enigma
Sending event: import_task_created
yielding album 207: Anathema - We're Here Because We're Here
.
.
.
```
Note:  Both files that span the error have the same track title as the respective album.

### Setup

* OS:  Fedora 23
* Python version:  2.7.11
* beets version: 1.3.13
plugins: chroma

* Turning off plugins made problem go away (yes/no): 
yes

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music
library: ~/.config/beets/musiclibrary.blb
import:
        move: yes
ignore: .AppleDouble ._* *~ .DS_Store
ignore_hidden: yes
art_filename: albumart
#plugins: bpd lyrics fetchart scrub chroma duplicates
plugins: chroma
pluginpath: ~/.config/beets/myplugins
threaded: yes
ui:
    color: yes
paths:
    default: $albumartist/$album/$track - $artist - $title
    singleton: $artist/$title/$track - $artist - $title
    comp: $genre/$album/$track - $artist -$title
    albumtype:soundtrack: Soundtracks/$album/$track -$artist - $title
```
