### ISSUE TITLE
Weirdness with albumartist and ls -a

### ISSUE THREAD

**Issue by tweitzel** [beetbox/beets#2155]
### Problem

Beet import, on at least a couple of albums (https://musicbrainz.org/release/43c08b18-4f38-3953-9605-cde95836ef93 is where I first noticed), is populating albumartist_sort and albumartist_credit, but not albumartist. As a result, that field is not seen by beet ls -a. 

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv info id:23155
```

Led to this problem:

```
user configuration: /Users/xarph/.config/beets/config.yaml
data directory: /Users/xarph/.config/beets
plugin paths: /Users/xarph/work/whatlastgenre/plugin/beets/beetsplug
Sending event: pluginload
inline: adding item field disc_and_track
library database: /Users/xarph/Music/beetslibrary.blb
library directory: /Users/xarph/Music/beets
Sending event: library_opened
/Users/xarph/Music/beets/Depeche Mode/The Singles 81_85/16 Photographic (Some Bizzare version).mp3
acoustid_fingerprint: AQADtMkkKUmUJFIkHDAOADAAHzhxADBwAAZOHIB1HDCgG8dJnNiyHDmeC8dNIUWNH6qYrrguMA9cRYlhlbhD4RHhZzH6ENVhlcGVDEWN57gH9_jxhHgNtYKPR8oQnrgqo0f6oN0hhYeH8ET3wD947XgZ4A9SJ1vxCP2FsoLKlbCDSEqzIJfo4Ud9TGmSCTryLSYKX2MGxg4uE_vR7AhfXCf6BU1aHs-Pn3iQUx9RncarHz-KHv_hozyOVzKqUJsjRIvYSUjoagZz_Og3wffQox6auMGJE2eITityZR70LMfDI9cE6ziHsH-wQ73QQwsZHTl2CZV5UBaFG9uPkzkuGumRTNWIl-FxKUh-5Ml-VBWakcGVzEL54DiccDqmT8GfIUtG7oJWXUIkXolwkSweHBV1CUeHXsOPXcctHN12XOnx7LiE5DTyLMWD68J5OJUuMB_6TCuOjcuOy3imwztCK9ugG9WF5zK69EFiKVk23EfRTCLOeRNK-cELO8SHPj3WSgjdRDEkbUkehFNkLVh__J3QSEPZh_iGvnHgn6iM4zvGC49ihDf88MjDw8YzHM-Q7_B36EeOM_B18L7w4D4cHZO37Uhe5BV-XPiF8kS6aAqJ5Ie7_OiPujmaNcrx6MF1VLyMH2GciNgdLlDFRKKGsD-akUGfE0x6vMkXNKhOfMcDnAi54PSgEyrhRwd5qFSiY0d-_PCWon9xbqj-wmKDPke-J1B_Iz9OySnaRUfaB9qRF89xMQ_W67iOSuSRNYdmcYiPfqnwG-uoHEd-Qk-24UxURNO-gi-uHRtHlPxxz8HhOseT4AqQR8ozaKlaIWR29Dn8GM_hG300PHlCnEesHMmZ4w8ap0eoQ35wvsgfnEZIR4ZYEuF7HHd-YUz0gZVOnItRTkhe5Da2OJFhFT2-6fgzIVkmXUSeccEfjM7Bi8e1tBz24caH7jlOI-mP_MKPltfhTTt-XD0c6rjRdHgi4A1yHoqaI4yYLMZFNAdjITfeo8_x4QxO8XgGMVNz3PjhM8YTXIYf4iNOXtCHS_jhI2-Mb_hxmGOMHiEZFt5RV8UXdDrEHv8OvsEPfzEenDhDNFWIHxoPn8eZB03xBHl0NKfRLzhyoc9yPC16QnsGKhN-PAsUesET4uOh54CPh7AmHn1QcTv8Q5MfrHrwBKeyoD0eOObRU3gmjggPHy1e9KCOj0cavMQF_-BzqNJhHp1RicUL74Ge4DNuHOk3hDd6HH5ReccPTS6eHd_xx9DhF_GD7gPT6UNz4owzrEaTX0jGpwjTyEfvD89xNCfODHp-uBf-GE9koX-G-3h63CmaWOjC7DhOLYkT5EkuKH-O8MkE5zxa7kUXiYF_9DrOHNN-POiFP8GJPx0aSsqR79BV-Ed-3MRV5Mev48U_-A_Ch_nQwx3-4YyGbx_8yQjf4MrxLIhJUSjHF9cSoZSD_sf_BOfxZXh0fII_GhWbSEPU6oN6E2E45mCe7MHJ7Lgy9ERz8NmH-nCTDE2Odwn2FbfROEd-iFQY5ISfYzv60LiiHOc-jL9Q82h2PB_Q_Ai5ZDl6QcvDekA_QnUWItxZ_HhSWThzNHpOVKpyPMfvoCd-ONfxWHnQxJmQ_JERnvAzCdc9-LzQLzl-NKHwBc3x4VKOEy2XDmG-40e37RA_IaKDP2BQUcmOPT2-HO8O_5ge9ojFC3qQbzGYDNUXcdiJn6ieHWnNIJl6PD9O5UNzPhx6BqUU2JGOs6iLHxcfVKEvREoWZZKgM8hRdj38GFdu2GmNnjiH7pjEEU8UfMeHUBw7iDsDHJUXXEp0_AnyHz2ascUjJcd19ETz8DjiJg_U7B9yHmWzMPAR_kju49iT_DjlDNyHlzFOE8lzhFwHV3SEs-iPHS-SJZ0ShDyFXwqOiesJ6vhzbOLxF36OPhK-Ix90HrHzotPhiFnwo7fQEw6VLMaTh2ieHbmcD0kV_MEPn8ePOHxDqJSkI-fUo3mO9sih50F-XMtjjMd7ZDeF5EGlD39nPMd-1BxyqLqQ18SUM-hmHnyOnUd_ODp69DmafCc-5riTIznCL0ezjMb5oN4Pu0FFH9PQ5OAZYBaRC7pTlCTQM9hRicGn4wrqDS_qC3aGDz0xXXBo5EkWhEd_PIeYK-iGN2gjBv7RQzemo12QiwhF4xYevHjxHyYO_jgOMS6eBkfDPNCJFs2Z4znqg3J4fMcDE32Om-imHMcH9_iOd8EPH-oU4lsO__jx8dCVGOfxUIO7BQ-OF7WKyoGFR8KjB3o4iDr6Hf0Ck8KJ4w6FHzd0DnCOrgy-oIffQx-MezHUHz6Om4F1aFXQZ4Nz5ApOhTmsx4hVeDz6LMXjB-yOPhqaFxF_PPvQHp4c_COe49SQ6-gP_cOPx6gcLod4pEepHn12mFSOCs8_tFUK90d_hE-yQ0slyUceb8FzA2uVc9Y5YQ2QQAhFVGLCEAQMAMxQIRgwiikhiAKIEgmAAAIYI5AwTklClNDEIUMQEwAZKgRAADgjCgAkWEOSk0gIRIwBDBgCAABFG9EFYoIwJATgAAIDjINNCQAAYIixQ4EViiBCjGCAICUQMoQoogBigiChDCDCACsEAhAYYRAQhDkiiAIACWaaIgJIwBggQFDhoEAIKjCFQEIIogQiCBkhgABAIACIgcIyg4AwghNgODHMGCGBA0gBwoAiigKABLJAUKIcYMI4YgQhBgiGFAPICokYAcARJiggzDhNAWGSAcYAEEIYhBCBBgBFBAQGIASFQgAiRCAQzAoEpGJCGIYUUEIJxIBgQBgAFAGMAGKEQsgw5oR0zgEABHJCAgGoBIQYRRAgyAMCiECMISSQwUwAoAQCCABRCFCACWGEAAoo4hyCBggggBLDCMKIEwY4YQgBDBiBBKCEBEaMMEQwoYhAADkLkBBEKAOEIAAyQggTwDAigDJEIGYAAhQQoSBBAABTIENKACSpEMYAQQBQxFgnhDIAEIIsIAQIAhBiSAGDgEAEAESIggAQBQiDghBCADSKCEIdIEIIgxUxABDDjEOOCSKIUgIwJIRwhAAAhTDEAC-QQVYQAAgAAjhHiQEeC4WAAIQRYBAjwjjhBAQQQAscSQQoBxCAAAlgCBZEAKegQsIoLhQwCgGAEGEQAWMgY0pAAoQgCiElHHJCCAEMkwIjQoATiACBADMEUUCUEMgYpoRVCBhBAEIEEUSAMgQR4YQyjCGBjRCICgAQEAQYw5gAwDhFHAOMISAYAsABChRQhjnCCGMWAYGYMEQBAxhSzABECCDMAsasMEYBoYQBQgIiKAFAMGEAEkAoISxDwDjJhCKQKSAgAQIoQIARghgAFJAA
         acoustid_id: 31fbfcd4-7127-48e3-9e04-7b235c6f678f
               album: The Singles 81>85
  albumartist_credit: Depeche Mode
    albumartist_sort: Depeche Mode
         albumstatus: Official
           albumtype: compilation
                 art: True
              artist: Depeche Mode
       artist_credit: Depeche Mode
                asin: B00000HY5N
            bitdepth: 0
             bitrate: 246741
                 bpm: 0
          catalognum: 9 47298-2
            channels: 2
                comp: False
             country: US
                date: 1985-10-15
                 day: 15
                disc: 1
           disctotal: 1
              format: MP3
               genre: Synthpop, Electronic Rock, Electronic
              genres: Synthpop, Electronic Rock, Electronic
         initial_key: Gm
               label: Mute
            language: eng
              length: 193.666666667
              lyrics:
          mb_albumid: 43c08b18-4f38-3953-9605-cde95836ef93
         mb_artistid: 8538e728-ca0b-4321-b7e5-cff6565dd4c0
   mb_releasegroupid: eadcd3aa-84fb-3931-88ba-a8489f4894f1
          mb_trackid: d2fff167-6e48-4966-9091-8bd7b002dbdc
               media: CD
               month: 10
       original_date: 1985-01-01
       original_year: 1985
       rg_album_gain: -9.41
       rg_album_peak: 1.478232
       rg_track_gain: -8.24
       rg_track_peak: 1.167808
          samplerate: 44100
              script: Latn
               title: Photographic (Some Bizzare version)
               track: 16
          tracktotal: 17
                year: 1985
Sending event: cli_exit
```

### Setup

* OS: OS X 10.11.6 (15G31)
* Python version: 2.7.11
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: acousticbrainz, badfiles, chroma, duplicates, embedart, fetchart, fromfilename, ftintitle, info, inline, lastgenre, mbsubmit, mbsync, play, random, replaygain, scrub, web
lemon:cd xarph$ beet config
play:
    command: /usr/local/bin/mpv $args --display-tags='Artist,Album,Album_Artist,Genre,Title,Track,disc,date,icy-title,service_name' --vo null --no-audio-display --af=volume=replaygain-album --playlist
    warning_threshold: -2
    use_folders: no
    warning_treshold: 100
    raw: no
    relative_to:
scrub:
    auto: no
pluginpath: ~/work/whatlastgenre/plugin/beets/beetsplug
asciify_paths: yes
fetchart:
    auto: yes
    minwidth: 300
    enforce_ratio: yes
    sources: coverart itunes amazon albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
library: /Users/xarph/Music/beetslibrary.blb
original_date: yes

clutter: .DS_Store desktop.ini
importfeeds:
    formats: m3u_multi link
    dir: /Users/xarph/Music/beetsplaylist
    absolute_path: yes
badfiles:
    commands: {}

plugins: lastgenre chroma replaygain ftintitle info duplicates web fromfilename scrub badfiles play random fetchart embedart acousticbrainz mbsync mbsubmit inline

paths:
    default: $albumartist/$album%aunique{}/$disc_and_track $title
    comp: Compilations/$album%aunique{}/$disc_and_track $artist - $title
    singleton: $artist/Unknown Album/$title

format_item: '$id: $artist - $album%aunique{} - $disc_and_track - $title ($year)'
item_fields:
    disc_and_track: u'%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
per_disc_numbering: yes
id3v23: yes
languages: en
lastgenre:
    fallback: Unfiled
    canonical: ''
    whitelist: /Users/xarph/.config/beets/genres.txt
    source: track
    force: no
    count: 3
    min_weight: 10
    auto: yes
    separator: ', '
directory: /Users/xarph/Music/beets

import:
    move: no
    copy: yes
    write: yes
    log: /Users/xarph/Music/beetslog.txt

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
wlg:
    auto: yes
chroma:
    auto: yes
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
mbsubmit:
    threshold: medium
    format: $track. $title - $artist ($length)
pathfields: {}
album_fields: {}
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
replaygain:
    targetlevel: 89
    auto: yes
    overwrite: no
    backend: command
    command: ''
    noclip: yes
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
acousticbrainz:
    auto: yes
```
