### ISSUE TITLE
acoustid_fingerprint missing in metadata

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#2160]
### Problem

acoustid_fingerprint is missing in metadata.

The documentation says that the acoustid_fingerprint will be written to the metadata of a file. I enabled the chromaprint plugin and set "import.write=yes" in the config but can't find the info in the metadata (but the acoustid_fingerprint is saved in the database file).
Is this an error or am I missing something? Here is the output of exiftool of a file that has an acoustid_fingerprint value saved in the database:

> ExifTool Version Number         : 10.24
File Name                       : 01-Allah-Las - Catamaran.mp3
Directory                       : music/a/Allah-Las/(2012) Allah-Las
File Size                       : 8.2 MB
File Modification Date/Time     : 2016:08:07 21:32:50+02:00
File Access Date/Time           : 2016:08:07 21:32:50+02:00
File Inode Change Date/Time     : 2016:08:07 21:32:50+02:00
File Permissions                : rw-rw-r--
File Type                       : MP3
File Type Extension             : mp3
MIME Type                       : audio/mpeg
MPEG Audio Version              : 1
Audio Layer                     : 3
Audio Bitrate                   : 320 kbps
Sample Rate                     : 44100
Channel Mode                    : Stereo
MS Stereo                       : Off
Intensity Stereo                : Off
Copyright Flag                  : False
Original Media                  : False
Emphasis                        : None
Mp 3gain Minmax                 : 110,178
Mp 3gain Album Minmax           : 000,255
Replaygain Track Gain           : -8.150000 dB
Replaygain Track Peak           : 0.999923
Replaygain Album Gain           : -9.640000 dB
Replaygain Album Peak           : 3.242103
ID3 Size                        : 57380
Title                           : Catamaran
Artist                          : Allah-Las
Track                           : 1/12
Album                           : Allah-Las
Part Of Set                     : 1/1
Recording Time                  : 2012:09:18
Genre                           : Indie/Garage Rock/Psychedelic Rock
Picture MIME Type               : image/jpeg
Picture Type                    : Front Cover
Picture Description             : 
Picture                         : (Binary data 41348 bytes, use -b option to extract)
Comment                         : (Songs-DB_Occasion) Summer
Beats Per Minute                : 0
Compilation                     : No
Original Release Time           : 2012:09
Grouping                        : Psychedelic Rock
Language                        : eng
Media                           : CD
Band                            : Allah-Las
Publisher                       : Innovative Leisure Records
Album Artist Sort Order         : Allah-Las
Performer Sort Order            : Allah-Las
User Defined Text               : (originalyear) 2012
Lyrics                          : 
Year                            : 2012
Date/Time Original              : 2012:09:18
Duration                        : 0:03:33 (approx)

### Setup

* OS: Gentoo Linux
* Python version: 2.7.12
* beets version:  1.3.13

My configuration (output of `beet config`) is:

```yaml
paths:
    default: '%lower{%left{$albumartist_sort,1}}/$albumartist_sort/($year) $album/$track-$albumartist - $title'
    singleton: _unsorted/$artist/$title
library: /home/r/.config/beets/musiclibrary.blb

plugins: chroma
directory: /mnt/archivefs/music

import:
    copy: yes
    write: yes
acoustid:
    apikey: REDACTED
chroma:
    auto: yes

```
