### ISSUE TITLE
Lyrics Plugin Doesn't Work Properly

### ISSUE THREAD

**Issue by MetaIronic** [beetbox/beets#2161]
When using the lyrics plugin I seem unable to get lyrics from genius or musixmatch, despite the documentation page claiming it can. An example of such a song is Sick and Tired - Denzel Curry. This song has complete lyrics on both genius and musixmatch yet when I run "beet lyrics Denzel Curry Sick and Tired" I get the result "lyrics: lyrics not found: Denzel Curry - Imperial - Sick And Tired". This is deeply vexing as I downloaded beets due to the fact it would solve my music lyrics problem in what seemed an elegant manner, with added tag checking benefits. 

I have also tried enabling the custom google search by adding an api key. This has the same result as above

I am on Windows 8.1
Running python 2.7.7
with beets 1.3.18

These are my config.yaml options excluding the library and directory

```yaml
plugins: embedart fetchart lyrics
art_filename: albumcover

import:
    copy: no

lyrics:
    sources: google lyricwiki lyrics.com musixmatch genius

embedart:
    ifempty: yes

fetchart:
    cautious: yes
    minwidth: 480
    sources: coverart itunes amazon albumart google
```
