### ISSUE TITLE
Problem with albumartist on DJ mix albums

### ISSUE THREAD

**Issue by dowcet** [beetbox/beets#2170]
### Problem

In the following test, the import seems to go well: 

```
$ beet -l '/home/user/test' import /home/user/music/Booka\ Shade/DJ-Kicks_\ Booka\ Shade/

/home/user/music/beets/Booka Shade/DJ-Kicks_ Booka Shade (22 items)
Tagging:
    Booka Shade - DJ-Kicks: Booka Shade
URL:
    http://musicbrainz.org/release/5b8e404d-8e44-323d-baf3-4e16bf99246b
(Similarity: 100.0%) (CD, 2008, DE, !K7)
```

But when I update, beets messes up the albumartist like so:

```
Aphex Twin - DJ-Kicks: Booka Shade - Alberto Balsalm
  month: 08 -> 00
  day: 01 -> 00
  disctotal: 01 -> 00
  albumartist: Booka Shade -> Aphex Twin
  artist_sort: Aphex Twin -> 
  tracktotal: 22 -> 00
Brigitte Bardot - DJ-Kicks: Booka Shade - Contact
  month: 08 -> 00
  day: 01 -> 00
  disctotal: 01 -> 00
  albumartist: Booka Shade -> Brigitte Bardot
  tracktotal: 22 -> 00
```
... and so on with every track.

Music files for testing: https://www.mediafire.com/?lbj7oqay5u2srd5

### Setup

* OS: Ubuntu 14.04
* Python version: 3.4
* beets version: 1.3.16 

My configuration (output of `beet config`) is:

```yaml
import:
    copy: no
    write: no

plugins: badfiles duplicates missing info
missing:
    count: no
    total: no
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no

```
