### ISSUE TITLE
beets doesn't seem to be writing artist_sort, original-day, original-month anymore

### ISSUE THREAD

**Issue by tweitzel** [beetbox/beets#2189]
### Problem

I noticed when I was doing some tidiness that certain tracks were appearing in beet write over and over again. I isolated a problem file, verified the permissions were fine (0644, nothing weird), and did some checks

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv write id:22460
user configuration: /Users/xarph/.config/beets/config.yaml
data directory: /Users/xarph/.config/beets
plugin paths: /Users/xarph/work/whatlastgenre/plugin/beets/beetsplug
Sending event: pluginload
inline: adding item field disc_and_track
library database: /Users/xarph/Music/beetslibrary.blb
library directory: /Users/xarph/Music/beets
Sending event: library_opened
: Inon Zur - Icewind Dale II - 24 - IWD2 Main Theme (2002)
  original_day: 00 -> 28
  artist_sort:  -> Zur, Inon
  original_month: 00 -> 08
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: cli_exit
```

Led to this problem:

```
beet info id:22460
/Users/xarph/Music/beets/Inon Zur/Icewind Dale II/24 IWD2 Main Theme.mp3
acoustid_fingerprint: [no one cares]
         acoustid_id: 04b0b79f-3080-42dd-af70-763a9b993951
               album: Icewind Dale II
         albumartist: Inon Zur
  albumartist_credit: Inon Zur
    albumartist_sort: Zur, Inon
         albumstatus: Official
           albumtype: soundtrack
                 art: True
              artist: Inon Zur
       artist_credit: Inon Zur
            bitdepth: 0
             bitrate: 192000
                 bpm: 0
          catalognum: CD-W58-1336-3
            channels: 2
                comp: False
             country: US
                date: 2002-08-28
                 day: 28
                disc: 1
           disctotal: 1
              format: MP3
               genre: Video Game Music, Electronic, Ambient
              genres: Video Game Music, Electronic, Ambient
         initial_key: Dm
               label: Interplay Entertainment Corp.
            language: eng
              length: 61.4192083333
              lyrics:
    mb_albumartistid: ba23bac1-2b00-43fb-95e5-c3c0fd286e7e
          mb_albumid: dd25d4a9-9276-4f61-bb8a-e77daeb848dc
         mb_artistid: ba23bac1-2b00-43fb-95e5-c3c0fd286e7e
   mb_releasegroupid: b26d11ed-230f-33f5-839d-964fd0964755
          mb_trackid: 3750a0d9-8c18-4a26-b2b9-3b69a5cef4d4
               media: CD
               month: 8
       original_date: 2002-01-01
       original_year: 2002
       rg_album_gain: -2.0
       rg_album_peak: 0.97319
       rg_track_gain: -1.21
       rg_track_peak: 0.803964
          samplerate: 44100
              script: Latn
               title: IWD2 Main Theme
               track: 24
          tracktotal: 40
                year: 2002
```

Here's a link to the music files that trigger the bug (if relevant): 
I'll post on request, but as it affects large swathes of my library at the moment, it's safe to say it's not file-related.

### Setup

* OS: OS X 10.11.6
* Python version: ```Python 2.7.11 (default, Dec 29 2015, 10:20:38)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin```
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```
play:
    command: /usr/local/bin/mpv $args --display-tags='Artist,Album,Album_Artist,Genre,Title,Track,disc,date,icy-title,service_name' --vo null --no-audio-display --af=volume=replaygain-track --playlist
    warning_threshold: -2
    use_folders: no
    warning_treshold: 100
    raw: no
    relative_to:
scrub:
    auto: no
pluginpath: ~/work/whatlastgenre/plugin/beets/beetsplug
asciify_paths: yes
fetchart:
    auto: yes
    minwidth: 300
    enforce_ratio: yes
    sources: coverart itunes amazon albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
library: /Users/xarph/Music/beetslibrary.blb
original_date: yes
replaygain:
    backend: bs1770gain
    auto: yes
    overwrite: yes
    targetlevel: 89
    chunk_at: 5000
    method: replaygain

clutter: .DS_Store desktop.ini
importfeeds:
    formats: m3u_multi link
    dir: /Users/xarph/Music/beetsplaylist
    absolute_path: yes
badfiles:
    commands: {}

plugins: chroma replaygain ftintitle info duplicates web fromfilename scrub badfiles play random fetchart embedart acousticbrainz mbsync mbsubmit inline recordingdate wlg

paths:
    default: $albumartist/$album%aunique{}/$disc_and_track $title
    comp: Compilations/$album%aunique{}/$disc_and_track $artist - $title
    singleton: $artist/Unknown Album/$title

format_item: '$id: $artist - $album%aunique{} - $disc_and_track - $title ($year)'
item_fields:
    disc_and_track: u'%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
per_disc_numbering: yes
id3v23: yes
languages: en
lastgenre:
    fallback: Unfiled
    canonical: yes
    whitelist: /Users/xarph/.config/beets/genres.txt
    source: album
    force: yes
    count: 1
directory: /Users/xarph/Music/beets

import:
    move: no
    copy: yes
    write: yes
    log: /Users/xarph/Music/beetslog.txt

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
wlg:
    auto: yes
    count: 1
    force: yes
    whitelist: wlg
    separator: ', '
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
chroma:
    auto: yes
pathfields: {}
album_fields: {}
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
acousticbrainz:
    auto: yes
mbsubmit:
    threshold: medium
    format: $track. $title - $artist ($length)
```
