### ISSUE TITLE
Could not edit configuration

### ISSUE THREAD

**Issue by tc-kirby** [beetbox/beets#2192]
### Problem

Running beet config -e results in an error.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv config -e
```

Led to this problem:

```
error: Could not edit configuration: [Errno 2] No such file or directory
```

### Setup

* OS: Ubuntu 14.04
* Python version: 2.7.6
* beets version: 1.3.19
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/media/Music

import:
    copy: no
    write: no
library: ~/beets_library.blb
```
