### ISSUE TITLE
rg_album_gain hates AAC files

### ISSUE THREAD

**Issue by tweitzel** [beetbox/beets#2194]
### Problem

Discovered in #2189 

``` sh
6120: Jesper Kyd - Assassin’s Creed: Revelations - 01-02 - Animus Island (2011)
lemon:~ xarph$ beet -vv write id:6120
user configuration: /Users/xarph/.config/beets/config.yaml
data directory: /Users/xarph/.config/beets
plugin paths: /Users/xarph/work/whatlastgenre/plugin/beets/beetsplug
Sending event: pluginload
inline: adding item field disc_and_track
library database: /Users/xarph/Music/beetslibrary.blb
library directory: /Users/xarph/Music/beets
Sending event: library_opened
: Jesper Kyd - Assassin’s Creed: Revelations - 01-02 - Animus Island (2011)
  rg_album_gain: 1.0 -> 0.0
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: cli_exit
```

Led to this problem:

```
lemon:~ xarph$ beet info id:6120
/Users/xarph/Music/beets/Jesper Kyd & Lorne Balfe/Assassin's Creed_ Revelations/02 Animus Island.m4a
acoustid_fingerprint: lalalalalal
         acoustid_id: ed1d2632-7645-44ec-b549-c278fa18883d
               album: Assassin’s Creed: Revelations
         albumartist: Jesper Kyd & Lorne Balfe
  albumartist_credit: Jesper Kyd & Lorne Balfe
    albumartist_sort: Kyd, Jesper & Balfe, Lorne
       albumdisambig: the complete recordings
         albumstatus: Official
           albumtype: soundtrack
                 art: False
              artist: Jesper Kyd
       artist_credit: Jesper Kyd
         artist_sort: Kyd, Jesper
                asin:
            bitdepth: 16
             bitrate: 256000
                 bpm: 0
          catalognum:
            channels: 2
            comments: Adjusted by iVolume 02/27/2012 11:07:39

                comp: False
            composer: Jesper Kyd
             country: XW
                date: 2011-11-15
                 day: 15
                disc: 1
           disctitle: Volume I: Single Player
           disctotal: 3
             encoder:
              format: AAC
               genre: Video Game Music, Neoclassical
              genres: Video Game Music, Neoclassical
            grouping:
               label: Ubisoft Entertainment
            language: eng
              length: 172.222403628
              lyrics:
    mb_albumartistid: 5156bb2c-45d7-4660-8234-4d84452c93e1
          mb_albumid: 96596c1c-f12d-465f-902f-01f928b33341
         mb_artistid: 5156bb2c-45d7-4660-8234-4d84452c93e1
   mb_releasegroupid: 7c7fb0cd-edbe-4e27-939a-52b77c705eac
          mb_trackid: ebb8b286-1d9b-4a8e-8bbd-e35cc826dd40
               media: Digital Media
               month: 11
       original_date: 2011-11-15
        original_day: 15
      original_month: 11
       original_year: 2011
       rg_album_gain: 0.98233
       rg_album_peak: 0.0
       rg_track_gain: -0.4
       rg_track_peak: 0.982335
          samplerate: 44100
              script: Latn
               title: Animus Island
               track: 2
          tracktotal: 80
                year: 2011
lemon:~ xarph$ beet -vv write id:6120
user configuration: /Users/xarph/.config/beets/config.yaml
data directory: /Users/xarph/.config/beets
plugin paths: /Users/xarph/work/whatlastgenre/plugin/beets/beetsplug
Sending event: pluginload
inline: adding item field disc_and_track
library database: /Users/xarph/Music/beetslibrary.blb
library directory: /Users/xarph/Music/beets
Sending event: library_opened
: Jesper Kyd - Assassin’s Creed: Revelations - 01-02 - Animus Island (2011)
  rg_album_gain: 1.0 -> 0.0
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: cli_exit
```

Here's a link to the music files that trigger the bug (if relevant): 
[02 Animus Island.m4a.zip](https://github.com/beetbox/beets/files/465759/02.Animus.Island.m4a.zip)
### Setup
- OS: OS X 10.11.6
- Python version: 2.7.11
- beets version:
  `beets version 1.3.18
  plugins: acousticbrainz, badfiles, chroma, duplicates, embedart, fetchart, fromfilename, ftintitle, info, inline, mbsubmit, mbsync, play, random, recordingdate, replaygain, scrub, web, wlg`
- Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

``` yaml
play:
    command: /usr/local/bin/mpv $args --display-tags='Artist,Album,Album_Artist,Genre,Title,Track,disc,date,icy-title,service_name' --vo null --no-audio-display --af=volume=replaygain-track --playlist
    warning_threshold: -2
    use_folders: no
    warning_treshold: 100
    raw: no
    relative_to:
scrub:
    auto: no
pluginpath: ~/work/whatlastgenre/plugin/beets/beetsplug
asciify_paths: yes
fetchart:
    auto: yes
    minwidth: 300
    enforce_ratio: yes
    sources: coverart itunes amazon albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
library: /Users/xarph/Music/beetslibrary.blb
original_date: yes
replaygain:
    backend: bs1770gain
    auto: yes
    overwrite: yes
    targetlevel: 89
    chunk_at: 5000
    method: replaygain

clutter: .DS_Store desktop.ini
importfeeds:
    formats: m3u_multi link
    dir: /Users/xarph/Music/beetsplaylist
    absolute_path: yes
badfiles:
    commands: {}

plugins: chroma replaygain ftintitle info duplicates web fromfilename scrub badfiles play random fetchart embedart acousticbrainz mbsync mbsubmit inline recordingdate wlg

paths:
    default: $albumartist/$album%aunique{}/$disc_and_track $title
    comp: Compilations/$album%aunique{}/$disc_and_track $artist - $title
    singleton: $artist/Unknown Album/$title

format_item: '$id: $artist - $album%aunique{} - $disc_and_track - $title ($year)'
item_fields:
    disc_and_track: u'%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
per_disc_numbering: yes
id3v23: no
languages: en
lastgenre:
    fallback: Unfiled
    canonical: yes
    whitelist: /Users/xarph/.config/beets/genres.txt
    source: album
    force: yes
    count: 1
directory: /Users/xarph/Music/beets

import:
    move: no
    copy: yes
    write: yes
    log: /Users/xarph/Music/beetslog.txt

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
wlg:
    auto: yes
    count: 1
    force: yes
    whitelist: wlg
    separator: ', '
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
mbsubmit:
    threshold: medium
    format: $track. $title - $artist ($length)
chroma:
    auto: yes
pathfields: {}
album_fields: {}
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
acousticbrainz:
    auto: yes
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
```

Bonus AtomicParsley output:

```
lemon:~ xarph$ AtomicParsley /Users/xarph/Music/beets/Jesper\ Kyd\ \&\ Lorne\ Balfe/Assassin\'s\ Creed_\ Revelations/02\ Animus\ Island.m4a -t
Atom "©nam" contains: Animus Island
Atom "©ART" contains: Jesper Kyd
Atom "©wrt" contains: Jesper Kyd
Atom "©alb" contains: Assassin’s Creed: Revelations
Atom "©gen" contains: Video Game Music, Neoclassical
Atom "trkn" contains: 2 of 80
Atom "disk" contains: 1 of 3
Atom "©day" contains: 2011-11-15
Atom "cpil" contains: false
Atom "tmpo" contains: 0
Atom "©too" contains:
Atom "----" [com.apple.iTunes;CATALOGNUMBER] contains:
Atom "----" [com.apple.iTunes;ASIN] contains:
Atom "----" [com.apple.iTunes;MusicBrainz Album Release Country] contains: XW
Atom "----" [com.apple.iTunes;LANGUAGE] contains: eng
Atom "----" [com.apple.iTunes;SCRIPT] contains: Latn
Atom "----" [com.apple.iTunes;replaygain_track_gain] contains: -0.40 dB
Atom "----" [com.apple.iTunes;replaygain_album_peak] contains: 0.000000
Atom "----" [com.apple.iTunes;replaygain_track_peak] contains: 0.982335
Atom "----" [com.apple.iTunes;MusicBrainz Album Status] contains: Official
Atom "----" [com.apple.iTunes;ORIGINAL YEAR] contains: 2011-11-15
Atom "----" [com.apple.iTunes;Artist Credit] contains: Jesper Kyd
Atom "----" [com.apple.iTunes;MusicBrainz Album Type] contains: soundtrack
Atom "----" [com.apple.iTunes;MEDIA] contains: Digital Media
Atom "----" [com.apple.iTunes;Label] contains: Ubisoft Entertainment
Atom "----" [com.apple.iTunes;publisher] contains: Ubisoft Entertainment
Atom "----" [com.apple.iTunes;DISCSUBTITLE] contains: Volume I: Single Player
Atom "----" [com.apple.iTunes;MusicBrainz Album Comment] contains: the complete recordings
Atom "----" [com.apple.iTunes;Album Artist Credit] contains: Jesper Kyd & Lorne Balfe
Atom "----" [com.apple.iTunes;MusicBrainz Artist Id] contains: 5156bb2c-45d7-4660-8234-4d84452c93e1
Atom "----" [com.apple.iTunes;MusicBrainz Album Artist Id] contains: 5156bb2c-45d7-4660-8234-4d84452c93e1
Atom "----" [com.apple.iTunes;MusicBrainz Release Group Id] contains: 7c7fb0cd-edbe-4e27-939a-52b77c705eac
Atom "----" [com.apple.iTunes;MusicBrainz Album Id] contains: 96596c1c-f12d-465f-902f-01f928b33341
Atom "----" [com.apple.iTunes;MusicBrainz Track Id] contains: ebb8b286-1d9b-4a8e-8bbd-e35cc826dd40
Atom "----" [com.apple.iTunes;Acoustid Id] contains: ed1d2632-7645-44ec-b549-c278fa18883d
Atom "----" [com.apple.iTunes;iTunNORM] contains:  00000448 00000448 00000AB5 00000AB5 00000000 00000000 00007DBD 00007DBD 00000000 00000000
Atom "----" [com.apple.iTunes;Acoustid Fingerprint] contains: AQADtEq0KMmiRcVlose3wMg3uKaE9gbnHUdHmNFW4Ud-4s5y_PiDIxeDM9NxwehxCyGPH__RIyzhQ9txohPhmkV_aA88ZocriejxqEPZEZYOjTx6Ij7yoJQOrT-aOJmQF-eCPhe8I5cE2cQR9jiO0Cf8HYq4B8dX4wk0i_CpoRfeFTr-IKQu-Dqu4XuQ48dRHOUDUeKi4jr-42SEPMfhc8h59EYtXHgOt1AOnwh_oCw-mEf5I8ugT0aOh4ZHHS1xGjlz6Mvxo4-D9EfYHdd26MGPfh4u7RC542WNXoiLE2R-9NrxIv0OiMW_I9rnoceJi8M-pqiVwxH6Hd9S3DhynOjh6-iso5SO5hKh50NfxO4Dr8MT4UrwxfCHvnijo0cTGvmhbkXPI8x0HOEP79BT-EfOwD8uRrgIPzgF-Ed19IUPwDmOQP1whAdx6ugE_0R97KhY5D966A5-NP_QB-_wHN92_CiMNjH2B3nwDf1gezgO8MjRHfpZ9CLMbMfxH82OH6_R_miOFz-O4xd6QDvQ_TCOwwdx5MPh4xcO18Rd-GhvIZCiE34E5Ad_8Dh8IocfaMWRBzV44sSRSRsPtD-Kw8yQC7_gr-iF4-hj-PhwBMcN6fCPj0iJ4weOsAegfTBS4IBL_AhxtIGPHz6OvkTMD9XRPMjRbTHhC-rxI8cP8-jBA8URaDjC4gf8HA5M4kXQh8d16Md7hHrgF76M8zCfCiFJHHoLnAi7BD5e5BIcI2-G7zjgHmeCIyaHH1_QG22Wwyf4HfmP5nyQS8nxoxe0kEvxCjuO40SF84JmPNiN8IQf3ITn48fxDv9goh9u9MiNo9B-HEeO4w98ochR3sEPrR2EH80FHD6ED9cRHDiIw0cPhDv0Azlx4Md1-AiPQziaC-Fn_EfzCJXk4RLCJ4Z3nMGdGat6_PBp5E-I9-iPH6-IKR0660TOQ8c_DqEl4YczFSeHnggP7oSeBj0N8gkY8fCP99DV44HP4y7Yg_Shr8GPXNRxDUZLBbX2wz7CQzsR5ikuCZV5NH9woiRxvMJzPBOcI8-twFSPksN_PMV3lDecb2DqoOdhlSh0T6i2PEifHP3wEwzJ48cFnxeeIiSPB-11ONoU9Dvy4CJ6wvJRP0Ko7nB9-EugkTqeHWKk5Hj5DX9OTEc6SsHTwNvx5zjCLC9KQYsTOsV1BfElNPrR0_h5vLjUI8_R29ByBvfxo4kZa8iP_RJ6XDpOVN6xH7mWFXpdIN8e-MgvPJkVnHhYQdYkbM_R7jP0OCgZ-AfEH10a_LiOr0Uz9uh5PNBs48aDC47xCucBVevBI7yL37iGHr4-hDpO6Jgo48YBTUdIofmMb_iFnkhlacSLS3hw5TiPXA8O98JqRO_xHcbxFZ9gzfhxiMfjID_-DhfSX6jf4eEKuXqwoxmXQMclHoejRhn4wwp3aPKFmi3Sow_O48fRHPWy4wev6AhfXAr0HUd0McYzdE8q_BZeNDrC9_hRNodr_Ec14tB-WD--I_cTXOgXXEeuH5fIoPmSojt0_NjvoX_gR_h3VA9e4zqkC8eHp2i0o5w8TEzg3sgPO8J1-MPR58h_6PiLZpL0os10HG_w5ugJ_-hK8bgR5jrOIeWh-8h_PDxu_Jh5ODTaI9-hhdGJvsiX40O_gUlq4T1y5Qcz9RDP40B949AOs0d4dGtgo8e14zSueMiPPj0eaLkQu8f34IX_gxdeVB8aHk9wI9eJdsdhmUZ-HEeKB8cdQ7xwiDxOwzh--PgO3PCHHv3xgz0-Hw_e4sGJH89yiPpx7Pjg4z7xEb8gUsSP5zhcHboPVyku9Mvx48R5aOdgThfyzOjxVgwuHo1-nPjhk4If5TgJ80jyZAifoTvuRujxHS_yGL5x4UJEIZ-C95iehcd9iPBzlBKf4UQuhIkY1KqDC79QoZ-gKzF-BxqjJ3B1RJIz41dQwfOFNkf441yOdx-O5tCT4jryHQ0u5UfDHUfOIFlKocePE07C0DiP3NBz9HJQLzp-PBo6cUdzHcd_Iz_6wz_SMTuqG03yoM8DHT96mFw05ETFCxdeGfHRY0dfAMYQMghBAQgAzBgHDgGcAoCYIMRA7ARSQEBGIFIMGEWEoIYMR4AQihkljADAKkAUAE4xIgIzRACilAhMKCacAgJAAIRhijAlBBFcIWCIgAAQIhSxjgggjAACAIEAAkYARAx5AhgCADJKEMgEI0QAJoAyhQiJiAAIIUAQIEJhJxARgADjCQCAACOAosgJIYUDRBBynaQCAEGFAYJQBIBSyjlplCIAWa-QM0cABoQAwhglmBnGWnCdFwJYJqAyICmEKIXWCOeEdI5ZI6ASglhlLJKSUKKdEUYbBgRATAAglBKGAEIQcIggxoADDAiGmAFEECAIAEIIpYwkJDJjnCUGKSsoQcAIRSgjHAVDqOEEGiesFNYZZ51AgABmnCIAKmKAEAAhhhwDBAIgACECGMCEIlAA5xwBQAihEGFIAAcEgAg4YgADQFmBBADEUMuEsoAIAAh1zDgChEGAMAEkgEBQxAAQhCGBlDEAGoKEAEZoAxAQkCCjABEAAE6AAAoAJZhggBFirEBAGAOUYUwxgAwkwjClBUNICCZcJIYQA4hDGAhjuAVDGCEFYwwCRpgwABCEoINOiGQcIcIRAQhxChDQBEBAMeAMVQAYICBTAAomDCBAMKYEIEYBQAiyBIACCYAAAQCJRAQgBACTCjFkmuOAEQaFBRYBgAICkBKAhDBEEUYkEMwIxZSwxjOhmECaEKWAIMA5IDuxUFiBFFKCAYeIFURoK7AUhhkKBTWHImGCs84oBxARRQkpBHBMEigMIsCCJ5BARiBHBURGCAIMZAgBoZhQijjDJBCOCQIIsMhYURALQggBBECCahGFIMQgIYCAQhlACBkQMiUIEVIqYRgDwCCiBAEUAAmKEAYaAwwwRCDwCFZCGIRNAw
Atom "©lyr" contains:
Atom "©grp" contains:
Atom "soar" contains: Kyd, Jesper
Atom "aART" contains: Jesper Kyd & Lorne Balfe
Atom "soaa" contains: Kyd, Jesper & Balfe, Lorne
Atom "©cmt" contains: Adjusted by iVolume 02/27/2012 11:07:39
```
