### ISSUE TITLE
Fetchart can't move the image

### ISSUE THREAD

**Issue by masterT** [beetbox/beets#2199]
### Fetchart can't move the image

It seem like the `fetchart` plugin try to move the fetched image in the `config.Library` path

```sh
beet -vv fetchart
```

Log

```
user configuration: /Users/simon/.config/beets/config.yaml
data directory: /Users/simon/.config/beets
plugin paths:
Sending event: pluginload
library database: /Users/simon/data/beets/musiclibrary.blb
library directory: /Users/simon/Music/Music
Sending event: library_opened
fetchart: trying source filesystem for album AbJo - Travel Heavy
fetchart: trying source coverart for album AbJo - Travel Heavy
artresizer: method is (2, (6, 9, 0))
fetchart: downloading image: http://coverartarchive.org/release/41f44ea6-8301-49cb-8fea-a4106a161534/front
fetchart: downloaded art to: /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmpCAPerJ.jpg
fetchart: image size: (2400, 2400)
fetchart: image needs resizing (2400 > 700)
fetchart: using remote image /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmpCAPerJ.jpg
artresizer: ImageMagick resizing /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmpCAPerJ.jpg to /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmpIeZ_r4.jpg
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/util/__init__.py", line 449, in move
    shutil.copyfile(path, dest)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/simon/Music/beets/AbJo/Travel Heavy/cover.jpg'

Error: No such file or directory while moving /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmpIeZ_r4.jpg to /Users/simon/Music/beets/AbJo/Travel Heavy/cover.jpg
```

### Setup

* OS: OS X El Capitan
* Python version: Python 2.7.10
* beets version: beets version 1.3.18
* Turning off plugins made problem go away (yes/no): 

Config

```yaml
convert:
    auto: yes
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    dest:
    threads: 4
    copy_album_art: no
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
lyrics:
    auto: yes
    force: yes
fetchart:
    auto: yes
    minwidth: 200
    maxwidth: 700
    enforce_ratio: yes
    ifempty: yes
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cautious: no
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
library: ~/data/beets/musiclibrary.blb

ui:
    color: yes
embedart:
    auto: yes
    remove_art_file: yes
    compare_threshold: 0
    ifempty: no
    maxwidth: 0

plugins: web convert fetchart embedart
directory: ~/Music/Music

import:
    write: yes
    move: yes
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
```

**Comment by sampsyo** [comment]
Wow; that's certainly strange. Needless to say, I can't reproduce that on my Mac. Does this happen every time, or just for some covers?

Does it go away if you turn off resizing in the fetchart plugin?

**Comment by masterT** [comment]
I turned off the resizing, it didn't work!

**Comment by sampsyo** [comment]
Can you please give full details (i.e., your updated config and the resulting verbose log)?

**Comment by masterT** [comment]
Config
```
convert:
    auto: yes
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    dest:
    threads: 4
    copy_album_art: no
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
lyrics:
    auto: yes
    force: yes
fetchart:
    enforce_ratio: yes
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
library: /Users/simon/data/_beets/musiclibrary.blb

ui:
    color: yes
embedart:
    auto: yes
    remove_art_file: yes
    compare_threshold: 0
    ifempty: no
    maxwidth: 0

plugins: web convert fetchart embedart
directory: /Users/simon/Music/Music

import:
    write: no
    move: no
    copy: no
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
```

Command 

```bash
beet -vv fetchart
```

Log 

```
user configuration: /Users/simon/.config/beets/config.yaml
data directory: /Users/simon/.config/beets
plugin paths:
Sending event: pluginload
library database: /Users/simon/data/_beets/musiclibrary.blb
library directory: /Users/simon/Music/Music
Sending event: library_opened
fetchart: trying source filesystem for album AbJo - Travel Heavy
fetchart: trying source coverart for album AbJo - Travel Heavy
fetchart: downloading image: http://coverartarchive.org/release/41f44ea6-8301-49cb-8fea-a4106a161534/front
fetchart: downloaded art to: /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmpkxhyT1.jpg
artresizer: method is (2, (6, 9, 0))
fetchart: image size: (2400, 2400)
fetchart: using remote image /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmpkxhyT1.jpg
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/util/__init__.py", line 454, in move
    shutil.copyfile(path, dest)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/simon/Music/beets/AbJo/Travel Heavy/cover.jpg'

Error: No such file or directory while moving /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmpkxhyT1.jpg to /Users/simon/Music/beets/AbJo/Travel Heavy/cover.jpg
```

**Comment by sampsyo** [comment]
That's certainly strange! Thanks for the additional information.

Here's one other idea: could this be interacting with the `convert` plugin in `auto` mode? Does the problem go away if you turn that off? (In general, this is a good debugging strategy: turn off plugins and functionality until the problem stops.)

**Comment by masterT** [comment]
Damn, it use the default config for `fetchart` and remove all the plugins and I still have this error.

### Config

```
directory: /Users/simon/Music/Music

import:
    write: no
    move: no
    copy: no

ui:
    color: yes
library: /Users/simon/data/_beets/musiclibrary.blb

plugins: fetchart
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
```

### Command 

```bash
beet -vv fetchart
```

### Log 

```
user configuration: /Users/simon/.config/beets/config.yaml
data directory: /Users/simon/.config/beets
plugin paths:
Sending event: pluginload
library database: /Users/simon/data/_beets/musiclibrary.blb
library directory: /Users/simon/Music/Music
Sending event: library_opened
fetchart: trying source filesystem for album Arctic Monkeys - Black Treacle
fetchart: trying source coverart for album Arctic Monkeys - Black Treacle
fetchart: downloading image: http://coverartarchive.org/release/e02d8ffe-9c6f-4bf3-9f6c-d61aa456956d/front
fetchart: downloaded art to: /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmp5uW1Pr.jpg
fetchart: using remote image /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmp5uW1Pr.jpg
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/util/__init__.py", line 454, in move
    shutil.copyfile(path, dest)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/simon/Music/beets/Arctic Monkeys/Black Treacle/cover.jpg'

Error: No such file or directory while moving /var/folders/z0/79byb2f55plcnbfdphvkw8k80000gn/T/tmp5uW1Pr.jpg to /Users/simon/Music/beets/Arctic Monkeys/Black Treacle/cover.jpg
```
