### ISSUE TITLE
'empty album' crash

### ISSUE THREAD

**Issue by kript** [beetbox/beets#2201]
### Problem

failure to use the convert function on OSX to convert FLAC (possibly any media) to mp3. I think its because the path isn't being escaped in the callout to ffmpeg

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import  ~/Music/FLAC/Hugh\ Laurie/
```

Led to this problem:

```
error: convert: couldn't invoke 'ffmpeg -i /Users/john/Music/FLAC/Hugh Laurie/Didn't It Rain (Special Edition Bookpack)/01 The St. Louis Blues-1.flac -y -vn -aq 2 /var/folders/02/6ncpzlt15kb6l4czdc7670ph0000gn/T/tmpINFSTE.mp3': [Errno 2] No such file or directory

```

Music files were FLAC
ffmpeg version N-81688-g38c3fc9-tessus

### Setup

* OS: Mac OSX 10.10.5
* Python version: 2.7.8
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): N/A

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    bing_client_secret: REDACTED
    google_API_key: REDACTED
    force: no
    google_engine_ID: REDACTED
    sources:
    - google
    - lyricwiki
    - lyrics.com
    - musixmatch
    auto: yes
    fallback:
    genius_api_key: REDACTED
    bing_lang_to:
smartplaylist:
    playlist_dir: /Volumes/NiftyMini/playlists
    playlists: [{name: all.m3u, query: ''}, {name: ReleasedIn$year.m3u, query: 'year::201(0|1|2|3|4)'}]
    auto: yes
    relative_to:
convert:
    ffmpeg: /Users/john/bin/ffmpeg
    max_bitrate: 320
    auto: yes
    dest: /Volumes/NiftyMini/music
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    threads: 4
    copy_album_art: no
    tmpdir:

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
library: /Volumes/NiftyMini/musiclibrary.blb

plugins: fetchart lyrics convert duplicates random info smartplaylist
directory: /Volumes/NiftyMini/music

import:
    log: /Volumes/NiftyMini/beets_log

match:
    strong_rec_thresh: 0.1
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
```
