### ISSUE TITLE
Directory structure for non-album tracks makes no sense

### ISSUE THREAD

**Issue by nagisa** [beetbox/beets#2218]
### Problem

Regular tracks associated with album are stored in `$ROOT/$ARTIST/$ALBUM/$TRACK_TEMPLATE` however the album-less tracks are stored in `$ROOT/Non-Album/$ARTIST/$TRACK_TEMPLATE`. If it was consistent you’d expect it to be `$ROOT/$ARTIST/Non-Album/$TRACK_TEMPLATE` or something.

### Setup

* OS: Arch linux
* Python version: 3.5.2
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
replaygain:
    backend: gstreamer
    targetlevel: 89
    auto: yes
    overwrite: no
library: $SOME_OTHER_PATH

plugins: chroma replaygain echonest
directory: $SOME_PATH

import:
    copy: no
    write: no
echonest:
    upload: no
    encode: no
acoustid:
    apikey: REDACTED
chroma:
    auto: yes
```
