### ISSUE TITLE
mbsync plugin should not give up on first failure

### ISSUE THREAD

**Issue by nagisa** [beetbox/beets#2219]
### Problem

Running mbsync plugin. A query it makes fails: 

```
Error: MusicBrainz not reachable in get release by ID with query u'some-existing-id'
mbsync: Release ID some-existing-id not found for album Some Album
```

and mbsync exits.

NB: not reliably reproducible (need flaky connection or some other cause for the failure.

The plugin should probably not fail overall on the first failure (perhaps only fail after a few failed requests). Bonus points for it retrying the failed requests later on.
### Setup
- OS: Arch Linux
- Python version: 3.5.1
- beets version: 1.3.18
- Turning off plugins made problem go away (yes/no): not applicable

My configuration (output of `beet config`) is:

``` yaml
replaygain:
    backend: gstreamer
    targetlevel: 89
    auto: yes
    overwrite: no
library: some path

plugins: chroma replaygain mbsync scrub
directory: some path

import:
    copy: no
    write: no
echonest:
    upload: no
    encode: no
acoustid:
    apikey: REDACTED
scrub:
    auto: yes
chroma:
    auto: yes
```
