### ISSUE TITLE
convert: Invocation of ffmpeg can make standard input break

### ISSUE THREAD

**Issue by Tmplt** [beetbox/beets#2234]
### Problem

Some times when using `beet convert` I'm unable to press Enter. Instead `^M` is printed.
To escape the prompt I must enter `EOF` (CTRL + d) after a CTRL + c.

``` sh
$ beet -vv convert [redacted; query] --dest .
user configuration: /home/tmplt/.config/beets/config.yaml
data directory: /home/tmplt/.config/beets
plugin paths:
Sending event: pluginload
library database: /home/tmplt/media/music/.lib/musiclibrary.blb
library directory: /home/tmplt/media/music
Sending event: library_opened
[redacted; tracks to convert]
Convert? (Y/n) ^M^M^M^M^M^Cerror: stdin stream ended while input required
```
### Setup
- OS: Arch Linux x64
- Python version: 2.7.12
- beets version: 1.3.18
- Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

``` yaml
directory: ~/media/music
library: ~/media/music/.lib/musiclibrary.blb

plugins: chroma fetchart embedart mpdstats ihate smartplaylist replaygain convert fetchart lastgenre fuzzy

import:
    move: no

embedart:
    remove_art_file: yes

ihate:
    warn:
        - album:christmas
        - genre:polka

smartplaylist:
    relative_to: ~/media/music
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name:  'All.m3u'
          query: '^artist:Two Steps From Hell'
        - name:  'Rock.m3u'
          query: 'genre:rock'
        - name:  'Metal.m3u'
          query: 'genre:metal'
        - name:  'Rap.m3u'
          query: 'genre:rap'
        - name:  'Space.m3u'
          query: ['artist:Ben Prunty', 'artist:Keldian', 'album:Space metal']
        - name:  'Power Metal.m3u'
          query: 'genre:Power Metal'
        - name:  'Symphonic Metal.m3u'
          query: 'genre:Symphonic Metal'


replaygain:
    backend: gstreamer

convert:
    embed: yes
    quiet: true
    never_convert_lossy_files: yes
    format: mp3
    formats:
        mp3:
            command: ffmpeg -i $source -qscale:a 0 $dest
            extension: mp3

```
### Notes:

Occurs in `st` and `termite`, both in and not in `tmux`.
