### ISSUE TITLE
Thumbnails Plugin

### ISSUE THREAD

**Issue by arnauldb** [beetbox/beets#2235]
### Problem

Thumbnails Plugin works fine and shows thumbnail on folder, but if I open the folder then close it, the thumbnail disappears and look like a regular folder, no thumbnail any more, never, for the folder I opened.
### Setup
- OS:  Ubuntu
- Python version: 
- beets version: last

My configuration (output of `beet config`) is:

``` yaml
directory: /home/arnauld/Music/beet
library: /home/arnauld/Desktop/musiclibrary.blb

import:
    move: no
    copy: yes
    write: yes

plugins: inline fromfilename discogs acousticbrainz fetchart embedart lastgenre chroma thumbnails lyrics missing

acousticbrainz:
 beet import: yes

fetchart:
    auto: yes
    sources: filesystem coverart itunes amazon albumart

chroma:
    auto: yes

missing:
    format: $albumartist - $album - $title
    count: no
    total: no   


```

thank you,
