### ISSUE TITLE
Beatport Plugin: Ignore '(Original Mix) in file names for search

### ISSUE THREAD

**Issue by itsbrex** [beetbox/beets#2237]
Is is possible to have Beets ignore `(Original Mix)` in file names when it performs the search query? If so then the % similarity would be nearly spot on with every song.

**Comment by sampsyo** [comment]
I don't believe it's currently configurable, but we actually do reduce the importance of text in parentheses. Do you happen to have a good example in hand of a match gone wrong?

**Comment by brianroach** [comment]
@sampsyo I will tag some more tracks today and post some examples. 

If Beets could ignore 'Original Mix)' but not '(xxxxx Remix)' or (xxxxx Dub Mix)' etc. then we'd really be onto something. ;)

**Comment by brianroach** [comment]
@sampsyo So I've got an example. How should I send it to you?

**Comment by brianroach** [comment]
The output of my ```beet config```

is this:

```
lyrics:
    bing_lang_from: []
    bing_client_secret: REDACTED
    google_API_key: REDACTED
    force: no
    google_engine_ID: REDACTED
    sources:
    - google
    - lyricwiki
    - lyrics.com
    - musixmatch
    auto: yes
    fallback:
    genius_api_key: REDACTED
    bing_lang_to:
fetchart:
    cautious: yes
    cover_names: cover front art album folder
    sources: itunes *
    maxwidth: 800
    enforce_ratio: yes
    auto: yes
    minwidth: 0
    google_engine: 001442825323518660753:hrh5ch1gjzm
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED

import:
    copy: no
    write: yes
    resume: yes
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
library: /Users/anodigital/github/beets/music.blb
original_date: yes
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
embedart:
    maxwidth: 1000
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
pluginpath: ~/github/beets/beetsplug

plugins: beatport edit embedart fetchart fuzzy importadded lyrics mbsync spotify types discogs duplicates

musicbrainz:
    user: brexy
    pass: REDACTED
mbcollection:
    auto: yes
acousticbrainz:
    auto: yes
threaded: yes
art_filename: cover
duplicate_action: remove
none_rec_action: skip
setlister:
    playlist_dir: ~/Music/ROACH\ Music/Setlists
beatport:
    source_weight: 0.5
    tokenfile: beatport_token.json
    apikey: REDACTED
    apisecret: REDACTED
ignore: .AppleDouble ._* *~ .DS_Store
edit:
    itemfields: track title artist album genre key bpm
    albumfields: album albumartist
    ignore_fields: id path

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

match:
    strong_rec_thresh: 0.05
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    ignored: missing_tracks unmatched_tracks
directory: /Users/anodigital/Music/beets_music
lastgenre:
    fallback: ''
    canonical: ''
    source: track
    count: 4
    force: no
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
group_albums: no
acoustid:
    apikey: OCRrjtfen1
discogs:
    source_weight: 0.5
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
importadded:
    preserve_write_mtimes: no
    preserve_mtimes: no
spotify:
    regex: []
    artist_field: albumartist
    mode: list
    track_field: title
    album_field: album
    region_filter:
    show_failures: no
    tiebreak: popularity
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
fuzzy:
    threshold: 0.7
    prefix: '~'
```
