### ISSUE TITLE
Discogs & Beatport don't prompt for authentication

### ISSUE THREAD

**Issue by axiom-nz** [beetbox/beets#2238]
### Problem

After installing the discogs-client and the requirements for beatport, I run the import and am not prompted for authentication by either discogs or beatport.   This is on OSX El Capitan

Running this command in verbose (`-vv`) mode:

``` sh
$ beet -vv import ~/Music/Music/_/Alix\ Perez\ \&\ Ivy\ Lab/Arkestra\ -\ EP
```

Led to this problem:

```
user configuration: /Users/user/.config/beets/config.yaml
data directory: /Users/user/.config/beets
Sending event: pluginload
no config file found at /Users/user/.beetsconfig
library database: /Users/user/.config/musiclibrary.blb
library directory: /Users/user/Music/Music
Sending event: library_opened
Sending event: import_task_start
Looking up: /Users/user/Music/Music/_/Alix Perez & Ivy Lab/Arkestra - EP
Tagging Alix Perez & Ivy Lab - Arkestra - EP
No album IDs found.
Search terms: Alix Perez & Ivy Lab - Arkestra - EP
Album might be VA: False
/Library/Python/2.7/site-packages/beetsplug/beatport.py:57: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  .format(e.message))
Beatport API Error: Error connection to Beatport API: HTTPConnectionPool(host='api.beatport.com', port=80): Max retries exceeded with url: /catalog/3/search?query=Alix+Perez+Ivy+Lab+Arkestra+EP&facets=fieldType%3Arelease&perPage=5 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1032065d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)) (query: Alix Perez & Ivy Lab Arkestra - EP)
Discogs API Error: 401: You must authenticate to access this resource. (query: Alix Perez & Ivy Lab Arkestra - EP)
Evaluating 5 candidates.
Candidate: Alix Perez & Lynx - Allegiance EP
Success. Distance: <beets.autotag.hooks.Distance object at 0x1029d5f10>
Candidate: Alix Perez & EPROM - Shades EP
Success. Distance: <beets.autotag.hooks.Distance object at 0x1028bf3d0>
Candidate: Alix Perez - Elephant Dreams - EP
Success. Distance: <beets.autotag.hooks.Distance object at 0x103206510>
Candidate: Alix Perez - 1984
Success. Distance: <beets.autotag.hooks.Distance object at 0x10329df50>
Candidate: Alix Perez - Dark Days EP
Success. Distance: <beets.autotag.hooks.Distance object at 0x10329df10>

/Users/user/Music/Music/_/Alix Perez & Ivy Lab/Arkestra - EP (6 items)
Finding tags for album "Alix Perez & Ivy Lab - Arkestra - EP".
Candidates:
1. Alix Perez - Elephant Dreams - EP (47.3%) (tracks, album, artist, ...) (Digital Media, 2016, XW, 1985 Music)
2. Alix Perez & EPROM - Shades EP (39.9%) (tracks, album, unmatched tracks, ...) (Digital Media, 2015, XW, Alpha Pup Records)
3. Alix Perez & Lynx - Allegiance EP (33.6%) (tracks, album, unmatched tracks, ...) (2x12" Vinyl, 2008, GB, Soul:R)
4. Alix Perez - Dark Days EP (31.6%) (tracks, album, artist, ...) (2x12" Vinyl, 2010, GB, Shogun Audio)
5. Alix Perez - 1984 (25.3%) (tracks, album, mediums, ...) (3x12" Vinyl, 2009, GB, Shogun Audio)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? b
Sending event: import
Sending event: cli_exit
```
### Setup
- OS:  OSX El Capitan
- Python version:  2.7.10
- beets version: 1.3.8
- Turning off plugins made problem go away (yes/no): not applicable 

My configuration (output of `beet config`) is:

``` yaml
directory: ~/Music/Music
library: ~/.config/musiclibrary.blb
import:
  move: yes
  write: yes
threaded: yes
plugins: discogs beatport lastgenre
lastgenre:
  auto: yes
discogs:
  auto: yes
  source_weight: 0.0
paths:
  default: $genre/$albumartist/$album%if{$catalognum, [$catalognum]}/$track $title
  comp: Compilations/$label/$album%if{$catalognum, [$catalognum]}/$track $title
  genre:"Drum And Bass": $genre/$label/$albumartist - $album%if{$catalognum, - [$catalognum]}/$track $title
  genre:"Breakbeat": $genre/$label/$albumartist - $album%if{$catalognum, - [$catalognum]}/$track $title
  genre:"Jungle": $genre/$label/$albumartist - $album%if{$catalognum, - [$catalognum]}/$track $title
  genre:"Liquid Funk": $genre/$label/$albumartist - $album%if{$catalognum, - [$catalognum]}/$track $title

```
