### ISSUE TITLE
Beets not writing vorbis comments to FLAC files when modifying

### ISSUE THREAD

**Issue by zigarrre** [beetbox/beets#2250]
### Problem

Beets doesn't write tag modifications done via `beet modify` into the files.

I tested it with FLAC files and the tags `PERFORMER`, `COMPOSER` and `DISC` all with the same result, so I assume it is independent of the tag.

#### Steps to reproduce

```
beet modify -wy title:'foo' PERFORMER='bar'
```

checking with `metaflac`

```
metaflac --list "$(beet list -p title:'foo')" | grep PERFORMER
```

prints

```
    comment[0]: PERFORMER=
```

should be

```
    comment[0]: PERFORMER=bar
```

### Setup

```
% uname -a         
Linux desktop 4.8.3-1-ARCH #1 SMP PREEMPT Thu Oct 20 19:53:59 CEST 2016 x86_64 GNU/Linux
% python2 --version
Python 2.7.12
% beet version     
beets version 1.3.18
no plugins loaded
% pacman -Ss beets 
community/beets 1.3.19-1 [installed]
    Flexible music library manager and tagger
```

```yaml
% beet config
ignore_hidden: no

paths:
    default: $albumartist/[$year] $album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: compilations/[$year] $album%aunique{}/$track $title
    albumtype:soundtrack: soundtracks/[$year] $album%aunique{}/$track $title
mpd:
    host: localhost
    port: 6600
log: ~/.beets_import_log
library: ~/.beets_musiclibrary.db
replaygain:
    backend: gstreamer
    auto: yes
    overwrite: no
    noclip: yes
    method: replaygain

ui:
    color: yes
directory: /media/sda2/music

import:
    copy: yes
```
