### ISSUE TITLE
embedart has invalid text encoding?

### ISSUE THREAD

**Issue by gboysko** [beetbox/beets#2264]
### Problem

When I try to `embedart` into an entire album, MP3Diag complains that the "text encoding is unsupported for APIC frame in ID3V2 tag". 

```sh
$ beet embedart grind
```

### Setup

* OS: Ubuntu 16.04
* Python version: 2.7.12
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): N/A

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/980425CD0425AF66/MP3s.new
import:
    move: yes
    write: yes
original_date: yes
asciify_paths: yes
id3v23: yes
plugins: edit embedart fetchart lastgenre scrub missing info
paths:
    default: $albumartist/$album%aunique{}/$track $title
replaygain:
    backend: gstreamer
```
