### ISSUE TITLE
beets import crash on bad unicode filenames

### ISSUE THREAD

**Issue by welch** [beetbox/beets#2267]
### Problem

__Summary__: 

while importing a directory containing filenames with questionable unicode, beets crashes during the decode.

__Details__:

Some perfectly nice unicode filenames on a Mac got mangled on their journey via a USB drive to an Intel NUC running ubuntu. When listing on the NUC, they look like:
/music/Legacy/Air/Moon Safari [0170 4 66644 17]/10 Le Voyage de P�n�lope.mp3

When `beet import` encounters one of these paths during sorted_walk's call to is_hidden(), it crashes at path.decode('utf-8') (stack trace forthcoming, I'm without access, it's the standard `codec can't decode byte xxx in position yyy error`). 

Dunno if there's anything nicer to be done than skip with an error (my local workaround). These tracks already have metadata, so the filename seems less important if there's any way to proceed without it. Anyway, not crashing is nice.

My configuration (output of `beet config`) is:

```yaml
duplicates:
    tiebreak:
        items: [bitrate, filesize]
    format: $artist - $album - $title .$format-$bitrate $path
    count: no
    full: no
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no

format_item: $artist - $album - $title .$format-$bitrate

ui:
    color: yes
    colors:
        text_success: green
        text_warning: purple
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

plugins: acousticbrainz convert duplicates edit fetchart fromfilename info lastgenre play
directory: /Volumes/Lexar/Music

import:
    copy: yes
    move: no
    duplicate_action: remove
library: /Users/welch/gd/Music/musiclibrary.blb
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
play:
    warning_threshold: -2
    use_folders: no
    warning_treshold: 100
    raw: no
    command:
    relative_to:
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
convert:
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    dest:
    auto: no
    threads: 4
    copy_album_art: no
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
acousticbrainz:
    auto: yes
lastgenre:
    count: 1
    source: album
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
```
