### ISSUE TITLE
`beet update` clears information

### ISSUE THREAD

**Issue by Freso** [beetbox/beets#2271]
### Problem

When running `beet update`, it will clear some information (probably information not stored in tags?).

See `beet update` output here:
https://gist.github.com/Freso/d847bcda9e375d7b0f69d002c7dd16f6

### Setup

* OS: Arch Linux
* Python version: Python 3.5.2
* beets version: [1.3.19.r421.g02bd794](https://github.com/beetbox/beets/tree/02bd7946c1f6dd84e0fd28d152f4bca5c09d9e0a) (using the [beets-python3-git AUR package](https://aur.archlinux.org/packages/beets-python3-git/))

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    sources: lyricwiki genius musixmatch
    bing_lang_to:
    force: no
    google_API_key: REDACTED
    bing_client_secret: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    auto: yes

import:
    move: yes
item_fields:
    artist_not_albumartist: artist != albumartist
asciify_paths: yes
convert:
    auto: yes
    format: vorbis
    never_convert_lossy_files: yes
    embed: no
    formats:
        vorbis:
            command: ffmpeg -hide_banner -i $source -y -vn -acodec libvorbis -aq 5.9999999999999999 $dest
            extension: ogg
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    tmpdir:
    max_bitrate: 500
    dest:
    quiet: no
    album_art_maxwidth: 0
    threads: 4
    copy_album_art: no
    pretend: no

    paths: {}

plugins: acousticbrainz chroma convert fetchart importadded info inline lastgenre lyrics mbsync permissions play spotify types
acoustid:
    apikey: REDACTED
spotify:
    region_filter: ES
    show_failures: no
    regex: []
    tiebreak: popularity
    album_field: album
    track_field: title
    artist_field: albumartist
    mode: list
directory: ~/Audio
lastgenre:
    canonical: yes
    source: track
    force: yes
    min_weight: 10
    count: 1
    prefer_specific: no
    whitelist: yes
    separator: ', '
    fallback:
    auto: yes
library: ~/.local/share/beets/library.db
fetchart:
    cautious: yes
    maxwidth: 1000
    sources: fanarttv coverart filesystem
    fanarttv_key: REDACTED
    store_source: yes
    google_key: REDACTED
    enforce_ratio: no
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    minwidth: 0
    auto: yes

paths:
    albumtype:audiobook: Audiobooks/$albumartist - $title%aunique{}
    singleton: Music/$artist/0000 - singletons/$title
    default: Music/$albumartist/$year - $album%aunique{albumartist album year,albumtype label catalognum albumdisambig}/$track. %if{$artist_not_albumartist,$artist - }$title
permissions:
    file: '644'
    dir: '755'
chroma:
    auto: yes
acousticbrainz:
    auto: yes
album_fields: {}
pathfields: {}
play:
    warning_treshold: 100
    command:
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: -2
importadded:
    preserve_mtimes: no
    preserve_write_mtimes: no
```
