### ISSUE TITLE
unidecode() needs a path escape

### ISSUE THREAD

**Issue by tweitzel** [beetbox/beets#2286]
### Alternate ticket title
Vaporwave artists are jerks

### Problem
Short version: ¢ gets decoded to 'C/' in ascii, which results in directories getting created mid-filename if using asciify_paths.

This album (track 21 of which is attached, as it causes the most weirdness) seems to be written solely to find bugs in beets, unicode, and filesystems. Notwithstanding the ¢ bug, track 25 got turned into a unicode comet emoji.

https://auto-7.bandcamp.com/album/greatest-hits
https://musicbrainz.org/release/c9dc947d-8fe1-4843-8ce9-7e9cdb56b64e

The database thinks this is the file:
/Users/xarph/Music/beets/hoesaAUTO/Greatest Hits/21 dollar menu (99C/ents + tax).mp3 - dollar menu (99¢ents + tax)

What happens instead is there's a file called 'ents + tax).mp3' inside a folder called '/Users/xarph/Music/beets/hoesaAUTO/Greatest Hits/21 dollar menu (99C'.
[UNICODE TOXIC WASTE HERE.zip](https://github.com/beetbox/beets/files/613985/UNICODE.TOXIC.WASTE.HERE.zip)

### Setup

* OS: Mac OS X 10.11.6
* Python version: 2.7.12
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
play:
    command: /usr/local/bin/mpv $args --display-tags='Artist,Album,Album_Artist,Genre,Title,Track,disc,date,icy-title,service_name' --vo null --no-audio-display --af=volume=replaygain-track --playlist
    warning_threshold: -2
    use_folders: no
    warning_treshold: 100
    raw: no
    relative_to:
scrub:
    auto: no
pluginpath: ~/work/whatlastgenre/plugin/beets/beetsplug
asciify_paths: yes
rewrite:
    "title \xA2": c
library: /Users/xarph/Music/beetslibrary.blb
original_date: yes
replaygain:
    backend: bs1770gain
    auto: yes
    overwrite: yes
    targetlevel: 89
    chunk_at: 5000
    method: replaygain

clutter: .DS_Store desktop.ini
importfeeds:
    formats: m3u_multi link
    dir: /Users/xarph/Music/beetsplaylist
    absolute_path: yes
badfiles:
    commands: {}

plugins: chroma replaygain ftintitle info duplicates web fromfilename scrub badfiles play random fetchart embedart acousticbrainz mbsync mbsubmit inline recordingdate wlg smartplaylist rewrite

paths:
    default: $albumartist/$album%aunique{}/$disc_and_track $title
    comp: Compilations/$album%aunique{}/$disc_and_track $artist - $title
    singleton: $artist/Unknown Album/$title

format_item: '$id: $artist - $album%aunique{} - $disc_and_track - $title ($year)'
item_fields:
    disc_and_track: u'%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
per_disc_numbering: yes
id3v23: no
smartplaylist:
    playlist_dir: ~/Music/beetsplaylists
    playlists: [{name: working.m3u, query: ['artist:ben prunty', 'artist:garoad', 'artist:vyking', 'album:Music to Die Alone in Space To: Tod Weitzel']}]
    auto: yes
    relative_to:
fetchart:
    auto: yes
    minwidth: 300
    enforce_ratio: yes
    sources: coverart itunes amazon albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
languages: en
lastgenre:
    fallback: Unfiled
    canonical: yes
    whitelist: /Users/xarph/.config/beets/genres.txt
    source: album
    force: yes
    count: 1
directory: /Users/xarph/Music/beets

import:
    move: no
    copy: yes
    write: yes
    log: /Users/xarph/Music/beetslog.txt

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
wlg:
    auto: no
    count: 1
    force: yes
    whitelist: wlg
    separator: ', '
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
acousticbrainz:
    auto: yes
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
pathfields: {}
album_fields: {}
chroma:
    auto: yes
mbsubmit:
    threshold: medium
    format: $track. $title - $artist ($length)
web:
    host: 127.0.0.1
    port: 8337
    cors: ''

```
