### ISSUE TITLE
discogs: Match individual subtracks

### ISSUE THREAD

**Issue by welch** [beetbox/beets#2318]
### Problem
I'm trying to import this album:
https://www.discogs.com/Erich-Wolfgang-Korngold-Jerome-Moross-Franz-Waxman-Colin-Towns-featuring-The-Korngold-Quartet-Scott-/release/3647530

In the tracklist there are 0-length "index" items naming the work to which the next few tracks belong. These do not have track numbers. The tracks themselves are listed as "subtracks", and have the proper global track numbers (in the listing, and as ripped from my CD. track numbers and times agree between them). 

Beets does not see any of the track numbers that exist as "subtracks". It sees this album as containing a single track, #13, which it wants to renumber as #1 during import. 

Here's the output proposing the partial match for the album:
```
Correcting tags from:
    Jerome Moross - Classical Hollywood III
To:
    Erich Wolfgang Korngold / Jerome Moross / Franz Waxman / Colin Towns featuring The Korngold Quartet, Scott Woolley, The Mildred Pierce Orchestra - Classical Hollywood III
URL:
    https://www.discogs.com/Erich-Wolfgang-Korngold-Jerome-Moross-Franz-Waxman-Colin-Towns-featuring-The-Korngold-Quartet-Scott-/release/3647530
(Similarity: 36.6%) (unmatched tracks, artist, source, tracks) (Discogs, CD, 1992, US, Bay Cities)
CD: Quintet For Piano And Strings
 * American Suite For Orchestra (#13) -> American Suite For Orchestra (#1) (index)
Unmatched tracks (12):
 ! 01  (#1) (3:00)
 ! 02  (#2) (4:48)
 ! 03  (#3) (2:45)
 ! 04  (#4) (1:53)
 ! 05  (#5) (12:36)
 ! 06  (#6) (12:14)
 ! 07  (#7) (8:54)
 ! 08  (#8) (1:30)
 ! 09  (#9) (3:51)
 ! 10  (#10) (1:26)
 ! 11  (#11) (1:11)
 ! 12  (#12) (5:27)
```

(that item 13 it wants to renumber to 1 should really be 13)

### Setup

* OS: Mac OS 10.11.5
* Python version: 2.7.12 
* beets version:  1.3.18
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
duplicates:
    tiebreak:
        items: [bitrate, filesize]
    format: $artist - $album - $title .$format-$bitrate $path
    count: no
    full: no
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no

format_item: $artist - $album - $title .$format-$bitrate

ui:
    color: yes
    colors:
        text_success: green
        text_warning: purple
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

plugins: acousticbrainz convert duplicates edit fetchart fromfilename info lastgenre play discogs
directory: /Users/welch/Music/Beets

import:
    copy: no
    move: no
    duplicate_action: keep
library: /Users/welch/gd/Music/musiclibrary.blb
acousticbrainz:
    auto: yes
convert:
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    dest:
    auto: no
    threads: 4
    copy_album_art: no
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
lastgenre:
    count: 1
    source: album
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
play:
    warning_threshold: -2
    use_folders: no
    warning_treshold: 100
    raw: no
    command:
    relative_to:
```
