### ISSUE TITLE
cannot zero in "as-is" mode

### ISSUE THREAD

**Issue by simonbcn** [beetbox/beets#2320]
### Problem

When I import an album with `Use as-is` because it doesn't find the right album information, beets shows this message: `cannot zero in "as-is" mode`. Why?

I want it imports the tracks with its metadata but I want too it deletes certain fields. Why it cannot?

My configuration (output of `beet config`) is:

```yaml
directory: "/home/juan/M\xFAsica/"
library: /home/juan/.beets/musiclibrary.blb
#threaded: no

plugins: convert fetchart info duplicates badfiles zero replaygain embedart lastgenre scrub chroma discogs fromfilename

fetchart:
  auto: yes
  maxwidth: 300

embedart:
  auto: yes
  maxwidth: 300
  remove_art_file: yes

match:
  strong_rec_thresh: 0.20
#  max_rec:
#    missing_tracks: strong
    
import:
  art: yes
  languages: es en

paths:
  default: $albumartist/$album/$track - $title
  singleton: $artist - $title
  comp: Varios/$album/$track - $title

replaygain:
  backend: bs1770gain
  overwrite: yes

lastgenre:
  auto: no
  canonical: yes
  count: 3
   
convert:
  auto: yes
  tmpdir: /tmp
  command: ffmpeg -i $source -y -codec:a libmp3lame -vn -qscale:a 1 $dest
  extension: mp3
  #embed: yes
  quiet: yes
  never_convert_lossy_files: yes
   
duplicates:
  path: yes
#   checksum: yes

scrub: 
  auto: yes  

zero:
  fields: comments albumartist_sort artist_sort albumartist_sort
  update_database: true

acoustid:
  apikey: cKEYu7Ccgf
```
