### ISSUE TITLE
UnicodeDecodeError when trying to play a song in mpd client (BPD)

### ISSUE THREAD

**Issue by MG2R** [beetbox/beets#2332]
### Problem

When trying to serve an mpd client (either sonata or cantata, same results), playback fails and the beets server outputs the following error on the terminal:

```sh
 $ beet -vv bpd
user configuration: /home/simon/.config/beets/config.yaml
data directory: /home/simon/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/simon/.config/beets/library.db
library directory: /home/simon/music
Sending event: library_opened
Building directory tree...
... done.
bpd: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/beetsplug/bpd/__init__.py", line 685, in run
    for data in results:
  File "/usr/lib/python2.7/site-packages/beetsplug/bpd/__init__.py", line 917, in _add
    for item in self._all_items(self._resolve_path(path)):
  File "/usr/lib/python2.7/site-packages/beetsplug/bpd/__init__.py", line 820, in _resolve_path
    components = path.split(u'/')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```
Happens with any music file I try. This is a fresh library (just set everything up).

### Setup

* OS: Arch Linux
* Python version: 2.7.12
* beets version: 1.4.2
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/music

paths:
    default: $albumartist/$album%aunique{} ($original_year)/$artist - $album - $track - $title
    singleton: $artist/__single_tracks/$artist - $title
    comp: __compilations/$album%aunique{} ($original_year)/$artist - $album - $track - $title
replaygain:
    backend: command
    targetlevel: 89
    auto: yes
    overwrite: no
    command: ''
    noclip: yes
fetchart:
    maxwidth: 480
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder

plugins: web chroma fromfilename fetchart scrub mbsync replaygain bpd
bpd:
    volume: 100
    host: ''
    password: REDACTED
    port: 6600
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
chroma:
    auto: yes
scrub:
    auto: yes

```
