### ISSUE TITLE
Metasync plugin fails to match anything in library.

### ISSUE THREAD

**Issue by pirish** [beetbox/beets#2335]
### Problem

Running 'beets metasync' is unable to match anything in my itunes library.  I've tried running a sync after importing directly from the itunes library with and without tagging on import.  I've verified the the tracks are in the library.xml file.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv metasync
user configuration: /Users/patirish/.config/beets/config.yaml
data directory: /Users/patirish/.config/beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: /Users/patirish/music/beets/data/library.db
library directory: /Users/patirish/music/beets
Sending event: library_opened
metasync: loading iTunes library from /Users/patirish/music/beets/data/Library.xml
```

Led to this problem:

```
metasync: loading iTunes library from /Users/patirish/music/beets/data/Library.xml
metasync: no iTunes match found for A Day Well Spent - The What CD - Tied to Dead Lines
metasync: no iTunes match found for A German Spectacle - The What CD - We Heard The Tree Fall
metasync: no iTunes match found for A Plus D - Best of Bootie 2012 - Levels That I Used to Know (Gotye vs. Avicii)
metasync: no iTunes match found for A Plus D - Best of Bootie 2012 - We Are Never Ever Getting the Sweater (Taylor Swift vs. Weezer)
....
....
```

Attached is the entry from the library.xml file corresponding to the first error

```xml
		<key>4602</key>
		<dict>
			<key>Track ID</key><integer>4602</integer>
			<key>Name</key><string>Tied to Dead Lines</string>
			<key>Artist</key><string>A Day Well Spent</string>
			<key>Album</key><string>The What CD</string>
			<key>Kind</key><string>MPEG audio file</string>
			<key>Size</key><integer>5483759</integer>
			<key>Total Time</key><integer>240248</integer>
			<key>Track Number</key><integer>11</integer>
			<key>Year</key><integer>2008</integer>
			<key>Date Modified</key><date>2016-09-22T01:27:13Z</date>
			<key>Date Added</key><date>2016-09-30T20:17:04Z</date>
			<key>Bit Rate</key><integer>182</integer>
			<key>Sample Rate</key><integer>44100</integer>
			<key>Play Count</key><integer>2</integer>
			<key>Play Date</key><integer>3559070248</integer>
			<key>Play Date UTC</key><date>2016-10-12T02:37:28Z</date>
			<key>Rating</key><integer>60</integer>
			<key>Album Rating</key><integer>60</integer>
			<key>Album Rating Computed</key><true/>
			<key>Normalization</key><integer>3086</integer>
			<key>Sort Album</key><string>What CD</string>
			<key>Sort Artist</key><string>Day Well Spent</string>
			<key>Persistent ID</key><string>C9D560FF64F639B9</string>
			<key>Track Type</key><string>File</string>
			<key>Location</key><string>file:///Users/patirish/Music/iTunes/iTunes%20Music/Music/A%20Day%20Well%20Spent/The%20What%20CD/11%20Tied%20to%20Dead%20Lines.mp3</string>
			<key>File Folder Count</key><integer>5</integer>
			<key>Library Folder Count</key><integer>1</integer>
		</dict>
```

### Setup

* OS: OSX 10.11.6
* iTunes: 12.5.4.42
* Python version: Python 2.7.10
* beets version:
beet --version
beets version 1.4.2
Python version 2.7.10
plugins: bpd, fetchart, lastgenre, lyrics, metasync, web 
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
directory: ~/music/beets
library: ~/music/beets/data/library.db
threaded: yes
import:
    move: no
    copy: yes
    write: yes
    resume: yes
    quiet_fallback: skip
    timid: no
    log: beetslog.txt

match:
    strong_rec_thresh: 0.10

ignore: .AppleDouble ._* *~ .DS_Store
ignore_hidden: yes
art_filename: albumart
convert:
    dest: ~/music/converted

plugins: fetchart lyrics lastgenre bpd web metasync

ui:
    color: yes

paths:
    default: $genre/$albumartist/$album/$track $title
    singleton: Singletons/$artist - $title
    comp: $genre/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title

metasync:
    source: itunes
    itunes:
        library: ~/music/beets/data/Library.xml
```

Let me know if you need anything else.
