### ISSUE TITLE
discogs: Track IDs not fetched

### ISSUE THREAD

**Issue by welch** [beetbox/beets#2336]
### Problem

While importing tracks correctly identified as 
https://www.discogs.com/The-Larry-Goldings-Trio-Moonbird/release/8913670
the import appears to succeed, yet track id's are not stored.
`beet info moonbird` gives this same set of id's for each track:

```
    mb_albumartistid: 354487
    mb_albumid: 8913670
    mb_artistid: 354487
    mb_releasegroupid:
    mb_trackid:
```
those are discogs id's, and no track has an mb_trackid, although the tracks
are given their proper titles.

This came to my attention because the `duplicates` command sees all these
tracks as duplicates of each other. I've done the drill of `beet rm moonbird`
and reimporting their directory, behavior is consistent.

### Setup

* OS: ubuntu 16.04
* Python version: 2.7.12
* beets version: 1.4.2
* Turning off plugins made problem go away (yes/no): uuuuuuhhhhh

My configuration (output of `beet config`) is:

```yaml

format_item: $artist - $album - $title .$format-$bitrate
duplicates:
    tiebreak:
        items: [added, bitrate, country]
        albums: [added]
    format: $artist - $album - $title .$format-$bitrate $path
    count: no
    full: no
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
library: /music/beets/musiclibrary.blb

ui:
    color: yes
    colors:
        text_success: green
        text_warning: purple
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

plugins: acousticbrainz convert duplicates edit fetchart fromfilename info lastgenre play discogs
directory: /archive/music/

import:
    move: yes
    duplicate_action: remove
    log: /music/beets/log/flacs-2016-12-09.log
    ignore_hidden: no

match:
    strong_rec_thresh: 0.15
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
acousticbrainz:
    auto: yes
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
lastgenre:
    count: 1
    source: album
    prefer_specific: no
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
play:
    warning_threshold: -2
    use_folders: no
    warning_treshold: 100
    raw: no
    command:
    relative_to:
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
convert:
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    dest:
    auto: no
    threads: 4
    copy_album_art: no
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
```
