### ISSUE TITLE
beets 1.4.2 possibly causing video errors on Linux server

### ISSUE THREAD

**Issue by Maitaikawika** [beetbox/beets#2373]
### Problem

I am doing a multi-thousand song/album import and after "a while" (time frame varies) the terminal window I am using gets inundated with what appears to be endless Linux libva related messages. Beets is still working, or so it appears, but that point is moot since the libva errors are scrolling frequently which causes beets information to scroll off screen.

Running beets appears to be the only way (so far as I have found) to trigger the errors, and exiting beets causes the errors to stop. This is reproducible. No relation to any specific time interval, file, file type, album, artist or activity seems apparent.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import "/DataVolume/MediaLib/iTunes"
```

Led to this problem:

```
The following errors repeatedly appear on the terminal window:
error: XDG_RUNTIME_DIR not set in the environment.
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0

They don't appear to be coming from beets per se, but beets is tickling something that seems to cause linux to throw them.
```

Here's a link to the music files that trigger the bug (if relevant): 

No specific file appears to trigger it.

### Setup

* OS: Ubuntu 16.04.1 LTS, 4.4.0-57-generic kernel, 64 bit, server variant (so no X windows, no desktop and no desktop apps loaded), fully updated from Ubuntu repositories as of 01/02/17
* Python version: 2.7.12
* beets version: 1.4.2
* Turning off plugins made problem go away (yes/no): Maybe?  Unable to recreate problem with plugins turned off, but due to the inability to predict when problem will occur I cannot say with 100% certainty whether disabling plugins affected it or not.

My configuration (output of `beet config`) is:

```yaml
ignore_hidden: yes

paths:
    default: $albumartist - $album%aunique{}/$track - $title
    singleton: Non-Album - $album%aunique{}/$track - $title
    comp: Compilations - $album%aunique{}/$track - $title
    albumtype:soundtrack: Soundtracks - $album%aunique{}/$track - $title
threaded: yes
art_filename: albumart
chroma:
    auto: yes
library: /DataVolume/MediaLib/.beets_database
ignore: .AppleDouble ._* *~ .DS_Store
replaygain:
    auto: yes
    backend: gstreamer
    overwrite: yes
    targetlevel: 89

ui:
    color: no

plugins: chroma fetchart embedart scrub discogs replaygain
directory: /DataVolume/MediaLib/MusicLib

import:
    copy: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
scrub:
    auto: yes
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
```
