### ISSUE TITLE
musicbrainz: Use artist alias closest to tags

### ISSUE THREAD

**Issue by microcreators** [beetbox/beets#2378]
### Problem
If an artist use many aliases, the importing and auto-tagging functionality of beets and musicbrianz suggest the main artist name only, trying to fix the existing alias. As the alias was officially used, it should be retained.
Suggestion: keep the artist alias closes to the one present in tags.

Led to this problem:
Example: the band KLF used many other names incl. 2K. This release ([https://www.discogs.com/2K-k-The-Millennium/release/127207]) is identified forced to change the artist, despite the fact that the referenced musicbrainz URL is linked with  the alias.

```
Correcting tags from:
    2k - ***k the millennium
To:
    The KLF - ***k the Millennium
URL:
    http://musicbrainz.org/release/3ec83d1e-4f91-48aa-89dd-ac3bd75dd35a
```

### Setup

* OS: debian
* Python version: 2.7.9
* beets version: 1.4.2
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /z/sounds_the_rest
library: /h/beets/library.db
asciify_paths: yes
format_album: %lower{$albumartist} - %lower{$album}
import:
    copy: no
    write: no
plugins: discogs
```
