### ISSUE TITLE
beets 1.4.3 on Python 3.6: MPDupdate produces `TypeError: must be str, not bytes`

### ISSUE THREAD

**Issue by Antagonym** [beetbox/beets#2383]
### Problem
Since updating to beets 1.4.3 the `mpdupdate` plugin seems broken. Whenever it is triggered, it produces the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1198, in _raw_main
    plugins.send('cli_exit', lib=lib)
  File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 452, in send
    result = handler(**arguments)
  File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/beetsplug/mpdupdate.py", line 92, in update
    config['mpd']['password'].as_str(),
  File "/usr/lib/python3.6/site-packages/beetsplug/mpdupdate.py", line 108, in update_mpd
    resp = s.readline()
  File "/usr/lib/python3.6/site-packages/beetsplug/mpdupdate.py", line 53, in readline
    self.buf += data
TypeError: must be str, not bytes
```

Running any command that would result in an MPD database update in verbose (`-vv`) mode does give any more insight than that stacktrace already provides, so I'll leave this part out. (Unless you insist.)

It might also be worth noting, that during some update since 1.4.1, the python version beets used changed from 2.7 to 3.x, though that may have been intended, since 1.4.2 introduced experimental support for Python 3.x if I recall correctly.

### Setup

* OS: Arch Linux, Kernel 4.8.13-1
* Python version: 3.6.0
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): yes (Duh! :)

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    sources:
    - google
    - lyricwiki
    - lyrics.com
    - musixmatch
library: ~/.config/beets/library.db
directory: ~/music
pluginpath: [~/.config/beets/plugins]

plugins:
- chroma
- fromfilename
- edit
- embedart
- fetchart
- lyrics
- mbsync
- mpdupdate
- scrub
- inline
- thumbnails
- convert
- info
- mbcollection
- missing
- random

replace:
    '[\\/]': ''
    ^\.: ''
    '[\x00-\x1f]': ''
    '[<>,;:"\?\*\|\(\)\[\]]': ''
    "['\u2019]": ''
    "\xE9": e
    "\u2010": '-'
    "\u2026": '...'
    \.$: ''
    \s+$: ''
    ^\s+: ''
    \s+: .
    \.+: .
original_date: yes
per_disc_numbering: yes

import:
    resume: yes
    incremental: yes
    timid: yes
    languages: [en]
    detail: yes

match:
    strong_rec_thresh: 0.05

paths:
    default: $albumartist/$album.$original_year%aunique{albumartist album year, albumtype label catalognum albumdisambig}/$disctrack-$title
    singleton: Single/$artist/$title
    comp: Various.Artists/$album.$original_year%aunique{album year, label catalognum albumdisambig}/$disctrack-$title
    albumtype:soundtrack: Soundtracks/$album.$original_year%aunique{album year, label catalognum albumdisambig}/$disctrack-$title
chroma:
    auto: yes
acoustid:
    apikey: REDACTED
edit:
    itemfields:
    - disc
    - track
    - artist
    - album
    - title
    albumfields: [albumartist, album, year]
    ignore_fields: id path
embedart:
    auto: no
    compare_treshold: 50
    ifempty: yes
    maxwidth: 512
    compare_threshold: 0
    remove_art_file: no
fetchart:
    minwidth: 256
    auto: yes
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
mpd:
    rating_mix: 0.7
    host: localhost
    port: 6600
    password: REDACTED
scrub:
    auto: no
item_fields:
    disctrack: u'%02i.%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
convert:
    copy_album_art: yes
    dest: ~/music/00_export
    embed: no
    threads: 8
    format: opus
    formats:
        opus:
            command: opusenc --vbr --bitrate 128 --comp 10 $source $dest
            extension: opus
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    pretend: no
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no

    paths: {}
    never_convert_lossy_files: no
    album_art_maxwidth: 0

musicbrainz:
    user: REDACTED
    pass: REDACTED
missing:
    count: yes
    total: yes
check:

    import: yes
    write-check: yes
    write-update: yes
    convert-update: yes
thumbnails:
    auto: yes
    force: no
    dolphin: no
mbcollection:
    auto: no
pathfields: {}
album_fields: {}
```
