### ISSUE TITLE
Akiko Suwanai transliterates weirdly when languages: en

### ISSUE THREAD

**Issue by tweitzel** [beetbox/beets#2401]
### Problem

This album:
http://musicbrainz.org/release/d48690a8-8bb2-4925-b227-2fb773eb09c3

Transliterates badly, becoming
/Users/xarph/Music/beets/Johann Sebastian Bach; The Chamber Orchestra of Europe, Zou Fang Nei Jing Zi/Violin Concertos

Instead of using the english name for 諏訪内晶子 which musicbrainz has as "Akiko Suwanai".

```sh
101:~ xarph$ beet im /Users/xarph/Music/iTunes/iTunes\ Media/Music/Akiko\ Suwanai\ \&\ Chamber\ Orchestra\ of\ Europe/Bach_\ Violin\ Concertos/01\ Concerto\ for\ 2\ Violins,\ Strings,\ and\ Continuo\ in\ D\ minor,\ BWV\ 1043_\ I.\ Vivace.m4a

/Users/xarph/Music/iTunes/iTunes Media/Music/Akiko Suwanai & Chamber Orchestra of Europe/Bach_ Violin Concertos/01 Concerto for 2 Violins, Strings, and Continuo in D minor, BWV 1043_ I. Vivace.m4a (1 items)
Finding tags for album "Akiko Suwanai & Chamber Orchestra of Europe - Bach: Violin Concertos".
Candidates:
1. Johann Sebastian Bach; Scottish Chamber Orchestra, Jaime Laredo - Bach Violin Concertos (44.3%) (missing tracks, artist, tracks, ...) (CD, 1985, GB, IMP)
2. Johann Sebastian Bach; Ruggiero Ricci, City of London Ensemble - Bach Violin Concertos (42.4%) (missing tracks, artist, tracks, ...) (CD, 1994, GB, Unicorn-Kanchana Records)
3. Johann Sebastian Bach; 諏訪内晶子, The Chamber Orchestra of Europe - Violin Concertos (41.4%) (missing tracks, artist, album, ...) (CD, 2006, XE, Philips)
4. Jean Sibelius, Sir William Walton; 諏訪内晶子, City of Birmingham Symphony Orchestra, Sakari Oramo - Violin Concertos (37.4%) (missing tracks, artist, tracks, ...) (Hybrid SACD, 2003, US, Philips Classics)
5. Johann Sebastian Bach; The Chamber Orchestra of Europe, 諏訪内晶子 - Violin Concertos (37.1%) (missing tracks, artist, album, ...) (Digital Media, 2006, XW, Decca Classics)
6. Johann Sebastian Bach - Concertos for 1, 2 and 3 Violins (20.8%) (missing tracks, album, artist, ...)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, Print tracks? 5
Correcting tags from:
    Akiko Suwanai & Chamber Orchestra of Europe - Bach: Violin Concertos
To:
    Johann Sebastian Bach; The Chamber Orchestra of Europe, 諏訪内晶子 - Violin Concertos
URL:
    http://musicbrainz.org/release/d48690a8-8bb2-4925-b227-2fb773eb09c3
(Similarity: 37.1%) (missing tracks, artist, album, country, media) (Digital Media, 2006, XW, Decca Classics)
 * Concerto for 2 Violins, Strings, and Continuo in D minor, BWV 1043: I. Vivace ->
   Concerto for 2 Violins, Strings and Continuo in D minor, BWV 1043: I. Vivace
Missing tracks (12/13 - 92.3%):
 ! Concerto for 2 Violins, Strings and Continuo in D minor, BWV 1043: II. Largo ma non tanto (#2) (6:37)
 ! Concerto for 2 Violins, Strings and Continuo in D minor, BWV 1043: III. Allegro (#3) (7:19)
 ! Violin Concerto no. 2 in E, BWV 1042: I. Allegro (#4) (7:28)
 ! Violin Concerto no. 2 in E, BWV 1042: II. Adagio (#5) (5:50)
 ! Violin Concerto no. 2 in E, BWV 1042: III. Allegro assai (#6) (2:34)
 ! Concerto for Violin, Oboe and Strings in D minor, BWV 1060: I. Allegro (#7) (4:47)
 ! Concerto for Violin, Oboe and Strings in D minor, BWV 1060: II. Adagio (#8) (4:48)
 ! Concerto for Violin, Oboe and Strings in D minor, BWV 1060: III. Allegro (#9) (3:25)
 ! Violin Concerto no. 1 in A minor, BWV 1041: I. (Allegro moderato) (#10) (3:41)
 ! Violin Concerto no. 1 in A minor, BWV 1041: II. Andante (#11) (5:55)
 ! Violin Concerto no. 1 in A minor, BWV 1041: III. Allegro assai (#12) (3:34)
 ! Violin Sonata no. 3 in C, BWV 1005: III. Largo (#13) (3:17)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, Print tracks? a
```

Led to this problem:

```
101:~ xarph$ beet ls -p concerto for 2 violins
/Users/xarph/Music/beets/Johann Sebastian Bach; The Chamber Orchestra of Europe, Zou Fang Nei Jing Zi/Violin Concertos/01 Concerto for 2 Violins, Strings and Continuo in D minor, BWV 104.m4a
```

Here's a link to the music files that trigger the bug (if relevant): 
https://itunes.apple.com/us/album/concerto-for-2-violins-strings/id151269848?i=151269868

### Setup

* OS: OS X 10.11.6
* Python version: 2.7.13
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no):  no
My configuration (output of `beet config`) is:

```yaml
play:
    command: /usr/local/bin/mpv $args --display-tags='Artist,Album,Album_Artist,Genre,Title,Track,disc,date,icy-title,service_name' --vo null --no-audio-display --af=volume=replaygain-track --playlist
    warning_threshold: -2
    use_folders: no
    warning_treshold: 100
    raw: no
    relative_to:
scrub:
    auto: no
pluginpath: ~/work/whatlastgenre/plugin/beets/beetsplug
asciify_paths: yes
rewrite:
    "title \xA2": c
library: /Users/xarph/Music/beetslibrary.blb
original_date: yes
replaygain:
    backend: command
    auto: yes
    overwrite: yes
    targetlevel: 89
    command: ''
    noclip: yes

clutter: .DS_Store desktop.ini
importfeeds:
    formats: m3u_multi link
    dir: /Users/xarph/Music/beetsplaylist
    absolute_path: yes
badfiles:
    commands: {}

plugins: chroma replaygain ftintitle info duplicates web fromfilename scrub badfiles play random fetchart embedart acousticbrainz mbsync mbsubmit inline recordingdate wlg smartplaylist rewrite bpd

paths:
    default: $albumartist/$album%aunique{}/$disc_and_track %left{$title,64}
    comp: Compilations/$album%aunique{}/$disc_and_track $artist - %left{$title,64}
    singleton: $artist/Unknown Album/%left{$title,64}

format_item: '$id: $artist - $album%aunique{} - $disc_and_track - $title ($year)'
item_fields:
    disc_and_track: u'%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
per_disc_numbering: yes
id3v23: no
smartplaylist:
    playlist_dir: ~/Music/beetsplaylists
    playlists: [{name: working.m3u, query: ['artist:ben prunty', 'artist:garoad', 'artist:vyking', 'album:Music to Die Alone in Space To: Tod Weitzel']}]
    auto: yes
    relative_to:
fetchart:
    auto: yes
    minwidth: 300
    enforce_ratio: yes
    sources: coverart itunes amazon albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
languages: en
lastgenre:
    fallback: Unfiled
    canonical: yes
    whitelist: /Users/xarph/.config/beets/genres.txt
    source: album
    force: yes
    count: 1
directory: /Users/xarph/Music/beets

import:
    move: no
    copy: yes
    write: yes
    log: /Users/xarph/Music/beetslog.txt

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
wlg:
    auto: no
    count: 1
    force: yes
    whitelist: wlg
    separator: ', '
mbsubmit:
    threshold: medium
    format: $track. $title - $artist ($length)
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
pathfields: {}
album_fields: {}
acousticbrainz:
    auto: yes
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
chroma:
    auto: yes
bpd:
    volume: 100
    host: ''
    password: REDACTED
    port: 6600
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
```
