### ISSUE TITLE
ZSH completion error: zregexparse:4: not enough regex arguments

### ISSUE THREAD

**Issue by duckpuppy** [beetbox/beets#2414]
### Problem

When installing the zsh completion (I used wget on the "raw" url to get the current version of the completion script), I get the following when trying to complete:

```
❯ beet list artist:<TAB>
_beet:zregexparse:4: not enough regex arguments
_beet:zregexparse:4: not enough regex arguments
_beet:zregexparse:4: not enough regex arguments
```

Running `which _beet` returns

```
❯ which _beet
_beet () {
        local _ra_p1 _ra_p2 _ra_left _ra_right _ra_com expl tmp nm="$compstate[nmatches]"
        local _ra_actions _ra_line="${(pj:\0:)${(@)words[1,CURRENT - 1]:Q}}"$'\0'"$PREFIX"
        _ra_actions=()
        zregexparse -c _ra_p1 _ra_p2 "$_ra_line" $'/[^\0]##\0/' $'(' $'(' $'/-c\0/' $':_ra_comp $\'options:global options:(( -c:path\\\\ to\\\\ configuration\\\\ file ))\'' $'/[^\0]##\0/' $':_ra_comp $\'file:file:_files\'' $'|' $'/-v\0/' $':_ra_comp $\'options:global options:(( -v:print\\\\ debugging\\\\ information ))\'' $'|' $'/-l\0/' $':_ra_comp $\'options:global options:(( -l:library\\\\ database\\\\ file\\\\ to\\\\ use ))\'' $'/[^\0]##\0/' $':_ra_comp $\'file:file:_files\'' $'|' $'/-h\0/' $':_ra_comp $\'options:global options:(( -h:show\\\\ this\\\\ help\\\\ message\\\\ and\\\\ exit ))\'' $'|' $'/-d\0/' $':_ra_comp $\'options:global options:(( -d:destination\\\\ music\\\\ directory ))\'' $'/[^\0]##\0/' $':_ra_comp $\'dir:directory:_dirs\'' $')' $'#' $')' $'(' $'/help\0/' $':_ra_comp $\'subcmds:subcommands:(( help:show\\\\ help ))\'' $'(' $')'
        case "$?" in
                (0|2) _message "no more arguments" ;;
                (1) if [[ "$_ra_line[_ra_p1 + 1, -1]" = *$'\0'* ]]
                        then
                                _message "parse failed before current word"
                        else
                                _ra_left="$_ra_line[_ra_p1 + 1, _ra_p2]"
                                _ra_right="$_ra_line[_ra_p2 + 1, -1]"
                                compset -p $(( $#PREFIX - $#_ra_line + $_ra_p1 ))
                                (( $#_ra_actions )) && _alternative "$_ra_actions[@]"
                        fi ;;
                (3) _message "invalid regex" ;;
        esac
        [[ nm -ne "$compstate[nmatches]" ]]
}
```

### Setup

* OS: Raspbian Jessie (I'm running this on a Raspberry Pi)
* Python version: 2.7.9
* beets version: 1.4.3
* ZSH version: 5.0.7
* Turning off plugins made problem go away (yes/no): no

My configuration is:

```yaml
directory: /mnt/barry/music
library: ~/.config/beets/library.blb
per_disc_numbering: yes
art_filename: cover
threaded: yes
ui:
  color: yes
import:
  copy: no
  move: yes
  write: yes
  resume: ask
  quiet_fallback: skip
  timid: yes
  log: ~/.config/beets/import.log
plugins: fetchart embedart ftintitle lastgenre lyrics mbsync info fuzzy duplicates missing chroma inline badfiles edit scrub rewrite smartplaylist convert types mpdstats mpdupdate
embedart:
  remove_art_file: yes
fetchart:
  minwidth: 300
  sources: coverart itunes amazon albumart filesystem
lastgenre:
  source: track
  canonical: yes
  count: 4
  separator: ';'
  whitelist: yes
ftintitle:
  auto: yes
smartplaylist:
  relative_to: /mnt/barry/music
  playlist_dir: ~/.config/beets/playlists
duplicates:
  count: yes
missing:
  count: yes
item_fields:
  initial: albumartist[0].upper() + u'.'
  disc_and_track: u'%01i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
scrub:
  auto: no
paths:
  default: $albumartist/$album%aunique{albumartist album albumdisambig,albumtype year albumdisambig country label}%if{$albumdisambig, [%title{$albumdisambig}]}/$disc_and_track $title
  singleton: $albumartist/[non album tracks]/$title
  comp: Various Artists/$album%aunique{albumartist album albumdisambig,albumtype year albumdisambig country label}%if{$albumdisambig, [%title{$albumdisambig}]}/$disc_and_track $artist - $title
```
