### ISSUE TITLE
beet update: Do not stop when files (including album art) cannot be moved

### ISSUE THREAD

**Issue by azrdev** [beetbox/beets#2419]
### Problem

Running `beet up` fails for me with messages like
~~~
moving album art /srv/music/beets/ASP/Aus der Tiefe_ Der schwarze Schmetterling, Teil IV/cover.jpg to /srv/music/beets/ASP/Aus der Tiefe_ Der schwarze Schmetterling, Teil IV [5622]/cover.1.
jpg
Traceback (most recent call last):
  File "/srv/home/azrael/dev/beets/upstream/beets/util/__init__.py", line 470, in move
    shutil.copyfile(path, dest)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/srv/music/beets/ASP/Aus der Tiefe_ Der schwarze Schmetterling, Teil IV/cover.jpg'
~~~

### Setup

* OS: Fedora 23
* Python version: 2.7.11
* beets version: v1.4.3-71-g0a13240 (git HEAD)
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
importfeeds:
    relative_to: /srv/music
    dir: /srv/music/lib/beets_importfeeds
    formats: m3u
    absolute_path: no
    m3u_name: imported.m3u

paths:
    singleton: $albumartist/$album%aunique{}/$track $title
    comp: $albumartist/$album%aunique{}/$track $title
play:
    command: bash -c 'cat $0 | mpc add'
    relative_to: /srv/music
    use_folders: no
    raw: no
    warning_threshold: 100
mpdstats:
    host: localhost
    port: 6600
    music_directory: /srv/music/
    rating: no
chroma:
    auto: no
convert: (...)
embedart:
    auto: no
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    maxwidth: 0
library: ~/.share/beets/library.blb

plugins: acousticbrainz embedart fetchart fromfilename info missing duplicates chroma info convert importfeeds play
directory: /srv/music/beets

import:
    move: yes
    log: ~/.share/beets/import.log
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
missing:
    count: no
    total: no
acousticbrainz:
    auto: yes
    force: no

```
