### ISSUE TITLE
Beets froze during import and now library contains just 1 album

### ISSUE THREAD

**Issue by zeltak** [beetbox/beets#2423]
### Problem
ive been using beets for a few years now but last week started to have issue
so decided to start from scratch. i remimported all library with beets -A
and that worked well.today i added another album (beet import /path/to/nas/album/
and it seemed to just hang i killed the terminal after a few minutes and ever since then beet ls shows
only 1 album in the beets DB. 
the db itself still shows 35mb

Running this command in verbose (`-vv`) mode:

```
zeltak@zx1voics:~|⇒  beet -vv
user configuration: /home/zeltak/.config/beets/config.yaml
data directory: /home/zeltak/.config/beets
plugin paths: /home/zeltak/.beets/myplugins
Sending event: pluginload
rewrite: adding template field artist Carl Newman
rewrite: adding template field artist Bob Marley & The Wailers
artresizer: method is (2, (6, 9, 7))
lyrics: Disabling google source: no API key configured.
library database: /home/zeltak/.beets/musiclibrary.blb
library directory: /home/zeltak/music
Sending event: library_opened

```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: Arch linux
* Python version:  3.6
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): 
NA
My configuration (output of `beet config`) is:

```yaml
zeltak@zx1voics:~|⇒  beet config
lyrics:
    bing_lang_from: []
    fallback: ''
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    force: no
    sources:
    force: no                                                                                                                              
    sources:
    - google
    - lyricwiki
    - lyrics.com
    - musixmatch
directory: ~/music
library: ~/.beets/musiclibrary.blb

paths:
    default: '%the{$albumartist}/$year $album/$track $title'
    comp: 3Compilations/$album/$track $title
    albumtype:soundtrack: 2Soundtracks/$album/$track $title
    singleton: '%the{$albumartist}/$year $album/$track $title'
    mis:1: '%the{$albumartist}/$year $album/$track $title'

import:
    copy: yes
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
original_date: yes

clutter: .DS_Store *.*
pluginpath: /home/zeltak/.beets/myplugins/

plugins: fuzzy mbsync fetchart embedart  fromfilename scrub lyrics rewrite the duplicates info convert   badfiles missing
replaygain:
    backend: gstreamer
    overwrite: yes
convert:
    embed: no
    format: opus
    dest: /home/zeltak/ZH_tmp/$convmusic/

    paths:
        default: $albumartist/$title
    pretend: no
    threads: 4
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
rewrite:
    artist Carl Newman: A.C. Newman
    artist Bob Marley & The Wailers: Bob Marley
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
embedart:
    auto: yes
    maxwidth: 500
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
zero:
    fields: month day genre comments
    comments: ['^[^Ff]']
    genre: [rnb, power metal]
mpdupdate:
    host: localhost
    port: 6600
ignore: .AppleDouble ._* *~ .DS_Store .txt .cue
art_filename: folder
threaded: yes
ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
smartplaylist:
    playlist_dir: ~/.mpd/playlists/
    playlists: [{query: '', name: All.m3u}, {query: 'favorite:yes', name: Favorites.m3u}, {query: 'playlist::^(?!\s*$).+', name: $playlist.m3u}]

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
lastimport:
    per_page: 500
    retry_limit: 3
lastfm:
    user: zeltak
    api_key: e70efe1eea4ede457b02941c13f7f093
types:
    play_count: int
    rating: float
scrub:
    auto: yes
fuzzy:
    prefix: '~'
    threshold: 0.7
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
missing:
    count: no
    total: no


```
