### ISSUE TITLE
Problem with artpath

### ISSUE THREAD

**Issue by beedaddy** [beetbox/beets#2438]
### Problem

After some time (and some updates) I used beets (now 1.4.3) again to edit some tags. So I run `beet edit -a --all ...` and make the changes (alter albumartist, for example - **not** artpath). But saving them gives me the message:

> artpath: None -> /home/myuser/None

The actual path is the current woking directory. Why is this?
And if I try to convert the album with beet `convert -a ...`, I get these errors:

> convert: could not read image file: [Errno 2] No such file or directory: b'/home/myuser/None'

Why is this behaviour?

Thanks a lot
Martin

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv edit --all  -a Grieg Marriner
```

Led to this problem:

```
artpath: None -> /home/myuser/None
```

### Setup

* OS: Arch Linux
* Python version: 3.6.0
* beets version: 1.4.3

My configuration (output of `beet config`) is:

```yaml
plugins: inline info edit convert play duplicates embedart
directory: ~/Musikarchiv

paths:
    default: $genre/$albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
item_fields:
    multidisc: 1 if disctotal > 1 else 0
convert:
    dest: ~/Musik_transcodiert
    copy_album_art: no
    format: opus
    formats:
        opus:
            command: opusenc --bitrate 160 $source $dest
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    pretend: no
    threads: 4
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    never_convert_lossy_files: no
    album_art_maxwidth: 0
pathfields: {}
album_fields: {}
play:
    command:
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
```
