### ISSUE TITLE
Some default config options not explained in the man pages

### ISSUE THREAD

**Issue by milsen** [beetbox/beets#2449]
The following options are present in the default config (`beet config`) but not explained in the man pages nor on [http://beets.readthedocs.io/en/v1.4.3/reference/config.html](http://beets.readthedocs.io/en/v1.4.3/reference/config.html).
To a new user (like me) this is a little confusing as I can only guess what these options do.

```
ui:
    terminal_width: 80
    length_diff_thresh: 10.0
path_sep_replace: _
time_format: '%Y-%m-%d %H:%M:%S'
format_raw_length: no
timeout: 5.0
verbose: 0
import:
    delete: no
    quiet: no
    singletons: no
    flat: no
    pretend: no
    search_ids: []

statefile: state.pickle
match:
    distance_weights: _all_sub_options_
    track_length_grace: 10
    track_length_max: 30
```

#### By beets version:
```
$ beet version
beets version 1.4.3
Python version 3.6.0
no plugins loaded
```
