### ISSUE TITLE
absubmit: Do not filter on supported formats

### ISSUE THREAD

**Issue by bearcatsandor** [beetbox/beets#2471]
### Problem

When running `beet absubmit artist:"ace frehley" title:"rip it out"`  i get the error 
absubmit: Not analysing Ace Frehley - 1978 - Ace Frehley - Rip It Out - 3:39, file not in supported format.

However, i submited a bug about it to the essentia developers ( https://github.com/MTG/essentia/issues/569 ) and they claim that since essentia is based on ffmpeg that it should work just fine.

Can you tell me what is going on? I've placed a strace here: https://gist.github.com/4eb667a7eb81cdcfb16096b05240c651

Any ideas how i can fix this? The strace complains about my missing the files /home/bearcat/.config/beets/musiclibrary.blb-wal and /home/bearcat/.config/beets/musiclibrary.blb-journal but i've never seen mention of those files anywhere else.

### Setup

* OS: Linux jaguarundi 4.9.5-gentoo #1 SMP Sat Jan 21 16:29:49 MST 2017 x86_64 AMD FX(tm)-6300 Six-Core Processor AuthenticAMD GNU/Linux
* Python version: 2.7.13, 3.4.6, 3.5.6 and 3.6.0
* beets version: git
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    fallback: No lyrics found
    bing_client_secret: REDACTED
    google_API_key: REDACTED
    force: no
    google_engine_ID: REDACTED
    sources:
    - google
    - lyricwiki
    - lyrics.com
    - musixmatch
    auto: yes
    genius_api_key: REDACTED
    bing_lang_to:
duplicates:
    format: $albumartist - $album - $title
    count: yes
    album: no
    full: no
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    strict: no
    checksum: ''
    merge: no
    delete: no
play:
    command: gst-play-1.0 --gapless --volume=1.0
    use_folders: no
    raw: yes
    warning_threshold: 100
    relative_to:
library: ~/.config/beets/musiclibrary.blb

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \s+$: ''
    ' ': _
    \!: ''
original_date: yes
replaygain:
    backend: gstreamer
    auto: yes
    overwrite: yes
    targetlevel: 89

plugins: absubmit acousticbrainz badfiles bpd chroma convert copyartifacts duplicates edit embedart fetchart follow fromfilename ftintitle fuzzy hook importadded info inline lastgenre lyrics mbcollection mbsubmit mbsync mpdstats mpdupdate missing play random replaygain rewrite smartplaylist the thumbnails types web zero
follow:
    auto: yes
    email: bearcatsandor@gmail.com
    password: REDACTED
    userid: REDACTED
acousticbrainz:
    auto: yes
    force: yes

paths:
    default: '%lower{%the{$albumartist}/$original_year-$album%if{$albumdisambig,_[$albumdisambig]}/$disc-$track-$title}'
    singleton: '%lower{singletons/%the{$artist}-$title}'
    comp: '%lower{various_artists/%if{$original_year,$original_year,$year}-$album%if{$albumdisambig,_[$albumdisambig]}/$disc-$track-%the{$artist}-$title}'

format_item: $albumartist - $original_year - $album - $title - $length
art_filename: cover
zero:
    fields: comments
    comments:
    - EAC
    - LAME
    - from.+collection
    - ripped by
    update_database: yes
    auto: yes
    keep_fields: []
smartplaylist:
    relative_to: /home/hometheater/audio
    playlist_dir: ~/.config/mpd/playlists
    playlists: [{name: all.m3u, query: ''}, {name: beatles.m3u, query: 'artist:Beatles'}]
    auto: yes
missing:
    format: $albumartist - $album - $title
    count: yes
    total: yes
format_album: $albumartist - $original_year - $album - {$source}
lastgenre:
    fallback: ''
    canonical: ''
    source: track
    count: 4
    prefer_specific: no
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '

import:
    move: yes
    incremental: yes
    detail: yes
    timid: yes
    resume: ask
    log: /tmp/beets_import.log
    write: yes

sort_album: albumartist+ original_year+ album+

match:
    preferred:
        media:
        - Hybrid SACD
        - SACD
        - CD
        - Digital Media|File
mbcollection:
    auto: no
mpd:
    host: localhost
    port: 6600
    rating: no
    rating_mix: 0.75
    music_directory: /home/hometheater/audio
    password: REDACTED
fetchart:
    auto: yes
    google_key: REDACTED
    google_search: no
    cautious: no
    cover_names: cover front back art album folder
    minwidth: 500
    sources: filesystem fanarttv coverart itunes amazon albumart wikipedia google
    fanarttv_key: REDACTED
    store_source: yes
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    maxwidth: 0
embedart:
    auto: yes
    maxwidth: 1000
    compare_threshold: 0
    ifempty: no
    remove_art_file: no

musicbrainz:
    user: bearcatsandor
    pass: REDACTED
    searchlimit: 20
fuzzy:
    threshold: 0.7
    prefix: '~'
sort_item: albumartist+ original_year+ album+ disc+ track+
convert:
    auto: no
    format: wavpack
    pretend: no
    quiet: no
    formats:
        flac:
            command: gst-launch-1.0 filesrc location="$source" ! decodebin ! audioconvert ! flacenc quality=8 ! flactag ! filesink location="$dest"
            extension: flac
        wavpack:
            command: gst-launch-1.0 filesrc location="$source" ! decodebin ! audioconvert ! wavpackenc extra-processing=1 md5=true ! apev2mux ! filesink location="$dest"
            extension: wv
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
    dest: ~/tmp
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    threads: 6
    copy_album_art: no
    tmpdir:
    max_bitrate: 500

    paths: {}
threaded: yes
bpd:
    port: 6600
    volume: 100
    host: ''
    password: REDACTED
per_disc_numbering: yes
ftintitle:
    format: (feat. {0})
    auto: yes
    drop: no
absubmit:
    auto: yes
    extractor: ''
album_fields:
    album_length: "total = 0\nfor item in items:\n    total += item.length\n    return total\n"

ui:
    color: yes
directory: /home/hometheater/audio
copyartifacts:
    print_ignored: no
    extensions: .*
pathfields: {}
item_fields: {}
hook:
    hooks: []
chroma:
    auto: yes
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
thumbnails:
    auto: yes
    dolphin: no
    force: no
the:
    a: yes
    patterns: []
    the: yes
    strip: no
    format: '{0}, {1}'
mbsubmit:
    threshold: medium
    format: $track. $title - $artist ($length)
rewrite: {}
web:
    host: 127.0.0.1
    include_paths: no
    port: 8337
    cors: ''
importadded:
    preserve_write_mtimes: no
    preserve_mtimes: no
```
