### ISSUE TITLE
Beets crashing when importing MP4 files

### ISSUE THREAD

**Issue by najmead** [beetbox/beets#2498]
### Problem

Running import on MP4 files in my collection is causing beets to crash with the error

ValueError: MP4 files only supports PNG and JPEG images

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import -t
```

Led to this problem:

[log.txt](https://github.com/beetbox/beets/files/878632/log.txt)

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS:  Linux
* Python version:  2.7.13
* beets version:  1.4.3
* Turning off plugins made problem go away (yes/no):  No.  However, running ```beet clearart``` prior to importing resolves the issue.

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart convert scrub web inline embedart
directory: /export/Music/Cleaned
library: /config/musiclibrary.db
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: yes

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    
paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc, $disc-}$track $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/%if{$multidisc, $disc-}$track $title
    albumtype_soundtrack: Soundtracks/$album/%if{$multidisc, $disc-}$track $title 

item_fields:
    multidisc: 1 if disctotal > 1 else 0
        
import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

embedart:
    auto: no

fetchart:
    auto: yes
    
replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337
```
