### ISSUE TITLE
Ratings Plugin

### ISSUE THREAD

**Issue by akovia** [beetbox/beets#2530]
Not sure what the ratings philosophy is here but I'd love to see a ratings plugin that could help manage them. I've gone though a ton of music player over nearly 20 years and it seems every single one has it's own rating system. A plugin to either unify them into a single preferred tag, or writing multiple tags would be immensely helpful.

Maybe it could read all (plugin supported) existing ratings and you could choose the order of priority to set the new rating to a single tag, or equalize everything by writing a rating to all supported tags.

Highest Rated
fmps_rating
rating:banshee
POPM
fmps_rating_amarok_score
rating:quodlibet
Lowest rated
etc..

The option to write a normalized rating to all supported tags would make a library completely portable, or an option to strip all but one preferred tag.

```
ratings:
    order: highest fmps banshee amarok quodlibet popm lowest
    onetag: fmps # write this tag and clear all other rating tags.
    multitag: * # list of tags to write or * for all supported
```
Would this be useful to anyone else?
