### ISSUE TITLE
Beets not picking up Discogs to tag

### ISSUE THREAD

**Issue by macdalor** [beetbox/beets#2544]
### Problem

I've just discovered this BRILLIANT platform and I have to say I'm quite impressed! Maybe I am doing something wrong and would appreciate your advice.

I am trying to get my mainly 80's & 90's electronic music collection re-tagged by Discogs as it is the best/most complete platform for my needs. The important point for me is to get the correct original year for each track.

I have enabled the disco's plugin within beets and have also assigned its source_weight to 0.0 as advised in the following post https://github.com/beetbox/beets/issues/2391 but unless I am missing something it's not picking it up although the tracks are in discogs.

Running this command in verbose (`-vv`) & singleton mode:

```sh
$ beet -vv import -s /path/to/my/music/files
```

Led to this problem:

```
Sending event: before_choose_candidate
Correcting track tags from:
     - Boomshanka - Do You Have the Power! (That Side mix)
To:
    Dig - Reinvent Yourself
URL:
    https://musicbrainz.org/recording/14e9d518-2ecd-4fe3-9bba-fec61e6ac4fd
(Similarity: 51.0%) (title, length)
Apply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? e
Artist: boomshanka
Track: Do You Have The Power?
Item search terms: boomshanka - Do You Have The Power?
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.
Sending event: before_choose_candidate
Finding tags for track " - Boomshanka - Do You Have the Power! (That Side mix)".
Candidates:
1. Boomshanka - Do What U Wanna Do (13.1%) (title, length)
2. Boomshanka - First Thing Tomorrow (10.1%) (title, length)
3. Boomshanka - Peter North (9.5%) (title, length)
4. Boomshanka - Full Circle (4.7%) (title, length)
5. Boomshanka - BFD (4.1%) (title, length)
# selection (default 1), Skip, Use as-is, Enter search, enter Id, aBort? 1
Correcting track tags from:
     - Boomshanka - Do You Have the Power! (That Side mix)
To:
    Boomshanka - Do What U Wanna Do
URL:
    https://musicbrainz.org/recording/e510dbe0-9882-4eaa-8aca-d8f8c0847e86
(Similarity: 13.1%) (title, length)
Apply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? m
Finding tags for track " - Boomshanka - Do You Have the Power! (That Side mix)".
Candidates:
1. Boomshanka - Do What U Wanna Do (13.1%) (title, length)
2. Boomshanka - First Thing Tomorrow (10.1%) (title, length)
3. Boomshanka - Peter North (9.5%) (title, length)
4. Boomshanka - Full Circle (4.7%) (title, length)
5. Boomshanka - BFD (4.1%) (title, length)
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: osx 10.11.4
* Python version: Python 2.7.10
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): N/A

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/Music/DJ_Music/Classics
library: /Users/Producer/Documents/beets/musiclibrary.blb

import:
    move: yes
    write: yes
    log: beetslog.txt
art_filename: albumart
plugins: discogs fromfilename chroma fetchart keyfinder bucket
discogs:
    source_weight: 0.0
fetchart:
    sources: google coverart itunes amazon albumart
threaded: yes
asciify_paths: yes
original_date: yes
ui:
    color: yes
paths:
    default: %bucket{$year}/$artist - $title
    singleton: %bucket{$year}/$artist - $title
    comp: %bucket{$year}/$artist - $title
bucket:
    bucket_year:  ['1980-85', '1986-89','1990', '1991', '1992', '1993', '1994','1995-99', '2000s']
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
```
