### ISSUE TITLE
smartplaylist: Parse query terms containing whitespace

### ISSUE THREAD

**Issue by mschuerig** [beetbox/beets#256]
I would like playlists like this

``` yaml
  playlists:
    - name: 'Fred Frith.m3u'
      query: 'artist::Frith|(Skeleton Crew)|(Cosa Brava)|(Henry Cow)|(^Massacre$)'
```

Unfortunately, a plain query string like that is split at whitespace in get_query. The list command is not affected as it does not pass down a string, but an array of strings.

As a remedy, I have changed smartplaylist.py like this

``` python
def update_playlists(lib):
   ...
   for playlist in playlists:
       items = lib.items([playlist['query']]) # note the outer brackets
       ....
```
