### ISSUE TITLE
Remove Part of Title for all Tracks

### ISSUE THREAD

**Issue by mefynn** [beetbox/beets#2561]
### Problem

I want to remove a certain string from titles, how do i do that

### Setup

* OS:  macos
* Python version: 2.7
* beets version:  1.4.7
* Turning off plugins made problem go away (yes/no): n

My configuration (output of `beet config`) is:

```yaml
import:
    move: yes
    copy: no
replace:
    '\[Explicit]': ''
ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
```
