### ISSUE TITLE
Beets is haunted, reads info from comment lines?

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2565]
### Problem

A lot is going on here. May be many bugs combining? Some thoughts:

* Beets reading info to the right of a comment indicator `#` which is unintuitive
* Information in replace somehow ruining musicbrainz.host
* Maybe something to do with using git branch rather than latest stable (1.4.3)?
* Maybe something to do with latest commit?

Running this command in verbose (`-vv`) mode:

```sh
beet -vv
configuration error: musicbrainz.host not found
```

### Setup

* OS: win10 x64
* Python version: 3.6
* beets version: Latest git (https://github.com/beetbox/beets/commit/9840964f51fed3b3d0dcc1db9c76f90be4c05e73)
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

Causes issue:

```yaml
library: e:\songs\beetslibrary.bib

replace:
    'qqqqqqq': 'eeeeeeeee'
    #”
```

Works fine:

```yaml
library: e:\songs\beetslibrary.bib

replace:
    'qqqqqqq': 'eeeeeeeee'
    #
```
