### ISSUE TITLE
Aunique{} always starts with a space

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2568]
### Problem

The space after `u` [here](https://github.com/beetbox/beets/blob/c2b6623aaccd82aa695ba9583e34b879fa674b1a/beets/library.py#L1517) and a few lines [below](https://github.com/beetbox/beets/blob/c2b6623aaccd82aa695ba9583e34b879fa674b1a/beets/library.py#L1526) (with another `u`) makes the string from aunique{} always start with spaces.

Removing the space from the two `u' '` strings fixes this behavior. 

Config:

```
directory: e:\Music\
library: e:\songs\beetslibrary.bib

import:
    copy: yes
    move: no
    write: yes

paths:
    default: |
        a%aunique{albumartist,path label,}b/$track. $title
```

Example output:

![image](https://cloud.githubusercontent.com/assets/4810902/26210219/f993c1e8-3bbc-11e7-97ab-9ed84592109d.png)
