### ISSUE TITLE
How can I change 'by hand' the proposition I get from the autotagger? 

### ISSUE THREAD

**Issue by dosoe** [beetbox/beets#2570]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
[dorian@stonearch Fri May 19 beets]$ -> beet import -Lt ../beets2/Bach\,\ Johann\ Sebastian\;\ Leonhardt\,\ Gustav/Clavier-Ubung\ 1.\ Teil\,\ 6\ Partiten/ 
```

Led to this problem:

```sh
/run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets2/Bach, Johann Sebastian; Leonhardt, Gustav/Clavier-Ubung 1. Teil, 6 Partiten (40 items)
Tagging:
    Johann Sebastian Bach; Gustav Leonhardt - Clavier-Übung 1. Teil, 6 Partiten
URL:
    https://musicbrainz.org/release/76aff5dd-61ea-4a60-9067-7e802891e2be
(Similarity: 99.2%) (tracks) (2xCD, 1987, EMI Digital)
CD 1
CD 2
 * Partita no. 5 in G major: VII. Gigue (3:21) -> Partita no. 5 in G major: VII. Gigue (2:19) (length)
 * Partita no. 6 in E minor: VII. Gigue (2:19) -> Partita no. 6 in E minor: VII. Gigue (3:21) (length)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```

How can I tell him to exchange the two tracks? 
Btw, the tracktitles don't match those I get on picard. Do they both have the same tag mapping for the trackname? 

### Setup

* OS: Arch Linux
* Python version: 3.6.1
* beets version: 1.4.4
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: /run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets
library: /run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets/Musicdata.db

import:
    copy: no
    write: yes
    incremental: no
    locale: en
    language: en
    languages: en

plugins: inline web duplicates info fetchart mbsync the badfiles
badfiles:
    commands:
        ogg: ogginfo -q

paths:
    default: '%asciify{$albumartist_sort}/%asciify{$album}/$disc-$track %asciify{$title}'
    singleton: ZZZ_Non-Album/%ifdef{composer_sort,%asciify{$composer_sort},no composer}/%asciify{$artist_sort}/%asciify{$title}
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
pathfields: {}
item_fields: {}
album_fields: {}
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    reverse_proxy: no
    include_paths: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
```
