### ISSUE TITLE
FetchaArt/EmbedArt fail silently

### ISSUE THREAD

**Issue by kupietools** [beetbox/beets#2574]
### Problem
I have a folder, `~/Music/Music Downloads/Badly Tagged Bowie 2/DavidBALetterToHermoine-YUP/`, which contains MP3s and a file `00 Front Cover.jpg`. The MP3s do not have cover art embedded.

The following commands all fail to either give an error or any kind of output, or embed the art in the files:

`beet embedart path:'/Users/home/Music/Music Downloads/Badly Tagged Bowie 2/DavidBALetterToHermoine-YUP/'`

`beet embedart 'path:/Users/home/Music/Music Downloads/Badly Tagged Bowie 2/DavidBALetterToHermoine-YUP/'`

`beet embedart path:/Users/home/Music/Music\ Downloads/Badly\ Tagged\ Bowie\ 2/DavidBALetterToHermoine-YUP/`

`beet embedart -f '/Users/home/Music/Music Downloads/Badly Tagged Bowie 2/DavidBALetterToHermoine-YUP/00 Front Cover.jpg' path:'/Users/home/Music/Music Downloads/Badly Tagged Bowie 2/DavidBALetterToHermoine-YUP/'`

`beet embedart -f '/Users/home/Music/Music Downloads/Badly Tagged Bowie 2/DavidBALetterToHermoine-YUP/00 Front Cover.jpg' 'path:/Users/home/Music/Music Downloads/Badly Tagged Bowie 2/DavidBALetterToHermoine-YUP/'`

`beet embedart -f /Users/home/Music/Music\ Downloads/Badly\ Tagged\ Bowie\ 2/DavidBALetterToHermoine-YUP/00\ Front\ Cover.jpg path:/Users/home/Music/Music\ Downloads/Badly\ Tagged\ Bowie\ 2/DavidBALetterToHermoine-YUP/`

I have tried preceding these with fetchart with all permuations of the quoting and escaping, as well as with and without the trailing slash on the directory name. In no case do I get any feedback or does the cover art file get embedded.

Running this command in verbose (`-vv`) mode:

```sh
user configuration: /Users/home/.config/beets/config.yaml
data directory: /Users/home/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Users/home/Library/Preferences/Beets/data/musiclibrary.db
library directory: /Users/home/music
Sending event: library_opened
Sending event: cli_exit

```

Led to this problem:

```
no output
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: MacOS Sierra 12.0.4
* Python version: ?
* beets version: latest, just downloaded the other day
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is:

```yaml
embedart:
    ifempty: yes
    remove_art_file: no
    compare_threshold: 0
    auto: yes
    maxwidth: 0
fetchart:
    auto: yes
    art_source: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
directory: ~/music

import:
    move: no
    copy: no

plugins: embedart fetchart
library: ~/Library/Preferences/Beets/data/musiclibrary.db
```
