### ISSUE TITLE
fetchart says "found album art" but it downloads nothing

### ISSUE THREAD

**Issue by simonbcn** [beetbox/beets#2578]
### Problem

`fetchart` says "_found album art_" but it downloads nothing

```sh
$ beet -vv fetchart -f "a‐ha"
user configuration: /home/juan/.config/beets/config.yaml
data directory: /home/juan/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 9, 8))
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
library database: /home/juan/.beets/musiclibrary.blb
library directory: /home/juan/Música
Sending event: library_opened
fetchart: trying source filesystem for album a‐ha - The Singles: 1984-2004
fetchart: trying source coverart for album a‐ha - The Singles: 1984-2004
fetchart: downloading image: https://coverartarchive.org/release/73bb4da7-b5ed-34c4-b586-b96568e5f68d/front
fetchart: downloaded art to: /tmp/tmp3eqeiahi.jpg
fetchart: image size: (1200, 1200)
fetchart: image needs resizing (1200 > 300)
fetchart: using remote image /tmp/tmp3eqeiahi.jpg
artresizer: ImageMagick resizing /tmp/tmp3eqeiahi.jpg to /tmp/tmplkpq54qa.jpg
Sending event: art_set
embedart: Resizing album art to 300 pixels wide
artresizer: ImageMagick resizing /home/juan/Música/a‐ha/The Singles_ 1984-2004/cover.jpg to /tmp/tmp2hmxchkz.jpg
embedart: Embedding album art into a‐ha - The Singles: 1984-2004
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
open failed: [Errno 2] No such file or directory: b'/home/juan/M\xc3\xbasica/a-ha/The Singles_ 1984-2004/03 - Train of Thought (remix).mp3'
error reading /home/juan/Música/a-ha/The Singles_ 1984-2004/03 - Train of Thought (remix).mp3: [Errno 2] No such file or directory: b'/home/juan/M\xc3\xbasica/a-ha/The Singles_ 1984-2004/03 - Train of Thought (remix).mp3'
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
embedart: embedding /tmp/tmp2hmxchkz.jpg
Sending event: write
zero: comments:  -> None
zero: albumartist_sort:  -> None
zero: artist_sort:  -> None
Sending event: after_write
thumbnails: generating thumbnail for a‐ha - The Singles: 1984-2004
artresizer: ImageMagick resizing /home/juan/Música/a‐ha/The Singles_ 1984-2004/cover.jpg to /home/juan/.cache/thumbnails/large/1231e5c72c04d8c15b14fcd1ecacfdd5.png
artresizer: ImageMagick resizing /home/juan/Música/a‐ha/The Singles_ 1984-2004/cover.jpg to /home/juan/.cache/thumbnails/normal/1231e5c72c04d8c15b14fcd1ecacfdd5.png
thumbnails: wrote thumbnail for a‐ha - The Singles: 1984-2004
Sending event: database_change
fetchart: a‐ha - The Singles: 1984-2004: found album art
Sending event: cli_exit
```

Led to this problem:

```
$ ls Música/a-ha/The\ Singles_\ 1984-2004
04 - Hunting High and Low (remix).mp3  12 - Move to Memphis.mp3
05 - I've Been Losing You.mp3          13 - Dark Is the Night.mp3
06 - Cry Wolf.mp3                      14 - Shapes That Go Together.mp3
07 - Manhattan Skyline.mp3             15 - Summer Moved On.mp3
08 - The Living Daylights.mp3          16 - Minor Earth, Major Sky.mp3
09 - Stay on These Roads.mp3           17 - Velvet.mp3
10 - Touchy!.mp3                       18 - Forever Not Yours.mp3
11 - Crying in the Rain.mp3            19 - Lifelines.mp3
```

### Setup

* OS: Arch Linux
* Python version:  3.6.1
* beets version: beets-git 1.4.3.r351.g01480704-1 (_installed from AUR package_)

My configuration (output of `beet config`) is:

```yaml
directory: "/home/juan/M\xFAsica/"
library: /home/juan/.beets/musiclibrary.blb
threaded: no

plugins: convert fetchart info duplicates badfiles zero replaygain embedart lastgenre scrub chroma discogs fromfilename thumbnails
fetchart:
    auto: yes
    maxwidth: 300
    cover_names: cover front art album folder Frontal frontal
    google_key: REDACTED
    sources: filesystem coverart itunes amazon albumart google *
    minwidth: 0
    enforce_ratio: no
    cautious: no
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
embedart:
    auto: yes
    maxwidth: 300
    compare_threshold: 0
    ifempty: no
    remove_art_file: no

match:
    strong_rec_thresh: 0.2

import:
    art: yes
    languages: es en

paths:
    default: $albumartist/$album/$track - $title
    singleton: $artist - $title
    comp: Varios/$album/$track - $title
replaygain:
    backend: gstreamer
    overwrite: yes
    auto: yes
    targetlevel: 89
lastgenre:
    auto: yes
    canonical: yes
    count: 3
    whitelist: yes
    min_weight: 10
    fallback:
    source: album
    force: yes
    separator: ', '
    prefer_specific: no
convert:
    auto: yes
    tmpdir: /tmp
    command: ffmpeg -i $source -y -codec:a libmp3lame -vn -qscale:a 1 $dest
    extension: mp3
    quiet: yes
    never_convert_lossy_files: yes
    dest:
    pretend: no
    threads: 8
    format: mp3
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    embed: yes

    paths: {}
    copy_album_art: no
    album_art_maxwidth: 0
duplicates:
    count: yes
    full: yes
    album: no
    checksum: ''
    copy: ''
    delete: no
    format: ''
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
scrub:
    auto: yes
zero:
    fields: comments albumartist_sort artist_sort albumartist_sort
    update_database: yes
    auto: yes
    keep_fields: []
acoustid:
    apikey: REDACTED
thumbnails:
    auto: yes
    force: no
    dolphin: no
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
chroma:
    auto: yes
```
