### ISSUE TITLE
Beet convert spitting out lots of `error reading`

### ISSUE THREAD

**Issue by CommunicationAnimale** [beetbox/beets#2599]
### Problem
When running `beet convert`, beet prints twice the same error message `error reading ...` (see below) after every conversion. However every file seems to have been correctly written to its destination, so I'm not sure what the error really is, maybe the error message could be changed to something more informative? 

```sh
❯ beet convert Disclosure Intro
Disclosure - Settle - Intro
Convert? (Y/n) y
convert: Encoding /home/com/Music/Library/Disclosure/Settle/01 Intro.flac
convert: Finished encoding /home/com/Music/Library/Disclosure/Settle/01 Intro.flac
error reading /home/com/Music/Library/Disclosure/Settle/01 Intro.flac: b'/home/com/Music/Converted/Disclosure/Settle/01 Intro.mkv'
error reading /home/com/Music/Library/Disclosure/Settle/01 Intro.flac: b'/home/com/Music/Converted/Disclosure/Settle/01 Intro.mkv'

```

### Setup

* OS: Fedora 25
* Python version: Python 3.5.3
* beets version: 1.4.4
* Turning off plugins made problem go away (yes/no): N.a

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    fallback:
    bing_lang_to:
    bing_client_secret: REDACTED
    google_engine_ID: REDACTED
    auto: yes
    sources: [google, lyricwiki, musixmatch]
    force: no
    genius_api_key: REDACTED
    google_API_key: REDACTED
directory: ~/Music/Library
convert:
    dest: ~/Music/Converted
    never_convert_lossy_files: yes
    command: ffmpeg -i $source -vn -c:a libopus -vbr on -b:a 128k -threads 0 $dest
    extension: mkv
    formats:
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        aac:
            extension: m4a
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        alac:
            extension: m4a
            command: ffmpeg -i $source -y -vn -acodec alac $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest

    paths: {}
    auto: no
    format: mp3
    copy_album_art: no
    quiet: no
    max_bitrate: 500
    album_art_maxwidth: 0
    pretend: no
    threads: 4
    tmpdir:
    embed: yes

import:
    copy: yes
    move: no
library: ~/.local/share/beets/musiclibrary.db

plugins: [fetchart, lyrics, convert]
fetchart:
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    cautious: no
    maxwidth: 0
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    store_source: no
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    fanarttv_key: REDACTED
```
