### ISSUE TITLE
beets keeps writing data

### ISSUE THREAD

**Issue by yacoob** [beetbox/beets#2620]
### Problem

I've reran `beet write` after 1.4.4 update and beet decided to write some more metadata to files. That's OK, perhaps something has changed and more metadata from database can now be serialised into files. Problem is, the write doesn't seem to be succeeding, and beets wants to write it next time, again and again

```sh
$ beet -vv write noisetest
user configuration: /home/yacoob/.config/beets/config.yaml
data directory: /home/yacoob/.config/beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
inline: adding item field multidisc
library database: /home/yacoob/.beetsdb
library directory: /mnt/lcl/geofront/worek/music
Sending event: library_opened
65daysofstatic - No Man’s Sky: Music for an Infinite Universe - Departure / Shortwave / Noisetest
  original_day: 00 -> 05
  artist_sort:  -> 65daysofstatic
  original_month: 00 -> 08
  disctitle:  -> Soundscapes
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: cli_exit
```
but
```
$ beet info noisetest | ag original
     original_date: 2016-01-01
     original_year: 2016
```
If I rerun `beet write`, I get same output as above. This happens for a large number of songs in the library, so I don't think it's file-specific. File permissions seem to be OK:

```
$ ls -l "$(beet ls -p noisetest)"
-rwxrwx---+ 1 yacoob pierniks 31799157 Jul  2 00:26 /mnt/lcl/geofront/worek/music/65daysofstatic/No Man’s Sky_ Music for an Infinite Universe/02-03 Departure _ Shortwave _ Noisetest.mp3
```

### Setup

* OS: Linux
* Python version: 3.4.2
* beets version: 1.4.5
* Turning off plugins made problem go away: no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    sources: [google, lyricwiki, musixmatch]
    force: no
    bing_lang_to:
    bing_client_secret: REDACTED
    genius_api_key: REDACTED
    google_engine_ID: REDACTED
    fallback:
    google_API_key: REDACTED

paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc,$disc-}$track $title
    comp: Compilations/$album%aunique{}/%if{$multidisc,$disc-}$track $title
lastgenre:
    prefer_specific: yes
    canonical: yes
    fallback:
    auto: yes
    min_weight: 10
    force: yes
    source: album
    separator: ', '
    count: 1
    whitelist: yes
original_date: yes

match:
    strong_rec_thresh: 0.1
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes

plugins: mbsync fetchart metasync duplicates missing scrub embedart lyrics lastgenre discogs web info inline
per_disc_numbering: yes
directory: /mnt/lcl/geofront/worek/music
item_fields:
    multidisc: 1 if disctotal > 1 else 0
fetchart:
    cautious: yes
    cover_names: front covert art
    auto: yes
    minwidth: 0
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    google_key: REDACTED
    maxwidth: 0
    enforce_ratio: no
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    store_source: no

import:
    copy: yes
    write: yes
    resume: yes
    languages: en
library: ~/.beetsdb
metasync:
    source: itunes
    itunes:
        library: /home/yacoob/workarea/itunes.xml
id3v23: yes
chroma:
    auto: no
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    user_token: REDACTED
    source_weight: 0.5
    tokenfile: discogs_token.json
web:
    host: 127.0.0.1
    cors: ''
    port: 8337
    include_paths: no
    reverse_proxy: no
pathfields: {}
album_fields: {}
missing:
    count: no
    album: no
    total: no
scrub:
    auto: yes
embedart:
    auto: yes
    compare_threshold: 0
    remove_art_file: no
    ifempty: no
    maxwidth: 0
duplicates:
    copy: ''
    keys: []
    checksum: ''
    album: no
    tiebreak: {}
    full: no
    merge: no
    strict: no
    delete: no
    format: ''
    tag: ''
    path: no
    move: ''
    count: no
```
