### ISSUE TITLE
Beet import --set does not set custom fields

### ISSUE THREAD

**Issue by martinhoefling** [beetbox/beets#2625]
### Setting custom field during import does not work

Setting a custom field, via 

```sh
$ beet import --set=type=Somthing SomeAlbumDir
```
does not result in the 'type' tag to be set to Something. `beet modify` works as intended but this requires a two step import process.

The documentation for `beet import` says
```
$ beet import -h                               
Usage: beet import [options]

Options:
  -h, --help            show this help message and exit
...
  --set=FIELD=VALUE     set the given fields to the supplied values
```

### Setup

* OS: Ubuntu 17.04
* Python version: 2.7.13
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
paths:
    default: Artists/%left{$albumartist,1}/$albumartist/$album%aunique{}/$track - $artist - $title
    singleton: Artists/%left{$artist,1}/$artist/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $artist - $title
    type:Kinder: Kinder/$albumartist/$album/$track - $artist - $title
embedart:
    ifempty: yes
    remove_art_file: yes
    compare_threshold: 0
    auto: yes
    maxwidth: 0

plugins: inline web edit fetchart embedart acousticbrainz discogs
directory: ~/Musik/Library

import:
    move: yes
library: ~/Musik/Library/beetlibrary.db
discogs:
    user_token: REDACTED
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
acousticbrainz:
    auto: yes
    force: no
web:
    host: 127.0.0.1
    include_paths: no
    port: 8337
    reverse_proxy: no
    cors: ''
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
pathfields: {}
album_fields: {}
item_fields: {}
```
