### ISSUE TITLE
Calculating album replaygain with gstreamer causes error

### ISSUE THREAD

**Issue by pprkut** [beetbox/beets#2636]
### Problem

I tried calculating replaygain values for all albums in my collection and encountered a very weird problem. I tried figuring out myself what's going on, but I'm pretty much stumped. Maybe someone else can point me in a good direction...

```
beet replaygain -a "Streets of Gold"
```
yields
```
replaygain: analyzing 3OH!3 - Streets of Gold
replaygain: ReplayGain error: Error GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1) - 'gstoggdemux.c(4883): gst_ogg_demux_loop (): /GstPipeline:pipeline0/GstDecodeBin:decbin/GstOggDemux:oggdemux1:\nstreaming stopped, reason error (-5)' on file '/mnt/media/Music/Vorbis/3OH!3 - Streets of Gold/02 - 3OH!3 - I Can Do Anything.ogg'
```
Yet
```
beet replaygain "Streets of Gold"
```
works just fine:
```
replaygain: analyzing 3OH!3 - Streets of Gold - Beaumont
replaygain: analyzing 3OH!3 - Streets of Gold - I Can Do Anything
replaygain: analyzing 3OH!3 - Streets of Gold - Déjà Vu
replaygain: analyzing 3OH!3 - Streets of Gold - We Are Young
replaygain: analyzing 3OH!3 - Streets of Gold - Touchin on My
replaygain: analyzing 3OH!3 - Streets of Gold - House Party
replaygain: analyzing 3OH!3 - Streets of Gold - R.I.P.
replaygain: analyzing 3OH!3 - Streets of Gold - I Know How to Say
replaygain: analyzing 3OH!3 - Streets of Gold - Double Vision
replaygain: analyzing 3OH!3 - Streets of Gold - I'm Not the One
replaygain: analyzing 3OH!3 - Streets of Gold - Streets of Gold
replaygain: analyzing 3OH!3 - Streets of Gold - See You Go
replaygain: analyzing 3OH!3 - Streets of Gold - Love 2012
replaygain: analyzing 3OH!3 - Streets of Gold - Don't Trust Me
replaygain: analyzing 3OH!3 feat. Kesha - Streets of Gold - My First Kiss
replaygain: analyzing 3OH!3 feat. Katy Perry - Streets of Gold - Starstrukk
```

My first thought was corrupted files (I just recently copied them over from a dying ssd). However, nothing seems to indicate the files themselves are corrupt, with the prime example being track replaygain calculation working just fine. I played the file it errors out on and that too worked fine, so did a quick check with `ogginfo`. But it gets even weirder.

I noticed that the above error (or similar) happens with pretty much every album I have. However, if I calculate the album replaygain value of multiple albums at once, it will only hit a fraction, but always the first one in the list. So in my example, if "Streets of Gold" is the second album in the processing list, it succeeds.

I have absolutely no idea what could be causing this and gstreamer's debugging output isn't really helping (it's like searching for a needle in a haystack. The debugging output for the above `replaygain -a` command is above 3GB)

### Setup

* OS:  Slackware Linux
* Python version:  3.6.1
* beets version:  beets 1.4.6 (e742f8694c3057c1fea053aafdbc7455f6867995)

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    sources: [google, lyricwiki, musixmatch]
directory: /mnt/media/Music
library: ~/data/beets.blb

import:
    move: yes
    write: no
    languages: en
    timid: yes
threaded: yes
per_disc_numbering: yes

plugins: mbsync lyrics info inline missing metasync replaygain
item_fields:
    format_name: u'Vorbis' if format == u'OGG' else format[0].upper() + format[1:].lower()
    full_album: album + (u'' if albumdisambig == u'' else u' (' + albumdisambig + ')')
    disc_folder: (u'Disc ' + str(disc).zfill(2)) if disctotal > 1 else u''

paths:
    default: $format_name/$albumartist - $full_album%aunique{albumartist album albumdisambig,albumtype year country label catalognum}/%if{$disc_folder, $disc_folder/}$track - $artist - $title
    singleton: $format_name/$albumartist - $full_album%aunique{albumartist album albumdisambig,albumtype year country label catalognum}/%if{$disc_folder, $disc_folder/}$track - $artist - $title
    comp: $format_name/$full_album%aunique{albumartist album albumdisambig,albumtype year country label catalognum}/%if{$disc_folder, $disc_folder/}$track - $artist - $title
metasync:
    source: amarok
replaygain:
    backend: gstreamer
    overwrite: yes
    auto: yes
    targetlevel: 89
    r128: [Opus]
pathfields: {}
album_fields: {}
missing:
    count: no
    total: no
    album: no
```
