### ISSUE TITLE
Problems with missing plugin, reporting albums in database

### ISSUE THREAD

**Issue by gboysko** [beetbox/beets#2661]
### Problem

When I try to find missing albums, it reports albums already in my database.

```sh
$ beet ls --album tycho
Tycho - Awake
Tycho - Epoch
$ beet missing -a tycho
Tycho - Division Remix
Tycho - Descent
Tycho - Spectre Remix
Tycho - Division
Tycho - Elsewhere
Tycho - Dive
Tycho - Awake Remix
Tycho - Hours
Tycho - Montana
Tycho - Awake
Tycho - Sunrise Projector
Tycho - The Daydream / The Disconnect
Tycho - Past Is Prologue
Tycho - Spectre
Tycho - Adrift / From Home
Tycho - Black Sunrise
Tycho - EDC Sunrise 2016
Tycho - Epoch
Tycho - See Remix
Tycho - Coastal Brake
Tycho - See
Tycho - Awake Remixes
```
Note that `Tycho - Epoch` and `Tycho - Awake` are both listed in the `missing -a` output.

### Setup

* OS: Ubuntu 16.04
* Python version: 2.7
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): No. By removing all plugins (other than `missing`), I still see the incorrect `missing` output.

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/980425CD0425AF66/MP3s.new
import:
#    move: yes
    write: yes
original_date: yes
asciify_paths: yes
id3v23: yes
# plugins: edit embedart fetchart lastgenre scrub missing info replaygain gmusic
plugins: missing
paths:
    default: $albumartist/$album%aunique{}/$track $title
replaygain:
    backend: gstreamer
embedart:
    ifempty: yes
    remove_art_file: yes
gmusic:
    email: 'REDACTED'
    password: 'REDACTED'
```
