### ISSUE TITLE
DB broken after import (can't decode 'lyrics')

### ISSUE THREAD

**Issue by jckoester** [beetbox/beets#2665]
### Problem

After succesfully importing quite a lot of songs, the databse seems to be broken.
Each and every command, be it `ls`, `update`, `stats`, ... fails with an sqlite error.
Is there any way to get the database working again (excepts restoring from a backup and doing the import again)?
Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv stats
```

Led to this problem:

```
user configuration: /home/jan/.config/beets/config.yaml
data directory: /home/jan/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 9, 9))
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
lyrics: Disabling google source: no API key configured.
library database: /home/jan/Musik/kafs/Sammlung.db
library directory: /home/jan/Musik/kafs/Sammlung
Sending event: library_opened
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.5', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 
1256, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 
1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 
1297, in stats_func
    show_stats(lib, decargs(args), opts.exact)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 
1251, in show_stats
    items = lib.items(query)
  File "/usr/lib/python3.6/site-packages/beets/library.py", line 1348, 
in items
    return self._fetch(Item, query, sort or 
self.get_default_item_sort())
  File "/usr/lib/python3.6/site-packages/beets/library.py", line 1323, 
in _fetch
    model_cls, query, sort
  File "/usr/lib/python3.6/site-packages/beets/dbcore/db.py", line 874, 
in _fetch
    rows = tx.query(sql, subvals)
  File "/usr/lib/python3.6/site-packages/beets/dbcore/db.py", line 686, 
in query
    return cursor.fetchall()
sqlite3.OperationalError: Could not decode to UTF-8 column 'lyrics' with 
text 'Call me a joker, call me a fool
Right at this moment I'm totally cool
Clear as a crystal, sharp as a knife
I feel like I'm in the prime of my lif
```

### Setup

* OS: arch linux 
* Python version: 3.6.2 
* beets version:  1.4.5
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
import:
    move: yes
    write: yes
group_albums: yes

plugins: chroma fetchart lyrics lastgenre replaygain scrub duplicates 
thumbnails
fetchart:
    cautious: yes
    cover_names: front back
    sources: itunes *
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
lastgenre:
    canonical: yes
    count: 3
    whitelist: yes
    min_weight: 10
    fallback:
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
replaygain:
    backend: gstreamer
    overwrite: no
    auto: yes
    targetlevel: 89
    r128: [Opus]
chroma:
    auto: yes
scrub:
    auto: yes
thumbnails:
    auto: yes
    force: no
    dolphin: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
```
