### ISSUE TITLE
Date in path is always constant

### ISSUE THREAD

**Issue by ubmarco** [beetbox/beets#2666]
### Problem

When using $year, $month, $day in a path schema, I always get a constant date 2015.11.15. It looks like it is the first date in the list of files. When looking at the items table in the sqlite db, I see the correct values for year, month, day and after the move, I also see the paths with the constant date. So the database correctly reflects what I have on my hard disk, but the dates are computed incorrectly when changing the file names.

Running this command:

```sh
beet ls wumme -f '$year-$month-$day $album: $title'
2015-11-15 Wumme: Wumme-und-der-Geburtstagskuchen
2015-11-22 Wumme: Ist-Wumme-gescheit
2015-11-29 Wumme: Wumme-und-Dieter
2015-12-06 Wumme: Wumme-und-die-Schlittschuhe
2015-12-13 Wumme: Wumme-und-die-Weihnachtsueberraschung
...
```

Led to this problem:
I configured my paths to be like this:

```
album:Wumme: aa_Kinder/$albumartist/$album%aunique{}/$year.$month.$day $title
```

However, when I type

```
beet move
```

I get this folder structure:

```
aa_Kinder/Bayern 2/Wumme/2015.11.15 Wumme-und-der-Geburtstagskuchen.mp3
aa_Kinder/Bayern 2/Wumme/2015.11.15 Ist-Wumme-gescheit.mp3
aa_Kinder/Bayern 2/Wumme/2015.11.15 Wumme-und-Dieter.mp3
aa_Kinder/Bayern 2/Wumme/2015.11.15 Wumme-und-die-Schlittschuhe.mp3
aa_Kinder/Bayern 2/Wumme/2015.11.15 Wumme-und-die-Weihnachtsueberraschung.mp3
...
```

### Setup

* OS: Linux / Ubuntu
* Python version: 3.5.3
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /media/daten_fat32/Musik/Musik_Beets_new
library: /media/daten_fat32/musiclibrary.blb
detail: yes
import:
    move: no
    copy: yes
    write: yes
    resume: ask
    log: beetslog.txt
    plugins: discogs lyrics lastgenre fromfilename # chroma
# chroma:
#     auto: no
paths:
    albumtype:soundtrack: aa_Soundtracks/$album/$track $artist - $title
    genre:audio book: aa_Hörbücher/$albumartist/$album%anunique{}/$track $title
    genre:comedy: aa_Comedy/$albumartist/$album%aunique{}/$track $title
    album:Wumme: aa_Kinder/$albumartist/$album%aunique{}/$year.$month.$day $title
    genre:kinder: aa_Kinder/$albumartist/$album%aunique{}/%if{$track,$track,} $title
    singleton: $albumartist/0AA Non-Album/$title
    comp: aa_Compilations/$album%aunique{}/$track $title
    default: $albumartist/$album%aunique{}/$track $title
```

**Comment by sampsyo** [comment]
That’s certainly strange! Does the same thing happen, with the same dates, if you simplify down to just a single `default` path with the date in it?

**Comment by ubmarco** [comment]
I changed the paths as follows:
```
paths:
    #    albumtype:soundtrack: aa_Soundtracks/$album/$track $artist - $title
    #    genre:audio book: aa_Hörbücher/$albumartist/$album%anunique{}/$track $title
    #    genre:comedy: aa_Comedy/$albumartist/$album%aunique{}/%if{$track,$track,} $title
    default: aa_Kinder/$albumartist/$album%aunique{}/$year.$month.$day $track $title
    #    album:Wumme: aa_Kinder/$albumartist/$album%aunique{}/$track $title
    #    genre:kinder: aa_Kinder/$albumartist/$album%aunique{}/%if{$track,$track,} $title
    #    singleton: $albumartist/$title
    #    comp: aa_Compilations/$album%aunique{}/$track $title
    #    default: $albumartist/$album%aunique{}/$track $title
```

After issuing

```
marco@marcoos:~$ beet move
Moving 549 items.
```

The hard disk layout looks like this:

```
marco@marcoos:/media/daten_fat32/Musik/Musik_Beets_new$ tree
.
├── aa_Kinder
│   ├── Bayern 2
│   │   └── Wumme
│   │       ├── 2015.11.15 01 Wumme-und-der-Geburtstagskuchen.mp3
│   │       ├── 2015.11.15 02 Ist-Wumme-gescheit.mp3
│   │       ├── 2015.11.15 03 Wumme-und-Dieter.mp3
│   │       ├── 2015.11.15 04 Wumme-und-die-Schlittschuhe.mp3
│   │       ├── 2015.11.15 05 Wumme-und-die-Weihnachtsueberraschung.mp3
│   ├── Die Ärzte
│   │   ├── 13
│   │   │   ├── 1998.05.25 02 Punk ist ….mp3
│   │   │   ├── 1998.05.25 03 Ein Lied für dich.mp3
│   │   │   ├── 1998.05.25 04 Goldenes Handwerk.mp3
│   │   │   ├── 1998.05.25 05 Meine Freunde.mp3
│   │   │   ├── 1998.05.25 06 Party stinkt.mp3
│   │   │   ├── 1998.05.25 07 ½ Lovesong.mp3
```

So it looks like all other albums have the same problem. Is there anything else I can do to pinpoint the problem further?

**Comment by sampsyo** [comment]
Aha! Thanks for clarifying.

A unique thing about path formats is that album-level fields override track-level fields. Some fields, including obvious ones like $albumartist but also including the release date, are shared among the "album" structure in beets and the individual "items" that make up albums. When generating paths, beets prefers the album-level value. This way, if a single track on an album has a different $albumartist, it still gets filed away consistently. The reason the release date is album-level is because of the structure of MusicBrainz: an album corresponds to an MB "release," which has a single release date.

If you'd like to have track-level release dates that are reflected in paths, you could consider inventing new fields like $track_year to hold them. Or, you could try importing these tracks that have specific dates as "singletons," which means they're not associated with an album. That doesn't stop them from having an $albumartist and other similar fields, of course.

**Comment by ubmarco** [comment]
Hallo again,
yes, I could verify they all belonged to one album. The import of singletons via `beet import -s` made it work on track level. I'm happy with that solution. These tracks are not in the MusicBrainz DB, so I imported them 'Use as-is'.
Thanks a lot for your time and the contribution to this awesome project.

The ticket can be closed.

**Comment by sampsyo** [comment]
Great! I'm glad that's doing what you want.

**Comment by wordofglass** [comment]
Btw, you can access the item-level date fields in a path template using the `inline` plugin like so:
``` yaml
item_fields:
    item_year:
        return "{:04d}".format(year)
    item_month:
        return "{:02d}".format(month)
    item_day:
        return "{:02d}".format(day)


paths:
    album:Wumme: aa_Kinder/$albumartist/$album%aunique{}/$item_year.$item_month.$item_day $title
```
