### ISSUE TITLE
Convert Plugin: Very Large mp3 Files Created from m4a Files

### ISSUE THREAD

**Issue by Stunner** [beetbox/beets#2675]
### Problem

I import a directory containing m4a files, the convert plugin does its thing and creates mp3 files but they are each about 4-5x the size they should be.

Here's a link to the music files that trigger the bug (if relevant): 

https://www.dropbox.com/s/znu4e0fpbp9385z/source_m4a.zip?dl=0

Example bloated file:

https://www.dropbox.com/s/aebgmdvuvaidfs0/01%20Waiting%20for%20My%20Ruca.mp3?dl=0

### Setup

* OS: Mac OS X 10.11.6
* Python version: 2.7.10
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): N/A as convert is a plugin.

My configuration (output of `beet config`) is:

```yaml
missing:
    count: yes
    album: no
    total: no

format_item: $albumartist <=> $artist <=> $album <=> $track. $title ($length)
embedart:
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    maxwidth: 0
copyartifacts:
    extensions: .*
    print_ignored: yes

plugins: mbsubmit missing embedart fetchart chroma fromfilename badfiles web inline spotify mbsync edit info convert copyartifacts
library: /Volumes/Drobo Vol 1/Music/beets/musiclibrary.db

paths:
    default: $initial/$albumartist/$album%aunique{}/$disc_and_track $title
convert:
    auto: yes
    command: ffmpeg -i $source -y -vn -aq 2 $dest
    extension: mp3
    dest: /Volumes/Drobo Vol 1/Music/beets/music
    tmpdir: /Volumes/Drobo Vol 1/Music/beets/tmp_convert
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    threads: 4
    copy_album_art: no
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
item_fields:
    initial: "strippedartist = ''.join(ch for ch in artist if ch.isalnum()) or '_' \nif strippedartist[0].isdigit():\n    return '#'\nreturn strippedartist[0].upper()\n"
    disc_and_track: u'%02i.%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
fetchart:
    auto: yes
    enforce_ratio: yes
    sources: coverart itunes amazon albumart wikipedia google
    google_key: REDACTED
    minwidth: 0
    google_engine: 001442825323518660753:hrh5ch1gjzm
    cautious: no
    maxwidth: 0
    store_source: no
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
chroma:
    auto: yes
format_album: $albumartist <=> $artist <=> $album
spotify:
    mode: list
    regex: []
    artist_field: albumartist
    track_field: title
    album_field: album
    region_filter:
    show_failures: no
    tiebreak: popularity
directory: /Volumes/Drobo Vol 1/Music/beets/music

import:
    move: yes
    log: /Volumes/Drobo Vol 1/Music/beets/beets-import.log
acoustid:
    apikey: REDACTED
mbsubmit:
    format: $track. $albumartist <=> $artist <=> $album <=> $title ($length)
    threshold: medium
pathfields: {}
album_fields: {}
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
web:
    host: 127.0.0.1
    include_paths: no
    port: 8337
    reverse_proxy: no
    cors: ''
```
