### ISSUE TITLE
Cover Art won't copy to destination folder

### ISSUE THREAD

**Issue by julzKB** [beetbox/beets#2679]
### Problem

Hello, I can't get my cover art to follow the other files in the destination directory, the art is embedded fine, but I just can't get "cover.jpg" to end up in the destination folder . 
Any clues on where I should look ?

### Setup

* OS: Ubuntu 16
* Python version: 2.7.12
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
library: /media/Music/0-Lossless/music.blb
directory: /media/Music/0-Lossless
import:
    copy: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: cover
plugins: bpd embedart fetchart
pluginpath: ~/beets/myplugins
threaded: yes
ui:
    color: yes

paths:
    default: %left{%lower{$albumartist},1}/$albumartist/$albumartist - [$original_year] - $album/$albumartist - $track - $title
    singleton: Singletons/$artist - $title
    comp: $genre/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
match:
    strong_rec_thresh: 0.15
fetchart:
    cautious: true
    cover_names: front back
    sources: coverart itunes amazon albumart
    minwidth: 800
```
