### ISSUE TITLE
Always prefer a different metadata source over MusicBrainz

### ISSUE THREAD

**Issue by 0x1f415** [beetbox/beets#2686]
### Problem

I really dislike how musicbrainz normalizes capitalization across its entire database, ignoring the original stylization of the source material. I buy a lot of music from bandcamp, and would prefer to use the bandcamp plugin for metadata whenever possible. however, it seems there is not existing way to prefer an external metadata source _above_ musicbrainz, only _equal to_ musicbrainz, and even when both sources match 100% beets still prefers musicbrainz over bandcamp:

![image](https://user-images.githubusercontent.com/6064300/30252064-df1ffd18-9639-11e7-9acf-906e96a02844.png)

this could be alleviated if I could set the `source_weight` of bandcamp to a negative number, or if I could assign musicbrainz a `source_weight` of >0.0 (if this is already possible, it should be documented).

### Setup

* OS: windows 10, running beets in msys2
* Python version: 3.6.1
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): haven't tried (disabling the beets plugin would be counterproductive)

My configuration (output of `beet config`) is:

```yaml
directory: /f/music/
library: /f/music/musiclibrary.lib

plugins: info discogs bandcamp edit badfiles missing #fetchart #copyartifacts
pluginpath:
    - ~/.config/beets/
    - ~/src/beets-bandcamp/beetsplug/
    - ~/src/beets-copyartifacts/beetsplug/

bandcamp:
    source_weight: 0

musicbrainz:
    source_weight: 0.5

copyartifacts:
    print_ignored: yes
    extensions: .*

ignore:
    - '*.mp4'
    - '*.avi'
paths:
    default: %ifdef{GROUPING,%ifdef{ERA,$GROUPING/$ERA/[$year-$month-$day] $albumartist - $album/$track $title,$GROUPING/$albumartist/[$year-$month-$day] $album/$track $title},$albumartist/[$year-$month-$day] $album/$track $title}
    singleton: %ifdef{GROUPING,%ifdef{ERA,$GROUPING/$ERA/[$year-$month-$day] $albumartist - $album/$track $title,$GROUPING/$albumartist/[$year-$month-$day] $album/$track $title},$albumartist/[$year-$month-$day] $album/$track $title}
    comp: %ifdef{GROUPING,%ifdef{ERA,$GROUPING/$ERA/[$year-$month-$day] $albumartist - $album/$track $title,$GROUPING/$albumartist/[$year-$month-$day] $album/$track $title},$albumartist/[$year-$month-$day] $album/$track $title}

```
