### ISSUE TITLE
beet move does not do anything after changing asciify_paths.

### ISSUE THREAD

**Issue by nathdwek** [beetbox/beets#2697]
I just changed `asciify_paths` from no to yes, but using `beet move` afterwards does not update the file paths on disk.

```
plugins: missing duplicates fetchart embedart zero convert chroma info play discogs random fuzzy
play:
    warning_threshold: no
    raw: yes
    command: ds vlc --one-instance --playlist-enqueue --started-from-file -ZL
    relative_to:
    use_folders: no
directory: ~/music/beetsdir

import:
    copy: yes
    log: ~/.beetsimports.log
fetchart:
    enforce_ratio: no
    minwidth: 500
    cautious: no
    maxwidth: 0
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    store_source: no
    fanarttv_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    google_key: REDACTED
    auto: yes
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
convert:
    dest: /mnt/n/itunesMedia/Automatically Add to iTunes
    never_convert_lossy_files: yes
    format: ipod
    formats:
        ipod:
            command: ffmpeg -v warning -analyzeduration 100000000 -i $source -vn -c:a alac -ar 48000 -sample_fmt s16p $dest
            extension: m4a
        mp320:
            command: ffmpeg -v warning -analyzeduration 100000000 -i $source -vn -c:a libmp3lame -b:a 320k $dest
            extension: mp3
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    tmpdir:
    copy_album_art: no
    max_bitrate: 500
    quiet: no

    paths: {}
    auto: no
    embed: yes
    album_art_maxwidth: 0
    threads: 4
    pretend: no
zero:
    fields: albumartist_sort artist_sort comments genre
    update_database: yes
    auto: yes
    keep_fields: []
library: ~/.beets.db
fuzzy:
    threshold: 0.8
    prefix: '?'
missing:
    count: no
    total: no
    album: no
duplicates:
    delete: no
    move: ''
    tiebreak: {}
    format: ''
    merge: no
    tag: ''
    full: no
    keys: []
    copy: ''
    checksum: ''
    count: no
    path: no
    strict: no
    album: no
embedart:
    ifempty: no
    maxwidth: 0
    remove_art_file: no
    compare_threshold: 0
    auto: yes
chroma:
    auto: yes
discogs:
    source_weight: 0.5
    apisecret: REDACTED
    user_token: REDACTED
    tokenfile: discogs_token.json
    apikey: REDACTED
```

```
beets version 1.4.6 #master
Python version 3.5.3
plugins: chroma, convert, discogs, duplicates, embedart, fetchart, fuzzy, info, missing, play, random, zero
```
