### ISSUE TITLE
fetchart sometimes doesn't import cover from file

### ISSUE THREAD

**Issue by abba23** [beetbox/beets#2699]
### Problem

When importing with the `fetchart` plugin enabled and using `filesystem` as the primary source, sometimes the album cover file isn't moved into the library folder. After the import has finished, the album folder is empty except for the cover file.
When I copy that file into the album's folder in the library afterwards and do `beet fetchart` for it, the cover is imported successfully.

I imported about 10 albums and the problem appeared with 2 of them. All albums had the cover (`Cover.jpg`) in their folder together with their sound files.

The problem doesn't seem to be album specific. I tried removing an album from the library that previously had that problem and could reimport it with the cover file being carried over.

I didn't run beets in verbose mode at the time, but I will do next time and post the result if the problem occurs again.

### Setup

* OS:  Arch Linux
* Python version: 3.6.2
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no):  I can't really tell as I wasn't able to reproduce the problem.

### My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    force: yes
    fallback: ''
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    sources: [google, lyricwiki, musixmatch]
directory: ~/Music/Beets
library: ~/Music/Beets/library.blb

format_item: "\e[92m$artist\e[39m - \e[31m$album\e[39m - \e[93m$title\e[39m"
format_album: "\e[92m$albumartist\e[39m - \e[31m$album\e[39m"

import:
    move: yes
    copy: no
    write: yes

match:
    preferred:
        media: [Digital Media, CD]
        country: [US, GB, DE]

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    comp: Various Artists/$album%aunique{}/$track - $artist - $title

plugins: badfiles embedart fetchart fromfilename ftintitle info lastgenre lyrics mbsync missing replaygain scrub zero

fetchart:
    minwidth: 1000
    sources: filesystem coverart itunes amazon albumart
    auto: yes
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
ftintitle:
    drop: yes
    auto: yes
    format: feat. {0}
lastgenre:
    canonical: yes
    whitelist: ~/.config/beets/genres.txt
    fallback: ''
    min_weight: 10
    count: 1
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
replaygain:
    backend: gstreamer
    overwrite: no
    auto: yes
    targetlevel: 89
    r128: [Opus]
zero:
    fields: comments
    update_database: yes
    auto: yes
    keep_fields: []
missing:
    count: no
    total: no
    album: no
scrub:
    auto: yes
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
```
