### ISSUE TITLE
unreadable FLAC file: open failed: > 1 Vorbis comment block found

### ISSUE THREAD

**Issue by claudioruiz** [beetbox/beets#2701]
### Problem

I've been trying to add up a FLAC album which files are correct after checking with metaflac 

Running this command in verbose (`-vv`) mode:

```sh
c@c ~> beet -vv import seeding/album/
user configuration: /home/blah/
data directory: /home/user/.config/beets
plugin paths:
Sending event: pluginload
library database: /home/user/Music/_beets/musiclibrary.blb
library directory: /home/user/Music
Sending event: library_opened
Sending event: import_begin
open failed: > 1 Vorbis comment block found
unreadable file: /home/c/seeding/Album/01. Song.flac
open failed: > 1 Vorbis comment block found
```

### Setup

* OS: Debian
* Python version: 2.7.9
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
threaded: yes
art_filename: albumart
fetchart:
    auto: yes
    cover_names: cover front art album folder
    sources: filesystem coverart amazon albumart
    cautious: yes
    minwidth: 0
    google_engine:
    enforce_ratio: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
color: yes
library: ~/Music/_beets/musiclibrary.blb
ignore: .AppleDouble ._* *~ .DS_Store
original_date: yes

plugins: discogs inline convert fetchart missing duplicates export
directory: ~/Music

import:
    copy: yes
    write: yes
    move: no
    resume: ask
    incremental: yes
    log: ~/Music/_beets/beetslog.log

match:
    strong_rec_thresh: 0.08
per_disc_numbering: yes
pathfields: {}
album_fields: {}
item_fields: {}
convert:
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    dest:
    auto: no
    threads: 8
    copy_album_art: no
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
export:
    default_format: json
    json:
        formatting:
            ensure_ascii: no
            indent: 4
            sort_keys: yes
            separators: [',', ': ']
discogs:
    tokenfile: discogs_token.json
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
missing:
    count: no
    album: no
    total: no
```
