### ISSUE TITLE
lastgenre: `force` config option doesn’t work

### ISSUE THREAD

**Issue by geoffreynl** [beetbox/beets#2704]
### Problem

I want to write the popular genres from Last.fm in the metatags of my music.

I have the following configuration:

```
lastgenre:
    whitelist: no
    count: 5
    fallback: nogenre
    min_weight: 20
    source: track
    force: yes
```

Now I run "beets lastgenre"

Other than what I had expected that beets would now write the 5 most popular genres into each file, it just outputs with (keep) and doesn't change anything to the genre metatag...

What could be going wrong here and how can I fix this?

Thanks a lot for any help!

**Comment by sampsyo** [comment]
Hello! When you report a problem, it *really* helps us if you use the issue template. I know it looks like a lot of extra information, but actually including the verbose output from running the command and your versions can help us understand what's happening.

**Comment by kimpenhaus** [comment]
Today I stumbled across the same problem - so I am trying to fill the issue template

### Problem

Even though I added lastgenre with `force: yes` inside my config.yaml (which should than overwrite the genreas from what I understood from the docs) running lastgenre results in `keep`.

I did re-run it for a single album and it always procudes the same output - `keep`
The album (or better each track) ist currently having the genre `metalcore` - re-running I would asume changing it to the correct `Metalcore`

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv lastgenre albumartist:"Integrity" album:"The Blackest Curse"
```

Led to this problem:

```
lastgenre: genre for album Integrity - The Blackest Curse (keep): metalcore
```

### Setup

* OS: 10.13.5
* Python version: 3.6.5
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```
directory: /Volumes/music/

paths:
    default: $albumartist/$album/%if{$disc == 0 && $totaldisc == 1, 01, $disc} - $track - $title
    comp: Compilations/$album/%if{$disc == 0 && $totaldisc == 1, 01, $disc} - $track - $title

ignore: ['Ringtones', '#recycle', '.*', '*~', 'System Volume Information', 'lost+found', '.m4r']

format_item: ($format) $artist - $album - $track - $title

clutter: ['Thumbs.db', '.DS_Store', '*.m3u', '*.pls', '*.nfo', '*.sfv', '*.jpg', '*.jpeg', '*.png', '*.url', '*.URL', '*.txt', '*.ini']

import:
    copy: no
    write: yes
    move: yes

plugins: [discogs, bandcamp, fetchart, embedart, chroma, zero, scrub, duplicates, missing, edit, lastgenre]

bandcamp:
    art: true

fetchart:
    cautious: true
    minwidth: 200
    maxwidth: 200
    enforce_ratio: yes
    sources: [filesystem, bandcamp, coverart, amazon, albumart, wikipedia, google]

zero:
    fields: comments
    update_database: true

lastgenre:
    source: album
    count: 10
    force: yes
    canonical: '~/Documents/git/india.kimpenhaus.home/beets/genres-tree.yaml'
    whitelist: '~/Documents/git/india.kimpenhaus.home/beets/genres.txt'
    prefer_specific: yes
    min_weight: 20
    fallback: ''
    separator: ';'

missing:
    format: $albumartist - $album - $title
    count: no
    total: no

edit:
    itemfields: [track, title, artist, albumartist, album, genre]

```
If you need more detailed info I will gladly provide.
Thanks!
