### ISSUE TITLE
Modify on artist query returns "No matching albums found." with -a option

### ISSUE THREAD

**Issue by lbesnard** [beetbox/beets#2705]
### Problem

Hi There, I'm trying to modify the genre of some artists, such as Django Reinhardt for example.
The following commands will always fail

```sh
$ beet modify -a genre="Gypsy Jazz" artist:reinhardt 
$ # beet modify -a genre="Gypsy Jazz" "artist::Django Reinhardt"
$ # beet modify -a genre="Gypsy Jazz" artist:Django\ Reinhardt 
error: No matching albums found.
```

However the the query works fine with list
```sh
$ beet list artist:reinhardt                                                                                                                                                                                                                  
Django Reinhardt - First Clas...
```

Also, if I remove the ```-a ``` option, the first 3 queries will work, but won't perform on the album, only on the tracks. which means than the artist folders won't be moved over to my different genre folder.

The only way I have found to fix this is to do the query on ```path:``` which is pretty of course really slow.

Am I doing something wrong ?

### Setup

* OS: Linux Mint 17.3
* Python version: 2.7.12
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
acousticbrainz:
    auto: yes

badfiles:
      commands: {}
    #    commands:
    #    ogg: myoggchecker --opt1 --opt2
    #    flac: flac --test --warnings-as-errors --silent

chroma:
    auto: yes

directory: ~/music_library

fetchart:
    auto: yes
    maxwidth: 1000
    cover_names: cover front art album folder back
    sources: filesystem coverart itunes amazon albumart google

ftintitle:
    auto: yes

import:
    copy: no
    move: yes
    write: yes
    languages: en
    resume: yes
    autotag: no

item_fields:
    multidisc: 1 if disctotal > 1 else 0

lastgenre:
    auto: yes
    fallback: 'unknown'
    source: artist
    canonical: ~/genres-tree.yaml
    whitelist: ~/beets_genre
    prefer_specific: true

library: ~/musiclibrary2.blb

smartplaylist:
    playlist_dir: ~/playlists
    playlists: [{name: all.m3u, query: ''}, {name:  vivaldi.m3u, query: 'kennedy'}]

sort_item: albumartist+ album+ disc+ track+
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []

threaded: yes

paths:
    default: '%title{$genre}/%the{%title{$albumartist}}/$original_year - $album/%if{$multidisc,Disc $disc/}$track $title'
    comp: Compilations/$album/$track $title
    albumtype:soundtrack: Soundtracks/$albumartist - $original_year - $album/%if{$multidisc,Disc $disc/}$track $title
    singleton: '%the{$albumartist}/$year -  $album/$track $title'
    mis:1: '%the{$albumartist}/$year - $album/$track $title'

per_disc_numbering: true

#plugins: rewrite fetchart badfiles inline convert web lastgenre play chroma fromfilename duplicates acousticbrainz discogs mbsync cmus smartplaylist artistcountry the fuzzy random web bandcamp scrub ftintitle
plugins: inline the fuzzy lastgenre fetchart

pluginpath:
    - ~/github_repo/dotfiles/beets
    - ~/github_repo/dotfiles/beets/bandcamp/beetsplug

play:
    command: mp3blaster --list

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''

rewrite:
    artist The Jimi Hendrix Experience: Jimi Hendrix
    albumartist The Jimi Hendrix Experience: Jimi Hendrix
    artist .*Grateful Dead.*: Grateful Dead
    albumartist .*Grateful Dead.*: Grateful Dead
    artist .*Bill Monroe.*: Bill Monroe
    albumartist .*Bill Monroe.*: Bill Monroe


path_sep_replace: _

ui:
    color: yes
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

# http://akeil.net/listings/beets.config.yaml.html
# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30

```
