### ISSUE TITLE
Incorrect song matching

### ISSUE THREAD

**Issue by mgray88** [beetbox/beets#2711]
### Problem

Running `beet import` it wasn't able to identify the album name from the folder name for search. So I entered the MusicBrainz id that I wanted to match.

Led to this problem:

That worked, and matched correctly with the first two songs as can be seen; however, it incorrectly tried to match the third song with a different song

![screenshot from 2017-10-14 23-58-07](https://user-images.githubusercontent.com/411747/31581592-a3e3e966-b13d-11e7-8142-840bd307529a.png)
![screenshot from 2017-10-14 23-58-20](https://user-images.githubusercontent.com/411747/31581593-a3f5bfc4-b13d-11e7-8699-ffcd9bbd5a81.png)

### Setup

* OS: ubuntu 17.04
* Python version: 2.7.13
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): didn't try, only plugin is discogs, which didn't seem to cause the problem

My configuration (output of `beet config`) is:

```
directory: /mnt/Media/Music
import:
    move: yes
plugins: discogs
discogs:
    user_token: ***
paths:
    singleton: $albumartist/$album%aunique{}/$track $title
match:
    preferred:
        countries: ['US', 'GB|UK']
        media: ['CD', 'Digital Media|File']
```
