### ISSUE TITLE
Lastgenre plugin sometimes finding incorrect genres

### ISSUE THREAD

**Issue by ZedPea** [beetbox/beets#2719]
### Problem

Hiya,

I'm using the lastgenre plugin, and it seems to work pretty well, except for some albums where it appears to find non-related genres.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv lastgenre "deafheaven"
```

Led to this problem:

```
lastgenre: genre for album Deafheaven - Demo (album): Reggaeton, Queercore, Goregrind
lastgenre: genre for album Deafheaven - Libertine Dissolves (album): Reggaeton, Queercore, Goregrind
lastgenre: genre for album Deafheaven - New Bermuda (album): Black Metal, Post-Rock, Metal
lastgenre: genre for album Deafheaven - Roads to Judah (album): Reggaeton, Queercore, Goregrind
lastgenre: genre for album Deafheaven - Sunbather (album): Black Metal, Shoegaze, Queercore
lastgenre: genre for album Deafheaven / Bosse-de-Nage - Deafheaven / Bosse-de-Nage (None):
```

The genres reggaeton and queercore don't fit the albums at all, and don't appear to be in the tag clouds either: https://www.last.fm/music/Deafheaven/Demo

My first thought was that someone had mistakenly tagged them as that, and the other tags weren't classified as genres, but altering the min_weight setting didn't prevent them being found, and other more relevant tags appear on lastfm, and are correctly applied to the other albums, such as Black Metal.

Verbose output: https://pastebin.com/9M3LFAjP

I can upload the album(s) if needed.

### Setup

* OS: Arch Linux 4.13.9-1-Arch
* Python version: 3.6.2
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: /media/Media/Music
library: /media/Media/Music/.musiclibrary.db

paths:
    default: $albumartist/$album%aunique{}/$title

import:
    move: yes

plugins: embedart fetchart lastgenre

fetchart:
    enforce_ratio: yes
    sources: filesystem coverart amazon albumart wikipedia google fanarttv

embedart:
    ifempty: no

lastgenre:
    count: 3
```

Thanks.
