### ISSUE TITLE
Question: How to Configure Convert Plugin to Not Convert a Specific Format?

### ISSUE THREAD

**Issue by Stunner** [beetbox/beets#2732]
I currently have the configuration for the convert plugin is as follows:

```yaml
convert:
    auto: yes
    command: ffmpeg -i $source -y -vn -aq 2 $dest
    extension: mp3
    dest: /Music/beets/music
    tmpdir: /Music/beets/tmp_convert
```

Currently it converts anything that is non-`mp3` to `mp3` with the command specified in the config, which is fine. However, I want it to **ignore** any `m4a` files but convert anything else it finds to `mp3`. Is there an existing way for me to achieve this? (I have consulted [the docs](http://beets.readthedocs.io/en/v1.4.5/plugins/convert.html) and don't see any obvious way to do this.)
