### ISSUE TITLE
scrub corrupts FLACs

### ISSUE THREAD

**Issue by translit** [beetbox/beets#2743]
### Problem

FLACs get corrupted after ```scrub```ing:

```
$ beet bad chanson
/music/Artist/Album/01 Chanson.flac: checker exited with status 1
  01 Chanson.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
  01 Chanson.flac: ERROR while decoding data
                                                     state = FLAC__STREAM_DECODER_ABORTED
```

### Setup

* OS: macOS High Sierra v. 10.13.1
* Python version: 3.6.3
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no):  yes

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    google_API_key: REDACTED
    fallback: ''
    bing_client_secret: REDACTED
    bing_lang_to:
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    force: no
    sources: [google, lyricwiki, musixmatch]
directory: /music
library: ~/.config/beets/library.db

plugins:
- badfiles
- chroma
- convert
- duplicates
- embedart
- fetchart
- info
- lastgenre
- lyrics
- mbsync
- missing
- random
- replaygain
- scrub
- zero

import:
    move: no
    write: yes
    timid: yes
    verbose: yes
acoustid:
    apikey: REDACTED
badfiles:
    commands:
        flac: flac --test --warnings-as-errors --silent
convert:
    dest: ~/Music/Converted
    copy_album_art: yes
    never_convert_lossy_files: yes
    pretend: no
    threads: 4
    format: mp3
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    album_art_maxwidth: 0
duplicates:
    keys: artist title
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
embedart:
    auto: no
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
fetchart:
    auto: no
    cautious: no
    cover_names: cover front art album folder
    minwidth: 600
    maxwidth: 1000
    enforce_ratio: 20%
    sources: filesystem fanarttv coverart
    google_key: REDACTED
    fanarttv_key: REDACTED
    google_engine: REDACTED
    store_source: no
lastgenre:
    auto: yes
    canonical: yes
    count: 1
    force: yes
    source: album
    whitelist: yes
    min_weight: 10
    fallback:
    separator: ', '
    prefer_specific: no
replaygain:
    auto: yes
    backend: gstreamer
    overwrite: yes
    targetlevel: 89
    r128: [Opus]
scrub:
    auto: no
zero:
    auto: yes
    fields: comments
    update_database: yes
    keep_fields: []
chroma:
    auto: yes
missing:
    count: no
    total: no
    album: no
```

**Comment by sampsyo** [comment]
Hmm; I can't reproduce this with a FLAC file I have on hand:

```
$ beet scrub 'the artist'
scrub: scrubbing: /Users/asampson/code/beets/_etc/testlib/Non-Album/the artist/full.flac
$ beet bad -v 'the artist'
/Users/asampson/code/beets/_etc/testlib/Non-Album/the artist/full.flac: ok
$
```

Do you have a test case that would let us reproduce the problem?

**Comment by translit** [comment]
I wonder how best let you grab the files. Do you have Usenet? Here's the NZB.
[album.txt](https://github.com/beetbox/beets/files/1489433/album.txt)

**Comment by sampsyo** [comment]
No, sorry—any chance you can craft a small, truncated file that exhibits the problem?

**Comment by mineo** [comment]
This is a bit of a wild guess, but is there any chance that gstreamer touched the corrupted files? We have people with the same error messages from flac --test over at Picard: https://tickets.metabrainz.org/browse/PICARD-1088.

**Comment by translit** [comment]
Absolutely! I also have this in my config:

```
replaygain:
    auto: yes
    backend: gstreamer
    overwrite: yes
```

Really annoying to worry constantly about corruption. It doesn't happen to all FLACs though, only to some. I keep backups now.
