### ISSUE TITLE
ReplayGain : calculate album-gain from album tag, not directory

### ISSUE THREAD

**Issue by breversa** [beetbox/beets#2749]
### Problem

From what I understand, the ReplayGain plugin considers that all files in the same directory belong to the same album.
While this is fine (to me) for most of my collection, I do *not* keep compilation tracks in the same directory (i.e. ALL my files are in an "Artist/Album/Track" hierarchy, even for compilations).

It would be great to have an option to calculate album-gain from all the files' album tag, so that they don't need to be in the same folder.
SoundKonverter does it already : https://github.com/dfaust/soundkonverter

### Setup

* OS: Linux Mint 18.2
* beets version 1.4.5
* Python version 2.7.12
* plugins: chroma, duplicates, fetchart, replaygain, scrub

My configuration (output of `beet config`) is:

```yaml
replaygain:
    backend: bs1770gain
    command: /usr/bin/bs1770gain
    method: ebu
    auto: yes
    overwrite: no
    targetlevel: 89
    r128: [Opus]
    chunk_at: 5000
scrub:
    auto: no

plugins: replaygain chroma duplicates fetchart scrub
directory: ~/Musique

ui:
    color: yes

import:
    copy: no
library: ~/.config/beets/musiclibrary.db
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
chroma:
    auto: yes
```
