### ISSUE TITLE
replaygain: Sets R128 fields to zero when R128 values are not calculated

### ISSUE THREAD

**Issue by breversa** [beetbox/beets#2757]
### Problem
The Replaygain plugins calculate either replaygain_* OR r128 tags, but when using "beet write", both series of tags are written, one being equal to zero.

My music player (Vanilla Music, on Android) applies r128_* gain if the tags are present, before trying the replaygain_* ones.

Is there any way NOT to write the r128 tags with the "beet write" command ? And to delete the existing r128 tags in my now messed-up library (I'm not blaming anyone ; just looking for a solution :) ) ?

### Setup

* OS: Linux
* Python version: 2.7.12
* beets version: 1.4.5

My configuration (output of `beet config`) is:

```yaml
$ beet config

paths:
    default: $artist/$album%aunique{}/$artist - $title
    singleton: $artist/$album%aunique{}/$artist - $title
    comp: $artist/$album%aunique{}/$artist - $title
threaded: yes
scrub:
    auto: no
chroma:
    auto: yes
library: ~/.config/beets/musiclibrary.db
replaygain:
    backend: bs1770gain
    method: ebu
    auto: yes
    overwrite: yes
    targetlevel: 89
    r128: [Opus]
    chunk_at: 5000

ui:
    color: yes

plugins: replaygain chroma duplicates fetchart web info
directory: ~/Musique

import:
    copy: no
    autotag: no
    resume: ask
    group_albums: yes
    bell: yes
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
web:
    host: 127.0.0.1
    include_paths: no
    port: 8337
    reverse_proxy: no
    cors: ''
```
