### ISSUE TITLE
Missing plugin misses tracks without -c option

### ISSUE THREAD

**Issue by rjdang** [beetbox/beets#2765]
When I run `beet missing -c` the results for the albums I am concerned with are correct. However, when I try to list all of the tracks by just running `beet missing`, the number of songs listed per track don't add up to the counts produced from the command with the -c option. For example:

\>\>`beet missing -c | grep 'Soilent'`
Soilent Green - Inevitable Collapse In The Presence Of Conviction: 10
Soilent Green - Sewn Mouth Secrets: 2
Soilent Green - Sewn Mouth Secrets & A String Of Lies: 15

But then running
\>\>`beet missing | grep 'Soilent'`
Soilent Green - Sewn Mouth Secrets - Emptiness Found
Soilent Green - Sewn Mouth Secrets - Sticks and Stones

Only the 2 missing songs from the 2nd album listed are found, even though 10 and 15 missing tracks are counted from the other 2 albums. Should these tracks be listed too, or is this because musicbrainz can only find the track count and not track titles for some albums?

My setup:
OS: Ubuntu 17.10
\>\> beet --version
beets version 1.4.5
Python version 2.7.14
plugins: acousticbrainz, bpm, chroma, discogs, duplicates, edit, embedart, fetchart, fuzzy, gmusic, hook, ihate, importadded, lastgenre, lastimport, lyrics, mbsync, metasync, missing, mpdstats, random, scrub

My configuration is:

```yaml
directory: ~/music/library
library: ~/.config/beets/.musiclibrary.db
import:
    move: yes
paths:
    default: $albumartist - $album ($year)%aunique{}/$track $title

plugins: discogs fetchart lyrics lastgenre acousticbrainz bpm edit embedart importadded lastimport mbsync metasync mpdstats scrub duplicates gmusic missing ihate fuzzy hook random chroma

lastfm:
    user: myusername
lastgenre:
    count: 1
acousticbrainz:
    auto: yes
chroma:
    auto: yes
mpd:
    host: 127.0.0.1
    port: 6600
    rating: yes
    rating_mix: 0.75
duplicates:
    album: no
```
