### ISSUE TITLE
Windows Powershell not displaying colors

### ISSUE THREAD

**Issue by Oyashirox** [beetbox/beets#2766]
### Problem
I just upgraded beets from I believe was 1.2.+ to 1.4.6, and now powershell does not display colors and gives some unreadable garbage output. It was working fine before upgrading.

Running this command in verbose (`-vv`) mode:

```sh
$ beet import 'Kno - Death Is Silent'
```

Led to this problem:

```
URL:
    https://musicbrainz.org/release/65ee731c-5c3c-47e9-a324-dcf9ac6aeac7
(Similarity: [33;01m76.9%[39;49;00m) [33;01m(tracks, unmatched tracks)[39;49;00m [37m(CD, 2010, US)[39;49;00m
 * If You Cry[31;01m f. Natti[39;49;00m ->
   If You Cry [33;01m(title)[39;49;00m
 * Loneliness[31;01m f. Nemo Achida & Deacon The Villain[39;49;00m ->
   Loneliness [33;01m(title)[39;49;00m
 * La [37mP[39;49;00metite [37mM[39;49;00mort (Come Die With Me) ->
   La [37mp[39;49;00metite [37mm[39;49;00mort (Come Die With Me)
 * Rhythm [37mO[39;49;00mf [37mT[39;49;00mhe Rain[31;01m (Thomax Remix)[39;49;00m[31;01m (#14)[39;49;00m ->
   Rhythm [37mo[39;49;00mf [37mt[39;49;00mhe Rain[31;01m (#5)[39;49;00m [33;01m(index, title)[39;49;00m
 * Spread Your Wings[31;01m f. Deacon The Villain[39;49;00m ->
   Spread Your Wings [33;01m(title)[39;49;00m
 * Graveyard[31;01m f. Sheisty Khrist[39;49;00m ->
   Graveyard [33;01m(title)[39;49;00m
 * I Wish I Was Dead[31;01m f. Tonedeff[39;49;00m ->
   I Wish I Was Dead [33;01m(title)[39;49;00m
 * They Told Me[31;01m f. Deacon The Villain[39;49;00m ->
   They Told Me [33;01m(title)[39;49;00m
 * When I Was Young[31;01m f. Natti & Substantial[39;49;00m ->
   When I Was Young [33;01m(title)[39;49;00m
 * Not [37mA[39;49;00mt [37mT[39;49;00mhe End[31;01m f. Tunji[39;49;00m ->
   Not [37ma[39;49;00mt [37mt[39;49;00mhe End [33;01m(title)[39;49;00m
Unmatched tracks (1):
[33;01m ! Rhythm Of The Rain f. Thee Tom Hardy & Tunji (#5) (4:33)[39;49;00m
[36;01m[A][39;49;00mpply, [34;01mM[39;49;00more candidates, [34;01mS[39;49;00mkip, [34;01mU[39;49;00mse as-is, as [34;01mT[39;49;00mracks, [34;01mG[39;49;00mroup albums,
[34;01mE[39;49;00mnter search, enter [34;01mI[39;49;00md, a[34;01mB[39;49;00mort?
```

### Setup

* OS: Windows 10 Pro
* Python version: 3.6.4
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): Didn't try

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    google_API_key: REDACTED
    sources: google lyricwiki lyrics.com musixmatch
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
directory: N:\Musique\beet
library: N:\Musique\beets-database.db

import:
    move: yes
    write: yes

plugins: inline lyrics

paths:
    singleton: $artist/$title
    albumtype:soundtrack: Soundtracks/$album/$track $title
pathfields: {}
item_fields: {}
album_fields: {}
```
