### ISSUE TITLE
Rewrite plugin modifies tags

### ISSUE THREAD

**Issue by fdaniele85** [beetbox/beets#2786]
Hi guys. In the documentation of rewrite plugin it is written that "Note that this plugin only applies to templating; it does not modify files' metadata tags or the values tracked by beets' library database.", but it seems that it modifies the tags.

Without rewrite plugin I import an album by "Buckethead & Friends" and I obtain
```
beet ls enter the chicken --format '$albumartist - $title'
Buckethead & Friends - Intro
Buckethead & Friends - Nottingham Lace
Buckethead & Friends - Coma
Buckethead & Friends - Waiting Hare
Buckethead & Friends - The Hand
Buckethead & Friends - Funbus
Buckethead & Friends - Botnus
Buckethead & Friends - Running From the Light
Buckethead & Friends - We Are One
Buckethead & Friends - Three Fingers
Buckethead & Friends - Interlude
```

But enabling the rewrite plugin with this config file:
```
import:
    move: yes

directory: /media/Esterno/Organizzati

plugins: inline convert	rewrite

rewrite:
    albumartist .*buckethead.*: Buckethead

paths:
    default: $albumartist/$original_year - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    singleton: $albumartist/$original_year - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    comp: $albumartist/$original_year - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0

convert:
    formats:
        mp3: ffmpeg -i $source -y -vn -aq 0 $dest
```

I obtain
```
beet ls enter the chicken --format '$albumartist - $title'
Buckethead - Intro
Buckethead - Nottingham Lace
Buckethead - Coma
Buckethead - Waiting Hare
Buckethead - The Hand
Buckethead - Funbus
Buckethead - Botnus
Buckethead - Running From the Light
Buckethead - We Are One
Buckethead - Three Fingers
Buckethead - Interlude
```

And inspecting the tags with easytag, the albumartist is simply Buckethead. I would like to maintain the correct tags, but change the saving path.

Thanks.
