### ISSUE TITLE
'beet import -A' fails with "error: no path specified"

### ISSUE THREAD

**Issue by ferderm** [beetbox/beets#2787]
The command `beet import -A` fails with `error: no path specified`. I want to use beets to add covers to my mp3 only, so the configuration is very small - maybe too small?

Running this command in verbose (`-vv`) mode:

```beet -vv import -A
user configuration: /home/marc/.config/beets/config.yaml
data directory: /home/marc/.config/beets
Sending event: pluginload
no config file found at /home/marc/.beetsconfig
library database: /home/marc/.config/beets/library.db
library directory: /home/marc/Musik
Sending event: library_opened
error: no path specified

```

### Setup

* OS: Xubuntu 16.04
* Python version: 2.7
* beets version: 1.3.8 (plugins: fetchart, embedart)
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
embedart:
    auto: no
    maxwidth: 0
fetchart:
    auto: no
    cautious: no
    maxwidth: 0
    remote_priority: no
    google_search: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
directory: ~/Musik

import:
    copy: no
    write: no

plugins: fetchart embedart
library: ~/.config/beets/library.db
```
