### ISSUE TITLE
lastgenre: applying genre-aliases for a more specific handling of genres in your own library

### ISSUE THREAD

**Issue by kimpenhaus** [beetbox/beets#2792]
### Problem

This is more a feature request than a problem. Maybe it is also special to how I want to setup my music library. As far as I understood the lastgenre plugin reads the tags of lastfm. So one can only write genres that are tags inside lastfm.

Some of the albums are tagged with genres I don't like because they are abbreviations or do not match the conventions I made to my library.
An example:

Artist: `Madball`
Album: `Demonstrating My Style`

This album is tagged with following:
` hardcore, hardcore punk, nyhc, 1996, best albums ever, hardcore-punk`

But my genre-tree and genre-whitelist do not contain `nyhc` and I don't want the genre to be `nyhc` but I want to have it `new york hardcore` (which is obviously inside my genre-tree and whitelist).

So I thought about having a list of aliases that I can define to certain tags/genres and once they are found they will be replaced by the value defined.

For example:
`new york hardcore: [nyhc]`

The idea is to have more than one alias for a genre - that's why I made a list of it.
In my example `nyhc` will be replaced by `new york hardcore` - I bet you already thought that!

### Setup

* OS: OSX 10.13.2
* Python version: 2.7.14
* beets version: 1.4.6

My configuration (output of `beet config`) is:

```yaml
paths:
    default: $albumartist/$album/%if{$disc == 0 && $totaldisc == 1, 01, $disc} - $track - $title
    comp: Compilations/$album/%if{$disc == 0 && $totaldisc == 1, 01, $disc} - $track - $title

format_item: ($format) $artist - $album - $track - $title
fetchart:
    cautious: yes
    minwidth: 200
    maxwidth: 200
    enforce_ratio: yes
    sources:
    - filesystem
    - bandcamp
    - coverart
    - amazon
    - albumart
    - wikipedia
    - google
    auto: yes
    google_engine: 001442825323518660753:hrh5ch1gjzm
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
edit:
    itemfields:
    - track
    - title
    - artist
    - albumartist
    - album
    - genre
    albumfields: album albumartist
    ignore_fields: id path
missing:
    format: $albumartist - $album - $title
    count: no
    total: no
    album: no
bandcamp:
    art: yes
    min_candidates: 5
    lyrics: no
    source_weight: 0.5
ignore:
- Ringtones
- '#recycle'
- .*
- '*~'
- System Volume Information
- lost+found
- .m4r
zero:
    fields: comments
    update_database: yes
    auto: yes
    keep_fields: []

clutter:
- Thumbs.db
- .DS_Store
- '*.m3u'
- '*.pls'
- '*.nfo'
- '*.sfv'
- '*.jpg'
- '*.jpeg'
- '*.png'
- '*.url'
- '*.URL'
- '*.txt'
- '*.ini'

plugins:
- discogs
- bandcamp
- fetchart
- embedart
- chroma
- zero
- scrub
- duplicates
- missing
- edit
- lastgenre
directory: /Volumes/music/

import:
    copy: no
    write: yes
    move: yes
lastgenre:
    source: album
    count: 3
    force: yes
    canonical: ~/Documents/git/devil.station/beets/genres-tree.yaml
    whitelist: ~/Documents/git/devil.station/beets/genres.txt
    prefer_specific: yes
    min_weight: 20
    fallback: ''
    aliases: ~/Documents/git/devil.station/beets/genre-aliases.yaml
    separator: ;
    auto: yes
discogs:
    tokenfile: discogs_token.json
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
chroma:
    auto: yes
scrub:
    auto: yes
```
As you can see in my config I already implemented this feature into my local installation. I would be happy to share (via pr) and have it embedded into the main version and for sure discuss the solution first - as I told you I am not an python expert ;-)

m.
