### ISSUE TITLE
Memory leak using embedart plugin

### ISSUE THREAD

**Issue by Delgan** [beetbox/beets#2795]
Hi.

Foreword: congratulations and thank you for beets, you made a really great tool. 👍 

### Problem

I am facing a memory leak while using the `embedart` plugin.
I have to use this command by batches, otherwise my computer will quickly stop responding.

Running this command:

```sh
$ beet embedart
```

Led to this problem:

![ezgif-1-adf7709c9e](https://user-images.githubusercontent.com/4193924/35173463-c9a66a78-fd6b-11e7-9807-ffbaaf55eb57.gif)
(deliberately accelerated)

You can see the memory usage slowly increasing until I cancel the command and it starts returning to normal.

### Setup

* OS: Windows 10 but using the Linux bash shell
* Python version: 3.6.3
* beets version: 1.4.6

My configuration is:

```yaml
directory: '/mnt/c/Users/delgan/### Playlist ###'

import:
    move: no
    copy: no
    write: no

paths:
    default: $albumartist - $album%aunique{} - $original_year/$track. $title
    comp: $albumartist - $album%aunique{} - $original_year/$track. $title

plugins: fetchart embedart edit
fetchart:
    maxwidth: 240
    auto: yes
    minwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
```

Is there anything that I can do to help you locate the problem? As it stands I do not know if you can do much.
My library is just mp3 files in folders, next to which is a single 260x260 image "cover.jpg".
