### ISSUE TITLE
ftintitle: `drop: yes` seems to be ignored

### ISSUE THREAD

**Issue by Antagonym** [beetbox/beets#2817]
### Problem
As indicated by the title, the `drop: yes` option in the config seems to have no effect:

```sh
$ beet -vv ftintitle what have you done
user configuration: /home/johndoe/.config/beets/config.yaml
data directory: /home/johndoe/.config/beets
plugin paths: /home/johndoe/.config/beets/plugins
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
artresizer: method is (2, (7, 0, 7))
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
inline: adding item field disctrack
library database: /home/johndoe/.config/beets/library.db
library directory: /home/johndoe/music
Sending event: library_opened
ftintitle: /home/johndoe/music/Within.Temptation/The.Heart.of.Everything.2007/02-What.Have.You.Done.mp3
ftintitle: artist: Within Temptation feat. Mina Caputo -> Within Temptation
ftintitle: title: What Have You Done -> What Have You Done feat. Mina Caputo
Sending event: database_change
Sending event: write
Sending event: after_write
ftintitle: /home/johndoe/music/Within.Temptation/The.Heart.of.Everything.2007/12-What.Have.You.Done.Rock.mix.mp3
ftintitle: artist: Within Temptation feat. Mina Caputo -> Within Temptation
ftintitle: title: What Have You Done (Rock mix) -> What Have You Done (Rock mix) feat. Mina Caputo
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: cli_exit
mpdupdate: Updating MPD database...
mpdupdate: Database updated.
```

Since keeping the featured artist in the artist field messes up sorting/grouping by artist and storing it in the title messes up filenames, dropping the information would be the next best solution after storing it in a dedicated metadata field (Is there even a field for that?).

### Setup

```
$ beet version
beets version 1.4.6
Python version 3.6.4
plugins: chroma, convert, edit, embedart, fetchart, fromfilename, ftintitle, info, inline, lyrics, mbcollection, mbsync, missing, mpdupdate, random, scrub, thumbnails

$ uname -a
Linux archimedes 4.15.4-1-ARCH #1 SMP PREEMPT Sat Feb 17 16:01:38 UTC 2018 x86_64 GNU/Linux
```

The config:

```yaml
library: ~/.config/beets/library.db
directory: ~/music
pluginpath: [~/.config/beets/plugins]

plugins:
- ftintitle
- chroma
- fromfilename
- edit
- embedart
- fetchart
- lyrics
- mbsync
- mpdupdate
- scrub
- inline
- thumbnails
- convert
- info
- mbcollection
- missing
- random

ftintitle:
    drop: yes
    auto: yes
    format: feat. {0}
```

(Note: My config is rather long, so I cut out information that didn't seem relevant to me. If you really want my enitre config, I can still provide it though.)
