### ISSUE TITLE
Deprecation warning in plugins.py

### ISSUE THREAD

**Issue by akyag** [beetbox/beets#2826]
### Problem

Installed beets from fedora repo and getting the following error every time I run any command

Running this command in verbose (`-vv`) mode:

```sh
[akya@quady scripts] $ beet -vv
user configuration: /home/akya/.config/beets/config.yaml
data directory: /home/akya/.config/beets
plugin paths: /home/akya/.config/beets/beetsplug
/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL
Sending event: pluginload
/usr/lib/python3.6/site-packages/beets/plugins.py:114: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  argspec = inspect.getargspec(func)
lyrics: Disabling google source: no API key configured.
library database: /home/akya/data/musiclibrary.db
library directory: /media/Media/Songs/English
Sending event: library_opened
Usage: 
  beet COMMAND [ARGS...]
  beet help COMMAND

Options:
  --format-item=FORMAT_ITEM
                        print with custom format
  --format-album=FORMAT_ALBUM
                        print with custom format
  -l LIBRARY, --library=LIBRARY
                        library database file to use
  -d DIRECTORY, --directory=DIRECTORY
                        destination music directory
  -v, --verbose         log more details (use twice for even more)
  -c CONFIG, --config=CONFIG
                        path to configuration file
  -h, --help            show this help message and exit

Commands:
  bad               check for corrupt or missing files
  clearart          remove images from file metadata
  config            show or edit the user configuration
  convert           convert to external location
  duplicates (dup)  List duplicate tracks or albums.
  embedart          embed image files into file metadata
  extractart        extract an image from file metadata
  fetchart          download album art
  fields            show fields available for queries and format strings
  help (?)          give detailed help on a specific sub-command
  import (imp, im)  import new music
  info              show file metadata
  lastgenre         fetch genres
  list (ls)         query the library
  lyrics            fetch song lyrics
  missing (miss)    List missing tracks.
  modify (mod)      change metadata fields
  move (mv)         move or copy items
  play              send music to a player as a playlist
  remove (rm)       remove matching items from the library
  splupdate         update the smart playlists. Playlist names may be passed
                    as arguments.
  stats             show statistics about the library or a query
  update (upd, up)  update the library
  version           output version information
  web               start a Web interface
  write             write tag information to files
Sending event: cli_exit

```

Led to this problem:

```
[akya@quady scripts] $ beet --version
/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL
/usr/lib/python3.6/site-packages/beets/plugins.py:114: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  argspec = inspect.getargspec(func)
beets version 1.4.6
Python version 3.6.4
plugins: badfiles, beatport, convert, duplicates, embedart, fetchart, info, lastgenre, lyrics, missing, mpdupdate, play, smartplaylist, web

```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: Fedora 27
* Python version: 3.6.4 
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): yes, problem is in plugins.py

My configuration (output of `beet config`) is:

```yaml
directory: /media/Media/Songs/English
#directory: /media/Media/Songs/Hindi
library: ~/data/musiclibrary.db
#library: ~/data/musiclibrary2.db
import:
    copy: no
    write: yes
    log: /home/akya/.config/beets/import.log

pluginpath: 
    - /home/akya/.config/beets/beetsplug/

plugins: fetchart embedart lastgenre lyrics web missing beatport duplicates convert info play smartplaylist mpdupdate badfiles

play:
    command: mpv $args --playlist

mpd:
    host: 192.168.1.100
    port: 6600

fetchart:
    cautious: true
    cover_names: front back
    minwidth: 300
    sources: itunes *

smartplaylist:
    relative_to: 
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: fav.m3u
          query: 'comments:Fav'
        - name: new.m3u
          query: 'comments:New'
        - name: epic.m3u
          query: 'comments:Epic'
        - name: lush.m3u
          query: 'comments:Lush'
        - name: naruto.m3u
          query: 'comments:Naruto'
        - name: latest.m3u
          query: 'added:2017-11-27'
convert:
    format: mp3
    dest: /home/akya/1Dump/sync
    max_bitrate: 320
    never_convert_lossy_files: yes


paths:
    default: $albumartist/$album%aunique{}/$track $title
#    default: $album%aunique{}/$track $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track $title

```
