### ISSUE TITLE
Move not behaving as expected

### ISSUE THREAD

**Issue by Laharah** [beetbox/beets#2828]
### Problem

The move command does not consolidate or relocate files based on updated tags. While trying to consolidate folders/artists by renaming albumartist and then executing a move on the changed files causes 0 file moves

Running this command in verbose (`-vv`) mode:

assuming `beet ls nugget -f '$albumartist - $artist - $title - $path'` == 
```
Cake - Cake - Fashion Nugget - The Distance - /pool/Media/Music/Cake/Fashion Nugget/02 The Distance.mp3
```

```sh
$ beet -vv modify nugget albumartist=CAKE artist=CAKE albumartist_sort=CAKE; beet -vv move nugget
```

Led to this problem:

```
Moving 0 items.
```

### Setup

* OS: Linux Debian (Jessie)
* Python version: 3.6.3
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
library: /pool/Media/Music/beets_library.db

plugins: chroma fromfilename lastgenre discogs fetchart edit duplicates badfiles info
chroma:
    auto: yes
directory: /pool/Media/Music

import:
    write: yes
    copy: yes
    incremental: yes
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5

match:
    max_rec:
        missing_tracks: none
    preferred:
        countries: [US, GB|UK]
        media: [Digital Media|File, CD]
        original_year: yes
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
```
### Things I have tried:

* forcing move to a new location: the folder names continue to be in lowercase and unchanged, I have also tried changing to a completely different `albumartist` eg: `tst`, with no change.

* deleting state.pickle

* restarting

* moving with -a option

* moving with -d option
