### ISSUE TITLE
Embedding ALAC with already existing cover art

### ISSUE THREAD

**Issue by Satris404** [beetbox/beets#2830]
### Problem

My source library contains FLAC files in their album folder, each matched with folder.jpg as covert art. (artist/album/song.flac and artist/album/folder.jpg)
My ultimate goal here is to convert automatically into ALAC my files when importing into Beets, while keeping my covert art (without auto-tagging or fetching cover art online). FFMPEG is not able to keep the cover art when converting from FLAC to ALAC, so I had to configure plugins in order achieve this. I tried many things but at the end, I can't get my ALAC files to be embedded with their cover art. 

First of all, convert plugin works as it can automatically convert from FLAC to ALAC, but the configuration "copy_album_art" doesn't seem to work (my folder.jpg is not copied into conversion destination). With that and "embed" option enabled, the result is the same: no cover is embedded. 

So, I tried "copyartifacts" to copy the folder.jpg into the beets library, and "embedart" to embed automatically the cover. To try this, I imported directly an ALAC file with no cover art without converting it (to be sure convert plugin is not messing with the embedding). This setup is not working either. The folder.jpg is successfully copied into the beets library but the embedding part is not done. I then tried to embed the art with commands. When not specifying the image path, it says the album art is not present (but it's there, in the album folder). It finally worked with the command specifying the image path. But, it's not the best way to do it. 

I know beets' default cover art name is "cover", so I tried everything again with cover art file named "cover" instead of "folder", but nothing changed. For the next examples, I made the test with cover art named "cover.jpg".  
 
Running import command with auto-convert in verbose (`-vv`) mode:

```sh
$ beet -vv import ~/Drive/music/Anderson\ East/
user configuration: /var/services/homes/Samuel/.config/beets/config.yaml
data directory: /var/services/homes/Samuel/.config/beets
plugin paths:
Sending event: pluginload
library database: /var/services/homes/Samuel/.config/beets/library.db
library directory: /var/services/homes/Samuel/Drive/beets/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
/var/services/homes/Samuel/Drive/music/Anderson East/Encore
0 of 1 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
convert: Encoding /var/services/homes/Samuel/Drive/music/Anderson East/Encore/01 - King For A Day.flac
convert: Finished encoding /var/services/homes/Samuel/Drive/music/Anderson East/Encore/01 - King For A Day.flac
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: album_imported
Sending event: import
Sending event: cli_exit

```
Running import command with copyartefacts and embedart in verbose (`-vv`) mode:
```sh
$ beet -vv import ~/Drive/music/Anderson\ East/
user configuration: /var/services/homes/Samuel/.config/beets/config.yaml
data directory: /var/services/homes/Samuel/.config/beets
plugin paths:
Sending event: pluginload
library database: /var/services/homes/Samuel/.config/beets/library.db
library directory: /var/services/homes/Samuel/Drive/beets/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
/var/services/homes/Samuel/Drive/music/Anderson East/Encore
0 of 1 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Copying artifact: cover.jpg
Copying artifact: 01APIC_03.jpg
Ignored files:
    01 - King For A Day.flac@SynoEAStream
Sending event: album_imported
Sending event: import
Sending event: cli_exit
``` 

### Setup

* OS: Synology DSM
* Python version: 2.7.12
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

Test with the convert plugin:
```yaml
directory: ~/Drive/beets/music/

import: 
    log: ~/.config/beets/log.txt
    autotag: no
    group_albums: no

plugins: convert

paths:
    singleton: $albumartist/$album/$track %artist - $title
    comp: Various Artists/$album/$track $title
    
convert:
    auto: yes
    embed: yes
    copy_album_art: yes
    never_convert_lossy_files: yes
    format: alac
```

Test with the copyartifacts and embedart plugins:
```yaml
directory: ~/Drive/beets/music/

import: 
    log: ~/.config/beets/log.txt
    autotag: no
    group_albums: no
    
plugins: embedart copyartifacts

paths:
    singleton: $albumartist/$album/$track %artist - $title
    comp: Various Artists/$album/$track $title
    
embedart:  
    auto: yes
    ifempty: yes
    
copyartifacts:
    extensions: .lrc .jpg
    print_ignored: yes
```
