### ISSUE TITLE
lastgenre-plugin: API search with Singleton tracks

### ISSUE THREAD

**Issue by jones1008** [beetbox/beets#2843]
​After I imported my ~150gb music library with lastgenre plugin enabled, I listed all tracks without a genre tagged, with the command `beet list genre::^$`
This are about 1000 tracks.

Then I picked out a few tracks and tried to manually search for them with a lastfm API request.
example:
- Track: `DJ Antoine feat. Jay Sean - Provocateur - Keep on Falling (radio edit)`

- The Request I tried for this track is [here](https://ws.audioscrobbler.com/2.0/?method=track.search&track=DJ%20Antoine%20feat.%20Jay%20Sean%20Keep%20on%20Falling%20(radio%20edit)&api_key=2dc3914abf35f0d9c92d97d8f8e42b43&format=json) (just a search with title tag and artist tag)
And the first result is the track I was searching for...

So why doesn't it get a genre assigned to it?
Is it because this track maybe has no tag assigned to it on last.fm or what am I missing?

PS: I just wasn't able to pull the answer out of the [lastgenre-script](https://github.com/beetbox/beets/blob/master/beetsplug/lastgenre/__init__.py) due to my lack of python knowledge...

**Comment by sampsyo** [comment]
Probably! Can you please complete the rest of the bug template, including the verbose log and your configuration? Do some of the tracks get genres but not others? If so, do they have anything in common?

**Comment by jones1008** [comment]
So I imported one track **as an album** that has no genre tag assigned to it with this command:
`beet -vv import /path/to/audio.mp3` (DJ Antoine feat. Jay Sean - Provocateur - Keep on Falling (radio edit)) and recieved the following output:

> [...]
> lastgenre: added last.fm album genre (artist): House, Electronic
> Sending event: database_change
> Sending event: database_change
> lastgenre: added last.fm item genre (None):
> [...]

This means that the album has a genre assigned to it, but the item doesn't.
Then I imported the same track as a singleton with the `-s` option and it logically didn't get a genre assigned to it.

This means that the command `beet list genre::$` will not find the items where the corresponding album has a genre assigned to it, but only the items with a genre assigned to it.
A possible solution would then be: assign the same genre tag found for the album to the item itself...


> do they have anything in common?

The tracks I get with the command `beet list genre::^$` are many items imported as a singleton but also many albums and also many with mutltiple artist like `DJ Antoine, Mad Mark, FlameMakers feat. Ladina Spence`


This is my config:
```
directory: /path/to/newmusic
library: /path/to/musiclibrary.db

import:
 move: no
 copy: yes
 log: /var/log/beets/import.log
 duplicate_action: remove
 default_action: apply
 incremental: yes
 quiet_fallback: asis
 none_rec_action: ask

match:
 strong_rec_thresh: 0.10
 medium_rec_thresh: 0.25
 max_rec:
  missing_tracks: strong
 preferred:
  original_year: yes

plugins: lyrics lastgenre acousticbrainz popularity info zero web fromfilename smartplaylist
lyrics:
 force: yes
lastgenre:
 canonical: yes
 count: 2
 source: track
zero:
 fields: comments
 update_database: true
web:
 reverse_proxy: true

paths:
 default: $albumartist/$album%aunique{}/$title - $artist
 singleton: $albumartist/Singles/$title - $artist
 comp: $albumartist/$album%aunique{}/$title - $artist
 albumtype:soundtrack: Theme/$album%aunique{}/$title - $artist
```
