### ISSUE TITLE
"replace" Not Applied to Albums.

### ISSUE THREAD

**Issue by AndyIbanez** [beetbox/beets#2844]
### Problem
It looks like the replace command is not applied to albums. I have an artist called "Isshuukan Friends." (notice the period in the name), and that artist has an album called "Isshuukan Friends. OST".

Running a beet import created this artist directory and this album:

![Dirs](https://i.imgur.com/iiohpvb.png)

Like you can see, the period was properly replaced in the Artist Name, but not in the album name.

The period doesn't get replaced in song names either (i.e. This song called `01-30 Niji no Kakera -Piano ver.-.m4a`, which has a period other than the file extension). I'd expect replace to be applied to anything that Beets does on the file system.

I have explicitly copied and pasted the rules from the documentation in my config file.

I have had issues in the past in which it looked like Beets wasn't copying all my files, which led me to import my library album by album. I suspect this might be related

```
replace:
 '[\\/]': _
 '^\.': _
 '[\x00-\x1f]': _
 '[<>:"\?\*\|]': _
 '\.$': _
 '\s+$': ''
 '^\s+': ''
```

* OS: macOS High Sierra 10.13.13
* Python version: 3.6.4
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): (no plugins installed)

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/Vault/Music/Library
library: /Volumes/Vault/Music/Beets/Data/library.db

import:
    write: no
    copy: yes
    log: /Volumes/Vault/Music/Beets/Logs/beets.log
    group_albums: yes
    autotag: no

format_item: $artist - $album - $disc-$track $title
format_album: $albumartist - $album ($year)
per_disc_numbering: yes

paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
    ^\s+: ''
```
