### ISSUE TITLE
Windows folder not found with trailing backslash

### ISSUE THREAD

**Issue by SuperSandro2000** [beetbox/beets#2850]
### Problem

Running import with a path that contains a trailing slash will fail.

```sh
beet -vv import "C:\Users\Sandro\MuImp\smartphone\"
user configuration: C:\Users\Sandro\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Sandro\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: C:\Users\Sandro\AppData\Roaming\beets\library.db
library directory: C:\Users\Sandro\Music
Sending event: library_opened
error: no such file or directory: C:\Users\Sandro\MuImp\smartphone"
```

Works without the trialing backslash.

```sh
beet -vv import "C:\Users\Sandro\MuImp\smartphone"
user configuration: C:\Users\Sandro\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Sandro\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: C:\Users\Sandro\AppData\Roaming\beets\library.db
library directory: C:\Users\Sandro\Music
Sending event: library_opened
Sending event: import_begin
Import of the directory:
C:\Users\Sandro\MuImp\smartphone
was interrupted. Resume (Y/n)?
```

### Setup

* OS: Windows 10
* Python version: 3.6.4
* beets version:  1.4.6

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music

import:
    move: yes

paths:
    default: $albumartist/$album%aunique{}/$track $title - $artist
    singleton: Non-Album/$artist/$title - $artist
    comp: $albumartist/$album%aunique{}/$track $title - $artist

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': ''
    \.$: _
    \s+$: ''
    ^\s+: ''
    ^-: _
```
