### ISSUE TITLE
MusicBrainz uses canonical artist name, not release name

### ISSUE THREAD

**Issue by ddfreyne** [beetbox/beets#2854]
### Problem

Beets sets the artist to the canonical artist name. For example:

```
/Volumes/Champlain Music/music-pending/Monolith/Volume 1 (4 items)
Correcting tags from:
    Monolith - Volume 1
To:
    Dave Monolith - Volume 1
URL:
    https://musicbrainz.org/release/38f33632-90a1-3f7f-8bc4-c60de61a7eae
```

Note: `Monolith` -> `Dave Monolith`.

**Expected:** Tracks are tagged with artist `Monolith` (because that is how the artist is credited on the release).

**Actual:** Tracks are tagged with artist `Dave Monolith`.

This *might* be expected behavior for some (or in some cases), but I could not find a way to configure it.

### Setup

```
% uname -a
Darwin attignawantan.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,2 Darwin
```

```
% beet --version
beets version 1.4.5
Python version 3.6.4
plugins: discogs, mbsync
```

My configuration (output of `beet config`) is:

```yaml
library: "/Volumes/Champlain Music/music.db"
directory: "/Volumes/Champlain Music/music-imported"
plugins: discogs mbsync
id3v23: true
per_disc_numbering: true

import:
  move: yes
  write: yes
  duplicate_action: skip
  log: "/Volumes/Champlain Music/beet-import.log"

paths:
  default: "$albumartist/$album%aunique{}/$disc-$track $title"
  singleton: "(Not on album)/$artist/$title"
  comp: "(Compilations)/$album%aunique{}/$disc-$track $title"
```
