### ISSUE TITLE
plexupdate: Support SSL

### ISSUE THREAD

**Issue by wilsonic** [beetbox/beets#2871]
### Problem

Is it possible to add the option for updating Plex via SSL? I have my Plex Server set to Secure required and can no longer update the Music library after a beets import. 

### Setup

* OS: Linuxserver Docker
* Python version:  2.7
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web plexupdate the ftintitle discogs duplicates missing zero permissions
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no
#color: yes

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1

paths:
    default: %the{$albumartist}/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title 

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    sources: coverart itunes amazon albumart google

replaygain:
    auto: no

scrub:
    auto: yes

plex:
    host: 192.168.10.200
    port: 32400
    token: 

ftintitle:
    auto: yes
    drop: no
    format: feat. {0}

web:
    host: 0.0.0.0
    port: 8337

zero:
    fields: comments
    update_database: true

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

permissions:
    file: 644
    dir: 755

```
