### ISSUE TITLE
feature request: date range querys for the field 'year'

### ISSUE THREAD

**Issue by jones1008** [beetbox/beets#2872]
In some cases it would be useful to use [date and date range querys](http://beets.readthedocs.io/en/v1.4.6/reference/query.html#date-and-date-range-queries) with the `year` tag.

So a query like:
`beet list 'added:-5y..'`
would also be useful with the year tag:
`beet list 'year:-5y..'`
This query would list all tracks from the last 5 years. 
It is more dynamic than those:
```
beet list 'year:2013..2018'
beet list 'year:2013..'
```

Any thoughts on that?

**Comment by jones1008** [comment]
This sounds more solid than my version!
Very good!

**Comment by sampsyo** [comment]
OK, this is a good idea. Thanks for the suggestion.

**Comment by solson** [comment]
FYI it seems like you can implement this with the following configuration:

```yaml
plugins: inline types

types:
  date: date

item_fields:
  date: |
    import datetime
    return datetime.datetime(year or 1, month or 1, day or 1).timestamp()

album_fields:
  date: |
    import datetime
    return datetime.datetime(year or 1, month or 1, day or 1).timestamp()
```

The reason I have all the `x or 1` expressions is that many of my tags seem to lack specific dates, and set things like `year:1994 month:0 day:0` when only the year is known. I'm not sure what an official implementation of `date` should do in this case, but it would be nice to figure it out. It's nice that `inline` makes this possible, but this seems like a case where it should be replaced by a built-in feature.

**Comment by eternaleye** [comment]
You can also collapse the definition into a one-liner by using `__import__`:

```yaml
plugins: inline types

types:
  date: date

item_fields:
  date: __import__("datetime").datetime(year or 1, month or 1, day or 1).timestamp()

album_fields:
  date: __import__("datetime").datetime(year or 1, month or 1, day or 1).timestamp()
```

I did this, and the same for the `original_` fields.
