### ISSUE TITLE
mbsync looks up albums bit by bit

### ISSUE THREAD

**Issue by dosoe** [beetbox/beets#2876]
### Problem

After I had some little problems with my library, I imported it again using ```beet import -A``` . That worked fine, but once I wanted to update the metadata with ```mbsync```, I ran into problems. 
The music I imported wasn't classified by album, I used another classification (by parentcomposer and parentwork, see https://github.com/beetbox/beets/pull/2580 ) so my albums were split into several folders. 
When I ran ```mbsync``` , it looked up all the albums but not as whole albums, it looked them up bit by bit (these bits corresponding to the split at the import), even after I reorganized the library for the files to be organized by album. This doesn't correspond to the documentation (that states that albums are updated as a whole) and slows down the sync quite substatially: my "Bach: Complete Works" are not looked up as one album, but it looks it up separately for each work (and there is a lot of them). 
A way to reproduce this could be to have an already tagged album split up over multiple directories (like create a directory for each track), import it using ```beet import -A``` and then try to ```mbsync``` it. 

### Setup

* OS: Ubuntu 17.10
* Python version: Python 2.7.13
* beets version: beets version 1.4.7
* Turning off plugins made problem go away (yes/no): Well, if I turn mbsync off it makes the problem go away but that's not really the point

My configuration (output of `beet config`) is:

```yaml
paths:
    albumartist_sort::'Wise Guys': '%asciify{ZZZ_Non-classical/$albumartist_sort/$album %ifdef{albumdisambig,($albumdisambig),}//$disc-$track $title}'
...
    albumartist_sort::'Williams, John, Hovhaness, Alan; London Symphony Orchestra, LeClair, Judith, Williams, John': '%asciify{ZZZ_Non-classical/$albumartist_sort/$album %ifdef{albumdisambig,($albumdisambig),}//$disc-$track $title}'
    artist::'Louis Armstrong': '%asciify{ZZZ_Non-classical/$artist_sort/$title}'
...
    artist::'Led Zeppelin': '%asciify{ZZZ_Non-classical/$artist_sort/$title}'
    artist_sort::'ZZ Top': '%asciify{ZZZ_Non-classical/$artist_sort/$title}'
    parent_work:Church parent_composer_sort:'Mozart, Wolfgang Amadeus': '%asciify{%ifdef{parent_composer_sort,$parent_composer_sort/Church Sonatas/$parent_work%ifdef{parent_work_disambig,($parent_work_disambig)}/%ifdef{album,$albumartist_sort/$album %ifdef{albumdisambig,($albumdisambig),}//$disc-$track $title,$artist/$title},ZZZ-Nosortcomposer/%ifdef{album,$albumartist_sort/$album %ifdef{albumdisambig,($albumdisambig),}//$disc-$track $title,$artist/$title}}}'
...
    default: '%asciify{%ifdef{parent_composer_sort,$parent_composer_sort/$parent_work%ifdef{parent_work_disambig,($parent_work_disambig)}/$albumartist_sort/$album %ifdef{albumdisambig,($albumdisambig),}//$disc-$track $title,%ifdef{parent_work,ZZZ-Nosortcomposer/$albumartist_sort/$album %ifdef{albumdisambig,($albumdisambig),}//$artist_sort/$disc-$track $title,ZZZ-nowork/$albumartist_sort/$album %ifdef{albumdisambig,($albumdisambig),}//$artist/$disc-$track $title}}}'
parentwork:
    force: no
    auto: no
missing:
    count: yes
    album: no
    total: no
duplicates:
    tiebreak:
        items: [bitrate]
    keys: [mb_trackid, mb_releasegroupid, track]
    count: no
    full: no
    format: ''
    move: ''
    tag: ''
    path: no
    copy: ''
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
bell: yes
library: /home/soergeld/Personnel/Music/Musicdata.db
mbsubmit:
    format: $title - $artist ($length)
    threshold: strong
badfiles:
    commands:
        ogg: ogginfo -q

plugins: inline web duplicates edit info mbsync badfiles fromfilename missing parentwork mbsubmit
directory: /home/soergeld/Personnel/Music

import:
    copy: no
    write: no
    incremental: no
    detail: yes
    languages: en
    duplicate_action: keep
    per_disc_numbering: yes
pathfields: {}
album_fields: {}
item_fields: {}
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
web:
    cors_supports_credentials: no
    reverse_proxy: no
    host: 127.0.0.1
    include_paths: no
    cors: ''
    port: 8337

```
