### ISSUE TITLE
"open failed: Stream info block not found" while importing certain FLAC files

### ISSUE THREAD

**Issue by splump** [beetbox/beets#2883]
### Problem

Trying to import FLAC files purchased from autechre.ws does not work

Running this command in verbose (`-vv`) mode:
```
$ beet -vv import Autechre\ -\ NTS\ Session\ 2/
```
### Led to this problem:
```
user configuration: /home/splump/.config/beets/config.yaml
data directory: /home/splump/.config/beets
plugin paths: 
Sending event: pluginload
library database: /hive/music/.library.blb
library directory: /hive/music
Sending event: library_opened
Sending event: import_begin
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-001-Autechre-elyc9 7hres.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-002-Autechre-six of eight (midst).flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-003-Autechre-xflood.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-004-Autechre-gonk tuf hi.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-005-Autechre-dummy casual pt2.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-006-Autechre-violvoic.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-007-Autechre-sinistrailAB air.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-008-Autechre-wetgelis casual interval.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-009-Autechre-e0.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-010-Autechre-peal MA.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-011-Autechre-9 chr0.flac
open failed: Stream info block not found
unreadable file: /home/splump/Autechre - NTS Session 2/NTS Session 2-012-Autechre-turbile epic casual, stpl idle.flac
No files imported from /home/splump/Autechre - NTS Session 2
Sending event: import
Sending event: cli_exit

### Here's a link to the music files that trigger the bug (if relevant): 
Not sure i'm allowed to post these since they are copyright protected. Metaflac yields no issues with the files and i can play them in any music player without issues. 
```
### Setup

* OS: Arch Linux
* Python version: 2.7.14
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): no

### My configuration (output of `beet config`) is:
```
paths:
    default: $albumartist/$album ($year)/$disc.$track. $title
    comp: Various Artists/$album ($year)/$disc.$track. $title
threaded: yes
art_filename: cover
fetchart:
    cautious: yes
    cover_names: front
    sources: bandcamp itunes *
    auto: yes
    minwidth: 0
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
library: /hive/music/.library.blb
ignore: .AppleDouble ._* *~ .DS_Store

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

plugins: fetchart lastgenre info discogs bandcamp
directory: /hive/music

import:
    copy: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    log: beetslog.txt

match:
    required: year
bandcamp:
    min_candidates: 5
    art: no
    lyrics: no
    source_weight: 0.5
discogs:
    tokenfile: discogs_token.json
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
lastgenre:
    count: 1
    source: album
    prefer_specific: no
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
```
