### ISSUE TITLE
Typo in config is accepted

### ISSUE THREAD

**Issue by cgtobi** [beetbox/beets#2894]
### Problem

I made a typo in the `lastgenre `config and put in `whiltelist` instead of `whitelist`. Surprisingly this resulted in a working config although the config entry which made no sense.

```yaml
lastgenre:
    auto: no
    canonical: /data/genres-tree.yaml
    whiltelist: /data/genres.txt
    whitelist: yes
```

This is also true for other plugins as e.g. zero. What I also noticed is that beets does not complain about having:

```yaml
zero:
    auto: yes

zero:
    auto: no
```

### Setup

* OS: Ubuntu
* Python version: 3.6.5
* beets version: 1.4.6
