### ISSUE TITLE
%ifdef{} unexpected behaviour

### ISSUE THREAD

**Issue by DjSlash** [beetbox/beets#2925]
### Problem

In my path I have recently exchanged `%if{$year, $year - }` for `%ifdef{original_year, $original_year - ,$year - }`. In most cases this works as expected. However, I witnessed that some files were misplaced: they ended up in a directory where year was presented as '0000'.

```sh
$ beet info 0000\ -\ LoveLounge\ Vol.\ 2\ \(disc01\)\ \[compilation\]/01\ -\ Fabergé\ -\ Spring\ Again.mp3|grep year
     original_year: 2003
              year: 2003
$ beet move 0000\ -\ LoveLounge\ Vol.\ 2\ \(disc01\)\ \[compilation\]/01\ -\ Fabergé\ -\ Spring\ Again.mp3
Moving 0 items.
```
However, when I change the `%ifdef{}`to `%if{$original_year,$original_year - ,$year - }`, it works as expected:
```sh
$ beet move 0000\ -\ LoveLounge\ Vol.\ 2\ \(disc01\)\ \[compilation\]/01\ -\ Fabergé\ -\ Spring\ Again.mp3
Moving 1 item.
```

### Setup

* OS: Debian testing
* Python version: 3.6.5rc1
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no

Relevant configuration:

```yaml
paths:
        default: albums/%the{$albumartist}/%ifdef{original_year,$original_year - ,$year - }$album%if{$multidisc, (disc$disc$cdtitle)}%if{$notalbum, $cdtype}%aunique{original_year albumartist album}/$track - $artist - $title
        comp: albums/000 Various Artists/%ifdef{original_year,$original_year - ,$year - }$album%if{$multidisc, (disc$disc$cdtitle)}%if{$notalbum, $cdtype}%aunique{original_year albumartist album}/$track - $artist - $title
```
([full config](https://gist.github.com/DjSlash/3313266de1b696667725))
