### ISSUE TITLE
Singleton tags not updated

### ISSUE THREAD

**Issue by ryanakca** [beetbox/beets#2939]
### Problem

Using `beet modify` to set the singleton field to true doesn't actually do anything.

```sh
rak@zeta:/media/wd/music_clean/MP3/Various Artists/Gold$ beet -vv ls "path:$(pwd)" singleton:False | wc -l
user configuration: /home/rak/.config/beets/config.yaml
data directory: /home/rak/.config/beets
plugin paths:
Sending event: pluginload
library database: /media/wd/music_clean/beetsmusic.blb
library directory: /media/wd/music_clean
Sending event: library_opened
Sending event: cli_exit
115
rak@zeta:/media/wd/music_clean/MP3/Various Artists/Gold$ beet -vv mod "path:$(pwd)" singleton:False singleton=True
user configuration: /home/rak/.config/beets/config.yaml
data directory: /home/rak/.config/beets
plugin paths:
Sending event: pluginload
library database: /media/wd/music_clean/beetsmusic.blb
library directory: /media/wd/music_clean
Sending event: library_opened
Modifying 115 items.
No changes to make.
Sending event: cli_exit
rak@zeta:/media/wd/music_clean/MP3/Various Artists/Gold$ beet -vv ls "path:$(pwd)" singleton:False | wc -l
user configuration: /home/rak/.config/beets/config.yaml
data directory: /home/rak/.config/beets
plugin paths:
Sending event: pluginload
library database: /media/wd/music_clean/beetsmusic.blb
library directory: /media/wd/music_clean
Sending event: library_opened
Sending event: cli_exit
115
```

### Setup

* OS: Debian unstable
* Python version: 3.6.5
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): Didn't check.

My configuration (output of `beet config`) is:

```yaml
directory: /media/wd/music_clean
library: /media/wd/music_clean/beetsmusic.blb

plugins: mbsync duplicates fetchart mbcollection badfiles

import:
    incremental: yes
    quiet_fallback: skip
    log: /media/wd/music_clean/import_log
    move: yes
    write: yes
    autotag: yes

paths:
    default: $format/$albumartist/$album/$track $title
    singleton: $format/Singletons/$artist - $title
    comp: $format/comp/$album/$track $title

musicbrainz:
    user: ryanakca
    pass: REDACTED
    auto: yes

match:
    preferred:
        countries: [CA, US]
        media: [CD]
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
mbcollection:
    auto: no
    collection: ''
    remove: no
```
