### ISSUE TITLE
Flexible attributes don't get picked up

### ISSUE THREAD

**Issue by wschella** [beetbox/beets#2940]
### Problem

Whenever I try to use a flexible attribute in path name during an import, %ifdef prints the falsy result.
The attribute also doesn't show up in `beet fields`. Am I missing something, configuring something wrong?

Running this command in verbose (`-vv`) mode:

```sh
$  beet -vv import SourceBackup/4\ Non\ Blondes/
```

Led to this problem (the `ne` is the falsy arm, see config`):

```
/4 Non Blondes/[1992] Bigger, Better, Faster, More!  ne
```

### Setup

* OS: Ubuntu 18.04
* Python version: 3.6.5
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): /

My configuration (output of `beet config`) is:

```yaml
directory: ~/data/Music/Library
library: ~/data/Music/Resources/library.db

plugins: fetchart

paths:
    default: $albumartist/[$year] $album%aunique{} %ifdef{tags, e, ne}/$track - $title
    singleton: $albumartist/Non-Album/[$year] $title
    comp: Compilations/[$year] $album%aunique{}/$track - $title
album_fields:
    tags: test
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
```

The problem persists whether i use `tags` or `$tags`, put it in `album_fields or `item_fields` (or root), or if i explicitly `return 'test'`.
