### ISSUE TITLE
File extension not added on ALAC/AAC-LC file after import

### ISSUE THREAD

**Issue by ryanakca** [beetbox/beets#2941]
### Problem

I imported an [ALAC/AAC file](http://www.johnbottomleybagpipes.com/carlisle.m4a), but beets did not append an extension on the file after placing it in the appropriate directory. This means that mpd does not detect the file (appending ".m4a" to the file name causes mpd to detect the file).

```sh
rak@zeta:~$ beet -vv  ls -p Carlisle Medley
user configuration: /home/rak/.config/beets/config.yaml
data directory: /home/rak/.config/beets
plugin paths:
Sending event: pluginload
library database: /media/wd/music_clean/beetsmusic.blb
library directory: /media/wd/music_clean
Sending event: library_opened
/media/wd/music_clean/AAC/Singletons/Andrew Carlisle - Medley
Sending event: cli_exit
rak@zeta:~$ file "/media/wd/music_clean/AAC/Singletons/Andrew Carlisle - Medley"
/media/wd/music_clean/AAC/Singletons/Andrew Carlisle - Medley: ISO Media, Apple iTunes ALAC/AAC-LC (.M4A) Audio
rak@zeta:~$ mediainfo "/media/wd/music_clean/AAC/Singletons/Andrew Carlisle - Medley"
General
Complete name                            : /media/wd/music_clean/AAC/Singletons/Andrew Carlisle - Medley
Format                                   : MPEG-4
Format profile                           : Apple audio with iTunes info
Codec ID                                 : M4A  (M4A /mp42/isom)
File size                                : 4.18 MiB
Duration                                 : 9 min 1 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 64.8 kb/s
Album                                    : Metro Cup 2018
Track name                               : Medley
Performer                                : Andrew Carlisle
Recorded date                            : 2018
Encoded date                             : UTC 2018-02-18 02:46:53
Tagged date                              : UTC 2018-02-18 02:46:53
Writing application                      : com.apple.VoiceMemos (iOS 11.2.5)
R128_ALBUM_GAIN                          : 0
R128_TRACK_GAIN                          : 0
ORIGINAL YEAR                            : 0000
FileExtension_Invalid                    : mov mp4 m4v m4a m4b m4p 3ga 3gpa 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma ismt f4a f4b f4v

Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 9 min 1 s
Source duration                          : 9 min 1 s
Bit rate mode                            : Constant
Bit rate                                 : 64.0 kb/s
Channel(s)                               : 2 channels
Channel(s)_Original                      : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 4.07 MiB (98%)
Source stream size                       : 4.07 MiB (98%)
Title                                    : Core Media Audio
Encoded date                             : UTC 2018-02-18 02:46:53
Tagged date                              : UTC 2018-02-18 02:46:53

```

Here's a link to the music files that trigger the bug (if relevant): http://www.johnbottomleybagpipes.com/carlisle.m4a

### Setup

* OS: Linux zeta 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
* Python version: 3.6.5
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /media/wd/music_clean
library: /media/wd/music_clean/beetsmusic.blb

plugins: mbsync duplicates fetchart mbcollection badfiles

import:
    incremental: yes
    quiet_fallback: skip
    log: /media/wd/music_clean/import_log
    move: yes
    write: yes
    autotag: yes

paths:
    default: $format/$albumartist/$album/$track $title
    singleton: $format/Singletons/$artist - $title
    comp: $format/comp/$album/$track $title

musicbrainz:
    user: ryanakca
    pass: REDACTED
    auto: yes

match:
    preferred:
        countries: [CA, US]
        media: [CD]
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
mbcollection:
    auto: no
    collection: ''
    remove: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
```
