### ISSUE TITLE
convert plugin copies replaygain tags into opus files, instead of using R128 tags

### ISSUE THREAD

**Issue by cstoitner** [beetbox/beets#2945]
### Problem
When converting flac files to opus, the previously generated replaygain tags get copied over to the opus files. Opus files should use R128 tags instead (see https://github.com/beetbox/beets/issues/2557).

### Setup

* OS: linux
* Python version: 2.7.14
* beets version: 1.4.6

My configuration (output of `beet config`) is:

```yaml
mpd:
    port: 6600
    host: REDACTED
    password: REDACTED
lyrics:
    bing_lang_from: []
    force: no
    auto: yes
    genius_api_key: REDACTED
    google_engine_ID: REDACTED
    sources:
    - google
    - lyricwiki
    - musixmatch
    - genius
    bing_lang_to:
    bing_client_secret: REDACTED
    google_API_key: REDACTED
    fallback:
    local: no
asciify_paths: yes
art_filename: cover
replaygain:
    backend: bs1770gain
    method: ebu
    overwrite: yes
    targetlevel: 89
    auto: yes
    r128: [Opus]
    chunk_at: 5000

plugins: fetchart lastimport lyrics mbsync zero the thumbnails replaygain scrub mpdupdate convert importadded

ui:
    color: yes

import:
    move: yes
thumbnails:
    force: yes
    dolphin: yes
    auto: yes

paths:
    default: '%the{$albumartist}/$album %aunique{}/$track. $title'
    quarantine:true singleton:true: _quarantine/_non album/%the{$artist}/$title
    quarantine:true comp:true: _quarantine/_various artists/$album %aunique{}/$track. $title
    quarantine:true: _quarantine/%the{$albumartist}/$album %aunique{}/$track. $title
    singleton: _non album/%the{$artist}/$title
    comp: _various artists/$album %aunique{}/$track. $title
convert:
    dest: /mnt/enclave/share/Media/Audio/convertedMusic
    never_convert_lossy_files: yes
    copy_album_art: yes
    album_art_maxwidth: 1080
    embed: no
    format: opus
    formats:
        opus:
            command: opusenc --bitrate 192 "$source" "$dest"
            extension: opus.ogg
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    auto: no
    threads: 8
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    no_convert: ''
per_disc_numbering: no
zero:
    fields: [comments]
    comments:
    - EAC
    - LAME
    - CUERipper
    - from.+collection
    - ripped by
    - encoded by
    - \.com
    - \.de
    - \.net
    - \.org
    - Track \d+
    auto: yes
    update_database: no
    keep_fields: []
lastgenre:
    count: 3
    separator: ;
    whitelist: ~/.config/beets/genres.txt
    canonical: ~/.config/beets/canonicalGenres.yaml
directory: /mnt/enclave/share/Media/Audio/Music
lastfm:
    user: REDACTED
    api_key: REDACTED
the:
    a: yes
    the: yes
    patterns: [^der, ^die, ^das]
    strip: no
    format: '{0}, {1}'
mpdupdate:
    host: REDACTED
    port: 6600
lastimport:
    per_page: 500
    retry_limit: 3
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
importadded:
    preserve_write_mtimes: no
    preserve_mtimes: no
scrub:
    auto: yes
```
