### ISSUE TITLE
replaygain: Avoid magic Windows prefix in calls to mp3gain

### ISSUE THREAD

**Issue by Sirove** [beetbox/beets#2946]
The ReplayGain section inside my config file:
```
replaygain:
    auto: yes
    backend: command
    command: D:\Test\mp3gain.exe
    overwrite: yes
    targetlevel: 89
    noclip: yes
```

> replaygain: analyzing TestSong
> replaygain: ReplayGain error: mp3gain failed

I wish I could find more info but this is already the verbose output...
