### ISSUE TITLE
paths: genre canonical support

### ISSUE THREAD

**Issue by Sirove** [beetbox/beets#2950]
I use a pretty simple path format for my mostly singleton based collection: `$genre/$artist - $title`
The problem with that is my lastgenre configuration:
```
lastgenre:
    auto: yes
    canonical: yes
    count: 3
    force: yes
    min_weight: 10
    source: album
    whitelist: yes
```
As you can see the canonical option is activated as well as the genre count of 3.  So the created folder for a metal song looks like this: "D:\Test\Beets\Music_2\Metalcore, Heavy Metal, Rock". But I only want the first genre as the folder name like this "D:\Test\Beets\Music_2\Metalcore" **without** subfolders for Heavy Metal or Rock. 

Of course I could change the count to 1 but this would also embed only one genre into the music file.
What I suggest is something like this `$genre_canonical/$artist - $title`.
