### ISSUE TITLE
Special characters "skipped" on import, folder not found by beets

### ISSUE THREAD

**Issue by soadroxs** [beetbox/beets#2959]
### Problem
I'm trying to import a folder into my library that contains a special character (é), as so:

```sh
$ beet import "José Afonso - Venham Mais Cinco [FLAC]"
```
When I do, I get this back:

```
error: no such file or directory: Jos Afonso - Venham Mais Cinco [FLAC]
```

It seems to skip past the special character in the path, and that way it doesn't recognize the folder as such.

### Setup

* OS: Windows 10 Enterprise Build 1607 (x64)
* Python version: Python 3.6.5
* beets version: beets 1.4.7
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: E:\FinalMusic
original_date: yes

plugins: the ftintitle inline convert

paths:
    default: '%the{$mainartist}/$year - $album/$disc.$track - $title'

ui:
    color: no

import:
    write: yes
    move: yes
ftintitle:
    drop: yes
    auto: yes
    format: feat. {0}
the:
    a: no
    the: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
convert:
    auto: yes
    command: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest
    extension: opus
    never_convert_lossy_files: yes
    dest:
    pretend: no
    threads: 4
    format: mp3
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    copy_album_art: no
    album_art_maxwidth: 0
item_fields:
    mainartist: albumartist.split(";")[0].strip()
pathfields: {}
album_fields: {}
```
