### ISSUE TITLE
Stuck at Sending event: import_task_files

### ISSUE THREAD

**Issue by gerroon** [beetbox/beets#2964]
### Problem
I am Beets with using incremental  import with -W -C.  I was able to import my whole lib succesfully after couple tries. 

I wanted to add new music so I used again

```
beet -v import -i -A -C -W MYMEDIA
```

It gets at this step. using -vv did not give me any more information at all, almost the same lines.  If you know how to get more debug output I would be happy to trr out.

```
/Arthur Rubinstein/Piano Concertos
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
```

Here's a link to the music files that trigger the bug (if relevant):
Setup

    OS: Debian Testing
    Python version: 2.7
    beets version: 1.4.5

My configuration (output of beet config) is:

```
library: /media/USER/beets/musiclibrary.db                                                                                                                      
                
                                                                                                                                                          
  import:                                                                                                                                                                 
      copy: no                                                                                                                                                            
      write: no                                                                                                                                                           
      move: no                                                                                                                                                            
                                                                                                                                                                          
  plugins: fetchart inline convert web random                                                                                                                             
                                                                                                                                                                          
  convert:                                                                                                                                                                
      auto: true                                                                                                                                                          
                                                                                                                                                                          
  web:                                                                                                                                                                    
      host: 192.168.5.106                                                                                                                                                 
      port: 8337           

```
