### ISSUE TITLE
poor song title matching

### ISSUE THREAD

**Issue by nbartnik** [beetbox/beets#2981]
### Problem
Hi,
I've encountered what I think is a bug (or an oversight?) where song titles are being matched incorrectly.  It occurs when the number of tracks on the musicbrainz release matches the number of tracks in my album folder but the song titles may be different (due to the specific release not being on musicbrainz, or my album having missing/duplicate tracks).  

For example:
```
Tagging:
    Redgum - 4 Play, Volume 19
URL:
    https://musicbrainz.org/release/916138f8-60e2-4226-99f0-42821b8157e8
(Similarity: 86.6%) (tracks) (Vinyl, 1988, AU, Epic)
 * I Was Only 19 (A Walk in the Light Green) (#1) (4:26) -> Long Run (#4) (3:03) (id, title, length, index)
```

I have 4 tracks in this album, 3 are correct and 1 is a duplicate.  beets is attempting to rename the duplicate to the missing track name. The Levenshtein distance between the two strings is high so, given I have: 
```
match:
    ignored:  unmatched_tracks
``` 
beets should be skipping the album.  

The same issue occur when there are albums with multiple releases and variation in the tracks on each release 

### Setup
OS: 10.13.3
beets version 1.4.6
Python version 3.6.2
plugins: discogs

My configuration (output of `beet config`) is:

```yaml

paths:
    default: /$albumartist/$album/$track $title
    singleton: /$albumartist/$album/$track $title
    comp: /Compilation/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title

plugins: discogs
directory: /volume1/homes/admin/fs_admin/Music_WIP/beets/

import:
    move: yes
    write: yes
    log: beetslog.txt
discogs:
    user_token: REDACTED
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5

match:
    ignored: missing_tracks  unmatched_tracks
    strong_rec_thresh: 0.15
duplicate_action: skip
```
