### ISSUE TITLE
Multi-disc albums imported with --flat, in incremental mode gets sub-folders incorrectly reimported as separate albums

### ISSUE THREAD

**Issue by inthevidual** [beetbox/beets#2987]
### Problem

Multi-disc albums imported with --flat, in incremental mode gets sub-folders incorrectly reimported as separate albums whenever I run import.

### Setup

* OS: Ubuntu 18.04
* Python version: 2.7.15rc1
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
paths:
    default: $albumartist/$albumartist - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
convert:
    copy_album_art: yes
    embed: no
    dest: /E/E/beets/converted
    format: opus
    formats:
        opus: ffmpeg-audio-convert-or-copy $source $dest opus -y -vn -ab 96k
        mp3: ffmpeg -i $source -y -vn -aq 0 $dest
        pretend: no
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    threads: 6
    max_bitrate: 275
    auto: no
    quiet: no
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    tmpdir:

    paths: {}
    pretend: no
    no_convert: ''
threaded: yes
item_fields:
    multidisc: 1 if disctotal > 1 else 0
per_disc_numbering: yes
fetchart:
    sources: coverart itunes amazon albumart
    store_source: yes
    auto: yes
    minwidth: 0
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
max_filename_length: 255
library: ~/data/musiclibrary.db
replaygain:
    overwrite: yes
    backend: bs1770gain
    r128: Opus FLAC
    method: ebu
    auto: yes
    targetlevel: 89
    chunk_at: 5000

plugins: discogs inline fetchart replaygain convert
directory: /E/E/beets/

import:
    copy: yes
    move: no
    write: yes
    delete: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    none_rec_fallback: skip
    timid: no
    languages: en
    log: ~/beets-import.log
discogs:
    tokenfile: discogs_token.json
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
pathfields: {}
album_fields: {}


```
