### ISSUE TITLE
What is `beet update` doing???

### ISSUE THREAD

**Issue by shimizurei** [beetbox/beets#2989]
### Problem

I edit my files in tagscanner after import and for some reason when I go to do `beet update`, I get stale updates. Today, I edited an album called "Kakegurui original soundtrack", but that's not even shown. The code below was edited sometime last week and shouldn't even be in the update queue. Some of the tags seem to be in the process of being deleted, which I never even specified! (I went and tried to re-add mbids late last week because they were gone). Since that time, I've even nuked my db once or twice.

Is there a flush system where you can start with fresh updates? I have no idea what beets is doing (or what I'm doing -_-).

This is not a very reproducible issue. If all else fails, I will reinstall beets since destroying the db does nothing.

```
PS C:\Users\me> beet update -p

BRIEF & TRUNKS - Buritora Golden Best - Ishiyaki Imo (τƒ│τä╝πéñπâó)
  catalognum:  -> VSCD-3184
MAN WITH A MISSION - 5 Years 5 Wolves 5 Souls - FLY AGAIN
  original_day: 01 -> 00
  original_month: 01 -> 00
MAN WITH A MISSION - 5 Years 5 Wolves 5 Souls - Wake Myself Again
  albumstatus: Official ->
  original_day: 01 -> 00
  albumdisambig: ΘÇÜσ╕╕τ¢ñ ->
  mb_releasegroupid: 72303be6-b80f-4474-9544-071f177717ae ->
  script: Qaaa ->
  albumartist_credit: MAN WITH A MISSION ->
  original_month: 01 -> 00
  asin: B00OT34AT6 ->
  original_year: 2015 -> 0000
  language: eng -> English
  country: JP ->
  albumtype: compilation ->
MAN WITH A MISSION - 5 Years 5 Wolves 5 Souls - RAIN OF JULY
  original_day: 01 -> 00
  original_month: 01 -> 00
MAN WITH A MISSION - Dead End in Tokyo [European Edition] - Dead End in Tokyo
  albumstatus: Official ->
  mb_releasegroupid: 30406de9-8f8f-4e4c-a91f-74d38d18764e ->
  script: Latn ->
  albumartist_credit: MAN WITH A MISSION ->
  original_year: 2017 -> 0000
  language: eng ->
  country: JP ->
  albumtype: EP ->
MAN WITH A MISSION - Dead End in Tokyo [European Edition] - Seven Deadly Sins
  albumstatus: Official ->
  mb_releasegroupid: 30406de9-8f8f-4e4c-a91f-74d38d18764e ->
  script: Latn ->
  albumartist_credit: MAN WITH A MISSION ->
  original_year: 2017 -> 0000
  language: eng ->
  country: JP ->
  albumtype: EP ->
MAN WITH A MISSION - Dead End in Tokyo [European Edition] - Survivor - live from The World's On Fire Tour
  original_day: 00 -> 21
  original_month: 00 -> 06
MAN WITH A MISSION - Dead End in Tokyo [European Edition] - Give it Away - live from The World's On Fire Tour
  original_day: 00 -> 21
  original_month: 00 -> 06
MAN WITH A MISSION - Dead End in Tokyo [European Edition] - The World's On Fire - live from The World's On Fire Tour
  original_day: 00 -> 21
  original_month: 00 -> 06
MAN WITH A MISSION - Out of Control - The Cure
  albumstatus:  -> Official
  original_day: 00 -> 20
  mb_releasegroupid:  -> 4feb14ac-0008-4601-9a11-634abe023c84
  script:  -> Latn
  albumartist_credit:  -> MAN WITH A MISSION├ùZebrahead
  original_month: 00 -> 05
  original_year: 0000 -> 2015
  language:  -> eng
  country:  -> JP
  albumtype:  -> EP
MAN WITH A MISSION - The World's On Fire - Waiting for the Moment
  albumstatus: Official ->
  original_day: 03 -> 00
  mb_releasegroupid: 30396142-2b07-4447-b862-7d6e7d2f99f1 ->
  script: Jpan ->
  albumartist_credit: MAN WITH A MISSION ->
  original_month: 02 -> 00
  original_year: 2016 -> 0000
  language: jpn ->
  country: ID ->
  albumtype: album ->
MAN WITH A MISSION - The World's On Fire - Raise your flag
  albumstatus: Official ->
  original_day: 03 -> 00
  mb_releasegroupid: 30396142-2b07-4447-b862-7d6e7d2f99f1 ->
  script: Jpan ->
  albumartist_credit: MAN WITH A MISSION ->
  original_month: 02 -> 00
  original_year: 2016 -> 0000
  language: jpn ->
  country: ID ->
  albumtype: album ->
MAN WITH A MISSION - The World's On Fire - followers
  original_day: 03 -> 00
  original_month: 02 -> 00
MAN WITH A MISSION - The World's On Fire - The World's On Fire
  albumstatus: Official ->
  original_day: 03 -> 00
  mb_releasegroupid: 30396142-2b07-4447-b862-7d6e7d2f99f1 ->
  script: Jpan ->
  albumartist_credit: MAN WITH A MISSION ->
  original_month: 02 -> 00
  original_year: 2016 -> 0000
  language: jpn ->
  country: ID ->
  albumtype: album ->
MAN WITH A MISSION - The World's On Fire - Give it Away
  original_day: 03 -> 00
  original_month: 02 -> 00
MAN WITH A MISSION - The World's On Fire - Seven Deadly Sins
  albumstatus: Official ->
  original_day: 03 -> 00
  mb_releasegroupid: 30396142-2b07-4447-b862-7d6e7d2f99f1 ->
  script: Jpan ->
  albumartist_credit: MAN WITH A MISSION ->
  original_month: 02 -> 00
  original_year: 2016 -> 0000
  language: jpn ->
  country: ID ->
  albumtype: album ->
MAN WITH A MISSION - The World's On Fire - Out of Control feat. Zebrahead
  albumstatus: Official ->
  original_day: 03 -> 00
  mb_releasegroupid: 30396142-2b07-4447-b862-7d6e7d2f99f1 ->
  script: Jpan ->
  albumartist_credit: MAN WITH A MISSION ->
  original_month: 02 -> 00
  original_year: 2016 -> 0000
  language: jpn ->
  country: ID ->
  albumtype: album ->
MAN WITH A MISSION - The World's On Fire - Wonderland (πâ»πâ│πâÇπâ╝πâ⌐πâ│πâë)
  albumstatus: Official ->
  original_day: 03 -> 00
  mb_releasegroupid: 30396142-2b07-4447-b862-7d6e7d2f99f1 ->
  script: Jpan ->
  albumartist_credit: MAN WITH A MISSION ->
  original_month: 02 -> 00
  original_year: 2016 -> 0000
  language: jpn ->
  country: ID ->
  albumtype: album ->
Zebrahead - Out of Control - Lockjaw
  albumstatus:  -> Official
  mb_releasegroupid:  -> 4feb14ac-0008-4601-9a11-634abe023c84
  script:  -> Latn
  albumartist_credit:  -> MAN WITH A MISSION├ùZebrahead
  original_year: 0000 -> 2015
  language:  -> eng
  country:  -> JP
  albumtype:  -> EP
Zebrahead - Out of Control - Blue Light Special
  albumstatus:  -> Official
  mb_releasegroupid:  -> 4feb14ac-0008-4601-9a11-634abe023c84
  script:  -> Latn
  albumartist_credit:  -> MAN WITH A MISSION├ùZebrahead
  original_year: 0000 -> 2015
  language:  -> eng
  country:  -> JP
  albumtype:  -> EP
```

If I do verbose, I get a bunch of the following in addition to the cruft from above.

```
skipping C:\Users\me\Music\A-D\BRIEF & TRUNKS\[2000] Buritora Golden Best\09. Pechapai.mp3 because mtime is up to date (1531823365.0)
```

### Setup

* OS: Win7x64
* Python version: 2.7.14
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): N/A

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    fallback: ''
    sources: lyricwiki musixmatch genius google
    google_API_key: REDACTED
    force: no
    genius_api_key: REDACTED
    google_engine_ID: REDACTED
    bing_lang_to:
    bing_client_secret: REDACTED
    local: no
verbose: 0
asciify_paths: no
max_filename_length: 0
library: beets_musiclibrary.db

replace:
    '[\\/]': "\u2215"
    ^\.: _
    \.$: _
    '[\x00-\x1f]': _
    '[<>"\*\|]': _
    \s+$: ''
    ^\s+: ''
    '[\?]': "\uFF1F"
    '[\*]': "\u2736"
    '[\.]{3}$': "\u2026"
    '[\:]': "\u0589"
original_date: no
ftintitle:
    auto: yes
    format: feat. {0}
    drop: no

clutter:
- Thumbs.DB
- .DS_Store
- '*.m3u'
- '*.html'
- '*.htm'
copyartifacts:
    extensions: .cue .log .jpg .png
    print_ignored: yes

plugins:
- fromfilename
- vgmdb3
- edit
- embedart
- fetchart
- ftintitle
- lastgenre
- lyrics
- metasync
- scrub
- mbsync
- bucket
- inline
- the
- badfiles
- copyartifacts
- duplicates
- info
- missing
ignore_hidden: yes

paths:
    default: '%bucket{%upper{%left{%the{$albumartist},1}}}/%the{$albumartist}/[%if{$year,$year,0000}] $album %aunique{}/%if{$multidisc,Disc $disc/$disc-}$track. $title'
    albumtype_soundtrack: _Soundtracks/%ifdef{$grouped, %the{$fandom}}/[%if{$year,$year,0000}] $album %aunique{}/%if{$multidisc,Disc $disc/$disc-}$track. $title
    comp: _Compilations/%ifdef{$grouped, %the{$fandom}}/[%if{$year,$year,0000}] $album %aunique{}/%if{$multidisc,Disc $disc/$disc-}$track. $title
    singleton: _NoAlbum/%the{$artist}/$title
    ext:log: $albumpath/Extras/$artist - %asciify{$album}
    ext:cue: $albumpath/Extras/$artist - %asciify{$album}
    ext:jpg: $albumpath/Extras/albumart_%asciify{$album}
    ext:png: $albumpath/Extras/albumart_%asciify{$album}

format_item: $artist - $album - $title
sort_case_insensitive: yes
art_filename: '%asciify{albumart_$album}'
missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no
    album: no
format_album: $albumartist - $album
lastgenre:
    auto: yes
    force: no
    source: album
    count: 1
    prefer_specific: no
    min_weight: 10
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
path_sep_replace: _

import:
    log: ~/beets-import.log
    write: yes
    copy: yes
    group_albums: yes
    pretend: no
    search_ids: []
    duplicate_action: ask
    bell: yes
    set_fields: {}
    autotag: yes
    timid: yes
    resume: ask
    incremental: no
    incremental_skip_later: no
    quiet_fallback: skip
    none_rec_action: ask
    default_action: apply
    singletons: no
    languages: []
    detail: no
    flat: no

sort_album: albumartist+ album+

match:
    strong_rec_thresh: 0.04
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    required: []
    track_length_grace: 10
    track_length_max: 30
scrub:
    auto: no
artist_credit: no
fetchart:
    auto: yes
    minwidth: 500
    maxwidth: 2000
    cautious: yes
    cover_names: cover folder album albumart front cvr
    sources: filesystem coverart amazon itunes albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
embedart:
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    maxwidth: 0
time_format: '%Y-%m-%d %H:%M:%S'
pluginpath: [~\AppData\Roaming\beets\beetsplug]
item_fields:
    multidisc: 1 if disctotal > 1 else 0
    fandom: "if grouping != '':\n    return grouping\n"
sort_item: artist+ album+ disc+ track+
threaded: yes
va_name: Various Artists
per_disc_numbering: yes
id3v23: yes
bucket:
    bucket_alpha:
    - 0-9
    - A-D
    - E-H
    - I-L
    - M-P
    - Q-U
    - V-Z
    bucket_year: []
    extrapolate: no
    bucket_alpha_regex: {}
ignore:
- .*
- '*~'
- System Volume Information
- lost+found
- .DS_Store
- desktop.ini
- AlbumArtSmall.jpg
- AlbumArt_*_Small.jpg
album_fields:
    grouped: 1 if genre in ("Anime Soundtrack", "Soundtrack") or albumtype == 'soundtrack' else 0

ui:
    terminal_width: 80
    length_diff_thresh: 10.0
    color: yes
timeout: 5.0
directory: ~/Music
format_raw_length: no
terminal_encoding: UTF-8
the:
    a: yes
    patterns: []
    the: yes
    strip: no
    format: '{0}, {1}'
vgmdb3:
    lang-priority: en, ja-latn
    source_weight: 1.0
pathfields: {}
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
```

I've been reading the docs pretty much on a daily basis, but it hasn't been helpful in my issue.
