### ISSUE TITLE
FtInTitle doesn't always detect feats

### ISSUE THREAD

**Issue by Kxze** [beetbox/beets#2990]
### Problem

(Describe your problem, feature request, or discussion topic here. If you're reporting a bug, please fill out this and the "Setup" section below. Otherwise, you can delete them.)

Running this command in verbose (`-vv`) mode:

```sh
➜  SMLoadr git:(master) ✗ beet ls | grep "Charli XCX"
Charli XCX feat. Carly Rae Jepsen - Pop 2 - Backseat
➜  SMLoadr git:(master) ✗ beet -vv ftintitle "artist:Charli XCX feat. Carly Rae Jepsen"
user configuration: /home/rodrigo/.config/beets/config.yaml
data directory: /home/rodrigo/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/rodrigo/data/musiclibrary.db
library directory: /home/rodrigo/drive/Music
Sending event: library_opened
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: cli_exit
➜  SMLoadr git:(master) ✗ beet ls | grep "Charli XCX"
Charli XCX feat. Carly Rae Jepsen - Pop 2 - Backseat
```

### Setup

* OS: Linux (Debian Buster)
* Python version: 3.6.6
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/drive/Music
library: ~/data/musiclibrary.db

import:
    move: yes

plugins: ftintitle fromfilename web duplicates edit acousticbrainz lastimport embedart fetchart artiststofeat
ftintitle:
    format: (feat. {0})
    auto: yes
    drop: no
lastfm:
    user: xKazeSenoue
    api_key: REDACTED
embedart:
    remove_art_file: yes
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
convert:
    auto: yes
    max_bitrate: 256
    never_convert_lossy_files: yes
    dest: /home/rodrigo/drive/Music_Lossy
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
acousticbrainz:
    auto: yes
    force: no
    tags: []
lastimport:
    per_page: 500
    retry_limit: 3
```
