### ISSUE TITLE
`original_date` not working

### ISSUE THREAD

**Issue by dgrisham** [beetbox/beets#2992]
### Problem

(Describe your problem, feature request, or discussion topic here. If you're reporting a bug, please fill out this and the "Setup" section below. Otherwise, you can delete them.)

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import 1974_05-kimono_my_house
```

Gives this output:

```sh
user configuration: /home/grish/dotfiles/beets/config.yaml
data directory: /home/grish/dotfiles/beets
plugin paths: 
Sending event: pluginload
inline: adding item field album_custom
inline: adding item field track_custom
library database: /home/grish/dotfiles/beets/library.blb
library directory: /home/grish/media/music/library
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/grish/media/music/library/sparks/1974_05-kimono_my_house
Tagging Sparks - Kimono My House
Searching for discovered album ID: d148e3fc-5a54-437a-b7d7-25ecc7c060aa
Requesting MusicBrainz release d148e3fc-5a54-437a-b7d7-25ecc7c060aa
primary MB release type: album
Sending event: albuminfo_received
Candidate: Sparks - Kimono My House (d148e3fc-5a54-437a-b7d7-25ecc7c060aa)
Computing track assignment...
...done.
Success. Distance: 0.00
Album ID match recommendation is Recommendation.strong
ID match.

/home/grish/media/music/library/sparks/1974_05-kimono_my_house (12 items)
Sending event: before_choose_candidate
Tagging:
    Sparks - Kimono My House
URL:
    https://musicbrainz.org/release/d148e3fc-5a54-437a-b7d7-25ecc7c060aa
(Similarity: 100.0%) (CD, 1994, GB, Island Masters)
 * This Town Ain't Big Enough for Both of Us
 * Amateur Hour
 * Falling in Love With Myself Again
 * Here in Heaven
 * Thank God It's Not Christmas
 * Hasta Mañana Monsieur
 * Talent Is an Asset
 * Complaints
 * In My Family
 * Equator
 * Barbecutie
 * Lost and Found
Sending event: import_task_choice
Sending event: import_task_apply
Replacing item 548: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_01-this_town_aint_big_enough_for_both_of_us.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 549: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_02-amateur_hour.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 550: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_03-falling_in_love_with_myself_again.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 551: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_04-here_in_heaven.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 552: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_05-thank_god_its_not_christmas.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 553: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_06-hasta_mañana_monsieur.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 554: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_07-talent_is_an_asset.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 555: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_08-complaints.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 556: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_09-in_my_family.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 557: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_10-equator.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 558: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_11-barbecutie.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 559: /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_12-lost_and_found.mp3
Sending event: database_change
Sending event: database_change
Sending event: item_removed
12 of 12 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Reimported album: added 1532644213.3186693, flexible attributes dict_keys([]) from album 43 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house
Reimported item added 1532644213.319688 from item 548 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_01-this_town_aint_big_enough_for_both_of_us.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 548 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_01-this_town_aint_big_enough_for_both_of_us.mp3
Sending event: database_change
Reimported item added 1532644213.3209202 from item 549 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_02-amateur_hour.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 549 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_02-amateur_hour.mp3
Sending event: database_change
Reimported item added 1532644213.3225513 from item 550 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_03-falling_in_love_with_myself_again.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 550 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_03-falling_in_love_with_myself_again.mp3
Sending event: database_change
Reimported item added 1532644213.3238232 from item 551 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_04-here_in_heaven.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 551 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_04-here_in_heaven.mp3
Sending event: database_change
Reimported item added 1532644213.325041 from item 552 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_05-thank_god_its_not_christmas.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 552 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_05-thank_god_its_not_christmas.mp3
Sending event: database_change
Reimported item added 1532644213.3262398 from item 553 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_06-hasta_mañana_monsieur.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 553 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_06-hasta_mañana_monsieur.mp3
Sending event: database_change
Reimported item added 1532644213.3274348 from item 554 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_07-talent_is_an_asset.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 554 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_07-talent_is_an_asset.mp3
Sending event: database_change
Reimported item added 1532644213.328603 from item 555 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_08-complaints.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 555 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_08-complaints.mp3
Sending event: database_change
Reimported item added 1532644213.3297563 from item 556 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_09-in_my_family.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 556 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_09-in_my_family.mp3
Sending event: database_change
Reimported item added 1532644213.330921 from item 557 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_10-equator.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 557 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_10-equator.mp3
Sending event: database_change
Reimported item added 1532644213.3320813 from item 558 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_11-barbecutie.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 558 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_11-barbecutie.mp3
Sending event: database_change
Reimported item added 1532644213.3332589 from item 559 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_12-lost_and_found.mp3
Reimported item flexible attributes dict_keys(['data_source', 'track_alt']) from item 559 for /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_12-lost_and_found.mp3
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
lastgenre: added last.fm album genre (album): Glam Rock
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_01-this_town_aint_big_enough_for_both_of_us.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_02-amateur_hour.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_03-falling_in_love_with_myself_again.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_04-here_in_heaven.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_05-thank_god_its_not_christmas.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_06-hasta_mañana_monsieur.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_07-talent_is_an_asset.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_08-complaints.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_09-in_my_family.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_10-equator.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_11-barbecutie.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/grish/media/music/library/sparks/1974_05-kimono_my_house/1_12-lost_and_found.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
Sending event: album_imported
Sending event: import
Sending event: cli_exit
```

The problem: The year set in the resulting id3 metadata is `1994`. However, the `original_year` (as shown in the folder name above) is `1974`. I have `original_date` set to `yes`, so the expected behavior is that the `year` value in the metadata is also set to `1974`. Note that I manually set the year shown in the folder name to `original_year`, but if I use `year` instead then I get `1994`. So the issue seems to be with `original_date`.

### Setup

* OS: Arch
* Python version: 3.6.6
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
library: /home/grish/dotfiles/beets/library.blb
directory: /home/grish/media/music/library/

import:
    write: yes
    copy: no
    move: yes
    incremental: no
    timid: no
    detail: yes
    per_disc_numbering: yes
    asciify_paths: yes
    original_date: yes
    threaded: yes

ui:
    color: yes

match:
    ignored: missing_tracks unmatched_tracks
    preferred:
        media: [CD, Digital Media|File]
item_fields:
    album_custom: 'prefix = u''0'' if original_month < 10 else u''''

        smart_month = u'''' if (month == ''00'') else u''_{p}{m}''.format(p=prefix, m=original_month)

        return u''{y}{m}-{al}''.format(y=original_year, m=smart_month, al=album.lower())

        '
    track_custom: 'prefix = u''0'' if track < 10 else u''''

        smart_track = u''{p}{tr}''.format(p=prefix, tr=track)

        return u''{d}_{tr}-{ti}''.format(d=disc, tr=smart_track, ti=title.lower())

        '

paths:
    default: '%lower{$albumartist}/$album_custom/$track_custom'
    singleton: '%lower{$albumartist}/$album_custom/$track_custom'
    comp: etc/compilations/$album_custom/$track_custom
    albumtype:soundtrack: etc/soundtracks/$album_custom/$track_custom

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\[\]()&,]': ''
    \.$: _
    \s+$: ''
    '[''!.]': ''
    ^\s+: ''
    '[\s_]{2,}': _
    \s: _

plugins: inline fetchart scrub lastgenre ftintitle play
fetchart:
    minwidth: 600
    sources: coverart itunes amazon albumart google wikipedia
    auto: yes
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
ftintitle:
    format: (feat. {0})
    auto: yes
    drop: no
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
play:
    command:
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
scrub:
    auto: yes
pathfields: {}
album_fields: {}
```
