### ISSUE TITLE
Provide a way to copy from the library without changing the path

### ISSUE THREAD

**Issue by Linkandzelda** [beetbox/beets#2993]
### Problem

I wanted to get all files matching "search term" onto a thumb drive. 
So I did:
    beet move -c -d /my/thumb/drive search term

The docs state "The -c option copies files instead of moving them". 

The problem was, it updated the paths of the beets library to the new location on the thumb drive which I did not want. I assumed since I was only copying and not moving that the library paths would remain at the old directory.

### Setup

* OS: OSX
* Python version: 2.7.15
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): Did no try since its related to built in commands

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/MP3/beets
library: ~/Music/beetslibrary.blb
import:
  move: no
  copy: yes
plugins: bandcamp chroma lastgenre fromfilename lyrics fetchart ftintitle mpdupdate smartplaylist random embedart edit web
embedart:
  auto: yes
paths:
  default: $artist/$album%aunique{}/$track $title
  singleton: $artist/$title
  comp: Various Artists/$album%aunique{}/$track $title
mpdupdate:
  host: localhost
  port: 6600
bandcamp:
  lyrics: true
  art: true

```
