### ISSUE TITLE
Beets can't remove some metadata

### ISSUE THREAD

**Issue by turlando** [beetbox/beets#2999]
I'm using the Zero plugin to remove some fields from my tracks.

This is my configuration:

```yaml
---
directory: ~/Music
library: ~/Music/library.db

paths:
  default: $grouping/$albumartist/$original_year - $catalognum - $album/$disc_and_track - $title
  comp: $grouping/Various Artists/$original_year - $catalognum - $album/$disc_and_track - $title

import:
  move: no
  copy: yes

plugins: discogs edit ftintitle zero inline

edit:
  itemfields: >-
    acoustid_fingerprint acoustid_id
    added album albumartist
    albumartist_credit albumartist_sort
    albumdisambig albumstatus albumtype
    arranger artist artist_credit
    artist_sort asin bitdepth bitrate
    bpm catalognum channels comments
    comp composer composer_sort country
    day disc disctitle disctotal encoder
    filesize format genre grouping id
    initial_key label language length
    lyricist lyrics mb_albumartistid
    mb_albumid mb_artistid mb_releasegroupid
    mb_releasetrackid mb_trackid media
    month mtime original_day original_month
    original_year r128_album_gain
    r128_track_gain rg_album_gain rg_album_peak
    rg_track_gain rg_track_peak samplerate
    script singleton title track tracktotal
    year
  albumfields: >-
    added album albumartist albumartist_credit
    albumartist_sort albumdisambig albumstatus
    albumtotal albumtype artpath asin catalognum
    comp country day disctotal genre label
    language mb_albumartistid mb_albumid
    mb_releasegroupid month original_day
    original_month original_year path
    r128_album_gain rg_album_gain rg_album_peak
    script year

ftintitle:
  auto: yes
  format: ; {0}

zero:
  auto: yes
  fields: >-
    acoustid_fingerprint acoustid_id
    albumartist_credit albumartist_sort
    artist_credit artist_sort arranger
    asin comments composer composer_sort
    language lyricist
    mb_albumartistid mb_albumid
    mb_releasegroupid
    r128_album_gain r128_track_gain
    rg_album_gain rg_album_peak
    rg_track_gain rg_track_peak
    r128_album_gain
    rg_album_gain rg_album_peak
    script images
  update_database: true

item_fields:
  disc_and_track: >-
    "{0:01d}-{0:02d}".format(disc, track)
    if disctotal > 1
    else "{0:2d}".format(track)
```

The problem is that after I import a new album I can still see (with beet edit -a) some of the unwanted tags.

```
% beet -vv import -t Doc\ Scott\ -\ Drumz\ \'95\ \(Nasty\ Habits\ Remix\)\ _\ Blue\ Skies\ \(2015\ Remasters\)
user configuration: /home/me/.config/beets/config.yaml
data directory: /home/me/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field disc_and_track
library database: /home/me/Music/library.db
library directory: /home/me/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/me/Downloads/Doc Scott - Drumz '95 (Nasty Habits Remix) _ Blue Skies (2015 Remasters)
Tagging undefined - Drumz '95 (Nasty Habits Remix) / Blue Skies (2015 Remasters)
No album ID found.
Search terms: undefined - Drumz '95 (Nasty Habits Remix) / Blue Skies (2015 Remasters)
Album might be VA: False
Searching for MusicBrainz releases with: {'release': "drumz '95 (nasty habits remix) / blue skies (2015 remasters)", 'artist': 'undefined', 'tracks': '2'}
Requesting MusicBrainz release 490d0fe3-766d-439a-8ed5-2b2b9da2f27e
primary MB release type: single
Sending event: albuminfo_received
Candidate: Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters) (490d0fe3-766d-439a-8ed5-2b2b9da2f27e)
Computing track assignment...
...done.
Success. Distance: 0.27
Requesting MusicBrainz release b8099a00-20d6-4a0a-a4ff-1e3ef5c60ec8
primary MB release type: single
Sending event: albuminfo_received
Candidate: Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (b8099a00-20d6-4a0a-a4ff-1e3ef5c60ec8)
Computing track assignment...
...done.
Success. Distance: 0.37
Requesting MusicBrainz release 7c2aec74-7631-4759-9ea7-a5d4cc9477a0
primary MB release type: ep
Sending event: albuminfo_received
Candidate: The Wild Ones - Nasty Habits (7c2aec74-7631-4759-9ea7-a5d4cc9477a0)
Computing track assignment...
...done.
Success. Distance: 0.73
Requesting MusicBrainz release c9f6ec79-c4e6-41e1-ab8a-9ef8cbaaa5ea
primary MB release type: single
Sending event: albuminfo_received
Candidate: Special Needs - Blue Skies (c9f6ec79-c4e6-41e1-ab8a-9ef8cbaaa5ea)
Computing track assignment...
...done.
Success. Distance: 0.62
Requesting MusicBrainz release 43320bd1-0345-4753-957d-54310826144d
primary MB release type: single
Sending event: albuminfo_received
Candidate: Special Needs - Blue Skies (43320bd1-0345-4753-957d-54310826144d)
Computing track assignment...
...done.
Success. Distance: 0.62
Evaluating 5 candidates.

/home/me/Downloads/Doc Scott - Drumz '95 (Nasty Habits Remix) _ Blue Skies (2015 Remasters) (2 items)
Sending event: before_choose_candidate
Finding tags for album "undefined - Drumz '95 (Nasty Habits Remix) / Blue Skies (2015 Remasters)".
Candidates:
1. Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters) (72.7%) (artist, tracks) (Digital Media, 2015, GB, Metalheadz)
2. Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (63.3%) (artist, year, tracks, ...) (12" Vinyl, 1995, GB, Metalheadz)
3. Special Needs - Blue Skies (38.2%) (tracks, artist, album, ...) (2005, GB)
4. Special Needs - Blue Skies (38.2%) (tracks, artist, album, ...) (7" Vinyl, 2005, GB, Mercury Records)
5. The Wild Ones - Nasty Habits (26.8%) (missing tracks, tracks, album, ...) (Digital Media, 2013, XW)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 1
Correcting tags from:
    undefined - Drumz '95 (Nasty Habits Remix) / Blue Skies (2015 Remasters)
To:
    Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters)
URL:
    https://musicbrainz.org/release/490d0fe3-766d-439a-8ed5-2b2b9da2f27e
(Similarity: 72.7%) (artist, tracks) (Digital Media, 2015, GB, Metalheadz)
 * Drumz '95 (Nasty Habits Remix) (2015 Remaster) -> Drumz '95 (Nasty Habits remix) (title)
 * Blue Skies (2015 Remaster)                     -> Blue Skies (title)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? a
Sending event: import_task_choice
found duplicates: [22]
default action for duplicates: a
This album is already in the library!
Old: 2 items, FLAC, 1012kbps, 18:08, 131.6 MiB
New: 2 items, FLAC, 1012kbps, 18:08, 131.6 MiB
[S]kip new, Keep both, Remove old, Merge all? r
Sending event: import_task_apply
0 of 2 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
removing 2 old duplicated items
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/me/Music/_/Doc Scott/1995 - METH015 - Drumz '95 (Nasty Habits remix) _ Blue Skies (2015 Remasters)/1 - Drumz '95 (Nasty Habits remix).flac
Sending event: database_change
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/me/Music/_/Doc Scott/1995 - METH015 - Drumz '95 (Nasty Habits remix) _ Blue Skies (2015 Remasters)/2 - Blue Skies.flac
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
zero: acoustid_fingerprint:  -> None
zero: acoustid_id:  -> None
zero: albumartist_credit: Doc Scott -> None
zero: albumartist_sort: Scott, Doc -> None
zero: artist_credit: Doc Scott -> None
zero: artist_sort: Scott, Doc -> None
zero: arranger:  -> None
zero: asin:  -> None
zero: comments:  -> None
zero: composer:  -> None
zero: composer_sort:  -> None
zero: language: eng -> None
zero: lyricist:  -> None
zero: mb_albumartistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb -> None
zero: mb_albumid: 490d0fe3-766d-439a-8ed5-2b2b9da2f27e -> None
zero: mb_releasegroupid: 71feb820-81a3-3478-8447-9e785de39d70 -> None
zero: r128_album_gain: 0 -> None
zero: r128_track_gain: 0 -> None
zero: rg_album_gain: None -> None
zero: rg_album_peak: None -> None
zero: rg_track_gain: None -> None
zero: rg_track_peak: None -> None
zero: script: Latn -> None
zero: images:  -> None
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
zero: acoustid_fingerprint:  -> None
zero: acoustid_id:  -> None
zero: albumartist_credit: Doc Scott -> None
zero: albumartist_sort: Scott, Doc -> None
zero: artist_credit: Doc Scott -> None
zero: artist_sort: Scott, Doc -> None
zero: arranger:  -> None
zero: asin:  -> None
zero: comments:  -> None
zero: composer:  -> None
zero: composer_sort:  -> None
zero: language: eng -> None
zero: lyricist:  -> None
zero: mb_albumartistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb -> None
zero: mb_albumid: 490d0fe3-766d-439a-8ed5-2b2b9da2f27e -> None
zero: mb_releasegroupid: 71feb820-81a3-3478-8447-9e785de39d70 -> None
zero: r128_album_gain: 0 -> None
zero: r128_track_gain: 0 -> None
zero: rg_album_gain: None -> None
zero: rg_album_peak: None -> None
zero: rg_track_gain: None -> None
zero: rg_track_peak: None -> None
zero: script: Latn -> None
zero: images:  -> None
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: album_imported
Sending event: import
Sending event: cli_exit
```

This is the output of beet edit:

```yaml
added: 1533831083.477021
album: Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters)
albumartist: Doc Scott
albumartist_credit: Doc Scott
albumartist_sort: Scott, Doc
albumdisambig: ''
albumstatus: Official
albumtype: single
artpath: None
asin: ''
catalognum: METH015
comp: 'False'
country: GB
day: 23
disctotal: 1
genre: ''
id: 23
label: Metalheadz
language: eng
mb_albumartistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb
mb_albumid: 490d0fe3-766d-439a-8ed5-2b2b9da2f27e
mb_releasegroupid: 71feb820-81a3-3478-8447-9e785de39d70
month: 10
original_day: 0
original_month: 0
original_year: 1995
r128_album_gain: 0
rg_album_gain: '0.0'
rg_album_peak: '0.0'
script: Latn
year: 2015
```

As you can see the Zero plugin is claiming to be removing fields such as mb_albumartistid, but after mangling the track the tag is still there.

I also tried to write my own plugin and I ran in the same behavior, here is the code:

```python
from beets.plugins import BeetsPlugin


FIELDS_TO_STRIP = """acoustid_fingerprint acoustid_id
albumartist_credit albumartist_sort
artist_credit artist_sort arranger
asin comments composer composer_sort
language lyricist
mb_albumartistid mb_albumid
mb_releasegroupid
r128_album_gain r128_track_gain
rg_album_gain rg_album_peak
rg_track_gain rg_track_peak
r128_album_gain
rg_album_gain rg_album_peak
script images""".split()


class StripPlugin(BeetsPlugin):
    def __init__(self):
        super(StripPlugin, self).__init__()
        self.register_listener('pluginload', self.hello)
        self.register_listener('write', self.write_event_handler)

    def hello(self):
        self._log.debug('Plugin loaded')

    def write_event_handler(self, item, path, tags):
        self._log.debug('Stripping')
        new_tags = {k: v for k, v in tags.items()
                    if k not in FIELDS_TO_STRIP}
        return new_tags
```

Could it be a bug in MediaFile not correctly mapping `mb_albumartistid` (beets field) -> `musicbrainz_albumartistid` (actual VorbisComment tag)?

I'm using beets 1.4.7 with Python 3.7.0 on Linux x64.

---

Two small unrelated rants:

1. Looking at the documentation it is not clear at all that you have to return the tags dictionary when handling `write` events. It is also not clear that the `after_write` handler needs two parameters (item and path) and not just the item.
2. I've been lurking in your IRC channel for a day and it's getting spammed/flooded and nobody noticed that.

**Comment by sampsyo** [comment]
Hmm—it looks to me like zero is not working at all for you, right? For example, the `script` field is supposed to be nullified, but it still contains `Latn`. Same with `albumartist_credit` and `albumartist_sort`.

I don't have an immediate explanation for why that would be. Does it work if you run `beet zero` manually?

**Comment by turlando** [comment]
> Hmm—it looks to me like zero is not working at all for you, right?
Yep, correct.

> Does it work if you run beet zero manually?
Nope, it doesn't.

**Comment by turlando** [comment]
```
% beet -vv import -t Doc\ Scott\ -\ Drumz\ \'95\ \(Nasty\ Habits\ Remix\)\ _\ Blue\ Skies\ \(2015\ Remasters\)
user configuration: /home/me/.config/beets/config.yaml
data directory: /home/me/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field disc_and_track
library database: /home/me/Music/library.db
library directory: /home/me/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/me/Downloads/Doc Scott - Drumz '95 (Nasty Habits Remix) _ Blue Skies (2015 Remasters)
Tagging undefined - Drumz '95 (Nasty Habits Remix) / Blue Skies (2015 Remasters)
No album ID found.
Search terms: undefined - Drumz '95 (Nasty Habits Remix) / Blue Skies (2015 Remasters)
Album might be VA: False
Searching for MusicBrainz releases with: {'release': "drumz '95 (nasty habits remix) / blue skies (2015 remasters)", 'artist': 'undefined', 'tracks': '2'}
Requesting MusicBrainz release 490d0fe3-766d-439a-8ed5-2b2b9da2f27e
primary MB release type: single
Sending event: albuminfo_received
Candidate: Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters) (490d0fe3-766d-439a-8ed5-2b2b9da2f27e)
Computing track assignment...
...done.
Success. Distance: 0.27
Requesting MusicBrainz release b8099a00-20d6-4a0a-a4ff-1e3ef5c60ec8
primary MB release type: single
Sending event: albuminfo_received
Candidate: Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (b8099a00-20d6-4a0a-a4ff-1e3ef5c60ec8)
Computing track assignment...
...done.
Success. Distance: 0.37
Requesting MusicBrainz release 7c2aec74-7631-4759-9ea7-a5d4cc9477a0
primary MB release type: ep
Sending event: albuminfo_received
Candidate: The Wild Ones - Nasty Habits (7c2aec74-7631-4759-9ea7-a5d4cc9477a0)
Computing track assignment...
...done.
Success. Distance: 0.73
Requesting MusicBrainz release 43320bd1-0345-4753-957d-54310826144d
primary MB release type: single
Sending event: albuminfo_received
Candidate: Special Needs - Blue Skies (43320bd1-0345-4753-957d-54310826144d)
Computing track assignment...
...done.
Success. Distance: 0.62
Requesting MusicBrainz release c9f6ec79-c4e6-41e1-ab8a-9ef8cbaaa5ea
primary MB release type: single
Sending event: albuminfo_received
Candidate: Special Needs - Blue Skies (c9f6ec79-c4e6-41e1-ab8a-9ef8cbaaa5ea)
Computing track assignment...
...done.
Success. Distance: 0.62
Evaluating 5 candidates.

/home/me/Downloads/Doc Scott - Drumz '95 (Nasty Habits Remix) _ Blue Skies (2015 Remasters) (2 items)
Sending event: before_choose_candidate
Finding tags for album "undefined - Drumz '95 (Nasty Habits Remix) / Blue Skies (2015 Remasters)".
Candidates:
1. Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters) (72.7%) (artist, tracks) (Digital Media, 2015, GB, Metalheadz)
2. Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (63.3%) (artist, year, tracks, ...) (12" Vinyl, 1995, GB, Metalheadz)
3. Special Needs - Blue Skies (38.2%) (tracks, artist, album, ...) (7" Vinyl, 2005, GB, Mercury Records)
4. Special Needs - Blue Skies (38.2%) (tracks, artist, album, ...) (2005, GB)
5. The Wild Ones - Nasty Habits (26.8%) (missing tracks, tracks, album, ...) (Digital Media, 2013, XW)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 1
Correcting tags from:
    undefined - Drumz '95 (Nasty Habits Remix) / Blue Skies (2015 Remasters)
To:
    Doc Scott - Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters)
URL:
    https://musicbrainz.org/release/490d0fe3-766d-439a-8ed5-2b2b9da2f27e
(Similarity: 72.7%) (artist, tracks) (Digital Media, 2015, GB, Metalheadz)
 * Drumz '95 (Nasty Habits Remix) (2015 Remaster) ->
   Drumz '95 (Nasty Habits remix) (title)
 * Blue Skies (2015 Remaster) ->
   Blue Skies (title)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? a
Sending event: import_task_choice
Sending event: import_task_apply
0 of 2 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
zero: acoustid_fingerprint:  -> None
zero: acoustid_id:  -> None
zero: albumartist_credit: Doc Scott -> None
zero: albumartist_sort: Scott, Doc -> None
zero: artist_credit: Doc Scott -> None
zero: artist_sort: Scott, Doc -> None
zero: arranger:  -> None
zero: asin:  -> None
zero: comments:  -> None
zero: composer:  -> None
zero: composer_sort:  -> None
zero: language: eng -> None
zero: lyricist:  -> None
zero: mb_albumartistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb -> None
zero: mb_albumid: 490d0fe3-766d-439a-8ed5-2b2b9da2f27e -> None
zero: mb_releasegroupid: 71feb820-81a3-3478-8447-9e785de39d70 -> None
zero: r128_album_gain: 0 -> None
zero: r128_track_gain: 0 -> None
zero: rg_album_gain: None -> None
zero: rg_album_peak: None -> None
zero: rg_track_gain: None -> None
zero: rg_track_peak: None -> None
zero: script: Latn -> None
zero: images:  -> None
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
zero: acoustid_fingerprint:  -> None
zero: acoustid_id:  -> None
zero: albumartist_credit: Doc Scott -> None
zero: albumartist_sort: Scott, Doc -> None
zero: artist_credit: Doc Scott -> None
zero: artist_sort: Scott, Doc -> None
zero: arranger:  -> None
zero: asin:  -> None
zero: comments:  -> None
zero: composer:  -> None
zero: composer_sort:  -> None
zero: language: eng -> None
zero: lyricist:  -> None
zero: mb_albumartistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb -> None
zero: mb_albumid: 490d0fe3-766d-439a-8ed5-2b2b9da2f27e -> None
zero: mb_releasegroupid: 71feb820-81a3-3478-8447-9e785de39d70 -> None
zero: r128_album_gain: 0 -> None
zero: r128_track_gain: 0 -> None
zero: rg_album_gain: None -> None
zero: rg_album_peak: None -> None
zero: rg_track_gain: None -> None
zero: rg_track_peak: None -> None
zero: script: Latn -> None
zero: images:  -> None
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: album_imported
Sending event: import
Sending event: cli_exit
```

```
% beet info blue
/home/me/Music/_/Doc Scott/1995 - METH015 - Drumz '95 (Nasty Habits remix) _ Blue Skies (2015 Remasters)/1 - Drumz '95 (Nasty Habits remix).flac
            album: Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters)
      albumartist: Doc Scott
    albumdisambig: 
      albumstatus: Official
        albumtype: single
              art: False
           artist: Doc Scott
         bitdepth: 16
          bitrate: 1044956
              bpm: 0
       catalognum: METH015
         channels: 2
             comp: False
          country: GB
             date: 2015-10-23
              day: 23
             disc: 1
        disctitle: 
        disctotal: 1
          encoder: 
           format: FLAC
            genre: 
           genres: 
         grouping: 
            label: Metalheadz
           length: 538.5218594104308
           lyrics: 
      mb_artistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb
mb_releasetrackid: 7d688110-303d-4ccd-af4a-adf2afeaf0e9
       mb_trackid: 070dbce9-7c40-48b3-a030-ebccdcec8b48
            media: Digital Media
            month: 10
    original_date: 1995-01-01
    original_year: 1995
       samplerate: 44100
            title: Drumz '95 (Nasty Habits remix)
            track: 1
       tracktotal: 2
             year: 2015

/home/me/Music/_/Doc Scott/1995 - METH015 - Drumz '95 (Nasty Habits remix) _ Blue Skies (2015 Remasters)/2 - Blue Skies.flac
            album: Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters)
      albumartist: Doc Scott
    albumdisambig: 
      albumstatus: Official
        albumtype: single
              art: False
           artist: Doc Scott
         bitdepth: 16
          bitrate: 980141
              bpm: 0
       catalognum: METH015
         channels: 2
             comp: False
          country: GB
             date: 2015-10-23
              day: 23
             disc: 1
        disctitle: 
        disctotal: 1
          encoder: 
           format: FLAC
            genre: 
           genres: 
         grouping: 
            label: Metalheadz
           length: 550.22
           lyrics: 
      mb_artistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb
mb_releasetrackid: f994132c-4f94-4225-abcc-6fb103f9781b
       mb_trackid: fd7cc2e2-5407-4d2b-afda-f7f61dec2e3a
            media: Digital Media
            month: 10
    original_date: 1995-01-01
    original_year: 1995
       samplerate: 44100
            title: Blue Skies
            track: 2
       tracktotal: 2
             year: 2015
```

```
% beet -vv zero
user configuration: /home/me/.config/beets/config.yaml
data directory: /home/me/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field disc_and_track
library database: /home/me/Music/library.db
library directory: /home/me/Music
Sending event: library_opened
Remove fields for all items? (Y/n) y
zero: acoustid_fingerprint:  -> None
zero: acoustid_id:  -> None
zero: albumartist_credit:  -> None
zero: albumartist_sort:  -> None
zero: artist_credit:  -> None
zero: artist_sort:  -> None
zero: arranger:  -> None
zero: asin:  -> None
zero: comments:  -> None
zero: composer:  -> None
zero: composer_sort:  -> None
zero: language:  -> None
zero: lyricist:  -> None
zero: mb_albumartistid:  -> None
zero: mb_albumid:  -> None
zero: mb_releasegroupid:  -> None
zero: r128_album_gain: 0 -> None
zero: r128_track_gain: 0 -> None
zero: rg_album_gain: None -> None
zero: rg_album_peak: None -> None
zero: rg_track_gain: None -> None
zero: rg_track_peak: None -> None
zero: script:  -> None
zero: images:  -> None
Sending event: write
zero: acoustid_fingerprint: None -> None
zero: acoustid_id: None -> None
zero: albumartist_credit: None -> None
zero: albumartist_sort: None -> None
zero: artist_credit: None -> None
zero: artist_sort: None -> None
zero: arranger: None -> None
zero: asin: None -> None
zero: comments: None -> None
zero: composer: None -> None
zero: composer_sort: None -> None
zero: language: None -> None
zero: lyricist: None -> None
zero: mb_albumartistid: None -> None
zero: mb_albumid: None -> None
zero: mb_releasegroupid: None -> None
zero: r128_album_gain: None -> None
zero: r128_track_gain: None -> None
zero: rg_album_gain: None -> None
zero: rg_album_peak: None -> None
zero: rg_track_gain: None -> None
zero: rg_track_peak: None -> None
zero: script: None -> None
zero: images: None -> None
Sending event: after_write
Sending event: database_change
zero: acoustid_fingerprint:  -> None
zero: acoustid_id:  -> None
zero: albumartist_credit:  -> None
zero: albumartist_sort:  -> None
zero: artist_credit:  -> None
zero: artist_sort:  -> None
zero: arranger:  -> None
zero: asin:  -> None
zero: comments:  -> None
zero: composer:  -> None
zero: composer_sort:  -> None
zero: language:  -> None
zero: lyricist:  -> None
zero: mb_albumartistid:  -> None
zero: mb_albumid:  -> None
zero: mb_releasegroupid:  -> None
zero: r128_album_gain: 0 -> None
zero: r128_track_gain: 0 -> None
zero: rg_album_gain: None -> None
zero: rg_album_peak: None -> None
zero: rg_track_gain: None -> None
zero: rg_track_peak: None -> None
zero: script:  -> None
zero: images:  -> None
Sending event: write
zero: acoustid_fingerprint: None -> None
zero: acoustid_id: None -> None
zero: albumartist_credit: None -> None
zero: albumartist_sort: None -> None
zero: artist_credit: None -> None
zero: artist_sort: None -> None
zero: arranger: None -> None
zero: asin: None -> None
zero: comments: None -> None
zero: composer: None -> None
zero: composer_sort: None -> None
zero: language: None -> None
zero: lyricist: None -> None
zero: mb_albumartistid: None -> None
zero: mb_albumid: None -> None
zero: mb_releasegroupid: None -> None
zero: r128_album_gain: None -> None
zero: r128_track_gain: None -> None
zero: rg_album_gain: None -> None
zero: rg_album_peak: None -> None
zero: rg_track_gain: None -> None
zero: rg_track_peak: None -> None
zero: script: None -> None
zero: images: None -> None
Sending event: after_write
Sending event: database_change
Sending event: cli_exit
```

```
% beet info blue
/home/me/Music/_/Doc Scott/1995 - METH015 - Drumz '95 (Nasty Habits remix) _ Blue Skies (2015 Remasters)/1 - Drumz '95 (Nasty Habits remix).flac
            album: Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters)
      albumartist: Doc Scott
    albumdisambig: 
      albumstatus: Official
        albumtype: single
              art: False
           artist: Doc Scott
         bitdepth: 16
          bitrate: 1044956
              bpm: 0
       catalognum: METH015
         channels: 2
             comp: False
          country: GB
             date: 2015-10-23
              day: 23
             disc: 1
        disctitle: 
        disctotal: 1
          encoder: 
           format: FLAC
            genre: 
           genres: 
         grouping: 
            label: Metalheadz
           length: 538.5218594104308
           lyrics: 
      mb_artistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb
mb_releasetrackid: 7d688110-303d-4ccd-af4a-adf2afeaf0e9
       mb_trackid: 070dbce9-7c40-48b3-a030-ebccdcec8b48
            media: Digital Media
            month: 10
    original_date: 1995-01-01
    original_year: 1995
       samplerate: 44100
            title: Drumz '95 (Nasty Habits remix)
            track: 1
       tracktotal: 2
             year: 2015

/home/me/Music/_/Doc Scott/1995 - METH015 - Drumz '95 (Nasty Habits remix) _ Blue Skies (2015 Remasters)/2 - Blue Skies.flac
            album: Drumz '95 (Nasty Habits remix) / Blue Skies (2015 Remasters)
      albumartist: Doc Scott
    albumdisambig: 
      albumstatus: Official
        albumtype: single
              art: False
           artist: Doc Scott
         bitdepth: 16
          bitrate: 980141
              bpm: 0
       catalognum: METH015
         channels: 2
             comp: False
          country: GB
             date: 2015-10-23
              day: 23
             disc: 1
        disctitle: 
        disctotal: 1
          encoder: 
           format: FLAC
            genre: 
           genres: 
         grouping: 
            label: Metalheadz
           length: 550.22
           lyrics: 
      mb_artistid: 0c9a96fb-12e7-4ba1-bdc6-c2068c15abeb
mb_releasetrackid: f994132c-4f94-4225-abcc-6fb103f9781b
       mb_trackid: fd7cc2e2-5407-4d2b-afda-f7f61dec2e3a
            media: Digital Media
            month: 10
    original_date: 1995-01-01
    original_year: 1995
       samplerate: 44100
            title: Blue Skies
            track: 2
       tracktotal: 2
             year: 2015
```
