### ISSUE TITLE
Edit plugin exits with "No changes; aborting" immediately

### ISSUE THREAD

**Issue by RodrigoLeiteF** [beetbox/beets#3012]
### Problem

Using the `edit` plugin in the interactive menu by pressing D opens the text editor as expected, but the file is empty and the plugin returns with "No changes; aborting" immediately.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import offline.mp3
user configuration: /home/rodrigo/.config/beets/config.yaml
data directory: /home/rodrigo/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/rodrigo/data/musiclibrary.db
library directory: /home/rodrigo/drive/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/rodrigo/Downloads/XCX Offline + Our Boyfriend/offline xcx.mp3
Tagging Charli XCX - Offline
No album ID found.
Search terms: Charli XCX - Offline
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'offline', 'artist': 'charli xcx', 'tracks': '1'}
Requesting MusicBrainz release 0dd77c9e-bcb9-4c11-a1d4-86460ed6673b
primary MB release type: single
Sending event: albuminfo_received
Candidate: Charli XCX - SuperLove (0dd77c9e-bcb9-4c11-a1d4-86460ed6673b)
Computing track assignment...
...done.
Success. Distance: 0.46
Requesting MusicBrainz release f628b2ce-57bd-47cf-a026-2c26164ff754
primary MB release type: single
Sending event: albuminfo_received
Candidate: Charli XCX - Nuclear Seasons (f628b2ce-57bd-47cf-a026-2c26164ff754)
Computing track assignment...
...done.
Success. Distance: 0.55
Requesting MusicBrainz release f9e11444-2848-4519-9162-6f4d90718676
primary MB release type: single
Sending event: albuminfo_received
Candidate: Charli XCX - After the Afterparty (acoustic) (f9e11444-2848-4519-9162-6f4d90718676)
Computing track assignment...
...done.
Success. Distance: 0.56
Requesting MusicBrainz release 832e04e3-b8f7-4612-b0f6-b3ad0ac29a2f
primary MB release type: single
Sending event: albuminfo_received
Candidate: Charli XCX - Break the Rules (832e04e3-b8f7-4612-b0f6-b3ad0ac29a2f)
Computing track assignment...
...done.
Success. Distance: 0.53
Requesting MusicBrainz release 104d7990-64e9-43dd-aaeb-b948e2b5dd4a
primary MB release type: single
Sending event: albuminfo_received
Candidate: Charli XCX - Boys (Coldabank Remix) (104d7990-64e9-43dd-aaeb-b948e2b5dd4a)
Computing track assignment...
...done.
Success. Distance: 0.53
Evaluating 5 candidates.

/home/rodrigo/Downloads/XCX Offline + Our Boyfriend/offline xcx.mp3 (1 items)
Sending event: before_choose_candidate
Finding tags for album "Charli XCX - Offline".
Candidates:
1. Charli XCX - SuperLove (54.3%) (album, year, tracks) (Digital Media, 2013, GB, Asylum Records)
2. Charli XCX - Boys (Coldabank Remix) (46.9%) (album, tracks, year) (Digital Media, 2017, GB, Asylum Records)
3. Charli XCX - Break the Rules (46.8%) (album, tracks, year) (Digital Media, 2014, GB, Asylum Records)
4. Charli XCX - Nuclear Seasons (44.6%) (album, tracks, year) (CD-R, 2011, GB, This Is Music)
5. Charli XCX - After the Afterparty (acoustic) (44.4%) (album, tracks, year) (Digital Media, 2016, XW, Asylum Records)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? D
edit: invoking editor command: ['/usr/bin/code', '/tmp/tmpq2ar6m0x.yaml']
No changes; aborting.
Sending event: before_choose_candidate
Finding tags for album "Charli XCX - Offline".
Candidates:
1. Charli XCX - SuperLove (54.3%) (album, year, tracks) (Digital Media, 2013, GB, Asylum Records)
2. Charli XCX - Boys (Coldabank Remix) (46.9%) (album, tracks, year) (Digital Media, 2017, GB, Asylum Records)
3. Charli XCX - Break the Rules (46.8%) (album, tracks, year) (Digital Media, 2014, GB, Asylum Records)
4. Charli XCX - Nuclear Seasons (44.6%) (album, tracks, year) (CD-R, 2011, GB, This Is Music)
5. Charli XCX - After the Afterparty (acoustic) (44.4%) (album, tracks, year) (Digital Media, 2016, XW, Asylum Records)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 
```

### Setup

* OS: Debian Buster
* Python version: Python 3.6.6
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/drive/Music
library: ~/data/musiclibrary.db

import:
    move: yes

plugins: ftintitletest fromfilename web duplicates edit acousticbrainz lastimport embedart fetchart artiststofeat tagreplace convert
ftintitletest:
    format: (feat. {0})
    auto: yes
    drop: no
lastfm:
    user: xKazeSenoue
    api_key: REDACTED
embedart:
    remove_art_file: yes
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
convert:
    auto: yes
    max_bitrate: 256
    never_convert_lossy_files: yes
    dest: /home/rodrigo/drive/Music_Lossy
    pretend: no
    threads: 8
    format: mp3
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    copy_album_art: no
    album_art_maxwidth: 0
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
lastimport:
    per_page: 500
    retry_limit: 3
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
acousticbrainz:
    auto: yes
    force: no
    tags: []
tagreplace:
    "\u2010": '-'
    "\u2019": ''''
    "\u201C": '"'
    "\u201D": '"'
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
```
