### ISSUE TITLE
Updates "r128_album_gain: 000000 -> 000000" With or without replaygain plugin

### ISSUE THREAD

**Issue by K33k0** [beetbox/beets#3049]
### Problem

Running beets update leeds to the r128 tags been updated to 000000 even if its already at 000000. If I run the replaygain plugin manually this tag is updated correctly, only to be wiped again when beet update is run.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv update
```

Led to this problem:

```
skipping /mnt/data/music/Pearl Jam/Vitalogy/06 Whipping.ogg because mtime is up to date (1537958068.0)
Pearl Jam - Ten - Alive
  r128_album_gain: 000000 -> 000000
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Pearl Jam - Ten - Why Go
  r128_album_gain: 000000 -> 000000
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
```
(Happens to all my music)

### Setup

* OS: Ubuntu bionic
* Python version: 3.6.5
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
# Physical Location of your *Processed* music
directory: /mnt/data/music
# Where to store your beets database
library: /home/admin/.config/beets/musiclibrary.db

import:
  # write metadata to music files
  write: yes

  # move imported files from source to the music directory
  move: yes
  copy: no
  delete: no

  # use auto-tagging where possible
  # do not require confirmation on strong matches
  autotag: yes
  timid: no

  resume: ask
  incremental: no
  none_rec_action: ask
  log: /home/admin/logs/beets.log

  quiet: no
  quiet_fallback: skip
  default_action: apply


  singletons: no
  detail: no
  flat: no

#  duplicate_action: skip

# use the release-date of the original (first) release of an album?
original_date: yes

# on multi-disk releases, assign track numbers for the whole album.
# If "per disk", make sure tracknames do not collide ("paths" setting).
per_disc_numbering: no

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]

# Paths and filenames for music files
# relative to music directory
paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

path_sep_replace: _


# filename for the album art
art_filename: cover  # results in "cover.jpg"


# General --------------------------------------------------------------------

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: no

# User Interface -------------------------------------------------------------

color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0


# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.15      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: missing_tracks unmatched_tracks
    track_length_grace: 10
    track_length_max: 30


# Plugins -------------------------------------------------------------------

plugins: beatport chroma convert discogs fetchart ftintitle info lastgenre lyrics missing replaygain scrub web acousticbrainz

acousticbrainz:
  auto: yes

chroma:
  auto: yes

convert:
  auto: yes
  format: opus
  formats:
    opus:
      command: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
      extension: ogg

fetchart:
  auto: yes

ftintitle:
  auto: yes

lastgenre:
  auto: yes
  canonical: yes

lyrics:
  auto: yes

missing:
  format: $albumartist - $album - $title
  count: no
  total: no

replaygain:
  auto: yes
  backend: bs1770gain
  method: ebu
scrub:
  auto: yes
web:
  host: 127.0.0.1
  port: 8337
  reverse_proxy: true
```
