### ISSUE TITLE
Importing folders w/ missing songs

### ISSUE THREAD

**Issue by mankoff** [beetbox/beets#3058]
### Problem

I have a lot of folders that are incomplete albums. Some songs are missing. When I import interactively I'm warned about this but `beets` finds the album with sometimes high confidence:

```
Tagging:
    Alpha - Pepper
URL:
    https://musicbrainz.org/release/d9c8d8a2-2608-3dd0-abbd-e758283ce0d2
(Similarity: 96.1%) (missing tracks) (CD, 1998, US, Caroline Records)
 * With (Underdog Remix)                      -> With (Underdog remix)
 * Hazeldub (More Rockers Peace and Love Mix) -> Hazeldub (More Rockers Peace and Love mix)
 * Sometime Later (Tim Simenon Mix)           -> Sometime Later (Tim Simenon mix)
 * Slim (Underdog Remix)                      -> Slim (Underdog remix)
 * Firefly (Receiver Mix)                     -> Firefly (Receiver mix)
Missing tracks (1/8 - 12.5%):
 ! Over (#8) (4:53)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```

I'd like to auto-import, but when I import with `-q`, this album is skipped. I have not found a plugin or setting that seems to change this behavior. Is there a setting to import albums with missing tracks, but still keep as album (not using the `-s` singleton option)?

### Setup

* OS: Kubuntu 18.04
* Python version: 3.6.5
* beets version: 1.4.7

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/Library
library: ~/Music/musiclibrary.db

plugins: fromfilename

import:
    write: yes
    copy: yes
    move: no
    resume: yes
    log: ~/Music/beets.log

match:
    strong_rec_thresh: 0.25
    max_rec:
        missing_tracks: low
duplicate_action: skip
```
