### ISSUE TITLE
Beets not respecting my match: ignored: missing_tracks configuration

### ISSUE THREAD

**Issue by udiboy1209** [beetbox/beets#3064]
### Problem

I have mentioned in my config that `missing_tracks` should be ignored while matching. But the matching fails on an album which has 10 tracks out of which I am importing 5.
 
Running `beet import` in verbose (`-vv`) mode:

```sh
$ beet -vv import Doowhops\ and\ Hooligans/

user configuration: /home/udiboy/.config/beets/config.yaml
data directory: /home/udiboy/.config/beets
plugin paths: 
/home/udiboy/.local/lib/python2.7/site-packages/pylast/__init__.py:51: UserWarning: You are using pylast with Python 2. Pylast will soon be Python 3 only. More info: https://github.com/pylast/pylast/issues/265
  UserWarning,
Sending event: pluginload
library database: /home/udiboy/Music/.beetsdb
library directory: /home/udiboy/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/udiboy/Downloads/Doowhops and Hooligans
Tagging Bruno Mars - Doo-Wops & Hooligans
No album ID found.
Search terms: Bruno Mars - Doo-Wops & Hooligans
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'doo-wops & hooligans', 'tracks': u'5', 'artist': u'bruno mars'}
Requesting MusicBrainz release e5b02753-c983-4ff9-81b6-a6cbd01a8d47
primary MB release type: album
Sending event: albuminfo_received
Candidate: Bruno Mars - Doo-Wops & Hooligans (e5b02753-c983-4ff9-81b6-a6cbd01a8d47)
Computing track assignment...
...done.
Ignored. Penalty: missing_tracks
Requesting MusicBrainz release 33030768-eed0-404a-bd5e-af6950546211
primary MB release type: album
Sending event: albuminfo_received
Candidate: Bruno Mars - Doo-Wops & Hooligans (33030768-eed0-404a-bd5e-af6950546211)
Computing track assignment...
...done.
Ignored. Penalty: missing_tracks
Requesting MusicBrainz release d6982d34-b422-4b37-8b49-025ae87b4c10
primary MB release type: album
Sending event: albuminfo_received
Candidate: Bruno Mars - Doo-Wops & Hooligans (d6982d34-b422-4b37-8b49-025ae87b4c10)
Computing track assignment...
...done.
Ignored. Penalty: missing_tracks
Requesting MusicBrainz release f7425a29-4c80-4b19-9837-f1f727d44fb4
primary MB release type: album
Sending event: albuminfo_received
Candidate: Bruno Mars - Doo-Wops & Hooligans (f7425a29-4c80-4b19-9837-f1f727d44fb4)
Computing track assignment...
...done.
Ignored. Penalty: missing_tracks
Requesting MusicBrainz release 6bbe5606-67ba-4063-8481-49f8d4c41852
primary MB release type: album
Sending event: albuminfo_received
Candidate: Bruno Mars - Doo-Wops & Hooligans (6bbe5606-67ba-4063-8481-49f8d4c41852)
Computing track assignment...
...done.
Ignored. Penalty: missing_tracks
Evaluating 0 candidates.

/home/udiboy/Downloads/Doowhops and Hooligans (5 items)
Sending event: before_choose_candidate
No matching release found for 5 tracks.
For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort,
eDit? B
Sending event: import
Sending event: cli_exit
```

### Setup

* OS: ArchLinux
* Python version: 2.7.15
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
paths:
    default: $albumartist/$album/$track-$title
    singleton: Non-Album/$artist/$title
library: ~/Music/.beetsdb

plugins: ftintitle edit fromfilename fetchart embedart lastgenre
directory: ~/Music

import:
    move: yes

match:
    ignored: missing_tracks
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
lastgenre:
    count: 1
    source: album
    prefer_specific: no
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
```
