### ISSUE TITLE
Plugin Zero says I gave it invalid fields, beets says they are valid

### ISSUE THREAD

**Issue by clickwir** [beetbox/beets#3068]
### Problem

Running "beet fields" shows a nice list of supported fields. Zero complains about 5 that I've seen so far.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv zero "I hope you die"
user configuration: /home/user/.config/beets/config.yaml
data directory: /home/user/.config/beets
plugin paths: 
Sending event: pluginload
zero: invalid field: bitdepth
zero: invalid field: bitrate
zero: invalid field: filesize
zero: invalid field: samplerate
zero: invalid field: compilation
library database: /Data/Music_USB/musiclibrary.db
library directory: /Data/Music_USB
Sending event: library_opened
zero: bpm: 0 -> None
zero: acoustid_fingerprint:  -> None
zero: acoustid_id:  -> None
zero: asin:  -> None
zero: catalognum:  -> None
zero: country:  -> None
zero: encoder:  -> None
Sending event: write
zero: bpm: None -> None
zero: acoustid_fingerprint: None -> None
zero: acoustid_id: None -> None
zero: asin: None -> None
zero: catalognum: None -> None
zero: country: None -> None
zero: encoder: None -> None
Sending event: after_write
Sending event: database_change
Sending event: cli_exit

```

Led to this problem:

```
zero: invalid field: bitdepth
zero: invalid field: bitrate
zero: invalid field: filesize
zero: invalid field: samplerate
zero: invalid field: compilation
```

### Setup

* OS: Kubuntu 18.10
* Python version: 3.6.7rc1
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): problem is a plugin, I think.

My configuration (output of `beet config`) is:

```yaml
directory: /Data/Music_USB
library: /Data/Music_USB/musiclibrary.db

plugins: zero
zero:
    fields: bpm acoustid_fingerprint acoustid_id asin bitdepth bitrate catalognum country encoder filesize samplerate compilation
    update_database: yes
    auto: yes
    keep_fields: []

import:
    move: yes

paths:
    default: $albumartist/$album%aunique{}/$track - $albumartist - $title
    singleton: $artist/$artist - $title
art_filename: cover
```

Side note: I tried keep_fields with a list of like 15 fields to keep. But it seemed to only keep the first 6 or so. I didn't really pay attention that well, but it looked like it only looked at the first few things I gave it.
