### ISSUE TITLE
Cover imge not copied over when convert plugin is used

### ISSUE THREAD

**Issue by apastuszak** [beetbox/beets#3080]
### Problem

Cover imge not copied over when convert plugin is used

Running this command in verbose (`-vv`) mode:
yy
```sh
$ beet -vv convert Us3
```

Led to this problem:

```
user configuration: /home/andy/.config/beets/config.yaml
data directory: /home/andy/.config/beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
rewrite: adding template field artist シートベルツ
inline: adding item field multidisc
library database: /home/andy/Documents/library.db
library directory: /mnt/storage/music_library
Sending event: library_opened
Us3 - Hand on the Torch - Cantaloop (Flip Fantasia)
Us3 - Hand on the Torch - I Got It Goin' On
Us3 - Hand on the Torch - Different Rhythms Different People
Us3 - Hand on the Torch - It's Like That
Us3 - Hand on the Torch - Just Another Brother
Us3 - Hand on the Torch - Cruisin'
Us3 - Hand on the Torch - I Go to Work
Us3 - Hand on the Torch - Tukka Yoot's Riddim
Us3 - Hand on the Torch - Knowledge of Self
Us3 - Hand on the Torch - Lazy Day
Us3 - Hand on the Torch - Eleven Long Years
Us3 - Hand on the Torch - Make Tracks
Us3 - Hand on the Torch - The Darkside
Convert? (Y/n) y
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/02 I Got It Goin' On.flac
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/01 Cantaloop (Flip Fantasia).flac
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/03 Different Rhythms Different People.flac
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/04 It's Like That.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/03 Different Rhythms Different People.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/05 Just Another Brother.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/04 It's Like That.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/06 Cruisin'.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/01 Cantaloop (Flip Fantasia).flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/07 I Go to Work.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/02 I Got It Goin' On.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/08 Tukka Yoot's Riddim.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/05 Just Another Brother.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/09 Knowledge of Self.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/06 Cruisin'.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/10 Lazy Day.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/07 I Go to Work.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/11 Eleven Long Years.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/09 Knowledge of Self.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/12 Make Tracks.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/08 Tukka Yoot's Riddim.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Encoding /mnt/storage/music_library/Us3/Hand on the Torch/13 The Darkside.flac
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/11 Eleven Long Years.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/10 Lazy Day.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/12 Make Tracks.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
convert: Finished encoding /mnt/storage/music_library/Us3/Hand on the Torch/13 The Darkside.flac
Sending event: write
Sending event: after_write
convert: embedding album art from /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
convert: embedding /mnt/storage/music_library/Us3/Hand on the Torch/cover.jpg
Sending event: write
Sending event: after_write
Sending event: after_convert
Sending event: cli_exit

```

My config.yaml has the following convert settings:

```yaml

convert:
    auto: no
    copy_album_art: yes
    dest: /home/andy/lossy-music
    embed: yes
    never_convert_lossy_files: yes
    format: aac
    formats:
        aac:
            command: ffmpeg -i $source -vn -map 0:0 -c:a libfdk_aac -vbr 5 $dest
            extension: m4a
        mp3:
            command: ffmpeg -i $source -c:a libmp3lame -q:a 0 $dest
            extension: mp3
```

### Setup

* OS: Ubuntu Linux 18.04
* Python version: 2.7.15rc1
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): Didn't try.  This is a plugin issue

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    force: no
    auto: yes
    genius_api_key: REDACTED
    google_engine_ID: REDACTED
    sources:
    - google
    - lyricwiki
    - musixmatch
    - genius
    bing_lang_to:
    bing_client_secret: REDACTED
    google_API_key: REDACTED
    fallback:
    local: no
scrub:
    auto: yes
asciify_paths: yes

paths:
    default: $albumartist/$album %if{%aunique{},($year - $label)}/%if{$multidisc,$disc-}$track $title
library: ~/Documents/library.db
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}

plugins: lastgenre replaygain ftintitle fetchart embedart lastgenre info lyrics chroma scrub inline web convert rewrite duplicates export
web:
    host: 192.168.1.3
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    cors: ''
    port: 8337
convert:
    auto: no
    copy_album_art: yes
    dest: /home/andy/lossy-music
    embed: yes
    never_convert_lossy_files: yes
    format: aac
    formats:
        aac:
            command: ffmpeg -i $source -vn -map 0:0 -c:a libfdk_aac -vbr 5 $dest
            extension: m4a
        mp3:
            command: ffmpeg -i $source -c:a libmp3lame -q:a 0 $dest
            extension: mp3
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    album_art_maxwidth: 0
    threads: 4
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    no_convert: ''
item_fields:
    multidisc: 1 if disctotal > 1 else 0
per_disc_numbering: yes
rewrite:
    "artist \u30B7\u30FC\u30C8\u30D9\u30EB\u30C4": The Seatbelts
replaygain:
    backend: bs1770gain
    auto: yes
    overwrite: yes
    targetlevel: 89
    r128: [Opus]
    chunk_at: 5000
    method: replaygain
lastgenre:
    canonical: yes
    count: 3
    separator: ', '
    source: album
    prefer_specific: no
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    fallback:
directory: /mnt/storage/music_library

import:
    write: yes
    move: yes
    timid: yes

match:
    preferred:
        media: [CD]
chroma:
    auto: yes
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
export:
    default_format: json
    json:
        formatting:
            ensure_ascii: no
            indent: 4
            sort_keys: yes
            separators: [',', ': ']
pathfields: {}
album_fields: {}
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
fetchart:
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder

```
