### ISSUE TITLE
Discogs plugin matches based on master release

### ISSUE THREAD

**Issue by rotzbouw** [beetbox/beets#3093]
### Problem

It seems that the Discogs plugin matches source data to master releases instead of the specific releases. I.e. I want to match my data to https://www.discogs.com/Various-Dont-Press-Your-Luck-The-In-Sound-Of-60s-Connecticut/release/4117481 but somehow, the plugin cannot match the penultimate track even though it can be found in the release but **not** in the master release.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import Don\'t\ Press\ Your\ Luck\!\ The\ IN\ Sound\ of\ 60\'s\ Connecticut/Disc\ 01/
user configuration: /home/thierry/.config/beets/config.yaml
data directory: /home/thierry/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field initial
inline: adding item field multidisc
inline: adding item field release_year
library database: /home/thierry/.config/beets/library.db
library directory: /mnt/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/01 - I Can Only Give You Everything (Bram Rigg Set).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/02 - Don't Press Your Luck (The Shags).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/03 - Help Me (George's Boys).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/04 - Too Many Lies (The Lively Ones).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/05 - Take the Time Be Yourself (Bram Rigg Set).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/06 - Hide Away (The Shags).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/07 - \xe2\x80\x98SSS\xe2\x80\x99 Happenin\xe2\x80\x99 Here (Uranus and the Five Moons).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/08 - Sleepless Nights (Bram Rigg Set).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/09 - You're Cutting Out (Fourth Ryke).mp3"
chroma: matched recordings [u'f6036fa2-976b-43f6-b9b5-a624a5007017'] on releases [u'3b3995d8-f6ae-44a8-84d8-8259d0d962a3']
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/10 - I Paid My Dues (The Bearies).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/11 - Radio Spot_ WAVZ Radio Jingle (The Shags).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/12 - No Good to Cry (The Wildweeds).mp3"
chroma: matched recordings [u'2a2c45ad-87c1-411f-8c1f-e0f386b04340'] on releases [u'daab6108-9d76-4951-a429-5bd37dc9f7bd']
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/13 - Think (The Lively Ones).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/14 - I Can't Explain (Bram Rigg Set).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/15 - Breathe in My Ear (The Shags).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/16 - Please Leave (Fourth Ryke).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/17 - Radio Spot_ Specter's Radio Ad (The Shags).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/18 - Nothing Remains (Uranus and the Five Moons).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/19 - You Don't Love Me (Bram Rigg Set).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/20 - Come Back to Me (The Shags).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/21 - I Love the Way You Love Me (The Roadrunners).mp3"
chroma: no recordings found
chroma: chroma: fingerprinted "/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01/22 - Make a Record with the Shags (The Shags).mp3"
chroma: no recordings found
Looking up: /home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01
Tagging Various Artists - Don't Press Your Luck! The IN Sound of 60's Connecticut
No album ID found.
Search terms: Various Artists - Don't Press Your Luck! The IN Sound of 60's Connecticut
Album might be VA: True
Searching for MusicBrainz releases with: {'release': u"don't press your luck! the in sound of 60's connecticut", 'tracks': u'22', 'artist': u'various artists'}
Requesting MusicBrainz release 3b3995d8-f6ae-44a8-84d8-8259d0d962a3
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: Various Artists - Don't Press Your Luck! The IN Sound of 60's Connecticut (3b3995d8-f6ae-44a8-84d8-8259d0d962a3)
Computing track assignment...
...done.
Success. Distance: 0.16
Requesting MusicBrainz release 3e9d547f-2a65-4ca8-8062-189f83c82061
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: Various Artists - The California Sound of the 60’s (3e9d547f-2a65-4ca8-8062-189f83c82061)
Computing track assignment...
...done.
Success. Distance: 0.62
Requesting MusicBrainz release d36406ee-d70b-4e0b-bce9-d10e62701c9e
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: Various Artists - California: The Sound of the 60's (d36406ee-d70b-4e0b-bce9-d10e62701c9e)
Computing track assignment...
...done.
Success. Distance: 0.64
Requesting MusicBrainz release b65174b4-16f1-4080-bb3d-b2a39965ed5f
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: Various Artists - The California Sound of the 60’s (b65174b4-16f1-4080-bb3d-b2a39965ed5f)
Computing track assignment...
...done.
Success. Distance: 0.62
Requesting MusicBrainz release 8b533575-4d2b-4243-a982-94bafc80fabb
primary MB release type: album
Sending event: albuminfo_received
Candidate: Various Artists - Jukebox Collection: The Sound Of The 60's (8b533575-4d2b-4243-a982-94bafc80fabb)
Computing track assignment...
...done.
Success. Distance: 0.65
Searching for MusicBrainz releases with: {'release': u"don't press your luck! the in sound of 60's connecticut", 'tracks': u'22', 'arid': '89ad4ac3-39f7-470e-963a-56509c546377'}
Requesting MusicBrainz release 3b3995d8-f6ae-44a8-84d8-8259d0d962a3
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: Various Artists - Don't Press Your Luck! The IN Sound of 60's Connecticut (3b3995d8-f6ae-44a8-84d8-8259d0d962a3)
Duplicate.
Requesting MusicBrainz release 452943f9-ef0c-4511-a299-c83825faebd8
primary MB release type: album
secondary MB release type(s): soundtrack
Sending event: albuminfo_received
Candidate: Robert J. Kral - The Haunting in Connecticut (452943f9-ef0c-4511-a299-c83825faebd8)
Computing track assignment...
...done.
Success. Distance: 0.67
Requesting MusicBrainz release 3e9d547f-2a65-4ca8-8062-189f83c82061
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: Various Artists - The California Sound of the 60’s (3e9d547f-2a65-4ca8-8062-189f83c82061)
Duplicate.
Requesting MusicBrainz release d36406ee-d70b-4e0b-bce9-d10e62701c9e
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: Various Artists - California: The Sound of the 60's (d36406ee-d70b-4e0b-bce9-d10e62701c9e)
Duplicate.
Requesting MusicBrainz release b65174b4-16f1-4080-bb3d-b2a39965ed5f
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: Various Artists - The California Sound of the 60’s (b65174b4-16f1-4080-bb3d-b2a39965ed5f)
Duplicate.
discogs: Searching for master release 567158
discogs: Searching for master release 567158
discogs: Searching for master release 567158
Sending event: albuminfo_received
Candidate: Various Artists - Don't Press Your Luck! The In Sound Of 60's Connecticut (1493257)
Computing track assignment...
...done.
Success. Distance: 0.19
Sending event: albuminfo_received
Candidate: Various Artists - Don't Press Your Luck! The In Sound Of 60's Connecticut (4117481)
Computing track assignment...
...done.
Success. Distance: 0.19
Sending event: albuminfo_received
Candidate: Various Artists - Don't Press Your Luck! The In Sound Of 60's Connecticut (11122219)
Computing track assignment...
...done.
Success. Distance: 0.19
chroma: acoustid album candidates: 0
Evaluating 9 candidates.

/home/thierry/Don't Press Your Luck! The IN Sound of 60's Connecticut/Disc 01 (22 items)
Sending event: before_choose_candidate
Tagging:
    Various Artists - Don't Press Your Luck! The IN Sound of 60's Connecticut
URL:
    https://musicbrainz.org/release/3b3995d8-f6ae-44a8-84d8-8259d0d962a3
(Similarity: 83.8%) (missing tracks, tracks, mediums, year) (2x12" Vinyl, 2008, US, Sundazed Music)
12" Vinyl 1
 * I Can Only Give You Everything (#1)  -> I Can Only Give You Everything (#1-1)
 * Don't Press Your Luck (#2)           -> Don't Press Your Luck (#1-2)
 * Help Me (#3)                         -> Help Me (#1-3)
 * Too Many Lies (#4)                   -> Too Many Lies (#1-4)
 * Take the Time Be Yourself (#5)       -> Take the Time Be Yourself (#1-5)
 * Hide Away (#6)                       -> Hide Away (#1-6)
 * ‘SSS’ Happenin’ Here (#7)            -> ‘SSS’ Happenin’ Here (#1-7)
 * Sleepless Nights (#8)                -> Sleepless Nights (#1-8) (artist)
 * You're Cutting Out (#9)              -> You're Cutting Out (#1-9)
 * I Paid My Dues (#10)                 -> I've Paid My Dues (#1-10) (title)
 * Radio Spot: WAVZ Radio Jingle (#11)  -> Radio Spot: WAVZ Radio Jingle (#1-11)
 * No Good to Cry (#12)                 -> No Good to Cry (#1-12) (id)
 * Think (#13)                          -> Think (#1-13)
 * I Can't Explain (#14)                -> I Can't Explain (#1-14)
12" Vinyl 2
 * Breathe in My Ear (#15)              -> Breathe in My Ear (#2-1)
 * Please Leave (#16)                   -> Please Leave (#2-2)
 * Radio Spot: Specter's Radio Ad (#17) -> Radio Spot: Specter's Radio Ad (#2-3)
 * Nothing Remains (#18)                -> Nothing Remains (#2-4)
 * You Don't Love Me (#19)              -> You Don't Love Me (#2-5)
 * Come Back to Me (#20)                -> Come Back to Me (#2-6)
 * I Love the Way You Love Me (#21)     -> LUV (#2-7) (title)
 * Make a Record with the Shags (#22)   -> Make a Record With the Shag (#2-13) (index, title)
Missing tracks (5/27 - 18.5%):
 ! I'm Dreaming (#2-8) (2:41)
 ! Your Groove (#2-9) (2:47)
 ! Hey, Little Girl (#2-10) (2:15)
 ! Sticks and Stones (#2-11) (2:06)
 ! Bad News for Me (#2-12) (3:26)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, plaY? M
Finding tags for album "Various Artists - Don't Press Your Luck! The IN Sound of 60's Connecticut".
Candidates:
1. Various Artists - Don't Press Your Luck! The IN Sound of 60's Connecticut (83.8%) (missing tracks, tracks, mediums, ...) (2x12" Vinyl, 2008, US, Sundazed Music)
2. Various Artists - Don't Press Your Luck! The In Sound Of 60's Connecticut (81.4%) (missing tracks, tracks, mediums, ...) (Discogs, 2xVinyl, 2008, US, Sundazed Music)
3. Various Artists - Don't Press Your Luck! The In Sound Of 60's Connecticut (81.4%) (missing tracks, tracks, mediums, ...) (Discogs, 2xVinyl, 2008, US, Sundazed Music)
4. Various Artists - Don't Press Your Luck! The In Sound Of 60's Connecticut (81.1%) (tracks, source, year, ...) (Discogs, CD, 2008, US, Sundazed Music)
5. Various Artists - The California Sound of the 60’s (37.6%) (tracks, album, unmatched tracks, ...) (CD, 1989, DE, Wave)
6. Various Artists - The California Sound of the 60’s (37.5%) (tracks, album, unmatched tracks, ...) (CD, 1989, XE, Wave)
7. Various Artists - California: The Sound of the 60's (36.2%) (tracks, album, unmatched tracks)
8. Various Artists - Jukebox Collection: The Sound Of The 60's (34.8%) (tracks, unmatched tracks, album) (CD)
9. Robert J. Kral - The Haunting in Connecticut (32.8%) (tracks, missing tracks, artist, ...) (CD, 2009, US)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, plaY? 4  
Correcting tags from:
    Don't Press Your Luck! The IN Sound of 60's Connecticut
To:
    Don't Press Your Luck! The In Sound Of 60's Connecticut
URL:
    https://www.discogs.com/Various-Dont-Press-Your-Luck-The-In-Sound-Of-60s-Connecticut/release/4117481
(Similarity: 81.1%) (tracks, source, year, unmatched tracks) (Discogs, CD, 2008, US, Sundazed Music)
 * Take the Time Be Yourself            -> Take The Time Be Yourself
 * ‘SSS’ Happenin’ Here                 -> 'SSS' Happenin' Here
 * You're Cutting Out (#9)              -> You're Cutting Out (#8) (id, index)
 * I Paid My Dues (#10)                 -> I Paid My Dues (#9) (index)
 * Radio Spot: WAVZ Radio Jingle (#11)  -> WAVZ Radio Jingle (#10) (title, index)
 * No Good to Cry (#12)                 -> No Good To Cry (#11) (id, index)
 * Think (#13)                          -> Think (#12) (index)
 * I Can't Explain (#14)                -> I Can't Explain (#13) (index)
 * Breathe in My Ear (#15)              -> Breath In My Ear (#14) (index, title)
 * Please Leave (#16)                   -> Please Leave (#15) (index)
 * Radio Spot: Specter's Radio Ad (#17) -> Specter's Radio Ad (#16) (title, index)
 * Nothing Remains (#18)                -> Nothing Remains (#17) (index)
 * You Don't Love Me (#19)              -> You Don't Love Me (#18) (index)
 * Come Back to Me (#20) (2:27)         -> Come Back To Me (#19) (2:16) (index, length)
 * Sleepless Nights (#8) (3:06)         -> Luv (#20) (3:26) (title, artist, index, length)
 * Make a Record with the Shags (#22)   -> Make A Record With The Shags (#21) (index)
Unmatched tracks (1):
 ! I Love the Way You Love Me (#21) (2:33)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, plaY?
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: Linux debian
* Python version: 2.7.15+
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
$ beet config

paths:
    default: $initial/$albumartist/%if{$release_year,$release_year/}$album/%if{$multidisc, Disc $disc/}$track - $title
    comp: Compilations/%if{$release_year,$release_year/}$album/%if{$disc,Disc $disc/}$track - $title ($artist)
convert:
    copy_album_art: yes
    never_convert_lossy_files: yes
    command: ffmpeg -i $source -y -vn -aq 0 $dest
    extension: mp3
    album_art_maxwidth: 0
    format: mp3
    dest:
    auto: no
    threads: 4
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    embed: yes
    no_convert: ''
item_fields:
    initial: "if albumartist_sort:\n    return albumartist_sort[0].upper()\nelif albumartist:\n    return albumartist[0].upper()\nelif artist:\n    return artist[0].upper()\nelse:\n    return \"#\"\n"
    multidisc: "if disctotal > 1:\n    return 1\nelif disc > 0:\n    return 0\nelse:\n    return 0\n"
    release_year: "if original_year:\n    return original_year\nelif year:\n    return year\nelse:\n    return 0\n"
per_disc_numbering: yes
chroma:
    auto: yes
play:
    command: mpv --no-video --playlist
    use_folders: no
    raw: no
    warning_threshold: 100
    relative_to:

plugins: duplicates inline missing chroma discogs web convert random play info mbsync
directory: /mnt/music

import:
    copy: yes
    write: yes
    log: beets.log

sort_album: albumartist+ album+
sort_item: albumartist+ album+ disc+ track+
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
missing:
    count: no
    album: no
    total: no
discogs:
    tokenfile: discogs_token.json
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
web:
    cors_supports_credentials: no
    reverse_proxy: no
    host: 127.0.0.1
    include_paths: no
    cors: ''
    port: 8337
pathfields: {}
album_fields: {}
```
