### ISSUE TITLE
lastimport too strict?

### ISSUE THREAD

**Issue by billop** [beetbox/beets#3110]
### Setup

* OS:  Arch Linux
* Python version: 3.7.1
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/BeetsLibrary
library: ~/Music/beetslibrary.db
import:
  write: yes
  move: yes
  resume: no
match:
  distance_weights:
    missing_tracks: 0
    artist: 10
    title: 10
    length: 10
paths:
    default: $albumartist/$year $album%aunique{}/$track $title
    singleton: $artist/Non-Album/$year $title
    comp: Compilations/$album%aunique{}/$track $title
plugins:
  convert
  ftintitle
  lastimport
  info
  importadded
  fuzzy
  edit
lastfm:
  user: myusername
```

This plugin is great, however, I noticed that some of my library tracks did not get matched with last.fm data due to minor differences.

For example, in Random Access Memories by Daft Punk:
"Touch (feat. Paul Williams)" - Last.fm
"Touch" - My library

Or even worse, from M.A.A.D City:
"Compton (feat. Dr. Dre)" - Last.fm 
"Compton feat. Dr. Dre" - My library (following musicbrainz style guidelines)

I would try to fix it myself but I want to make sure I'm not missing something first.
