### ISSUE TITLE
Add Synology indexing plugin

### ISSUE THREAD

**Issue by nnutter** [beetbox/beets#3113]
### Problem

I have written a plugin, [beets-synoindex](https://github.com/nnutter/beets-synoindex
) to trigger Synology DiskStation's music indexing on import so that imported music immediately shows up in Audio Station.  If it's reasonably good I'd be happy to contribute it.

### Setup

* OS: Linux 4.4.59+ #23824 SMP PREEMPT x86_64 GNU/Linux synology_apollolake_918+
* Python version: 3.5.1
* beets version: 1.4.7

My configuration (`config.yaml`) is:

```yaml
directory: /volume1/music
library: /volume1/music/.beet.db

import:
  copy: no
  move: yes

plugins: fetchart lyrics lastgenre synoupdate
```
