### ISSUE TITLE
import failed after choosing [A]pply for suggested album

### ISSUE THREAD

**Issue by spfeifer222** [beetbox/beets#3118]
### Problem

(Describe your problem, feature request, or discussion topic here. If you're reporting a bug, please fill out this and the "Setup" section below. Otherwise, you can delete them.)

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import Various\ -\ P*

```

Led to this problem:

```
/media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture (16 items)
Sending event: before_choose_candidate
Correcting tags from:
    Pulp Fiction: Music From The Motion Picture
To:
    Pulp Fiction: Music From the Motion Picture
URL:
    https://musicbrainz.org/release/326a3d80-4c8c-4e2b-ad11-4fa822d430ea
(Similarity: 90.7%) (tracks) (12" Vinyl, 1994, GB, Simply Vinyl)
 * Dick Dale And His Del-Tones / Pumpkin & Honey Bunny / Misirlou ->
   Pumpkin and Honey Bunny / Misirlou (title)
 * Jules & Vincent / Royale With Cheese ->
   Royale With Cheese (title)
 * Kool & The Gang / Jungle Boogie ->
   Jungle Boogie (title)
 * Al Green / Let's Stay Together ->
   Let's Stay Together (title)
 * The Tornadoes / Bustin' Surfboards ->
   Bustin' Surfboards (title)
 * Ricky Nelson / Lonesome Town ->
   Lonesome Town (title)
 * Dusty Springfield / Son Of A Preacher Man ->
   Son of a Preacher Man (title)
 * The Centurians / Zed's Dead, Baby / Bullwinkle Part II ->
   Zed's Dead, Baby / Bullwinkle Part II (title)
 * Chuck Berry / Jack Rabbit Slims Twist Contest / You Never Can Tell ->
   Jack Rabbit Slims Twist Contest / You Never Can Tell (title)
 * Urge Overkill / Girl, You'll Be A Woman Soon ->
   Girl, You'll Be a Woman Soon (title)
 * Maria McKee / If Love Is A Red Dress (Hang Me In Rags) ->
   If Love Is a Red Dress (Hang Me in Rags) (title)
 * The Revels / Bring Out The Gimp / Comanche ->
   Bring Out the Gimp / Comanche (title)
 * The Statler Brothers / Flowers On The Wall ->
   Flowers on the Wall (title)
 * Jules & Vincent / Personality Goes A Long Way ->
   Personality Goes a Long Way (title)
 * The Lively Ones / Surf Rider ->
   Surf Rider (title)
 * Jules / Ezekiel 25:17 ->
   Ezekiel 25:17 (title)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates, plaY? A
Sending event: import_task_choice
Sending event: import_task_apply
Replacing item 2669: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/11 Maria McKee - If Love Is A Red Dress (Hang Me In Rags).mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2668: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/01 Dick Dale And His Del-Tones - Pumpkin & Honey Bunny - Misirlou.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2679: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/12 The Revels - Bring Out The Gimp - Comanche.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2666: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/06 Ricky Nelson - Lonesome Town.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2674: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/16 Jules - Ezekiel 25:17.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2665: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/05 The Tornadoes - Bustin' Surfboards.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2670: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/03 Kool & The Gang - Jungle Boogie.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2671: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/04 Al Green - Let's Stay Together.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2678: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/09 Chuck Berry - Jack Rabbit Slims Twist Contest - You Never Can Tell.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2675: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/07 Dusty Springfield - Son Of A Preacher Man.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2667: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/15 The Lively Ones - Surf Rider.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2676: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/10 Urge Overkill - Girl, You'll Be A Woman Soon.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2677: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/13 The Statler Brothers - Flowers On The Wall.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2673: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/08 The Centurians - Zed's Dead, Baby - Bullwinkle Part II.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2672: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/14 Jules & Vincent - Personality Goes A Long Way.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 2680: /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/02 Jules & Vincent - Royale With Cheese.mp3
Sending event: database_change
Sending event: database_change
Sending event: item_removed
16 of 16 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Reimported album: added 1545824629.97, flexible attributes [] from album 208 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture
Reimported item added 1545824641.04 from item 2669 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/11 Maria McKee - If Love Is A Red Dress (Hang Me In Rags).mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2669 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/11 Maria McKee - If Love Is A Red Dress (Hang Me In Rags).mp3
Sending event: database_change
Reimported item added 1545824641.0 from item 2668 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/01 Dick Dale And His Del-Tones - Pumpkin & Honey Bunny - Misirlou.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2668 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/01 Dick Dale And His Del-Tones - Pumpkin & Honey Bunny - Misirlou.mp3
Sending event: database_change
Reimported item added 1545824640.98 from item 2679 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/12 The Revels - Bring Out The Gimp - Comanche.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2679 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/12 The Revels - Bring Out The Gimp - Comanche.mp3
Sending event: database_change
Reimported item added 1545824641.03 from item 2666 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/06 Ricky Nelson - Lonesome Town.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2666 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/06 Ricky Nelson - Lonesome Town.mp3
Sending event: database_change
Reimported item added 1545824640.96 from item 2674 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/16 Jules - Ezekiel 25:17.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2674 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/16 Jules - Ezekiel 25:17.mp3
Sending event: database_change
Reimported item added 1545824641.03 from item 2665 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/05 The Tornadoes - Bustin' Surfboards.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2665 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/05 The Tornadoes - Bustin' Surfboards.mp3
Sending event: database_change
Reimported item added 1545824641.04 from item 2670 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/03 Kool & The Gang - Jungle Boogie.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2670 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/03 Kool & The Gang - Jungle Boogie.mp3
Sending event: database_change
Reimported item added 1545824640.97 from item 2671 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/04 Al Green - Let's Stay Together.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2671 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/04 Al Green - Let's Stay Together.mp3
Sending event: database_change
Reimported item added 1545824641.04 from item 2678 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/09 Chuck Berry - Jack Rabbit Slims Twist Contest - You Never Can Tell.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2678 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/09 Chuck Berry - Jack Rabbit Slims Twist Contest - You Never Can Tell.mp3
Sending event: database_change
Reimported item added 1545824640.97 from item 2675 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/07 Dusty Springfield - Son Of A Preacher Man.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2675 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/07 Dusty Springfield - Son Of A Preacher Man.mp3
Sending event: database_change
Reimported item added 1545824641.05 from item 2667 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/15 The Lively Ones - Surf Rider.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2667 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/15 The Lively Ones - Surf Rider.mp3
Sending event: database_change
Reimported item added 1545824641.04 from item 2676 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/10 Urge Overkill - Girl, You'll Be A Woman Soon.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2676 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/10 Urge Overkill - Girl, You'll Be A Woman Soon.mp3
Sending event: database_change
Reimported item added 1545824640.91 from item 2677 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/13 The Statler Brothers - Flowers On The Wall.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2677 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/13 The Statler Brothers - Flowers On The Wall.mp3
Sending event: database_change
Reimported item added 1545824641.05 from item 2673 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/08 The Centurians - Zed's Dead, Baby - Bullwinkle Part II.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2673 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/08 The Centurians - Zed's Dead, Baby - Bullwinkle Part II.mp3
Sending event: database_change
Reimported item added 1545824641.02 from item 2672 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/14 Jules & Vincent - Personality Goes A Long Way.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2672 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/14 Jules & Vincent - Personality Goes A Long Way.mp3
Sending event: database_change
Reimported item added 1545824641.03 from item 2680 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/02 Jules & Vincent - Royale With Cheese.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 2680 for /media/pfeifer/Musik@spf-01/Various - Pulp Fiction: Music From The Motion Picture/02 Jules & Vincent - Royale With Cheese.mp3
Sending event: database_change
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 943, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 913, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1511, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/convert.py", line 176, in auto_convert
    self.convert_on_import(config.lib, item)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/convert.py", line 467, in convert_on_import
    fd, dest = tempfile.mkstemp(util.py3_path(b'.' + ext), dir=tmpdir)
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: 'none/tmp6DEiXz.mp3'

```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: Linux Mint 19.1 Tessa 64-bit, Kernel Linux 4.18.0-13-generic x86_64, MATE 1.20.1
* Python version: Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    sources: google lyricwiki musixmatch genius
    force: no
    auto: yes
    genius_api_key: REDACTED
    google_engine_ID: REDACTED
    bing_lang_to:
    bing_client_secret: REDACTED
    google_API_key: REDACTED
    fallback:
    local: no

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype:soundtrack: Soundtracks/$album/$track - $title
play:
    command: mpv --loop-playlist=inf --playlist
    use_folders: no
    raw: no
    warning_threshold: 100
    relative_to:
fetchart:
    cautious: yes
    cover_names: cover front album front back
    auto: yes
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    maxwidth: 0
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
duplicates:
    album: no
    copy: none
    count: no
    delete: no
    full: no
    move: none
    path: yes
    strict: no
    tag: key=doublette
    tiebreak: {}
    format: ''
    keys: []
    checksum: ''
    merge: no
random:
library: /media/pfeifer/Musik_sortiert@spf-01/.beet/musiclibrary.db
replaygain:
    backend: gstreamer
    auto: no
    overwrite: no
    targetlevel: 89
    r128: [Opus]
pluginpath: /media/pfeifer/Musik_sortiert@spf-01/.beet/plugins

plugins: bpd chroma convert duplicates edit fetchart fromfilename fuzzy info lastgenre lyrics play random replaygain web
fuzzy:
    threshold: 0.85
    prefix: '~'
web:
    host: 127.0.0.1
    port: 8337
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    cors: ''
convert:
    dest: /media/pfeifer/Musik_sortiert@spf-01
    copy_album_art: yes
    max_bitrate: 192
    formats:
        mp3:
            command: ffmpeg -i $source -acodec libmp3lame -aq 2 $dest
            extension: mp3
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    auto: yes
    embed: yes
    tmpdir: none

    paths:
        default: $albumartist/$album%aunique{}/$track - $title
        singleton: Non-Album/$artist - $title
        comp: Compilations/$album%aunique{}/$track - $title
        albumtype:soundtrack: Soundtracks/$album/$track - $title
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    format: mp3
    threads: 4
    pretend: no
    quiet: no
    no_convert: ''
bpd:
    volume: 80
    host: ''
    password: REDACTED
    port: 6600
edit:
    itemfields: track title artist albumartist
    albumfields: album albumartist
    ignore_fields: id path
chroma:
    auto: yes
directory: /media/pfeifer/Musik_sortiert@spf-01

import:
    copy: yes
    move: yes
    write: yes
lastgenre:
    count: 1
    source: album
    prefer_specific: no
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no

```
