### ISSUE TITLE
badfiles: config options/command for fixing files

### ISSUE THREAD

**Issue by Wyrrrd** [beetbox/beets#3126]
How about a separate config entry for commands to fix bad files instead of just listing them. Also one could possibly run a separate command (for example `beet fix` or `beet bad -f` ) to fix every file in the library instead of just checking.

Suggested config structure:
```
badfiles:
    check:
        mp3: mp3val
        ...
    fix:
        mp3: mp3val -f -nb
        ...
```
