### ISSUE TITLE
mbcollection error: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by StalenBas** [beetbox/beets#3131]
### Problem

Hey, I was trying to add my music collection to Musicbrainz, but got the following error:

error: MusicBrainz API error: caused by: HTTP Error 400: Bad Request

Looks similar to this earlier bug report: https://github.com/beetbox/beets/issues/1152

Running this command in verbose (`-vv`) mode:

```sh
beet -vv mbupdate
user configuration: /home/stalenbas/.config/beets/config.yaml
data directory: /home/stalenbas/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/stalenbas/.config/beets/musiclibrary.db
library directory: /run/media/stalenbas/BASCH3/Muziek
Sending event: library_opened
mbcollection: Updating MusicBrainz collection a29b7044-9cd2-3749-8b72-fe84b708bc4d...
error: MusicBrainz API error: caused by: HTTP Error 400: Bad Request
```

### Setup

* OS: Arch Linux 64 bit
* Python version: 3.7.2-3
* beets version: 1.4.7-3

My configuration (output of `beet config`) is:

```yaml
directory: /run/media/stalenbas/BASCH3/Muziek/
library: ~/.config/beets/musiclibrary.db
import:
    copy: no
    write: no
    
plugins: mbcollection
musicbrainz:
    user: [my username]
    pass: [my password]

```
