### ISSUE TITLE
AttributeError: module 're' has no attribute '_pattern_type'

### ISSUE THREAD

**Issue by TheOttoman2012** [beetbox/beets#3147]
### Problem

Running this command in verbose (`-vv`) mode:

λ beet import "\\atlantis\Music_stg"
```

Led to this problem:
 
```
 λ beet import "\\atlantis\Music_stg"
user configuration: C:\Users\xxxx\AppData\Roaming\beets\config.yaml
data directory: C:\Users\xxxx\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
lyrics: The Genius backend requires BeautifulSoup, which is not installed, so the source is disabled.
library database: D:\Music\database\musiclibrary.db
library directory: D:\Music\Sorted
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: \\atlantis\Music_stg\Chicane
Tagging Chicane - behind the sun
No album ID found.
Search terms: Chicane - behind the sun
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'behind the sun', 'artist': 'chicane', 'tracks': '11'}
Requesting MusicBrainz release 1337252a-319d-43e5-9681-dc32329a5b96
primary MB release type: album
Sending event: albuminfo_received
Candidate: Chicane - Behind the Sun (1337252a-319d-43e5-9681-dc32329a5b96)
Computing track assignment...
...done.
Traceback (most recent call last):
  File "D:\Music\applications\Beets\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "c:\python372\lib\site-packages\beets\ui\__init__.py", line 1256, in main
    _raw_main(args)
  File "c:\python372\lib\site-packages\beets\ui\__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "c:\python372\lib\site-packages\beets\ui\commands.py", line 943, in import_func
    import_files(lib, paths, query)
  File "c:\python372\lib\site-packages\beets\ui\commands.py", line 913, in import_files
    session.run()
  File "c:\python372\lib\site-packages\beets\importer.py", line 331, in run
    pl.run_sequential()
  File "c:\python372\lib\site-packages\beets\util\pipeline.py", line 389, in run_sequential
    list(self.pull())
  File "c:\python372\lib\site-packages\beets\util\pipeline.py", line 466, in pull
    out = coro.send(msg)
  File "c:\python372\lib\site-packages\beets\util\pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "c:\python372\lib\site-packages\beets\importer.py", line 1351, in lookup_candidates
    task.lookup_candidates()
  File "c:\python372\lib\site-packages\beets\importer.py", line 641, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "c:\python372\lib\site-packages\beets\autotag\match.py", line 461, in tag_album
    _add_candidate(items, candidates, matched_candidate)
  File "c:\python372\lib\site-packages\beets\autotag\match.py", line 377, in _add_candidate
    dist = distance(items, info, mapping)
  File "c:\python372\lib\site-packages\beets\autotag\match.py", line 191, in distance
    dist.add_equality('media', album_info.media, likelies['media'])
  File "c:\python372\lib\site-packages\beets\autotag\hooks.py", line 461, in add_equality
    if self._eq(opt, value):
  File "c:\python372\lib\site-packages\beets\autotag\hooks.py", line 436, in _eq
    if isinstance(value1, re._pattern_type):
AttributeError: module 're' has no attribute '_pattern_type'

```

I can provide a zip if necessary


### Setup

* OS: Win10
* Python version: 3.7.2
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

user configuration: C:\Users\xbmc\AppData\Roaming\beets\config.yaml                                       
data directory: C:\Users\xbmc\AppData\Roaming\beets                                                       
plugin paths:                                                                                             
Sending event: pluginload                                                                                 
lyrics: Disabling google source: no API key configured.                                                   
lyrics: The Genius backend requires BeautifulSoup, which is not installed, so the source is disabled.     
library database: D:\Music\database\musiclibrary.db                                                       
library directory: D:\Music\Sorted                                                                        
Sending event: library_opened                                                                             
lyrics:                                                                                                   
    bing_lang_from: []                                                                                    
    auto: yes                                                                                             
    fallback: ''                                                                                          
    echonest_tempo:                                                                                       
    bing_client_secret: REDACTED                                                                          
    bing_lang_to:                                                                                         
    google_API_key: REDACTED                                                                              
    google_engine_ID: REDACTED                                                                            
    genius_api_key: REDACTED                                                                              
    force: no                                                                                             
    local: no                                                                                             
    sources:                                                                                              
    - google                                                                                              
    - lyricwiki                                                                                           
    - musixmatch                                                                                          
    - genius                                                                                              
directory: D:\Music\Sorted                                                                                
library: D:\Music\database\musiclibrary.db                                                                
threaded: no                                                                                              
verbose: yes                                                                                              
timeout: 5.0                                                                                              
color: yes                                                                                                
list_format_item: '%upper{$artist} - $album - $track. $title'                                             
list_format_album: '%upper{$albumartist} - $album'                                                        
time_format: '%Y-%m-%d %H:%M:%S'                                                                          
terminal_encoding: utf8                                                                                   
                                                                                                          
ui:                                                                                                       
    terminal_width: 80                                                                                    
    length_diff_thresh: 10.0                                                                              
                                                                                                          
import:                                                                                                   
    write: yes                                                                                            
    copy: no                                                                                              
    move: yes                                                                                             
    autotag: yes                                                                                          
    timid: no                                                                                             
    resume: ask                                                                                           
    incremental: yes                                                                                      
    incremental_skip_later: yes                                                                           
    none_rec_action: ask                                                                                  
    log: d:\Music\applications\logs.log                                                                   
    quiet: no                                                                                             
    quiet_fallback: skip                                                                                  
    default_action: apply                                                                                 
    duplicate_action: keep                                                                                
    detail: yes                                                                                           
per_disc_numbering: no                                                                                    
                                                                                                          
clutter:                                                                                                  
- Thumbs.DB                                                                                               
- .DS_Store                                                                                               
- '*.m3u'                                                                                                 
- .pls                                                                                                    
- '*.jpg'                                                                                                 
                                                                                                          
replace:                                                                                                  
    '[\\/]': _                                                                                            
    ^\.: _                                                                                                
    '[\x00-\x1f]': _                                                                                      
    '[<>:"\?\*\|]': _                                                                                     
    \.$: _                                                                                                
    \s+$: ''                                                                                              
                                                                                                          
match:                                                                                                    
    strong_rec_thresh: 0.1                                                                                
    medium_rec_thresh: 0.25                                                                               
    rec_gap_thresh: 0.25                                                                                  
    max_rec:                                                                                              
        missing_tracks: medium                                                                            
        unmatched_tracks: medium                                                                          
    distance_weights:                                                                                     
        source: 2.0                                                                                       
        artist: 3.0                                                                                       
        album: 3.0                                                                                        
        media: 1.0                                                                                        
        mediums: 1.0                                                                                      
        year: 1.0                                                                                         
        country: 0.5                                                                                      
        label: 0.5                                                                                        
        catalognum: 0.5                                                                                   
        albumdisambig: 0.5                                                                                
        album_id: 5.0                                                                                     
        tracks: 2.0                                                                                       
        missing_tracks: 0.9                                                                               
        unmatched_tracks: 0.6                                                                             
        track_title: 3.0                                                                                  
        track_artist: 2.0                                                                                 
        track_index: 1.0                                                                                  
        track_length: 2.0                                                                                 
        track_id: 5.0                                                                                     
    preferred:                                                                                            
        countries: []                                                                                     
        media: []                                                                                         
        original_year: no                                                                                 
    ignored: []                                                                                           
    track_length_grace: 10                                                                                
    track_length_max: 30                                                                                  
                                                                                                          
plugins: [discogs, lyrics, fetchart]                                                                      
pluginpath: []                                                                                            
discogs:                                                                                                  
    user_token: REDACTED                                                                                  
    apikey: REDACTED                                                                                      
    apisecret: REDACTED                                                                                   
    tokenfile: discogs_token.json                                                                         
    source_weight: 0.5                                                                                    
fetchart:                                                                                                 
    auto: yes                                                                                             
    maxwidth: 300                                                                                         
    cautious: yes                                                                                         
    cover_names: cover folder                                                                             
    minwidth: 0                                                                                           
    enforce_ratio: no                                                                                     
    sources:                                                                                              
    - filesystem                                                                                          
    - coverart                                                                                            
    - itunes                                                                                              
    - amazon                                                                                              
    - albumart                                                                                            
    google_key: REDACTED                                                                                  
    google_engine: 001442825323518660753:hrh5ch1gjzm                                                      
    fanarttv_key: REDACTED                                                                                
    store_source: no                                                                                      
                                                                                                          
Sending event: cli_exit                                                                                   
                                                                                                          
```yaml
# general settings
directory: D:\Music\Sorted
library: D:\Music\database\musiclibrary.db
threaded: no
verbose: yes
timeout: 5.0

# user interface
color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0


# relating to importing music
import:
    # write metadata to music files
    write: yes

    # copy files from source to directory, not move
    copy: no
    move: yes

    # use auto-tagging where possible
    # do not require confirmation on strong matches
    autotag: yes
    timid: no

    resume: ask
    incremental: yes
    incremental_skip_later: yes
    none_rec_action: ask
    log: d:\Music\applications\logs.log

    quiet: no  # enable with command line option
    quiet_fallback: skip
    default_action: apply
    duplicate_action: keep
    detail: yes

# on multi-disk releases, assign track numbers for the whole album.
# If "per disk", make sure tracknames do not collide ("paths" setting).
per_disc_numbering: no

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

# replace special characters in generated filenames
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

# tagging
match:
    strong_rec_thresh: 0.10
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30

# plugins
plugins: [
    discogs,
    lyrics,
    #lastgenre,
    fetchart,
]
pluginpath: []


discogs:
    user_token: tqpAPeEYVWiGzzUUCdlyjTjrqkrncMopxxhSWlAy

lyrics:
    auto: yes
    fallback: ''

    echonest_tempo:
    auto: yes

#lastgenre:
#    whitelist: ~/.config/beets/genres.txt
#    canoncical: ~/.config/beets/genres-tree.yaml
#    fallback: ''
#    source: artist

fetchart:
    auto: yes
    maxwidth: 300
    cautious: true
    cover_names: cover folder
```
