### ISSUE TITLE
hang on - Sending event: database_change

### ISSUE THREAD

**Issue by bugsyb** [beetbox/beets#3162]
### Problem

Beets hangs on updating database. It is mainly happening when couple of large folders are submit for import. Did not happen when importing same content in smaller steps, i.e. 2-3 albums.

Last entries on console are:
```
lastgenre: added last.fm album genre (album): Chillout
Sending event: database_change
Sending event: database_change
```

Strace shows:
```
clock_gettime(CLOCK_REALTIME, {1550831990, 304809629}) = 0
clock_gettime(CLOCK_REALTIME, {1550831990, 304958172}) = 0
clock_gettime(CLOCK_REALTIME, {1550831990, 305105373}) = 0
clock_gettime(CLOCK_REALTIME, {1550831990, 305207502}) = 0
clock_gettime(CLOCK_REALTIME, {1550831990, 305358912}) = 0
clock_gettime(CLOCK_REALTIME, {1550831990, 305460960}) = 0
select(0, NULL, NULL, NULL, {0, 1000})  = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 306910655}) = 0
select(0, NULL, NULL, NULL, {0, 2000})  = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 309369228}) = 0
select(0, NULL, NULL, NULL, {0, 4000})  = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 313834391}) = 0
select(0, NULL, NULL, NULL, {0, 8000})  = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 322468193}) = 0
select(0, NULL, NULL, NULL, {0, 16000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 339078047}) = 0
select(0, NULL, NULL, NULL, {0, 32000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 371974552}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 422809254}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 473593037}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 524358873}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 575057862}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 625863318}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 676636821}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 727497818}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 778422504}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 829191559}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 879960957}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 930640877}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831990, 981299933}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 31994687}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 82579673}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 133111917}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 183871712}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 234566531}) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 285361946}) = 0
select(0, NULL, NULL, NULL, {0, 19894}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 306073052}) = 0
clock_gettime(CLOCK_REALTIME, {1550831991, 306223141}) = 0
clock_gettime(CLOCK_REALTIME, {1550831991, 306370465}) = 0
clock_gettime(CLOCK_REALTIME, {1550831991, 306478963}) = 0
clock_gettime(CLOCK_REALTIME, {1550831991, 306673933}) = 0
clock_gettime(CLOCK_REALTIME, {1550831991, 306801035}) = 0
select(0, NULL, NULL, NULL, {0, 1000})  = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 308229058}) = 0
select(0, NULL, NULL, NULL, {0, 2000})  = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {1550831991, 310676053}) = 0
```

and it continues.

### Setup

* OS: docker image:
 	linuxserver/beets:latest@sha256:7dab4fae4c9b522377f4088fe496f4d0fd94f2f6af5d64d5ac6198eb0c3dca17

* Python version: 2.7.15
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web missing lyrics discogs fromfilename edit acousticbrainz duplicates
#missing match lyrics

directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    
paths:
    default: $albumartist/$year - $album%aunique{}/$track - $title
    singleton: 00_Non-Album/$artist - $title
    comp: 01_Compilations/$year - $album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$year - $album/$track $title 
        
import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    incremental_skip_later: no
    quiet_fallback: skip
    timid: no
    log: /config/beet.log
    languages: ['pl']
    duplicate_action: ask
    bell: yes

clutter: ["Thumbs.DB", ".DS_Store"]
ignore: [".*", "*~", "System Volume Information", "lost+found"]
ignore_hidden: yes

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    
replaygain:
    auto: no

scrub:
    auto: yes

    auto: yes

missing:
    format: $albumartist - $album - $track - $title
    count: yes
    total: yes

# Inline plugin multidisc template
item_fields:
    multidisc: 1 if disctotal > 1 else 0

chroma:
    auto: no

match:
#    strong_rec_thresh: 0.17      # match 90% or better for auto import
    strong_rec_thresh: 0.17      # match 90% or better for auto import
#    medium_rec_thresh: 0.25
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.2
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30

lastgenre:
    cannonical: yes
    count: 3

musicbrainz:
    host: 172.17.0.1:5000
#    ratelimit: 2000
    ratelimit: 10
```
