### ISSUE TITLE
Switch from pyyaml to ruamel.yaml

### ISSUE THREAD

**Issue by FichteFoll** [beetbox/beets#3170]
### Problem

The config parser does not accept the `!!omap` tag for an ordered mapping.

YAML mappings are, by default unordered, so in order to ensure that a mapping is to be parsd and represented in order, one need to use the ordered map format, indicated by `!!omap` and a list of one-elemental mappings. However, this is not supported.

```sh
~ Ξ beet --version
configuration error: file /home/fichte/.config/beets/config.yaml could not be read: expected a mapping node, but found sequence
  in "/home/fichte/.config/beets/config.yaml", line 11, column 8
```

Config file:

```yaml
directory: /data/audio/music/sorted
library: /data/audio/music/sorted/musiclibrary.db

per_disc_numbering: true

import:
  copy: true
  log: beetslog.txt
paths: !!omap
  - sourcetype:Anime: '#soundtrack/%ifdef{source,$source/}$album%aunique{}%ifdef{anime, [$anime]}/$disc_and_track - $title'
  - doujin:true: "#%ifdef{touhou,touhou,doujin}\
      /$albumartist_or_label\
      /$long_date - $album%aunique{}%ifdef{event, [$event]}\
      /$disc_and_track - $title"
  - albumtype:soundtrack: '#soundtrack/%if{source,$source/}$year - $album%aunique{}/$disc_and_track - $title'
  - comp: $albumartist_or_label/$year - $album%aunique{}/$disc_and_track - $artist - $title
  - singleton: $albumartist/$title
  - default: $albumartist/$year - $album%aunique{}/$disc_and_track - $title

album_fields:
  long_date: '"-".join(f"{n:02}" for n in [year, month, day] if n)'
  soundtrack_source: 'f"{source}/" if locals().get("source", None) and source != album else ""'

item_fields:
  disc_and_track:
    f"{disc}.{track:0{max(2, len(str(tracktotal)))}}"
    if disctotal > 1
    else f"{track:0{max(2, len(str(tracktotal)))}}"
  albumartist_or_label: label if comp and label else albumartist
plugins: fetchart lastgenre missing duplicates inline replaygain

lastgenre:
  count: 1

replaygain:
  backend: gstreamer

```

Via `setup.py`, beets uses pyyaml. I'd like to suggest using [ruamel.yaml](https://pypi.org/project/ruamel.yaml/) instead, which is the only YAML 1.2 parser in Python that I know of and has been maintained for a long time. pyyaml has recently switched maintainers, but there are still many inherent problems with the distribution, most notably `yaml.load` being *unsafe* by default, and the fact it still only parses YAML1.1.
This is only a minor inconvenience as the current setup works, although it technically shouldn't be relied on by the YAML spec.

### Setup

* OS: Arch
* Python version: 3.7
* beets version: 1.4.8+ (branch referenced in #2988)
