### ISSUE TITLE
Beets album grouping issues

### ISSUE THREAD

**Issue by malan88** [beetbox/beets#3180]
I frequently seem to find that many of my albums, especially compilation albums, don't have consistent metadata (perhaps it's the album artist). For example, I have a soundtrack for [28 Days Later][0] that beets attempts to tag as though it were a directory of singletons. As such, it ends up misidentifying all of the tracks because they have so many missing tracks (this is even with chromaprint, discogs, and beatport plugins enabled).

I figured out how to get around it by being vigilant over the import, doing it manually (I have an insane amount of music so it is not at all realistic for me to do this for every case), in the case of [clicks_+_cuts][1] but it becomes prohibitively time-consuming to do it this way because for every matched track, you have to re-merge with the already-in-the-library tracks, and that seems to take as long as a normal match. Furthermore, it doesn't seem to be an accurate process, because I seem to have accidentally ended up with a split album: all the tracks for 28 Days Later have ended up in my properly (custom) set `Soundtracks` directory, but Track 13 (In Paradisum) has ended up in a single folder with the same album name in my `Compilations` directory. Presumably this is because that track was matched to a discogs release?

It would be extremely helpful if there was a way to force beets to group an album together. I speak Python (perhaps mediocre-ly), and have considered wading into your source code to try and understand it and submit a pull request for that, but it will take me quite some time.

Advice in this regard would be incredibly helpful.

[0]: https://musicbrainz.org/release/0112d2f1-f978-461e-b92f-8c9a31462d11
[1]: https://musicbrainz.org/release/81e303d6-32e5-41c3-969b-7fd811656a25

**Comment by sampsyo** [comment]
Can you describe the directory structure that leads to these problems? And give more detail about your configuration and how you're running the import? Are you using `group_albums`, for example?

This FAQ has a hint about how to convince beets to import an entire directory tree as a single album:
http://docs.beets.io/en/v1.4.7/faq.html#import-a-multi-disc-album

**Comment by malan88** [comment]
The tree structure (in an example I'm dealing with right now) is like this:

```
A Brief History of Ambient V1
├── A Brief History Of Ambient V1 Disc 1
│   ├── 1-01 Flowered Knife Shadows.mp3
│   ├── 1-02 Thru Metamorphic Rock (Edit).mp3
│   ├── 1-03 Evening Star.mp3
│   ├── 1-04 Mountain Goat.mp3
│   ├── 1-05 Sea Of Vapours.mp3
│   ├── 1-06 The Forge Of Vulcan.mp3
│   ├── 1-07 Requiem (A Floating Leaf Always.mp3
│   ├── 1-08 An Ending (Ascent).mp3
│   ├── 1-09 Marnia's Tent.mp3
│   ├── 1-10 Rapido De Noir.mp3
│   ├── 1-11 Kazoo.mp3
│   ├── 1-12 Their Memories.mp3
│   ├── 1-13 Leave Your Body.mp3
│   └── 1-14 Electric Becomes Eclectic.mp3
└── A Brief History Of Ambient V1 Disc 2
    ├── 2-01 Phaedra (Edit).mp3
    ├── 2-02 Delta Rain Dream.mp3
    ├── 2-03 The Monkey King.mp3
    ├── 2-04 Castle In The Clouds.mp3
    ├── 2-05 Life Form.mp3
    ├── 2-06 The Dance #2.mp3
    ├── 2-07 Sacred Stones.mp3
    ├── 2-08 Earth Floor.mp3
    ├── 2-09 Läuft...Heisst Das Es Läuft Ode.mp3
    ├── 2-10 Gift Of Fire.mp3
    ├── 2-11 The End Of Words.mp3
    ├── 2-12 Panorphelia.mp3
    ├── 2-13 Voices.mp3
    ├── 2-14 Träum Mal Wieder.mp3
    └── 2-15 Home.mp3
```

Which would fall under what you're mentioning, but that's not actually the issue. When doing a quiet import the output looks like this:

> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 1/1-04 Mountain Goat.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 1/1-11 Kazoo.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 1/1-08 An Ending (Ascent).mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 2/2-02 Delta Rain Dream.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 1/1-12 Their Memories.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 1/1-14 Electric Becomes Eclectic.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 2/2-15 Home.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 2/2-12 Panorphelia.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 2/2-09 Läuft...Heisst Das Es Läuft Ode.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 2/2-04 Castle In The Clouds.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 1/1-01 Flowered Knife Shadows.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 1/1-06 The Forge Of Vulcan.mp3 (1 items)
> Skipping.
> 
> /home/data/unorganizedmusic/shitfiles/Compilations-Collections/A Brief History of Ambient V1/A Brief History Of Ambient V1 Disc 2/2-05 Life Form.mp3 (1 items)

The output of `beet config` follows:

```
import:
    move: yes
    resume: yes
    write: yes
    incremental: yes
    detail: yes
    log: /home/data/music/.log
    group_albums: yes
    languages: [en]
    autotag: yes
    quiet_fallback: skip
    timid: no

match:
    strong_rec_thresh: 0.3
    distance_weights:
        missing_tracks: 0.1
art_filename: albumart
threaded: yes

plugins:
- beatport
- discogs
- chroma
- web

ui:
    color: yes

clutter:
- '*.jpg'
- '*.jpeg'
- '*.png'
- '*.gif'
- '*.zip'
- Thumbs.db
- .DS_Store

paths:
    albumtype:soundtrack: Soundtracks/$album/$track $title
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
beatport:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: beatport_token.json
    source_weight: 0.5
chroma:
    auto: yes
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
```
I could record the verbose mode output but I was having trouble teeing it to a file (I guess you're writing to `stderr`) and when I `2> output.txt` it seemed to end up being rather uninformative (my tmux session in putty right now is not letting me scroll back far enough to see much, I could be more rigorous in this if you would really like to see it).
