### ISSUE TITLE
Replaingain Python Audio Tools error

### ISSUE THREAD

**Issue by stacksjb** [beetbox/beets#3183]
### Problem

Fairly simple - I'm trying to run beets with Replaygain set to audio tools mode.

```sh
$ beet -vvv
user configuration: /home/admin/.config/beets/config.yaml
data directory: /home/admin/.config/beets
plugin paths:
Sending event: pluginload
error: replaygain initialization failed: Failed to load audiotools: audiotools not found
$
```

However, it appears that audio tools is installed and fully functional - if I run audio tools config I get: 
```
"$ audiotools-config
Default verbosity level : normal

extraction arguments
  Format Readable Writable Default Quality
  ────── ──────── ──────── ───────────────
    aiff      yes      yes
    alac      yes      yes
      au      yes      yes
    flac      yes      yes               8
     m4a      yes       no             100
     mp2      yes       no             192
     mp3      yes       no               2
     ogg      yes      yes               3
    opus       no      yes              10
     tta      yes      yes
     wav      yes      yes
      wv       no       no        standard

  Format : %(track_number)2.2d - %(track_name)s.%(suffix)s
  Default simultaneous jobs : 1
  Add ReplayGain by default : yes

ID3 arguments
    ID3v2 tag version : ID3v2.3
  ID3v2 digit padding : not padded ("1", "2", …)
    ID3v1 tag version : ID3v1.1

CD lookup arguments
     Use MusicBrainz service : yes
  Default MusicBrainz server : musicbrainz.org
    Default MusicBrainz port : 80

          Use FreeDB service : yes
       Default FreeDB server : us.freedb.org
         Default FreeDB port : 80

system arguments
       Default CD-ROM device : /dev/cdrom
   CD-ROM sample read offset : 0
  CD-ROM sample write offset : 0
    Filesystem text encoding : US-ASCII
                Audio output : NULL
$
```

### Setup

* OS: FreeBSD 11.2 (running in a FreeNAS jail - I've run Beets successfully prior, but trying to get this plugin to work) 
* Python version: 
Python 3.6.7 (default, Feb  7 2019, 01:15:19)
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): yes (obviously, it's a plugin issue :))

My configuration (output of `beet config`) is:

```
directory: /Media/Music/
library: /Media/Music/musiclibrary.db
import:
   write: yes
   move: yes
   copy: no

   autotag: yes
   timid: no

clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls"]
ignore: [".*", "*~", "System Volume Information", "lost+found"]
ignore_hidden: yes

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
path_sep_replace: _
asciify_paths: false
art_filename: cover
max_filename_length: 0


plugins: [chroma,replaygain,acousticbrainz,plexupdate,duplicates,mbcollection,lyrics]

acoustid:
   apikey: xxxxxxxx

replaygain:
   backend: audiotools

plex:
   host: x.x.x.x
   port: 32400
   token: xxxxx

mbcollection:
   auto: yes
   remove: yes
   collection: My Music

lyrics:
  fallback: ''

duplicates:
   checksum: no
```
