### ISSUE TITLE
Format string of beet list does not work

### ISSUE THREAD

**Issue by mueihn** [beetbox/beets#3193]
### Problem

On my machine, the `--format` option of `beet list` does not work as expected. Each variable in the format string seems to be expanded to the empty string.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv list --format="${album} - ${track} - ${title}: ${mb_trackid}" "album:Machine Messiah"
```

Led to this problem:

```
user configuration: /home/mue/.config/beets/config.yaml
data directory: /home/mue/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field disc_and_track
library database: /mnt/daten/musiclibrary.blb
library directory: /mnt/daten/Musik
Sending event: library_opened
 -  - : 
 -  - : 
 -  - : 
 -  - : 
 -  - : 
 -  - : 
 -  - : 
 -  - : 
 -  - : 
 -  - : 
 -  - : 
 -  - : 
Sending event: cli_exit
```

The problem does not seem to depend on which actual music files from my collection I list. It seems to be the same for all files in my collection.

### Setup

* OS: Linux, OpenSuse Tumbleweed
* Python version: 3.7.2
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/daten/Musik
library: /mnt/daten/musiclibrary.blb

import:
    copy: yes

plugins: fetchart embedart lastgenre replaygain scrub inline zero edit chroma random
replaygain:
    backend: gstreamer
    overwrite: no
    auto: yes
    targetlevel: 89
    r128: [Opus]
zero:
    fields: comments
    update_database: yes
    auto: yes
    keep_fields: []
per_disc_numbering: yes
item_fields:
    disc_and_track: (u'%i%03i' % (disc, track) if tracktotal > 99 else u'%i%02i' % (disc, track)) if disctotal > 1 else (u'%03i' % (track) if tracktotal > 99 else u'%02i' % (track))

paths:
    default: $albumartist - $album%aunique{}/$disc_and_track - $title
    comp: $albumartist - $album%aunique{}/$disc_and_track - $title
    singleton: $artist - Non-Album/$title

match:
    max_rec:
        track_title: none
        track_artist: none
        country: none
    preferred:
        countries:
        - DE
        - XE
        - GB|UK
        - US
        media: [CD, Digital Media|File]
edit:
    itemfields: track title artist album albumartist
    albumfields: album albumartist
    ignore_fields: id path
acoustid:
    apikey: REDACTED
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
pathfields: {}
album_fields: {}
chroma:
    auto: yes
scrub:
    auto: yes
```
