### ISSUE TITLE
LastGenre fetching wrong data

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#3204]
### Problem

The plugin lastgenre is fetching the wrong genre tags from last.fm for [Bob Dylan - Moonshiner ](https://www.youtube.com/watch?v=DP7TFs53J7A). 

[Last.fm-Link](https://www.last.fm/de/music/Bob+Dylan/_/Moonshiner).

It saves the genres: **Metalcore, Hardstyle, Sludge Metal**
Last.fm genres for the title are: **melancholy, beautiful, folk, ballad**

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import --from-scratch -s Moonshiner.mp3 
user configuration: /home/rain0r/config/beets/config.yaml
data directory: /home/rain0r/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (7, 0, 8))
library database: /home/rain0r/.local/share/beets/musiclibrary.blb
library directory: /mnt/archivefs/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
chroma: chroma: fingerprinted b'/mnt/archivefs/Singleton/Dylan, Bob/Moonshiner.mp3'
chroma: matched recordings ['b82fe4e9-a3de-4548-9a00-f2c5c30d44b6', 'c2cc7b83-aa55-4ce2-ac03-7291fd3b4af0', 'da8c5d85-914c-45fd-ab49-0d580f8bab40'] on releases ['31dd4719-740e-4a46-8cd3
a', '390a0ca7-8d99-4a4e-8cd2-564097ac5a83']
Looking up: /mnt/archivefs/Singleton/Dylan, Bob/Moonshiner.mp3
Searching for track ID: da8c5d85-914c-45fd-ab49-0d580f8bab40
Sending event: trackinfo_received
Track ID match.

/mnt/archivefs/Singleton/Dylan, Bob/Moonshiner.mp3
Tagging track: Bob Dylan - Moonshiner
URL:
    https://musicbrainz.org/recording/da8c5d85-914c-45fd-ab49-0d580f8bab40
(Similarity: 100.0%)
Sending event: import_task_choice
Sending event: import_task_apply
0 of 1 items replaced
Sending event: database_change
Sending event: database_change
replaygain: analyzing Bob Dylan -  - Moonshiner
replaygain: analyzing 1 files
replaygain: executing mp3gain -o -s s -k -d 0 /mnt/archivefs/Singleton/Dylan, Bob/Moonshiner.mp3
replaygain: analysis finished
Sending event: database_change
replaygain: applied track gain -2.12, peak 0.6978181004638672
lastgenre: added last.fm item genre (artist): Metalcore, Hardstyle, Sludge Metal
Sending event: database_change
Sending event: item_copied
Sending event: database_change
Sending event: write
zero: month: 0 -> None
zero: day: 0 -> None
zero: year: 0 -> None
zero: comments:  -> None
zero: grouping:  -> None
Sending event: after_write
Sending event: database_change
Sending event: import_task_files
scrub: auto-scrubbing /mnt/archivefs/music/Singleton/Dylan, Bob/Moonshiner.mp3
scrub: writing new tags after scrub
Sending event: write
zero: month: 0 -> None
zero: day: 0 -> None
zero: year: 0 -> None
zero: comments:  -> None
zero: grouping:  -> None
Sending event: after_write
Sending event: item_imported
Sending event: import
Sending event: cli_exit

```

### Setup

* OS:  Linux
* Python version: 3.6.8
* beets version: 1.4.8

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/archivefs/music
library: /home/rain0r/.local/share/beets/musiclibrary.blb

paths:
    default: $albumartist_sort/$album/$track-$albumartist - $title
    singleton: Singleton/$artist_sort/$title

plugins: chroma info play mpdstats embedart fetchart lastgenre fromfilename mbsync replaygain scrub missing zero 

play:
    command: /usr/bin/mpv $args -playlist

import:
    copy: yes
    write: yes

embedart:
    auto: yes
    ifempty: yes
    maxwidth: 640

lastgenre:
    count: 3
    source: track

zero:
    fields: month day year comments grouping
    update_database: true

replaygain:
    overwrite: yes
```
