### ISSUE TITLE
Use year in path format

### ISSUE THREAD

**Issue by KuenzelIT** [beetbox/beets#3211]
### Problem
Hi,

I'm trying to sort my music files by decade: 1980s, 1990s, 2000s, 2010s, ...

Now I have the problem that my files have no id3 tags at all. So I'm entering artist and title and select the correct song manually. Now I assumed that beets would take the information from MusicBrainz including the year to write the ID3 tags and the filename. But my ID3 tags only contain the artist and the title and my files go to a `0000` directory.

I can't find any info about why beets doesn't save the year of the song and other data in the ID3 tags (and also the path).

Do you have an idea? Thanks!

### Setup

* OS: Linux mint
* Python version:  3.6.7
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/database
library: ~/Music/database/musiclibrary.db
import:
    write: yes
    copy: yes

paths:
    default: %left{$original_year,3}0s/$artist - $title
    singleton: %left{$original_year,3}0s/$artist - $title

plugins: fromfilename chroma

match:
    required: year
```
