### ISSUE TITLE
Ä and Ö characters aren't detected on Windows, "no such file or directory" error

### ISSUE THREAD

**Issue by 07416** [beetbox/beets#3228]
### Problem

Beet doesn't detect at least the Ä and Ö characters, preventing from managing music with applicable filenames. Examples of artists with a diaeresis include Motörhead and Mötley Crüe. 

Running `beet -vv import -A "E:\CUETools\Motörhead"` in verbose (`-vv`) mode:

```sh
user configuration: C:\Users\user\AppData\Roaming\beets\config.yaml
data directory: C:\Users\user\AppData\Roaming\beets
plugin paths: C:\Users\user\beets\myplugins
Sending event: pluginload
library database: C:\Users\user\AppData\Roaming\beets\library.db
library directory: C:\Users\user\Music
Sending event: library_opened
error: no such file or directory: E:\CUETools\Motrhead
```

### Setup

* OS: Windows 10 64-bit
* Python version: Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: C:\Users\user\Music\
library: C:\Users\user\AppData\Roaming\beets\library.db

import:
    copy: no
    write: no
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
ignore: .cue .log .pdf .accurip .m3u8 .m3u .txt .nfo
art_filename: cover

plugins: convert
pluginpath: ~/beets/myplugins
threaded: yes

ui:
    color: yes

paths:
    default: $albumartist/$album/$track $title
    singleton: single songs/$artist - $title
    comp: $album/$track $title
    albumtype:soundtrack: soundtracks/$album/$track $title
convert:
    copy_album_art: yes
    embed: no
    never_convert_lossy_files: yes
    format: opus
    formats:
        opus:
            command: ffmpeg -i $source -acodec libopus -b:a 128k $dest
            extension: opus
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    dest:
    pretend: no
    threads: 8
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no

    paths: {}
    no_convert: ''
    album_art_maxwidth: 0
```
