### ISSUE TITLE
Beets repeatedly writes acoustid tag

### ISSUE THREAD

**Issue by nichobi** [beetbox/beets#3232]
### Problem

Beets writes the Acoustid tag every time I run 'beet write', despite already being correctly written to the file. I've verified that the tags are indeed identical and I've verified that xxx and yyy in the output 'acoustid_fingerprint: xxx -> yyy'  are identical. This seems to happen to both flac and MP3 files and I've verified with mid3v2 that the tag is correctly written to the file.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv write path:'Music/Bob Dylan/1991 - The Bootleg Series
, Vol. 03_ Rare & Unreleased_ 1974-1991/01 If You See Her, Say Hello.mp3'
```

Led to this problem:

```
user configuration: /home/nichobi/.config/beets/config.yaml
data directory: /home/nichobi/.config/beets
plugin paths:
Sending event: pluginload
artresizer: method is (2, (7, 0, 8))
inline: adding item field multidisc
library database: /home/nichobi/.config/beets/musiclibrary.db
library directory: /home/nichobi/Music
Sending event: library_opened
Bob Dylan - The Bootleg Series, Vol. 03: Rare & Unreleased: 1974-1991 - If You See Her, Say Hello
  acoustid_fingerprint: AQADtFKiJPmyRAnMHeWp48Fx4lLj4D3CfIEmdR5yHs3Rx7gzNEcf4_uQfD9SmSjvHI4lBw98nHnQjBnxB830Fv2PGmGeHJV4NMyF5wpywlGOn8IfnIeb5ESeSDp0uiN6I29QB-cX4Q0ZBc2PkE6gZ8vxPMjl5MLNDXvApDvqhAn2Ho8-3EFYoonuQXsRJpnoFUdzEvVPnNjBH5GeEJoyXDueaMevBI2PXnjoHPoN-4LeC7llwU3C4Rke_IfHKBYepUHOPAhz9ElxBZ96lH5i-GfQdviQ59DDBWGoq0V5PD3-RMW3IkyuQLOUPPhSPMT5ECcnNKE-TD-uHP-ROUp4bCfe4-qD70YTOkfPo37QR8jzIOfx5DDjFJeSBOfRnHHQaRmOK35w6Uf3HOZSF5WO68aTXCJyptAP5UKu4FLSg3sQJ8zx7Am0y4iUNsd1nCIeuEd8Q0-OUNQCL9NywdGL8DwH-QjlCk2V4_iaHf-DfDueQN-RP9yGaqGLMMqO5OLxw2dx2QmuR3iGhkdIP0iOT8L4J-BSU8EZ4kGdPKCu9PgUItIP_cij4yVq5ehzBUefJUfDSPhxHX8O7Z-MpurxRyaakUc7piiZH82JJ1uK72h-4YzQxNSL5MmQP7jOINYHe1OJP4SuI-1z_IhOHVr2xPCTHTkNN6vAaOkRLlbSFBeP5vguglV0IZfQHP2CUfxxBXmi4ND14nxgJjr0Fz9y9mh-hA0fXBeSjcnRxAl-_BFq0fDkHD1KJXlw9Ikk4xJyE0nPo9OZodmDf0GDXqGES8zxHhdTHon7I0xoFeWDP8Hz44e_I9ZTWNBtvKuE_kITM7h1oZQNZ-tQModcOkRFHmG2Bo-NH5eUwlQeXJnxv_COnA-eoamDUFWCnMMlO9A6pkLI4zfQvEGdBD_Ohjly6BHhZsoENU-CT3nwH440_IP-BCG7TEZDDtc9PLrQo3qO9ULJqAr-G8i6B9Tzwr-CUsacxGGKpObR_Oh1PDpeHU8yiUGsvhBxZRny5cffoR0aLksl5H6gIz1TnCFO-DhhPUJSJ0ee4UEziWlQp8az4NLxI7RIiF-OdJm4onzxj_h2xN3QQKP0IWR49Mc_JI8QOkdf3B-eH30xZVIL3g-SI1IsHpdP3LiDfnjy4Cd8pcFvWMeTECeP9k7QjH2E_MRxyTaOLvIxCn3mYjFx6YV-5GKOixReolmio1SS4XHw6_A95IdcGnnQo_nSBT_-I60MfdmPco2mIcyPH1eOH6cShD6as9A5Ir-Exzv-NPh0lEKYBzpxZmiRTlSOe_iOmifxI2R0Djq_ILxw6kSvpLjCGCWPI38gNhqFXCquozya_vgeJBeHkAwL88mKR1PgM7iTGx-D4-4KnzAuizAfhDyS_sVT5nhwlA_eo49iI48IfdNxx_gRZrkw8akIntmE69YRiclhvci3MEQjPwje5XiFNTykL5jYIwzj40ofw19wnzjMJDkeHJ8IP8hzfIwTqNmIND-uHn8TPOLRM2i64MTDxXijjbiFUIf4SAgXlsF_lFIuWCxeCY_xRwtuw6-F0BahascTHX2KMB_uGfeQZ4xxrqjRNMVn_GjGw1KiEeEmKcf14Al5-MxxKTi-zBFKtrCN0OqN7_iD6jm04zuuQ-tyBV_G4L8IsQiP_zhOScbxN4rwXETCqshxmai0ZBzM3MZ79JQWTC-aJgy-C9yP50XE44cWTaE0VM-R3_iHWj7hHfuDM68G6jV2CVWPI8fFbMcfPBnhLgn048zyw8yR78JFB0-yDK6PE3fQH43G4A0PH3-C48zxHy2PZsMl4kyy40h2BjlK4ZPwfWiePagWMRw-HqeMPkGY43kEXXtwMz3CMYfTHn2FZ8eZE3kZKniu4JjCBSWlFNn7oU-PpuqDY5J4WMJlDf2MN3hwvcGuHE1_VCeexgUdG-XUDVePhLeIkMfxfviJ5kEp9eAUScglQ25-hDJDgUnTFlceeOeCJD_CrIuJ_geaKkf_4CSeXE8RWifRPGUCXUczLQu0E3mOS1dgn3gU6rhDNJ_hN8PUywizHoliHnWKJk-DZz148TieCPOD2xr-oJcQ0YIWHXFDB3OOiznRzTma40dy5OrxJXh-XG_Rn0GqvUjmZDhpoQwXEf6O0-hDXBk6XfB23EPPHnkLvQhTG71wXkWPZszx4LmFMyHeHOZzXA92pUK2n2jkBQqZUvgXwsuYG3nhnpiU5vgFzsf2BRfyRMrxBycdoVkXVC-FM4V8oR-ay4h7mBxOPRKeoyeaBx_ORCKc5eJxJgvRqDuSIQ-8Hk8mZQqqo7mEF8cl68h36MlS5FcP48eN_BYaMx10Ho40JUR_6OiXHGHG7DhrJTgatM_xRFUQSvwCHTlzNE5m_DmuwxVxI0-GZBKVo0ku4h8eP0abNGie40F-6PJRJ1Jy-Ohxhnh7qEf64ENjfaj-DD_6JEfDv8htNGMQ6dyOJnfAPMGuk_iD48eTI-eWIxm_w8uEKlZe7BeFfxL4OtgPP8g1JFcaNAkrosQ344c5rviRR0LTTdCYQzEf4q0C6jl-7Id2NmguxcOP6XGMhpMaBVyaH5OkQ8uDPMfxHPkCneIRNi8uFQ_MK0LJFedxLdORnkdyHVey4lFyNEHPGR_CrzOaK5OguRG0bEmOnMc_Hm8ZVDpnXELb48dVTGFQXgGfRUsQfoKi7EK-BBefDE3ydMVFEiEVHT_0HtHzDA5_kEd_bKGEOm2O6zi1B3WSEWYoo2cc5D00NwGADHCKAWGEQFABqRARCgDCMAOGASGMIEwJpQQRzjACBABEASMIEEApYYCWBjhCBHYBAGYJFoARgwwwDABBBBEMBCGAMAghJoQATBkhDDAKIUEIAYABwBAkyiBlBDBCCSEUVUooaAAhgBJBCCBME2CA4EQgRAwgxhCFEGXCIEAEgAoUZAAQQBIqBCMAFEEMA0ywJgQhhggkLBOAKScIGUph4IQAQBAAAAKAECUIA0YIQZwEhgBCFAAMAAGoAIgYjYhAEDkkCDBEGMkIMAIAS6RhwiijtAJAQAAIEcYAAYBwxjhgkAACCGIIIMpIgQwygBAFGACUKYAIEV44Y4QBChBFBJLgIACEYAABgQQQlAoECEACCQQM4JAwEIARhRCnsAAIEGGIUQQJqAhggAghFBhEUOoUIooAIxAQQDDgAnOCAOOMgw5RAAByRAjBkAFCAAEcAAoRZ5wQDAACjDEIEeeYEEwBIAACBDihjBBACqUMAQIAYEkTBEhDAEDIGSEIAAgMIAgQgBBDCDOCEECAAIAgIx4iigCFDCEECEwIM8AAQIghQABEkBKACgIpcQYwCAAgygAnGBPECAkccAYIYgBERAIBCEOEMMEQRIYhjIlgTjgBCLAEAMkEDMAAAwgBAAqEkGPAGEAQM6ABIghCTDClgTBAEIEUIAAQIIQSlCAijFECCCPEAYw64gACggMkkDcEQIGBIQIhAYQRhBgBAAAGCOGUIYYACARhyhgAiFDEIWgABAAIDBwzgBgBABEAEACkIEwhIhQCwDEAjgICAAGcEYAogBBhCgsoiBIEMCAII4IRgRgBgBjFhARMAkCAEQJQIgRBQDgvnAAGGGawAswAhZhihDEDAKEEAMMwxEwAIYggxBkAiBLEACGgkV4woYBAwgAEBGMIMQANAUgYhgCT1ghAgAICAGTEMgwwQj1CQBEACAMCCUsIEgoAIQRIkihHhCDAECQNA0YwABwxRAIihCAA -> AQADtFKiJPmyRAnMHeWp48Fx4lLj4D3CfIEmdR5yHs3Rx7gzNEcf4_uQfD9SmSjvHI4lBw98nHnQjBnxB830Fv2PGmGeHJV4NMyF5wpywlGOn8IfnIeb5ESeSDp0uiN6I29QB-cX4Q0ZBc2PkE6gZ8vxPMjl5MLNDXvApDvqhAn2Ho8-3EFYoonuQXsRJpnoFUdzEvVPnNjBH5GeEJoyXDueaMevBI2PXnjoHPoN-4LeC7llwU3C4Rke_IfHKBYepUHOPAhz9ElxBZ96lH5i-GfQdviQ59DDBWGoq0V5PD3-RMW3IkyuQLOUPPhSPMT5ECcnNKE-TD-uHP-ROUp4bCfe4-qD70YTOkfPo37QR8jzIOfx5DDjFJeSBOfRnHHQaRmOK35w6Uf3HOZSF5WO68aTXCJyptAP5UKu4FLSg3sQJ8zx7Am0y4iUNsd1nCIeuEd8Q0-OUNQCL9NywdGL8DwH-QjlCk2V4_iaHf-DfDueQN-RP9yGaqGLMMqO5OLxw2dx2QmuR3iGhkdIP0iOT8L4J-BSU8EZ4kGdPKCu9PgUItIP_cij4yVq5ehzBUefJUfDSPhxHX8O7Z-MpurxRyaakUc7piiZH82JJ1uK72h-4YzQxNSL5MmQP7jOINYHe1OJP4SuI-1z_IhOHVr2xPCTHTkNN6vAaOkRLlbSFBeP5vguglV0IZfQHP2CUfxxBXmi4ND14nxgJjr0Fz9y9mh-hA0fXBeSjcnRxAl-_BFq0fDkHD1KJXlw9Ikk4xJyE0nPo9OZodmDf0GDXqGES8zxHhdTHon7I0xoFeWDP8Hz44e_I9ZTWNBtvKuE_kITM7h1oZQNZ-tQModcOkRFHmG2Bo-NH5eUwlQeXJnxv_COnA-eoamDUFWCnMMlO9A6pkLI4zfQvEGdBD_Ohjly6BHhZsoENU-CT3nwH440_IP-BCG7TEZDDtc9PLrQo3qO9ULJqAr-G8i6B9Tzwr-CUsacxGGKpObR_Oh1PDpeHU8yiUGsvhBxZRny5cffoR0aLksl5H6gIz1TnCFO-DhhPUJSJ0ee4UEziWlQp8az4NLxI7RIiF-OdJm4onzxj_h2xN3QQKP0IWR49Mc_JI8QOkdf3B-eH30xZVIL3g-SI1IsHpdP3LiDfnjy4Cd8pcFvWMeTECeP9k7QjH2E_MRxyTaOLvIxCn3mYjFx6YV-5GKOixReolmio1SS4XHw6_A95IdcGnnQo_nSBT_-I60MfdmPco2mIcyPH1eOH6cShD6as9A5Ir-Exzv-NPh0lEKYBzpxZmiRTlSOe_iOmifxI2R0Djq_ILxw6kSvpLjCGCWPI38gNhqFXCquozya_vgeJBeHkAwL88mKR1PgM7iTGx-D4-4KnzAuizAfhDyS_sVT5nhwlA_eo49iI48IfdNxx_gRZrkw8akIntmE69YRiclhvci3MEQjPwje5XiFNTykL5jYIwzj40ofw19wnzjMJDkeHJ8IP8hzfIwTqNmIND-uHn8TPOLRM2i64MTDxXijjbiFUIf4SAgXlsF_lFIuWCxeCY_xRwtuw6-F0BahascTHX2KMB_uGfeQZ4xxrqjRNMVn_GjGw1KiEeEmKcf14Al5-MxxKTi-zBFKtrCN0OqN7_iD6jm04zuuQ-tyBV_G4L8IsQiP_zhOScbxN4rwXETCqshxmai0ZBzM3MZ79JQWTC-aJgy-C9yP50XE44cWTaE0VM-R3_iHWj7hHfuDM68G6jV2CVWPI8fFbMcfPBnhLgn048zyw8yR78JFB0-yDK6PE3fQH43G4A0PH3-C48zxHy2PZsMl4kyy40h2BjlK4ZPwfWiePagWMRw-HqeMPkGY43kEXXtwMz3CMYfTHn2FZ8eZE3kZKniu4JjCBSWlFNn7oU-PpuqDY5J4WMJlDf2MN3hwvcGuHE1_VCeexgUdG-XUDVePhLeIkMfxfviJ5kEp9eAUScglQ25-hDJDgUnTFlceeOeCJD_CrIuJ_geaKkf_4CSeXE8RWifRPGUCXUczLQu0E3mOS1dgn3gU6rhDNJ_hN8PUywizHoliHnWKJk-DZz148TieCPOD2xr-oJcQ0YIWHXFDB3OOiznRzTma40dy5OrxJXh-XG_Rn0GqvUjmZDhpoQwXEf6O0-hDXBk6XfB23EPPHnkLvQhTG71wXkWPZszx4LmFMyHeHOZzXA92pUK2n2jkBQqZUvgXwsuYG3nhnpiU5vgFzsf2BRfyRMrxBycdoVkXVC-FM4V8oR-ay4h7mBxOPRKeoyeaBx_ORCKc5eJxJgvRqDuSIQ-8Hk8mZQqqo7mEF8cl68h36MlS5FcP48eN_BYaMx10Ho40JUR_6OiXHGHG7DhrJTgatM_xRFUQSvwCHTlzNE5m_DmuwxVxI0-GZBKVo0ku4h8eP0abNGie40F-6PJRJ1Jy-Ohxhnh7qEf64ENjfaj-DD_6JEfDv8htNGMQ6dyOJnfAPMGuk_iD48eTI-eWIxm_w8uEKlZe7BeFfxL4OtgPP8g1JFcaNAkrosQ344c5rviRR0LTTdCYQzEf4q0C6jl-7Id2NmguxcOP6XGMhpMaBVyaH5OkQ8uDPMfxHPkCneIRNi8uFQ_MK0LJFedxLdORnkdyHVey4lFyNEHPGR_CrzOaK5OguRG0bEmOnMc_Hm8ZVDpnXELb48dVTGFQXgGfRUsQfoKi7EK-BBefDE3ydMVFEiEVHT_0HtHzDA5_kEd_bKGEOm2O6zi1B3WSEWYoo2cc5D00NwGADHCKAWGEQFABqRARCgDCMAOGASGMIEwJpQQRzjACBABEASMIEEApYYCWBjhCBHYBAGYJFoARgwwwDABBBBEMBCGAMAghJoQATBkhDDAKIUEIAYABwBAkyiBlBDBCCSEUVUooaAAhgBJBCCBME2CA4EQgRAwgxhCFEGXCIEAEgAoUZAAQQBIqBCMAFEEMA0ywJgQhhggkLBOAKScIGUph4IQAQBAAAAKAECUIA0YIQZwEhgBCFAAMAAGoAIgYjYhAEDkkCDBEGMkIMAIAS6RhwiijtAJAQAAIEcYAAYBwxjhgkAACCGIIIMpIgQwygBAFGACUKYAIEV44Y4QBChBFBJLgIACEYAABgQQQlAoECEACCQQM4JAwEIARhRCnsAAIEGGIUQQJqAhggAghFBhEUOoUIooAIxAQQDDgAnOCAOOMgw5RAAByRAjBkAFCAAEcAAoRZ5wQDAACjDEIEeeYEEwBIAACBDihjBBACqUMAQIAYEkTBEhDAEDIGSEIAAgMIAgQgBBDCDOCEECAAIAgIx4iigCFDCEECEwIM8AAQIghQABEkBKACgIpcQYwCAAgygAnGBPECAkccAYIYgBERAIBCEOEMMEQRIYhjIlgTjgBCLAEAMkEDMAAAwgBAAqEkGPAGEAQM6ABIghCTDClgTBAEIEUIAAQIIQSlCAijFECCCPEAYw64gACggMkkDcEQIGBIQIhAYQRhBgBAAAGCOGUIYYACARhyhgAiFDEIWgABAAIDBwzgBgBABEAEACkIEwhIhQCwDEAjgICAAGcEYAogBBhCgsoiBIEMCAII4IRgRgBgBjFhARMAkCAEQJQIgRBQDgvnAAGGGawAswAhZhihDEDAKEEAMMwxEwAIYggxBkAiBLEACGgkV4woYBAwgAEBGMIMQANAUgYhgCT1ghAgAICAGTEMgwwQj1CQBEACAMCCUsIEgoAIQRIkihHhCDAECQNA0YwABwxRAIihCAA
  Sending event: write
  Sending event: after_write
  Sending event: database_change
  Sending event: cli_exit
```

### Setup

* OS: Arch
* Python version: 3.7.3
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music
library: ~/.config/beets/musiclibrary.db

import:
    move: yes
    log: ~/.config/beets/imports.log

plugins: missing duplicates bandcamp discogs inline edit follow random the artistcountry replaygain fromfilename fetchart embedart chroma

paths:
    default: '%the{$albumartist}/%if{$original_year,$original_year,$year} - $album%aunique{}/%if{$multidisc,Disc $disc/}$track $title'
    singleton: '%the{$artist}/Non-Album/$title'
item_fields:
    multidisc: 1 if disctotal > 1 else 0
replaygain:
    backend: gstreamer
    overwrite: no
    auto: yes
    targetlevel: 89
    r128: [Opus]
fetchart:
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - wikipedia
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
embedart:
    maxwidth: 600
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
acoustid:
    apikey: REDACTED
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
bandcamp:
    source_weight: 0.5
    min_candidates: 5
    lyrics: no
    art: no
    split_artist_title: no
chroma:
    auto: yes
missing:
    count: no
    total: no
    album: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
follow:
    auto: no
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
pathfields: {}
album_fields: {}
```
