### ISSUE TITLE
`beet ls`: Umlauts are not case-insensitive.

### ISSUE THREAD

**Issue by dertuxmalwieder** [beetbox/beets#3249]
### Problem

It seems that beet's `ls` function is only case-insensitive *unless* German umlauts are involved:

> $ beet ls Ärzte Vegas
> Die Ärzte - 13 - Nie wieder Krieg, nie mehr Las Vegas!
> Die Ärzte - Runter mit den Spendierhosen, Unsichtbarer! - Las Vegas
> Die Ärzte - Wir wollen nur deine Seele - Nie Wieder Krieg, Nie Wieder Las Vegas
> $ beet ls Ärzte vegas
> Die Ärzte - 13 - Nie wieder Krieg, nie mehr Las Vegas!
> Die Ärzte - Runter mit den Spendierhosen, Unsichtbarer! - Las Vegas
> Die Ärzte - Wir wollen nur deine Seele - Nie Wieder Krieg, Nie Wieder Las Vegas
> $ beet ls ärzte Vegas
> $

One would think that they all have the same results.

### Setup

* OS: Windows 10
* Python version: 3.7.3
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: F:\musik

plugins: bpd embedart fetchart chroma discogs zero importadded
threaded: yes

paths:
    default: $albumartist/$album/$track. $title
    singleton: $artist/$title

import:
    move: yes
    resume: yes
    autotag: yes
    incremental: yes
embedart:
    remove_art_file: yes
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
zero:
    fields: month day genre comments
    update_database: yes
    comments:
    - EAC
    - LAME
    - from.+collection
    - ripped by
    - bandcamp.com
    auto: yes
    keep_fields: []
importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes
bpd:
    host: ''
    port: 6600
    control_port: 6601
    password: REDACTED
    volume: 100
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
chroma:
    auto: yes
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
```
