### ISSUE TITLE
play: mpv not parsing directory path correctly

### ISSUE THREAD

**Issue by enzelb** [beetbox/beets#3253]
The expected behavior of the `play` plugin should be to run `mpv` (and any `$args`) then to "paste" the path of the query.

Note that I'm also using the `raw: yes` option in my `config.yaml`. Otherwise the mpv CLI wouldn't allow any inputs (pause, scrub forward, etc.) when playing the temporary .m3u files.

I believe that the problem has somewhat to do with mpv as well, as it will only take a string in the format: `"G:\Music\Chance the Rapper\random.mp3"`, whereas from my understanding, beets will only output the byte(?)/string as `'G:\Music\Chance the Rapper\random.mp3'`. This leads to `mpv` as parsing the input as the commands:

* `mpv 'G:\Music\Chance'`
* `mpv 'the'`
* `mpv 'Rapper\random.mp3'`

Admittedly, I don't know much about python (yet), but this is my understanding of the issue. If there was some way to configure the play command option like:

```yaml
play:
    command: mpv $args $query
```
or
```yaml
play:
    command: mpv $args "$query"
```
I also attempted to do some string magic in the `play.py` to replace the `'` with `"`, but gave up due to a lack of knowledge in string/byte manipulation.

It appears that this issue is also related to #2208 and #2717 . Maybe a better `command` configuration is all that we need?

Running `mpv` though the command line

` mpv "G:\Music\Chance the Rapper\random.mp3" `

functions as intended.

____

Some relevant pages that I was going though:

* https://beets.readthedocs.io/en/v1.4.7/plugins/play.html
* https://mpv.io/manual/master/#escaping-spaces-and-other-special-characters
___
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv play "long time II"
user configuration: C:\Users\enzel\AppData\Roaming\beets\config.yaml
data directory: C:\Users\enzel\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: G:\Music\musiclibrary.db
library directory: G:\Music
Sending event: library_opened
Playing 1 track.
play: executing command: mpv [b'G:\\Music\\Chance the Rapper\\10 Day\\12 Long Time II.mp3']
```
*note the `[b'` and `']` surrounding the path
___

Led to this problem:

```
Playing: G:\Music\Chance
[file] Cannot open file 'G:\Music\Chance': No such file or directory
Failed to open G:\Music\Chance.

Playing: the
[file] Cannot open file 'the': No such file or directory
Failed to open the.

Playing: Rapper\10
[file] Cannot open file 'Rapper\10': Invalid argument
Failed to open Rapper\10.

Playing: Day\12
[file] Cannot open file 'Day\12': Invalid argument
Failed to open Day\12.

Playing: Long
[file] Cannot open file 'Long': No such file or directory
Failed to open Long.

Playing: Time
[file] Cannot open file 'Time': No such file or directory
Failed to open Time.

Auto-loading profile 'extension.mp3'
Playing: II.mp3
[file] Cannot open file 'II.mp3': No such file or directory
Failed to open II.mp3.


Exiting... (Errors when loading file)
```

### Setup

* OS: Windows 10 Home 1809 (17763.475)
* Python version: 3.7.2
* beets version:  1.4.7
* Turning off plugins made problem go away (yes/no): no
* using the Cmder consule emulator

My configuration (output of `beet config`) is:

```yaml
directory: G:\Music
library: G:\Music\musiclibrary.db

import:
    copy: no
    move: yes

plugins: play smartplaylist embedart
play:
    command: mpv $args
    raw: yes
    use_folders: no
    relative_to:
    warning_threshold: 100
embedart:
    auto: yes
    ifempty: yes
    maxwidth: 0
    compare_threshold: 0
    remove_art_file: no
smartplaylist:
    relative_to:
    playlist_dir: .
    auto: yes
    playlists: []
```
