### ISSUE TITLE
"embedart: ImageMagick 6.8.7 or higher not installed" but 6.9.7 installed

### ISSUE THREAD

**Issue by apiontek** [beetbox/beets#3274]
### Problem

I just upgraded to 1.4.8 today, and now when I run any beet operation, I see:

```
embedart: ImageMagick 6.8.7 or higher not installed; 'compare_threshold' option ignored
```

But I have ImageMagick 6.9.7-4:

```sh
$ which convert
/usr/bin/convert
$ convert -version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

### Setup

* OS: Ubuntu 18.04.2 LTS
* Python version: Python 3.6.3
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): probably could disable embedart but I don't want to.

My configuration (output of `beet config`) is:

```yaml
embedart:
    compare_threshold: 0
    maxwidth: 0
    auto: yes
    ifempty: no
    remove_art_file: no
lyrics:
    bing_lang_from: []
    google_API_key: REDACTED
    sources: google lyricwiki lyrics.com genius musixmatch
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
directory: /tank/media/music/archive/
library: /tank/media/music/beetsdata/musiclibrary.db

import:
    copy: no
    move: yes
    write: yes
    resume: no
asciify_paths: yes

paths:
    default: $albumartist/$year $album%aunique{}/$track $title
    singleton: Non-Album/$artist/$year $title
    comp: Compilations/$year $album%aunique{}/$track $title

format_item: $albumartist ($year) $album; $track $artist - $title [$format, $bitrate, $filesize, $length]
format_album: $albumartist ($year) $album

plugins: ftintitle discogs fetchart embedart lastgenre lyrics missing random spotify duplicates badfiles mbsync plexupdate subsonicupdate scrub fuzzy info export follow zero bandcamp web
fetchart:
    minwidth: 100
    enforce_ratio: 1%
    sources: itunes amazon google wikipedia coverart albumart filesystem *
    fanarttv_key: REDACTED
    store_source: yes
    auto: yes
    maxwidth: 0
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
plex:
    host: 172.22.1.10
    port: 32400
    token: REDACTED
    library_name: Music
follow:
    email: REDACTED
    password: REDACTED
    userid: REDACTED
    auto: no
missing:
    format: $albumartist ($year) $album; $artist - $title
    count: no
    total: no
    album: no
zero:
    fields: month day comments
    comments:
    - EAC
    - LAME
    - from.+collection
    - ripped by
    update_database: yes
    auto: yes
    keep_fields: []
web:
    host: 0.0.0.0
    reverse_proxy: yes
    port: 8337
    cors: ''
    cors_supports_credentials: no
    include_paths: no
spotify:
    mode: open
    region_filter: US
    show_failures: yes
    tiebreak: first
    artist_field: albumartist
    album_field: album
    track_field: title
    regex: []
    client_id: 4e414367a1d14c75a5c5129a627fcab8
    client_secret: REDACTED
    tokenfile: spotify_token.json
    source_weight: 0.5
bandcamp:
    lyrics: yes
    art: yes
    source_weight: 0.5
    min_candidates: 5
    split_artist_title: no
subsonic:
    host: 127.0.0.1
    port: 8080
    user: adam
    pass: REDACTED
    contextpath: /sonic
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
scrub:
    auto: yes
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
fuzzy:
    prefix: '~'
    threshold: 0.7
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
export:
    default_format: json
    json:
        formatting:
            ensure_ascii: no
            indent: 4
            separators: [',', ': ']
```
