### ISSUE TITLE
Failure embedding large cover art files in audio files

### ISSUE THREAD

**Issue by TastyDucks** [beetbox/beets#3284]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv embedart mel durham
```

Led to this problem:

```
Modify artwork for 1 album (Y/n)? Y
embedart: Embedding album art into Mel Durham - Skillet Fork - The Southern Illinois Tunes of Mel Durham
embedart: embedding /home/tastyducks/Music/FLAC/Mel Durham/2003-00-00 — Skillet Fork - The Southern Illinois Tunes of Mel Durham/cover.png
Sending event: write
save failed: block is too long to write
error writing /home/tastyducks/Music/FLAC/Mel Durham/2003-00-00 — Skillet Fork - The Southern Illinois Tunes of Mel Durham/01. Going to the Free State.flac: block is too long to write
[...]
```

Here's a link to the music files that trigger the bug (if relevant):

Audio file: http://pkre.co/Dump/01.%20Going%20to%20the%20Free%20State.flac
Cover art: http://pkre.co/Dump/cover.png

### Setup

* OS: Manjaro + KDE
* Python version: 3.7.3
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): Disabling `embedart` stopped the message from appearing; but I want the cover art to be embedded in the audio files.

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/FLAC
library: ~/Music/FLAC/MusicLibrary.db

plugins: fetchart embedart convert lyrics scrub

import:
    move: yes

ui:
    color: yes

threaded: yes    

original_date: yes

paths:
    default: "$albumartist/$original_year-$original_month-$original_day — $album%aunique{}/$track. $title"
    singleton: "#Non-Album/$albumartist/$original_year-$original_month-$original_day/$track. $title"
    comp: "#Compilations/$albumartist/$original_year-$original_month-$original_day — $album%aunique{}/$track. $title"

fetchart:
    enforce_ratio: 100px
    sources: filesystem itunes amazon albumart coverart

embedart:
    auto: yes

convert:
    dest: ~/Music/MP3 Transcodes

bell: yes
```

I am aware that the cover art has a huge file size; it's a raw 600-DPI scan. The error message just seems a bit obtuse to me. Is this caused by a limitation with the FLAC container, or is the size limitation being imposed arbitrarily by beets or one of its dependencies?
Thanks.
