### ISSUE TITLE
title case kept lower when following a special character

### ISSUE THREAD

**Issue by doucheymcdoucherson** [beetbox/beets#3298]
Using the `%title` Title Case function in the path, it looks like characters that are preceded by a non-alpha are not changed. 

For example:

The Album Title `Childish Gambino - 2016 - “awaken, My Love!”` where `%title{$album%aunique{}}` is defined in the default path. The "a" in awaken is preceded by a quote character. 

Another example, the track name `08 - Bow Shock (interlude).mp3` where `$track - %title{$title}` is defined. 

Not sure if this is a known issue or not? Any workarounds if known?

Thanks!

Snippet from my config.yaml if it's helpful:

```
paths:
    default: $albumartist - $original_year - %title{$album%aunique{}} %upper{$albumtype_EP}%title{$albumtype_Single}%if{$multidisc,(Disc $disc)}/$track - %title{$title}
    singleton: Non-Album/$artist - $title
    comp: \#VA/$album%aunique{} - $original_year/$track - $artist - $title

plugins: lastgenre fetchart replaygain scrub discogs ftintitle beatport smartplaylist inline

item_fields:
    albumtype_EP: u'(' + albumtype + u')' if albumtype == 'ep' else ''
    albumtype_Single: u'(' + albumtype + u')' if albumtype == 'single' else ''
    multidisc: 1 if disctotal > 1 else 0
```
