### ISSUE TITLE
remove a singleton named as "_" 

### ISSUE THREAD

**Issue by daviddoji** [beetbox/beets#3312]
During import, some Singletons were classified as "_.mp3", "_.1.mp3", ...
I'm trying to get rid of them, but it seems that beet can't find them.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
beet -vv remove _.1.mp3                               :(
```

Led to this problem:

```
user configuration: /home/david/.config/beets/config.yaml
data directory: /home/david/.config/beets
plugin paths: 
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: /datos/Music/musiclibrary.db
library directory: /datos/Music
Sending event: library_opened
error: No matching items found.
```

### Setup

* OS: ArchLinux
* Python version: 3.7.3
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    sources:
    - google
    - lyricwiki
    - musixmatch
    - genius
directory: /datos/Music
library: /datos/Music/musiclibrary.db

import:
    move: yes

plugins: fetchart lyrics lastgenre inline web edit play
fetchart:
    cautious: yes
    cover_names: front back
    sources: amazon *
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    google_key: REDACTED
    google_engine: 001442825323XXXXXXXX:hxxxxxxxx
    fanarttv_key: REDACTED
    store_source: no
web:
    host: 0.0.0.0
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
play:
    command: /usr/bin/clementine
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
    bom: no

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

paths:
    albumtype:english: English/$albumartist/$album%aunique{}/$track $title
    albumtype:spanish: Spanish/$albumartist/$album%aunique{}/$track $title
    albumtype:french: French/$albumartist/$album%aunique{}/$track $title
    albumtype:german: German/$albumartist/$album%aunique{}/$track $title
    albumtype:electronic: Electronic/$albumartist/$album%aunique{}/$track $title
    albumtype:misc: Miscellaneous/$albumartist/$album%aunique{}/$track $title
    albumtype:singleton: Singletons/$artist - $title
pathfields: {}
item_fields: {}
album_fields: {}
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path

```
