### ISSUE TITLE
beet config -e doesn't consider $BEETSDIR

### ISSUE THREAD

**Issue by Abbotta4** [beetbox/beets#3323]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv config -e
```

Led to this problem:

```
error: Could not edit configuration: [Errno 2] No such file or directory
```

I can edit the file with the same user using
```sh
$ emacs /srv/beets/config.yaml
```
without any permissions issues, so I would guess that `beet config -e` isn't reading `$BEETSDIR`.
### Setup

* OS: Arch Linux
* Python version: Python 3.7.3
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml

plugins: discogs fetchart scrub follow chroma acousticbrainz
library: /srv/beets/library.db
directory: /dev/null

import:
    copy: no
    move: no
    link: no
    hardlink: no
    incremental: yes
    incremental_skip_later: yes
    from_scratch: yes
    timid: yes
    group_albums: yes
    log: /srv/beets/beets.log
    bell: no

ui:
    color: yes

paths:
    default: '%first{$albumartist}/$album ($year)/$track $title'
    comp: Various Artists/$album ($year)/$track $title

match:
    ignored_media:
    - Data CD
    - DVD
    - DVD-Video
    - Blu-ray
    - HD-DVD
    - VCD
    - SVCD
    - UMD
    - VHS
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
fetchart:
    auto: yes
    minwidth: 500
    maxwidth: 500
    sources: filesystem google
    google_key: REDACTED
    store_source: yes
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
scrub:
    auto: no
follow:
    email: REDACTED
    password: REDACTED
    userid: REDACTED
    auto: no
chroma:
    auto: no
acousticbrainz:
    auto: yes
    force: no
    tags: []
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
```
