### ISSUE TITLE
Referencing Playlist Fails To Return Playlist

### ISSUE THREAD

**Issue by rsgca** [beetbox/beets#3325]
Attempting to reference a playlist in my playlist directory doesn't return the playlist contents.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv ls playlist:Soul
```

Led to this problem:

```sh
user configuration: /home/rsgca/.config/beets/config.yaml
data directory: /home/rsgca/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/rsgca/.config/beets/musiclibrary.db
library directory: /media/Storage/Music/Media
Sending event: library_opened
Sending event: cli_exit
```

Here's a link to the music files that trigger the bug (if relevant): N/A

### Setup

* OS: Ubuntu 19.04
* Python version: Python 2.7.16
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /media/Storage/Music/Media

import:
    copy: no
    write: no
    autotag: no
    incremental: yes
    log: ~/Desktop/beets.log
smartplaylist:
    auto: no
    playlist_dir: /media/Storage/Music/PlaylistsBeets
    playlists: [{name: classical.m3u, query: 'genre:classical'}, {name: Soul.m3u, query: 'genre:"Soul"'}]
    relative_to:
library: /home/rsgca/.config/beets/musiclibrary.db

plugins: info smartplaylist

```
Also want to confirm that the playlist queried exists:

```sh
ls -al /media/Storage/Music/PlaylistsBeets/
```
returns

```sh
Alternative.m3u               Folk.m3u                          Lecture.m3u   Rock.m3u
Christmas.m3u                'Hip Hop.m3u'                      Metal.m3u     Soul.m3u
Classical.m3u                'Instrumental Not Classical.m3u'   Party.m3u     Soundtrack.m3u
Country.m3u                   Instrumental.m3u                  Pop.m3u       Vocal.m3u
'Default Not Beatles.m3u'     'Jazz Instrumental.m3u'            Punk.m3u      World.m3u
'Default Not Classical.m3u'   'Jazz Vocal.m3u'                  'R&B.m3u'
'Default Not Soundtrack.m3u'   Jazz.m3u                          Rap.m3u
Default.m3u                  'Lecture Leadership'               Reggae.m3u

```
