### ISSUE TITLE
Recompress FLAC albums before adding them to the library

### ISSUE THREAD

**Issue by fturco** [beetbox/beets#3328]
I'm trying to use beets to automatically recompress my FLAC albums before adding them to the library. It's a FLAC to FLAC conversion. I'd like to use the maximum compression ratio (`--best` option). Currently there's a `convert` plugin for beets that seems to work only with music already in the library.

Is beets the right tool for the job? Or should I manually recompress music with some custom script before adding to the beets library?

**Comment by sampsyo** [comment]
The `convert` plugin is indeed what you want! Have you checked out its `auto` mode?

**Comment by fturco** [comment]
I tried the following configuration, but it seems it doesn't work:

```
convert:
  auto: yes
  format: flac
  formats:
    flac:
      command: flac --best --verify $source
      extension: flac
```

Am I missing something?
