### ISSUE TITLE
replaygain ffmpeg backend: ffmpeg exited with status 1

### ISSUE THREAD

**Issue by samuelnilsson** [beetbox/beets#3341]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv replaygain -f
```

Led to this problem:

```
user configuration: /home/samuel/.config/beets/config.yaml
data directory: /home/samuel/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/samuel/.config/beets/library.db
library directory: /home/samuel/Music
Sending event: library_opened
replaygain: analyzing Air - Moon Safari - Sexy Boy
replaygain: analyzing Air - Moon Safari - Sexy Boy
replaygain: executing ffmpeg -nostats -hide_banner -i /home/samuel/Music/02.flac -map a:0 -filter ebur128=peak=true -f null -
replaygain: ReplayGain error: ffmpeg exited with status 1
Sending event: cli_exit
```
When running the ffmpeg command above manually there is no error.

### Setup

* OS: Linux X240 5.2.5-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 31 08:30:34 UTC 2019 x86_64 GNU/Linux
* Python version: 3.7.4
* beets version: 1.5.0 (c74c9a46a9026c3c550c0c75d12eaf5dee854c5a)
* Turning off plugins made problem go away (yes/no): The error is in a plugin

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music
write: yes
move: yes

plugins: replaygain

paths:
    default: $track
replaygain:
    backend: ffmpeg
    overwrite: no
    auto: yes
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
```
