### ISSUE TITLE
Dynamic left-padding of track numbers

### ISSUE THREAD

**Issue by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [beetbox/beets#3352]
I noticed that importing an album with >99 tracks will cause an inconsistency in left-padding track numbers.

```
'09 Enemy Approaching.opus'
'100 MEGALOVANIA.opus'
'101 Good Night.opus'
'10 Ghost Fight.opus'
'11 Determination.opus'
'12 Home.opus'
```

This also makes ncmpcpp think that Megalovania is the 10th track.

I think beets should make sure that the zero padding scales up beyond >99 tracks.

### Setup

* OS: Arch Linux
* Python version: 3.7.4
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music
library: ~/Music/beetslibrary.db
import:
  write: yes
  move: yes
  resume: no
match:
  distance_weights:
    missing_tracks: 0
    date: 10
    artist: 10
    title: 10
    length: 10
paths:
    default: $albumartist/$original_year $album%aunique{}/$track $title
    singleton: $artist/Non-Album/$original_year $title
    comp: Compilations/$album%aunique{}/$track $title
```

**Comment by jackwilsdon** [comment]
It seems that we set the `track` field to be a padded integer with a length of two - changing this would probably end up making a mess and most people probably don't need 3 digit track numbers.

Off the top of my head, we could maybe add a new template function for left padding text, such that the user can implement their own track padding:

```YAML
paths:
    # usage: %pad{value,padding,length}
    default: $albumartist/$album%aunique{}/%pad{$track,0,3} $title
```
