### ISSUE TITLE
bs1770gain 0.6.0 failing initialization

### ISSUE THREAD

**Issue by r3b311i0n** [beetbox/beets#3367]
### Problem

bs1770gain failing initialization after upgrading to v0.6.0 from v0.5.2. Downgrading to v0.5.2 fixes the issue.

```sh
$ beet replaygain
error: replaygain initialization failed: bs1770gain exited with status 1
```

### Setup

* OS: Arch Linux
* Python version: 3.7.4
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): yes

My configuration is:

```yaml
directory: ~/Music/ext-music
library: ~/.config/beets/library.db
musicbrainz:
        match:
                ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray',
                                'HD-DVD', 'VCD', 'SVCD', 'UMD', 'VHS']
ui:
        color: yes
        colors:
                text_success: green
                text_warning: yellow
                text_error: red
                text_highlight: red
                text_highlight_minor: lightgray
                action_default: turquoise
                action: blue
import:
        move: yes
        copy: no
        autotag: yes
plugins: [mpdstats, replaygain, embedart, fetchart, convert, info, chroma, fuzzy, zero]
replaygain:
        backend: bs1770gain
        method: ebu
        r128: [Opus, MP3, FLAC, AAC, ALAC, Wave]
embedart:
        ifempty: yes
        remove_art_file: yes
mpd:
        music_directory: ~/Music/ext-music
chroma:
        auto: yes
zero:
        fields: comments genre
        update_database: true
```

**Comment by sampsyo** [comment]
Please include the verbose output.

**Comment by Streetwalrus** [comment]
I've been running into the same problem.

```yaml
library: ~/music/beets.blb
directory: ~/music
plugins: fetchart embedart replaygain

import:
    move: yes
    group_albums: yes

embedart:
    auto: no

replaygain:
    backend: bs1770gain
    overwrite: yes
    method: replaygain
```

```
$ beet -v  
user configuration: /home/streetwalrus/.config/beets/config.yaml
data directory: /home/streetwalrus/.config/beets
plugin paths: 
Sending event: pluginload
error: replaygain initialization failed: bs1770gain exited with status 1
```

It looks like version 0.6 now exits with 1 if you don't pass it any arguments. Passing `-h` or `--help` makes it exit with 0, and it looks like [this has already been fixed](https://github.com/beetbox/beets/commit/0c8eead45978addf6337b81ddd9efe65c0786f33#diff-9f6de922dc45a51fac3456d34789996dR150).
