### ISSUE TITLE
Clutter config option does not work for multiple files

### ISSUE THREAD

**Issue by allesmi** [beetbox/beets#3373]
### Problem

I have an existing non-beets music library and several albums that contain extra files which I do not need anymore. For example playlist (m3u) und checksum files (sfv).
When doing a beets import "sometimes" these files are left over, even though I set the clutter configuration option like below.

I have tried to recreate the issue and found out that if the album directory only contains one of the files (either m3u or sfv) it is deleted as expected. But if it contains both than these files are left there and the directory is not deleted as expected.

The following commands assume that there is an `import` directory containing the album directories to be imported. Note that I passed the top-level directory to beets and therefore expect that the album directories are deleted when the album is successfully imported and the directory only contains files that match a pattern in the clutter config option.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv --config config.yaml import import/
```

Led to this problem:

import/album/ contains a m3u and sfv file.
When the album originally contains a m3u file but not the sfv file than it is successfully deleted.

### Setup

* OS: Fedora 30, Kernel 5.2.11-200.fc30.x86_64
* Python version: Python 3.7.4
* beets version: beets version 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/beets-test/library
library: ~/Music/beets-test/library/library.db
plugins: []

import:
  write: yes
  move: yes

clutter:
  - "Thumbs.DB"
  - "Thumbs.db"
  - "thumbs.db"
  - ".DS_Store"
  - "*.svf"
  - "*.m3u"
  - ".mediaartlocal"
```
