### ISSUE TITLE
Debugging a plugin

### ISSUE THREAD

**Issue by velvet-jones** [beetbox/beets#3376]
### Problem

I'm trying to figure out how to log debug,warning,info,error messages to a log file while debugging a plugin. In my plugin code I've tried self._log.setLevel(logging.DEBUG) in __init__() after the super __init__() is called, but the log file always seems to contain the same thing.

How do I get a detailed log file of my plugin's messages for debugging?

### Setup

* OS: Xutuntu 18.04.3
* Python version: 2.7
* beets version: 1.5
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
...
import:
    write: yes
    move: yes
    log: ~/beets.log
...
```
