### ISSUE TITLE
Play Plugin not invloking configured music player correctly

### ISSUE THREAD

**Issue by austinmm** [beetbox/beets#3401]
When I execute the play command, `beet play`, it tries to configure a randomly named playlist containing my 3 songs currently imported to beets, like it is supposed to. However, the first attempt at this command always executes incorrectly. Instead of invoking my configured music player, Apple Music, it doesn't. If I go to my Apple Music application I can see a new playlist under the name of something like, 'tmp57e5ye7b'; however, it will never contain all three songs. Usually, it contains no songs or just one. Yet if I run the `beet play` command again it will correctly create a new playlist with all three of my songs and automatically starts the music.

### Setup
* OS: macOS Catalina
* Python version: 3.7.4
* beets version: 1.4.9 
* Turning off plugins made the problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: [play]
pluginpath: [~/Desktop/cs581/beetsplug/, ~/Desktop/cs581/beets/beetsplug/]
play:
    command:
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
    bom: no
```
