### ISSUE TITLE
Accessing the fingerprints stored in the database

### ISSUE THREAD

**Issue by ribeaud** [beetbox/beets#3417]
### Use case

I computed the fingerprints for a couple of songs. Firstly, I thought that fingerprint computation would automatically happen on import once the plugin has been activated:
```
directory: ~/Music/beets/library
library: ~/Music/beets/library.db
import:
    copy: no
    write: no
    log: ~/Music/beets/import.log
    autotag: false
plugins: chroma web
chroma:
    auto: yes
```
This was NOT the case. Obviously, you have to run a `beet fingerprint` afterwards. Or did I miss something?
Secondly, I would like to access this fingerprint. How could it be done?

### Solution

**beets** is able to query and list entries. However, I am not able to display info of one single entry in the terminal. Using the **web** plugin, it is possible to display info related to one single entry. But there, no fingerprint is displayed if present. 

Somehow I have the feeling that a command _info_ is missing to display one single entry. The info panel would display the fingerprint if present.

### Alternatives
You have to install and use **sqlite** for querying the database.
