### ISSUE TITLE
`beet move` doesn't move some files despite their structure not matching tags anymore

### ISSUE THREAD

**Issue by eramdam** [beetbox/beets#3424]
I used the `edit` plugin to change the `artist` and `albumartist` of a ~thousand tracks (renaming some artists from kanji/kana into romaji representation) at a time. I had hoped that `beet move` would properly rename/move the folders to their new names but it doesn't seem to be the case, or at least not consistently 😕

Here's an illustration of the issue on one album affected (I have a few dozens of those)

![Screen Shot 2019-11-06 at 11 33 21 PM](https://user-images.githubusercontent.com/1409924/68368937-f53ebc80-00ed-11ea-92ac-465bba7e3f84.png)

Is there a way to tell the `move` command to force a re-organization/renaming of the file structure? Should I just restart from scratch? (I'd rather not do that because I have 15k tracks in around 150GB...)

### Setup

* OS: macOS 10.14.6
* Python version: Python 3.7.5
* beets version: beet 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: inline fetchart edit embedart lastgenre chroma importadded hook convert smartplaylist mpdupdate

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
directory: /Volumes/Damien OST/beets

import:
    move: no
    incremental: no
    log: beets.log
    resume: yes
    write: yes
fetchart:
    auto: yes
    sources: albumart coverart filesystem
    maxwidth: 700
    minwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
lastfm:
    user: DErambert
lastgenre:
    auto: yes
    count: 40
    force: yes
    min_weight: 10
    source: album
    whitelist: yes
    fallback:
    canonical: no
    separator: ', '
    prefer_specific: no
convert:
    album_art_maxwidth: 1000
    embed: yes
    auto: yes
    format: alac
    never_convert_lossy_files: yes
    dest:
    pretend: no
    threads: 8
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    tmpdir:
    quiet: no

    paths: {}
    no_convert: ''
    copy_album_art: no
hook:
    hooks: [{event: album_imported, command: 'osascript /Users/damien/.dotfiles/bin/usr/itunes-refresh.scpt "{album.path}"'}]
mpd:
    host: localhost
    port: 6600
    password: REDACTED
smartplaylist:
    relative_to: /Volumes/Damien OST/beets
    playlist_dir: ~/.mpd/playlists
    playlists: [{name: _Recently-Added.m3u, query: 'added:-3w.. added-'}, {name: Need-Genre-Tag.m3u, query: '^genre:", "'}]
    auto: yes
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
pathfields: {}
item_fields: {}
album_fields: {}
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
importadded:
    preserve_mtimes: no
    preserve_write_mtimes: no
chroma:
    auto: yes
```
