### ISSUE TITLE
bs1770gain fails

### ISSUE THREAD

**Issue by tecosaur** [beetbox/beets#3428]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv replaygain
user configuration: /home/tec/.config/beets/config.yaml
data directory: /home/tec/.config/beets
plugin paths:
Sending event: pluginload
error: replaygain initialization failed: bs1770gain exited with status 1
```

Led to this problem:

```
error: replaygain initialization failed: bs1770gain exited with status 1
```

Which happened after adding this this config

```
replaygain:
    backend: bs1770gain
```

### Setup

* OS: Linux 5.3.8-133.current x86_64
* Python version: 3.6.9
* beets version: 1.4.9
* bs1770gain version: 0.6.5

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart replaygain lyrics lastgenre convert web chroma discogs fuzzy play

directory: ~/Music
library: ~/Music/library.db

paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$disc-$track $title

per_disc_numbering: yes
ignore_hidden: yes
threaded: yes

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    # incremental: yes
    timid: no
    log: ~/.config/beets/import.log

convert:
    auto: no
    threads: 12
    max_bitrate: none
    no_convert: format:mp3, format:flac

ui:
    color: yes

web:
    host: 127.0.0.177

lyrics:
    fallback: ''
    google_API_key: THIS_LOOKS_SENSITIVE

fetchart:
    google_key: THIS_LOOKS_SENSITIVE

discogs:
    user_token: THIS_LOOKS_SENSITIVE

replaygain:
    auto: yes
    backend: bs1770gain
```
