### ISSUE TITLE
Adds typo to artist

### ISSUE THREAD

**Issue by Extarys** [beetbox/beets#3431]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import '/media/NasEntertainment/Musik/L/Les Cowboys Fringants'
```

Led to this problem:

Artist is `Les Cowboys Fringants`
The album is `12 grandes chansons`
MB page: https://musicbrainz.org/release/284e85bc-2bf5-496b-8c61-ed8c1d149437

Beets says the name is `Fringuant` with an additional U. Picard seems to know the right name though. 98% of my songs have a MB id for the track as I used to use only Picard. (and about 40% of them have a beautiful filepath XD)

```
/media/NasEntertainment/Musik/L/Les Cowboys Fringants/12 grandes chansons - (1997) [MP3 128kbps] (12 items)
Sending event: before_choose_candidate
Correcting tags from:
    Les Cowboys Fringants - 12 grandes chansons
To:
    Les Cowboys Fringuants - 12 grandes chansons
URL:
    https://musicbrainz.org/release/284e85bc-2bf5-496b-8c61-ed8c1d149437
(Similarity: 94.2%) (tracks, artist) (1997, CA)
 * L'Agacepésie (#5) (3:15) -> Awikatchikaën (#2) (2:50) (id, title, index, length)
 * Impala blues (4:01)      -> Impala blues (4:45) (length)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? primary MB release type: album
```

### Setup

* OS: Mint 19.2
beets version 1.4.9
Python version 3.7.2
plugins: acousticbrainz, beatport, chroma, convert, fromfilename, inline, lastgenre, lyrics, scrub, web
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /media/DarkHawk/beet-Test
library: /media/DarkHawk/opt/beet/library.blb

import:
    write: yes
    move: no
    copy: yes
    timid: yes
    languages: en fr
    bell: yes
    
match:
    strong_rec_thresh: 0.04
    preferred:
        countries: ['CA', 'US', 'GB|UK', 'FR']
        media: ['CD', 'Digital Media|File']
        original_year: yes
    required: year country

ui:
    color: yes

paths:
    default: %left{%asciify{$albumartist},1}/$albumartist/%ifdef{$year,$year - }$album%aunique{}/$disc-$track. $title
    albumtype:soundtrack: Soundtracks/$album%ifdef{$year, - $year}/$track. $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

#plugins: inline convert web lyrics lastgenre acousticbrainz scrub fromfilename chroma acousticbrainz beatport

lyrics:
  fallback: ''
  google_engine_ID: 009217259823014548361:lndtuqkycfu

lastgenre:
    min_weight: 60
    count: 5
    separator: '; '

acousticbrainz:
    force: yes

chroma:
    auto: yes

acoustid:
    apikey: abcd1234
```

I'm sure the solution is quite simple. I just cannot find it.
