### ISSUE TITLE
Move and rename lrc files

### ISSUE THREAD

**Issue by Extarys** [beetbox/beets#3432]
### Use case

I'm trying to use beets to...
rename and move .lrc files along with the tracks

### Solution
- Fork/Update beets-copyartifacts to support `$title` and other variable that can be used in a track title
- Make it compatible with Python 3 as Python 2 EOL is near.

OR

- Find, before renaming, all files that match current file name and then rename the track and other matching filenames.

### Alternatives
Hmm, don't do anything but that feature should be a must.
Or maybe there is another plugin I'm not aware of? I barely find that one :laughing:

**Comment by sampsyo** [comment]
Yo! Have you seen [beets-extrafiles](https://github.com/Holzhaus/beets-extrafiles)? It may be at least closer to what you want, and it has been updated more recently.

**Comment by Extarys** [comment]
:man_facepalming: Thanks buddy! I'll try it right away.

**Comment by Extarys** [comment]
It seems that the plugin could move lrc files but doesn't rename them.

I tried renaming them using the following, after inspecting the code to get available variables:

```
extrafiles:
    patterns:
        artworkdir:
          - '[sS]cans/'
          - '[aA]rtwork/'
        lyrics:
          - '*.lrc'
    paths:
        artworkdir: $albumpath/artwork
        lyrics: $albumpath/$filename.lrc
```

I will continue testing further.
