### ISSUE TITLE
iphenated genres dont get the %title{$genre} respected in path 

### ISSUE THREAD

**Issue by lbesnard** [beetbox/beets#3436]
### Problem
Genres such as "Trip-Hop" or "Avant-Garde" have their id3tag value properly configured such as:

```
 beet info -i 'genre' albumartist:Herbaliser

/export/music/beet_library/Trip-hop/The Herbaliser/2002 - Something Wicked This Way Comes/...
genre: Trip-Hop  
```

However, the path of the file, as can be seen above is Trip-**h**op rather than Trip-**H**op.

in the config file, the path is setup as:
```yaml
 paths:                                                                                                                                                                                                                                                                      
     default: '%title{$genre}/%title{$albumartist}/$original_year - $album/%if{$multidisc,Disc $disc/}$track $title'    
```

**HOWEVER**
I 'fixed' this by using using the inline plugin and did this in my yaml file:

```yaml
 item_fields:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      genre_fix: genre.title()

paths:
    default: '$genre_fix/%title{$albumartist}/$original_year - $album/%if{$multidisc,Disc $disc/}$track $title'
```
I would have assumed that the %title would have had the same behaviour as on python? Am I missing out on something, or is it how it is supposed to behave?

### Setup

* OS: debian 9
* Python version: 3.7.4 
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
 paths:                                                                                                                                                                                                                                                                      
     default: '%title{$genre}/%title{$albumartist}/$original_year - $album/%if{$multidisc,Disc $disc/}$track $title'    
```
