### ISSUE TITLE
Genius lyrics provider not finding track

### ISSUE THREAD

**Issue by xhocquet** [beetbox/beets#3446]
Hey there, first off thanks for the software, it's very useful! I'm trying to get some lyrics for a new album I added to my library. I originally noticed more 'edge' hip-hop lyrics not importing despite Genius being enabled, and Genius having a TON of rap lyrics. It does not seem like the plugin is making a request to Genius like the other providers (which do not have the song)

Specific song I am trying to import below: https://genius.com/Billy-woods-marlow-lyrics

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vvv lyrics billy woods marlow -f
user configuration: C:\Users\meesles\AppData\Roaming\beets\config.yaml
data directory: C:\Users\meesles\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: C:\Users\meesles\AppData\Roaming\beets\library.db
library directory: D:\Library\Music
Sending event: library_opened
lyrics: failed to fetch: http://lyrics.wikia.com/Billy_Woods:Marlow (404)
lyrics: failed to fetch: https://www.musixmatch.com/lyrics/Billy-Woods/Marlow (404)
lyrics: lyrics not found: Billy Woods - Terror Management - Marlow
Sending event: cli_exit
```

File: http://www.mediafire.com/file/0rfq90y1v77mejf/01_Marlow.mp3/file

### Setup

* OS: Windows 10
* Python version: 3.7.4
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:                                                                  
    bing_lang_from: []                                                   
    sources: google lyricwiki musixmatch genius                          
    fallback: ''                                                         
    auto: yes                                                            
    bing_client_secret: REDACTED                                         
    bing_lang_to:                                                        
    google_API_key: REDACTED                                             
    google_engine_ID: REDACTED                                           
    genius_api_key: REDACTED                                             
    force: no                                                            
    local: no                                                            
directory: D:\Library\Music                                              
                                                                         
import:                                                                  
    move: yes                                                            
    incremental: yes                                                     
                                                                         
paths:                                                                   
    default: $albumartist/$album%aunique{}/$track $title                 
    singleton: Non-Album/$artist/$title                                  
    comp: Compilations/$album%aunique{}/$track $title                    
                                                                         
ui:                                                                      
    color: yes                                                           
                                                                         
musicbrainz:                                                             
    user: xhocquet                                                       
    pass: REDACTED                                                       
                                                                         
plugins: missing mbcollection mbsync lyrics random mbsubmit              
mbcollection:                                                            
    auto: yes                                                            
    collection: 51e9fbd7-7fdf-4fd5-a315-4cd225562474                     
    remove: yes                                                          
mbsubmit:                                                                
    format: $track. $title - $artist ($length)                           
    threshold: medium                                                    
missing:                                                                 
    count: no                                                            
    total: no                                                            
    album: no                                                            
                                                                         
```
