### ISSUE TITLE
Cannot Access Environment Variables

### ISSUE THREAD

**Issue by iot-resister** [beetbox/beets#3447]
### Use case

I'm trying to use beets to hook into funkwhale 

```
  hook:
    hooks:
      - event: import
        command: /docker/docker --config "/config/.docker" exec funkwhale manage import_files ${FUNKWHALE_LIBRARY_ID} "/music/**/**/*.mp3" --in-place --async --no-input
```
### Solution

Yes. As is common practice.
https://gist.github.com/VillanCh/1486316511df7b765c0bc9768905b089
https://medium.com/swlh/python-yaml-configuration-with-environment-variables-parsing-77930f4273ac

### Alternatives

This does not extend the functionality.  This would be the responsibilty of the YAML parser.
