### ISSUE TITLE
Beet complains over read-only-directory with -c option activated when trying to move an image file

### ISSUE THREAD

**Issue by waweic** [beetbox/beets#3454]
### Problem

I have mounted /mnt/extern_2 with option read-only to prevent any changes to the data on a hard drive I just lent.

Running this command:

```sh
$ beet import -c /mnt/extern_2/Musik
```

Led to this problem:

```
Error: Read-only file system while moving /mnt/extern_2/Musik/2raumwohnung/36grad/cover.jpg to /mnt/extern_1/Musik-Sortiert-Neu/2raumwohnung/36grad/cover.jpg
```
### Setup

* OS: Arch Linux x86_64 (5.4.1-arch1-1)
* Python version: 3.8.0
* beets version: 1.4.9

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    sources:
    - google
    - lyricwiki
    - musixmatch
    - genius
directory: /mnt/extern_1/Musik-Sortiert-Neu

plugins: lyrics info web fetchart edit duplicates ftintitle missing random mbsync fromfilename mbsubmit
web:
    host: 0.0.0.0
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no

import:
    move: yes
    log: ~/.config/beets/import.log
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
```
