### ISSUE TITLE
Beets overwrites new id3 v2 tags on `write`

### ISSUE THREAD

**Issue by alex-phillips** [beetbox/beets#3465]
### Problem

I have many tracks that have id3 v1 tags and am attempting to upgrade the physical files to id3v2. The problem is that when I convert the file's tags to id3 v2 (using `id3v2` CLI), many of the fields in v1 are truncated due to character constraints. So after converting them, I want to run a `beet write` on the files to get the proper, full file information in the metadata. When running `beet write` on the files, beets is removing the v2 tags that are newly created.

FIRST, LIST ALL TAGS OF THE TRACK
```
$ id3v2 --list Live\ at\ the\ Aragon\ Ballroom\ \[7319\]/07\ Sic\ Transit\ Gloria...\ Glory\ Fades.mp3 
id3v1 tag info for Live at the Aragon Ballroom [7319]/07 Sic Transit Gloria... Glory Fades.mp3:
Title  : Sic Transit Gloria... Glory Fa  Artist: Brand New                     
Album  : Live at the Aragon Ballroom     Year: 2017, Genre: Unknown (161)
Comment:                                 Track: 7
Live at the Aragon Ballroom [7319]/07 Sic Transit Gloria... Glory Fades.mp3: No ID3v2 tag
```

NEXT, CONVERT THE TAGS TO ID3 V2
```
$ id3v2 --convert Live\ at\ the\ Aragon\ Ballroom\ \[7319\]/07\ Sic\ Transit\ Gloria...\ Glory\ Fades.mp3
Converting id3v1 tag to id3v2 in Live at the Aragon Ballroom [7319]/07 Sic Transit Gloria... Glory Fades.mp3... converted 
```

NOW LIST THE UPDATED TAGS OUTPUT
```
$ id3v2 --list Live\ at\ the\ Aragon\ Ballroom\ \[7319\]/07\ Sic\ Transit\ Gloria...\ Glory\ Fades.mp3 
id3v1 tag info for Live at the Aragon Ballroom [7319]/07 Sic Transit Gloria... Glory Fades.mp3:
Title  : Sic Transit Gloria... Glory Fa  Artist: Brand New                     
Album  : Live at the Aragon Ballroom     Year: 2017, Genre: Unknown (161)
Comment:                                 Track: 7
id3v2 tag info for Live at the Aragon Ballroom [7319]/07 Sic Transit Gloria... Glory Fades.mp3:
TIT2 (Title/songname/content description): Sic Transit Gloria... Glory Fa
TPE1 (Lead performer(s)/Soloist(s)): Brand New
TALB (Album/Movie/Show title): Live at the Aragon Ballroom
TYER (Year): 2017
TRCK (Track number/Position in set): 7
TCON (Content type): Unknown (161)
```

USE BEETS TO WRITE METADATA FROM THE DB
```
beet write path:/mnt/storage/music/beets/Music/Brand\ New/Live\ at\ the\ Aragon\ Ballroom\ \[7319\]/
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
Brand New - Live at the Aragon Ballroom - Sic Transit Gloria... Glory Fa
  title: Sic Transit Gloria... Glory Fa -> Sic Transit Gloria... Glory Fades
  albumartist:  -> Brand New
  r128_track_gain: 000000 -> 000000
  r128_album_gain: 000000 -> 000000
```

VIEW UPDATED TAGS (AFTER BEETS WRITE ACTION)
```
$ id3v2 --list Live\ at\ the\ Aragon\ Ballroom\ \[7319\]/07\ Sic\ Transit\ Gloria...\ Glory\ Fades.mp3 
id3v1 tag info for Live at the Aragon Ballroom [7319]/07 Sic Transit Gloria... Glory Fades.mp3:
Title  : Sic Transit Gloria... Glory Fa  Artist: Brand New                     
Album  : Live at the Aragon Ballroom     Year: 2017, Genre: Unknown (161)
Comment:                                 Track: 7
Live at the Aragon Ballroom [7319]/07 Sic Transit Gloria... Glory Fades.mp3: No ID3v2 tag
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Linux (docker)_
* Python version: 3.8.1
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart scrub replaygain lastgenre web importadded ftintitle extrafiles 
directory: /mnt/storage/music/beets/Music
library: /config/musiclibrary.blb
art_filename: cover
threaded: yes
original_date: yes
per_disc_numbering: no

paths:
    # default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title 
        
import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

match:
    preferred:
        countries: ['US', 'GB|UK']
        media: ['CD', 'Digital Media|File']
        original_year: yes

importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes

ftintitle:
    auto: yes
    drop: no
    format: feat. {0}

lastgenre:
    auto: yes
    source: album

embedart:
    auto: no

fetchart:
    auto: yes
    cautious: yes
    cover_names: cover front art album folder
    fanarttv_key: 14da800247d4ebbfd775b4a40d91ae8f
    google_search: no
    enforce_ratio: yes
    #sources: filesystem fanarttv coverart itunes albumart amazon google wikipedia
    sources: filesystem coverart itunes albumart amazon google wikipedia

extrafiles:
    patterns:
        all:
            - "*.log"
            - "*.cue"
    paths:
        all: $albumpath/$filename

replaygain:
    auto: no

scrub:
    auto: no

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337
```
