### ISSUE TITLE
Beet Import created duplicate albums with numbers.

### ISSUE THREAD

**Issue by brotatos** [beetbox/beets#347]
I recently did a `beet imp -A ~/music` after changing my directory from `/mnt/media/music` to `~/music`. This caused multiple duplicates to show up in my music folder.

```
robin@box ~/music/Animal Collective % ls
Campfire Songs     Feels 95                    Merriweather Post Pavilion 97                    Sung Tongs
Campfire Songs 93  Here Comes the Indian       Spirit They're Gone, Spirit They've Vanished     Sung Tongs 100
Fall Be Kind       Here Comes The Indian       Spirit They're Gone, Spirit They've Vanished 98  Water Curses
Fall Be Kind 94    Here Comes the Indian 96    Strawberry Jam                                   Water Curses 101
Feels              Merriweather Post Pavilion  Strawberry Jam 99
```

Is there any way to easily remove the duplicated albums with integers in them?

Here's my configuration for reference:

``` yaml
directory: ~/music
library: ~/.beetsmusic.blb
plugins: bpd

import:
    resume: yes
    incremental: yes
    move: yes
    write: yes
    delete: yes
threaded: yes
color: yes
```
