### ISSUE TITLE
beet mod QUERY singleton=(true|false) has no effect

### ISSUE THREAD

**Issue by rnkn** [beetbox/beets#3476]
### Problem

Running `beet mod QUERY singleton=true` or `singleton=false` has no effect

Running this command in verbose (`-vv`) mode:

```sh
% beet -vv mod kyla la grange singleton=false
user configuration: /Users/pwr/.config/beets/config.yaml
data directory: /Users/pwr/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Users/pwr/.config/beets/library.db
library directory: /Volumes/Apollo/Music
Sending event: library_opened
Modifying 3 items.
No changes to make.
Sending event: cli_exit
```

Led to this problem:

After importing some tracks as singletons...
```
% beet -vv mod kyla la grange singleton=false
Modifying 3 items.
Kyla La Grange - Cut Your Teeth - Cut Your Teeth
  singleton: True
Kyla La Grange - Cut Your Teeth - Maia
  singleton: True
Kyla La Grange - Cut Your Teeth - Cannibals
  singleton: True
Really modify, move and write tags? (Yes/no/select) y
% beet ls singleton:true kyla la grange
Kyla La Grange - Cut Your Teeth - Cut Your Teeth
Kyla La Grange - Cut Your Teeth - Maia
Kyla La Grange - Cut Your Teeth - Cannibals
```

Here's a link to the music files that trigger the bug (if relevant):
This happens with any track.

### Setup

* OS: macOS 10.15.2
* Python version: Python 3.7.6
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): nope

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/Apollo/Music

import:
    copy: yes
    write: yes
    log: import.log
asciify_paths: yes
original_date: yes

match:
    preferred:
        countries: [au, us]
        media: [cd, digital]
    ignored_media: vinyl
languages: en

paths:
    default: $albumartist/$album/$track $title
    singleton: singles/$artist/$title
    comp: compilations/$album/$track $title
    genre:soundtrack: soundtracks/$album%aunique{}/$track $title
fetchart:
    auto: yes
    minwidth: 800
    enforce_ratio: 8px
    sources: itunes *
playlist:
    auto: yes
    relative_to: library
    playlist_dir: ~/Music/playlists
smartplaylist:
    auto: yes
    playlist_dir: ~/Music/playlists
    playlists:
    -   name: Last 2 Wks.m3u
        query: added- added:-2w..
    -   name: Last Month.m3u
        query: added- added:-1m..
    -   name: Lossless.m3u
        query: added- format:alac, format:flac
    -   name: low bitrate.m3u
        query: albumartist+ bitrate:..128000
    -   name: Music of This Year.m3u
        query: year:2019
    -   name: Singles Collection.m3u
        query: singleton:true
    -   name: Loved Songs.m3u
        query: love:True
    -   name: The Covers Playlist.m3u
        query: cover:True
convert:
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -ab 256k $dest
            extension: m4a
mpd:
    music_directory: /Volumes/Apollo/Music
lastgenre:
    auto: no
    count: 3
    min_weight: 30
discogs:
    user_token: TOPSECRET
bandcamp:
    source_weight: 0.7
    art: yes
```
