### ISSUE TITLE
cannot search by field comment

### ISSUE THREAD

**Issue by minusf** [beetbox/beets#3486]
I normally scrub comment tags, but I have some music imported "as-is" (not in musicbrainz) and these have comments (Visit http://XXX.bandcamp.com). I cannot seem to find these based on comments.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv list comment:bandcamp
```

Led to this problem:

```
[no results]
```

The comments are present in the library:

```
$ beet list ayman ander -f \$comment
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
Visit http://aymanmaas.bandcamp.com
```

An example file from the library:

```
Processing file "01-fakewrk.ogg"...

New logical stream (#1, serial: 047780b8): type vorbis
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Xiph.Org libVorbis I 20180316 (Now 100% fewer shells)
Channels: 2
Rate: 44100

Nominal bitrate: 192.000000 kb/s
Upper bitrate not set
Lower bitrate not set
User comments section follows...
	ACOUSTID_FINGERPRINT=
	ACOUSTID_ID=
	ALBUM=Ander
	ALBUM ARTIST=Ayman Maas
	ALBUMARTIST=Ayman Maas
	ALBUMARTIST_CREDIT=
	ALBUMARTISTSORT=
	MUSICBRAINZ_ALBUMCOMMENT=
	MUSICBRAINZ_ALBUMSTATUS=
	MUSICBRAINZ_ALBUMTYPE=
	ARRANGER=
	ARTIST=Ayman Maas
	ARTIST_CREDIT=
	ARTISTSORT=
	ASIN=
	BPM=0
	CATALOGNUMBER=
	DESCRIPTION=Visit http://aymanmaas.bandcamp.com
	COMMENT=Visit http://aymanmaas.bandcamp.com
	COMPILATION=0
	COMPOSER=
	COMPOSERSORT=
	RELEASECOUNTRY=
	DATE=2017
	YEAR=2017
	DISC=0
	DISCNUMBER=0
	DISCSUBTITLE=
	DISCTOTAL=0
	DISCC=0
	TOTALDISCS=0
	ENCODEDBY=
	ENCODER=
	GENRE=
	GROUPING=
	LABEL=
	PUBLISHER=
	LANGUAGE=
	LYRICIST=
	LYRICS=
	MUSICBRAINZ_ALBUMARTISTID=
	MUSICBRAINZ_ALBUMID=
	MUSICBRAINZ_ARTISTID=
	MUSICBRAINZ_RELEASEGROUPID=
	MUSICBRAINZ_RELEASETRACKID=
	MUSICBRAINZ_TRACKID=
	MEDIA=
	ORIGINALDATE=2017
	SCRIPT=
	TITLE=Fakewrk
	TRACK=1
	TRACKNUMBER=1
	TRACKTOTAL=0
	TRACKC=0
	TOTALTRACKS=0
Vorbis stream 1:
	Total data length: 6703751 bytes
	Playback length: 5m:55.328s
	Average bitrate: 150.930635 kb/s
Logical stream 1 ended
```

### Setup

* OS: macOS 10.14.6
* Python version: 3.7.6
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
mpd:
    port: 6600
    host: localhost
    password: REDACTED
directory: /Volumes/256/sonoteque

format_item: $artist - $album - $title - $length - $track

paths:
    default: '%lower{$albumartist/$original_year-$album/$track-$title}'
    genre:anime: '%lower{ost-anime/$album-$original_year/$track-$title}'
    genre:game: '%lower{ost-game/$album-$original_year/$track-$title}'
    genre:classic: '%lower{$composer/$album-$original_year/$track-$title}'
    albumtype:soundtrack: '%lower{ost/$album-$original_year/$track-$title}'
    comp: '%lower{various/$album-$original_year/$track-$title}'
    albumartist:"Ayman Maas": '%lower{joey/$albumartist/$original_year-$album/$track-$title}'

import:
    from_scratch: yes

replace:
    \s*&\s*: -and-
    '[\\/]': ''
    '[\x00-\x1f]': '-'
    '[<>:,"\?\*\|!#\$]': ''
    \.\.: ''
    ^\.\.: ''
    \.$: ''
    \.\s: '-'
    \s\.: '-'
    ^\s+: ''
    \s+$: ''
    \s: '-'
    ^-: ''
    -$: ''
    -\.: '-'
    '[\[\]\(\)]': ''
    '''': ''
    -_-: '-'
    '---': '-'
asciify_paths: yes

plugins: edit fetchart ftintitle play scrub random mpdupdate
fetchart:
    sources: [filesystem]
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
play:
    command: /Users/fholop/bin/m
    raw: yes
    use_folders: no
    relative_to:
    warning_threshold: 100
    bom: no
mpdupdate:
    host: localhost
    port: 6600
scrub:
    auto: yes
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
```
