### ISSUE TITLE
Cannot match a MusicBrainz recording

### ISSUE THREAD

**Issue by Randoragon** [beetbox/beets#3489]
### Problem

There's one particular file in my folder that does not get imported properly.
It has a correct filename and metadata and I am using a MusicBrainz release URL for matching.
Every other file that belongs to this release is matched correctly, however the problematic one constantly gets matched with the wrong one. This seems to be an issue with fuzzy matching?

It's really best explained with a screenshot:
![image](https://user-images.githubusercontent.com/46251339/74590589-04e47000-5010-11ea-9c27-a6463f60ecb1.png)

Basically, the song title is "Heartache", and a song with the exact same name exists in the release, but Beets matches my file with "Start Menu" instead, probably because it's "close enough" and it appears higher on the list than "Heartache". It's as though Beets didn't check the entire list for the best match, but instead iterated through the list and stopped upon finding the first good enough match.

I've tried pasting the link of both the release:
https://musicbrainz.org/release/be37a91e-d5db-4c27-994c-0390d14d4396
...and the exact recording:
https://musicbrainz.org/recording/b1856c5c-3b01-4d65-be1a-a023d65c05cb
...but it claims there's no match even when I pasted the recording.

Here's the output of `beet -vv import /path/to/Heartache.mp3`:

```
/home/pcache/Downloads/Music/Chiptune/Undertale - Heartache.mp3 (1 items)
Sending event: before_choose_candidate
Finding tags for album "Many People - Undertale".
Candidates:
1. insaneintherainmusic feat. SwigglesRP - Undertale (48.1%) (artist, tracks) (Digital Media, 2016, XW)
2. Hot Dad - Undertale (42.5%) (artist, tracks) (2016)
3. Daniel Tidwell - Megalovania (Undertale) (29.6%) (artist, tracks, album) (Digital Media, 2019, XW)
4. GuildmasterMusic - Undertale (16.7%) (missing tracks, artist, tracks) (Digital Media, 2017, XW)
5. Retrogame Tributes - Undertale (15.0%) (missing tracks, artist, tracks) (Digital Media, 2016, XW)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? i
Enter release ID: https://musicbrainz.org/recording/b1856c5c-3b01-4d65-be1a-a023d65c05cb
Tagging Many People - Undertale
Searching for album ID: https://musicbrainz.org/recording/b1856c5c-3b01-4d65-be1a-a023d65c05cb
Requesting MusicBrainz release https://musicbrainz.org/recording/b1856c5c-3b01-4d65-be1a-a023d65c05cb
Album ID match failed.
spotify: Searching for album https://musicbrainz.org/recording/b1856c5c-3b01-4d65-be1a-a023d65c05cb
Evaluating 0 candidates.
Sending event: before_choose_candidate
No matching release found for 1 tracks.
For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort,
eDit? 
```

(at the time of writing this issue I had `$albumartist` field set to "Many People", but changing it to "Toby Fox" didn't change a thing)

### Setup

* OS: Arch Linux x86_64 Linux 5.5.3-arch1-1
* Python version: 3.8.1
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
library: ~/.config/beets/library.db
directory: ~/Music

format_item: $artist - $title
format_album: $albumartist - $album
sort_item: artist+ album+ disc+ track+

sort_album: albumartist+ album+
sort_case_insensitive: yes

import:
    write: no
    move: no
    copy: yes
    resume: ask
    incremental: no
    incremental_skip_later: no
    quiet: no
    detail: yes
    from_scratch: no
    log: ~/.config/beets/import.log
    languages: en pl de ja jp
    autotag: yes

paths:
    default: $albumartist/$album%aunique{}/$title
    singleton: $artist/no album/$title
    comp: Compilations/$album%aunique{}/$title

```
