### ISSUE TITLE
test_ui.ConfigTest.test_cli_config_paths_resolve_relative_to_user_dir failing on my mac

### ISSUE THREAD

**Issue by adamjakab** [beetbox/beets#3500]
### Problem

when i run:

```sh
$ pytest
```

the test ConfigTest.test_cli_config_paths_resolve_relative_to_user_dir in test/test_ui.py fails with:

```
paths are not equal: b'/var/folders/yv/9ntm56m10ql9wf_1zkbw74hr0000gp/T/tmpidp1nrl0/Library/Application Support/beets/beets.db' and b'/var/folders/yv/9ntm56m10ql9wf_1zkbw74hr0000gp/T/tmpidp1nrl0/.config/beets/beets.db'
(b'/var/folders/yv/9ntm56m10ql9wf_1zkbw74hr0000gp/T/tmpidp1nrl0/.config/beets/b'
 b'eets.db') != (b'/var/folders/yv/9ntm56m10ql9wf_1zkbw74hr0000gp/T/tmpidp1nrl0/Library/Applica'
 b'tion Support/beets/beets.db')

<Click to see difference>
...
```

Do you have any idea why this happens and how I can fix this?

### Setup

* OS: macOS High Sierra (10.13.6)
* Python version: 3.7.6
* beets version: updated and clean master branch (commit: #e6c94be848f0ac0ac1ee059940a17ffe9a99db87)

My configuration (output of `beet config`) is:

```yaml
$ ./beet config
directory: /Volumes/Data/_TmpMusic_/
library: ~/.config/beets/test_library.db
asciify_paths: yes
id3v23: yes

ui:
    color: yes

plugins:
- the
- inline
- info
- fromfilename
- duplicates
- convert
- zero

import:
    copy: no
    move: yes
    autotag: yes
    from_scratch: yes
    none_rec_action: asis
    duplicate_action: remove
    set_fields:
        albumstatus: new

paths:
    default: $initial_letter/%the{$albumartist}/$album/$track. $title
    singleton: V/Various Artists/%the{$artist}/$track. $title
    comp: V/Various Artists/%the{$artist}/$track. $title

musicbrainz:
    searchlimit: 3
item_fields:
    initial_letter: albumartist[0].upper() if albumartist else 'U'
zero:
    auto: yes
    fields:
    - month
    - day
    - encoder
    - lyrics
    - comments
    update_database: yes
    keep_fields: []
convert:
    command: ffmpeg -i $source -y -q:a 5 -f mp3 $dest
    extension: mp3
    max_bitrate: 182
    threads: 1
    auto: no
    dest: /Volumes/Data/_TmpMusic_/___converted___
    format: mp3
    formats:
        mp3: ffmpeg -i $source -y -q:a 5 -f mp3 $dest
        flac: ffmpeg -i $source -y -acodec flac -q:a 5 -f mp3 $dest
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    pretend: no
    link: no
    hardlink: no
    id3v23: inherit
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
acousticbrainz:
    auto: no
    force: no
    tags: [bpm]
pathfields: {}
album_fields: {}
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''


```
