### ISSUE TITLE
beet update reports same changes everytime

### ISSUE THREAD

**Issue by akyag** [beetbox/beets#3506]
### Problem

Running this command in verbose (`-vv`) mode: I ran it without -vv because the output was too long. I will post it if its needed

```sh
$ beet up
```

Led to this problem:

```
Alice DeeJay - Who Needs Guitars Anyway? - Better Off Alone
  r128_album_gain: 000000 -> 000000
Ken Arai - Parasyte Kiseijuu Sei no Kakuritsu Original Soundtrack - Next to You
  r128_album_gain: 000000 -> 000000
Avicii - True - You Make Me
  r128_album_gain: 000000 -> 000000
Avicii - True - Hey Brother
  r128_album_gain: 000000 -> 000000
Avicii - True - Dear Boy
  r128_album_gain: 000000 -> 000000
Avicii - True - Liar Liar
  r128_album_gain: 000000 -> 000000
Avicii - True - Shame On Me
  r128_album_gain: 000000 -> 000000
Avicii - True - Lay Me Down
  r128_album_gain: 000000 -> 000000
Avicii - True - Hope There's Someone
  r128_album_gain: 000000 -> 000000
Avicii - True - Heart Upon My Sleeve
  r128_album_gain: 000000 -> 000000
Avicii - True - Long Road To Hell
  r128_album_gain: 000000 -> 000000
Avicii - True - Edom
  r128_album_gain: 000000 -> 000000
Coldplay - Ghost Stories - A Sky Full of Stars
  r128_album_gain: 000000 -> 000000
Delain - Lucidity - See Me in Shadow
  r128_album_gain: 000000 -> 000000
Eminem - Recovery - Not Afraid
  r128_album_gain: 000000 -> 000000
Eminem - The Marshall Mathers LP 2 - Rap God
  r128_album_gain: 000000 -> 000000
Enya - Only Time: The Collection - Only Time
  r128_album_gain: 000000 -> 000000
Evanescence - The Open Door - Call Me When You’re Sober
  r128_album_gain: 000000 -> 000000
Green Day - 21st Century Breakdown - ¡Viva la Gloria!
  r128_album_gain: 000000 -> 000000
Green Day - 21st Century Breakdown - 21 Guns
  r128_album_gain: 000000 -> 000000
Calvin Harris feat. Florence Welch - 18 Months - Sweet Nothing
  r128_album_gain: 000000 -> 000000
Imagine Dragons - Night Visions - On Top of the World
  r128_album_gain: 000000 -> 000000
Incubus - 8 - State of the Art
  r128_album_gain: 000000 -> 000000
Inna - Party Never Ends - Fall in Love / Lie
  r128_album_gain: 000000 -> 000000
Inna - Party Never Ends - Take Me Down to Mexico
  r128_album_gain: 000000 -> 000000
Inna - Party Never Ends - Caliente
  r128_album_gain: 000000 -> 000000
Inna - Party Never Ends - Crazy Sexy Wild
  r128_album_gain: 000000 -> 000000
Inna - Party Never Ends - Be My Lover
  r128_album_gain: 000000 -> 000000
Inna - The Romantic Collection - Devil's Paradise
  r128_album_gain: 000000 -> 000000
Inna feat. Daddy Yankee - Party Never Ends - More Than Friends
  r128_album_gain: 000000 -> 000000
Jewel - Pieces of You - You Were Meant for Me
  r128_album_gain: 000000 -> 000000
Avril Lavigne - Let Go - Sk8er Boi
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Heartbreaker
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Communication Breakdown
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - What Is and What Should Never Be
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Thank You
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - I Can't Quit You Baby
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Dazed and Confused
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Your Time Is Gonna Come
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Ramble On
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Travelling Riverside Blues
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Friends
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Celebration Day
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Hey Hey What Can I Do
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - White Summer / Black Mountain Side
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Over the Hills and Far Away
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - The Battle of Evermore
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Bron-Yr-Aur Stomp
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Tangerine
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Going to California
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - D'yer Mak'er
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Gallows Pole
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Custard Pie
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Rock and Roll
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - The Rain Song
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Kashmir
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Trampled Under Foot
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - For Your Life
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Dancing Days
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - The Song Remains the Same
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Ten Years Gone
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - In My Time of Dying
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - In the Evening
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Candy Store Rock
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - The Ocean
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Ozone Baby
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Houses of the Holy
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Wearing and Tearing
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Poor Tom
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Nobody's Fault but Mine
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Fool in the Rain
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - In the Light
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - The Wanton Song
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - Moby Dick / Bonzo's Montreux
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - I'm Gonna Crawl
  r128_album_gain: 000000 -> 000000
Led Zeppelin - Boxed Set - All My Love
  r128_album_gain: 000000 -> 000000
Linkin Park - Hybrid Theory - Pushing Me Away
  r128_album_gain: 000000 -> 000000
Linkin Park - Meteora - Breaking the Habit
  r128_album_gain: 000000 -> 000000
Linkin Park - Meteora - Numb
  r128_album_gain: 000000 -> 000000
Madcon - Step Up 3D - Beggin'
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - The Water Beneath You
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - My Energy
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - Last Forever
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - Losing Our Control
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - Backslide
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - Laid Low
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - The Runners
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - Falling
  r128_album_gain: 000000 -> 000000
The Naked and Famous - Simple Forms - Rotten
  r128_album_gain: 000000 -> 000000
Nirvana - Nevermind - In Bloom
  r128_album_gain: 000000 -> 000000
Nirvana - Nevermind - Come as You Are
  r128_album_gain: 000000 -> 000000
Nirvana - Nevermind - Lithium
  r128_album_gain: 000000 -> 000000
Pitbull feat. Kesha - Global Warming: Meltdown - Timber
  r128_album_gain: 000000 -> 000000
The Saturdays - Chasing Lights - Just Can’t Get Enough
  r128_album_gain: 000000 -> 000000
The Saturdays - Wordshaker - Ego
  r128_album_gain: 000000 -> 000000
The Saturdays feat. Flo Rida - Chasing the Saturdays - Higher
  r128_album_gain: 000000 -> 000000
澤野弘之 - 「進撃の巨人」オリジナルサウンドトラック - Vogel im Käfig
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Big Girls Cry
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Eye of the Needle
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Hostage
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Straight for the Knife
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Fair Game
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Free the Animal
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Fire Meet Gasoline
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Cellophane
  r128_album_gain: 000000 -> 000000
Sia - 1000 Forms of Fear - Dressed in Black
  r128_album_gain: 000000 -> 000000
Sia - We Are Born - I’m in Here
  r128_album_gain: 000000 -> 000000
System of a Down - Toxicity - Chop Suey!
  r128_album_gain: 000000 -> 000000
The Weeknd feat. Daft Punk - Starboy - Starboy
  r128_album_gain: 000000 -> 000000
Within Temptation - Destroyed - The Last Time (demo)
  r128_album_gain: 000000 -> 000000
Yun*chi - Your song* - Fuzzy*
  r128_album_gain: 000000 -> 000000
Yun*chi - Your song* - Your song* (instrumental)
  r128_album_gain: 000000 -> 000000
Yun*chi - Your song* - Fuzzy* (instrumental)
  r128_album_gain: 000000 -> 000000
Yun*chi with IroKokoro Project - Your song* - Waon*
  r128_album_gain: 000000 -> 000000
Yun*chi with IroKokoro Project - Your song* - Waon* (instrumental)
  r128_album_gain: 000000 -> 000000

```

Above mentioned changes happen at every instance + any songs were actually changed. Is this the normal behavior?

### Setup

* OS: Manjaro Linux x86_64 
* Python version: Python 3.8.1
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    sources: [google, lyricwiki, musixmatch]
directory: /media/entmt/audio/
library: ~/data/musiclibrary.db

import:
    copy: no
    write: yes
    log: /home/akya/.config/beets/import.log
pluginpath: [/home/akya/.config/beets/beetsplug/]

plugins: fetchart embedart lastgenre lyrics web missing beatport duplicates convert info play smartplaylist mpdupdate badfiles scrub
play:
    command: mpv $args --playlist
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
mpd:
    host: 127.0.0.1
    port: 6600
    password: REDACTED
fetchart:
    cautious: yes
    cover_names: front back
    minwidth: 300
    sources: itunes *
    auto: yes
    maxwidth: 0
    enforce_ratio: no
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
smartplaylist:
    relative_to:
    playlist_dir: /media/entmt/audio/playlists
    playlists:
    -   name: fav.m3u
        query: comments:Fav
    -   name: new.m3u
        query: comments:New
    -   name: epic.m3u
        query: comments:Epic
    -   name: lush.m3u
        query: comments:Lush
    -   name: selected.m3u
        query: comments:Selected
    -   name: run.m3u
        query: comments:Run
    -   name: oldies.m3u
        query: comments:oldies
    -   name: latest.m3u
        query: added:2019-09-22
    auto: yes
convert:
    dest: /home/akya/dump/sync
    max_bitrate: 192

    paths:
        default: $artist - $track $title
    pretend: no
    threads: 4
    format: mp3
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    auto: no
    tmpdir:
    quiet: no
    embed: yes
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0

paths:
    default: artists/$albumartist/$album%aunique{}/$track $title
    singleton: non_album/$artist - $title
    comp: compilations/$album%aunique{}/$track $title
missing:
    format: $albumartist - $album
    count: no
    total: no
    album: no
scrub:
    auto: yes
beatport:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: beatport_token.json
    source_weight: 0.5
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    reverse_proxy: no
    include_paths: no
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
```
