### ISSUE TITLE
Updating the year does not move files

### ISSUE THREAD

**Issue by danbee** [beetbox/beets#3510]
### Problem

I'm using the album release year as part of the path in my config. Updating the year on my music files does not appear to be resulting in a new path for the file. For example, I had an album tagged as "1992" instead of the correct value of "1982". So I fixed it with:

```sh
$ beet modify year=1982 casiopea
```

If I now list the year for these tracks I get the correct data:

```sh
$ beet ls -f '$year - $title' casiopea
1982 - Take Me
1982 - Asayake
1982 - Midnight Rendezvous
1982 - Time Limit
1982 - Domino Line
1982 - Tears of the Star
1982 - Swear
```

If I list the path to the files I get back the original path with the wrong year:

```sh
$ beet ls -f '$path' casiopea
.../Albums/Casiopea/(1992) Mint Jams/01 - Take Me.wv
.../Albums/Casiopea/(1992) Mint Jams/02 - Asayake.wv
.../Albums/Casiopea/(1992) Mint Jams/03 - Midnight Rendezvous.wv
.../Albums/Casiopea/(1992) Mint Jams/04 - Time Limit.wv
.../Albums/Casiopea/(1992) Mint Jams/05 - Domino Line.wv
.../Albums/Casiopea/(1992) Mint Jams/06 - Tears of the Star.wv
.../Albums/Casiopea/(1992) Mint Jams/07 - Swear.wv
```

Attempting to move results in the following:

```sh
$ beet mv casiopea
Moving 0 items (7 already in place).
```

### Setup

* OS: FreeBSD (music is on a ZFS volume)
* Python version: 3.6.9
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /osaka/media/music/Archive
library: ~/.config/beets/library.db

plugins: duplicates convert inline embedart fetchart zero missing random edit replaygain info
item_fields:
    trackartist: artist if artist != albumartist else ""
    use_artist: 1 if grouping != "Compilations" and grouping != "Games" else 0

paths:
    default: $grouping/%if{$use_artist,$albumartist/}($year) $album/%if{$disc,Disc $disc/}$track - $title%if{$trackartist, [$artist]}

import:
    autotag: no
    copy: no
    move: yes
    write: yes

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \s+$: ''
    ^\s+: ''
    \.$: ''
convert:
    dest: /osaka/media/music/Library
    format: aac
    copy_album_art: yes
    formats:
        aac:
            command: ffmpeg -i $source -c:a libfdk_aac -vbr 4 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    pretend: no
    link: no
    hardlink: no
    threads: 4
    id3v23: inherit
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    album_art_maxwidth: 0
embedart:
    auto: yes
    maxwidth: 1200
    quality: 75
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
replaygain:
    albums: yes
    backend: ffmpeg
    overwrite: no
    auto: yes
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
fetchart:
    sources: filesystem itunes coverart amazon albumart
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
    high_resolution: no
zero:
    fields: disc disctotal track tracktotal
    disc: ['00', ^0$]
    disctotal: ['00', ^0$]
    track: ['00', ^0$]
    tracktotal: ['00', ^0$]
    auto: yes
    keep_fields: []
    update_database: no
pathfields: {}
album_fields: {}
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
missing:
    count: no
    total: no
    album: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
```
