### ISSUE TITLE
Cannot hard link across folders

### ISSUE THREAD

**Issue by ee6f8317** [beetbox/beets#3511]
### Problem
Hi, I’m running the latest Linuxserver’s docker of Beets on a DS218+ Synology NAS with both the /downloads and /music on the same partition. When I launch the import command via ssh it show me this at the end:
Running this command via PuTTY:

```sh
docker exec -it Beets-8337 /bin/bash -c 'beet import /downloads'
```

Led to this problem:

```
Error: Cannot hard link across devices.link during (b'/downloads/We The Heathens/We The Heathens - Approaching Thunder/01 - 33 Shots.mp3', b'/music/MP3/We The Heathens/1. Album/2019 - Approaching Thunder/01 - 33 Shots.mp3') of paths T, r, a, c, e, b, a, c, k, , (, m, o, s, t, , r, e, c, e, n, t, , c, a, l, l, , l, a, s, t, ), :,, , , F, i, l, e, , ", /, u, s, r, /, l, i, b, /, p, y, t, h, o, n, 3, ., 8, /, s, i, t, e, -, p, a, c, k, a, g, e , s, /, b, e, e, t, s, /, u, t, i, l, /, _, _, i, n, i, t, _, _, ., p, y, ", ,, , l, i, n, e, , 5, 2, 8, ,, , i, n , , h, a, r, d, l, i, n, k,, , , , , o, s, ., l, i, n, k, (, s, y, s, p, a, t, h, (, p, a, t, h, ), ,, , s, y, s, p, a, t, h, (, d, e, s, t , ), ),, O, S, E, r, r, o, r, :, , [, E, r, r, n, o, , 1, 8, ], , C, r, o, s, s, -, d, e, v, i, c, e, , l, i, n, k, :, , b, ', /, d, o, w, n, l, o, a, d, s, /, W, e, , T, h, e, , H, e, a, t, h, e, n, s, /, W, e, , T, h, e, , H, e, a , t, h, e, n, s, , -, , A, p, p, r, o, a, c, h, i, n, g, , T, h, u, n, d, e, r, /, 0, 1, , -, , 3, 3, , S, h, o , t, s, ., m, p, 3, ', , -, >, , b, ', /, m, u, s, i, c, /, M, P, 3, /, W, e, , T, h, e, , H, e, a, t, h, e, n, s , /, 1, ., , A, l, b, u, m, /, 2, 0, 1, 9, , -, , A, p, p, r, o, a, c, h, i, n, g, , T, h, u, n, d, e, r, /, 0, 1 , , -, , 3, 3, , S, h, o, t, s, ., m, p, 3, ',
```

### Setup

* OS: DSM 6.2.2-24922 Update 4 
* Python version: ?
* beets version: latest of https://github.com/linuxserver/docker-beets as of the 03.03.2020
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    sources:
    - google
    - lyricwiki
    - musixmatch
    - genius

plugins: fetchart embedart convert scrub replaygain lastgenre chroma web lyrics
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no
convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    dest:
    pretend: no
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0

paths:
    default: $format/$albumartist/1. Album/$original_year - $album%aunique{}/$track - $title
    albumtype_ep: $format/$albumartist/2. EP/$original_year - $album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: no
    copy: no
    move: no
    hardlink: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log
lastgenre:
    auto: yes
    source: album
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    force: yes
    separator: ', '
    prefer_specific: no
embedart:
    auto: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
replaygain:
    auto: no
    overwrite: no
    backend: command
    targetlevel: 89
    r128: [Opus]
    command: ''
    noclip: yes
scrub:
    auto: yes

replace:
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    \.$: _
    \s+$: ''
web:
    host: 0.0.0.0
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
chroma:
    auto: yes
```
