### ISSUE TITLE
Track matching issue

### ISSUE THREAD

**Issue by syco** [beetbox/beets#3541]
Hi,
I'm having this issue where tracks get confused

```sh
# beet -vv -c /music/config.yaml import .
overlaying configuration: /music/config.yaml
no user configuration found at /root/.config/beets/config.yaml
data directory: /root/.config/beets
plugin paths: 
Sending event: pluginload
library database: /music/musiclibrary.blb
library directory: /music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /downloads/Skyhooks/Skyhooks - Live In The 80s
Tagging Skyhooks - Live In The 80's
No album ID found.
Search terms: Skyhooks - Live In The 80's
Album might be VA: False
Searching for MusicBrainz releases with: {'release': "live in the 80's", 'artist': 'skyhooks', 'tracks': '12'}
Requesting MusicBrainz release 303bb89a-72b6-4825-b71d-58d4347664b5
primary MB release type: album
secondary MB release type(s): live
Sending event: albuminfo_received
Candidate: Skyhooks - Live in the 80's (303bb89a-72b6-4825-b71d-58d4347664b5)
Computing track assignment...
...done.
Success. Distance: 0.05
Requesting MusicBrainz release 82b00119-3d3b-4444-9950-b63381b76d56
primary MB release type: album
Sending event: albuminfo_received
Candidate: T-Ski Valley - In the 80's (82b00119-3d3b-4444-9950-b63381b76d56)
Computing track assignment...
...done.
Success. Distance: 0.56
Requesting MusicBrainz release 5d8b4a6a-3e76-4f69-b0b5-fe87910ffeaf
primary MB release type: album
Sending event: albuminfo_received
Candidate: Organized Chaos - In the 80's (5d8b4a6a-3e76-4f69-b0b5-fe87910ffeaf)
Computing track assignment...
...done.
Success. Distance: 0.76
Requesting MusicBrainz release 74e6e228-4857-48f6-a0c6-c751abf0bd2f
primary MB release type: album
Sending event: albuminfo_received
Candidate: T-Ski Valley - In the 80's (74e6e228-4857-48f6-a0c6-c751abf0bd2f)
Computing track assignment...
...done.
Success. Distance: 0.59
Requesting MusicBrainz release c297c67c-3080-4d87-8e6e-86ecd5d62a2a
primary MB release type: album
Sending event: albuminfo_received
Candidate: The Lost Fingers - Lost in the 80s (c297c67c-3080-4d87-8e6e-86ecd5d62a2a)
Computing track assignment...
...done.
Success. Distance: 0.63
Sending event: albuminfo_received
Candidate: Skyhooks - Live In The 80's (2847693)
Computing track assignment...
...done.
Success. Distance: 0.12
Sending event: albuminfo_received
Candidate: Skyhooks - Live In The 80's (9978285)
Computing track assignment...
...done.
Success. Distance: 0.08
Sending event: albuminfo_received
Candidate: Skyhooks - The Skyhooks Box (8789847)
Computing track assignment...
...done.
Success. Distance: 0.78
Sending event: albuminfo_received
Candidate: Skyhooks - Women In Uniform (3170581)
Computing track assignment...
...done.
Success. Distance: 0.55
Sending event: albuminfo_received
Candidate: Skyhooks - Live In The 80's (11576177)
Computing track assignment...
...done.
Success. Distance: 0.10
Evaluating 10 candidates.

/downloads/Skyhooks/Skyhooks - Live In The 80s (12 items)
Sending event: before_choose_candidate
Correcting tags from:
    Skyhooks - Live In The 80's
To:
    Skyhooks - Live in the 80's
URL:
    https://musicbrainz.org/release/303bb89a-72b6-4825-b71d-58d4347664b5
(Similarity: 95.1%) (tracks) (1983, AU)
 * Ego Is Not A Dirty Word               -> Ego (Is Not a Dirty Word)
 * You Just Like Me 'Cos I'm Good In Bed -> You Just Like Me 'Cos I'm Good in Bed
 * Carlton (Lygon Street Limbo)          -> Million Dollar Riff (title)
 * Living In The 70's                    -> Living in the 70's
 * Million Dollar Riff                   -> Carlton (Lygon Street Limbo) (title)
 * Women In Uniform                      -> Women in Uniform
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? S
Sending event: import_task_choice
Sending event: import
Sending event: cli_exit
```

### Setup
* OS: ubuntu bionic on docker
* Python version: 3.6.9
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
library: /music/musiclibrary.blb
directory: /music

ui:
    color: yes

import:
    move: yes
    quiet_fallback: skip
art_filename: folder

paths:
    default: $albumartist/$album%aunique{} [$year]/$track - $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{} [$year]/$track - $title
plex:
    host: 000000000
    port: 32400
    token: kajdnjadnkajdnajkdnkajdna
    library_name: Music

plugins: convert discogs fetchart missing plexupdate scrub
convert:
    auto: yes
    dest:
    pretend: no
    threads: 2
    format: mp3
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
missing:
    count: no
    total: no
    album: no
scrub:
    auto: yes
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
```

In this example `Carlton (Lygon Street Limbo)` and `Million Dollar Riff` would be renamed incorrectly.
Please let me know what I can provide to debug it further, and thanks..
