### ISSUE TITLE
use existing MBID if available instead of trying to match metadata

### ISSUE THREAD

**Issue by hashhar** [beetbox/beets#3548]
### Use case

I'm trying to use beets to organise an already tagged collection which includes all the relevant MusicBrainz tags already.

What I'm currently observing it that with a config like:

```yaml
library: /mnt/d/Music/beets/library.db
directory: /mnt/d/Music/beets/Collection

plugins:
  - acousticbrainz
  - inline
  # mbupdate command to send data to a MusicBrainz collection
  - mbcollection

acousticbrainz:
  auto: yes
  force: yes

mbcollection:
  auto: yes
  collection:
  remove: yes

musicbrainz:
  user:
  pass:

ignore_hidden: no
asciify_paths: no
threaded: yes
original_date: no
artist_credit: no
per_disc_numbering: yes
aunique:
  keys: albumartist albumtype original_year year album
  disambiguators: albumdisambig label
  bracket: '[]'
id3v23: yes
va_name: 'Various Artists'

ui:
  color: yes

import:
  write: no
  copy: no
  move: no
  resume: ask
  incremental: no
  incremental_skip_later: no
  from_scratch: no
  timid: yes
  log: /mnt/d/Music/beets/importer.log
  languages: en
  group_albums: yes
  autotag: yes
  bell: yes
```

When running using `beets import ../Collection` it keeps querying some external source and comes up with different releases (within the same release group) even though the release id is already available in the ID3 tags.

**How can I instruct beets to fetch data using the existing MusicBrainz IDs instead of trying to match metadata?**
