### ISSUE TITLE
Auto-tagger picking weaker match

### ISSUE THREAD

**Issue by nirvdrum** [beetbox/beets#3564]
### Problem

I'm running into a problem where the auto-tagger is ignoring my country preference and consequently picking a weaker match. The vast majority of my CD collection consists of US releases, but I do have some imports. As a result, my `match.preferred.countries` configuration is `['US']`.

Running this command in verbose (`-vv`) mode:

```sh
beet -vv import -t /media/cd_rips/Pretty\ Hate\ Machine/
```

Led to this problem:

```
overlaying configuration: /root/beets/config.yaml
no user configuration found at /root/.config/beets/config.yaml
data directory: /root/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field albumtype_display
inline: adding item field compilation_display
inline: adding item field country_display
inline: adding item field disambiguation_display
lyrics: Disabling google source: no API key configured.
library database: /media/music/.beets.db
library directory: /media/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /media/cd_rips/Pretty Hate Machine
Tagging Nine Inch Nails - Pretty Hate Machine
No album ID found.
Search terms: Nine Inch Nails - Pretty Hate Machine
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'pretty hate machine', 'artist': 'nine inch nails', 'tracks': '10'}
Requesting MusicBrainz release 95e2508f-e830-4a79-a85c-ad5db1ae64cd
primary MB release type: album
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (95e2508f-e830-4a79-a85c-ad5db1ae64cd)
Computing track assignment...
...done.
Success. Distance: 0.05
Requesting MusicBrainz release ddf2fb0f-d0a7-4fd1-86ae-0843f57b95fd
primary MB release type: album
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (ddf2fb0f-d0a7-4fd1-86ae-0843f57b95fd)
Computing track assignment...
...done.
Success. Distance: 0.06
Requesting MusicBrainz release 5b5d00e8-3d90-3da7-9c17-c9e0e0376076
primary MB release type: album
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (5b5d00e8-3d90-3da7-9c17-c9e0e0376076)
Computing track assignment...
...done.
Success. Distance: 0.02
Requesting MusicBrainz release c90cf375-3208-378a-8535-8c9d68b5446b
primary MB release type: album
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (c90cf375-3208-378a-8535-8c9d68b5446b)
Computing track assignment...
...done.
Success. Distance: 0.05
Requesting MusicBrainz release d0e34aea-d5d4-3ec1-9147-24e1de5f001d
primary MB release type: album
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (d0e34aea-d5d4-3ec1-9147-24e1de5f001d)
Computing track assignment...
...done.
Success. Distance: 0.03
discogs: Searching for master release 3406
discogs: hit rate limit, waiting for 0.6294822692871094 seconds
discogs: Searching for master release 3406
discogs: hit rate limit, waiting for 0.6566057205200195 seconds
discogs: Searching for master release 3406
discogs: hit rate limit, waiting for 0.6517527103424072 seconds
discogs: Searching for master release 3406
discogs: hit rate limit, waiting for 0.6592931747436523 seconds
discogs: Searching for master release 3406
discogs: hit rate limit, waiting for 0.6544384956359863 seconds
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (3004371)
Computing track assignment...
...done.
Success. Distance: 0.09
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (75544)
Computing track assignment...
...done.
Success. Distance: 0.06
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (9154868)
Computing track assignment...
...done.
Success. Distance: 0.09
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (2580092)
Computing track assignment...
...done.
Success. Distance: 0.14
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (145796)
Computing track assignment...
...done.
Success. Distance: 0.03
Evaluating 10 candidates.

/media/cd_rips/Pretty Hate Machine (10 items)
Sending event: before_choose_candidate
Tagging:
    Nine Inch Nails - Pretty Hate Machine
URL:
    https://musicbrainz.org/release/5b5d00e8-3d90-3da7-9c17-c9e0e0376076
(Similarity: 98.1%) (country, year) (CD, 1991, AU, Interscope Records, 7567-91834-2)

```

As you can see, I'm only presented with a single choice. An Australian release with a 98.1% match. However, if I search on Musicbrainz, there's a US release with a 100% match:

```
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? i
Enter release ID: 60a04a88-3956-49f5-9d0f-b2603be9f612
Tagging Nine Inch Nails - Pretty Hate Machine
Searching for album ID: 60a04a88-3956-49f5-9d0f-b2603be9f612
Requesting MusicBrainz release 60a04a88-3956-49f5-9d0f-b2603be9f612
primary MB release type: album
Sending event: albuminfo_received
Candidate: Nine Inch Nails - Pretty Hate Machine (60a04a88-3956-49f5-9d0f-b2603be9f612)
Computing track assignment...
...done.
Success. Distance: 0.00
discogs: Searching for release 60a04a88-3956-49f5-9d0f-b2603be9f612
Evaluating 1 candidates.
Sending event: before_choose_candidate
Tagging:
    Nine Inch Nails - Pretty Hate Machine
URL:
    https://musicbrainz.org/release/60a04a88-3956-49f5-9d0f-b2603be9f612
(Similarity: 100.0%) (CD, 1989, US, TVT Records, TVT 2610-2)
```

I'm able to select "More candidates", but that seems to have an upper limit of 10 items. Some releases I'm looking at have more than 10 and the 100% match is buried deeper in the list.

### Setup

* OS: FreeBSD
* Python version: 3.7.7
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    force: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    local: no
    sources:
    - google
    - lyricwiki
    - musixmatch
    - genius
directory: /media/music
library: /media/music/.beets.db
per_disc_numbering: yes

plugins:
- discogs
- duplicates
- edit
- embedart
- extrafiles
- fetchart
- info
- inline
- lastgenre
- lyrics
- missing
- plexupdate
- scrub
- the
- web
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
embedart:
    auto: no
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
extrafiles:
    patterns:
        artwork: ['*.jpg']
        eac_logs: ['*.log']

    paths: {}
fetchart:
    midwidth: 400
    sources:
    - filesystem
    - itunes
    - amazon
    - albumart
    - coverart
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
format_album: $albumartist - $album ($year) $id
item_fields:
    albumtype_display: ''''' if albumtype.upper() == ''ALBUM'' or albumtype.upper() == ''COMPILATION'' else '' [%s]'' % (albumtype.upper())'
    compilation_display: '''Soundtracks'' if albumtype.upper() == ''SOUNDTRACK'' else ''Compilations'''
    country_display: country_display = ' [%s]' % (country.upper()); return '' if country.strip() == '' or country.upper() == 'US' or country_display in album else country_display
    disambiguation_display: ''''' if albumdisambig == '''' else '' (%s)'' % ('' ''.join([part.capitalize() for part in albumdisambig.split('' '')]))'

match:
    preferred:
        countries:
        - US
        media: [CD, Digital Media|File]
        original_year: yes

paths:
    comp: $compilation_display/$year - $album$country_display$disambiguation_display (%upper{$format})/$disctitle/$track $title
    default: '%the{$albumartist}/$year - $album$country_display$albumtype_display$disambiguation_display (%upper{$format})/$disctitle/$track $title'
plex:
    host: 192.168.13.202
    port: 32400
    token: REDACTED
    library_name: Music
web:
    host: 0.0.0.0
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
pathfields: {}
album_fields: {}
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
missing:
    count: no
    total: no
    album: no
scrub:
    auto: yes
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
```
