### ISSUE TITLE
ZSH Autocomplete Error: invalid regex

### ISSUE THREAD

**Issue by DomenicF** [beetbox/beets#3583]
When using beet import and ZSH (autocomplete) I get the following errors every time:

```sh
_beet:zregexparse:4: invalid regex : )
_beet:zregexparse:4: invalid regex : )
_beet:zregexparse:4: invalid regex : )
```

### Setup

* OS: Pop!_OS 20.04 (based on Ubuntu, using Ubuntu package)
* Python version: 3.8.2
* beets version: 1.4.9

My configuration (output of `beet config`) is:

```yaml
library: ~/beets.db
directory: /mnt/ORGANIZED_MUSIC

plugins: acousticbrainz fetchart lastgenre scrub

paths:
    default: $albumartist/$albumartist - $album%aunique{} ($year) [$format]/$track. $title
    singleton: Non-Album/$artist ($year) [$format]/$track. $title
    comp: Compilations/$album%aunique{} ($year) [$encoder]/$track. $title
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
acousticbrainz:
    auto: yes
    force: no
    tags: []
scrub:
    auto: yes
```

Any help would be appreciated. Thank you!
