### ISSUE TITLE
beets import error:  -bash: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by ArcaneGroove** [beetbox/beets#3584]
Hey! I'm in need of help here. I tried to install the discogs plugin for beets and ever since i have been getting 

-bash: syntax error near unexpected token `(' 

How can i fix this? I'm very new to python and git so maybe this is an easy fix but i cant seem to find any info on it. Thanks in advance for the help.

### Problem

Riley-Strattons-MacBook-Pro:~ Riley$ beet import /Users/Riley/Desktop/Music/2020/complete/Tom and Jerry (FLAC)/For Beet
-bash: syntax error near unexpected token `('
Riley-Strattons-MacBook-Pro:~ Riley$ 

### Setup

* OS: 10.11.6 (15G1004)
* Python version: 2.7 and 3.8
* beets version: Most Recent
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /Users/Riley/Desktop/Music/New Music
library : /Users/Riley/Desktop/Music/NewMusicDB/musiclibrary.db


import:
    # write metadata to music files
    write: yes

    # move imported files from source to the music directory
    move: no
    copy: yes
    delete: no
```
Here is my echo $PATH

/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/Riley/Library/Python/3.8:/Users/Riley/Library/Python/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

i've deleted the discogs plugin but i'm still getting the 

-bash: syntax error near unexpected token `('
