### ISSUE TITLE
How to convert and move / copy if no candidate found ?

### ISSUE THREAD

**Issue by chromafunk** [beetbox/beets#3585]
### Use case

I was using beets only to tag my collection, but now I am also using it to transcode to a new mp3 library. This is all fine and working, but since I started building the mp3 library, when an album directory is skipped because of metadata not found or candidate doesn't meet requirements, it ignores the album and doesn't copy it / move it to the library. 

Is there a way to tell beets to copy the album to the transcoded library even if there is no metadata candidate found ?

I am running beets with: `beet -vv import -a -q`

directory: /home/xavier/music/

```
import:
    copy: yes
    write: yes
    move: yes
    log: beetslog.txt


library: /home/xavier/beets_lib/musiclibrary.db


match:
    strong_rec_thresh: 0.50

plugins: fetchart lastgenre acousticbrainz embedart discogs chroma convert

convert:
        auto: yes
        copy_album_art: yes
        dest: /home/xavier/music/
        embed: yes
        never_convert_lossy_files: no
        command: ffmpeg -i $source -y -vn -aq 2 $dest
        extension: mp3


acousticbrainz:
        auto: true
        force: true
fetchart:
        auto: yes
        sources: itunes amazon wikipedia google fanarttv filesystem coverart albumart
        google_key: XXX
        fanarttv_key: XXX
        minwidth: 300

embedart:
        auto: yes

lyrics:
        google_API_key: XXX

art_filename: albumart


pluginpath: ~/beets/myplugins
ui:
    color: yes
```

Thanks
