### ISSUE TITLE
Beets uses (filesize / duration) as bitrate instead of audio stream bitrate

### ISSUE THREAD

**Issue by jheyens** [beetbox/beets#3623]
### Problem

I have a music library of ~20000 opus files and played a little with the embedart plugin yesterday. When embedding or clearing art from the media files themselves, obviously the file size changes. What I did not expect, however, was that a subsequent library update would adjust all the bitrates:

```sh
$ beet clearart
...

$ beet update
...
The Rolling Stones - The Rolling Stones - Honest I Do
  bitrate: 185kbps -> 156kbps
...
```

I think it's _technically_ correct to use the whole file for calculating the bitrate, but I think the more useful metric would be the bitrate of the audio stream in the container. At least I was surprised that beets did update the bitrate of my files due to embedding/clearing album art.

### Setup

* OS: Arch Linux
* Python version: Python 3.8.3
* beets version: beets version 1.4.9

* Turning off plugins made problem go away (yes/no): the issue kind of depends on the embedart plugin

My configuration (output of `beet config`) is:

```yaml
directory: ~/NC/Music
library: ~/.config/beets/library.db

import:
    move: yes

plugins: discogs embedart fetchart
embedart:
    auto: no
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: REDACTED
    fanarttv_key: REDACTED
    store_source: no
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
```
