### ISSUE TITLE
Crash when trying to retrieve lyrics

### ISSUE THREAD

**Issue by Clouraxe** [beetbox/beets#3630]
### Problem

Running `beet lyrics` finds some lyrics but then crashes in the middle of the process

```sh
$ beet lyrics
```

Led to this problem:
a crash
traceback: https://hastebin.com/kepanitono.sql

Here's a link to the music files that trigger the bug (if relevant): Im not really sure sorry, its going through my whole list

### Setup

* OS: Android 10.0
* Python version: 3.8.3
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): yes (?)

My configuration (output of `beet config`) is:

```yaml
directory: /sdcard/Music
library: ~/data/musiclibrary.db
import:
    copy: no
    from_scratch: yes
    languages: en

plugins: fromfilename chroma fetchart embedart lyrics

fetchart:
    cautious: yes
embedart:
    ifempty: yes
```
