### ISSUE TITLE
Beets doesn't rename song's filenames

### ISSUE THREAD

**Issue by entuccio** [beetbox/beets#3653]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
user configuration: /Users/daniele/.config/beets/config.yaml
data directory: /Users/daniele/.config/beets
plugin paths: 
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: /Users/daniele/.config/beets/library.db
library directory: /Volumes/GoogleDrive/My Drive/DaniSynologyNas/Musica
Sending event: library_opened
Usage: 
  beet COMMAND [ARGS...]
  beet help COMMAND

Options:
  --format-item=FORMAT_ITEM
                        print with custom format
  --format-album=FORMAT_ALBUM
                        print with custom format
  -l LIBRARY, --library=LIBRARY
                        library database file to use
  -d DIRECTORY, --directory=DIRECTORY
                        destination music directory
  -v, --verbose         log more details (use twice for even more)
  -c CONFIG, --config=CONFIG
                        path to configuration file
  -h, --help            show this help message and exit

Commands:
  clearart          remove images from file metadata
  config            show or edit the user configuration
  duplicates (dup)  List duplicate tracks or albums.
  edit              interactively edit metadata
  embedart          embed image files into file metadata
  extractart        extract an image from file metadata
  fetchart          download album art
  fields            show fields available for queries and format strings
  help (?)          give detailed help on a specific sub-command
  import (imp, im)  import new music
  info              show file metadata
  lastgenre         fetch genres
  lastimport        import last.fm play-count
  list (ls)         query the library
  lyrics            fetch song lyrics
  mbupdate          Update MusicBrainz collection
  missing (miss)    List missing tracks.
  modify (mod)      change metadata fields
  move (mv)         move or copy items
  mpdstats          run a MPD client to gather play statistics
  play              send music to a player as a playlist
  random            choose a random track or album
  remove (rm)       remove matching items from the library
  scrub             clean audio tags
  splupdate         update the smart playlists. Playlist names may be passed
                    as arguments.
  stats             show statistics about the library or a query
  update (upd, up)  update the library
  version           output version information
  write             write tag information to files
  ydl               Download music from YouTube
Sending event: cli_exit
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Catalina 10.15
* Python version: 3.7
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/GoogleDrive/My Drive/DaniSynologyNas/Musica

import:
    move: yes
    copy: no
    write: yes

plugins: edit lyrics scrub mbcollection mpdstats fetchart smartplaylist mpdupdate random embedart random lastimport duplicates missing fromfilename lastimport info hook play lastgenre ydl discogs

embedart:
    auto: yes      

ignore_hidden: yes                        


mpd:
    host: localhost
    port: 6600

lyrics:
  auto: no
  sources:
    - google
    - lyricwiki
    - musixmatch
    - genius

smartplaylist:
    relative_to: /Volumes/GoogleDrive/My Drive/DaniSynologyNas/Musica
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: smart_allFrancoBattiato.m3u
          query: 'artist:Franco Battiato'

        - name: smart_allMuse.m3u
          query: 'artist:Muse'

        - name: smart_allSystemOfaDown.m3u
          query: 'artist:System of a Down'

        - name: smart_allLucioBattisti.m3u
          query: 'artist:Lucio Battisti'

        - name: smart_allQueen.m3u
          query: 'artist:Queen'

        - name: smart_allFabriFibra.m3u
          query: 'artist:fabri fibra'

        - name: smart_allKaos.m3u
          query: 'artist:kaos one'


hook:
  hooks:
    # chiama Alfred quando inizia importazione
    - event: import_task_start
      command: /usr/bin/osascript /Applications/Alfred.alfredpreferences/workflows/user.workflow.768A02FA-A8F7-444B-9288-CB9F22FACACE/inizioimportazione.scpt

    # chiama Alfred quando completa una importazione
    - event: import
      command: /usr/bin/osascript /Applications/Alfred.alfredpreferences/workflows/user.workflow.768A02FA-A8F7-444B-9288-CB9F22FACACE/importazione.scpt


#serve per creare la playlist di un album
play:
    command: /usr/local/bin/mpc load

missing:
    format: $albumartist - $title -$year
    count: no
    total: no

mbcollection:
    auto: yes
    remove: yes

musicbrainz:
    user: entuccio
    pass: REDACTED

fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no

duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''

sort_album: year+

replace:
    '[\\/]': ''
    '^\.': _
    '[\x00-\x1f]': ''
    '[<>:"\?\*\|]': ''
    '\.$': ''
    '\s+$': ''
    '^\s+': ''
    '[\xf9]': ''
    '[\xfa]': ''
    '[ù]': ''

color: yes

bell: yes

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title


```
