### ISSUE TITLE
Track and disc numbers are added to mpd database as "NN | NN"

### ISSUE THREAD

**Issue by rnkn** [beetbox/beets#3662]
When importing or updating an item in the beets database, track and numbers are added to the mpd database as `NN | NN` e.g. `01 | 01` for track 1, `05 | 05` for track 5, `01 | 01` for disc 1, etc. and need to be manually edited to `01` `05` etc.

### Problem

Running this command in verbose (`-vv`) mode:

```text
$ beet -vv mod music for sleep added:-1d.. via=Bandcamp
```

Led to this problem:

```
Nostromo(s002) ~ % beet -vv mod music for sleep added:-1d.. via=Bandcamp
user configuration: /Users/william/.config/beets/config.yaml
data directory: /Users/william/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Users/william/.config/beets/library.db
library directory: /Volumes/Apollo/music
Sending event: library_opened
Modifying 1 items.
Music for Sleep - Return to Nara - Return to Nara
  via: Bandcamp
Really modify, move and write tags? (Yes/no/select) 

Sending event: write
Sending event: after_write
moving /Volumes/Apollo/music/Music for Sleep/Return to Nara/01 Return to Nara.flac to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
smartplaylist: Last 2 Wks.m3u will be updated because of Music for Sleep - Return to Nara - Return to Nara
smartplaylist: Lossless.m3u will be updated because of Music for Sleep - Return to Nara - Return to Nara
smartplaylist: Last Month.m3u will be updated because of Music for Sleep - Return to Nara - Return to Nara
smartplaylist: via Bandcamp.m3u will be updated because of Music for Sleep - Return to Nara - Return to Nara
Sending event: database_change
Sending event: database_change
Sending event: cli_exit
smartplaylist: Updating 4 smart playlists...
smartplaylist: Creating playlist Last Month.m3u
smartplaylist: Creating playlist Last 2 Wks.m3u
smartplaylist: Creating playlist Lossless.m3u
smartplaylist: Creating playlist via Bandcamp.m3u
smartplaylist: 4 playlists updated
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Lossless.m3u
playlist: Updated playlist /Volumes/Apollo/music/playlists/Lossless.m3u (1 changes, 0 deletions)
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Last Month.m3u
playlist: Updated playlist /Volumes/Apollo/music/playlists/Last Month.m3u (1 changes, 0 deletions)
playlist: Updating playlist: /Volumes/Apollo/music/playlists/low bitrate.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Singles Collection.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/via Bandcamp.m3u
playlist: Updated playlist /Volumes/Apollo/music/playlists/via Bandcamp.m3u (1 changes, 0 deletions)
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Music of This Year.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Last 2 Wks.m3u
playlist: Updated playlist /Volumes/Apollo/music/playlists/Last 2 Wks.m3u (1 changes, 0 deletions)
playlist: Updating playlist: /Volumes/Apollo/music/playlists/2010 - Freedom (We don't bleed when we don't fight).m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/2011 - George Clooney.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/2012 - Roland Emmerich.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/2013 - Thirteen.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/2019 - Cut Open.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/201x - Endless War.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/2020 - Like A Virus.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/BURIAL 4PWR.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Classical Me Maybe.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Eno :: Ambient.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/I've Got Dreams to Remember.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/In Case of Sadness, Break Glass.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Mix CD from Susu Laroche.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Pop Bangas!.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/The Covers Playlist.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/via Daniel.m3u
playlist: Updating playlist: /Volumes/Apollo/music/playlists/Dragon Punch!.m3u
mpdupdate: Updating MPD database...
mpdupdate: Database updated.
```

Here's a link to the music files that trigger the bug (if relevant): (N/A, happens with all music)

### Setup

* OS: macOS 10.15.5 (19F101)
* Python version:
```
Nostromo(s002) ~ % python --version
Python 2.7.16
Nostromo(s002) ~ % python3 --version
Python 3.7.7
```
* beets version:
```
beets version 1.4.9
Python version 3.7.7
plugins: convert, discogs, duplicates, edit, embedart, fetchart, missing, mpdupdate, playlist, smartplaylist
```
* Turning off plugins made problem go away (yes/no): Yes, the `mpdupdate` plugin needs to be enabled to reproduce

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/Apollo/music

import:
    copy: yes
    write: yes
    log: import.log
asciify_paths: yes
original_date: yes

match:
    preferred:
        countries: [au, us]
        media: [cd, digital]
    ignored_media: vinyl
languages: en

paths:
    default: $albumartist/$album/$track $title
    singleton: singles/$artist/$title
    genre:soundtrack: soundtracks/$album%aunique{}/$track $title
    comp: compilations/$album/$track $title

plugins:
- convert
- discogs
- duplicates
- edit
- embedart
- fetchart
- missing
- mpdupdate
- playlist
- smartplaylist
fetchart:
    auto: yes
    minwidth: 800
    enforce_ratio: 8px
    sources: itunes *
    maxwidth: 0
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
playlist:
    auto: yes
    relative_to: library
    playlist_dir: /Volumes/Apollo/music/playlists
smartplaylist:
    auto: yes
    relative_to: /Volumes/Apollo/music
    playlist_dir: /Volumes/Apollo/music/playlists
    playlists:
    -   name: Last 2 Wks.m3u
        query: added- added:-2w..
    -   name: Last Month.m3u
        query: added- added:-1m..
    -   name: Lossless.m3u
        query: added- format:alac, format:flac
    -   name: low bitrate.m3u
        query: albumartist+ bitrate:..128000
    -   name: Music of This Year.m3u
        query: year:2020
    -   name: Singles Collection.m3u
        query: singleton:true
    -   name: Loved Songs.m3u
        query: love:True
    -   name: The Covers Playlist.m3u
        query: cover:True
    -   name: via Daniel.m3u
        query: added- via:Daniel
    -   name: via Bandcamp.m3u
        query: added- via:Bandcamp
convert:
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -ab 256k $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    dest:
    pretend: no
    threads: 8
    format: mp3
    id3v23: inherit
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
mpd:
    music_directory: /Volumes/Apollo/music
    host: localhost
    port: 6600
    password: REDACTED
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
bandcamp:
    source_weight: 0.7
    art: yes
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
missing:
    count: no
    total: no
    album: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
```
