### ISSUE TITLE
secondary album type overrides primary

### ISSUE THREAD

**Issue by minusf** [beetbox/beets#3663]
It seems that the secondary album type overrides the primary:

```
primary MB release type: album
secondary MB release type(s): soundtrack
```

I have a custom `path` for soundtracks and this particular release ends up in soundtracks.

Wouldn't it make more sense if preferring the secondary type must be explicitly encouraged using `preferred` under `match:`, or something similar?

### Setup

* OS: macos
* Python version:  3.7.8
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /sonoteque

format_item: $artist - $album - $title - $length - $track
format_album: $albumartist - $album - $year

paths:
    default: '%lower{$albumartist/$original_year-$album/$track-$title}'
    genre:anime: '%lower{ost-anime/$album-$original_year/$track-$title}'
    genre:game: '%lower{ost-game/$album-$original_year/$track-$title}'
    genre:classic: '%lower{$composer/$album-$original_year/$track-$title}'
    albumtype:soundtrack: '%lower{ost/$album-$original_year/$track-$title}'
    comp: '%lower{various/$album-$original_year/$track-$title}'

match:
    preferred:
        media: [CD, Digital Media|File]
        original_year: yes
    ignored_media: [Data CD, DVD, DVD-Video]

import:
    from_scratch: yes
    move: yes
```
