### ISSUE TITLE
beet write seems to have no effect

### ISSUE THREAD

**Issue by gcoter** [beetbox/beets#3707]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv write -f
```

Doesn't seem to actually update my files tag. For instance, in the logs I see this:
```
Antonio Vivaldi - Die vier Jahreszeiten - Violinkonzerte op.8 : Der Winter I - Allegro non molto
  bpm: 137 -> 137.011138916
Sending event: write
Sending event: after_write
Sending event: database_change
```

But if I check the bpm in the track and in the library fields:
```bash
$ beet info Antonio Vivaldi Der Winter | grep bpm
                 bpm: 137
$ beet info -l Antonio Vivaldi Der Winter | grep bpm
                 bpm: 137.011138916
```

You can see that they are not the same. I would expect `beet write` to update my file tags so that they correspond to what is in the database. Here it looks like it doesn't actually write something. Is there something I misunderstood?

### Setup

* OS: Linux Aspire-E5-772G 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Python version: Python 3.6.9
* beets version: beets version 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    fallback: ''
    force: no
    sources: lyricwiki musixmatch
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    local: no
directory: ~/Nextcloud/Music/Collection/
library: ~/Nextcloud/Music/Collection/beets_library.db

paths:
    default: Albums/$albumartist/$album%aunique{}/$track - $title
    singleton: Singles/$artist - $title

plugins: scrub missing duplicates fromfilename lastgenre lyrics fetchart edit acousticbrainz info play
lastgenre:
    auto: yes
    count: 10
    whitelist: ~/projects/beets-config/lastgenre/genres.txt
    source: track
    min_weight: 10
    fallback:
    canonical: no
    force: yes
    separator: ', '
    prefer_specific: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
edit:
    itemfields: track title artist album genre lyrics
    albumfields: album albumartist genre
    ignore_fields: id path
acousticbrainz:
    auto: yes
    force: no
    tags: []
scrub:
    auto: yes
missing:
    count: no
    total: no
    album: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
play:
    command:
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
    bom: no
```
