### ISSUE TITLE
mpdstats records a skip when stopping playback

### ISSUE THREAD

**Issue by aereaux** [beetbox/beets#3722]
### Problem

I am using the mpdstats plugin.  Running `beet mpdstats` and then starting a song playing in mpd and then stopping it makes mpdstats record a skip and adjust the song rating downwards, even though that song remains at the beginning of the mpd playlist (i.e. it's not actually skipped).  Interestingly pausing and then later stopping seems to not cause this problem.

### Setup

* OS: Arch Linux
* Python version: 3.8.5
* beets version: b89a2650c
* Turning off plugins made problem go away (yes/no): Well... yes?

My configuration (output of `beet config`) is:

```yaml
plugins: parentwork scrub info mbsync alternatives chroma mpdstats
directory: ~/music/beets/

paths:
    default: '%ifdef{parent_composer_sort,$parent_composer_sort,[unknown]}/%ifdef{parentwork_date,$parentwork_date - }%ifdef{parentwork,$parentwork,[unknown]}/%ifdef{year,$year - }$album%aunique{album year,albumartist albumtype label catalognum albumdisambig releasegroupdisambig}/$track $title'

import:
    from_scratch: yes
    move: yes
acoustid:
    apikey: REDACTED
alternatives:
    aphone:
        directory: /home/user/music/aphone/
        formats: opus
        query: ''
parentwork:
    auto: no
    force: no
chroma:
    auto: yes
mpd:
    music_directory: /home/user/music/beets
    rating: yes
    rating_mix: 0.75
    host: localhost
    port: 6600
    password: REDACTED
scrub:
    auto: yes
```
