### ISSUE TITLE
Creating my own plugin and placing it in $PYTHONPATH cancels out the stock plugin I've enabled

### ISSUE THREAD

**Issue by dittoslash** [beetbox/beets#3739]
See title. While I'm here, the plugin I'm making manually adds metadata to music files with Taffy and I feel like Beets should be doing that itself, but it isn't.

### Problem
My plugin's currently located in python's site-packages folder, as such:
```
site-packages
  - beetsplug
    - __init__.py
    - actualtags.py
```
Having it there (or elsewhere in the PYTHONPATH) causes Beets to fail loading plugins:
```
** error loading plugin fetchart:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.fetchart'
```
and the same error occurs without it in PYTHONPATH, just with actualtags.

### Setup

* OS: Manjaro (yes, i know)
* Python version: 3.8.5
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is:

```yaml
directory: /var/music
library: /var/music/.beets.db

import:
    move: yes
    write: no

plugins: fetchart actualtags
```
