### ISSUE TITLE
beets.util.confit is deprecated; use confuse instead

### ISSUE THREAD

**Issue by avma** [beetbox/beets#3770]
The Backround:
Yesterday I accepted  python 3.8 update ver 3.8.5-1~20.4 from my Linux mint 20 update manager. Immediate after all beet commanded ended up with a bunch of errors (and without actual action).
So i went and installed pip3 install 'https://github.com/beetbox/beets/tarball/master', hoping that it will fix the problem,and indeed for the most part it did.
However now I'm getting on every beet command I'm running some new messages (see below).

### Problem

Running this command in verbose (`-vv`) mode:

```sh
~ » beet -vvv                                                                                                                      avi@avi-mint-pc
user configuration: /home/avi/.config/beets/config.yaml
data directory: /home/avi/.config/beets
plugin paths: 
/home/avi/.local/lib/python3.8/site-packages/beets/util/confit.py:21: UserWarning: beets.util.confit is deprecated; use confuse instead
  warnings.warn("beets.util.confit is deprecated; use confuse instead")
/home/avi/.local/lib/python3.8/site-packages/beets/mediafile.py:21: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
Sending event: pluginload
ImageMagick version check failed: [Errno 2] No such file or directory: 'magick'
artresizer: method is (2, (6, 9, 10), True)
library database: /home/avi/music_data/beets/mybeet_new.db
library directory: /home/avi/Music
Sending event: library_opened 
```

Led to this problem:
 I don not know what exactly id does. I'm not sure what these messages mean or if they are warnings that are safe to ignore which i doubt since they show up withe every beet command.
Also it complains about 'ImageMagick' although I do have both 'PILLOW' 7.2.0 and ImageMagick 6.9.10-23 Q16 x86_64 20190101 installed.
```
(paste here)
```
### Setup

* OS: Linux mint 20 Cinnamon
* Python version: 3.8 update ver 3.8.5-1~20.4
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
~ » beet config                                                                                                                    avi@avi-mint-pc
/home/avi/.local/lib/python3.8/site-packages/beets/util/confit.py:21: UserWarning: beets.util.confit is deprecated; use confuse instead
  warnings.warn("beets.util.confit is deprecated; use confuse instead")
/home/avi/.local/lib/python3.8/site-packages/beets/mediafile.py:21: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
lyrics:
    bing_lang_from: []
    auto: no
    fallback: ''
    force: yes
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    sources: google lyricwiki musixmatch genius *
    bing_client_secret: REDACTED
    bing_lang_to:
    genius_api_key: REDACTED
    local: no
directory: ~/Music
library: /home/avi/music_data/beets/mybeet_new.db

import:
    write: yes
    move: yes
    copy: no
    delete: no
    autotag: yes
    timid: no
    resume: ask
    incremental: no
    none_rec_action: ask
    log:
    quiet: no
    quiet_fallback: skip
    default_action: apply
    singletons: no
    languages: []
    detail: no
    flat: no
original_date: no
per_disc_numbering: no

clutter:
- Thumbs.DB
- .DS_Store
- '*.m3u'
- .pls
- '*.jpg'
ignore:
- .*
- '*~'
- System Volume Information
- .Trash-1*

paths:
    default: '%asciify{$albumartist}/%asciify{$album}%aunique{}/%asciify{$track}. %asciify{$title}'
    singleton: Non-Album/%asciify{$artist}/%asciify{$title}
    comp: Compilations/%asciify{$album}%aunique{}/$track %asciify{$title}

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
path_sep_replace: _
art_filename: cover_beet
max_filename_length: 0
threaded: yes
timeout: 5.0
verbose: no
color: yes
list_format_item: '%upper{$artist} - $album - $track. $title - $format $bitrate'
list_format_album: '%upper{$albumartist} - $album - $tracktotal'
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0

match:
    strong_rec_thresh: 0.1
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30

plugins:
- bpd
- beatport
- describe
- discogs
- duplicates
- embedart
- extrafiles
- fetchart
- lyrics
- info
- lastimport
- lastgenre
- mbcollection
- mbsync
- mpdupdate
- missing
- scrub
- smartplaylist
- spotify
- yearfixer
pluginpath: []
bpd:
    host: 127.0.0.1
    port: 6600
    volume: 100
    control_port: 6601
    password: REDACTED
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    separator: ', '
    index_tracks: no
duplicates:
    format: $path/%upper{$albumartist}/$album [$tracktotal]
    keys: [mb_trackid, mb_albumid]
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    full: no
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
echonest_tempo:
    auto: yes
embedart:
    auto: yes
    compare_threshold: 0
    ifempty: no
    maxwidth: 300
    remove_art_file: no
    quality: 0
extrafiles:
    patterns:
        all: '*.txt,*.cue,*.jpg,*.log,*.png,*.pdf'

    paths: {}
fetchart:
    auto: yes
    minwidth: 400
    cautious: yes
    cover_names: cover folder medium front back art album cd fold inley booklet
    sources: filesystem coverart amazon itunes albumart *
    maxwidth: 0
    quality: 0
    enforce_ratio: no
    google_key: REDACTED
    google_engine:REDACTED
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
lastimport:
    lastfm: REDACTED
    per_page: 500
    retry_limit: 3
lastfm:
    user: REDACTED
    api_key: REDACTED
lastgenre:
    auto: yes
    whitelist: ~/.config/beets/genres.txt
    canoncical: ~/.config/beets/genres-tree.yaml
    fallback: ''
    source: artist
    separator: '/ '
    min_weight: 10
    count: 1
    canonical: no
    force: yes
    prefer_specific: no
mbcollection:
    auto: yes
    collection: REDACTED
    remove: no
mpd:
    host: localhost
    port: 6600
    music_directory: ~/Music
    rating: yes
    rating_mix: 0.75
    password: REDACTED
missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no
    album: no

musicbrainz:
    user: REDACTED
    pass: REDACTED
replaygain:
    auto: yes
    overwrite: yes
    albumgain: yes
scrub:
    auto: yes
smartplaylist:
    relative_to: ~/Music
    playlist_dir: ~/Playlists
    playlists:
    -   name: Jazz.m3u
        query: genre:jazz
    -   name: Blues.m3u
        query: genre:blues
    -   name: Swing.m3u
        query: genre:Swing
    -   name: Country.m3u
        query: genre:country
    -   name: French.m3u
        query: genre:french
    -   name: Folk.m3u
        query: genre:Folk
    -   name: World.m3u
        query: genre:world
    auto: yes
    forward_slash: no
spotify:
    source_weight: 0.7
    mode: open
    region_filter: IL
    show_failures: yes
    tiebreak: first
    artist_field: albumartist
    album_field: album
    track_field: title
    regex: []
    client_id: REDACTED
    client_secret: REDACTED
    tokenfile: spotify_token.json
yearfixer:
    force: no
    auto: no
beatport:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: beatport_token.json
    source_weight: 0.5
describe:
    auto: no
```
