### ISSUE TITLE
"No tracks." reported from musicbrains when source is DVD

### ISSUE THREAD

**Issue by Mycah** [beetbox/beets#3785]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import .
```

Led to this problem:

```
Looking up: /home/mmattox/2004 - Pastperfect (disc01) [live]
Tagging VNV Nation - Pastperfect
Searching for discovered album ID: a8eb6da2-1423-41a4-af3c-f32cfb2f5bd7
Requesting MusicBrainz release a8eb6da2-1423-41a4-af3c-f32cfb2f5bd7
primary MB release type: album
secondary MB release type(s): compilation, live
Sending event: albuminfo_received
Candidate: VNV Nation - Pastperfect (a8eb6da2-1423-41a4-af3c-f32cfb2f5bd7)
No tracks.
Album ID match recommendation is Recommendation.none
```

Here's a link to the music files that trigger the bug (if relevant): n/a

### Setup

* OS: ubuntu 20.04
* Python version: 3.8.5
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
library: ~/.beets.db
directory: ~/music

plugins:
- convert
- duplicates
- fromfilename
- fuzzy
- info
- inline
- lastgenre
- mbsync
- missing
- badfiles
- random
- scrub
- the
- fetchart
- embedart
- web
- mbsubmit

replace:
    "\u201C": '"'
    "\u201D": '"'
    "\u2010": '-'
    "\u2011": '-'
    "\u2012": '-'
    "\u2013": '-'
    "\u2014": '-'
    "\u2015": '-'
    "\u2016": '-'
    "\u2026": '...'
original_date: yes
per_disc_numbering: yes

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
    distance_weights:
        missing_tracks: 10.0
asciify_paths: no

paths:
    default: $albumartist/%if{$year,$year - }$album%aunique{}/$track - $title%aunique{}
    singleton: $albumartist/%if{$year,$year - }$album%aunique{}/$track - $title%aunique{}
    comp: Compilation/%if{$year,$year - }$album%aunique{}/$track - $artist - $title%aunique{}
    albumtype:soundtrack: Soundtracks/%if{$year,$year - }$album%aunique{}/$track - $artist - $title%aunique{}
item_fields:
    cdtitle: u' - %s' % (disctitle) if disctitle else u''
    multidisc: 1 if disctotal > 1 else 0
    initial: artist.lower().lstrip('[]*')[0]
    nicelength: 'm, s = divmod(length, 60)

        h, m = divmod(m, 60)

        return "%d:%02d:%02d" % (h, m, s)

        '
album_fields:
    cdtype: u'[%s]' % (albumtype.lower()) if albumtype else u''
    notalbum: 0 if albumtype and albumtype.lower() == 'album' else 1
pathfields: {}

import:
    log: ~/beets.log
    write: yes
    copy: yes
convert:
    formats:
        alac:
            extension: m4a
            command: ffmpeg -i $source -y -vn -acodec alac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
        mp3: ffmpeg -i $source -y -vn -qscale:a 0 $dest
        aac:
            extension: m4a
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
    max_bitrate: 500
    embed: yes
    dest:
    copy_album_art: yes
    threads: 4
    never_convert_lossy_files: no
    pretend: no
    format: mp3
    tmpdir:
    quiet: no

    paths: {}
    auto: yes
    link: no
    hardlink: no
    id3v23: inherit
    no_convert: ''
    album_art_maxwidth: 0
    delete_originals: no
web:
    include_paths: no
    cors: ''
    port: 8337
    host: 127.0.0.1
    cors_supports_credentials: no
    reverse_proxy: no
fetchart:
    auto: yes
    minsize: 350
    maxsize: 700
    minwidth: 0
    maxwidth: 0
    quality: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
embedart:
    auto: yes
    remove_art_file: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    quality: 0
scrub:
    auto: yes
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
missing:
    count: no
    total: no
    album: no
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
fuzzy:
    prefix: '~'
    threshold: 0.7
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
mbsubmit:
    format: $track. $title - $artist ($length)
    threshold: medium
```
