### ISSUE TITLE
Unicode quote marks make `beet ls` appear to not work

### ISSUE THREAD

**Issue by ssssam** [beetbox/beets#3797]
### Problem

For some track names with apostrophes in, Musicbrainz uses U+2019 'single right quote mark' in place of the usual ASCII apostrophe.

This is the case, for example, in 1996 powerpop classic [Descendents - I'm The One](https://musicbrainz.org/recording/28ede7c3-6d0e-4c17-9b66-abb926956eba).

There's no simple way to enter U+2019 on a standard keyboard, so when searching for this track I type:

    beet ls I'm The One

In this case Beets doesn't return my favourite song of unrequited love, because the quote mark isn't the same.

### Setup

* OS: Fedora 33
* Python version: 3.9.0
* beets version: 297ff603dfa484f606eb8d755853e750b3cd026c
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /home/sam/External/Music
library: /home/sam/.local/share/beets/musiclibrary.db

import:
  move: yes
  write: yes
  log: /home/sam/.local/share/beets/import.log

plugins: check chroma duplicates export fromfilename fuzzy importadded info missing play random web

paths:
  # For random collections of music received from people that don't have a specific order
  collection::^.+$: $collection/$artist - $title
  
  default: $albumartist - $album [$original_year]/$track $title
  singleton: $artist/$title
  comp: $album [$original_year]/$track $title
  

include:
  - config-follow-muspy.yaml

extrafiles:
  patterns:
    all: '*.*'

play:
  command: /usr/bin/rhythmbox
```
