### ISSUE TITLE
Permission nearly always denied on modification to tag

### ISSUE THREAD

**Issue by ZhangTianrong** [beetbox/beets#3800]
### Problem

When running `import -s C:\Users\[USERNAME]\Music`, there is an error saying

```
error writing C:\Users\[USERNAME]\Music\[MUSICNAME].mp3: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\[USERNAME]\\Music\\[MUSICNAME].mp3'
```

almost whenever beets needs to modify a file. The current user does have the ownership and I also ran `takeown /f C:\Users\[USERNAME]\Music /r` to make sure that is the case. I see there is a strange `\\\\?\\` in from of the drive label; is that what's expected?  Both `[USERNAME]` and `[MUSICNAME]` can be within ASCII when the error ocurrs.

### Setup

* OS:  Windows 10 Pro 19041
* Python version: 3.7.4
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
directory: C:\Users\[USERNAME]\Music
library: C:\Users\[USERNAME]\Music\musiclibrary.db
import:
  copy: no
  write: yes
  languages: ['en', 'zh_CN', 'zh', 'jp', 'fr']
  log: C:\Users\[USERNAME]\Music\beet.log
  default_action: skip
  detail: true
match:
    preferred:
        countries: ['US', 'CN']
```
