### ISSUE TITLE
Imported album missing from database

### ISSUE THREAD

**Issue by syco** [beetbox/beets#3803]
I've reorganized my collection with beets recently, I've used the move option to move all files from lidarr to a new music folder.

The problem is that some albums were imported and matched to musicbrainz metadata, but when I do `beet ls -a` they don't appear.

For example, here the album Breaker is missing from `beets ls`:
```bash
$ ls -1 Accept/
Accept [2002]
Balls to the Wall [1983]
Blind Rage [2014]
Blood of the Nations [2010]
Breaker [2000]
Death Row [1995]
Eat the Heat [1989]
I'm a Rebel [2010]
Metal Heart [2002]
Objection Overruled [1993]
Predator [1996]
Restless and Wild [1992]
Russian Roulette [2009]
Stalingrad [2012]
The Rise of Chaos [2017]

$ beet -vv ls -a 'Accept'
user configuration: /config/config.yaml
data directory: /config
plugin paths: 
Sending event: pluginload
library database: /config/musiclibrary.blb
library directory: /music
Sending event: library_opened
Accept - Accept
Accept - Balls to the Wall
Accept - Blind Rage
Accept - Blood of the Nations
Accept - Death Row
Accept - Eat the Heat
Accept - I'm a Rebel
Accept - Metal Heart
Accept - Objection Overruled
Accept - Predator
Accept - Restless and Wild
Accept - Russian Roulette
Accept - Stalingrad
Accept - The Rise of Chaos
Sending event: cli_exit
```

### Setup
* OS: CentOS 7 + docker and linuxserver/beets
* Python version: 3.8.2
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): didn't try as the command `beet --plugins= version` returns the following:
```bash
$ beet --plugins= version

Usage: 
  beet COMMAND [ARGS...]
  beet help COMMAND

beet: error: no such option: --plugins
```

My configuration (output of `beet config`) is:
```yaml
plugins: convert discogs fetchart lastgenre missing replaygain scrub web
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
  auto: yes
  never_convert_lossy_files: yes
  dest: /music
  ffmpeg: /usr/bin/ffmpeg
  opts: -ab 320k -ac 2 -ar 48000
  format: mp3
  #max_bitrate: 640
  threads: 1

import:
  write: yes
  copy: yes
  move: no
  resume: ask
  incremental: yes
  quiet_fallback: skip
  timid: no
  log: /config/beet.log

fetchart:
  auto: yes

lastgenre:
  auto: yes
  source: album

missing:
  format: $albumartist - $album - $title
  count: no
  total: no

paths:
  default: $albumartist/$album%aunique{} [$year]/$track - $title
  singleton: Singleton/$artist - $title
  comp: Compilations/$album%aunique{} [$year]/$track - $title
  albumtype_soundtrack: Soundtracks/$album [$year]/$track - $title 

replaygain:
  auto: no

scrub:
  auto: yes

web:
  host: 0.0.0.0
  port: 8337
```

I don't know if this happened to other albums, how can I scan again the folder and recreate or update the database?

I tried `beet update` but it didn't work.

Thanks
