### ISSUE TITLE
ReplayGain: import stage write callbacks can have outdated metadata

### ISSUE THREAD

**Issue by ybnd** [beetbox/beets#3819]
### Problem

After parallel ReplayGain analysis on import, writing to newly imported files can fail if they're moved.

### Temporary solution

* #3818 
* The results are still stored in the database, so you can persist them to the imported files by running `beet write` after importing.

### Setup

* OS: any
* Python version: any 
* beets version: 206b1c10996d36084791b31dc7805e202552abe9
* Turning off plugins made problem go away (yes/no): N/A

Configuration:

```yaml
plugins: replaygain ...

replaygain:
   auto: yes
   overwrite: yes
```
