### ISSUE TITLE
Requesting option to slowdown fetchart process so I dont get banned. I hacked in a delay that appears to be working.

### ISSUE THREAD

**Issue by xekon** [beetbox/beets#3827]
### Use case

I am new to beets and using it to download some cover art. It goes so fast that sites temp ban me.
I know because it will find art for like 30 albums in a row and then all of a sudden no art is found for ANY albums.

Once I hacked in my delay the same albums that said no art found are now finding the art.

### Solution

`sudo nano /root/.local/lib/python3.8/site-packages/beets-1.5.0-py3.8.egg/beetsplug/fetchart.py`

at the top of the file:

```python
import os
import re
import time
```

at the bottom of the file:

```python
                local_paths = None if force else [album.path]

                # Add some delay so these nice sites do not ban us
                time.sleep(2) # Sleep for 2 seconds

                candidate = self.art_for_album(album, local_paths)
```

1 second may have been enough instead of 2 seconds, but honestly I am in no rush, I just want the convenience of automatic art download, and dont want to risk a permanent ban on any of these great sites.

```
plugins: fetchart
fetchart:
    auto: yes
    cautious: no
    fanarttv_key: REDACTED
    minwidth: 1000
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - lastfm
    - fanarttv
```
