### ISSUE TITLE
Beet modify fails to edit grouping tag and lies about doing so

### ISSUE THREAD

**Issue by metronidazole** [beetbox/beets#3840]
### Problem
If you attempt to edit a grouping tag, beets appears to do so, but in reality it does not

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv mod -a faery grouping=Game
user configuration: /home/metronidazole/.config/beets/config.yaml
data directory: /home/metronidazole/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/metronidazole/Music/beets_library.db
library directory: /home/metronidazole/Music/library
Sending event: library_opened
Modifying 1 albums.
David Joiner - The Faery Tale Adventure Book 1 Amiga Game Recording
  grouping: Game2 -> Game
Really modify, move and write tags? (Yes/no/select) yes

Sending event: database_change
Sending event: write
Sending event: after_write
moving /home/metronidazole/Music/library/David Joiner/1988 - The Faery Tale Adventure Book 1 Amiga Game Recording []/01 - Faery Tale Adventure - Intro.mp3 to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
moving /home/metronidazole/Music/library/David Joiner/1988 - The Faery Tale Adventure Book 1 Amiga Game Recording []/02 - Faery Tale Adventure - Ingame Day.mp3 to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
moving /home/metronidazole/Music/library/David Joiner/1988 - The Faery Tale Adventure Book 1 Amiga Game Recording []/03 - Faery Tale Adventure - Ingame Night.mp3 to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
moving /home/metronidazole/Music/library/David Joiner/1988 - The Faery Tale Adventure Book 1 Amiga Game Recording []/04 - Faery Tale Adventure - Indoors.mp3 to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
moving /home/metronidazole/Music/library/David Joiner/1988 - The Faery Tale Adventure Book 1 Amiga Game Recording []/05 - Faery Tale Adventure - Fight.mp3 to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
moving /home/metronidazole/Music/library/David Joiner/1988 - The Faery Tale Adventure Book 1 Amiga Game Recording []/06 - Faery Tale Adventure - Angel.mp3 to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
moving /home/metronidazole/Music/library/David Joiner/1988 - The Faery Tale Adventure Book 1 Amiga Game Recording []/07 - Faery Tale Adventure - Death.mp3 to synchronize path
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: cli_exit
```

Led to this problem:

```
$ beet -vv list faery grouping=Game
user configuration: /home/metronidazole/.config/beets/config.yaml
data directory: /home/metronidazole/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/metronidazole/Music/beets_library.db
library directory: /home/metronidazole/Music/library
Sending event: library_opened
Sending event: cli_exit

Using an external tag editor also shows the grouping tag is not applied
```

Here's a link to the music files that trigger the bug (if relevant):
https://archive.org/details/Saladedemais_-_The_Faery_Tale_Adventure_Amiga

### Setup

* OS: Arch Linux 
* Python version: 3.9.1 
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/library
library: ~/Music/beets_library.db

plugins: the fetchart embedart missing

import:
    copy: yes

per_disc_numbering: no

paths:
    grouping:Foo genre:Soundtrack: "_Foo/_Soundtrack/$albumartist/$year - $album%aunique{}/$track - $title"
    grouping:Foo singleton:false comp:false: "_Foo/$albumartist/$year - $album%aunique{}/$track - $title"
    grouping:Foo singleton:true: "_Foo/_Non-Album/$artist/$title"
    grouping:Foo comp:true: "_Foo/_Compilation/$albumartist/$year - $album%aunique{}/$track - $title"

    genre:Game: "_Game/$albumartist/$original_year - $album%aunique{}/$title"
    grouping:Game: "_Game/$albumartist/$original_year - $album%aunique{}/$title"
    genre:Soundtrack: "_Soundtrack/$albumartist/$original_year - $album%aunique{}/$track - $title"

    default: "$albumartist/$original_year - $album%aunique{} [%upper{$albumtype}]/$track - $title"
    singleton: "_Non-Album/$artist/$title"
    comp: "_Compilation/$albumartist/$original_year - $album%aunique{} [%upper{$albumtype}]/$track - $title"

fetchart:
    midwidth: 400
    enforce_ratio: 10px
    sources: filesystem itunes amazon albumart covertart

embedart:
    auto: no
```
