### ISSUE TITLE
Inline Plugin Returns Empty Genre

### ISSUE THREAD

**Issue by AzureWolf** [beetbox/beets#3841]
I'm trying to modify the organization of my music on a conditional basis. For example, I want the Anime genre to follow one folder format, and movie soundtracks to follow another. Then everything else will be by artist.

That's obviously not what I've setup yet, but that's the plan (based on the genre and the lastgenre feature). I am just testing out the inline plugin and the genre comes back blank. This is confirmed by both the if else statement and the print statement (which just prints a blank line). I have tried disabling both zero and lastgenre and get the same result. The end result is "Test Folder" with the rest sorting correctly. Genre of the imported songs are blank as well when they previously were not. And seems like genre gets wiped for everything that is imported now even after disabling the inline plugin. I don't know what changed...

I am not a programmer whatsoever, so this is more likely a misunderstanding on my part, but it _could_ be a bug?

Thank you in advance

### Setup

* OS: macOS Big Sur 11.1
* Python version: 3.8.2
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

```yaml
plugins: chroma fromfilename fetchart embedart lyrics lastgenre zero discogs mbsync inline #plexupdate

paths:
    default: $initial/%title{$albumartist}/[$year] $album%aunique{}/$track - $title

album_fields:
    initial: |
        if genre:
            return genre
        else:
            print(genre)
            return "Test Folder"
```

Here's a link to the music files that trigger the bug (if relevant):

All, but here are two for a reference:

https://www.discogs.com/Raujika-Fairy-Tale/master/299845
https://www.discogs.com/David-Nevue-Awakenings-The-Best-Of-David-Nevue-2001-2010/release/7917310
