### ISSUE TITLE
Create and update playlists

### ISSUE THREAD

**Issue by catap** [beetbox/beets#3847]
### Use case

Let assume that someone has some music library as series of files, and would like to manage also playlist for it.

I feel that it is expected that beets should have a way to create and update playlists per artist, albums, year, etc.

Right now playlist plugin can update paths to actual songs, but not created it.

### Solution

Update playlist plugin to support config like:
```
playlist:
  auto: yes
  relative_to: https://nas.domain.com/music/
  playlist_dir: ~/Music/playlists
  relative_url_encoded: yes
  dynamic_playlists: yes
```

This config creates a dynamic playlists in `~/Music/playlists` for each album, artist, year, genre, etc.

All paths to inside playlists are urlencoded and have form `https://nas.domain.com/music/[urldencoded path]` that allows to use this playlist almost everywhere with NAS that supports webdav/http access to your files.

### Alternatives

A lot of manual job. A lot.
