### ISSUE TITLE
asciify_paths ignores unicode character modifiers

### ISSUE THREAD

**Issue by catap** [beetbox/beets#3850]
### Problem

Let assume that I enable `asciify_paths`. And try to import an album which contains character modifier in name. For example [Ayọ ~ Release by Ayọ](https://musicbrainz.org/release/216b67c9-6f47-4f01-8a74-caff86bb3af3).

It is saved to disk as `Ayọ/Ayọ` and not `Ayo/Ayo` as expected.

### Setup

* OS: macOS 11.1
* Python version: Python 3.8.7 (default, Dec 24 2020, 19:07:18) 
* beets version: 04ea754d00e2873ae9aa2d9e07c5cefd790eaee2
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    sources: musixmatch google
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    bing_client_secret: REDACTED
    bing_lang_to:
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
directory: /Volumes/music

import:
    move: yes
    write: yes
    copy: yes
    resume: ask
    hardlink: no
    link: no
    asciify_paths: yes
    timid: no
follow:
    auto: yes
    email: REDACTED
    password: REDACTED
    userid: REDACTED

musicbrainz:
    user: catap
    pass: REDACTED
mbcollection:
    auto: yes
    remove: yes
    collection: 04540b29-ba5e-4e0e-82e8-161035854aa4

plugins: fetchart lyrics lastgenre missing embedart mbcollection mbsubmit mbsync duplicates fuzzy info follow smartplaylist
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
fuzzy:
    prefix: '~'
    threshold: 0.7
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
missing:
    count: no
    total: no
    album: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
mbsubmit:
    format: $track. $title - $artist ($length)
    threshold: medium
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
```
