### ISSUE TITLE
Option order matters with duplicates plugin 

### ISSUE THREAD

**Issue by spencermathews** [beetbox/beets#3857]
### Problem

When using the `-a`, `-p`, and `-F` options to the duplicates plugin simultaneously (and combined) the output varies depending on the ordering.

Running this command (and various other permutations):

```sh
$ beet duplicates -apF
```

Led to this problem:

```
NO OUTPUT
```

Combining the arguments in various other orderings work fine, for example:

```
$ beet duplicates -Fap
$ beet duplicates -a -p -F
```

Note that the output was also as expected when listing the options individually. This seems to be a bug in argument parsing.

### Setup

* OS: macOS 10.15.7
* Python version: 3.8.5
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): N/A

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/Beets

import:
    copy: no
    write: no

plugins: badfiles duplicates info missing
missing:
    count: no
    total: no
    album: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
```
