### ISSUE TITLE
setting genre in keep_fields: config of zero plugin isn't respected

### ISSUE THREAD

**Issue by Phil305** [beetbox/beets#3858]
### Problem
The **zero** plugin seems to have the *genre* field named incorrectly;
If **genre** is set in **zero.keep_fields** config section, genres are still deleted.
But if **genre** *AND* **genres** (with an **s**) are **both**, the genre field isn't removed

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv zero
```

Led to this problem:

```
Sending event: write
zero: genres: None -> None
```

### Setup

* OS: Fedora 33 (Workstation Edition)
* Python version: Python 3.9.1
* beets version: beets version 1.4.9

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/main
library: ~/Music/library.db
id3v23: yes

plugins: edit smartplaylist missing lastgenre bpm embedart fetchart zero acousticbrainz replaygain fromfilename play ftintitle chroma

import:
    timid: yes
    incremental: yes
    original_date: yes
chroma:
    auto: yes
ftintitle:
    format: (feat. {0})
    auto: yes
    drop: no
replaygain:
    backend: gstreamer
    overwrite: no
    auto: yes
    targetlevel: 89
    r128: [Opus]
edit:
    itemfields: album albumartist albumartist_credit albumartist_sort artist bpm comments comp composer disc disctitle disctotal genre grouping lyricist month original_day original_month original_year title track tracktotal year
    albumfields: album albumartist
    ignore_fields: id path
zero:
    keep_fields: acoustid_fingerprint acoustid_id added album album_id albumartist albumartist_credit albumartist_sort albumdisambig arranger artist artist_credit artist_sort asin bitdepth bitrate bpm catalognum channels comments comp composer composer_sort country day disc disctitle disctotal genre genres grouping id initial_key label length lyricist mb_albumartistid mb_albumid mb_artistid mb_releasegroupid mb_releasetrackid mb_trackid month mtime original_day original_month original_year path r128_album_gain r128_track_gain releasegroupdisambig rg_album_gain rg_album_peak rg_track_gain rg_track_peak samplerate script singleton title track tracktotal year
    comment: [^Track.*]
    auto: yes
    fields: []
    update_database: no
lastgenre:
    whitelist: /home/phoenix/Music/lastgenre_whitelist
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
embedart:
    auto: no
    ifempty: yes
    maxwidth: 0
    compare_threshold: 0
    remove_art_file: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
bpm:
    max_strokes: 3
    overwrite: yes
play:
    command:
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
    bom: no
acousticbrainz:
    auto: yes
    force: no
    tags: []
smartplaylist:
    relative_to:
    playlist_dir: .
    auto: yes
    playlists: []
missing:
    count: no
    total: no
    album: no
```
