### ISSUE TITLE
incremental_skip_later either documentation or implementation backwards

### ISSUE THREAD

**Issue by HackBug** [beetbox/beets#3860]
### Problem

According to [this page of documentation](https://github.com/beetbox/beets/blob/2b8a2eb96bcaf418cdfcc0cfe762a18e31cff138/docs/reference/config.rst#incremental_skip_later), setting the ``incremental_skip_later`` configuration option to "yes" should tell the importer to record skipped directories and not try to import them later. 

However, in practice, setting the option to "yes" causes beets to attempt to import skipped directories every time, and setting the option to "no" causes the importer to skip previously skipped directories. 

Line 596 of importer.py seems relevant here. It appears beets checks affirmatively if the directory should be recorded or not, but uses a "true" statement to mean that it should skip recording.

### Setup

* OS: Arch Linux 5.10.17-hardened1-1-hardened
* Python version: 3.9.1 
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
#Global
library: [omitted]
directory: [omitted]
threaded: yes
art_filename: cover
format_item: $year $album - $artist - $disc.$track $title
format_album: $albumartist - $album - $year
aunique:
  keys: albumartist album
  disambiguators: albumtype year label catalognum albumdisambig releasegroupdisambig
  bracket: '[]'
per_disc_numbering: no
paths:
  default: $albumartist/$year - $album%aunique{}/$disc.$track $title
  comp: Various Artists/$year - $artist$ - $album%aunique{}/$disc.$track $title
va_name: 'Various Artists'
sort_item: albumartist+ album+ disc+ track+
plugins: fetchart lyrics lastgenre edit random mbsubmit duplicates mbcollection scrub badfiles missing smartplaylist mbsync acousticbrainz absubmit duplicates thumbnails replaygain embedart permissions #discogs
#UI
ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue
#Import
import: 
  move: no
  copy: yes
  write: yes
  log: [omitted]
  incremental: yes
  incremental_skip_later: no
  quiet_fallback: asis
#  duplicate_action: skip
# ... remaining lines omitted (irrelevant plugin configuration)
```
