### ISSUE TITLE
Convert to same folder > Remove original > Import

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [beetbox/beets#3864]
### Use case

I'm trying to use beets to automatically convert all imported files to .mp3 and erase the original files.

### Solution

Using the convert plugin. I don't know what to put in as `dest:` in order to convert to the same folder, delete the original files, and then import them to my main `directory:`. 

Here are the relevant parts of my config.yaml file:

```
directory: /Volumes/Media/Media/Audio
import:
    copy: no
    write: yes
    move: yes
plugins: convert
convert:
    format: mp3
    formats:
    mp3:
      command: ffmpeg -i $source -q:a 0 -map_metadata 0 $dest
      extension: mp3
```
