### ISSUE TITLE
Add discogs as a source for fetchart

### ISSUE THREAD

**Issue by jordanbs** [beetbox/beets#3881]
### Use case

I'm trying to use beets to fetch album art. Many of my albums have album art on discogs, but fetchart struggles to find album art with all the default sources enabled.

Example: Hiroshi Yoshimura - Soundscape 1 - Surround
```
% beet info Hiroshi Yoshimura                          
/home/pi/ponybank/beets/Hiroshi Yoshimura/Soundscape 1 - Surround/01 Time After Time.m4a
acoustid_fingerprint: 
         acoustid_id: 
               album: Soundscape 1 - Surround
         albumartist: Hiroshi Yoshimura
  albumartist_credit: 
    albumartist_sort: 
       albumdisambig: 
         albumstatus: 
           albumtype: Album
            arranger: 
                 art: False
              artist: Hiroshi Yoshimura
       artist_credit: 
         artist_sort: 
                asin: 
            bitdepth: 16
             bitrate: 256000
                 bpm: 0
          catalognum: C32SD-1
            channels: 2
            comments: 
                comp: False
            composer: 
       composer_sort: 
             country: Japan
                date: 1986-01-01
                disc: 1
           disctitle: 
           disctotal: 1
             encoder: iTunes 12.5.5.5
              format: AAC
               genre: Ambient
              genres: Ambient
            grouping: Japan
               label: Misawa Home
            language: 
              length: 663.5102040816327
            lyricist: 
              lyrics: 
    mb_albumartistid: 691250
          mb_albumid: 4932073
         mb_artistid: 691250
   mb_releasegroupid: 599755
   mb_releasetrackid: 
          mb_trackid: 4932073-1
               media: CD
       original_date: 1986-01-01
       original_year: 1986
     r128_album_gain: 0
     r128_track_gain: 0
       rg_track_gain: 7.06
       rg_track_peak: 0.649536
          samplerate: 44100
              script: 
               title: Time After Time
               track: 1
          tracktotal: 6
                year: 1986

% beet fetchart Hiroshi Yoshimura
fetchart: Hiroshi Yoshimura - Soundscape 1 - Surround: no art found
```

### Solution
The art exists on discogs. Discogs integration is amazing for the autotagger! Perhaps it could work for fetchart too?

### Alternatives
Finding manually and using embedart works just fine.
