### ISSUE TITLE
Alt. Rock Alternative Rock Alternative-Rock are not the same folder

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#389]
I'm using the lastgenre plugin. This seems to have a bug
I have genres Alt. Rock, Alternative Rock and  Alternative-Rock
Isn't this all the same?

```
  # Automatically migrated from legacy .beetsconfig.                              

  directory: /tank/music                                                          
  library: ~/data/musiclibrary.blb                                                
  path_format: $genre/$artist/$album/$track $title                                

  paths:                                                                          
      default: $genre/$albumartist/$album/$track $title                           
      singleton: Singletons/$artist - $title                                      
      comp: $genre/$album/$track $title                                           
      albumtype:soundtrack: Soundtracks/$album/$track $title                      

  import:                                                                         
      move: true                                                                  
      copy: false                                                                 
  plugins:                                                                        
      fetchart                                                                    
      lastgenre                                                                   
      missing                                                                     

  acoustid:                                                                       
      apikey: foobar                                                            

  fetchart:                                                                       
      auto: true                                                                  

  lastgenre:                                                                      
      force: true                                                                 
      canonical: '' 
```
