### ISSUE TITLE
Files without extension cannot have one added

### ISSUE THREAD

**Issue by egon010** [beetbox/beets#3912]
### Problem

I imported a bunch of music in files without extensions. They import, and the files are renamed, but none of them have an extension, which makes them unacceptable for playing in some players.

Adding the `$format` symbol to the `path:` configurations don't work properly, and no extension is added when all the files are targeted with the `move` command.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv mv -p "Multi Muysic"
user configuration: /home/egon/.config/beets/config.yaml
data directory: /home/egon/.config/beets
plugin paths:
Sending event: pluginload
library database: /home/egon/.config/beets/library.db
library directory: /music/beets
Sending event: library_opened
Moving 0 items (8 already in place).
Sending event: cli_exit
```

Led to this problem:

```
Moving 0 items (8 already in place).
```

Here's a link to the music files that trigger the bug (if relevant):

The filenames are the problem, not the content of the filenames
```
beet ls "Multi Muysic" --path
/music/beets/A-D/Aavikko/Multi Muysic/01 Synchro Start
/music/beets/A-D/Aavikko/Multi Muysic/02 New York–London–Siilinjärvi–Tokyo
/music/beets/A-D/Aavikko/Multi Muysic/03 Sports Criminal
/music/beets/A-D/Aavikko/Multi Muysic/04 Seoul ’88
/music/beets/A-D/Aavikko/Multi Muysic/05 Omavastuualue
/music/beets/A-D/Aavikko/Multi Muysic/06 Slalom Tripmaster
/music/beets/A-D/Aavikko/Multi Muysic/07 Bermuda 3
/music/beets/A-D/Aavikko/Multi Muysic/12 Torpedo Girls
```

### Setup

* OS: Linux nuc 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Python version: 2.7.12
* beets version: 1.4.9, 1.5.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: fromfilename duplicates chroma missing bucket badfiles mbsync embedart fetchart discogs
duplicates:
    tiebreak:
        items: [bitrate]
    copy: ''
    tag: ''
    checksum: ''
    format: ''
    merge: no
    count: no
    full: no
    album: no
    path: no
    strict: no
    keys: []
    delete: no
    move: ''
incremental: yes
bucket:
    bucket_alpha:
    - 0-9
    - A-D
    - E-L
    - M-R
    - S-Z
    - Unicode
    bucket_alpha_regex:
        0-9: "^[0-9\xD8]"
        A-D: "^[a-dA-D\xC6\u0391\u0410\xC1\xC2\u0100\u0386\u0412\u010C\u0421\u0414]"
        E-L: "^[e-lE-L\xC9\u039A\u0399\u041D]"
        M-R: "^[m-rM-R\u041C\xD3\u03A1\u0418\u039C\u03A0\u041F\u0393\u03BC]"
        S-Z: "^[s-zS-Z\u0160\xDC\u03A3\u0531]"
        Unicode: "^[\u30AB\uB0A8\u4E45\u51A8\u5742\u5C0F\u5E73\u6731\u677E\u6C34\u6D5C\u7802\u83C5\u9577\u12A0\u304B\u30B7\u054B\u4EF2\u524D\u584A\u5DBA\u6238\u6751\u68B6\u6C60\u6DF1\u7D30\u9060\u98A8\u306F\u30C1\u30B8\u4E09\u4F0A\u5411\u5883\u5E03\u65B0\u6771\u691B\u6D45\u7530\u82B1\u9234\u9F13\u3086\u305F\u0639\u0645\u0646\u05D0\u05D6\u5409\u690D\u77E2\u042E]"
    extrapolate: no
    bucket_year: []
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
    tokenfile: discogs_token.json
directory: /music/beets

paths:
    default: '%bucket{$albumartist}/${albumartist}/${album}%aunique{}/$track ${title}.%lower{$format}'
    singleton: Non-Album/$artist/${title}.%lower{$format}
    comp: Compilations/$album%aunique{}/$track ${title}.%lower{$format}

import:
    move: no

replace:
    '[\\/]': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \s+$: ''
    ^\s+: ''
    ^-: _
max_filename_length: 0
embedart:
    remove_art_file: no
    maxwidth: 0
    ifempty: no
    auto: yes
    compare_threshold: 0
fetchart:
    fanarttv_key: REDACTED
    cautious: no
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    minwidth: 0
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_engine: 001442825323518660753:hrh5ch1gjzm
    store_source: no
    google_key: REDACTED
    auto: yes
    maxwidth: 0
    enforce_ratio: no
missing:
    count: no
    total: no
    album: no
chroma:
    auto: yes

```
