### ISSUE TITLE
fetchart doesn't work

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [beetbox/beets#3950]
### Problem

I erased all my cover.* files to begin again with fetchart. Last night, I ran `beet fetchart` and had most albums with art found and downloaded. It stopped with an error at an artist that I had moved away from the library without telling beets.

This morning, I sorted out that issue, and then ran `beet fetchart`, only now (when it goes past that artist) nothing is found.
 
`beet -vv fetchart`:

```
fetchart: trying source fanarttv for album Elvis Costello & The Attractions - Get Happy!!
fetchart: trying source itunes for album Elvis Costello & The Attractions - Get Happy!!
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+Get+Happy%21%21&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+Get+Happy%21%21&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Costello & The Attractions - Get Happy!!
fetchart: trying source coverart for album Elvis Costello & The Attractions - Get Happy!!
fetchart: trying source coverart for album Elvis Costello & The Attractions - Get Happy!!
fetchart: trying source albumart for album Elvis Costello & The Attractions - Get Happy!!
fetchart: Elvis Costello & The Attractions - Get Happy!!: no art found
fetchart: trying source fanarttv for album Elvis Costello & The Attractions - Imperial Bedroom
fetchart: trying source itunes for album Elvis Costello & The Attractions - Imperial Bedroom
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+Imperial+Bedroom&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+Imperial+Bedroom&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Costello & The Attractions - Imperial Bedroom
fetchart: trying source coverart for album Elvis Costello & The Attractions - Imperial Bedroom
fetchart: trying source coverart for album Elvis Costello & The Attractions - Imperial Bedroom
fetchart: trying source albumart for album Elvis Costello & The Attractions - Imperial Bedroom
fetchart: Elvis Costello & The Attractions - Imperial Bedroom: no art found
fetchart: trying source fanarttv for album Elvis Costello & The Attractions - King of America
fetchart: trying source itunes for album Elvis Costello & The Attractions - King of America
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+King+of+America&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+King+of+America&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Costello & The Attractions - King of America
fetchart: trying source coverart for album Elvis Costello & The Attractions - King of America
fetchart: trying source coverart for album Elvis Costello & The Attractions - King of America
fetchart: trying source albumart for album Elvis Costello & The Attractions - King of America
fetchart: Elvis Costello & The Attractions - King of America: no art found
fetchart: trying source fanarttv for album Elvis Costello & The Attractions - Punch the Clock
fetchart: trying source itunes for album Elvis Costello & The Attractions - Punch the Clock
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+Punch+the+Clock&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+Punch+the+Clock&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Costello & The Attractions - Punch the Clock
fetchart: trying source coverart for album Elvis Costello & The Attractions - Punch the Clock
fetchart: trying source coverart for album Elvis Costello & The Attractions - Punch the Clock
fetchart: trying source albumart for album Elvis Costello & The Attractions - Punch the Clock
fetchart: Elvis Costello & The Attractions - Punch the Clock: no art found
fetchart: trying source fanarttv for album Elvis Costello & The Attractions - Trust
fetchart: trying source itunes for album Elvis Costello & The Attractions - Trust
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+Trust&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Costello+%26+The+Attractions+Trust&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Costello & The Attractions - Trust
fetchart: trying source coverart for album Elvis Costello & The Attractions - Trust
fetchart: trying source coverart for album Elvis Costello & The Attractions - Trust
fetchart: trying source albumart for album Elvis Costello & The Attractions - Trust
fetchart: Elvis Costello & The Attractions - Trust: no art found
fetchart: trying source fanarttv for album Elvis Costello with Burt Bacharach - Painted From Memory
fetchart: trying source itunes for album Elvis Costello with Burt Bacharach - Painted From Memory
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Costello+with+Burt+Bacharach+Painted+From+Memory&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Costello+with+Burt+Bacharach+Painted+From+Memory&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Costello with Burt Bacharach - Painted From Memory
fetchart: trying source coverart for album Elvis Costello with Burt Bacharach - Painted From Memory
fetchart: trying source coverart for album Elvis Costello with Burt Bacharach - Painted From Memory
fetchart: trying source albumart for album Elvis Costello with Burt Bacharach - Painted From Memory
fetchart: Elvis Costello with Burt Bacharach - Painted From Memory: no art found
fetchart: trying source fanarttv for album Elvis Crespo - Suavemente
fetchart: trying source itunes for album Elvis Crespo - Suavemente
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Crespo+Suavemente&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Crespo+Suavemente&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Crespo - Suavemente
fetchart: trying source coverart for album Elvis Crespo - Suavemente
fetchart: trying source coverart for album Elvis Crespo - Suavemente
fetchart: trying source albumart for album Elvis Crespo - Suavemente
fetchart: Elvis Crespo - Suavemente: no art found
fetchart: trying source fanarttv for album Elvis Perkins in Dearland - Elvis Perkins in Dearland
fetchart: trying source itunes for album Elvis Perkins in Dearland - Elvis Perkins in Dearland
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Perkins+in+Dearland+Elvis+Perkins+in+Dearland&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Perkins+in+Dearland+Elvis+Perkins+in+Dearland&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Perkins in Dearland - Elvis Perkins in Dearland
fetchart: trying source coverart for album Elvis Perkins in Dearland - Elvis Perkins in Dearland
fetchart: trying source coverart for album Elvis Perkins in Dearland - Elvis Perkins in Dearland
fetchart: trying source albumart for album Elvis Perkins in Dearland - Elvis Perkins in Dearland
fetchart: Elvis Perkins in Dearland - Elvis Perkins in Dearland: no art found
fetchart: trying source fanarttv for album Elvis Presley - ELV1S 30 #1 Hits
fetchart: trying source itunes for album Elvis Presley - ELV1S 30 #1 Hits
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Presley+ELV1S+30+%231+Hits&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Presley+ELV1S+30+%231+Hits&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Presley - ELV1S 30 #1 Hits
fetchart: trying source coverart for album Elvis Presley - ELV1S 30 #1 Hits
fetchart: trying source coverart for album Elvis Presley - ELV1S 30 #1 Hits
fetchart: trying source albumart for album Elvis Presley - ELV1S 30 #1 Hits
fetchart: Elvis Presley - ELV1S 30 #1 Hits: no art found
fetchart: trying source fanarttv for album Elvis Presley - Elvis
fetchart: trying source itunes for album Elvis Presley - Elvis
fetchart: getting URL: https://itunes.apple.com/search?term=Elvis+Presley+Elvis&entity=album&media=music&limit=200
fetchart: iTunes search failed: 403 Client Error: Forbidden for url: https://itunes.apple.com/search?term=Elvis+Presley+Elvis&entity=album&media=music&limit=200
fetchart: trying source amazon for album Elvis Presley - Elvis
fetchart: trying source coverart for album Elvis Presley - Elvis
fetchart: trying source coverart for album Elvis Presley - Elvis
fetchart: trying source albumart for album Elvis Presley - Elvis
fetchart: Elvis Presley - Elvis: no art found
```

etc.

### Setup

* OS: macOS High Sierra
* Python version: 2.7.16
* beets version: 1.4.9

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/Music/
plugins: missing lyrics fetchart duplicates zero discogs badfiles convert embedart
autotag: yes
art_filename: cover
clutter: .pdf .bmp .png .jpg .jpef .tif .gif .sfv .nfo .m3u .log .DS_Store Thumbs.DB Thumbs.db
original_date: yes
languages: en
va_name: Various
ignored_media: .vob .mp4 .mkv .avi .ts .pdf .cbz .cbr
import:
    copy: no
    write: yes
    move: yes
paths:
    default: $albumartist/$album%aunique{albumartist album, tracktotal albumtype year label,()}/$track. $title
    comp: Various/$album%aunique{albumartist album, tracktotal albumtype year label,()}/$track. $title
    albumartist:various artists: Various/$album%aunique{albumartist album, tracktotal albumtype year label,()}/$track. $title
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
convert:
    tmpdir: /Volumes/Music/
    auto: yes
    format: mp3
    mp3:
      command: ffmpeg -i $source -q:a 0 -map_metadata 0 $dest
      extension: mp3
discogs:
    user_token: redacted
duplicates:
    album: yes
    move: /Users/redacted/Downloads/
fetchart:
    auto: yes
    sources: fanarttv itunes amazon coverart albumart
    fanarttv_key: redacted
embedart: 
    maxwidth: 1000
lyrics:
    auto: no
    force: yes
    sources: genius musixmatch lyricwiki google
    google_API_key: redacted
    fallback: ''
    import.write: yes
replaygain:
    auto: no
    backend: command
chroma:
    auto: no
zero:
    auto: yes
    keep_fields:
        - acoustid_fingerprint
        - acoustid_id
        - albumtype
        - artist
        - title
        - album
        - year
        - composer
        - albumartist
        - track
        - tracktotal
        - disc
        - disctotal
        - first played
        - last played
        - label
        - lyrics
        - play count
        - rating
        - images
```
