### ISSUE TITLE
Old MP3's tagged with RealJukebox show as unreadable.

### ISSUE THREAD

**Issue by mattheys** [beetbox/beets#3983]
### Problem

I have a lot of mp3's from the early 2000's and it looks like I tagged them with RealJukebox at some point. Beets seems to not be able to read these files, they have this (slightly altered due to non ascii characters) file header `ID3 GEOB  binary  RealJukebox:Metadata RJEX` and running the files through FFProbe gives messages like `Skipping 65535 bytes of junk at 0`. 

I've never had an issue with playing these files or using them in any other media player before. I did find an old thread from MythTv discussing what looks to be the same thing. http://lists.mythtv.org/pipermail/mythtv-users/2003-July/010789.html

I can also confirm that deleting the first 65535 bytes from the begining of the file fixes the issue, although I don't know if all files will be exactly 0xFFFF though.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import /downloads/Next/Wifey/
```

Led to this problem:

```
user configuration: /config/config.yaml
data directory: /config
plugin paths:
Sending event: pluginload
library database: /config/musiclibrary.blb
library directory: /music
Sending event: library_opened
Sending event: import_begin
unreadable file: /downloads/Next/Wifey/Next - Wifey (DYNK 4 Dub).mp3
unreadable file: /downloads/Next/Wifey/Next - Wifey (DYNK Vocal Mix).mp3
unreadable file: /downloads/Next/Wifey/Next - Wifey (Instrumental).mp3
unreadable file: /downloads/Next/Wifey/Next - Wifey (Radio Mix).mp3
unreadable file: /downloads/Next/Wifey/Next - Wifey.mp3
No files imported from /downloads/Next/Wifey
Sending event: import
Sending event: cli_exit

```

Here's a link to the music files that trigger the bug (if relevant): I can DM anyone a link who needs to investigate.

### Setup

* OS: Ubuntu (Linuxserver.io version:- eef26d18-ls66 Build-date:- 2021-05-14T09:02:06+00:00)
* Python version: 3.8.10
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no
chroma:
    auto: yes
convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    dest:
    pretend: no
    link: no
    hardlink: no
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
    delete_originals: no

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
    log: /config/beet.log
lastgenre:
    auto: yes
    source: album
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    force: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
embedart:
    auto: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
replaygain:
    auto: no
    overwrite: no
    backend: command
    threads: 8
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
    command: ''
    noclip: yes
scrub:
    auto: yes

replace:
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    \.$: _
    \s+$: ''
web:
    host: 0.0.0.0
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    readonly: yes
```
