### ISSUE TITLE
Convert: destination file name is erroneously "mp3.mp3"

### ISSUE THREAD

**Issue by Weker01** [beetbox/beets#3988]
### Problem

After running ```beet convert``` I noticed that there was a file called mp3.mp3 in my output folder.

After investigating the file it turned out to be "FORMAT.EXE" from the Album "C:\>CHKDSK /F" of the Artist "MASTER BOOT RECORD".
I first suspected the dot in "FORMAT.EXE" but alas in the same album there are many files with dots in them like "MSDOS.SYS". 

The error also occures with ```beet convert -p FORMAT.EXE``` resulting in
```
convert: ffmpeg -i /media/musicLib/MASTER BOOT RECORD/C___CHKDSK _F/07 FORMAT.EXE.flac -c:a libmp3lame -q:a 2 /media/convMp3/mp3.mp3
```

I reimported the album but this did not change the behavior.

I am not familiar with beets source but after a short investigation I saw that the error occured rather early in convert.py the variable ```dest``` is set by ```item.destination()``` to "mp3" at line 272 which is obviously wrong.

I must confess that I gave up following ```item.destination()``` as I am not familiar with the source.

This is all very strange and intriguing as I do not see any significant differences between this file and any other from the same album.

### Setup

* OS: ArchLinux
* Python version: 3.9.5
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): yes (the problem is a plugin...)

My configuration (output of `beet config`) is:

```yaml
directory: /media/musicLib
library: /media/musiclibrary.blb
asciify_paths: yes

import:
    copy: yes

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    albumtype:"game soundtrack": Soundtracks/$albumartist/$album%aunique{}/$track $title
    comp: Compilations/$album%aunique{}/$track $title

plugins: fetchart mbsync convert scrub
fetchart:
    sources: itunes *
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
convert:
    dest: /media/convMp3
    no_convert: format:mp3

    paths:
        default: $albumartist/$album%aunique{}/$track $title
        singleton: Non-Album/$title
        albumtype:"game soundtrack": Soundtracks/$album%aunique{}/$track $title
        comp: Compilations/$album%aunique{}/$track $title
        format: mp3
    formats:
        mp3:
            command: ffmpeg -i $source -c:a libmp3lame -q:a 2 $dest
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    pretend: no
    link: no
    hardlink: no
    threads: 32
    format: mp3
    id3v23: inherit
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    embed: yes
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
    delete_originals: no
scrub:
    auto: yes
```

**Comment by wisp3rwind** [comment]
There's a spurious line in your path format configuration, which happens to match this track:

```yaml

convert:
    paths:
        format: mp3
```

Probably, that line is supposed to be indented one level less?
