### ISSUE TITLE
smartplaylist: segfault with empty query

### ISSUE THREAD

**Issue by trapd00r** [beetbox/beets#4011]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$beet -vvv splupdate
```

when using an empty query to add all songs to a playlist led to this problem:

```
smartplaylist: Creating playlist +by plays/1 or more.m3u
smartplaylist: Creating playlist +by plays/loved.m3u
smartplaylist: Creating playlist +by time/last 60 days.m3u
smartplaylist: Creating playlist +all.m3u
[2]    831205 segmentation fault (core dumped)  ~/dev/beets/beet -vvv splupdate

[286944.007854] python[831205]: segfault at 7f7122be0728 ip 00007f712288129c sp 00007ffd4da65ed0 error 4 in libpython3.9.so.1.0[7f7122797000+21a000]
[286944.007863] Code: 4c 63 ea 48 8b 55 10 49 89 fc 83 c1 01 89 4d 20 3b 4a 40 0f 8f 2c 03 00 00 4c 8b 56 08 4c 8b 4f 08 4d 39 d1 0f 85 44 03 00 00 <49> 8b 81 c8 00 00 00 48 85 c0 0f 84 40 02 00 00 45 31 f6 48 8d 35


```

```
$ beet stats
Tracks: 236252
Total time: 1.8 years
Approximate total size: 2.7 TiB
Artists: 24014
Albums: 19610
Album artists: 8135
```

### Setup

* OS: Linux sid 5.9.16-1
* Python version: 3.9.4
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/music8/+TAGGED
library: ~/var/beets/beets202105.db
pluginpath: [/usr/lib/python3.9/site-packages/beetsplug/, /home/scp1/dev/beets-titlecase_proper, /home/scp1/etc/beets/plugins]

clutter:
- Thumbs.DB
- .DS_Store
- '*.m3u'
- '*.pls'
- '*.jpg'
- '*.nfo'
- '*.txt'
- '*.log'
- '*.gif'

replace:
    '[\\]': ''
    '[_]': '-'
    '[/]': '-'
    ^\.: ''
    '[\x00-\x1f]': ''
    '[<>:"\?\*\|]': ''
    \.$: ''
    \s+$: ''
    ^\s+: ''
    ^-: ''
    "\u2019": ''''
    "\u2032": ''''
    "\u2033": ''
art_filename: cover
format_album: $path

format_item: $path
ignore: [.*, '*~', System Volume Information]
ignore_hidden: yes
per_disc_numbering: no

sort_album: path+
sort_item: path+
sort_case_insensitive: yes
threaded: yes
timeout: 5.0
verbose: no
va_name: Various Artists

import:
    languages: en
    default_action: apply
    duplicate_action: keep
    non_rec_action: ask
    autotag: yes
    write: yes
    copy: no
    link: no
    move: yes
    quiet_fallback: skip
    incremental: yes

plugins:
- bucket
- discogs
- edit
- fetchart
- fromfilename
- ftintitle
- hook
- info
- inline
- lastgenre
- lastimport
- rewrite
- smartplaylist
- titlecase_proper
titlecase_proper:
    asis:
    - EP
    - LP
    - PhD
    - DJ
    - TCP
discogs:
    source_weight: 0.0
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    user_token: REDACTED
    separator: ', '
    index_tracks: no
bucket:
    bucket_alpha:
    - '#-!'
    - 0-9
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z
    bucket_alpha_regex:
        '#-!': "^[^0-9a-zA-Z\xE5\xC5\xE4\xC4\xF6\xD6]"
    bucket_year: []
    extrapolate: no
edit:
    itemfields: track title artist album year
    albumfields: track title artist albumartist album year
    ignore_fields: id path
embedart:
    auto: yes
fetchart:
    auto: yes
    minwidth: 500
    maxwidth: 1200
    sources: coverart itunes amazon albumart wikipedia google
    quality: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
hook:
    hooks: [{event: album_imported, command: "hr -c '\u2508' -fg 30 -s 72"}, {event: item_moved, command: 'ls_color_beets  "{destination}"'}, {event: before_choose_candidate, command: "hr -c '\u2508' -fg 30 -s 72"}]
lastfm:
    user: betbot
    api_key: REDACTED
lastgenre:
    auto: yes
    canonical: yes
    force: no
    source: artist
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    separator: ', '
    prefer_specific: no
    title_case: yes
lyrics:
    auto: yes
mpd:
    host: localhost
    port: 6600

musicbrainz:
    extra_tags:
    - year
    - originalyear
    - catalognum
    - country
    - media
    - label
rewrite:
    album .*Sommar i P1: P1 Sommar
    album .*Sommar (och|[&]) Vinter i P1.*: P1 Sommar
    "album S\xF6ndagsintervjun": "P1 S\xF6ndagsintervjun"
    album .*Musikguiden i p3: P3 Musikguiden
    album Jukeboxen i p4: P4 Jukeboxen
    album Musikspecial i p4: P4 Musikspecial
    artist Melanie B[.]?: Melanie Brown
    artist Far & Son: Far och Son
    artist Smith & Tell: Smith and Tell
    artist MBMA: Mobbade Barn med Automatvapen
    artist DPZ: Dead Prez
    artist Snoop Dogg.*: Snoop Dogg
    artist Pst.q: Pst-q
    artist 10,000 Maniacs: 10000 Maniacs
    artist Fronda.*: Fronda
    artist Magnus Rytterstam.*: Magnus Rytterstam
    "artist \u6C5F\u6D77\u8FE6": Aga
    artist Whoo Kid: DJ Whoo Kid
    artist Looptroop.*: Looptroop
    artist T[.]R: "\xD6ris"
    artist Smuts & Co: Organism 12
    artist Organismen: Organism 12
    artist Retarderat Eleverade: Organism 12
    "artist Ungdumsh\xE4lsan": Organism 12
    artist Gms.*: GMS
    artist (tupac|2[pP]ac).*: 2pac
    artist .*weird Al.*: Weird Al Yankovic
    artist .*Green Lantern.*: DJ Green Lantern
    artist .ingenting.: Ingenting
    "artist Sin[e\xE9]ad O.Connor.*": "Sin\xE9ad O'Connor"
    artist .*Suzanne.*Vega: Suzanne Vega
    artist .*1[23]00 mic.*: 1200 Micrograms
    artist elin (ruth)? sigvardsson: Elin Sigvardsson
    artist elin ruth: Elin Sigvardsson
    artist ^Game$: The Game
    artist ^Ken$: Ken Ring
    artist Special D: Special D.
    artist Danne W.*: "Sj\xE4tte Sinnet"
    artist Sjatte Sinnet: "Sj\xE4tte Sinnet"
    artist Ante Barazza: "Sj\xE4tte Sinnet"
setlister:
    playlist_dir: ~/mp3/_playlists/+setlists/
smartplaylist:
    auto: no
    playlist_dir: ~/mp3/_playlists/
    playlists:
    -   name: +all.m3u
        query: ''
    -   name: +by artist/eminem.m3u
        query: artist:Eminem
    -   name: +by artist/bob dylan.m3u
        query: artist:Bob Dylan
    -   name: +by concept/diss tracks.m3u
        query: title:" diss"
    -   name: +by year/$year.m3u
        query: year::(199[0-9]|200[0-9]|201[0-9]|202[0-9])
    -   name: +by plays/1 or more.m3u
        query: play_count:1..
    -   name: +by plays/5 or more.m3u
        query: play_count:5..
    -   name: +by plays/loved.m3u
        query: loved:1
    -   name: +by time/last day.m3u
        query: added- added:-1d..
    -   name: +by time/last 3 days.m3u
        query: added- added:-3d..
    -   name: +by time/last 7 days.m3u
        query: added- added:-7d..
    -   name: +by time/last 14 days.m3u
        query: added- added:-14d..
    -   name: +by time/last 30 days.m3u
        query: added- added:-30d..
    -   name: +by time/last 45 days.m3u
        query: added- added:-45d..
    -   name: +by time/last 60 days.m3u
        query: added- added:-60d..
    -   name: +by genre/psychedelic.m3u
        query: genre:psychedelic
    relative_to:
    forward_slash: no

aunique:
    disambuguators: mastering label catalognum albumdisambig releasegroupdisambig

match:
    strong_rec_thresh: 0.1
    medium_rec_thresh: 0.25
    ignored: missing_tracks unmatched_tracks
    ignored_media:
    - Data CD
    - DVD
    - DVD-Video
    - Blu-ray
    - HD-DVD
    - VCD
    - SVCD
    - UMD
    - VHS

paths:
    label:"Masters of Hardcore": M/Masters of Hardcore/$moh_catalog %if{$hasyear,${year}} %titlecase_proper{$album}/${padded_tracknr} %titlecase_proper{$artist} - %titlecase_proper{$title}
    tag:8bitpeoples: +game/+8bitpeoples/%titlecase_proper{$album} [$first_artist]%if{$hasyear, (${year})}/${padded_tracknr} $artist - %titlecase_proper{$title}
    tag:test: "+test/%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    singleton:true tag:eminem-skits: E/Eminem/+skits/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}
    singleton:true tag:eminem-diss: E/Eminem/+disses/+tracks/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}
    singleton:false tag:eminem-diss: "E/Eminem/+disses/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    singleton:true  tag:eminem-freestyles: E/Eminem/+freestyles/+tracks/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}
    singleton:false tag:eminem-freestyles: "E/Eminem/+freestyles/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    singleton:true tag:eminem-remix: E/Eminem/+remix/+tracks/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}
    tag:eminem albumtype:single: "E/Eminem/+singles/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:album: "E/Eminem/+lp/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:ep: "E/Eminem/+ep/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:promo: "E/Eminem/+promo/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:bootleg: "E/Eminem/+bootleg/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:unofficial: "E/Eminem/+bootleg/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:mixtape: E/Eminem/+mixtape/%titlecase_proper{$mixtape_album} [%titlecase_proper{$first_artist}]%if{$hasyear, (${year})}/${padded_tracknr} %titlecase_proper{$artist} - %titlecase_proper{$title}
    albumartist:eminem albumtype:mixtape: E/Eminem/+mixtape/%titlecase_proper{$mixtape_album} [%titlecase_proper{$first_artist}]%if{$hasyear, (${year})}/${padded_tracknr} %titlecase_proper{$artist} - %titlecase_proper{$title}
    tag:eminem albumtype:live: "E/Eminem/+live/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:demo: "E/Eminem/+demo/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:remix: "E/Eminem/+remix/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:soundtrack: "E/Eminem/+soundtrack/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:interview: "E/Eminem/+interview/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:compilation: "E/Eminem/+compilation/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:whitelabel: "E/Eminem/+whitelabel/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:audiobook: "E/Eminem/+audiobook/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem albumtype:other: "E/Eminem/+other/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem singleton:true: E/Eminem/+tracks/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}
    albumartist:eminem: "E/Eminem/+other/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:eminem: "E/Eminem/+other/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    tag:whoa: +hiphop-swe/whoa.nu/$base_name
    tag:frizon: +hiphop-swe/frizon.info/$base_name
    tag:randombastards: +hiphop-swe/randombastards/$base_name
    tag:streetfashion: +hiphop-swe/streetfashion/$base_name
    "tag:norrk\xF6ping": "+hiphop-swe/Sj\xE4tte Sinnet/$base_name"
    tag:ocremix: +game/+ocremix/$base_name
    tag:overlooked: +game/+overlookedremix/$base_name
    tag:amigaremix: +game/+amigaremix/$base_name
    tag:rosamannen: +live/+rosamannen/$base_name
    tag:sr: +radio/Sveriges Radio/%titlecase_proper{$album}/%if{$hasyear, $year} %titlecase_proper{$title}
    tag:gamesoundtrack: +game/+ost/$album%if{$hasyear, (${year})}/${padded_tracknr} $artist - %titlecase_proper{$title}
    tag:game: +game/%titlecase_proper{$album} [$albumartist]%if{$hasyear, (${year})}/${padded_tracknr} $artist - %titlecase_proper{$title}
    tag:game albumtype:soundtrack: +game/+ost/$album%if{$hasyear, (${year})}/${padded_tracknr} $artist - %titlecase_proper{$title}
    tag:game singleton:true: +game/+tracks/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}
    tag:mixtape: +mixtape/$mixtape_album [$first_artist]%if{$hasyear, (${year})}/${padded_tracknr} $artist - %titlecase_proper{$title}
    albumtype:mixtape: +mixtape/$mixtape_album [$first_artist]%if{$hasyear, (${year})}/${padded_tracknr} $artist - %titlecase_proper{$title}
    albumtype:single: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+singles/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:album: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+lp/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:ep: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+ep/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:promo: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+promo/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:whitelabel: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+whitelabel/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:bootleg: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+bootleg/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:unofficial: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+bootleg/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:live: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+live/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:demo: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+demo/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:remix: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+remix/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:audiobook: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+audiobook/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:interview: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+interview/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:other: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+other/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    singleton:true tag:demo: '%bucket{$first_artist_singleton, alpha}/%titlecase_proper{$first_artist_singleton}/+demo/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}'
    singleton:true tag:live: '%bucket{$first_artist_singleton, alpha}/%titlecase_proper{$first_artist_singleton}/+live/+tracks/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}'
    tag:live: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    singleton:true tag:interview: '%bucket{$first_artist_singleton, alpha}/%titlecase_proper{$first_artist_singleton}/+interview/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}'
    singleton:true tag:speechtone: '%bucket{$first_artist_singleton, alpha}/%titlecase_proper{$first_artist_singleton}/+speechtone/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}'
    singleton:true tag:freestyle: '%bucket{$first_artist_singleton, alpha}/%titlecase_proper{$first_artist_singleton}/+freestyles/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}'
    singleton:true: '%bucket{$first_artist_singleton, alpha}/%titlecase_proper{$first_artist_singleton}/+tracks/%if{$hasyear, $year} %titlecase_proper{$artist} - %titlecase_proper{$title}'
    albumtype:compilation ^albumartist:"Various Artists": "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/+compilation/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}"
    albumtype:soundtrack: +ost/%if{$hasyear,${year} }%titlecase_proper{$album} [$albumartist, $alb_type$media_type$format]/${padded_tracknr} %titlecase_proper{$title}
    comp: +va/%titlecase_proper{$album}%if{$hasyear, (${year})}/${padded_tracknr} $artist - %titlecase_proper{$title}
    default: "%bucket{$first_artist, alpha}/%titlecase_proper{$first_artist}/%titlecase_proper{$first_artist}%if{$hasyear, \u2502${year}\u2502} %titlecase_proper{$album} [$source]/${padded_tracknr} %titlecase_proper{$title}"
item_fields:
    padded_tracknr: '''{:02n}''.format(track)'
    moh_catalog: catalognum.replace(" ", "")
    first_artist: 'import re

        return re.split('',|\s+(feat(.?|uring)|&|(Vs|Ft).)'', albumartist, 1, flags=re.IGNORECASE)[0]

        '
    first_artist_singleton: 'import re

        return re.split('',|\s+(feat(.?|uring)|&|(Vs|Ft).)'', artist, 1, flags=re.IGNORECASE)[0]

        '
    base_name: 'import os.path

        base = os.path.basename(path)

        return os.path.splitext(base)[0]

        '
album_fields:
    cdtype: u'[%s]' % (albumtype.lower()) if albumtype else u''
    notalbum: 0 if albumtype and albumtype.lower() == 'album' else 1
    source: "media = set([i.media.lower() for i in items])\nformat = set([i.format for i in items])\ntbr = sum([i.bitrate for i in items])\nabr = tbr / len(items) / 1000\nbitdepth = sum([i.bitdepth for i in items]) // len(items)\n\n# Init output\no = [f for f in format] if format else []\n\n# Handle bitrate categories\nfor f in format:\n    if f == 'FLAC':\n        o.append(str(bitdepth) + 'bit')\n\nif abr < 480 and abr >= 320:\n    o.append('320')\nelif abr < 320 and abr >= 220:\n    o.append('V0')\nelif abr < 215 and abr >= 170 and abr != 192:\n    o.append('V2')\nelif abr == 192:\n    o.append('192')\nelif abr < 170:\n    o.append(str(abr))\n\n# Handle media aliases\nfor m in media:\n    if any(t in m for t in ('digital', 'file')):\n        o.append('WEB')\n    elif 'vinyl' in m:\n        o.append('Vinyl')\n    elif 'cd' in m:\n        o.append('CD')\n    elif m != '':\n        o.append(m)\n\nreturn \", \".join(o)\n"
    mixtape_album: 'import re

        album_fixed = album

        return re.sub(r"G.unit Radio,?\s+(Pt|Part)[.]?\s*(.*)", r"G-Unit Radio \2", album_fixed, flags=re.IGNORECASE)

        '
    alb_status: "# MB returns 4 values describing how \"offical\" a release is, they are:\n# Official, Promotional, Bootleg, and Pseudo-Release\n# We only note the middle two.\n# https://musicbrainz.org/doc/Release#Status\nif 'Promo' in albumstatus:\n  return 'Promo, '\nelif 'Bootleg' in albumstatus:\n  return 'Bootleg, '\nelif 'Official' in albumstatus:\n  return 'Official, '\nelif 'Promotion' in albumstatus:\n  return 'Promo, '\nelse:\n  return None\n"
    alb_type: "alb_types = \"\"\nalbumtypes_list = {\n  'ep': 'EP',\n  'lp': 'LP',\n  'single': 'Single',\n  'live': 'Live',\n  'remix': 'Remix',\n  'dj-mix': 'DJ-mix',\n  'mixtape/street': 'Mixtape',\n  'interview': 'Interview',\n}\nfor key, value in albumtypes_list.items():\n  if albumtype == key:\n    alb_types += str(value)\n\n  if alb_types is not None:\n    if alb_types != '':\n      return alb_types + ', '\n  else:\n    return None\n"
    media_type: "# https://musicbrainz.org/doc/Release/Format\n# Lets Merge the variations of the same medium into the main\n# medium name (Opinonated)\nmedia_list = {\n '12\" Vinyl':     'Vinyl, ',\n '10\" Vinyl':     'Vinyl, ',\n '7\" Vinyl':      'Vinyl, ',\n 'Vinyl':         'Vinyl, ',\n 'CDr':           'CDR, ',\n 'CD-R':          'CDR, ',\n 'Cassette':      'Cassette, ',\n 'Digital Media': 'Web, ',\n 'CD':            'CD, ',\n 'File':          'Web, ',\n 'DVD':           'DVDA, ',\n}\n# Lets omit these instead of converging them under a similar label like above (Opinonated)\nmedia_types_to_omit = ['Enhanced CD', 'CDDA', 'Blu-spec CD', 'HQCD', '']\nif items[0].media in media_list:\n  return str(media_list[items[0].media])\nelif items[0].media in media_types_to_omit:\n  return None\nelse:\n  return str(items[0].media)\n"
    hasyear: 1 if year > 0 else 0

ui:
    color: yes
    colors:
        text_success: '40'
        text_warning: '137'
        text_error: '160'
        text_highlight: '106'
        text_highlight_minor: '108'
        action_default: '197'
        action: '210'
pathfields: {}
lastimport:
    per_page: 500
    retry_limit: 3


```
