### ISSUE TITLE
beets fails to detect compilations when importing metadata from Deezer

### ISSUE THREAD

**Issue by Czechball** [beetbox/beets#4057]
### Problem

Beets is interpreting compilations as albums and is putting all artists into folder names, resulting in extremely long paths
Standard import command:

```sh
$ beet im
```

Led to this problem:

```
Correcting tags from:
    A.Skillz - 2017 Fractal Forest Compilation
To:
    A.Skillz, Chali 2na, CMC & Silenta, Deekline, Defunk, DJ Brace, Fort Knox Five, K+Lab, Krafty Kuts, KWADI, Marten Hørger, Neighbour, OPIUO, Skratch Bastid, Slynk, Stanton Warriors, Stickybuds, The Funk Hunters, Dynamite MC, Father Funk, MC Rtkal, Mystro, Neon Steve, Shad, Malenda, Various Artists - 2017 Fractal Forest Compilation
URL:
    https://www.deezer.com/album/43959881
(Similarity: 81.4%) (tracks, artist, source) (Deezer, 2017, Westwood Recordings)
 * Real Big Deal (Original Mix)                            -> Real Big Deal (Original Mix) (source)
 * 7 Day Weekend (Original Mix)                            -> 7 Day Weekend (Original Mix) (source)
 * Limoncello feat. Shad (Original Mix)                    -> Limoncello feat. Shad (Original Mix) (source)
 * The Things That You Do feat. Father Funk (Original Mix) -> The Things That You Do feat. Father Funk (Original Mix) (source)
 * Right Now (Original Mix)                                -> Right Now (Original Mix) (source)
 * Flanjitsu (Original Mix)                                -> Flanjitsu (Original Mix) (source)
 * Flute Ting feat. MC Rtkal (Original Mix)                -> Flute Ting feat. MC Rtkal (Original Mix) (source)
 * Still Here (Stanton Warriors Shambhala Mix)             -> Still Here (Stanton Warriors Shambhala Mix) (source)
 * You Don't (Original Mix)                                -> You Don't (Original Mix) (source)
 * Shake My Head (Original Mix)                            -> Shake My Head (Original Mix) (source)
 * Don't Go (K+Lab Remix)                                  -> Don't Go (K+Lab Remix) (source)
 * Brazilian Hipster (Original Mix)                        -> Brazilian Hipster (Original Mix) (source)
 * Yeah Thats Right feat. Mystro & Malenda (Original Mix)  -> Yeah Thats Right feat. Mystro & Malenda (Original Mix) (source)
 * Right Right Up feat. CMC&Silenta and Verse Ital         -> Right Right Up feat. CMC&Silenta and Verse Ital (source)
 * Get Involved feat. Defunk                               -> Get Involved feat. Defunk (source)
 * Clap Ya Hands Now feat. KWADI (Original Mix)            -> Clap Ya Hands Now feat. KWADI (Original Mix) (source)
```

[Full -vv output](https://pastebin.com/zhsQ7u64)

### Setup

* OS: Linux void 5.13.15_1
* Python version: Python 3.9.7
* beets version: beets version 1.5.0
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/hdd/beets-export
library: /mnt/hdd/beets.db

plugins: spotify discogs deezer edit

paths:
    default: $albumartist - $album ($year) %if{$catalognum,{$catalognum$} }[Deezer WEB - $format]/$track. $artist - $title
    singleton: $artist - $album ($year) %if{$catalognum,{$catalognum$} [Deezer WEB - $format]/$track. $artist - $title
    comp: Various Artists - $album ($year) %if{$catalognum,{$catalognum$} [Deezer WEB - $format]/$track. $artist - $title
spotify:
    source_weight: 0.5
    mode: list
    tiebreak: popularity
    show_failures: no
    artist_field: albumartist
    album_field: album
    track_field: title
    region_filter:
    regex: []
    client_id: REDACTED
    client_secret: REDACTED
    tokenfile: spotify_token.json
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
    separator: ', '
    index_tracks: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
deezer:
    source_weight: 0.5
```
