### ISSUE TITLE
comp vs. albumartist circle dependency with 'autotag: no' | 'autotag: no' but modification of tags

### ISSUE THREAD

**Issue by friedrich-daniel** [beetbox/beets#4072]
# Expected result
no modification of tags with 'autotag: no'

# Observed result

* import behaviour 1
	if comp is TRUE and albumartist is set
	beet import modifies 'comp: True -> False'
	
* import behaviour 2
	if comp is TRUE and albumartist is not set 
	beet import modifies 'albumartist: -> Various Artists'

Hint:
It seems that a comp with albumartist is not a comp,
but if no albumartist is set, a albumartist is set automatically which makes it indirectly with next import to a not comp.

Inconsistent behaviour.

# Version
v1.5.0

# Workaround
As workaround I commented out in file beets/importer.py function align_album_level_fields the part in if action.ASIS-plugins= version

# Configuration (output of `beet config`) is:

```yaml
directory: ~/MusicNew
library: ~/.cache/beets/musiclibrary.db

import:
    move: no
    copy: yes
    write: no
    autotag: no
    duplicate_action: ask

clutter:

plugins: inline fetchart duplicates

replace:
    \.: ''
item_fields:
    disc_and_track: u'%02i.%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)

paths:
    default: $albumartist/$album%aunique{} ($year)/$disc_and_track $title
    comp: $genre/$album%aunique{} ($year)/$track $title
    singleton: Non-Album/$artist/$title
    albumtype:soundtrack: Soundtracks/$album%aunique{} ($year)/$track $title
    albumtype:Audiobook: Audiobook/$album%aunique{} ($year)/$track $title
fetchart:
    auto: yes
    cover_names: cover front back art
    sources: filesystem
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    google_key: REDACTED
    google_engine: xxx
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
pathfields: {}
album_fields: {}
```
