### ISSUE TITLE
Beet update seems to move files sometimes even when "move: no" is set

### ISSUE THREAD

**Issue by the-solipsist** [beetbox/beets#4079]
### Problem
I ran the following commands, and somewhere in between, a number of folders got deleted from my hard drive.

```sh
beet import /mnt/sadr/music/Compilations/
beet update classi
beet ls classica
beet ls classical
beet ls jazz
```

Before I ran the above commands, a directory named 'Albums' was there on my drive. After running the `beet ls jazz` command, I realized my entire Albums directory had been erased.  Since it was on an NFS-connected drive, the files didn't even end up in a 'Trash' folder.

I haven't run anything else that could possibly have deleted that entire folder.

When I run beet, I get this warning, which I've been ignoring:
```
/home/sol/.local/lib/python3.9/site-packages/beets/mediafile.py:21: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
```

Could that be related?

Here is an extract from the beets.log:
```
import started Thu Sep 30 05:44:42 2021
skip /mnt/sadr/music/Compilations/[2021] - 100 Greatest Classic Jazz Songs
import started Fri Oct  1 01:59:30 2021
import started Fri Oct  1 01:59:59 2021
import started Fri Oct  1 03:19:36 2021
import started Fri Oct  1 03:23:59 2021
import started Fri Oct  1 03:29:21 2021
import started Fri Oct  1 03:32:53 2021
asis /mnt/sadr/music/Compilations/[2021] - 100 Greatest Classic Jazz Songs
```

### Setup

* OS: Linux (Ubuntu 21.04)
* Python version: 3.9.0
* beets version: 1.5.1
* Turning off plugins made problem go away (yes/no): Too scared to try.

```
beet --version                                                                                                                                                    ↵ 2
/home/sol/.local/lib/python3.9/site-packages/beets/mediafile.py:21: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
beets version 1.5.1
Python version 3.9.0
plugins: discogs, duplicates, edit, extrafiles, fetchart, fetchartist, fromfilename, fuzzy, info, inline, mbsync, missing, the
```

My configuration (output of `beet config`) is:

```yaml
/home/sol/.local/lib/python3.9/site-packages/beets/mediafile.py:21: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
directory: /mnt/sadr/music
library: ~/.data/musiclibrary.blb

paths:
    albumtype:soundtrack: OST/[$_year] - $album/[$album - ${disc_and_track}] - $artist - $title
    series_name::.: Series/$series_name/[$_year] - $album/[$album - $disc_and_track] - $artist - $title
    comp: Compilations/[$_year] - $album/[$album - ${disc_and_track}] - $artist - $title
    singleton: Singles/$artist - $title
    default: Albums/$albumartist/[$_year] - $album/$albumartist - [$album - $disc_and_track] %if{$diffartist,- $artist }- $title

plugins: discogs inline duplicates edit extrafiles fetchart fetchartist fromfilename fuzzy info mbsync missing the
pluginpath: ~/.config/beets/plugins

format_item: $albumartist - $_year - $original_year - $album - $disc_and_track - %if{$diffartist,$artist - }$title
format_album: $albumartist - $_year - $original_year - $album
original_date: yes
per_disc_numbering: yes
chroma:
    auto: no

import:
    write: yes
    resume: yes
    move: no
    incremental: no
    log: ~/.data/beets.log
    languages: en
fetchart:
    cautious: yes
    cover_names: cover front back art album folder
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
fetchartist:
    filename: folder
freedesktop:
    auto: yes
item_fields:
    initial: albumartist[0].upper() + u'.'
    disc_and_track: u'%02i.%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
    multidisc: 1 if disctotal > 1 else 0
    diffartist: 1 if albumartist != artist else 0
    _year: original_year if original_year else year
web:
    host: 0.0.0.0
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    separator: ', '
    index_tracks: no
extrafiles:
    patterns:
        all: '*.*'

    paths: {}
missing:
    count: no
    total: no
    album: no
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
fuzzy:
    prefix: '~'
    threshold: 0.7
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
pathfields: {}
album_fields: {}
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
```
