### ISSUE TITLE
Prevent Discogs from overwriting genre tags

### ISSUE THREAD

**Issue by arsaboo** [beetbox/beets#4087]
Discogs is a useful source for meta-data, however, the genre information in Discogs is pretty useless. Currently, when we use Discogs as a tag source, everything is overwritten by Discogs information. I posted it on [Discourse here](https://discourse.beets.io/t/prevent-discogs-plugin-from-overwriting-existing-genre-tags/1884) and Adrian suggested that currently, the Discogs plugin is not configurable. 

In general, I think it would be a good idea to make plugins configurable so that they don't overwrite other details that the user may not want. 

### Proposed solution

Make Discogs plugin configurable so that users can choose fields to be ignored. The current behavior (where it imports everything) can be the default so that this is not a breaking change. 

### Objective

Avoid getting unwanted information from Discogs. 

#### Goals

Provide more fine-grained user control.

**Comment by wisp3rwind** [comment]
Maybe the solution here should be a more general mechanism to configure auto-tagging rather than a discogs-specific approach? Something like a `keep-fields` importer option? The `*sync` plugins might want to respect such a setting, too.

**Comment by wisp3rwind** [comment]
In fact, we could have something like the following to also address (a part of) #4071

```yaml
import:
    autotag: yes|no
    autotag-fields:
        genre: 'append'  # see #4071
        year: 'as-is'   # import as-is, don't apply autotagger data
        comment: 'set: foo'   # set field to a constant value
        title: 'auto'   # the default, autotag this field
        albumartist_sort: 'zero'   # clear the field
```

and deprecate the `set_fields` option.

**Comment by sampsyo** [comment]
That's a pretty good idea! We could start with just the "filter" functionality (selecting fields not to apply) and then later expand it to take on the role of stuff like `set_fields`.

**Comment by arsaboo** [comment]
I like the idea of configuring inputs (with sensible defaults) that other auto-taggers could follow.

**Comment by snejus** [comment]
I've got something similar implemented in the `beetcamp` plugin, where most of the fields can be excluded. See the [readme](https://github.com/snejus/beetcamp) or the [implementation](https://github.com/snejus/beetcamp/blob/master/beetsplug/bandcamp/_metaguru.py#L587)
```yaml
bandcamp:
  ...
  exclude_extra_fields: []
  ...
```
