### ISSUE TITLE
kodiupdate: support updating multiple Kodi instances

### ISSUE THREAD

**Issue by ITguy3118** [beetbox/beets#4101]
Pretty straitforward ask, it would be nice if when running beets using the Kodi update client that you could enter multiple clients

syntax would be something to the tune of ...

kodi:
    host: x.x.x.x
    port: 8080
    user: user
    pwd: password
kodi:
    host: x.x.x.x
    port: 8080
    user: user
    pwd: password
kodi:
    host: x.x.x.x
    port: 8080
    user: user
    pwd: password
can this please be implemented

**Comment by jackwilsdon** [comment]
Thanks for opening a feature request. I don't think we can read duplicate keys from our configuration, so I propose the following configuration format:

```YAML
kodi:
  - host: localhost
    port: 8080
    user: kodi
    pwd: kodi
  - host: localhost
    port: 8081
    user: kodi
    pwd: kodi
```

We'd still need to support the non-list format too for backwards compatibility:

```YAML
kodi:
  host: localhost
  port: 8080
  user: kodi
  pwd: kodi
```
