### ISSUE TITLE
Import an album with track without ID

### ISSUE THREAD

**Issue by catap** [beetbox/beets#4110]
### Problem

I'm trying to import an album where the fist track hasn't got an ID.
Autotagger suggest to update all indexes to `+1` and set `1` to the first track which hasn't got and ID:
```
Tagging:
    Михаил Щербаков - Fair Lawn
URL:
    https://musicbrainz.org/release/e2515072-efe1-4cf7-b366-d321380a02dc
(Similarity: 87.3%) (tracks) (CD)
 * Начало (#0)            -> Начало (#1)
 * Дожил (#1)             -> Дожил (#2) (index)
 * То галопом (#2)        -> То галопом (#3) (index)
 * Ты черный волк (#3)   -> Ты черный волк (#4) (index)
 * Ничему не поверю (#4)  -> Ничему не поверю (#5) (index)
 * То ли дело (#5)        -> То ли дело (#6) (index)
 * День деньской (#6)    -> День деньской (#7) (index)
 * Навещая знакомый (#7) -> Навещая знакомый (#8) (index)
 * Если (#8)              -> Если (#9) (index)
 * Помнишь как (#9)       -> Помнишь как (#10) (index)
 * До поезда (#10)        -> До поезда (#11) (index)
 * Что в чужом (#11)      -> Что в чужом (#12) (index)
 * Когда не долг бы (#12) -> Когда не долг бы (#13) (index)
 * Не нарушать бы (#13)   -> Не нарушать бы (#14) (index)
``` 

### Setup

* OS: macOS 11.6
* Python version: 3.9.7 
* beets version: 1a5ddf89b5fe7191edb085bf38f9e0f3f434b1a8
* Turning off plugins made problem go away (yes/no): irrelevant.

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    sources: musixmatch genius tekstowo google
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    bing_client_secret: REDACTED
    bing_lang_to:
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
directory: /Volumes/music
asciify_paths: yes

import:
    move: yes
follow:
    auto: yes
    email: REDACTED
    password: REDACTED
    userid: REDACTED
fetchart:
    sources: filesystem coverart itunes amazon albumart lastfm
    lastfm_key: REDACTED
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
    high_resolution: no

musicbrainz:
    user: catap
    pass: REDACTED
mbcollection:
    auto: yes
    remove: yes
    collection: 04540b29-ba5e-4e0e-82e8-161035854aa4
smartplaylist:
    auto: yes
    relative_to: /Volumes/music
    prefix: REDACTED
    urlencode: yes
    forward_slash: yes
    playlist_dir: ~/Music/playlists
    playlists: [{name: _Everything.m3u, query: ''}, {name: $albumartist/_Everything.m3u, query: ''}, {name: '$albumartist/$album%aunique{}.m3u', query: ''}]
convert:
    copy_album_art: yes
    auto: no
    format: flac
    formats:
        copy_m4a:
            command: ffmpeg -i $source -y -vn -c:a copy $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    dest:
    pretend: no
    link: no
    hardlink: no
    threads: 12
    id3v23: inherit
    max_bitrate: 500
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    delete_originals: no

paths:
    default: '%the{$albumartist}/$album%aunique{}/$track $title'
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
ibroadcast:
    username: kirill@korins.ky
    password: jyhXyk-capzuh-2xunvi
    auto: no

plugins: convert duplicates edit embedart fetchart follow fuzzy ibroadcast info lastgenre lyrics mbcollection mbsubmit mbsync missing smartplaylist the web
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
missing:
    count: no
    total: no
    album: no
fuzzy:
    prefix: '~'
    threshold: 0.7
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
mbsubmit:
    format: $track. $title - $artist ($length)
    threshold: medium
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    readonly: yes

```
