### ISSUE TITLE
Beets missing obvious match within album and not moving file

### ISSUE THREAD

**Issue by azukaar** [beetbox/beets#4163]
In this particular example I was trying to import The Cardigans. In my library it was "Cardigans (The)" and Beets wants to move it to "The Cardigan". After importing for example "The First Band on the Moon", it imported everything succesfully except the track 5. All the tracks have the same naming schemes and proper tags, it had no reasons not to want to import this one particular file from the album. Anyway, I select "use as is" but Beets does not copy the file to the new "The Cardigan" folder, and keeps it in  "Cardigans (The)"  as an orphan track.
I would expect as-is to at least copy the file, otherwise its behaviour is not any different than "skip" right ?
The rest of the tracks were moved and recognized just fine.

* OS: Ubuntu
* Python version: 3
* beets version: 151

```yaml
directory: /mnt/music
library: ~/beets.db
match:
  ignored: missing_tracks
  strong_rec_thresh: 0.1
import:
  move: yes
  bell: yes
  incremental_skip_later: yes
fetchart:
  auto: yes
paths:
  default: '$albumartist/$album%aunique{}/$track $title'
  singleton: $artist/$title
  comp: 'Compilations/$album%aunique{}/$track $title'
plugins: fetchart embedart

```
![image](https://user-images.githubusercontent.com/7872597/143688929-c412b1d1-3e09-4b2a-b136-fd7b26e1a16f.png)

![image](https://user-images.githubusercontent.com/7872597/143688822-26294faa-795d-4eaa-a847-d0d748bc4c8a.png)
