### ISSUE TITLE
Folder case change seems to not work

### ISSUE THREAD

**Issue by azukaar** [beetbox/beets#4164]
Beets seems to trip when trying to rename folders changing casing. I have aerosmith and it's visibly trying to change it to Aerosmith (uppercase) and it just fails at doing that, even worst, it seems to register both aerosmith and Aerosmith in the DB

* OS: Ubuntu
* Python version: 3
* beets version: 151

```yaml
directory: /mnt/music
library: ~/beets.db
match:
  ignored: missing_tracks
  strong_rec_thresh: 0.1
import:
  move: yes
  bell: yes
  incremental_skip_later: yes
fetchart:
  auto: yes
paths:
  default: '$albumartist/$album%aunique{}/$track $title'
  singleton: $artist/$title
  comp: 'Compilations/$album%aunique{}/$track $title'
plugins: fetchart embedart
```

![image](https://user-images.githubusercontent.com/7872597/143689164-920cc38e-52f1-448b-a1b8-f14b1789ab8b.png)
