### ISSUE TITLE
warning message on every beet command

### ISSUE THREAD

**Issue by mattmartini** [beetbox/beets#4166]
Whenever I run a beet command I get the following warning message:

```
/usr/local/lib/python3.9/site-packages/beets/util/confit.py:19: UserWarning: beets.util.confit is deprecated; use confuse instead warnings.warn("beets.util.confit is deprecated; use confuse instead")
```
I get the same warning under MacOS (10.14.6, Mojave) or Ubuntu Linux (18.04.6 LTS).

It does not seem to affect the operation of beet, but it would be nice for it to go away.

### Problem

[MacOS]:
```
$ beet version
/usr/local/lib/python3.9/site-packages/beets/util/confit.py:19: UserWarning: beets.util.confit is deprecated; use confuse instead
  warnings.warn("beets.util.confit is deprecated; use confuse instead")
beets version 1.6.0
Python version 3.9.8
plugins: acousticbrainz, chroma, discogs, duplicates, edit, fetchart, fromfilename, importadded, info, lastgenre, mbsubmit, mbsync, metasync, missing, permissions, summarize, unimported, yearfixer
```

[Ubuntu]:
```
$ beet version
/home/<USER>/.local/lib/python3.6/site-packages/beets/util/confit.py:19: UserWarning: beets.util.confit is deprecated; use confuse instead
  warnings.warn("beets.util.confit is deprecated; use confuse instead")
beets version 1.6.0
Python version 3.6.9
plugins: acousticbrainz, chroma, discogs, duplicates, edit, fetchart, fromfilename, importadded, info, lastgenre, mbsync, metasync, missing, permissions, summarize, unimported, yearfixer
```

### Setup

* OS: MacOS 10.14.6 (Mojave)
* Python version: 3.9.8
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): yes

* OS: Ubuntu Linux 18.04.6 LTS
* Python version: 3.6.9
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
$ beet config
/usr/local/lib/python3.9/site-packages/beets/util/confit.py:19: UserWarning: beets.util.confit is deprecated; use confuse instead
  warnings.warn("beets.util.confit is deprecated; use confuse instead")
directory: /Users/<USER>/Music/Beets/Music
library: /Users/<USER>/Music/Beets/beets_musiclibrary.db

import:
    move: yes
    copy: no
    write: yes
    autotag: yes
    singletons: no
    duplicate_action: keep
    detail: yes
    log: /Users/<USER>/Music/Beets/beets_musiclibrary.log
    bell: yes

match:
    strong_rec_thresh: 0.07
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: low
        unmatched_tracks: medium
        preferred:
            countries: [US, GB|UK, GR]

format_item: "$format $bitrate  $length  ${track}/$tracktotal  $genre\t$artist\t$year\t$album\t$title"
format_album: "$year\t$albumartist\t$genre\t$album"
time_format: '%Y-%m-%d %H:%M:%S'

sort_album: albumartist_sort+ albumartist+ year+ album+
sort_item: artist+ year+ album+ disc+ track+
sort_case_insensitive: yes

clutter: [Thumbs.DB, .DS_Store, .AppleDouble]

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

plugins:
- acousticbrainz
- chroma
- discogs
- duplicates
- edit
- fetchart
- fromfilename
- importadded
- info
- lastgenre
- mbsubmit
- mbsync
- metasync
- missing
- permissions
- summarize
- unimported
- yearfixer
acousticbrainz:
    auto: yes
    force: no
    tags: []
chroma:
    auto: yes
discogs:
    user_token: REDACTED
    index_tracks: yes
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    separator: ', '
duplicates:
    count: yes
    delete: no
    merge: no
    path: no
    album: no
    checksum: ''
    copy: ''
    format: ''
    full: no
    keys: []
    move: ''
    tiebreak: {}
    strict: no
    tag: ''
fetchart:
    auto: yes
    sources: itunes *
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: REDACTED
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes
lastgenre:
    auto: yes
    canonical: no
    count: 1
    source: album
    separator: '; '
    title_case: yes
    whitelist: yes
    min_weight: 10
    fallback:
    force: yes
    prefer_specific: no
metasync:
    source: itunes
    itunes:
        library: /Users/<USER>/Music/iTunes/iTunes Library.xml
missing:
    format: $albumartist - $album - $title
    count: yes
    total: yes
    album: no
mbsubmit:
    format: $track. $title - $artist ($length)
    threshold: medium

musicbrainz:
    searchlimit: 8
permissions:
    file: 644
    dir: 755
unimported:
    ignore_extensions: jpg png
web:
    host: 0.0.0.0
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
yearfixer:
    auto: no
    force: no


```
