### ISSUE TITLE
Issue with albumdisambig

### ISSUE THREAD

**Issue by wazabees** [beetbox/beets#4171]
### Discussed in https://github.com/beetbox/beets/discussions/4066

<div type='discussions-op-text'>

<sup>Originally posted by **wazabees** September 18, 2021</sup>
After #3852 was fixed, I am having a strange result with `albumdisambig`. 
https://github.com/beetbox/beets/issues/3852

A few examples below:
```
beet ls -f '%asciify{$albumartist}/%if{$original_year,$original_year,$year} - $album%ifdef{albumdisambig, ($albumdisambig),}%ifdef{u_type, [$u_type],}/%right{$disc,1}-$track - $title' album:"The Gereg" track:1
```

**Result:** `The HU/2019 - The Gereg (deluxe edition)/1-01 - The Gereg`

The above command gives me the expected output. I want "deluxe edition" capitalized, so I'll change the command to this:
```
beet ls -f '%asciify{$albumartist}/%if{$original_year,$original_year,$year} - $album%ifdef{albumdisambig, (%title{$albumdisambig}),}%ifdef{u_type, [$u_type],}/%right{$disc,1}-$track - $title' album:"The Gereg" track:1
```
Again, I get the expected result, which is `The HU/2019 - The Gereg (Deluxe Edition)/1-01 - The Gereg`.

If I try an album that has `u_type` set, but empty `albumdisambig`, I get extra `()`, which is not expected.
```
beet ls -f '%asciify{$albumartist}/%if{$original_year,$original_year,$year} - $album%ifdef{albumdisambig, (%title{$albumdisambig}),}%ifdef{u_type, [$u_type],}/%right{$disc,1}-$track - $title' album:Nightmother track:1
```
**Result**: `Wormlight/2021 - Nightmother () [Bandcamp]/1-01 - Nightmother`

And if I try an album with empty `u_type` and empty `albumdisambig`, I see the same issue with extra `()` from `albumdisambig`, but there is no extra `[]` from `u_type`.
```
beet ls -f '%asciify{$albumartist}/%if{$original_year,$original_year,$year} - $album%ifdef{albumdisambig, (%title{$albumdisambig}),}%ifdef{u_type, [$u_type],}/%right{$disc,1}-$track - $title' album:Singularity track:1
```
**Result:** `Stortregn/2016 - Singularity ()/1-01 - Enlighten Salvation`

This leads be to believe the issue is with `albumdisambig`, but I am not sure why. :)

My installation is on Arch Linux:
```
╰─❯ beet --version
beets version 1.6.0
Python version 3.9.9
plugins: edit, fetchart, importfeeds, info, inline, lastimport, mbcollection, mbsync, mpdstats, mpdupdate, originquery, playlist, scrub, smartplaylist, summarize, types, unimported, zero
```

Thanks!</div>

**Comment by sampsyo** [comment]
Interesting! Might I suggest that a good way to narrow down the problem would be to simplify the formatting templates you're using so they *only* include the suspicious parts? That is, remove all the other parts and focus on the potentially-problematic disambig fields.

It might also be helpful to take a look at your config to see if any plugins/settings might be interfering with these fields. Disabling them temporarily could help answer that question.

**Comment by wazabees** [comment]
Thanks @sampsyo !

I have stripped down my config to a minimum one, as shown below.

```
# Global Options

directory: /mnt/barracuda/Music Library (FLAC)

library: ~/Music/beets.db

import:
    move: yes
    timid: yes
    log: ~/beets.log

unimported:
    ignore_extensions: jpg png cue nfo yaml log LOG sfv old m3u jpeg accurip txt json bmp org m3u8 JPG pdf PDF tif md5 bak mpdignore

max_filename_length: 255

match:
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD',
                    'VCD', 'SVCD', 'UMD', 'VHS', 'Cassette', 'Vinyl']
    ignore_video_tracks: yes
    ignore_data_tracks: yes

# Makes sure that multidisc volumes get track no. 1.. and up.
per_disc_numbering: yes

mpd:
    host: localhost
    port: 6600

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
```

I narrowed down the query to albumdisambig specifically and tested it out.

In my mind, there should be no output from the command below, but it still outputs `()`.

```
╰─❯ beet ls -f '%ifdef{albumdisambig, ($albumdisambig),}' album:"Nightmother" track:1
 ()
```

For a track with `albumdisambig` non-empty, it works.
```
╰─❯ beet ls -f '%ifdef{albumdisambig, ($albumdisambig),}' album:"The Gereg" track:1
(deluxe edition)
```
