### ISSUE TITLE
clutter option not doing anything

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [beetbox/beets#4174]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
beet import /Volumes/Music/Cavalcade 
```

Led to:

```
user configuration: /Users/redacted/.config/beets/config.yaml
data directory: /Users/redacted/.config/beets
plugin paths: 
artresizer: method is (2, (7, 0, 10), False)
Sending event: pluginload
library database: /Users/redacted/.config/beets/library.db
library directory: /Volumes/Audio
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /Volumes/Audio/Cavalcade
Tagging black midi - Cavalcade
No album ID found.
Search terms: black midi - Cavalcade
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'cavalcade', 'artist': 'black midi', 'tracks': '8'}
Requesting MusicBrainz release 3fe0649a-cea8-44a9-ae6c-2d575fae5aed
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: black midi - Cavalcade (3fe0649a-cea8-44a9-ae6c-2d575fae5aed)
Computing track assignment...
...done.
Success. Distance: 0.00
Requesting MusicBrainz release 4287af1d-53c8-40ec-96f0-4caf7f832a4d
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: black midi - Cavalcade (4287af1d-53c8-40ec-96f0-4caf7f832a4d)
Computing track assignment...
...done.
Success. Distance: 0.15
Requesting MusicBrainz release 345d99c7-ea59-4af1-8212-cff33b42608f
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: black midi - Cavalcade (345d99c7-ea59-4af1-8212-cff33b42608f)
Computing track assignment...
...done.
Success. Distance: 0.46
Requesting MusicBrainz release c38e105c-bd85-4e3b-b652-73261e3ebd49
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: black midi - Cavalcade (c38e105c-bd85-4e3b-b652-73261e3ebd49)
Computing track assignment...
...done.
Success. Distance: 0.04
Requesting MusicBrainz release 0be2bb5a-2ee3-4751-8cf0-25f0fa7187b8
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: black midi - bmbmbm (Dos Monos remix) (0be2bb5a-2ee3-4751-8cf0-25f0fa7187b8)
Computing track assignment...
...done.
Success. Distance: 0.65
discogs: Searching for master release 2140543
discogs: Searching for master release 2140543
discogs: Searching for master release 2140543
discogs: Searching for master release 2140543
discogs: Searching for master release 2140543
Sending event: albuminfo_received
Candidate: Black Midi - Cavalcade (18869488)
Computing track assignment...
...done.
Success. Distance: 0.18
Sending event: albuminfo_received
Candidate: Black Midi - Cavalcade (18852154)
Computing track assignment...
...done.
Success. Distance: 0.18
Sending event: albuminfo_received
Candidate: Black Midi - Cavalcade (18958246)
Computing track assignment...
...done.
Success. Distance: 0.07
Sending event: albuminfo_received
Candidate: Black Midi - Cavalcade (18963268)
Computing track assignment...
...done.
Success. Distance: 0.26
Sending event: albuminfo_received
Candidate: Black Midi - Cavalcade (18576418)
Computing track assignment...
...done.
Success. Distance: 0.18
Evaluating 10 candidates.

/Volumes/Audio/Cavalcade (8 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
Tagging:
    black midi - Cavalcade
URL:
    https://musicbrainz.org/release/3fe0649a-cea8-44a9-ae6c-2d575fae5aed
(Similarity: 100.0%) (Digital Media, 2021, XW, Rough Trade)
Sending event: import_task_choice
Sending event: import_task_apply
0 of 8 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
lyrics: lyrics not found: black midi - Cavalcade - John L
lyrics: lyrics not found: black midi - Cavalcade - Marlene Dietrich
lyrics: lyrics not found: black midi - Cavalcade - Chondromalacia Patella
lyrics: lyrics not found: black midi - Cavalcade - Slow
lyrics: lyrics not found: black midi - Cavalcade - Diamond Stuff
lyrics: lyrics not found: black midi - Cavalcade - Dethroned
lyrics: lyrics not found: black midi - Cavalcade - Hogwash and Balderdash
lyrics: lyrics not found: black midi - Cavalcade - Ascending Forth
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: art_set
artresizer: ImageMagick resizing /Volumes/Audio/black midi/Cavalcade/cover.jpg to /var/folders/4y/96gd8p814dq0mlqc24_6_bq00000gn/T/tmprp4jkxmc.jpg
embedart: Embedding album art into black midi - Cavalcade
Sending event: write
Sending event: after_write
Sending event: write
Sending event: after_write
Sending event: write
Sending event: after_write
Sending event: write
Sending event: after_write
Sending event: write
Sending event: after_write
Sending event: write
Sending event: after_write
Sending event: write
Sending event: after_write
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: album_imported
Sending event: import
Sending event: cli_exit
redacteds-iMac:~ redacted$ 
```

There's no mention of anything about clutter and the folder is not removed. This happens with any folder. I'm testing it with a test.cue file, which is the sole file remaining on it after beet runs.

### Setup

* OS: macOS High Sierra
* Python version: 3.9.5
* beets version: 1.6.0

It's been like this for a while, not sure it ever worked.

My configuration (output of `beet config`) is:

```
directory: /Volumes/Music/

plugins: convert discogs duplicates fetchart embedart lyrics missing zero
autotag: yes
art_filename: cover

clutter:
- .DS_Store
- Thumbs.DB
- '*.txt'
- '*.pdf'
- '*.bmp'
- '*.png'
- '*.jpg'
- '*.jpeg'
- '*.tif'
- '*.gif'
- '*.sfv'
- '*.nfo'
- '*.m3u'
- '*.log'
- '*.cue'
original_date: yes
languages: en
va_name: Various
ignored_media: .vob .mp4 .mkv .avi .ts .pdf .cbz .cbr

import:
    copy: no
    write: yes
    move: yes

paths:
    default: $albumartist/$album%aunique{albumartist album, tracktotal year label,()}/$track. $title
    comp: Various/$album%aunique{albumartist album, tracktotal year label,()}/$track. $title
    albumartist:various artists: Various/$album%aunique{albumartist album, tracktotal year label,()}/$track. $title

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
    ^\s+: ''
    ^-: _
    ;: _
convert:
    tmpdir: /Volumes/Media/Audio/
    auto: yes
    delete_originals: yes
    no_convert: path::\.(m4a)$
    command: ffmpeg -y -i $source -vsync 0 -q:a 0 -map_metadata 0 $dest
    extension: mp3
    dest:
    pretend: no
    link: no
    hardlink: no
    threads: 4
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    quiet: no
    embed: yes

    paths: {}
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    separator: ', '
    index_tracks: no
duplicates:
    album: yes
    move: /Users/redacted/Downloads/
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    path: no
    tiebreak: {}
    strict: no
    tag: ''
fetchart:
    auto: yes
    sources: fanarttv itunes amazon coverart albumart google
    fanarttv_key: REDACTED
    google_API_key: REDACTED
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
embedart:
    auto: yes
    maxwidth: 1000
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
chroma:
    auto: no
zero:
    auto: yes
    update_database: yes
    keep_fields:
    - artist
    - title
    - album
    - year
    - composer
    - albumartist
    - track
    - tracktotal
    - disc
    - disctotal
    - label
    - acoustid_fingerprint
    - acoustid_id
    - albumtype
    - lyrics
    - unsyncedlyrics
    - images
    - rating
    - first played
    - last played
    - play count
    fields: []
missing:
    count: no
    total: no
    album: no
```
