### ISSUE TITLE
MusicBrainz Genres apparently not being added

### ISSUE THREAD

**Issue by kongwak** [beetbox/beets#4201]
### After upgrading from v1.5 to 1.6.0 and then a clean install to the latest tarball (v1.6.1) MusicBrainz Genres are not being added to track/album/library metadata

The same problem existed after uninstalling and re-installing 1.6.0 and then doing a clean install of v1.6.1 from the current tarball (per instruction in FAQ). I tried with numerous albums but settled on Let it Bleed as it is well populated with Genre Tags in MusicBrainz

I see the same issue in mbsync and with import.

Picard will populate the field successfully

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv mbsync "Let it bleed"
user configuration: /home/rtpg/.config/beets/config.yaml
data directory: /home/rtpg/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/rtpg/.config/beets/lib/musiclibrary.db
library directory: /home/rtpg/Music
Sending event: library_opened
Requesting MusicBrainz release 739dce81-ed70-4ebc-8ae5-607f1fbcebf6
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
mbsync: applying changes to The Rolling Stones - Let It Bleed
Sending event: cli_exit
```

and also 

```sh
 $ beet -vv import -L Music/Rolling\ Stones\,\ The/Let\ It\ Bleed/
user configuration: /home/rtpg/.config/beets/config.yaml
data directory: /home/rtpg/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/rtpg/.config/beets/lib/musiclibrary.db
library directory: /home/rtpg/Music
Sending event: library_opened
Sending event: import_begin
yielding album 1132: The Rolling Stones - Let It Bleed
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/rtpg/Music/Rolling Stones, The/Let It Bleed
Tagging The Rolling Stones - Let It Bleed
Searching for discovered album ID: 739dce81-ed70-4ebc-8ae5-607f1fbcebf6
Requesting MusicBrainz release 739dce81-ed70-4ebc-8ae5-607f1fbcebf6
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: The Rolling Stones - Let It Bleed (739dce81-ed70-4ebc-8ae5-607f1fbcebf6)
Computing track assignment...
...done.
Success. Distance: 0.07
Album ID match recommendation is Recommendation.medium
Search terms: The Rolling Stones - Let It Bleed
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'let it bleed', 'artist': 'the rolling stones', 'tracks': '9'}
Requesting MusicBrainz release f6d8a428-d098-4e44-9434-97c2e13b0e03
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: The Rolling Stones - Let It Bleed (f6d8a428-d098-4e44-9434-97c2e13b0e03)
Computing track assignment...
...done.
Success. Distance: 0.28
Requesting MusicBrainz release 499485cb-dac1-4741-bfcc-e6b218c50029
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: The Rolling Stones - Let It Bleed (499485cb-dac1-4741-bfcc-e6b218c50029)
Computing track assignment...
...done.
Success. Distance: 0.29
Requesting MusicBrainz release f70b14d4-8d29-4c98-803e-6219316e1b6a
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: The Rolling Stones - Let It Bleed (f70b14d4-8d29-4c98-803e-6219316e1b6a)
Computing track assignment...
...done.
Success. Distance: 0.28
Requesting MusicBrainz release 6f603b94-ad3b-4db6-808f-5e3576da1513
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: The Rolling Stones - Let It Bleed (6f603b94-ad3b-4db6-808f-5e3576da1513)
Computing track assignment...
...done.
Success. Distance: 0.29
Requesting MusicBrainz release 4f04e1b3-6a72-4869-9450-637c57370b88
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: The Rolling Stones - Let It Bleed (4f04e1b3-6a72-4869-9450-637c57370b88)
Computing track assignment...
...done.
Success. Distance: 0.29
Evaluating 6 candidates.

/home/rtpg/Music/Rolling Stones, The/Let It Bleed (9 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
Tagging:
    The Rolling Stones - Let It Bleed
URL:
    https://musicbrainz.org/release/739dce81-ed70-4ebc-8ae5-607f1fbcebf6
(Similarity: 92.7%) (tracks) (Vinyl, 1969, GB, Decca Records, SKL 5025)
 * Gimme Shelter (3:33) ->
   Gimme Shelter (4:30) (length)
 * Country Honk (7:31) ->
   Country Honk (3:07) (length)
 * Live With Me (2:54) ->
   Live With Me (3:33) (length)
 * Let It Bleed (4:34) ->
   Let It Bleed (5:27) (length)
 * Midnight Rambler (3:05) ->
   Midnight Rambler (6:52) (length)
 * You Got the Silver (5:25) ->
   You Got the Silver (2:50) (length)
 * You Can’t Always Get What You Want (6:56) ->
   You Can’t Always Get What You Want (7:28) (length)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? a
Sending event: import_task_choice
Sending event: import_task_apply
Replacing item 14583: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-01 Gimme Shelter.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 14584: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-02 Love in Vain.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 14585: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-03 Country Honk.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 14586: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-04 Live With Me.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 14587: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-05 Let It Bleed.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 14588: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-06 Midnight Rambler.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 14589: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-07 You Got the Silver.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 14590: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-08 Monkey Man.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 14591: /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-09 You Can’t Always Get What You Want.mp3
Sending event: database_change
Sending event: database_change
Sending event: album_removed
Sending event: item_removed
9 of 9 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Reimported album: added 1638502099.8043275, flexible attributes ['data_source', 'data_source'] from album 1132 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed
Reimported item added 1638502099.8087428 from item 14583 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-01 Gimme Shelter.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14583 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-01 Gimme Shelter.mp3
Sending event: database_change
Reimported item added 1638502099.8073368 from item 14584 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-02 Love in Vain.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14584 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-02 Love in Vain.mp3
Sending event: database_change
Reimported item added 1638502099.812142 from item 14585 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-03 Country Honk.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14585 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-03 Country Honk.mp3
Sending event: database_change
Reimported item added 1638502099.8107913 from item 14586 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-04 Live With Me.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14586 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-04 Live With Me.mp3
Sending event: database_change
Reimported item added 1638502099.8064501 from item 14587 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-05 Let It Bleed.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14587 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-05 Let It Bleed.mp3
Sending event: database_change
Reimported item added 1638502099.8080661 from item 14588 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-06 Midnight Rambler.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14588 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-06 Midnight Rambler.mp3
Sending event: database_change
Reimported item added 1638502099.809421 from item 14589 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-07 You Got the Silver.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14589 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-07 You Got the Silver.mp3
Sending event: database_change
Reimported item added 1638502099.8114667 from item 14590 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-08 Monkey Man.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14590 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-08 Monkey Man.mp3
Sending event: database_change
Reimported item added 1638502099.810111 from item 14591 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-09 You Can’t Always Get What You Want.mp3
Reimported item flexible attributes ['track_alt', 'data_source', 'track_alt', 'data_source'] from item 14591 for /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-09 You Can’t Always Get What You Want.mp3
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
the: "The Rolling Stones" -> "Rolling Stones, The"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-01 Gimme Shelter.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-02 Love in Vain.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-03 Country Honk.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-04 Live With Me.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-05 Let It Bleed.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-06 Midnight Rambler.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-07 You Got the Silver.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-08 Monkey Man.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
scrub: auto-scrubbing /home/rtpg/Music/Rolling Stones, The/Let It Bleed/01-09 You Can’t Always Get What You Want.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
Sending event: album_imported
Sending event: import
Sending event: cli_exit

```

Led to this problem: Genres field is unpopulated

```
$beet info "Let it bleed"
<only showing last track>
/Music/Rolling Stones, The/Let It Bleed/01-09 You Can’t Always Get What You Want.mp3
             album: Let It Bleed
       albumartist: The Rolling Stones
albumartist_credit: The Rolling Stones
  albumartist_sort: Rolling Stones, The
      albumartists: 
       albumstatus: Official
         albumtype: album
          arranger: 
               art: True
            artist: The Rolling Stones
     artist_credit: The Rolling Stones
       artist_sort: Rolling Stones, The
           artists: 
          bitdepth: 0
           bitrate: 192000
      bitrate_mode: 
               bpm: 0
        catalognum: SKL 5025
          channels: 2
              comp: False
           country: GB
              date: 1969-12-05
               day: 5
              disc: 1
         disctotal: 1
      encoder_info: 
  encoder_settings: 
            format: MP3
            genres:
             label: Decca Records
          language: eng
            length: 416.6007916666667
            lyrics: 
  mb_albumartistid: b071f9fa-14b0-4217-8e97-eb41da73f598
 mb_albumartistids: b071f9fa-14b0-4217-8e97-eb41da73f598
        mb_albumid: 739dce81-ed70-4ebc-8ae5-607f1fbcebf6
       mb_artistid: b071f9fa-14b0-4217-8e97-eb41da73f598
      mb_artistids: b071f9fa-14b0-4217-8e97-eb41da73f598
 mb_releasegroupid: 784c0edd-0f37-33a2-9ca5-dff87b4f999c
 mb_releasetrackid: a3bf4e9c-82e2-325a-8d92-313287747375
        mb_trackid: 9d8c543c-8dee-4aca-867e-909b496ca875
         mb_workid: 5ac1c053-5f4d-3e75-b6c9-6169595e784e
             media: Vinyl
             month: 12
     original_date: 1969-11-29
      original_day: 29
    original_month: 11
     original_year: 1969
        samplerate: 44100
            script: Latn
             title: You Can’t Always Get What You Want
             track: 9
        tracktotal: 9
              year: 1969

```

### Setup

* OS: Ubuntu 20.04
* Python version: 3.8.10
* beets version: 1.6.0 (returned by  "beet version", the site packages says 1.6.1) 
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music
library: ~/.config/beets/lib/musiclibrary.db

import:
    write: yes
    move: yes
    resume: ask
    log: ~/.config/beets/lib/import.log

musicbrainz:
    extra_tags: []
    genres: yes

paths:
    default: '%asciify{%the{$albumartist}}/$album%aunique{albumartist album year, year label catalognum albumdisambig releasegroupdisambig}/$disc-$track $title'
    singleton: '%the{$artist}/Non-Album/%the{$artist} - $title'
    comp: Various_Artist/$album%aunique{}/$disc-$track $title
    albumtype:soundtrack: Soundtracks/$album/$disc-$track $title

plugins:
- badfiles
- info
- fetchart
- ftintitle
- missing
- scrub
- duplicates
- the
- mbsync
fetchart:
    auto: yes
    cover_names: cover front album art
    maxwidth: 500
    enforce_ratio: yes
    minwidth: 0
    quality: 0
    max_filesize: 0
    cautious: no
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
ftintitle:
    auto: yes
    format: (feat. {0})
    drop: no
missing:
    format: $albumartist - $album - $title
    count: yes
    total: yes
    album: no
scrub:
    auto: yes
duplicates:
    count: yes
    album: no
    checksum: ''
    copy: ''
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
the:
    a: yes
    the: yes
    format: '{0}, {1}'
    strip: no
    patterns: []

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
threaded: yes
ignore: .AppleDouble ._* *~ .DS_Store

```
Thank you for any help or guidance
