### ISSUE TITLE
ReplayGain threads don't appear to be working in master.

### ISSUE THREAD

**Issue by HidYn** [beetbox/beets#4245]
I upgraded to master/nightly docker to fix the R128 integer issue [4195](https://github.com/beetbox/beets/pull/4195) and started a re-scan on my library.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv replaygain -a
$ beet -vv replaygain --threads 16 -a
```

Led to this problem:

```
Only one instance of ffmpeg is used no matter the settings
```

### Setup

* OS:  Docker
* Python version: 3.9.7
* beets version:  1.6.0/master/nightly
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web mbsync mbsubmit lyrics zero permissions
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    threads: 1
    formats:
        flac:
            command: ffmpeg -i $source -y -acodec flac $dest
            extension: flac
    
paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/-$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title 
        
import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album
    
zero:
    auto: no
    fields: rg_album_gain rg_album_peak rg_track_gain rg_track_peak
    update_database: true

lyrics:
    auto: no
    fallback: ''
    sources: google genius musixmatch

embedart:
    auto: yes

fetchart:
    auto: yes
    sources: filesystem itunes fanarttv coverart amazon albumart
    
replaygain:
    auto: yes
    overwrite: yes
    backend: ffmpeg
    targetlevel: 89
    r128_targetlevel: 84
    r128: FLAC
    threads: 16
    parallel_on_import: no
    

scrub:
    auto: yes
    
permissions:
    file: 644
    dir: 755
    
acoustid:
    apikey: REDACTED

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337


```
