### ISSUE TITLE
Edit Plugin: Text file is always blank

### ISSUE THREAD

**Issue by gcoter** [beetbox/beets#4257]
Hello :slightly_smiling_face: I have a question regarding the Edit Plugin.

When I edit a track, I expect the opened text file to be prefilled with the existing metadata. In other words, I would expect the file to be filled with the content of `beet info`. Then I can edit the fields I want and save the file to apply the changes.

However, it is not the case for me. When I run `beet edit`, the text file is always blank, even if the track has metadata (which I can see with `beet info`). 

Is it normal?

Here are some information about my setup:
- OS: Ubuntu 20.04
- Beet:
```
beets version 1.6.0
Python version 3.8.10
plugins: acousticbrainz, duplicates, edit, fetchart, fromfilename, info, lastgenre, lyrics, missing, play, scrub, smartplaylist
```
- My config.yaml
```
directory: ~/Nextcloud/Music/Collection/
library: ~/Nextcloud/Music/Collection/beets_library.db
paths:
    default: Albums/$albumartist/$album%aunique{}/$track - $title
    singleton: Singles/$artist - $title
plugins: scrub missing duplicates fromfilename lastgenre lyrics fetchart edit acousticbrainz info play smartplaylist
lastgenre:
    auto: yes
    count: 10
    whitelist: ~/projects/beets-config/lastgenre/genres.txt
    source: track
lyrics:
    auto: yes
    fallback: ''
    force: no
    sources: lyricwiki musixmatch
fetchart:
    auto: yes
edit:
    itemfields: track title artist album genre lyrics
    albumfields: album albumartist genre
acousticbrainz:
    auto: yes
smartplaylist:
    auto: yes
    playlist_dir: ~/Nextcloud/Music/Collection/Playlists/
    forward_slash: no
    prefix: ""
    urlencoded: no
    playlists:
    - name: Complextro.m3u
      query: "Complextro"
```

Thank you for your help :slightly_smiling_face:
