### ISSUE TITLE
beets not detecting Queens of the Stone Age - Villains in MusicBrainz

### ISSUE THREAD

**Issue by trevordavies095** [beetbox/beets#4276]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import "/Volumes/Backup/Music_old/Queens of the Stone Age/[0000-00-00] Villains"
```

Led to this problem:

Beets not picking up Queens of the Stone Age - Villains release from MusicBrainz

https://musicbrainz.org/release/fde9a6de-1610-44d5-8f11-bfc139656a2b

```
Link to log: https://gist.github.com/trevordavies095/6ba517e397d4aa33908299ecbb951956
```
![Screen Shot 2022-02-13 at 3 19 05 PM](https://user-images.githubusercontent.com/647327/153961400-c157bada-c925-41be-af70-240230138604.png)

### Setup

* OS: macOS Monterey (12.1)
* Python version: Python 3.9.1
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/Backup/Music/
library: /Volumes/Backup/Music/musiclibrary.db

plugins: fetchart
fetchart:
    cautious: yes
    cover_names: front back
    sources: itunes *
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
threaded: yes

paths:
    default: $albumartist/[$original_year-$original_month-$original_day] $album/$disc-$track $title

```
