### ISSUE TITLE
SEVERE DATA LOSS BUG WITH MUSICBRAINZ GENRES

### ISSUE THREAD

**Issue by vinyllionel** [beetbox/beets#4289]
my grandfather and i have been spending the past two years scanning, digitizing, sorting, and categorizing his extensive vinyl collection. literally thousands of records, about half of which are so old/rare/obscure that they're either not in musicbrainz or have only the thinnest of entries.

he's not very computer literate, so i wrote a bunch of scripts to help him input data. these are really just simple helper scripts and rely on picard+beets for all the heavy lifting under the hood. i did this because 1) when we complete this effort, we want to export our library and contribute back to musicbrainz so making sure everything is properly tagged is critical and 2) because everyone said picard+beets was one of the most powerful combos for the job.

well, we're on the last step of filling in genres, and at some point (i believe it was after an mbsync on monday) **_we just lost every genre for every item that was updated_**

### this amounts to a week's worth of tagging work (6-7 evenings) completely lost. this is beyond infuriating.

@sampsyo @aereaux @alastair i realize it's probably my fault for relying on some hobbyist project for an undertaking like this, but i'm so incredibly annoyed a bug like this hasn't been immediately reverted or mitigated as soon as it was known.

**can you three please work together to either get this fixed and a new point release pushed asap or completely remove any dependencies on whatever code is responsible for handling genres until this gets figured out? or print out a HUGE WARNING that data loss is possible?**

this has been massively demoralizing for both me and more importantly, my 91 year old grandfather who's just trying to catalog and share his jazz collection.

### Problem

catastrophic data loss bug using mbsync and genre tags for items musicbrainz seemingly already knows about:

```sh
$ beet -vv mbsync [ANYTHING]
```

Led to this problem: genre field getting blanked out on anything matching the mbsync query above.

### Setup

* OS: Ubuntu 21.10
* Python version: Python 3.8
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): No

This is a minimally viable reproducer config:

```yaml
directory: /mnt/external14tb/music
library: /mnt/external14tb/lib/musiclibrary.db

import:
    write: yes
    move: yes
    resume: ask
    log: /mnt/external14tb/lib/import.log

musicbrainz:
    extra_tags: []
    genres: yes

paths:
    default: '%asciify{%the{$albumartist}}/$album%aunique{albumartist album year, year label catalognum albumdisambig releasegroupdisambig}/$disc-$track $title'
    singleton: '%the{$artist}/Non-Album/%the{$artist} - $title'
    comp: Various_Artist/$album%aunique{}/$disc-$track $title
    albumtype:soundtrack: Soundtracks/$album/$disc-$track $title

plugins:
- mbsync

ui:
    color: yes
```
