### ISSUE TITLE
move: import and beet import -AC leads to data loss

### ISSUE THREAD

**Issue by hamaryns** [beetbox/beets#4291]
I had sorted out part of my music library, using a config file based on the docs, which had

```yaml
import:
    move: yes
…
paths:
    …
    comp: Compilations/$album%aunique{}/$artist – $title
```
 
But then I realized I wanted Compilations to be Compilaties (Dutch), so I changed that.  I then did

`rm .beets/musiclibrary.db`

and 

`beet import -AC Muziek`

after which the folder ‘Compilations’ has disappeared, and nothing in return.  It seems like the files are gone.
### Setup

* OS: Linux Mint Mate 20.3 64-bit
* Python version: 
* beets version: beet --version
beets version 1.6.0
Python version 3.8.10

* Turning off plugins made problem go away (yes/no): 
no

also, now no folder ‘Compilaties’ is made and new compilations are placed under ‘Various artists’, but the ones that were under ‘Compilations’ are gone
