### ISSUE TITLE
Incremental option not working

### ISSUE THREAD

**Issue by KrLx1994roller** [beetbox/beets#4315]
### Problem

Running `import` on the same directory with `incremental: yes` keeps adding already added songs, creating thousands of duplicates that need to be removed afterwards.

Command:

```sh
$ beet import /mnt/tmp/music
```

### Setup

* OS: Debian 10
* Python version: 3.7.3
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no
* Plugins: duplicates

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/music
library: ~/beet/library.db
asciify_paths: yes
threaded: yes

import:
    copy: yes
    autotag: no
    write: no
    incremental: yes
    group_albums: yes
    duplicate_action: ask
    log: ~/beet/import.log

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track - $title

plugins: duplicates

duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
```
