### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by hamaryns** [beetbox/beets#4342]
OK, so this time I really think I spotted a problem.  I ripped a CD, but since it didn’t work properly, it ended up in 2 directories.  I then imported those directories with beets.  The first one imported fine, with of course the mention that some tracks were missing.  Then it proceeded to the second directory, and again found the album and mentioned tracks were failing, but I chose Apply, and then… BOOM.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import -P /media/hendrik2/Scharnier/Muziek\ te\ sorteren/ 2> beet2.log

/media/hendrik2/Scharnier/Muziek te sorteren/Cobla Amsterdam (11 items)
Tagging:
    Cobla Amsterdam - Live in Catalunya
URL:
    https://musicbrainz.org/release/d09e68bd-04b7-4e5b-bbfa-854868467486
(Similarity: 90.4%) (missing tracks) (CD, 2008, NL, Etcetera, KTC 1375)
Missing tracks (4/15 - 26.7%):
 ! Ricard Viladesau – Barcelona ’92 (obligada 2 trumpets) (# 7) (5:06)
 ! Francesc Riumalló – Oncle i nebot (obligada tenora)    (# 9) (4:48)
 ! Max Havart – Rouranenca (obligada tenora)              (#11) (4:06)
 ! Emili Saló – El Bruel de Pals (obligada 2 fiscorns)    (#12) (4:44)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? 

/media/hendrik2/Scharnier/Muziek te sorteren/Cobla La Principal d’Amsterdam (4 items)
Finding tags for album "Cobla La Principal d’Amsterdam - Live in Catalunya".
Candidates:
1. Cobla Amsterdam - Live in Catalunya (36.3%) (missing tracks, tracks, artist, ...) (CD, 2008, NL, Etcetera, KTC 1375)
2. Cobla Maravella - Catalunya Dança (19.6%) (missing tracks, tracks, album, ...) (12" Vinyl, 1964, ES, Zafiro, Z-M 10)
3. Cobla Maravella Dtor. Lluís Ferrer i Puigdemont - Catalunya Canta (19.4%) (missing tracks, tracks, album, ...) (12" Vinyl, 1968, ES, Canigó, CANI-4-S)
4. Cobla "La Selvatana" - Sardanas A Salvador Dalí (17.0%) (tracks, album, artist, ...) (7" Vinyl, 1964, ES, Sandiego, SAN-111)
5. Jaume Pahissa, Miguel Llobet Solés, Gaspar Cassadó, Manuel de Falla; Giacomo Palazzesi - Catalunya (16.7%) (missing tracks, tracks, artist, ...) (Digital Media, 2016, XW, GuitArt Collection)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? 
Correcting tags from:
    Cobla La Principal d’Amsterdam - Live in Catalunya
To:
    Cobla Amsterdam - Live in Catalunya
URL:
    https://musicbrainz.org/release/d09e68bd-04b7-4e5b-bbfa-854868467486
(Similarity: 36.3%) (missing tracks, tracks, artist, year) (CD, 2008, NL, Etcetera, KTC 1375)
 * Track 7  -> Ricard Viladesau – Barcelona ’92 (obligada 2 trumpets) (title)
 * Track 9  -> Francesc Riumalló – Oncle i nebot (obligada tenora) (title)
 * Track 11 -> Max Havart – Rouranenca (obligada tenora) (title)
 * Track 12 -> Emili Saló – El Bruel de Pals (obligada 2 fiscorns) (title)
Missing tracks (11/15 - 73.3%):
 ! Vicens Bou – Girona aimada!                   (# 1) (4:19)
 ! Ricard Castells – Els Degotalls               (# 2) (3:38)
 ! Conrad Saló – La Feste de Sant Martirià       (# 3) (4:51)
 ! Josep Saderra – Mercé                         (# 4) (4:26)
 ! Manel S. Puigferrer – Ceretana                (# 5) (4:27)
 ! Pere Mercader – Conxita encisera              (# 6) (4:41)
 ! Jaume Roca Delpech – Gavina                   (# 8) (4:22)
 ! Joaquim Serra – Sabadell                      (#10) (4:33)
 ! Robert Sarrade – En Guii de Sant Cebrià       (#13) (4:55)
 ! Marcel Artiaga – Els milors anys              (#14) (4:07)
 ! Tomàs Gil Membrado – 25 anys de Baix Montseny (#15) (4:56)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? a
Old: 11 items, FLAC, 725kbps, 44.1kHz/16 bit, 49:21, 256.4 MiB
New: 4 items, FLAC, 715kbps, 44.1kHz/16 bit, 18:46, 95.9 MiB
[S]kip new, Keep all, Remove old, Merge all? m

```

Led to this problem:

```
(paste here)
```
[beet2.log](https://github.com/beetbox/beets/files/8609731/beet2.log)

### Setup
OS: Linux Mint Mate edition 20.3 64 bit
Python version:
$ python2 --version
Python 2.7.18
beets version:
$ beet --version
beets version 1.6.0
Python version 3.8.10
plugins: chroma, fetchart, fromfilename, lastgenre
(different python versions, that’s interesting)* Turning off plugins made problem go away (yes/no): How can I test this?  The first folder is imported and moved, the second is still in the to be imported folder.

My configuration (output of `beet config`) is:

```yaml
$ beet config
directory: /media/hendrik2/Scharnier/Muziek
library: ~/.beets/musiclibrary.db

import:
    move: yes
log: beetslog.txt
art_filename: "$albumartist \u2013 $album"

plugins: fetchart lastgenre chroma fromfilename mbsync

paths:
    default: "Albums/$albumartist/$album%aunique{}/$artist \u2013 $title"
    singleton: "Losse nummers/$artist/$artist \u2013 $title"
    comp: "Compilaties/$album%aunique{}/$artist \u2013 $title"
acoustid:
    apikey: REDACTED
chroma:
    auto: yes
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes

```
