### ISSUE TITLE
beet import icremental

### ISSUE THREAD

**Issue by antonellocaroli** [beetbox/beets#4376]
### Problem

Sorry, but I don't quite understand how it works `beet import -i`

I have a fairly large library and sometimes I delete several directories

at this point when I use `beet import -i` I would expect beet to automatically delete from the database the paths it no longer finds, in the same way it does with new paths (which it adds in this case)
am I missing something in the configuration?

I would expect it to first delete the paths that no longer exist and then import the new ones.
Otherwise, it would keep the old path in case of renaming...

### Setup

* OS: Gentoo
* Python version: 3.9.13
* beets version: 1.6.0
* Plugin: acousticbrainz, chroma, info, lastgenre, missing, play, types
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
plugins: play info acousticbrainz chroma lastgenre missing types
directory: /home/filippo/Musica/

import:
    copy: no
    write: no
    log: /home/filippo/.config/beets/import.log
    default_action: apply
    languages: en de it
play:
    command: gst-play-1.0 --gapless --audiosink='alsasink device=hw:CARD=DirettaAlsa,DEV=0'
    raw: yes
    use_folders: no
    relative_to:
    warning_threshold: 100
    bom: no
acoustid:
    apikey: REDACTED
chroma:
    auto: yes
acousticbrainz:
    auto: yes
    force: yes
    tags: []
lastgenre:
    auto: yes
    canonical: ~/.config/beets/genres/genres-tree.yaml
    whitelist: ~/.config/beets/genres/genres.txt
    count: 5
    fallback: Pop/Rock
    separator: '; '
    force: no
    min_weight: 10
    prefer_specific: no
    source: track
    title_case: yes
verbose: no

ui:
    color: yes
    colors:
        text_success: green
        text_warning: blue
        text_error: red
        text_highlight: blue
        text_highlight_minor: lightgray
        action_default: darkblue
        action: purple
hook:
    hooks:
    -   event: album_imported
        command: echo "\"{album}\""
    -   event: import
        command: echo "imported from {paths}"
    -   event: art_set
        command: echo "Coverart saved"
    -   event: import_begin
        command: echo "GP import started..."
    -   event: import_task_apply
        command: echo "Metadata applied"
    -   event: item_copied
        command: echo "\"{item}\" copied from \"{source}\" to \"{destination}\""
    -   event: item_moved
        command: echo "Moved \"{item}\""
    -   event: write
        command: echo "Writing to {path}"
    -   event: cli_exit
        command: echo "All tasks finished!"
missing:
    count: no
    total: no
    album: no
```
