### ISSUE TITLE
Simple track matching out of place

### ISSUE THREAD

**Issue by J4gQBqqR** [beetbox/beets#4391]
This is very troublesome:
```
$ pwd
...滨崎步/Hamasaki.Ayumi.Album.Single.Remix.Flac/Album/1995-12-01 濱崎步 - NOTHING FROM NOTHING

$ ls
'1 Nothing from Nothing - single version.flac'  '3 Paper Doll.flac'  '5 Nothing from Nothing - album version.flac'
'2 Limit.flac'                                  '4 Gut it-pez.flac'   cover.jpg

$ beet -c /home/xxxxx/.config/beets/config.yaml import .

.../滨崎步/Hamasaki.Ayumi.Album.Single.Remix.Flac/Album/1995-12-01 濱崎步 - NOTHING FROM NOTHING (5 items)
Correcting tags from:
    浜崎あゆみ - NOTHING.FROM.NOTHING
To:
    浜崎あゆみ FEATURING 童子-T & DJ BASS - NOTHING FROM NOTHING
URL:
    https://musicbrainz.org/release/aed16164-b296-40ad-810f-35a7714a1156
(Similarity: 91.1%) (tracks, artist) (CD, 1995, JP, ART FORCE, COCA-13057, Mini-Album)
 * Nothing from Nothing - single version     -> NOTHING FROM NOTHING (Single Version)
 * Limit                                     -> LIMIT
 * Paper Doll                                -> PAPER DOLL
 * Nothing from Nothing - album version (#5) -> Gut it-Pez (#4) (title, index)
 * Gut it-pez (#4)                           -> NOTHING FROM NOTHING (Album Version) (#5) (title, index)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```

Please see above, track 4 and track 5 is switched in place by Beets. In this case, this is a letter by letter match, why the switch?
```
 * Nothing from Nothing - album version (#5) -> Gut it-Pez (#4) (title, index)
 * Gut it-pez (#4)                           -> NOTHING FROM NOTHING (Album Version) (#5) (title, index)
 ```

**Comment by sampsyo** [comment]
Do the files have MusicBrainz IDs embedded in them? What do the track lengths look like? (It can sometimes be useful to actually listen to the songs; sometimes beets detects that the titles are wrong.)

**Comment by J4gQBqqR** [comment]
![image](https://user-images.githubusercontent.com/77554817/176441215-b4e996fb-b717-47c9-89fd-2f383485a360.png)

![image](https://user-images.githubusercontent.com/77554817/176441132-85114a53-f686-420c-a63a-94757f9766bd.png)

No, it does not have musicbrainz id in its metadata, and the track number is tagged correctly in its metadata as well.
I've listened to the track myself, I can also confirm that the track is correct.

**Comment by sampsyo** [comment]
Hard to say in that case! FWIW, I'm not sure what tool you're using to look at the metadata, but it doesn't look like it's set up to display MBIDs. You could try the beets `info` plugin, which will show everything beets knows how to read.

**Comment by J4gQBqqR** [comment]
screenshots are from foobar2000. But let me try beets info:
```
            album: NOTHING.FROM.NOTHING
     albumartists:
              art: False
           artist: 浜崎あゆみ
          artists:
         bitdepth: 16
          bitrate: 793905
     bitrate_mode:
         channels: 2
         comments: RIP By xxx
             date: 1995-01-01
     encoder_info:
 encoder_settings:
           format: FLAC
            genre: JPop
           genres: JPop
           length: 374.63281179138323
mb_albumartistids:
     mb_artistids:
       samplerate: 44100
            title: Nothing from Nothing - album version
            track: 5
       tracktotal: 5
             year: 1995
```

```
            album: NOTHING.FROM.NOTHING
     albumartists:
              art: False
           artist: 浜崎あゆみ
          artists:
         bitdepth: 16
          bitrate: 806170
     bitrate_mode:
         channels: 2
         comments: RIP By xxx
             date: 1995-01-01
     encoder_info:
 encoder_settings:
           format: FLAC
            genre: JPop
           genres: JPop
           length: 364.26666666666665
mb_albumartistids:
     mb_artistids:
       samplerate: 44100
            title: Gut it-pez
            track: 4
       tracktotal: 5
             year: 1995
`
