### ISSUE TITLE
import languages transliteration not working ?

### ISSUE THREAD

**Issue by rombat** [beetbox/beets#4453]
### Problem

From what I understand, `languages` option is supposed to transliterate artist name.
For instance, my `languages` config is this:

```yaml
import:
    copy: yes
    write: yes
    timid: yes
    languages: fr en jp
```

If I run this command

Running this command in verbose (`-vv`) mode:

```sh
beet -vv import '.\Fantastic Children OST ~A Gift from Greecia\' --set genre="Anime"
user configuration: C:\Users\tinbapakk\AppData\Roaming\beets\config.yaml
data directory: C:\Users\tinbapakk\AppData\Roaming\beets
plugin paths:
artresizer: method is (2, (7, 1, 0), False)
lyrics: Disabling google source: no API key configured.
inline: adding item field disc_and_track
Sending event: pluginload
library database: D:\Downloads\beets\musiclibrary.db
library directory: D:\Downloads\beets
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: D:\Downloads\soulseektemp\Fantastic Children Music Collection (FLAC)\Fantastic Children OST ~A Gift from Greecia
Tagging Ueno Koji - Fantastic Children OST ~A Gift from Greecia
No album ID found.
Search terms: Ueno Koji - Fantastic Children OST ~A Gift from Greecia
Additional search terms: {'year': 2005, 'catalognum': ''}
Album might be VA: True
Searching for MusicBrainz releases with: {'release': 'fantastic children ost ~a gift from greecia', 'artist': 'ueno koji', 'tracks': '27', 'date': '2005'}
Requesting MusicBrainz release 14dd6b6c-498b-475d-9037-ec7d93eaf7c5
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: 上野耕路 - Fantastic Children OST "Greece Kara no Okurimono" (14dd6b6c-498b-475d-9037-ec7d93eaf7c5)
Computing track assignment...
...done.
Success. Distance: 0.27
Requesting MusicBrainz release 612c10de-b822-4b4c-befd-9fa7068e4b9d
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Takashi Ueno - Sui-Gin (612c10de-b822-4b4c-befd-9fa7068e4b9d)
Computing track assignment...
...done.
Success. Distance: 0.78
Requesting MusicBrainz release 00db62ce-abc0-4611-b9fd-e2094f607604
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Takashi Ueno - ハスノス (00db62ce-abc0-4611-b9fd-e2094f607604)
Computing track assignment...
...done.
Success. Distance: 0.71
Requesting MusicBrainz release 5a41cecf-7bef-4a5d-ba05-f28f24dce113
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Takashi Ueno - Variations of Weeds (5a41cecf-7bef-4a5d-ba05-f28f24dce113)
Computing track assignment...
...done.
Success. Distance: 0.67
Requesting MusicBrainz release fa917072-0539-468e-b341-46ed88daf8e0
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: TJ_babybrain - forgotten_children (OST) (fa917072-0539-468e-b341-46ed88daf8e0)
Computing track assignment...
...done.
Success. Distance: 0.83
Searching for MusicBrainz releases with: {'release': 'fantastic children ost ~a gift from greecia', 'arid': '89ad4ac3-39f7-470e-963a-56509c546377', 'tracks': '27', 'date': '2005'}
Requesting MusicBrainz release 14dd6b6c-498b-475d-9037-ec7d93eaf7c5
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: 上野耕路 - Fantastic Children OST "Greece Kara no Okurimono" (14dd6b6c-498b-475d-9037-ec7d93eaf7c5)
Duplicate.
Requesting MusicBrainz release fa917072-0539-468e-b341-46ed88daf8e0
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: TJ_babybrain - forgotten_children (OST) (fa917072-0539-468e-b341-46ed88daf8e0)
Duplicate.
Requesting MusicBrainz release 79e1f6d4-5564-4c32-bafd-3cfd15e54393
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Gang of Four - A Gift (79e1f6d4-5564-4c32-bafd-3cfd15e54393)
Computing track assignment...
...done.
Success. Distance: 0.80
Requesting MusicBrainz release 0eb8e372-d8f9-492a-8218-3fe66609a462
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Janie Horton - A Gift From Janie (0eb8e372-d8f9-492a-8218-3fe66609a462)
Computing track assignment...
...done.
Success. Distance: 0.75
Requesting MusicBrainz release 6c26d163-a747-38d4-8367-0344a12ea952
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Janie Horton - A Gift From Janie (6c26d163-a747-38d4-8367-0344a12ea952)
Computing track assignment...
...done.
Success. Distance: 0.76
bandcamp: Searching as for Fantastic Children OST ~A Gift from Greecia using {'query': 'Fantastic Children OST ~A Gift from Greecia', 'artist': 'Ueno Koji', 'label': '', 'search_type': 'a'}
Evaluating 8 candidates.

D:\Downloads\soulseektemp\Fantastic Children Music Collection (FLAC)\Fantastic Children OST ~A Gift from Greecia (27 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
Correcting tags from:
    Ueno Koji - Fantastic Children OST ~A Gift from Greecia
To:
    上野耕路 - Fantastic Children OST "Greece Kara no Okurimono"
URL:
    https://musicbrainz.org/release/14dd6b6c-498b-475d-9037-ec7d93eaf7c5
```

Artists names end up being tagged in kanji.
If I do the exact same thing with MusicBrainz Picard, they are transliterated:
![image](https://user-images.githubusercontent.com/9024503/186011775-603e75b8-10fb-4eb6-9e90-08149dc783be.png)

Is there something I don't get with this option, or is it a bug ?

### Setup

* OS:  Windows 11
beets version 1.6.0
Python version 3.10.6
plugins: bandcamp, convert, embedart, fetchart, ftintitle, inline, lyrics, zero

My configuration (output of `beet config`) is:

```yaml
directory: D:\Downloads\beets
library: D:\Downloads\beets\musiclibrary.db

import:
    copy: yes
    write: yes
    timid: yes
    languages: fr en jp

artist_credit: yes
per_disc_numbering: yes
original_date: yes

match:
    preferred:
        media: ['CD', 'Digital Media|File']
        original_year: yes

paths:
    default: $albumartist/$year - $album%aunique{}/$disc_and_track - $title
    singleton: Non-Album/$artist/$title
    albumtype:soundtrack: Soundtracks/$album/$track - $title
    albumtype:anime: Anime/[$original_year-$original_month-$original_day] $album/$track - $title
    albumtype:game: Game/[$original_year-$original_month-$original_day] $album/$track - $title
    comp: Various Artists/[$original_year-$original_month-$original_day] $album%aunique{}/$track - $title

musicbrainz:
    extra_tags: [year, catalognum]
    
plugins: fetchart lyrics embedart inline convert zero ftintitle bandcamp

fetchart: 
    cover_format: JPEG
    minwidth: 800
    maxwidth: 1600
    sources: filesystem coverart itunes amazon albumart fanarttv lastfm google
#    quality: 90
    
embedart:
    maxwidth: 1200
#    quality: 90
    
item_fields:
    disc_and_track: u'%2i.%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
    
convert:
    format: aac
    formats: 
        aac:
            command: qaac --ignorelength --threading -q 2 --tvbr 118 --rate keep $source -o $dest
            extension: m4a
    dest: D:\Downloads\beets
    copy_album_art: yes
    embed: yes
    auto: yes
    never_convert_lossy_files: yes

zero:
    auto: yes
    fields: albumartist_sort composer_sort artist_sort original_month original_day
    
ftintitle:
    auto: yes
        
bandcamp:
    art: yes
    genre:
        maximum: 1

lyrics:
    auto: true,
    sources: google genius musixmatch
```
