### ISSUE TITLE
BPD: Could not create playbin

### ISSUE THREAD

**Issue by robinwit** [beetbox/beets#4460]
I installed these deps:
`brew reinstall gstreamer gst-plugins-base pygobject3 gst-plugins-good`
But BPD fails to call GStreamer (found [this](https://github.com/beetbox/beets/pull/2696) related PR).

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ python3 -m beets -vv bpd
```

Led to this problem:

```
user configuration: /Users/robin/.config/beets/config.yaml
data directory: /Users/robin/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Users/robin/.config/beets/library.db
library directory: /Users/robin/Music
Sending event: library_opened
bpd: Starting server...
error: Could not create playbin
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: macOS 12.5.1 (arm64)
* Python version: Python 3.10.6
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is:

```yaml
plugins: bpd
bpd:
    host: 127.0.0.1
    port: 6600
    password: REDACTED
    volume: 100
    control_port: 6601
```
