### ISSUE TITLE
configuration `include:` array/list merging (e.g. Plugins, Sources etc.)

### ISSUE THREAD

**Issue by jojoxd** [beetbox/beets#4470]
### Problem

Using `include:` in configuration overwrites `plugins`, `sources` etc.

Having file 'config.yaml':
```yaml
include:
  - ./config/plugin-1.yaml
  - ./config/plugin-2.yaml
```

and file './config/plugin-1.yaml':
```yaml
plugins:
  - plugin-1

plugin-1:
  some: config
```

and file './config/plugin-2.yaml':
```yaml
plugins:
  - plugin-2

plugin-2:
  some: config
```

produces the following configuration:
```yaml
include:
  - ./config/plugin-1.yaml
  - ./config/plugin-2.yaml

plugins:
  - plugin-2

plugin-1:
  some: config

plugin-2:
  some: config
```

It selects plugin-2 as this is the lowest plugin in `include:`.

I Expect that it generates the following configuration:
```yaml
include:
  - ./config/plugin-1.yaml
  - ./config/plugin-2.yaml

plugins:
  - plugin-1 # The plugins array is merged
  - plugin-2

plugin-1:
  some: config

plugin-2:
  some: config
```

This should also work with `sources:` and `pluginpath:`.

This would allow sharing snippet yaml files as full configurations that can be `include:`d in the main beets config.yaml file, It would also allow segmenting the configuration (my use-case) on a per-category base (`art.yaml` includes fetchart and embedart plugins, and `replaygain.yaml` includes the replaygain plugin, for example)

### Setup

* OS: Fedora 35 KDE Using docker (betanin)
* Python version: 3.9.5
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is: n/a, example provided above.
