### ISSUE TITLE
musicbrainz host, https and ratelimit config options are ignored

### ISSUE THREAD

**Issue by PotcFdk** [beetbox/beets#4518]
### Problem

While trying to make the `mbsync` plugin work with a selfhosted server, I noticed that the ratelimiting was not respected.
Further looking into the issue, I noticed that none of the requests were appearing in my server logs.
Not only that, but when watching the logs while doing a normal import on a fresh installation without any plugins, nothing appears either.

### Setup

* OS: multiple tried, behavior was consistent between NixOS and Arch Linux
* Python version: tried 3.10.5 and 3.10.8 respectively
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
# beet -c poc.yml config

musicbrainz:
    host: mbserver.example.org
    https: yes
    ratelimit: 100


```
