### ISSUE TITLE
albumtypes is converted from a string to a list of individual characters

### ISSUE THREAD

**Issue by MorgothSauron** [beetbox/beets#4528]
### Problem

After importing new files I will run `beet update`. Some of the tracks will have the `albumtypes` 'transformed' from a string (`album`) to a list of character (`['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']`). The `albumtype` field will become a single character (`album` -> `a`)

I could not get the output with `-vv` because it doesn't seem to happen everytime. I deleted albums that previous triggered this problem and the problem didn't repeat on import and update again.

```sh
$ beet update
```

Led to this problem:

```
Ghost - Ceremony and Devotion - Square Hammer
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - From the Pinnacle to the Pit
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Con clavi con dio
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Per aspera ad inferi
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Elizabeth
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Body and Blood
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Devil Church
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Cirice
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Ghuleh / Zombie Queen
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Year Zero
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Spöksonat
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - He Is
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Mummy Dust
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Secular Haze
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Absolution
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Ghost - Ceremony and Devotion - Ritual
  albumtypes: album; live -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 'l', 'i', 'v', 'e']
  albumtype: live -> a
Arch Enemy - Wages of Sin - Enemy Within
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Arch Enemy - Wages of Sin - Burning Angel
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Arch Enemy - Wages of Sin - Heart of Darkness
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Arch Enemy - Wages of Sin - Ravenous
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Arch Enemy - Wages of Sin - Savage Messiah
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Glenn Tipton - Baptizm of Fire - Hard Core
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Glenn Tipton - Baptizm of Fire - Paint It Black
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Glenn Tipton - Baptizm of Fire - Enter the Storm
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Glenn Tipton - Baptizm of Fire - Fuel Me Up
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Glenn Tipton - Baptizm of Fire - Extinct
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Glenn Tipton - Baptizm of Fire - Baptizm of Fire
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Glenn Tipton - Baptizm of Fire - The Healer
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
Glenn Tipton - Baptizm of Fire - Cruise Control
  albumtypes: album -> ['a', 'l', 'b', 'u', 'm']
  albumtype: album -> a
```

### Setup

* OS: Gentoo Linux (6.0.3-gentoo-x86_64)
* Python version: 3.10.8
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): don't know: I don't have the `albumtypes` plugin in my config.

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    force: yes
    fallback: ''
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    local: no
    sources:
    - google
    - musixmatch
    - genius
    - tekstowo
library: /home/mcarpentier/Music/.beets/BeetMusicLibrary.blb
directory: /home/mcarpentier/Music

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

import:
    copy: no
    write: yes
    move: yes

plugins: embedart fetchart info lyrics
embedart:
    auto: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
```

**Comment by MorgothSauron** [comment]
I checked the flac file metadata and album type is defined multiple time ... one tag for each letter

```
RELEASETYPE=a
RELEASETYPE=l
RELEASETYPE=b
RELEASETYPE=u
RELEASETYPE=m
MUSICBRAINZ_ALBUMTYPE=a
MUSICBRAINZ_ALBUMTYPE=l
MUSICBRAINZ_ALBUMTYPE=b
MUSICBRAINZ_ALBUMTYPE=u
MUSICBRAINZ_ALBUMTYPE=m
```

**Comment by MorgothSauron** [comment]
I tried to investigate this issue a little bit. Lets hope this information will be useful

I started by re-importing the library: `beet import ~/Music`. The library is mostly comprised of FLAC files.,

There was nothing displayed when I ran `beet update -p`.

I used `metaflac --export-tags-to` to export tags for all tracks in my library.

Things got worse. Now **every single** file have these weird tags. 

Example for `/home/mcarpentier/Music/Trivium/Shogun/01 Kirisute Gomen.flac`

`metaflac`:

```
RELEASETYPE=a
RELEASETYPE=l
RELEASETYPE=b
RELEASETYPE=u
RELEASETYPE=m
MUSICBRAINZ_ALBUMTYPE=a
MUSICBRAINZ_ALBUMTYPE=l
MUSICBRAINZ_ALBUMTYPE=b
MUSICBRAINZ_ALBUMTYPE=u
MUSICBRAINZ_ALBUMTYPE=m
```

`beet info`:

```
         acoustid_id: 
               album: Shogun
         albumartist: Trivium
  albumartist_credit: Trivium
    albumartist_sort: Trivium
        albumartists: 
       albumdisambig: 
         albumstatus: Official
           albumtype: a
          albumtypes: a; l; b; u; m
```

I deleted the tags from the FLAC files for this album:

```
metaflac --remove-tag MUSICBRAINZ_ALBUMTYPE *.flac
metaflac --remove-tag RELEASETYPE *.flac
```

I ran an update

```
$ beet update   
Trivium - Shogun - Kirisute Gomen
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Torn Between Scylla and Charybdis
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Down From the Sky
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Into the Mouth of Hell We March
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Throes of Perdition
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Insurrection
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - The Calamity
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - He Who Spawned the Furies
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Of Prometheus and the Crucifix
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Like Callisto to a Star in Heaven
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Shogun
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Poison, the Knife or the Noose
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Upon the Shores
  albumtype: album -> 
  albumtypes: album -> []
Trivium - Shogun - Iron Maiden
  albumtype: album -> 
  albumtypes: album -> []
```

I added the tag back with a proper value

```
metaflac --set-tag MUSICBRAINZ_ALBUMTYPE=album *.flac
metaflac --set-tag RELEASETYPE=album *.flac
```

And I ran update for the last time

```
$ beet update   
Trivium - Shogun - Kirisute Gomen
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Torn Between Scylla and Charybdis
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Down From the Sky
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Into the Mouth of Hell We March
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Throes of Perdition
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Insurrection
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - The Calamity
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - He Who Spawned the Furies
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Of Prometheus and the Crucifix
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Like Callisto to a Star in Heaven
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Shogun
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Poison, the Knife or the Noose
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Upon the Shores
  albumtype:  -> album
  albumtypes: [] -> ['album']
Trivium - Shogun - Iron Maiden
  albumtype:  -> album
  albumtypes: [] -> ['album']
```

I'm not sure I get it right, but it seems that the error comes from the tag in the FLAC file. `beet` sees, for example `MUSICBRAINZ_ALBUMTYPE`, mutliple times (once for each letter) than builds its own values for the database (`~/Music/.beet/BeetMusicLibrary.blb`)

At this point I will check every single file to make sure tags `MUSICBRAINZ_ALBUMTYPE` and `RELEASETYPE` are properly set. By properly set I mean to have a real value (e.g. album, live) and not a single character.
