### ISSUE TITLE
Album Disambiguation not Working

### ISSUE THREAD

**Issue by scolby33** [beetbox/beets#4576]
Beets is not recognizing an album that should be disambiguated.

### Problem

I have already imported albums 1 (link below). When I try to import album 2, despite having a `disambiguation` configuration key and `%aunique{}` in the paths, Beets thinks that I am importing a duplicate.

The output of `beet list` for the first album shows that the disambiguation fields (albumartist and album) match what the tagger found for the second album:
```console
> beet list -a 'mb_albumid:f039a0c9-5ae8-4150-8cb2-70dc1397b763'
Stephen Sondheim - Into the Woods
```

Maybe there's something going on with Unicode or invisible characters that causes the duplicate detection to kick in but not `%aunique{}`? I'm not sure how to debug that though.

Also, this is the first import I've done with this config that requires disambiguation. Have I messed up the config?

How do I get Beets to recognize these albums as separate?

Here are links to the releases that trigger the bug:
1. https://musicbrainz.org/release/f039a0c9-5ae8-4150-8cb2-70dc1397b763
2. https://musicbrainz.org/release/66864391-a433-4cdf-8fcf-f28604522c90

Running this command in verbose (`-vv`) mode shows the problem:

```console
> beet --plugins= -vv import .\importtemp\ --timid --search-id '66864391-a433-4cdf-8fcf-f28604522c90'
user configuration: C:\Users\Scott\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Scott\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: D:\incrementalbeets.db
library directory: D:\incrementalbeets
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: D:\importtemp; D:\importtemp\Stephen Sondheim - Into the Woods (disc 1 of 2); D:\importtemp\Stephen Sondheim - Into the Woods (disc 2 of 2)
Tagging Stephen Sondheim - Into the Woods
Searching for album ID: 66864391-a433-4cdf-8fcf-f28604522c90
Requesting MusicBrainz release 66864391-a433-4cdf-8fcf-f28604522c90
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Stephen Sondheim - Into the Woods (66864391-a433-4cdf-8fcf-f28604522c90)
Computing track assignment...
...done.
Success. Distance: 0.00
Evaluating 1 candidates.

D:\importtemp
D:\importtemp\Stephen Sondheim - Into the Woods (disc 1 of 2)
D:\importtemp\Stephen Sondheim - Into the Woods (disc 2 of 2) (50 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
Tagging:
    Stephen Sondheim - Into the Woods
URL:
    https://musicbrainz.org/release/66864391-a433-4cdf-8fcf-f28604522c90
(Similarity: 100.0%) (2xCD, 2014, US, Walt Disney Records, D002076392, 2-disc deluxe edition soundtrack)
CD 1
CD 2
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
Sending event: import_task_choice
found duplicates: [63]
default action for duplicates: a
This album is already in the library!
Old: 22 items, FLAC, 719kbps, 44.1kHz/16 bit, 76:26, 394.8 MiB
New: 50 items, FLAC, 595kbps, 44.1kHz/16 bit, 97:31, 435.2 MiB
[S]kip new, Keep all, Remove old, Merge all? Traceback (most recent call last): ^C
```

### Setup

* OS: Windows 10
* Python version: 3.10.3
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
library: D:\incrementalbeets.db
directory: D:\incrementalbeets

plugins: embedart inline convert
art_filename: $albumartist - $album%aunique{}
per_disc_numbering: yes

aunique:
    keys: albumartist album
    disambiguators: albumdisambig releasegroupdisambig albumtype year label catalognum
    bracket: '[]'

ui:
    color: no

import:
    bell: yes

paths:
    default: $albumartist - $album%aunique{}%if{$multidisc, (disc $disc of $disctotal)}/$track $title
    comp: Compilations/$album%aunique{}%if{$multidisc, (disc $disc of $disctotal)}/$track $title
    singleton: Non-Album/$artist/$title
embedart:
    auto: no
    ifempty: yes
    maxwidth: 0
    compare_threshold: 0
    remove_art_file: no
    quality: 0
item_fields:
    multidisc: 1 if disctotal > 1 else 0
convert:
    dest: D:\incrementalalac
    embed: yes
    never_convert_lossy_files: yes
    format: alac
    formats:
        alac:
            command: C:/Users/Scott/Applications/ffmpeg/bin/ffmpeg -i $source -y -c:v copy -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    pretend: no
    link: no
    hardlink: no
    threads: 12
    id3v23: inherit
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no

    paths: {}
    no_convert: ''
    copy_album_art: no
    album_art_maxwidth: 0
    delete_originals: no
pathfields: {}
album_fields: {}
```
