### ISSUE TITLE
lastfm source is broken on fetchart plugin 

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [beetbox/beets#4587]
### Problem

```sh
fetchart:
    auto: yes
    sources: lastfm
    lastfm_key: redacted
```

is giving me no results for any query that I give the plugin. For instance:

```
beet -vv fetchart "the strokes"
user configuration: /Users/redacted/.config/beets/config.yaml
data directory: /Users/redacted/.config/beets
plugin paths: 
artresizer: method is ImageMagick
Sending event: pluginload
library database: /Users/redacted/.config/beets/library.db
library directory: /Users/redacted/Music
Sending event: library_opened
fetchart: trying source lastfm for album The Strokes - 12:51
fetchart: The Strokes - 12:51: no art found
fetchart: trying source lastfm for album The Strokes - Angles
fetchart: The Strokes - Angles: no art found
fetchart: trying source lastfm for album The Strokes - Comedown Machine
fetchart: The Strokes - Comedown Machine: no art found
fetchart: trying source lastfm for album The Strokes - Covers, Demos, B-Sides & Unreleased
fetchart: The Strokes - Covers, Demos, B-Sides & Unreleased: no art found
fetchart: trying source lastfm for album The Strokes - Elephant Song
fetchart: The Strokes - Elephant Song: no art found
fetchart: trying source lastfm for album The Strokes - Exclusive 5 Track CD
fetchart: The Strokes - Exclusive 5 Track CD: no art found
fetchart: trying source lastfm for album The Strokes - First Impressions of Earth
fetchart: The Strokes - First Impressions of Earth: no art found
fetchart: trying source lastfm for album The Strokes - Future Present Past
fetchart: The Strokes - Future Present Past: no art found
fetchart: trying source lastfm for album The Strokes - Heart in a Cage
fetchart: The Strokes - Heart in a Cage: no art found
fetchart: trying source lastfm for album The Strokes - Is This It
fetchart: The Strokes - Is This It: no art found
fetchart: trying source lastfm for album The Strokes - Juicebox
fetchart: The Strokes - Juicebox: no art found
fetchart: trying source lastfm for album The Strokes - Live In Iceland
fetchart: The Strokes - Live In Iceland: no art found
fetchart: trying source lastfm for album The Strokes - Reptilia
fetchart: The Strokes - Reptilia: no art found
fetchart: trying source lastfm for album The Strokes - Room on Fire
fetchart: The Strokes - Room on Fire: no art found
fetchart: trying source lastfm for album The Strokes - Someday
fetchart: The Strokes - Someday: no art found
fetchart: trying source lastfm for album The Strokes - The New Abnormal
fetchart: The Strokes - The New Abnormal: no art found
fetchart: trying source lastfm for album The Strokes - You Only Live Once
fetchart: The Strokes - You Only Live Once: no art found
```

### Setup

* OS:  10.13.6
* Python version: 3
* beets version: 1.6.1

My configuration (output of `beet config`) is:

```yaml
plugins: embedart fetchart lyrics
autotag: yes
ignore_hidden: yes
original_date: yes
languages: en
va_name: Compilation
import:
    copy: no
    write: yes
    move: no
convert:
    tmpdir: /Volumes/Expansion-1/Media/Audio/
    auto: yes
    delete_originals: no
    no_convert: path::\.(m4a)$
    command: ffmpeg -y -i $source -vsync 0 -q:a 0 -map_metadata 0 $dest
    extension: m4a
discogs:
    user_token: redacted
fetchart:
    auto: yes
    sources: lastfm
    lastfm_key: redacted
embedart: 
    auto: yes
    maxwidth: 1000
    remove_art_file: yes
lyrics:
    auto: yes
    force: yes
    sources: musixmatch
    fallback: ''
    import.write: yes
zero:
    auto: yes
    update_database: true
    keep_fields: 
    - artist
    - title
    - album
    - year
    - albumartist
    - track
    - tracktotal
    - disc
    - disctotal
    - label
    - unsyncedlyrics
    - images
    - rating
    - first played
    - last played
    - play count
```
