### ISSUE TITLE
required_media

### ISSUE THREAD

**Issue by Emporea** [beetbox/beets#4607]
Additionally to [ignored_media](https://beets.readthedocs.io/en/stable/reference/config.html#id110)
```
match:
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD',
                    'VCD', 'SVCD', 'UMD', 'VHS']
```
and [preferred](https://beets.readthedocs.io/en/stable/reference/config.html#id107)
```
match:
    preferred:
        countries: ['US', 'GB|UK']
        media: ['CD', 'Digital Media|File']
        original_year: yes
```
i would propose a **required_media** something like this:
```
match:
    required_media: ['CD', 'Spotfiy']
```
---
This would only suggest "CD" or "Spotify" releases in this example, and ignore everything else.

In hope this option doesn't exists and I just wasn't able to find it in the documentation.
