### ISSUE TITLE
beet ls: format fields do not populate when the format string is enclosed in double-quotes

### ISSUE THREAD

**Issue by josephbertino** [beetbox/beets#4617]
### Problem

When running the `beet ls` command and printing a formatted string, the formatted field values (e.g. $album, $albumartist) do not populate with data when enclosing the formatted string in double-quotes.

Running this:
```
beet ls -a forever -f '$album  - $albumartist'
```

Led to this:
```
Forever - Changes Love
Forever - Pete Drake
Wu-Tang Forever - Wu-Tang Clan
```

**But running this**:
```
beet ls -a forever -f "$album - $albumartist"
```

Led to this:
```
 - 
 - 
 - 
```

### Setup

* OS: macOS 10.15.7
* Python version: 3.8.2
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:
```yaml
directory: ~/Documents/beet_lib
library: ~/Documents/beet_lib.db

import:
    copy: no
    move: no
    write: no
```
