### ISSUE TITLE
fetchart: Creates files with incorrect permissions

### ISSUE THREAD

**Issue by rsammelson** [beetbox/beets#4622]
On linux, running beet fetchart creates files with `600` permissions, rather than 644 (or using the default provided by umask).

### Setup

* OS: Debian 11
* Python version: 3.9.2
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): issue with plugin

My configuration (output of `beet config`) is:

```yaml
fetchart:                                           
    sources: filesystem coverart
    auto: yes                                       
    minwidth: 0                                     
    maxwidth: 0                                     
    quality: 0                                      
    max_filesize: 0                                 
    enforce_ratio: no                               
    cautious: no                                    
    cover_names:                                    
    - cover                                         
    - front                                         
    - art                                           
    - album                                         
    - folder                                        
    google_key: REDACTED                            
    google_engine: 001442825323518660753:hrh5ch1gjzm 
    fanarttv_key: REDACTED
    lastfm_key: REDACTED                            
    store_source: no                                
    high_resolution: no                             
    deinterlace: no                                 
    cover_format:
```
