### ISSUE TITLE
Converting with copying album artwork breaks if album artwork is missing

### ISSUE THREAD

**Issue by capital-G** [beetbox/beets#4692]
### Problem

Running this command in verbose (`-vv`) mode:

```shell
❯ beet -vv convert -a
user configuration: /Users/xxx/.config/beets/config.yaml
data directory: /Users/xxx/.config/beets
plugin paths:
/usr/local/lib/python3.10/site-packages/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
inline: adding item field multidisc
Sending event: pluginload
library database: /Users/xxx/Music/Archive/lib.db
library directory: /Users/xxx/Music/Archive
Sending event: library_opened
100 Gecs - 1000 Gecs And The Tree Of Clues
```

leads at some point to this uncaught exception

```shell
convert: Copying cover art from /Users/xxx/Music/Archive/DJ Healer/2019 - Nothing 2 Loose/Disc 01/cover.jpg to /Volumes/PLATTE/Convert/DJ Healer/2019 - Nothing 2 Loose/Disc 01/cover.jpg
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/beets/util/__init__.py", line 468, in copy
    shutil.copyfile(path, dest)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: b'/Users/xxx/Music/Archive/DJ Healer/2019 - Nothing 2 Loose/Disc 01/cover.jpg'
```

the folder structure looks like this - the `Disc 01` folder has indeed no `cover.jpg` but the root directory has.

```shell
❯ tree
.
└── 2019 - Nothing 2 Loose
    ├── Disc 01
    │   ├── 01 - At Last (Becalming the Storm).flac
    │   ├── 02 - Great Escape.flac
    │   └── 03 - 2 the Dark.flac
    ├── Disc 02
    │   ├── 04 - Gods Creation.flac
    │   ├── 05 - [untitled].flac
    │   ├── 06 - Planet Lonely.flac
    │   └── 07 - Hopes and Fears.flac
    ├── Disc 03
    │   ├── 08 - We Are Going Nowhere.flac
    │   ├── 09 - The Interview.flac
    │   ├── 10 - Gone.flac
    │   └── 11 - Protectionspell.flac
    └── cover.jpg

4 directories, 12 files
```

### Setup

* OS: macOS 12.6.1
* Python version: `Python 3.10.8`
* beets version: `beets version 1.6.0` with `plugins: bandcamp, convert, discogs, extrafiles, fetchart, inline`
* Turning off plugins made problem go away (yes/no): this is a bug of the convert plugin

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/Archive
library: ~/Music/Archive/lib.db
plugins: discogs fetchart extrafiles inline bandcamp convert

paths:
    default: $albumartist/$year - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    singleton: Non-Album/$year - $artist/$title
    comp: Compilations/$album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0

discogs:
   source_weight: 0.0

fetchart:
    cautious: true
    cover_names: front back
    sources:
    - filesystem
    - coverart: release
    - itunes
    - coverart: releasegroup
    - '*'

extrafiles:
    patterns:
        all: '*.*'

convert:
  copy_album_art: true
  auto: false
  dest: /Volumes/PLATTE/Convert
  never_convert_lossy_files: false
  copy_album_art: true
  embed: false
  format: opus
  formats:
    opus: ffmpeg -i $source -y -vn -acodec libopus -ab 120k $dest
```

### Suggestion

https://github.com/beetbox/beets/blob/d63bebb1131adc9ff2e1d2a7685057bde3e93d96/beetsplug/convert.py#L371-L377

Add an `os.path.isfile` check here or traverse the directory up in case if it is a multi cd directory.
