### ISSUE TITLE
Locales/languages for artist names do not work

### ISSUE THREAD

**Issue by mschuerig** [beetbox/beets#473]
My case: I want localized german or english names for artists. For that purpose, I have configured beets like this

In config.yml:

```
languages: de en

paths:
  default: %asciify{$albumartist/$album%aunique{}/$track.$title}
  singleton: %asciify{$artist/div/$title}
  comp: %asciify{Various_Artists/$album%aunique{}/$track.$title}
```

However, this does not result in the names I am expecting. In particular, it does not seem to work for the names of russian composers. For instance for this album 

http://musicbrainz.org/release/a1868755-9149-486f-9ac2-a2188d068cc5

The files are stored at a path more or less as intended

```
<path-to-music-dir>/Johannes_Brahms_Igor_Fiodorovich_Stravinskii_Hilary_Hahn_Academy_of_St_Martin_in_the_Fields_Sir_Neville_Marriner/Violin_Concertos
```

But the metadata is not localized

```
$ beet ls -f '$artist -- $albumartist' concerto hahn toccata
Игорь Фёдорович Стравинский -- Johannes Brahms, Игорь Фёдорович Стравинский; Hilary Hahn, Academy of St Martin in the Fields, Sir Neville Marriner
```

MusicBrainz does have localized data for this release and Picard would apply them when configured to use localized names.

For reference, see https://groups.google.com/forum/#!topic/beets-users/XnDBZTk-31c
