### ISSUE TITLE
badfiles: Respect "quiet" mode during import hook

### ISSUE THREAD

**Issue by simonmcnair** [beetbox/beets#4736]
Error:
```Sending event: import_task_before_choice
BAD one or more files failed checks:
/srv/dev-disk-by-uuid-342ac512-ae09-47a7-842f-d3158537d395/mnt/Audio/forbeets/Albums/aaa/bbb/Verified/flac/ccc.flac: checker exited with status 1
  bbb.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
  *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
  *** Got error code 1:FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
  *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
  bbb.flac: ERROR while decoding data
                 state = FLAC__STREAM_DECODER_ABORTED

What would you like to do?
a[B]ort, Skip, Continue?
```
command line:
```
/usr/local/bin/beet -vvv import /srv/dev-disk-by-uuid-342ac512-ae09-47a7-842f-d3158537d395/mnt/Audio/forbeets

```
Config
```
plugins: fetchart embedart convert scrub replaygain lastgenre chroma lyrics fromfilename info badfiles ftintitle inline duplicates hook albumtypes smartplaylist missing
directory: /srv/dev-disk-by-uuid-342ac512-ae09-47a7-842f-d3158537d395/mnt/Audio/sorted
library: /srv/dev-disk-by-uuid-342ac512-ae09-47a7-842f-d3158537d395/mnt/Audio/beetsmusiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: yes
ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
#paths:
#    default: $albumartist/$album%aunique{}/$disc-$track $title
#    default: $albumartist/$album%aunique{}/$track - $title
#    singleton: Non-Album/$artist - $title
#    comp: Compilations/$album%aunique{}/$track - $title
#    albumtype_soundtrack: Soundtracks/$album/$track $title

match:
    required: artist album
    max_rec:
        missing_tracks: strong
        unmatched_tracks: strong
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    ignored: missing_tracks unmatched_tracks
    strong_rec_thresh: 0.75    # Reflects the distance threshold below which beets will make a “strong recommendation” that the metadata be used.
                             # Strong recommendations are accepted automatically (except in “timid” mode),
                             # so you can use this to make beets ask your opinion more or less often.
                             # The threshold is a distance value between 0.0 and 1.0, so you can think of it as the opposite of a similarity value.
                             # For example, if you want to automatically accept any matches above 90% similarity, use: "strong_rec_thresh: 0.10"
                             # The default strong recommendation threshold is 0.04.
                             # When a match is below the medium recommendation threshold
                             # or the distance between it and the next-best match is above the gap threshold,
                             # the importer will suggest that match but not automatically confirm it.
                             # Otherwise, you’ll see a list of options to choose from.

    medium_rec_thresh: 0.125   # The medium_rec_thresh and rec_gap_thresh options work similarly.
paths:
    default: Albums/$albumartist/[$year]$atypes $album/$disc-$track $title
    albumtype:soundtrack: Various Artists/$album [$year]$atypes/$disc-$track $title
    comp: Various Artists/$album [$year]$atypes/$disc-$track $title
    singleton: Non-Album/$artist - $title
import:
    write: yes
    copy: no
    move: yes
    resume: yes
    incremental: yes
#    incremental: no
    quiet_fallback: skip
    timid: no
    log:  /srv/dev-disk-by-uuid-342ac512-ae09-47a7-842f-d3158537d395/mnt/Audio/beet.log
#    quiet: no
    quiet: yes
    none_rec_action: skip
    default_action: apply
    duplicate_action: keep
    group_albums: yes
duplicates:
    move:   /srv/dev-disk-by-uuid-342ac512-ae09-47a7-842f-d3158537d395/mnt/Audio/Dupes/
    checksum: ffmpeg -i {file} -f crc -
    count: yes
#    checksum: ''
item_fields:
    multidisc: 1 if disctotal > 1 else 0
    decade: str(year)[0:3]+"0s"
lastgenre:
    auto: yes
    source: album
embedart:
    auto: yes
fetchart:
    auto: yes
replaygain:
    auto: no
scrub:
    auto: yes
replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''
albumtypes:
    types:
        - ep: 'EP'
        - single: 'Single'
        - soundtrack: 'OST'
        - live: 'Live'
        - compilation: 'Anthology'
        - remix: 'Remix'
        - album: 'LP'
    ignore_va: compilation
    bracket: '[]'
badfiles:
    check_on_import: yes
    mp3: mp3val
    flac: flac --test --warnings-as-errors --silent
    m4a: ffprobe -v error
lyrics:
    auto: yes
```
