### ISSUE TITLE
Beet Listing Non-existent Albums

### ISSUE THREAD

**Issue by Quantalabs** [beetbox/beets#4766]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv ls -a Various Artists -f '$path $album'
user configuration: C:\Users\..\AppData\Roaming\beets\config.yaml
data directory: C:\Users\..\AppData\Roaming\beets
plugin paths:
lyrics: Disabling google source: no API key configured.
Sending event: pluginload
library database: C:\Users\..\Documents\Music\Beets\musiclibrary.db
library directory: C:\Users\..\Music\music for moto
Sending event: library_opened
'C:\Users\..\Music\music for moto' I Won't
'C:\Users\..\Music\music for moto\Compilations\One Night in Miami… Original Motion Picture Soundtrack' One Night in Miami… Original Motion Picture Soundtrack
Sending event: cli_exit

$ beet -vv rm -a Various Artists - I Won't
user configuration: C:\Users\..\AppData\Roaming\beets\config.yaml
data directory: C:\Users\..\AppData\Roaming\beets
plugin paths:
lyrics: Disabling google source: no API key configured.
Sending event: pluginload
library database: C:\Users\..\Documents\Music\Beets\musiclibrary.db
library directory: C:\Users\..\Music\music for moto
Sending event: library_opened
error: No matching albums found.
```

Led to this problem:

```
error: No matching albums found.
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Windows 10 
* Python version: Python 3.9.16
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    sources:
    - google
    - musixmatch
    - genius
    - tekstowo
directory: ~/Music/music for moto
library: ~/Documents/Music/Beets/musiclibrary.db

import:
    move: yes

plugins: fetchart lyrics lastgenre missing

paths:
    default: Albums/$artist/$album%aunique{}/$track $title
    singleton: Singles/$title
    comp: Compilations/$album%aunique{}/$track $title
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
missing:
    count: no
    total: no
    album: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
```
