### ISSUE TITLE
Beets convert plugin crashes on import

### ISSUE THREAD

**Issue by Kaduo** [beetbox/beets#4837]
### Problem

Running `beet import` with the convert plugin enabled leads to a series of successful conversions ending in a crash looking like this:

```
error: convert: couldn't invoke 'ffmpeg -i /music/somesong.flac -y -vn -aq 2 /home/me/.tmp/tmpcidf9osv.mp3': [Errno 11] Resource temporarily unavailable
```

### Setup

* OS:  Gentoo Linux
* Python version: 3.10.12
* beets version: 1.6.1
* Turning off plugins made problem go away (yes/no): no, except for the convert plugin obviously

My configuration (output of `beet config`) is:

```yaml

import:
    copy: yes
    write: yes
    incremental: yes

plugins:
    replaygain: yes
    convert: yes
replaygain:
    backend: ffmpeg
    overwrite: no
    auto: yes
    threads: 72
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
convert:
    auto: yes
    threads: 1
    dest:
    pretend: no
    link: no
    hardlink: no
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate:
    auto_keep: no
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
    delete_originals: no
    playlist:
```
