### ISSUE TITLE
Consider adding filename extensions to tracks without one

### ISSUE THREAD

**Issue by oalbiez** [beetbox/beets#4881]
I try to import an album called 'The New Complete Edition' (https://musicbrainz.org/release/06b914aa-f4d5-49bd-9df1-0b89b046ab16). It's a huge album with 3335 tracks. 

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import -m --flat Mozart-Complete/
```

Led to this problem:

At the end, some track title are very long and the resulting filename are truncated and loose the extension (.flac). For example the track 3320 has the '.flac', but not the 3319.

```
Wolfgang Amadeus Mozart/The New Complete Edition/3157 - Harmoniemusik_ Die Entfuhrung aus dem Serail K. 384 (for Wind Band)_ 14. Ich baue ganz auf deine Starke. ich baue ganz auf deine␣
Wolfgang Amadeus Mozart/The New Complete Edition/3319 - Aria _Ehi sor paggio... Non piu andrai_, K. 492.10)) - act 2 - ''ehi, sor paggio; non p
Wolfgang Amadeus Mozart/The New Complete Edition/3320 - Offertory _Scande coeli limina_ in C, K. 34_ 1. Scande coeli limina.flac
```

And sometimes the file name ends with a space, like the track 3157.

How can the filename be properly truncated without loosing the extension ?

track 3157: https://musicbrainz.org/track/7f3c9c80-9253-467c-a7cb-fcbef5f50527
track 3319: https://musicbrainz.org/track/db2122e4-bde6-4146-b95b-51a9cdeab63a
track 3320: https://musicbrainz.org/track/c3be48fc-a65d-4e15-a155-6baca6fbcd12

### Setup

* OS: Debian GNU/Linux 12 (bookworm) 
* beets version 1.6.0
* Python version 3.11.2
* plugins: badfiles, bucket, chroma, discogs, duplicates, fetchart, fromfilename, fuzzy, lastgenre, missing, the, thumbnails

My configuration (output of `beet config`) is:

```yaml
library: library.db
directory: ~/Musics

max_filename_length: 200

asciify_paths: yes

import:
    write: yes
    copy: yes
    bell: yes
    languages: fr en us

paths:
    default: Album/%bucket{$albumartist}/$albumartist/$album%aunique{}/$track - %left{$title,150}
    singleton: Non-Album/$artist/%left($title, 150}
    comp: Compilations/$album%aunique{}/$track - %left{$title, 150}

match:
    preferred:
        countries: ['FR', 'US', 'GB|UK']
        media: ['CD', 'Digital Media|File', 'DVD', 'Blu-ray']
        original_year: yes

plugins: 
  # autotaggers
  - discogs
  - chroma
  - fromfilename
  # metadata
  - fetchart
  - lastgenre
  # paths
  - the
  - bucket
  # other
  - missing
  - fuzzy
  - duplicates
  - badfiles
  - thumbnails

  #- replaygain
  #- lyrics

bucket:
    bucket_alpha: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'X', 'Y', 'Z']

fuzzy:
  threshold: 0.6

fetchart:
    cover_names: cover front art album folder back

badfiles:
    commands:
        ogg: oggz-validate -p
        flac: flac --test --warnings-as-errors --silent
```
