### ISSUE TITLE
WavPack tags

### ISSUE THREAD

**Issue by 888B8888** [beetbox/beets#4902]
### Problem

Looking at the file properties in foobar2000, I get some strange tags

1. Album Artist field repeats 3 times (e.g. Black Sabbath; Black Sabbath; Black Sabbath)
2. Date field gets year and full date (e.g. 1971; 1971-07-21)

```sh
beet info '/mnt/1tb/music/beets/non-classical/B/Black Sabbath/Album/1971-07-21 — Master of Reality/01 Sweet Leaf.wv'                  
/mnt/1tb/music/beets/non-classical/B/Black Sabbath/Album/1971-07-21 — Master of Reality/01 Sweet Leaf.wv
           album: Master of Reality
     albumartist: Black Sabbath
       albumtype: album
      albumtypes: album
             art: False
          artist: Black Sabbath
        bitdepth: 1
         bitrate: 2639299
    bitrate_mode: 
        channels: 2
            comp: False
        composer: Geezer Butler, Tony Iommi, Ozzy Osbourne, Bill Ward
            date: 1971-07-21
             day: 21
            disc: 1
       disctitle: 
       disctotal: 1
    encoder_info: 
encoder_settings: 
          format: WavPack
          length: 303.7733333333333
           media: SHM-SACD
           month: 7
   rg_album_gain: 2.11
   rg_album_peak: 0.638611
   rg_track_gain: 1.3
   rg_track_peak: 0.593475
      samplerate: 352800
           title: Sweet Leaf
           track: 1
      tracktotal: 8
            year: 1971
```
### Setup

* OS: Linux
* Python version: 3.11.5
* beets version: 1.6.1 (latest source)

My configuration (output of `beet config`) is:

```yaml
beet config   
directory: /mnt/1tb/music/beets

import:
    bell: yes
    duplicate_keys:
        album: albumartist album year
        item: artist title year
        languages: en eng
format_album: "$albumartist \u2014 $year%if{$month,-$month}%if{$day,-$day} \u2014 $album"

format_item: "$artist \u2014 $album \u2014 $title"
original_date: yes

sort_album: albumartist+ year+ month+ day+ album+

paths:
    genre::'(^|[^\w]\s)Classical([,]|$)': "classical/%first{$albumartist_sort}/$year%if{$month,-$month}%if{$day,-$day} \u2014 $album/$track $title"
    default: "non-classical/%upper{%left{%the{$albumartist},1}}/$albumartist/Album/$year%if{$month,-$month}%if{$day,-$day} \u2014 $album/$track $title"
    singleton: "non-album/$artist \u2014 $title"
    comp: "non-classical/%upper{%left{%the{$albumartist},1}}/$albumartist/Compilation/$year%if{$month,-$month}%if{$day,-$day} \u2014 $album/$track $title"
    albumtypes:compilation: "non-classical/%upper{%left{%the{$albumartist},1}}/$albumartist/Compilation/$year%if{$month,-$month}%if{$day,-$day} \u2014 $album/$track $title"
    albumtypes:ep: "non-classical/%upper{%left{%the{$albumartist},1}}/$albumartist/EP/$year%if{$month,-$month}%if{$day,-$day} \u2014 $album/$track $title"
    albumtypes:live: "non-classical/%upper{%left{%the{$albumartist},1}}/$albumartist/Live/$year%if{$month,-$month}%if{$day,-$day} \u2014 $album/$track $title"
    albumtypes:single: "non-classical/%upper{%left{%the{$albumartist},1}}/$albumartist/Single/$year%if{$month,-$month}%if{$day,-$day} \u2014 $album/%if{$track,$track} $title"
    albumtypes:soundtrack: "non-classical/%upper{%left{%the{$albumartist},1}}/$albumartist/Soundtrack/$year%if{$month,-$month}%if{$day,-$day} \u2014 $album/$track $title"

plugins: copyartifacts chroma convert deezer discogs duplicates edit embedart fetchart fromfilename ftintitle info lastgenre loadext mbsync parentwork play random rewrite scrub smartplaylist the zero
chroma:
    auto: yes
convert:
    auto: no
    copy_album_art: yes
    no_convert: path::\.(m4a|mp3|opus)$
    format: aac
    formats:
        aac:
            command: convert-to-aac $source $dest
            extension: m4a
        opus:
            command: opusenc --bitrate 128 $source $dest
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    dest: /mnt/1tb/music/converted/beets
    embed: no
    pretend: no
    link: no
    hardlink: no
    threads: 4
    id3v23: inherit
    max_bitrate:
    auto_keep: no
    tmpdir:
    quiet: no

    paths: {}
    never_convert_lossy_files: no
    album_art_maxwidth: 0
    delete_originals: no
    playlist:
copyartifacts:
    print_ignored: yes
    extensions: .*
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    separator: ', '
    index_tracks: no
    append_style_genre: no
edit:
    itemfields: track title artist album genre
    albumfields: year day month albumartist album genre
    ignore_fields: id path
embedart:
    auto: no
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
fetchart:
    auto: yes
    minwidth: 200
    sources:
    - filesystem
    - fanarttv
    - itunes
    -   coverart: releasegroup
    - lastfm
    - '*'
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: yes
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
ftintitle:
    format: (feat. {0})
    auto: yes
    drop: no
lastgenre:
    auto: yes
    canonical: no
    count: 2
    fallback: ''
    prefer_specific: no
    whitelist: ~/.config/beets/genres.txt
    min_weight: 10
    source: album
    force: yes
    separator: ', '
    title_case: yes
loadext: [libicu]
play:
    command: mpv
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
    bom: no
rewrite:
    albumtype .*compilation.*: compilation
    albumtype Album.*: album
    albumtype LP.*: album
    albumtype MP3, Album: album
    "artist .*\u0448\u0430 \u0437\u0430\u043A\u043E\u043D.*": "\u041B\u0451\u0448\u0430 \u0417\u0430\u043A\u043E\u043D"
    "artist \u0410\u0443\u043A\u0446\u044B\u043E\u043D": "\u0410\u0443\u043A\u0446\u042B\u043E\u043D"
    "artist \u0413\u0440\u0430\u0436\u0434\u0430\u043D\u0441\u043A\u0430\u044F \u041E\u0431\u043E\u0440\u043E\u043D\u0430": "\u0413\u0440\u0430\u0436\u0434\u0430\u043D\u0441\u043A\u0430\u044F \u043E\u0431\u043E\u0440\u043E\u043D\u0430"
    "artist \u0418\u043D\u0441\u0442\u0440\u0443\u043A\u0446\u0438\u044F \u041F\u043E \u0412\u044B\u0436\u0438\u0432\u0430\u043D\u0438\u044E": "\u0418\u043D\u0441\u0442\u0440\u0443\u043A\u0446\u0438\u044F \u043F\u043E \u0432\u044B\u0436\u0438\u0432\u0430\u043D\u0438\u044E"
    "artist \u041F\u0442\u0438\u0446\u0443 \u0435\u043C\u044A": "\u041F\u0442\u0438\u0446\u0443 \u0415\u041C\u042A"
    "artist \u0421\u0442\u0443\u043A \u0411\u0430\u043C\u0431\u0443\u043A\u0430 \u0412 XI \u0427\u0430\u0441\u043E\u0432": "\u0421\u0442\u0443\u043A \u0431\u0430\u043C\u0431\u0443\u043A\u0430 \u0432 XI \u0447\u0430\u0441\u043E\u0432"
    "artist \u4E2D\u68EE\u660E\u83DC": Akina Nakamori
    "artist \u5927\u7027\u8A60\u4E00": Eiichi Ohtaki
    "artist \u674F\u91CC": Anri
    "artist \u76F8\u6CA2\u85AB": Kaoru Aizawa
    "artist \u79CB\u5143\u85AB": Kaoru Akimoto
    "artist \u9ED2\u6CA2\u5F8B\u5B50": Ritsuko Kurosawa
    "artist \uC774\uC815\uD604": Lee Jung Hyun
scrub:
    auto: no
smartplaylist:
    playlist_dir: /mnt/1tb/music/playlists
    playlists: [{name: Atmospheric Black Metal.m3u, query: 'genre:"atmospheric black metal" length:1:30..'}, {name: 'City Pop, J-Pop.m3u', query: ['genre:"city pop" length:1:30.. year:..1999', 'genre:"j-pop" length:1:30.. year:..1999', '"miho nakayama"']}]
    relative_to:
    auto: yes
    forward_slash: no
    prefix: REDACTED
    urlencode: no
    pretend_paths: no
zero:
    auto: yes
    keep_fields: album albumartist albumtype albumtypes artist comp composer day disc disctitle disctotal genre language media month rg_album_gain rg_album_peak rg_track_gain rg_track_peak singleton title track tracktotal year
    update_database: no
    fields: []
parentwork:
    auto: no
    force: no
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
deezer:
    source_weight: 0.5

```
