### ISSUE TITLE
readthedocs config deprecation

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4912]
https://blog.readthedocs.com/migrate-configuration-v2/

We should take care of it really soon, due date Sep, 25th!

**Comment by JOJ0** [comment]
This is what worked for us in another project. Might help. The very last lines were important to have RTD really build the package to be documented which is a prerequisite for sphinx-autodoc:

```
cat .readthedocs.yaml 
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: ./rtd_requirements.txt
    - method: pip
      path: .

```
