### ISSUE TITLE
Sidebar scrolling in docs not working and general adjustment ideas

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4916]
I was too lazy for a PR but I a quickfixed the sidebar in Alabaster. It did not stay "in place" like we had it before. More adjustments might come in proper PR.

**_~Well, the fix does not work in master but it does work on my local docs build!~_**

Update: Actually the sidebar scrolling did work, probably there was some caching issue with my local browser, so that is [x] DONE

Anyway, we should take care of docs build and customization. Some ideas:

- Explicitely state Alabaster as the theme to use.
- Set the pic we have for the beetbox organization as the logo in the docs. (Or do we have a logo or does someone want to design one?
- Default to "latest" version of the docs
- ...I might add some more ideas here...

Might be related: https://github.com/beetbox/beets/issues/4912

_Originally posted by @JOJ0 in https://github.com/beetbox/beets/issues/4644#issuecomment-1728881928_

**Comment by JOJ0** [comment]
This is what worked for us in another project. Might help. The very last lines were important to have RTD really build the package to be documented which is a prerequisite for sphinx-autodoc:

```
cat .readthedocs.yaml 
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: ./rtd_requirements.txt
    - method: pip
      path: .

```
