### ISSUE TITLE
Auto import asks questions

### ISSUE THREAD

**Issue by DavidHenryThoreau** [beetbox/beets#4957]
I'd like to auto import album , i've set `quiet: yes` but still ask questions

here's config.yaml
```
directory: ~/music
                                                                                 
import :                                                                         
  move: yes                                                                      
  write: yes                                                                     
  resume: yes                                                                    
  default_action: apply                                                          
  autotag: yes                                                                   
  delete: no
  detail: yes  
  quiet: yes                                                                  
                                                                                 
art_filename: pochette                                                           
                                                                                 
threaded: yes                                                                    
                                                                                 
original_date: no                                                                
                                                                                 
paths:
  default: $albumartist/$album/$track %title{$title}
  comp: $albumartist/$album/$track %title{$title}
  albumtype:compilation: $albumartist/$album/$track %title{$title}
                                                                                 
replace:                                                                         
  ' ': _                                                                         
                                                                                 
match:                                                                           
  strong_rec_thresh: 0.40                                                        
  medium_rec_thresh: 0.40                                                        
  preferred:
    original_year: yes
                                                                                 
plugins: acousticbrainz chroma fetchart embedart zero lastgenre ftintitle   
                                                                                 
acousticbrainz:                                                                  
  auto: yes                                                                      
                                                                                 
chroma:                                                                          
  auto: yes                                                                      
                                                                                 
fetchart:                                                                        
  auto: yes                                                                      
  cover_names: cover front album art folder                                      
                                                                                 
embedart:                                                                        
  auto: yes                                                                      
  remove_art_file: no
  ifempty: yes
                                                                                 
zero:                                                                            
  fields: month day                                                              
                                                                                 
lastgenre:                                                                       
  auto: yes                                                                      

ftintitle:
  auto: yes
```

Here's the output : 

```
beet --verbose import /data/
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
chroma: acoustid album candidates: 1
Sending event: albuminfo_received
Candidate: xxxxxxxx (987e59b6-cc68-4f66-ab62-7274f2d09650)
Computing track assignment...
...done.
Success. Distance: 0.51
Evaluating 1 candidates.

/data/encode/audio/FOLDER (4 items)
Sending event: import_task_before_choice
Skipping.
Sending event: import_task_choice
Sending event: import
Sending event: cli_exit
```

**Comment by arsaboo** [comment]
It doesn't look like it is asking for input. It skipped import since the distance was 0.51. 

Can you remove the `--verbose` part and show what input it is asking?

**Comment by DavidHenryThoreau** [comment]
```
beet import /data/audio/

/data/audio/DIR (4 items)
Skipping.
```

**Comment by arsaboo** [comment]
I still don't see a problem. I did not see any prompt for user input there...isn't that what you wanted?

**Comment by DavidHenryThoreau** [comment]
Skipping so nothing was imported to the directory `directory: ~/music`

**Comment by arsaboo** [comment]
Yes, it's skipping because the distance is 0.51, i.e., it's a poor match.

**Comment by DavidHenryThoreau** [comment]
Right I've change match to test  :  

```
match:                                                                           
  strong_rec_thresh: 0.91
  medium_rec_thresh: 0.91                                                        
  preferred:
    original_year: yes
```

It's working :+1:
