### ISSUE TITLE
Auto import & convert at the same time

### ISSUE THREAD

**Issue by DavidHenryThoreau** [beetbox/beets#4963]
I'd like to convert and import at the same time i'm using this config file 

```
directory: ~/Musique
                                                                                 
import :                                                                         
  move: yes                                                                      
  write: yes                                                                     
  resume: yes                                                                    
  default_action: apply                                                          
  autotag: yes                                                                   
  delete: no
  detail: yes                                                                    
  quiet: yes
  timid: no
                                                                                 
art_filename: pochette                                                           
                                                                                 
threaded: yes                                                                    
                                                                                 
original_date: no                                                                

match:                                                                           
  strong_rec_thresh: 0.91
  medium_rec_thresh: 0.91                                                        
  preferred:
    original_year: yes
                                                                                 
paths:
  default: $albumartist/$album/$track %title{$title}
  comp: $albumartist/$album/$track %title{$title}
  albumtype:compilation: $albumartist/$album/$track %title{$title}
                                                                                 
replace:                                                                         
  ' ': _                                                                         
                                                                                 
plugins: acousticbrainz chroma fetchart embedart zero lastgenre ftintitle convert
                                                                                 
acousticbrainz:                                                                  
  auto: yes                                                                      
                                                                                 
chroma:                                                                          
  auto: yes                                                                      
                                                                                 
fetchart:                                                                        
  auto: yes                                                                      
  cover_names: cover front album art folder                                      
                                                                                 
embedart:                                                                        
  auto: yes                                                                      
  remove_art_file: no
  ifempty: yes
                                                                                 
zero:                                                                            
  fields: month day                                                              
                                                                                 
lastgenre:                                                                       
  auto: yes                                                                      

ftintitle:
  auto: yes

convert:
  auto: yes
  max-bitrate: 128
  embed: yes
  delete_originals: yes
  dest: ~/Musique
  format: mp3
  formats:
    all:
      command: ffmpeg -i $source -ab 128k -map_metadata 0 $dest
      extension: mp3
```

During import 

```
beet convert Album
convert: Empty query result.
```

**Comment by arsaboo** [comment]
You are getting the sequence wrong. Beets can convert during import `beet import` should automatically convert based on your config during initial import. You use `beet convert` to convert after the album is already imported.

**Comment by DavidHenryThoreau** [comment]
If my mp3 are in 320k bitrate and I want to convert to 128k bitrate 

```
 
convert:
  auto: yes
  max-bitrate: 128
  embed: yes
  delete_originals: yes
  paths: .
  dest: ~/Musique
  format: mp3
  formats:
    all:
      command: ffmpeg -i $source -ab 128k -map_metadata 0 $dest
      extension: mp3
```
Skip the convert

**Comment by arsaboo** [comment]
Can you please provide verbose logs, beet -v...

**Comment by DavidHenryThoreau** [comment]
```
beet --verbose import zero-project_and_Athanasios_Lafazanidis_feat._Konstantina_Tsirimona_-_Pass_me_by.mp3
user configuration: /home/HD/.config/beets/config.yaml
data directory: /home/HD/.config/beets
plugin paths:
Sending event: pluginload
library database: /home/HD/.config/beets/library.db
library directory: /home/HD/Musique
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/HD/d/zero-project_and_Athanasios_Lafazanidis_feat._Konstantina_Tsirimona_-_Pass_me_by.mp3
Tagging zero-project -
No album ID found.
Search terms: zero-project -
Album might be VA: False
chroma: acoustid album candidates: 0
Evaluating 0 candidates.

/home/HD/d/zero-project_and_Athanasios_Lafazanidis_feat._Konstantina_Tsirimona_-_Pass_me_by.mp3 (1 items)
Sending event: import_task_before_choice
Skipping.
Sending event: import_task_choice
Sending event: import
Sending event: cli_exit
```

**Comment by arsaboo** [comment]
It doesn't look like anything is imported there. You need to point it to a folder for it to work. See [here](https://beets.readthedocs.io/en/stable/guides/tagger.html#overview).

**Comment by DavidHenryThoreau** [comment]
```
directory: ~/Musique
                                                                                 
import :                                                                         
  move: yes                                                                      
  write: yes                                                                     
  resume: yes                                                                    
  default_action: apply                                                          
  autotag: yes                                                                   
  delete: yes
  detail: yes                                                                    
  quiet: yes
  timid: no
                                                                                 
art_filename: pochette                                                           
                                                                                 
threaded: yes                                                                    
                                                                                 
original_date: no                                                                

match:                                                                           
  strong_rec_thresh: 0.91
  medium_rec_thresh: 0.91                                                        
  preferred:
    original_year: yes
                                                                                 
paths:
  default: $albumartist/$album/$track %title{$title}
  comp: $albumartist/$album/$track %title{$title}
  albumtype:compilation: $albumartist/$album/$track %title{$title}
                                                                                 
replace:                                                                         
  ' ': _                                                                         
                                                                                 
plugins: acousticbrainz chroma fetchart embedart zero lastgenre ftintitle convert
                                                                                 
acousticbrainz:                                                                  
  auto: yes                                                                      
                                                                                 
chroma:                                                                          
  auto: yes                                                                      
                                                                                 
fetchart:                                                                        
  auto: yes                                                                      
  cover_names: cover front album art folder                                      
                                                                                 
embedart:                                                                        
  auto: yes                                                                      
  remove_art_file: no
  ifempty: yes
                                                                                 
zero:                                                                            
  fields: month day                                                              
                                                                                 
lastgenre:                                                                       
  auto: yes                                                                      

ftintitle:
  auto: yes

convert:
    auto: yes
    max-bitrate: 128
    embed: yes
    delete_originals: yes
    paths: .
    dest: ~/Musique
    command: ffmpeg -i $source -ab 128k -map_metadata 0 $dest
    extension: mp3
```
I've set  `dest` `directory` and `path`
