### ISSUE TITLE
New Importer UI not showing track level changes when `import.detail: false`

### ISSUE THREAD

**Issue by InvisibleFunction** [beetbox/beets#4980]
I'm trying to import some hybrid SACDs and with the old UI it shows me changes that it's going to make to the tracks, but with the new UI it does not show them, but the changes are made.

### Problem

Older version:

```sh
me@compy:/Volumes/Music/ToImport/1988 - Four! - 1$ beet imp -t .

/Volumes/Music/ToImport/1988 - Four! - 1 (14 items)
No matching release found for 14 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort,
eDit? i
Enter release ID: https://musicbrainz.org/release/03f118d7-99bb-4daa-ad58-ab86d5325398
Correcting tags from:
    (unknown album)
To:
    Hampton Hawes with Barney Kessel, Shelly Manne & Red Mitchell - Four!
URL:
    https://musicbrainz.org/release/03f118d7-99bb-4daa-ad58-ab86d5325398
(Similarity: 68.1%) (tracks, album, artist, media, country) (2xHybrid SACD (CD layer), 2022, XW, Contemporary Records, CR00501, Contemporary Records Acoustic Sounds Series)
Hybrid SACD (CD layer) 1
 * - Yardbird Suite - Remastered 2021 (#1)                  -> Yardbird Suite (#1-1) (title)
 * - There Will Never Be Another You - Remastered 2021 (#2) -> There Will Never Be Another You (#1-2) (title)
 * - Bow Jest - Remastered 2021 (#3)                        -> Bow Jest (#1-3) (title)
 * - Sweet Sue - Remastered 2021 (#4)                       -> Sweet Sue (#1-4) (title)
 * - Up Blues - Remastered 2021 (#5)                        -> Up Blues (#1-5) (title)
 * - Like Someone In Love - Remastered 2021 (#6)            -> Like Someone in Love (#1-6) (title)
 * - Love Is Just Around The Corner - Remastered 2021 (#7)  -> Love Is Just Around the Corner (#1-7) (title)
Hybrid SACD (CD layer) 2
 * Yardbird Suite (#1-1)                                    -> Yardbird Suite (#2-1)
 * There Will Never Be Another You (#1-2)                   -> There Will Never Be Another You (#2-2)
 * Bow Jest (#1-3)                                          -> Bow Jest (#2-3)
 * Sweet Sue (#1-4)                                         -> Sweet Sue (#2-4)
 * Up Blues (#1-5)                                          -> Up Blues (#2-5)
 * Like Someone In Love (#1-6)                              -> Like Someone in Love (#2-6)
 * Love Is Around The Corner (#1-7)                         -> Love Is Just Around the Corner (#2-7) (title)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates?
```

New Version:

```sh
me@compy:/Volumes/Music/ToImport/1988 - Four! - 1$ beet imp -t .

/Volumes/Music/ToImport/1988 - Four! - 1 (14 items)
No matching release found for 14 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
➜ [S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort,
eDit? i
Enter release ID: https://musicbrainz.org/release/03f118d7-99bb-4daa-ad58-ab86d5325398

  Match (68.1%):
  Hampton Hawes with Barney Kessel, Shelly Manne & Red Mitchell - Four!
  ≠ tracks, album, artist, media, country
  MusicBrainz, 2xHybrid SACD (CD layer), 2022, XW, Contemporary Records, CR00501, Contemporary Records Acoustic Sounds Series
  https://musicbrainz.org/release/03f118d7-99bb-4daa-ad58-ab86d5325398
  ≠ Artist:  -> Hampton Hawes with Barney Kessel, Shelly Manne & Red Mitchell
  * Hybrid SACD (CD layer) 1
  * Hybrid SACD (CD layer) 2
➜ Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates?
```

In both cases it swaps all the disc 1 tracks to disc 2.

Here's a discussion where it was suggested that this might warrant a bug report: https://github.com/beetbox/beets/discussions/4976

### Setup

* OS: Mac 13.6
* Python version: 3.11.6
* beets version: 1.6.1 (git HEAD)
* Turning off plugins made problem go away (yes/no): haven't tried yet

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/Music
library: /Users/me/.config/beets/beetsMusic.db
plugins: fetchart inline info lastgenre edit
import:
  move: no
per_disc_numbering: yes
original_date: yes
item_fields:
  multidisc: 1 if disctotal > 1 else 0
paths:
  default: $albumartist/$album%aunique{}/%if{$multidisc,$disc-}$track $title
lastgenre:
  whitelist: /Users/me/.config/beets/genres.txt
  canonical: /Users/me/.config/beets/genres-tree.yaml
bandcamp:
  lyrics: true
  art: true
```
