### ISSUE TITLE
Can't get beets to add album metadata to my mixed-album files and move them to proper structure

### ISSUE THREAD

**Issue by kitesi** [beetbox/beets#5014]
### Problem

My music folder is structured as such: `~/Music/artist/song.m4a`. I am trying to move them into the form of `~/Music/artistalbum/album/song.m4a` All the songs have the proper artist and title metadata already, and when I try to import them, they are recognized properly, but they are not moved to the correct album folder, and the album metadata is not added. 

I understand that my Music folder is not structured the way beets assumes so, and as such I should use the `group_albums: yes` option, but when I do, I get this output:

```
No matching release found for 1 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort?
```

I then press [T]racks, and it finds it correctly, but nothing is updated.

```
/home/seven/Music/Alex G/Mary.m4a
Tagging track: Alex G - Mary
URL:
    https://musicbrainz.org/recording/62f06ba5-755a-45f3-9de7-0341b0e6ec7b
(Similarity: 100.0%)
```

If I manually set the album metadata it will then move it to the right directory, but I want beets to set the album metadata for me.

### Setup

* OS: Linux 5.15.0-89-generic Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Python version: 3.10.12
* beets version: 3.10.12
* Turning off plugins made problem go away (yes/no):  no

My configuration (config.yaml) is:

```yaml
directory: ~/Music

plugins: lastgenre fetchart embedart

lastgenre:
    count: 3

import:
    move: yes
    group_albums: yes

paths:
    default: $albumartist/$album%aunique{}/$title
    singleton: $artist/$title
    comp: Compilations/$album%aunique{}/$title
```

output of `beet config`:

```yaml
directory: ~/Music

plugins: lastgenre fetchart embedart
lastgenre:
    count: 3
    whitelist: yes
    min_weight: 10
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes

import:
    move: yes
    group_albums: yes

paths:
    default: $albumartist/$album%aunique{}/$title
    singleton: $artist/$title
    comp: Compilations/$album%aunique{}/$title
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
```
