### ISSUE TITLE
Folders left behind with .jpg file after moving files despite *.jpg in clutter

### ISSUE THREAD

**Issue by jdrewsteiner** [beetbox/beets#5016]
### Problem

Folders that are processed by beets (all music files are moved out of the folder) are not always being deleted. Often times they are left behind with only a single .jpg file remaining even though I have *.jpg added to my clutter list. 

### Setup

* OS: Synology DSM 7.2.1-69057 Update 3
* Python version: ?
* beets version: v1.6.0

My configuration (output of `beet config`) is:

plugins: fetchart embedart lastgenre inline ftintitle zero bucket duplicates web
# plexupdate

#- /volume1/data/torrents/incoming/music:/downloads
#- /volume1/data/media/music:/music
directory: /music/
library: /config/musiclibrary.blb 
art_filename: albumart
threaded: yes
original_date: yes
per_disc_numbering: yes

# If [x] and other non standard signs won't be printed correctly try some different values here
# https://docs.python.org/2/library/codecs.html#standard-encodings
terminal_encoding: utf-8
 
bucket:
  bucket_alpha:
    - "#-!"
    - "0-9"
    - "A"
    - "B"
    - "C"
    - "D"
    - "E"
    - "F"
    - "G"
    - "H"
    - "I"
    - "J"
    - "K"
    - "L"
    - "M"
    - "N"
    - "O"
    - "P"
    - "Q"
    - "R"
    - "S"
    - "T"
    - "U"
    - "V"
    - "W"
    - "X"
    - "Y"
    - "Z"
  bucket_alpha_regex:
    "#-!": ^[^a-zA-Z]
  bucket_year: []
  extrapolate: no

# Each line is a small python script which should return a string or an int
item_fields:
# 'Nine Inch Nails - ' or '' depending if the artist differs from the album artist
  mySongartist: artist + ' - ' if artist != albumartist and artist != '' else ''
 
# Release with multiple discs? For boolean operations
  isMultidisc: 1 if disctotal > 1 else 0
 
# Changes the case of the album type 
  myAlbumType: ('' if albumtype == '' else ' [' + ('EP' if albumtype == 'ep' else albumtype.capitalize()) + ']')
 
# '1 - ' or '' depending if there are multiple discs or not
  myDisc: ('' if disctotal <= 1 else str(disc) + ' - ')
  
# First Charachter of Artist
  #initial: albumartist[0].upper() if albumartist[0:4].lower() != 'the ' and albumartist[0].isalpha() else albumartist[4].upper() if albumartist[4].isalpha() and albumartist[0:4].lower() == 'the ' else "#"
  initial: albumartist[4].upper() if albumartist[0:4].lower() == 'the ' else albumartist[0].upper() 
#  initial:
#   if albumartist[0:4].lower() == 'the ':
#     albumartist[4].upper()
#   else:
#     albumartist[0].upper()

album_fields:
#  bitrate: |
#    if items[0].format.upper() == "MP3":
#      total = 0
#      for item in items:
#          total += item.bitrate
#      return total / len(items)
#    else: return items[0].format
  iscd: |
    return "CD" in items[0].media
  mediatype: |
    mediaList = {
      '12" Vinyl': "Vinyl",
      '7" Vinyl': "Vinyl",
      "Digital Media": "WEB",
    }
    try:
      return mediaList[items[0].media]
    except KeyError:
      return items[0].media
  bitdepthmost: |
    bitdepths = dict()
    for item in items:
      try:
        bitdepths[item.bitdepth] += 1
      except KeyError:
        bitdepths[item.bitdepth] = 1
    sorted_depths = {k: v for k, v in sorted(bitdepths.items(), key=lambda item: item[1])}
    return list(sorted_depths)[-1]
  sampleratemost: |
    samplerates = dict()
    for item in items:
      try:
        samplerates[item.samplerate] += 1
      except KeyError:
        samplerates[item.samplerate] = 1
    sorted_rates = {k: v for k, v in sorted(samplerates.items(), key=lambda item: item[1])}
    formatted_num = int(list(sorted_rates)[-1]/1000) if int(list(sorted_rates)[-1]/1000) == float(list(sorted_rates)[-1]/1000) else float(list(sorted_rates)[-1]/1000)
    return str(formatted_num) + "kHz"
  bettercatalognum: |
    return items[0].catalognum if items[0].catalognum != "[none]" else ""
  mp3_quality: |
    if items[0].format.upper() == "MP3":
      total_bitrate = 0
      for item in items:
        total_bitrate += item.bitrate
      average_bitrate = total_bitrate / len(items) / 1000
      if average_bitrate == 320:
        return "320"
      elif average_bitrate == 192:
        return "192"
      elif average_bitrate == 160:
        return "160"
      elif average_bitrate == 128:
        return "128"
      elif average_bitrate >= 200:
        return "V0"
      else:
        return "TOO LOW FIND NEW SOURCE"
    else: return items[0].format 

#paths:
#  default: %bucket{$albumartist,alpha}/$albumartist/($year) $album %if{$bettercatalognum, {$bettercatalognum$}} [%if{$iscd,$mediatype - $format,%if{$mediatype,$mediatype - }$format - %if{$bitdepth,$bitdepthmost,$mp3_quality} - $sampleratemost}]/$disc-$track - $title
#  singleton: -singles/%bucket{$artist,alpha}/$artist/$title ($year)%if{$bettercatalognum, {$bettercatalognum$}} [%if{$iscd,$mediatype - $format,%if{$mediatype,$mediatype - }$format - %if{$bitdepth,$bitdepthmost,$mp3_quality} - $sampleratemost}]/$title
#  comp: -compilations/VA - $album ($year)%if{$bettercatalognum, {$bettercatalognum$}} [%if{$iscd,$mediatype - $format,%if{$mediatype,$mediatype - }$format - %if{$bitdepth,$bitdepthmost,$mp3_quality} - $sampleratemost}]/$disc-$track. $artist - $title
  
paths:
# For the normal albums and eps. Used when none of the other paths should be used
# Interpreten/boysetsfire/(2000) After the Eulogy [Album]/02 - Rookie.flac
# Interpreten/Oliver Koletzki/(2019) We Are All Lost/1 - 02 - Oliver Koletzki; Monolink - We Are All Lost.flac
  #default: $initial/$albumartist/($year) $album%aunique{}$myAlbumType [$bitrate]/%if{$isMultidisc,$disc - }$track - $mySongartist$title
 # (last best) default: %bucket{$initial,alpha}/$albumartist/$albumartist - ($year) $album%aunique{}$myAlbumType [$mp3_quality]/%if{$isMultidisc,$disc - }$track - $mySongartist$title
  default: %bucket{$initial,alpha}/$albumartist/$albumartist - ($year) $album%aunique{}$myAlbumType [$mp3_quality]/%if{$isMultidisc,$disc - }$track - $mySongartist$title
  
  
# For individual tracks not part of an entire album. Used when 'singleton:true' is set 
  #singleton: -singles/$initial/$artist/$artist - $title
 
# For sampler and compilations. Used when 'comp:true' is set
# Compilations/Giegling/(2017) Planet Giegling/03 - Kettenkarussell - Walk With Me.flac
  comp: -compilations/VA - $album%aunique{} ($year)/%if{$isMultidisc,$disc - }$track $artist - $title
 
# For Soundtracks. Used when 'albumtype:soundtrack'
# Soundtracks/Trent Reznor & Atticus Ross/Watchmen_ Volume 1 (Music From the HBO Series) (2019)/04 - Trent Reznor & Atticus Ross - Nun With a Motherf_&_ing Gun.flac
  albumtype:soundtrack: -soundtracks/$albumartist/$album%aunique{} ($year)/%if{$isMultidisc,$disc - }$track $artist - $title
  
#  genre:classical: -classical/
        
import:
  write: yes
  copy: no
  move: yes
  autotag: yes
  resume: ask
  incremental: no
  quiet: no
  quiet_fallback: skip
  timid: no
  log: /config/beet.log
    
lastgenre:
  auto: yes
  source: album
  count: 3
    
zero:
  fields: comments
  
duplicates:
  count: yes
  album: yes
  delete: yes
  merge: yes
  
ignore_hidden: yes
  
match:
  strong_rec_thresh: 0.10
#  ignored: missing_tracks unmatched_tracks
  
ignore: .AppleDouble ._* *~ .DS_Store *.nfo *.ini *.xml *.db *.DB *.sfk *.mediaartlocal *.sfv *.m3u *.m3u8 *.cue *.jpg *.jpeg *.bmp *.png Thumbs.DB *.pls *.url .drive_sync *.txt *.log *.pdf *.exe *.ico
clutter: .AppleDouble ._* *~ .DS_Store *.nfo *.ini *.xml *.db *.DB *.sfk *.mediaartlocal *.sfv *.m3u *.m3u8 *.cue *.jpg *.jpeg *.bmp *.png Thumbs.DB *.pls *.url .drive_sync *.txt *.log *.pdf *.exe *.ico
 
embedart:
    auto: yes

fetchart:
  auto: yes
  cover_names: cover front album art
  minwidth: 500
  enforce_ratio: yes
  fanarttv_key: REDACTED
  google_key: REDACTED
  sources: coverart albumart amazon google fanarttv filesystem

ftintitle:
  auto: yes
  format: (feat. {0})
    
aunique:
  keys: albumartist album
  disambiguators: albumtype year label catalognum albumdisambig releasegroupdisambig
  bracket: '[]'

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

#plex:
#  host: xxxxxxxx
#  port: xxxxx
#  token: xxxxx
#  library_name: "Music"
  
#web:
#    host: 0.0.0.0
#    port: 8337

**Comment by sampsyo** [comment]
Hi! Could you please put your configuration into a code block so we can read it? It would also be _very_ helpful to see `ls -R` output from the directories in question, before and after an import.

**Comment by jdrewsteiner** [comment]
Sorry. Fixed that. I'll try yo get the ls -R output as well.  =Might be a bit.

**Comment by kchr** [comment]
I am having the same issue as the author.

Here is my configuration file:

```yaml
directory: ~/Music/sorted
# --------------- Main ---------------

library: ~/.config/beets/library.db

# --------------- Performance ---------------

threaded: yes

import:
    move: yes
paths:
    default: $albumartist/$albumartist - ($year) $album%aunique{}%if{$atypes, $atypes}/%if{$multidisc,$disc-}$track - $title
    singleton: Non-Album/$artist/$title
    comp: Various Artists/$album%aunique{} ($year)%if{$atypes, $atypes}/%if{$multidisc,$disc-}$track - $title
    albumtype:soundtrack: Various Artists/$album%aunique{} ($year)%if{$atypes, $atypes}/%if{$multidisc,$disc-}$track - $title

# --------------- Plugins ---------------

plugins: albumtypes discogs edit fetchart ftintitle inline lastgenre lastimport
zero:
    fields: comments
item_fields:
    multidisc: 1 if disctotal > 1 else 0
original_date: yes

# --------------- Tagging ---------------

per_disc_numbering: yes
replace:
    '[\\/]': \-
    ^\.: _
    \.$: _
    '[\x00-\x1f]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '[<>:"\?\*\|]': _
    \s+$: ''
    ^\s+: ''
    ^-: _
ignore: .AppleDouble ._* *~ .DS_Store *.nfo *.ini *.xml *.db *.DB *.sfk *.mediaartlocal *.sfv *.m3u *.m3u8 *.cue *.jpg *.jpeg *.bmp *.png Thumbs.DB *.pls *.url .drive_sync *.txt *.log *.pdf *.exe *.ico

# --------------- Import ---------------

clutter: .AppleDouble ._* *~ .DS_Store *.nfo *.ini *.xml *.db *.DB *.sfk *.mediaartlocal *.sfv *.m3u *.m3u8 *.cue *.jpg *.jpeg *.bmp *.png Thumbs.DB *.pls *.url .drive_sync *.txt *.log *.pdf *.exe *.ico
lastfm:
    api_key: REDACTED
    user: REDACTED
albumtypes:
    types:
    -   ep: EP
    -   single: Single
    -   soundtrack: OST
    -   live: Live
    -   compilation: Anthology
    -   remix: Remix
    ignore_va: compilation
    bracket: '[]'
discogs:
    source_weight: 0.5
    apikey: REDACTED
    apisecret: REDACTED
    separator: ', '
    index_tracks: yes
    append_style_genre: yes
    tokenfile: discogs_token.json
    user_token: REDACTED
fetchart:
    maxwidth: 500
    lastfm_key: REDACTED
    sources:
    - filesystem
    - coverart
    - lastfm
    - itunes
    - amazon
    - albumart
    - cover_art_url
    auto: yes
    minwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
ftintitle:
    auto: yes
    format: (feat. {0})
    drop: no
    keep_in_artist: no
lastgenre:
    auto: yes
    source: album
    count: 3
    whitelist: yes
    min_weight: 10
    fallback:
    canonical: no
    force: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
pathfields: {}
album_fields: {}
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
lastimport:
    per_page: 500
    retry_limit: 3
```

The following command line was used to import the album:

```
$ beet import -l ~/.config/beets/import.log -t The\ Vitamin\ String\ Quartet\ -\ Tribute\ To\ Massive\ Attack/
```

Here is a list of the directory contents, before and after import:

## Before import

```
-rw-r--r-- 1 user users    56308 May 13 22:51 '00. The Vitamin String Quartet - Tribute to Massive Attack.jpg'
-rw-r--r-- 1 user users     1643 May 13 22:51 '00. The Vitamin String Quartet - Tribute to Massive Attack.m3u'
-rw-r--r-- 1 user users     1803 May 13 22:51 '00. The Vitamin String Quartet - Tribute to Massive Attack.nfo'
-rw-r--r-- 1 user users     1160 May 13 22:51 '00. The Vitamin String Quartet - Tribute to Massive Attack.sfv'
-rw-r--r-- 1 user users 14792704 May 13 22:55 'The Vitamin String Quartet - Tribute To Massive Attack - 01 - Angel.mp3'
-rw-r--r-- 1 user users 12470272 May 13 22:55 'The Vitamin String Quartet - Tribute To Massive Attack - 02 - Hymn Of The Big Wheel.mp3'
-rw-r--r-- 1 user users 12093440 May 13 22:56 'The Vitamin String Quartet - Tribute To Massive Attack - 03 - Rising Son.mp3'
-rw-r--r-- 1 user users  9078784 May 13 22:56 'The Vitamin String Quartet - Tribute To Massive Attack - 04 - Better Things.mp3'
-rw-r--r-- 1 user users 12363776 May 13 22:57 'The Vitamin String Quartet - Tribute To Massive Attack - 05 - Safe From Harm.mp3'
-rw-r--r-- 1 user users  9799680 May 13 22:57 'The Vitamin String Quartet - Tribute To Massive Attack - 06 - Inertia Creeps.mp3'
-rw-r--r-- 1 user users  8740864 May 13 22:58 'The Vitamin String Quartet - Tribute To Massive Attack - 07 - Sly.mp3'
-rw-r--r-- 1 user users  9719808 May 13 22:51 'The Vitamin String Quartet - Tribute To Massive Attack - 08 - Teardrop.mp3'
-rw-r--r-- 1 user users 10031104 May 13 22:58 'The Vitamin String Quartet - Tribute To Massive Attack - 09 - Three.mp3'
-rw-r--r-- 1 user users 13862912 May 13 22:59 'The Vitamin String Quartet - Tribute To Massive Attack - 10 - Weather Storm.mp3'
-rw-r--r-- 1 user users  7024640 May 13 22:59 'The Vitamin String Quartet - Tribute To Massive Attack - 11 - Unfinished Sympathy.mp3'
-rw-r--r-- 1 user users 17324032 May 13 23:00 'The Vitamin String Quartet - Tribute To Massive Attack - 12 - Oto (Original Composition).mp3'
```

## After import

```
-rw-r--r-- 1 user users 56308 May 13 22:51 '00. The Vitamin String Quartet - Tribute to Massive Attack.jpg'
-rw-r--r-- 1 user users  1643 May 13 22:51 '00. The Vitamin String Quartet - Tribute to Massive Attack.m3u'
-rw-r--r-- 1 user users  1803 May 13 22:51 '00. The Vitamin String Quartet - Tribute to Massive Attack.nfo'
-rw-r--r-- 1 user users  1160 May 13 22:51 '00. The Vitamin String Quartet - Tribute to Massive Attack.sfv'
```
