### ISSUE TITLE
Running with import command with --set tag=value does not reflect on copied files.

### ISSUE THREAD

**Issue by jackwalten** [beetbox/beets#5023]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import --set albumartist='Made in Abyss' -A \[2017.08.23\]\ メイドインアビス｜Deep\ in\ Abyss\ \[OP.1\]/
```

Led to this problem:

```
user configuration: /home/catharsis/.config/beets/config.yaml
data directory: /home/catharsis/.config/beets
inline: adding item field multidisc
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
fetchart: To use Spotify as an album art source, you must install the beautifulsoup4 module. See the documentation for further details.
Sending event: pluginload
library database: /home/catharsis/.config/beets/library.db
library directory: /home/catharsis/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
/home/catharsis/Downloads/[2017.08.23] メイドインアビス｜Deep in Abyss [OP.1]
0 of 4 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Set field albumartist=Made in Abyss for /home/catharsis/Downloads/[2017.08.23] メイドインアビス｜Deep in Abyss [OP.1]
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: album_imported
Sending event: import
Sending event: cli_exit

```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Debian 12 Bookworm Stable
* Python version: 3.11.2
* beets version:  from git
* Turning off plugins made problem go away (yes/no): no

beets version 1.6.1
Python version 3.11.2
no plugins loaded

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart convert inline
directory: ~/Music
library: library.db
per_disc_numbering: yes
art_filename: Cover

import:
    copy: yes
    incremental: no
    log: ~/import.log

fetchart:
    auto: yes
    cover_names: cover Cover
    sources: filesystem

paths:
    default: $albumartist/$year-$album/%if{$multidisc,Disc $disc/}$track-$title
    singleton: $albumartist/$year-$album/%if{$multidisc,Disc $disc/}$track-$title
    comp: $albumartist/$year-$album/%if{$multidisc,Disc $disc/}$track-$title

item_fields:
    multidisc: 1 if disctotal > 1 else 0
    
convert:
    auto: no
    dest: ~/Music 
    copy_album_art: yes
    embed: yes
    never_convert_lossy_files: yes
    format: mp3
    formats:
        opus:
            command: opusenc --bitrate 256 $source $dest
            extension: opus
        mp3:
            command: ffmpeg -i $source -y -codec:a libmp3lame -q:a 0 $dest
            extension: mp3
```

If I go into the imported files and then do a mediainfo, the Album/Performer is still unchanged, and only during noautotag. If I enable autotag, it sets the albumartist tag I specified fine. Also if I enable auto convert to yes, the problem also goes away, but that's not really a viable solution. Weirdly enough, beets does seem to think the albumartist is "Made in Abyss" when it tries to create the directory structure.

I think I get what's going on, in the problematic command I showed, when I specify -A, the files are imported as-is, ignoring the --set fields, but it is recorded in beets database as 'Made in Abyss'. That is why when we use the convert plugin, since it fetches the tags from the database and applies them on the converted file, they get the correct tags.
