### ISSUE TITLE
beets duplicate plugin can't detect duplicates

### ISSUE THREAD

**Issue by ragnarov** [beetbox/beets#5039]
### Problem

Beets duplicate plugin don't detect the following duplicates.

```sh
$ beet -vv ls
```

Led to this problem:

```
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 -  - 
 - Piano Arrangements from 2017 - The Force Theme - Star Wars
 - Piano Arrangements from 2017 - The Force Theme - Star Wars
 - Piano Arrangements from 2017 - The Force Theme - Star Wars
 - Piano Arrangements from 2017 - The Force Theme - Star Wars
 - Piano Arrangements from 2017 - The Force Theme - Star Wars
```

### Setup

* OS: 
* beets & Python version: 
* ``` $ beet version
beets version 1.6.0
Python version 3.11.2
plugins: duplicates, play ```
* Turning off plugins made problem go away (yes/no):  not applicable

My configuration (output of `beet config`) is:

```directory: /home/atom/HWD/mounts/data/Music/files
library: /home/atom/HWD/mounts/data/Music/records/records.db
pluginpath: /home/atom/HWD/mounts/data/Music/plugins
asciify_paths: yes
color: yes

import:
    write: no
    copy: yes
    move: no
    link: no
    hardlink: no
    reflink: no
    resume: ask
    languages: en bn ru
    quiet: no
    group_albums: yes
    autotag: no

plugins: play duplicates
play:
    command: cmus-remote -q
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
    bom: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: '' ```

**Comment by DjSlash** [comment]
The `ls` shows a list of tracks that have missing metadata; why is that, how are they imported ? What does `beet ls -f $path` show?

You have a certain expectation of duplicates, but you don't state what that is. You don't show what the current behavior is, nor do you state what it does (not). If I'm not mistaken, you have it configured in a way that it just won't work. You emptied the `keys:` option, which disables it's default behavior. All other options also disables it's functionality (except for `tag:`, wich is set to an incorrect syntax).  Also, the duplicates plugin has to be triggered manually.

**Comment by ragnarov** [comment]
config.yaml
```
directory: /home/atom/HWD/mounts/data/Music/files
library: /home/atom/HWD/mounts/data/Music/records/records.db
pluginpath: /home/atom/HWD/mounts/data/Music/plugins
asciify_paths: yes
color: yes
import:
    write: no
    copy: yes
    move: no
    link: no
    hardlink: no
    reflink: no
    resume: ask
    languages: en bn ru
    quiet: no
    group_albums: yes
    autotag: no
plugins: play duplicates

play:
    command: cmus-remote -q
```
This is the configuration set by me.

**Comment by ragnarov** [comment]
> The `ls` shows a list of tracks that have missing metadata; why is that, how are they imported ? What does `beet ls -f $path` show?
```
/home/atom/HWD/mounts/data/Music/files/__/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[27]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[28]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[29]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[30]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[32]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[33]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[34]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[35]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[37]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[38]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[39]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[40]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[42]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[43]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[44]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[45]/00.flac
/home/atom/HWD/mounts/data/Music/files/_/[82]/00.opus
/home/atom/HWD/mounts/data/Music/files/_/Piano Arrangements from 2017/00 The Force Theme - Star Wars.flac
/home/atom/HWD/mounts/data/Music/files/_/Piano Arrangements from 2017 [31]/00 The Force Theme - Star Wars.flac
/home/atom/HWD/mounts/data/Music/files/_/Piano Arrangements from 2017 [36]/00 The Force Theme - Star Wars.flac
/home/atom/HWD/mounts/data/Music/files/_/Piano Arrangements from 2017 [41]/00 The Force Theme - Star Wars.flac
/home/atom/HWD/mounts/data/Music/files/_/Piano Arrangements from 2017 [46]/00 The Force Theme - Star Wars.flac
```
 
> You have a certain expectation of duplicates, but you don't state what that is. You don't show what the current behavior is, nor do you state what it does (not).

I want it to remove those duplicates.

>  If I'm not mistaken, you have it configured in a way that it just won't work. You emptied the `keys:` option, which disables it's default behavior. All other options also disables it's functionality (except for `tag:`, which is set to an incorrect syntax). Also, the duplicates plugin has to be triggered manually.

this is my config.yaml
```
directory: /home/atom/HWD/mounts/data/Music/files
library: /home/atom/HWD/mounts/data/Music/records/records.db
pluginpath: /home/atom/HWD/mounts/data/Music/plugins
asciify_paths: yes
color: yes
import:
    write: no
    copy: yes
    move: no
    link: no
    hardlink: no
    reflink: no
    resume: ask
    languages: en bn ru
    quiet: no
    group_albums: yes
    autotag: no
plugins: play duplicates

play:
    command: cmus-remote -q
```
