### ISSUE TITLE
Lastgenre downloading genres but not writing to files

### ISSUE THREAD

**Issue by Explosion-Scratch** [beetbox/beets#5107]
It looks like it's working but then no files are modified

```sh
$ beet -vv lastgenre -A ""
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: 
* Python version: 
* beets version: 
* Turning off plugins made problem go away (yes/no): i mean yeah

```
user configuration: /home/tjs/.config/beets/config.yaml
data directory: /home/tjs/.config/beets
plugin paths:
lastgenre: Loading canonicalization tree /home/tjs/.local/lib/python3.10/site-packages/beetsplug/lastgenre/genres-tree.yaml
artresizer: method is (2, (6, 9, 11), False)
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
lyrics: Disabling google source: no API key configured.
Sending event: pluginload
library database: /home/tjs/Media/Data/musiclibrary3.db
library directory: /media/tjs/drive/media/Music3
Sending event: library_opened
lastgenre: added last.fm item genre (track): Indie Rock
Sending event: database_change
lastgenre: added last.fm item genre (track): Jazz
Sending event: database_change
lastgenre: added last.fm item genre (track): Classic Country
Sending event: database_change
lastgenre: added last.fm item genre (track): Soul
Sending event: database_change
lastgenre: added last.fm item genre (None):
Sending event: database_change
lastgenre: added last.fm item genre (track): Indie Pop
Sending event: database_change
lastgenre: added last.fm item genre (track): Orchestral
Sending event: database_change
lastgenre: added last.fm item genre (album): Neo Soul
Sending event: database_change
lastgenre: added last.fm item genre (artist): Indie Rock
Sending event: database_change
lastgenre: added last.fm item genre (artist): Indie Rock
Sending event: database_change
lastgenre: added last.fm item genre (album): Indie Rock
Sending event: database_change
lastgenre: added last.fm item genre (track): Indie Rock
```

<details>
<summary>Config</summary>

```yaml
lyrics:
    bing_lang_from: []
    synced: yes
    sources: lrclib google genius tekstowo
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
directory: /media/tjs/drive/media/Music3
library: /home/tjs/Media/Data/musiclibrary3.db

import:
    incremental: yes
    write: yes
    quiet: yes
quiet_fallback: skip

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Tracks/$albumartist/$album%aunique{}/$track $title
    comp: Compilations/$album%aunique{}/$track $title
    playlist::.: Playlists/$playlist/$artist - $title

plugins: spotify lyrics ftintitle replaygain thumbnails importadded discogs embedart fetchart lastgenre info importadded smartplaylist
lastgenre:
    auto: yes
    canonical: yes
    count: 1
    source: track
    prefer_specific: yes
    separator: '; '
    whitelist: yes
    min_weight: 10
    fallback:
    force: yes
    title_case: yes
spotify:
    source_weight: 0
    show_failures: no
    tiebreak: first
    mode: list
    artist_field: albumartist
    album_field: album
    track_field: title
    region_filter:
    regex: []
    client_id: 4e414367a1d14c75a5c5129a627fcab8
    client_secret: REDACTED
    tokenfile: spotify_token.json

musicbrainz:
    source_weight: 1
    enabled: no
    host: localhost:5000
discogs:
    source_weight: 0.5
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    user_token: REDACTED
    separator: ', '
    index_tracks: no
chroma:
    auto: yes
replaygain:
    backend: command
    auto: yes
    overwrite: no
    threads: 8
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
    command: ''
    noclip: yes
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
embedart:
    auto: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
thumbnails:
    auto: yes
    force: no
    dolphin: no
group_albums: yes
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
importadded:
    preserve_mtimes: no
    preserve_write_mtimes: no
smartplaylist:
    relative_to:
    playlist_dir: .
    auto: yes
    playlists: []
    forward_slash: no
    prefix: REDACTED
    urlencode: no
```

</details>

I might also note that my library is on an external drive but all permissions are fine for writing and beets can write to it when importing so I don't see why it can't write while modifying tags.
