### ISSUE TITLE
`unimported`'s `ignore_subdirectories` doesn't work

### ISSUE THREAD

**Issue by ArtemSmaznov** [beetbox/beets#5130]
### Problem

```sh
beet unimported
```

Leads to directories specified in `ignore_subdirectories` still being listed

### Setup

* OS: Arch Linux
* Python version: 3.11.7 
* beets version: 1.6.1
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is:

```yaml
unimported:
  ignore_extensions: jpg png txt md org mod
  ignore_subdirectories: Unsorted import
```
`ignore_extensions` works as expected though
