### ISSUE TITLE
bug[fetchart]: Only one of the resize operation is executed.

### ISSUE THREAD

**Issue by Dr-Blank** [beetbox/beets#5151]
Consider a case where a coverart is of PNG format with size 15 MB. (happens sometimes with itunes coverart on musicbrainz).

Also consider the following fetchart config:
```yaml
plugins: fetchart
fetchart:
  sources:
    - filesystem
    - coverart: release
    - itunes
    - amazon
    - albumart
    - coverart: releasegroup
    - "*"
  max_filesize: 3500000
  cover_format: JPEG
```

PIL is used as the image resizer

### Problem

```sh
$ beet -vv fetchart
```
```py
Candidate._validate(self, plugin)
# returns only CANDIDATE_DOWNSIZE
# and skips CANDIDATE_REFORMAT
```

the function can only perform one of the operations in the current scenario, and since downsizing is returned before reformatting, during `.resize()` only downsizing takes place. Which is its own separate bug since PIL can not downnsize PNG files.

### Setup

* OS: Windows
* Python version: 3.11.0b1 
* beets version: https://github.com/beetbox/beets/commit/b09806e0df8f01b9155017d3693764ae7beedcd5
* Turning off plugins made problem go away (yes/no): N/A
