### ISSUE TITLE
No path completion in fish for `beet import`

### ISSUE THREAD

**Issue by justbispo** [beetbox/beets#5198]
### Problem

After enabling the fish plugin to get tab completion, path completion doesn't work. When I press `tab`, I get all the fieldnames as suggestions instead. 

![beets](https://github.com/beetbox/beets/assets/38961424/a572babc-b0f5-49e2-b036-c4b6f2801f60)

Before enabling, I was getting path completion but no arguments completion.

### Setup

* OS: Arch Linux
* Python version: 3.11.8
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    sources: genius
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
discogs:
    user_token: REDACTED
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    separator: ', '
    index_tracks: no
hook:
    hooks: [{event: import, command: echo 'beets just exited!'}, {event: import, command: echo 'have a nice day!'}]
lastgenre:
    count: 4
    separator: '; '
    whitelist: yes
    min_weight: 10
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    prefer_specific: no
    title_case: yes
lastfm:
    user: REDACTED
    api_key: REDACTED
spotify:
    source_weight: 0.7
    regex: [{field: title, search: ft., replace: feat.}]
    mode: list
    tiebreak: popularity
    show_failures: no
    artist_field: albumartist
    album_field: album
    track_field: title
    region_filter:
    client_id: REDACTED
    client_secret: REDACTED
    tokenfile: spotify_token.json
wlg:
    auto: yes
    force: yes
    separator: '; '
    count: 4
    whitelist: wlg
pluginpath: [/lib/python3.10/site-packages/beetsplug, ~/.config/beets/plugins]

plugins:
- discogs
- edit
- hook
- lastgenre
- lastimport
- lyrics
- mbsync
- spotify
- wlg
- fish
include: [beets.d/plugins.yaml, beets.d/plugins_settings.yaml]
directory: ~/audio
library: library.db

import:
    copy: no
    languages: en
languages: en

match:
    ignore_video_tracks: no
lastimport:
    per_page: 500
    retry_limit: 3
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path
```
