### ISSUE TITLE
Different releases incorrectly considered duplicate

### ISSUE THREAD

**Issue by raimundomartins** [beetbox/beets#5250]
### Problem

I'm trying to import both https://musicbrainz.org/release/3e475b92-6217-43cf-8557-e0c11bc96091 and https://musicbrainz.org/release/0701e066-6823-4987-946e-ad04a972bb0c but when I try to import the second one it is considered duplicate. Catalog number is different and they have different tracks, but I'm not allowed to have both albums in my library.

### Setup

* OS: void-linux
* Python version: 3.12.3
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no (even worse, now autotagger can't even match the release!)

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    sources:
    - google
    - musixmatch
    - genius
    - tekstowo
directory: /srv/music

import:
    from_scratch: yes
    write: yes
    copy: yes
    move: yes
    detail: yes

aunique:
    keys: year albumartist album
    disambiguators: albumtype label catalognum albumdisambig releasegroupdisambig
    bracket: '[]'
per_disc_numbering: yes

paths:
    default: '%lower{$albumartist}/$year %lower{$album}%aunique{}/$disc_and_track %lower{$title}'
    singleton: '%lower{$artist}/%lower{$title}'
    comp: VA/$year %lower{$album}%aunique{}/$disc_and_track %lower{$title}

musicbrainz:
    extra_tags: [year, label, catalognum]
    genres: no
    searchlimit: 5
max_rec:
    missing_tracks: strong

match:
    ignored: missing_tracks
    preferred:
        media: [CD, Digital Media|File]
        original_year: yes
    ignored_media:
    - Data CD
    - DVD
    - DVD-Video
    - Blu-ray
    - HD-DVD
    - VCD
    - SVCD
    - UMD
    - VHS
pluginpath: [~/beet-plugins]

plugins: inline discogs chroma fetchart lyrics acousticbrainz web frompathname
item_fields:
    disc_and_track: u'%01i%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
discogs:
    user_token: REDACTED
    index_tracks: yes
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    separator: ', '
fetchart:
    quality: 90
    auto: yes
    minwidth: 0
    maxwidth: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
chroma:
    auto: no
acoustid:
    apikey: REDACTED
web:
    reverse_proxy: yes
    port: 8004
    host: 127.0.0.1
    cors: ''
    cors_supports_credentials: no
    include_paths: no
    readonly: yes
pathfields: {}
album_fields: {}
acousticbrainz:
    auto: yes
    force: no
    tags: []
```
