### ISSUE TITLE
Metadata not updating when using discogs plugin

### ISSUE THREAD

**Issue by Batwam** [beetbox/beets#5260]
### Problem

Beets doesn't appear to be updating durations. This means that it is attempeting to update the files over and over again. I have updated the read right so user/group/others have write access but the same issue still occurs. I can confirm that it does update other fields like Artist.

Looking at the songs in my music players, I am not convinced that the duration tag is meant to be writable. Kind of feels like this information should be part of the mp3 properties already. Is beet mean to be overwriting the duration metadata? if not, how do I make is so that it ignores this metadata and doesn't attempt to update the files to fix it?

As you can see below, the while beets finds that the duration should be updated, the duration is the same before and after import:

![Screenshot from 2024-05-25 15-34-41](https://github.com/beetbox/beets/assets/56710655/01e46cc4-2fdc-4a2d-97cb-f195710c24bb)

### Setup

* OS: Ubuntu 23.10
* Python version: 3.11.6
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music
library: ~/.config/beets/musiclibrary.db

pluginpath:
  ~/.config/beets/plugins

import:
    move: yes
    copy: no
    write: yes
    
#set threshold for auto matching (0.10 = 90% match)
match:
    strong_rec_thresh: 0.15
```
