### ISSUE TITLE
Beets uses artist Japanese characters name instead of the available English one

### ISSUE THREAD

**Issue by sezaru** [beetbox/beets#5269]
### Problem

When importing Japanese music, most artists will show their name in Japanese characters instead of English ones.

AFAIK, setting the language to `en` in beets config is enough for beets to use the English name instead of the Japanese one.

For example, I have the following album that I want to import:

https://musicbrainz.org/release/62aea103-e3d3-45b3-b8a9-6ef2651b7b27

The artist is Yoko Kanno, and if you look into her aliases, there is an English version there: https://musicbrainz.org/artist/5ffb73c0-b739-4231-ba22-f8d361be1d45/aliases

Even though there is an English version, beets will still use the Japanese name (菅野よう子) and set it as the artist name.

My guess is that beets is using the album artist name directly which is in Japanese instead of looking into the artist data in musicbrainz and getting the correct name.

Is this a bug or am I doing something wrong?

### Setup

* OS:  Docker
* Python version: 3.11.9
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web lyrics
directory: /media/musics
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no
languages: en

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes

replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337
```
