### ISSUE TITLE
discogs: python3-discogs-client version should be >= 2.3.15

### ISSUE THREAD

**Issue by ovizii** [beetbox/beets#5281]
Using this Docker image: lscr.io/linuxserver/beets:latest - getting the above error after the upgrade to the latest beets version

### Problem

Running this command daily via cron: 
`docker exec -u abc -it beets /bin/bash -c 'beet import -q /mnt/downloads/completed/music/*'`

Led to this problem:

```
discogs: python3-discogs-client version should be >= 2.3.15
```

### Setup

* OS: Debian 12
* Docker Image by linuxserver

```
beet version
discogs: python3-discogs-client version should be >= 2.3.15
beets version 2.0.0
Python version 3.11.9
plugins: albumtypes, beatport, chroma, convert, discogs, duplicates, embedart, fetchart, fromfilename, fuzzy, info, lastgenre, mbsync, missing, permissions, replaygain, rewrite, scrub, web

```

My configuration (output of `beet config`) is:

```
# --------------- Plugins ---------------

plugins: albumtypes beatport chroma convert discogs duplicates embedart fetchart fromfilename fuzzy info lastgenre mbsync missing permissions replaygain rewrite scrub web
directory: /music
# --------------- Main ---------------

library: /config/musiclibrary.blb
art_filename: albumart

# --------------- Performance ---------------

threaded: yes
original_date: no

# --------------- Tagging ---------------

per_disc_numbering: no
albumtypes:
    types:
    -   ep: EP
    -   single: Single
    -   soundtrack: OST
    -   live: Live
    -   compilation: Anthology
    -   remix: Remix
    ignore_va: compilation
    bracket: '[]'
chroma:
    auto: yes
convert:
    auto: yes
    ffmpeg: /usr/bin/ffmpeg
    opts: -aq 0 -acodec libmp3lame
    max_bitrate: 320
    threads: 1
    never_convert_lossy_files: yes
    delete_originals: yes
    dest:
    pretend: no
    link: no
    hardlink: no
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    auto_keep: no
    tmpdir:
    quiet: no
    embed: yes
    paths: {}
    no_convert: ''
    copy_album_art: no
    album_art_maxwidth: 0
    playlist:
embedart:
    auto: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    incremental_skip_later: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log
lastgenre:
    auto: yes
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
missing:
    format: $albumartist - $album - $title
    count: yes
    total: yes
    album: no
paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Various Artists/$album%aunique{}/$track - $title
    albumtype:soundtrack: Soundtracks/$album/$track - $title
permissions:
    file: 660
    dir: 770
replace:
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    \.$: _
    \s+$: ''
replaygain:
    auto: yes
    threads: 2
    backend: ffmpeg
    overwrite: no
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
rewrite:
    artist .*jimi hendrix.*: Jimi Hendrix
    artist .*Abdullah Ibrahim.*: Abdullah Ibrahim
scrub:
    auto: yes
web:
    host: 0.0.0.0
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    readonly: yes
fuzzy:
    prefix: '~'
    threshold: 0.7
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
    separator: ', '
    index_tracks: no
    append_style_genre: no
beatport:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: beatport_token.json
    source_weight: 0.5

```
