### ISSUE TITLE
Error when loading `convert` plugin

### ISSUE THREAD

**Issue by seadowg** [beetbox/beets#5324]
### Problem

Running `beet` (any command) fails to load the `convert` plugin:

```
** error loading plugin convert:
Traceback (most recent call last):
  File "/usr/share/beets/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
  File "/home/beets/.local/lib/python3.10/site-packages/beetsplug/convert.py", line 32, in <module>
    from beets.util.m3u import M3UFile
ModuleNotFoundError: No module named 'beets.util.m3u'
```

### Setup

I'm running in a Docker image built from the following file:

```Dockerfile
FROM ubuntu:jammy

RUN adduser beets
RUN apt-get update && apt-get install -y beets ffmpeg
RUN apt-get update && apt-get install -y wget unzip
COPY beets-config.yaml /home/beets/.config/beets/config.yaml

USER beets
RUN pip install --user beets-extrafiles

WORKDIR /home/beets
```

The output of `beet version` is:

```
beets version 1.6.0
Python version 3.10.12
plugins: extrafiles
```

My configuration (output of `beet config`) is:

```yaml
directory: /home/beets/music
library: /home/beets/music/beet-library.db

plugins: convert extrafiles
asciify_paths: yes

format_item: $artist - $album - $title ($format $bitrate $samplerate $bitdepth)
convert:
    copy_album_art: yes
    never_convert_lossy_files: yes
    formats:
        cd:
            command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 $dest
            extension: flac
        cd_with_dither:
            command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 -dither_method triangular $dest
            extension: flac
extrafiles:
    patterns:
        jpg: '*.jpg'
        pdf: '*.pdf'
        png: '*.png'

    paths: {}
```
