### ISSUE TITLE
Itunes ignores albumartist_sort

### ISSUE THREAD

**Issue by AlexChalk** [beetbox/beets#5335]
Thanks for your work on this project!

### Problem

Setting `albumartist_sort` (on an album or a track) does not write the metadata in a way that iTunes can read. When I hit `get info -> sorting` in iTunes, album artist sort is blank.

I found this mp3tag issue, but unlike the OP there, `artist_sort` and `album_sort` are picked up fine by iTunes for me: https://community.mp3tag.de/t/itunes-and-artist-albumartist-and-album-sort-tags/56070

### Setup

OS: nixos 24.05
beets version 2.0.0
Python version 3.11.9
plugins: albumsort, badfiles, bandcamp, convert, duplicates, edit, embedart, fetchart, ftintitle, info, inline, replaygain, scrub

My configuration (output of `beet config`) is:

```yaml
directory: ~/beets-data/music
# --------------- Main ---------------

library: ~/beets-data/musiclibrary.db

# --------------- Plugins ---------------

plugins: albumsort bandcamp badfiles convert duplicates edit embedart fetchart ftintitle info inline replaygain scrub
original_date: no

# --------------- Tagging ---------------

per_disc_numbering: yes

# --------------- Performance ---------------

threaded: yes

sort_album: albumartist+ year+ album+
item_fields:
    disc_and_track: u'%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
paths:
    default: $albumartist/$album%aunique{}/$disc_and_track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$disc_and_track $title

import:
    write: yes
    copy: yes
    from_scratch: no
    timid: yes
edit:
    itemfields: track title artist album album_sort albumartist_sort artist_sort year original_year genre format
    albumfields: album albumartist albumartist_sort genre
    ignore_fields: id path
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
badfiles:
    check_on_import: yes
    commands:
        m4a: ffmpeg -v error -f null - -i
        flac: flac --test --warnings-as-errors --silent
fetchart:
    auto: no
    enforce_ratio: yes
    minwidth: 500
    maxwidth: 500
    quality: 0
    max_filesize: 0
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
embedart:
    auto: no
    ifempty: no
    maxwidth: 500
    remove_art_file: no
    compare_threshold: 0
    quality: 0
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
scrub:
    auto: yes
replaygain:
    backend: ffmpeg
    overwrite: no
    auto: yes
    threads: 8
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
bandcamp:
    preferred_media: Vinyl,CD,Cassette
    include_digital_only_tracks: yes
    search_max: 5
    art: no
    comments_separator: '

        ---

        '
    exclude_extra_fields: []
    genre:
        capitalize: yes
        maximum: 0
        always_include: []
        mode: progressive
convert:
    dest:
    pretend: no
    link: no
    hardlink: no
    threads: 8
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate:
    auto: no
    auto_keep: no
    tmpdir:
    quiet: no
    embed: yes
    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
    delete_originals: no
    playlist:
pathfields: {}
album_fields: {}
```
