### ISSUE TITLE
beet version prints echonest twice 

### ISSUE THREAD

**Issue by dfc** [beetbox/beets#536]
I am running 1.3.2 with my config appended. if I do not enable the echonest plugin beet version operates like you would expect:

```
$ beet version
beets version 1.3.2
plugins: chroma, fromfilename, fetchart
```

If I switch the commented plugin line to enable echonest beet version prints echonest twice:

```
$ beet version
beets version 1.3.2
plugins: chroma, fromfilename, fetchart, echonest, echonest 
```

My conig is: 

```
directory: ~/MyTunes
library: ~/.beets/musiclibrary.db

#plugins: chroma fromfilename fetchart
plugins:  chroma fromfilename fetchart echonest

import:
    move: yes
    quiet_fallback: skip
    log:    ~/.beets/imported-beets.log

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: 0xSingles/$genre/$artist/$title
    comp: 0xCompilations/$genre/$album%aunique{}/$track $title

fetchart:
    cautious: true

echonest:
    upload: no
    convert: no
    apikey: XXXXXXXX

```
