### ISSUE TITLE
I have two issues: 1st could not set permissions on... 2nd FileNotFoundError: [Errno 2] No such file or directory:... then crash!

### ISSUE THREAD

**Issue by fabiendostie** [beetbox/beets#5364]
**### Problem 1 ###**
when I do a ```beet import /path/to/my/folder``` for every file after it get this: ```permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/title of the song...```
one per file. It doesnt crash but I wonder what causes it?
full example:
```
  Match (97.1%):
  Savoy Brown - A Step Further
  ≠ year, tracks
  MusicBrainz, CD, 1990, US, Deram, 844 015-2, Remastered
  https://musicbrainz.org/release/e2ee7c29-67e9-3c52-a408-5a5f244e6f2f
  * Artist: Savoy Brown
  * Album: A Step Further
     ≠ (#2) Waiting In The Bamboo Grove (3:38) -> (#2) Waiting in the Bamboo Groove (3:38)
     ≠ (#3) Life's One Act Play (6:30) -> (#3) Life’s One Act Play (6:30)
     ≠ (#4) I'm Tired - Where Am I (5:05) -> (#4) I’m Tired / Where Am I (5:05)
     ≠ (#5) Savoy Brown Boogie Medley (22:06) -> (#5) Savoy Brown Boogie (live) (22:06)

/Volumes/data/usenet/completed/New_Music/Savoy_Brown-Bring_It_Home-16BIT-WEB-FLAC-1994-OBZEN (13 items)

permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1969-A Step Further(05)-[Album][Deram][FLAC][16_bit_44kHz]/albumart.jpg
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1969-A Step Further(05)-[Album][Deram][FLAC][16_bit_44kHz]/01-Made Up My Mind.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1969-A Step Further(05)-[Album][Deram][FLAC][16_bit_44kHz]/02-Waiting in the Bamboo Groove.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1969-A Step Further(05)-[Album][Deram][FLAC][16_bit_44kHz]/03-Life’s One Act Play.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1969-A Step Further(05)-[Album][Deram][FLAC][16_bit_44kHz]/04-I’m Tired _ Where Am I.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1969-A Step Further(05)-[Album][Deram][FLAC][16_bit_44kHz]/05-Savoy Brown Boogie (live).flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1969-A Step Further(05)-[Album][Deram][FLAC][16_bit_44kHz]
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/albumart.jpg
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/01-Mr. Brown's Boogie.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/02-Sweet Loving Thing.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/03-Too Much of a Good Thing.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/04-Misery.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/05-Shake for Me.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/06-Pack It Up.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/07-High on Your Love.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/08-Worried Man.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/09-Little Wheel.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/10-You're in for a Big Surprise.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/11-Real Fine Woman.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/12-That's What Love Will Do.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]/13-Baby Please.flac
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/1994-Bring It Home(13)-[Album][Magnetic Air Records][FLAC][16_bit_44kHz]
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues
permissions: could not set permissions on /volumes/data/media/Music_Clean/Albums/Blues/S/Savoy Brown/2019-City Night(12)-[Album][Quarto Valley Records][FLAC][16_bit_44kHz]/albumart.jpg
```

**### Problem 2 ###**
Causes crash, also happen after a while wen I do ```beet import /path/to/my/folder``` 
The last line says cant find that file, but beets just moved it, its nomal... it's like beets is triying to do an operation on a file that it just moved to another location. Always happen after a bunch of permissions: could not set permissions on... from problem 1!! 

Full Example:
```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/beets/ui/__init__.py", line 1865, in main
    _raw_main(args)
  File "/usr/local/lib/python3.11/site-packages/beets/ui/__init__.py", line 1852, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.11/site-packages/beets/ui/commands.py", line 1395, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python3.11/site-packages/beets/ui/commands.py", line 1326, in import_files
    session.run()
  File "/usr/local/lib/python3.11/site-packages/beets/importer.py", line 360, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python3.11/site-packages/beets/util/pipeline.py", line 447, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/beets/util/pipeline.py", line 315, in run
    for msg in _allmsgs(out):
  File "/usr/local/lib/python3.11/site-packages/beets/util/pipeline.py", line 468, in pull
    out = coro.send(msg)
          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/beets/util/pipeline.py", line 195, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python3.11/site-packages/beets/importer.py", line 1490, in lookup_candidates
    plugins.send("import_task_start", session=session, task=task)
  File "/usr/local/lib/python3.11/site-packages/beets/plugins.py", line 507, in send
    result = handler(**arguments)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/beets/plugins.py", line 143, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/beetsplug/chroma.py", line 186, in fingerprint_task
    return fingerprint_task(self._log, task, session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/beetsplug/chroma.py", line 257, in fingerprint_task
    acoustid_match(log, item.path)
  File "/usr/local/lib/python3.11/site-packages/beetsplug/chroma.py", line 86, in acoustid_match
    duration, fp = acoustid.fingerprint_file(util.syspath(path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/acoustid.py", line 352, in fingerprint_file
    return _fingerprint_file_audioread(path, maxlength)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/acoustid.py", line 292, in _fingerprint_file_audioread
    with audioread.audio_open(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
               ^^^^^^^^^^^^^^^^^^^^
**FileNotFoundError: [Errno 2] No such file or directory: b'/Volumes/data/usenet/completed/New_Music/Sebastien_Tellier-Domesticated-FR-24BIT-44KHZ-WEB-FLAC-2020-OBZEN/06-sebastien_tellier-atomic_smile.flac'**
```

### Setup

* Mac OS Sonoma 14.3.1 
* beets version 2.0.0
* Python version 3.11.9
* Turning off plugins would make the operation i need to do impossible

My configuration (output of `beet config`) is:

```yaml
# General ###########################################################################################
#plugins: fetchart embedart convert scrub replaygain lastgenre chroma bucket absubmit acousticbrainz lastimport mbsync mbcollection mbsubmit ftintitle

include:                     
  - local.yaml               
  - secrets.yaml
  - plugins.yaml

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /Users/lefab/.config/beets/log/import.log
    default_action: apply
    autotag: yes
    duplicate keys:
      album: albumartist album
      item: artist title
    duplicate_action: merge 

art_filename: albumart
threaded: yes
original_date: yes
per_disc_numbering: yes

# Paths ###########################################################################################

asciify_path: yes             # Convert all non-ASCII characters in paths to ASCII equivalents.

clutter:                     # When beets imports all the files in a directory, it tries to remove the directory if it’s empty.
                             # A directory is considered empty if it only contains files whose names match the glob patterns in clutter,
                             # which should be a list of strings.
                             # The importer only removes recursively searched subdirectories—the top-level directory you specify on the command line is never deleted.

clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg", "*.cue", "*.jpeg", "*.pdf"]

bucket:
  bucket_alpha_regex:
    [A-Z]                    # Create folders with the first letters of the band names.

paths:
    default: 
        Albums/
        $genre/
        %bucket{$artist,alpha}/
        $albumartist/
        $year-$album%aunique{}($tracktotal)-[%title{$albumtype}][$label][%upper{$format}][$bitdepth\bit_$samplerate]/
        $track-$title
    singleton: 
        Singles/
        $genre/
        %bucket{$artist,alpha}/
        $year-$artist/$title%sunique{}[$label][$bitdepth\bit_$samplerate]/
    comp:
        Compilations/
        $genre/
        $year-$album%aunique{}[$bitdepth\bit_$samplerate]/
        $track-$title
    albumtype:soundtrack:
        Soundtracks/
        $year-$album%aunique{}[$label][$bitdepth\bit_$samplerate]/
        $track-$title
    albumtype:DJ-mix:
        DJ-mix/
        $year-$album%aunique{}[$label][$bitdepth\bit_$samplerate]/
        $track-$title

copyartifacts: 
  ext:jpg: $albumpath/scans/cover
  ext:png: $albumpath/scans/cover
  ext:pdf: $albumpath/scans/booklet


max_filename_length: 255     # 0 = unlimited.


ftintitle:
    auto: yes
    drop: no
    format: feat. {0}


# Last.fm #########################################################################################

lastimport:
  per_page: 500              # The number of tracks to request from the API at once. Default: 500.
  retry_limit: 3             # How many times should we re-send requests to Last.fm on failure? Default: 3.
lastfm:
  user: REDACTED
  api_key: REDACTED
types:
  play_count: int
  rating: float

lastgenre:
                             # Fetches tags from Last.fm and assigns them as genres to your albums and items.
  auto: yes                  # Fetch genres automatically during import. Default: yes.
                             # Use a canonicalization tree. Setting this to yes will use a built-in tree.
  canonical: ~/.config/beets/genres/genres-tree.yaml 
                             # The filename of a custom genre list, yes to use the internal whitelist, or no to consider all genres valid.
                             # Default: yes.
  whitelist: ~/.config/beets/genres/genres.txt
                             
                             
  count: 1                   # Number of genres to fetch. Default: 1
  fallback: 'No_Genre'       # A string if to use a fallback genre when no genre is found.
                             # You can use the empty string '' to reset the genre.
                             # Default: None.
  separator: ', '
  force: yes                 # By default, beets will always fetch new genres, even if the files already have one.
                             # To instead leave genres in place in when they pass the #whitelist: ~/.config/beets/genres.txt,
                             # set the force option to no.
  min_weight: 10             # Minimum popularity factor below which genres are discarded. Default: 10.
  prefer_specific: no        # Sort genres by the most to least specific, rather than most to least popular. Default: no.
  source: album              # Which entity to look up in Last.fm. Can be either artist, album or track. Default: album. 
  title_case: yes            # Convert the new tags to TitleCase before saving. Default: yes.




###########################################################################################

# MusicBrainz #####################################################################################

musicbrainz:
  user: REDACTED
  pass: REDACTED
  searchlimit: 20            # Recommendation from: https://github.com/kernitus/beets-oldestdate
  extra_tags:                # Enable improved MediaBrainz queries from tags.
    ["catalognum","country","label","media","year"]


match:
  max_rec:
    missing_tracks: medium
    unmatched_tracks: medium
  required: year label catalognum country

  preferred:
    media: ['CD','Digital Media|File', 'Digital Media'] # Priorize digital media.
    countries: ['US', 'GB|UK', 'CA', 'DE', 'XW']
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD',
                    'VCD', 'SVCD', 'UMD', 'VHS']
    original_year: yes
    ignore_data_tracks: yes
    ignore_video_tracks: yes
 

  strong_rec_thresh: 0.75    # Reflects the distance threshold below which beets will make a “strong recommendation” that the metadata be used.
                             # Strong recommendations are accepted automatically (except in “timid” mode),
                             # so you can use this to make beets ask your opinion more or less often.
                             # The threshold is a distance value between 0.0 and 1.0, so you can think of it as the opposite of a similarity value.
                             # For example, if you want to automatically accept any matches above 90% similarity, use: "strong_rec_thresh: 0.10"
                             # The default strong recommendation threshold is 0.04.
                             # When a match is below the medium recommendation threshold
                             # or the distance between it and the next-best match is above the gap threshold,
                             # the importer will suggest that match but not automatically confirm it.
                             # Otherwise, you’ll see a list of options to choose from.

  medium_rec_thresh: 0.125   # The medium_rec_thresh and rec_gap_thresh options work similarly.


mbcollection:
  auto: yes                  # Automatically amend your MusicBrainz collection whenever you import a new album.
  collection: REDACTED       # Which MusicBrainz collection to update. Use the ID from the URL instead of the name.
  remove: yes                # Remove albums from collections which are no longer present in the beets database.
                             # ToDo: remove doesn't work.

mbsubmit:                    # As MusicBrainz currently does not support submitting albums programmatically,
                             # the recommended workflow is to copy the output of the Print tracks choice and
                             # paste it into the parser that can be found by clicking on the “Track Parser” button on MusicBrainz “Tracklist” tab.
  format: $track. $title - $artist ($length)
                             # The format used for printing the tracks, defined using the same template syntax as beets’ path formats.
                             # Default: $track. $title - $artist ($length).
  threshold: medium          # The minimum strength of the autotagger recommendation that will cause the Print tracks choice to be displayed on the prompt.
                             # Default: medium (causing the choice to be displayed for all albums that have a recommendation of medium strength or lower).
                             # Valid values: none, low, medium, strong.
#permissions:
   # file: 644
    # dir: 755

###################################################################################################

#plex:
    #host: localhost
    #port: 32400
    #token: W7MS3QxNwJxi92PGKzz5

###################################################################################################

duplicates:
  albums: yes
  singles: yes
  checksum: ffmpeg -i {file} -f crc -
  keys: [mb_trackid, mb_albumid]
  tiebreak:
    items: [bitrate]

###################################################################################################

zero:
    auto: yes
    keep_fields: title artist album year track genre images bitrate samplerate
    update_database: true

###################################################################################################

#badfiles:
    #check_on_import: no
    #commands:
        #ogg: myoggchecker --opt1 --opt2
        #flac: flac --test --warnings-as-errors --silent

###################################################################################################
#beets-autofix:

#max_exec_time: 0
#tasks:
#  missing_file_checker:
  #   enabled: no
  # year_fixer:
  #   enabled: no
  # audio_conversion:
  #   enabled: no
  # tag_cleaner:
  #   enabled: yes
  # ab_data_fetcher:
  #   enabled: no
  # xtractor:
  #   enabled: no
  # genre_finder:
  #   enabled: no



###################################################################################################

#convert:
    #auto: no
    #ffmpeg: /usr/bin/ffmpeg
    #opts: -ab 320k -ac 2 -ar 48000
    #max_bitrate: 320
    #threads: 1

###################################################################################################
xtractor:
  auto: yes
  dry-run: no
  write: yes
  threads: 1
  force: no
  quiet: no
  keep_output: yes
  keep_profiles: no
  output_path: /Users/lefab/Documents/essentia-extractors-v2.1_beta2/xtraction_data
  essentia_extractor: /Users/lefab/Documents/essentia-extractors-v2.1_beta2/streaming_extractor_music
  extractor_profile:
    highlevel:
      svm_models:
        - /mnt/data/extractors/beta5/svm_models/danceability.history
        - /mnt/data/extractors/beta5/svm_models/gender.history
        - /mnt/data/extractors/beta5/svm_models/genre_rosamerica.history
        - /mnt/data/extractors/beta5/svm_models/mood_acoustic.history
        - /mnt/data/extractors/beta5/svm_models/mood_aggressive.history
        - /mnt/data/extractors/beta5/svm_models/mood_electronic.history
        - /mnt/data/extractors/beta5/svm_models/mood_happy.history
        - /mnt/data/extractors/beta5/svm_models/mood_sad.history
        - /mnt/data/extractors/beta5/svm_models/mood_party.history
        - /mnt/data/extractors/beta5/svm_models/mood_relaxed.history
        - /mnt/data/extractors/beta5/svm_models/voice_instrumental.history
        - /mnt/data/extractors/beta5/svm_models/moods_mirex.history
```
