### ISSUE TITLE
`beet write`: false positive for changes in fields with multiple values

### ISSUE THREAD

**Issue by celynw** [beetbox/beets#5371]
### Problem

It seems that for fields which allow multiple tags, the write command might incorrectly say there are changes to be made.

#### Backstory

I am using the [albumtypes](https://beets.readthedocs.io/en/latest/plugins/albumtypes.html) plugin to set the 'soundtrack' album type.

My relevant config looks like this:

```yml
albumtypes:
  types:
    - soundtrack: "OST"
    - ep: "EP"
    - single: "Single"
    - live: "Live"
    - compilation: "Anthology"
    - remix: "Remix"
  ignore_va: compilation
paths:
  default: $albumartist/$year - $album%aunique{}/%if{$multidisc,$paddisc-}$padtrack $title
  albumtype:soundtrack: Soundtracks/$album/%if{$multidisc,$paddisc-}$padtrack $title
  albumtypes:soundtrack: Soundtracks/$album/%if{$multidisc,$paddisc-}$padtrack $title
musicbrainz:
```

(I opened a [related discussion](https://github.com/beetbox/beets/discussions/4978), which was solved.)

Basically, if 'soundtrack' appears at all in MusicBrainz's `albumtypes` list, I'll set the main albumtype to soundtrack. This is because I prefer soundtrack to be the highest priority when something belongs to multiple types.

This _does_ work; I checked the database manually, and the types are set correctly:

| albumtype  | albumtypes        |
| ---------- | ----------------- |
| soundtrack | album; soundtrack |

I also checked the files themselves and found the data to also be correct.

```plaintext
RELEASETYPE     : album;soundtrack
MUSICBRAINZ_ALBUMTYPE: album;soundtrack
```

My issue is that when I run `beet write`, it tells me there are many changes to be made like:

```
albumtype: album -> soundtrack
```

This never clears; if I run the command again, it tries to do this again.

The issue seems to related to this part in [`mediafile`](https://github.com/beetbox/mediafile/blob/11c180078d6775f7c72dd182d9b6762061b677c7/mediafile.py#L1954):

```python
    albumtypes = ListMediaField(
        MP3ListDescStorageStyle('MusicBrainz Album Type', split_v23=True),
        MP4ListStorageStyle('----:com.apple.iTunes:MusicBrainz Album Type'),
        ListStorageStyle('RELEASETYPE'),
        ListStorageStyle('MUSICBRAINZ_ALBUMTYPE'),
        ASFStorageStyle('MusicBrainz/Album Type'),
    )
    albumtype = albumtypes.single_field()
```

`ListMediaField.single_field` returns the first item in `albumtypes`.

This comes up in the `write` command, `write_items()`, where a 'clean_item` is created from the file on disk:

https://github.com/beetbox/beets/blob/b88c09720c3f0782b90f83df74e65680c050392f/beets/ui/commands.py#L2285

It's a bit tricky, because both the file and the database are already correct, but because the write command thought there is a difference, it will attempt to write the corrections anyway.

- Beets' database holds both multiple (`albumtypes`) and single fields (`albumtype`) for that entry, and the single field can be configured by the user to choose which one from the multiple field
- Beets reads a field with multiple values and returns the first one to the write command
- Beets writes (only) the multiple values tag to the file
  - I haven't investigated with other media file types - this one is an FLAC

If the above is always true, a workaround which works for me is to add

```python
        if item.albumtype in clean_item.albumtypes:
            clean_item.albumtype = item.albumtype
```

before checking for the changes here:

https://github.com/beetbox/beets/blob/b88c09720c3f0782b90f83df74e65680c050392f/beets/ui/commands.py#L2293

I'm not sure if this is the most robust though.

Also, I guess it could apply to other 'multiple' fields too:

- genres
- catalognums
- languages
- mb_artistids
- mb_albumartistids

### Setup

* OS: Ubuntu 22.04
* Python version: 3.10.12
* beets version: 2.0.0
* Turning off plugins made problem go away (yes/no): N/A
