### ISSUE TITLE
Please help, newbie, had it running, but halfway through it keeps stopping

### ISSUE THREAD

**Issue by EchoShauf** [beetbox/beets#5430]
I keep getting "Error: The specified path is invalid while creating \\00.mp3", but this happens in the middle of it already working, I got it to import files but somehow it keeps stopping, and I cant find anything that is labeled or close to 00.mp3 or anything that has a file name of that. I have a lot of music that are unsorted, and I just want to have them be imported and sorted by artist, album, title

Edit: another error keeps coming up, "Error: The filename, directory name, or volume label syntax is incorrect while creating C:\Users\Jericho\AppData\Roaming\beets\‪D:" Windows? just trying to import "‪C:\Users\Jericho\Downloads\Music" to "D:\Beets Music"

### Problem

Running this config file:

```
beet import ‪C:\Users\Jericho\Downloads\Music
```

Led to this problem:

```
"Error: The specified path is invalid while creating \\00.mp3"
"Error: The filename, directory name, or volume label syntax is incorrect while creating C:\Users\Jericho\AppData\Roaming\beets\‪D:"
```

### Setup

* OS: Windows
* Python version: 3.12.6
* beets version: 2.0.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart scrub chroma web
directory: D:\Beets Music
library: D:\Beets Music\Index Library
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no


paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    cover_names: cover front art album folder

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337

```
