### ISSUE TITLE
Lastgenre changes other tags than only GENRE

### ISSUE THREAD

**Issue by isthatwyll** [beetbox/beets#5443]
### Setup

* OS: Windowd 10 23H2
* Python version: 3.12
* beets version: 2.0.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml

plugins: lastgenre

import:
    copy: no
    write: no
    move: no
    autotag: no
    incremental: no
lastgenre:
    min_weight: 10
    count: 4
    fallback:
    source: track
    force: no
    auto: yes
    separator: \\
    prefer_specific: yes
    title_case: yes
    whitelist: yes
    canonical: C:\Users\wylli\AppData\Roaming\beets\genres-tree.yaml
```
Before
![image](https://github.com/user-attachments/assets/14c5b9e6-cc51-4f97-9a58-8039d9e51b2d)

After
![image](https://github.com/user-attachments/assets/9aedd060-461e-4b2e-a9fd-7899489b9b59)
