### ISSUE TITLE
Fetchart Error: The process cannot access the file because it is being used by another process while moving

### ISSUE THREAD

**Issue by robuck86** [beetbox/beets#5521]
Why do I keep getting this error when using fetchart? When I use fetchart to find a cover (manually or on import) it seems to download and move ONE cover.jpg to the correct spot, crash and not delete the tmp files nor does it continue the queue. I've tried clearing the tmp folder, rebooting. Thought it works, I can only 'fetchart' one album at a time. 

```
``Error: The process cannot access the file because it is being used by another process while moving C:\Users\rob86\AppData\Local\Temp\beets\beetsplug_fetchart\xvbmqvlo.jpg to T:\navidrome\music\beets\XMAS\The Canadian Brass\Christmas With The Canadian Brass\cover.1.jpg` 

fetchart: The Coasters - Christmas With the Coasters: found album art
Error: The process cannot access the file because it is being used by another process while moving C:\Users\rob86\AppData\Local\Temp\beets\beetsplug_fetchart\gkj0rosm.jpg to T:\navidrome\music\beets\XMAS\Nat King Cole\The Magic of Christmas\cover.jpg
PS C:\beets> beet fetchart -q
fetchart: Nat King Cole - The Magic of Christmas: found album art
Error: The process cannot access the file because it is being used by another process while moving C:\Users\rob86\AppData\Local\Temp\beets\beetsplug_fetchart\_detmij9.jpg to T:\navidrome\music\beets\XMAS\Judy Collins\Christmas With Judy Collins\cover.jpg
PS C:\beets> beet fetchart -q
fetchart: Judy Collins - Christmas With Judy Collins: found album art
```
`

* OS: Windows 11
* Python version: 3.13
* beets version: 2.1.0
* Turning off plugins made problem go away (yes/no):  yes

My configuration (output of `beet config`) is:

```
lyrics:
    bing_lang_from: []
    import.write: no
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    synced: no
    sources:
    - google
    - genius
    - tekstowo
    - lrclib
    dist_thresh: 0.1
directory: T:/navidrome/music/beets
# --------------- Main ---------------

library: T:/navidrome/Test/musiclibrary.db

# --------------- Plugins ---------------

plugins: fetchart embedart discogs lastgenre lyrics mbsync smartplaylist spotify convert
paths:
    default: $albumartist/$album/$track $title
    singleton: Singletons/$artist - $title
    xmas:XMAS: XMAS/$albumartist/$album/$title
    comp: Compilation/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
convert:
    auto: no
    dest: T:/converted/
    pretend: no
    link: no
    hardlink: no
    threads: 16
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate:
    auto_keep: no
    tmpdir:
    quiet: no
    embed: yes
    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
    delete_originals: no
    playlist:
spotify:
    source_weight: 0.7
    mode: open
    region_filter: US
    show_failures: yes
    tiebreak: first
    regex: [{field: albumartist, search: Something, replace: Replaced}, {field: title, search: Something Else, replace: AlsoReplaced}]
    artist_field: albumartist
    album_field: album
    track_field: title
    client_id: 4e414367a1d14c75a5c5129a627fcab8
    client_secret: REDACTED
    tokenfile: spotify_token.json
lastgenre:
    count: 4
    separator: '; '
    whitelist: whitelist.txt
    source: track
    min_weight: 10
    fallback:
    canonical: no
    force: yes
    auto: yes
    prefer_specific: no
    title_case: yes

# --------------- Import ---------------

clutter:
- '*.jpg'
- '*.jpeg'
- '*.txt'
- '*.log'

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes

smartplaylist:
    relative_to: T:/navidrome/music/beets
    playlist_dir: T:/navidrome/music/beets
    forward_slash: no
    playlists: [{name: Xmas.m3u, query: 'xmas:XMAS'}]
    auto: yes
    uri_format:
    fields: []
    prefix: REDACTED
    urlencode: no
    pretend_paths: no
    output: m3u
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
    separator: ', '
    index_tracks: no
    append_style_genre: no
```
