### ISSUE TITLE
Underscores in comments are removed

### ISSUE THREAD

**Issue by imoBooze** [beetbox/beets#5524]
### Problem

When importing, any underscores in the comments field are removed. 

### Setup

* OS: NixOS 25.05.20241125.4633a7c (Warbler) x86_64
* Python version: 3.12.7
* beets version: 1.6.1
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```
copyartifacts:
    extensions:
    - .jpg
    - .lrc
    - .txt
    - '*/*'
    print_ignored: yes
directory: ~/Music_new

import:
    copy: yes
paths:
    default: $albumartist/$albumartist - $album ($year.$month.$day)/$disc $track $title

# --------------- Plugins ---------------

plugins:
- copyartifacts
- lastgenre
- scrub
- zero
zero:
    keep_fields:
    - title
    - artist
    - arranger
    - composer
    - lyricist
    - album
    - albumartist
    - disc
    - disctotal
    - track
    - tracktotal
    - year
    - month
    - day
    - genre
    - genres
    - asin
    - catalognum
    - catalognums
    - country
    - isrc
    - label
    - language
    - languages
    - media
    - script
    - comments
    - art
    - images
    update_database: yes
    auto: yes
    fields: []
scrub:
    auto: yes
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
```
