### ISSUE TITLE
Test fails on OpenBSD at 2.2.0: `At index 13 diff: b'\x00' != b'\x01'`

### ISSUE THREAD

**Issue by catap** [beetbox/beets#5527]
### Problem

```
/build/pobj/beets-2.2.0/beets-2.2.0/test/plugins/test_aura.py:57
=================================== FAILURES ===================================
___________________ EmbedartCliTest.test_accept_similar_art ____________________

args = (<test.plugins.test_embedart.EmbedartCliTest testMethod=test_accept_similar_art>,)
kwargs = {}

    def wrapper(*args, **kwargs):
        if not ArtResizer.shared.can_compare:
            raise unittest.SkipTest("compare not available")
        else:
>           return test(*args, **kwargs)

test/plugins/test_embedart.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.plugins.test_embedart.EmbedartCliTest testMethod=test_accept_similar_art>

    @require_artresizer_compare
    def test_accept_similar_art(self):
        self._setup_data(self.abbey_similarpath)
        album = self.add_album_fixture()
        item = album.items()[0]
        self.run_command("embedart", "-y", "-f", self.abbey_artpath)
        config["embedart"]["compare_threshold"] = 20
        self.run_command("embedart", "-y", "-f", self.abbey_similarpath)
        mediafile = MediaFile(syspath(item.path))
    
>       assert (
            mediafile.images[0].data == self.image_data
        ), f"Image written is not {displayable_path(self.abbey_similarpath)}"
E       AssertionError: Image written is not /build/pobj/beets-2.2.0/beets-2.2.0/test/rsrc/abbey-similar.jpg
E       assert b'\xff\xd8\xf...8\x7f\xff\xd9' == b'\xff\xd8\xf...f\x00\xff\xd9'
E         
E         At index 13 diff: b'\x00' != b'\x01'
E         Use -v to get more diff

```

### Setup

* OS: OpenBSD-current
* Python version: 3.11.10
* beets version: 2.2.0
* Turning off plugins made problem go away (yes/no): no

**Comment by snejus** [comment]
I know that `embedart` plugin depends on Pillow and ImageMagick, so the issue may have to do with this.

That's why in #5526 I suggested to exclude plugin tests from the sdist, since some of them depend not only on additional Python packages but also system packages, see below:

```toml
[tool.poetry.extras]
# inline comments note required external / non-python dependencies
absubmit = ["requests"] # extractor binary from https://acousticbrainz.org/download
aura = ["flask", "flask-cors", "Pillow"]
autobpm = ["librosa", "resampy"]
# badfiles # mp3val and flac
beatport = ["requests-oauthlib"]
bpd = ["PyGObject"] # python-gi and GStreamer 1.0+
chroma = ["pyacoustid"] # chromaprint or fpcalc
# convert # ffmpeg
docs = ["pydata-sphinx-theme", "sphinx"]
discogs = ["python3-discogs-client"]
embedart = ["Pillow"] # ImageMagick
embyupdate = ["requests"]
fetchart = ["beautifulsoup4", "langdetect", "Pillow", "requests"]
import = ["py7zr", "rarfile"]
# ipfs # go-ipfs
# keyfinder # KeyFinder
kodiupdate = ["requests"]
lastgenre = ["pylast"]
lastimport = ["pylast"]
lyrics = ["beautifulsoup4", "langdetect", "requests"]
metasync = ["dbus-python"]
mpdstats = ["python-mpd2"]
plexupdate = ["requests"]
reflink = ["reflink"]
replaygain = [
    "PyGObject",
] # python-gi and GStreamer 1.0+ or mp3gain/aacgain or Python Audio Tools or ffmpeg
scrub = ["mutagen"]
sonosupdate = ["soco"]
thumbnails = ["Pillow", "pyxdg"]
web = ["flask", "flask-cors"]
```
