### ISSUE TITLE
Debian package does not contain autobpm

### ISSUE THREAD

**Issue by guerda** [beetbox/beets#5572]
### Problem

If you install beets via `apt` on debian bookworm, it does not contain the `autobpm` plugin.  Starting beets with a config yields this warning:

```
** error loading plugin autobpm:
Traceback (most recent call last):
  File "/usr/share/beets/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'beetsplug.autobpm'
```

The [documentation page for autobpm](https://beets.readthedocs.io/en/stable/plugins/autobpm.html#install) contains the hint to install it via pip: `pip install beets[autobpm]`.
This is not possible with the system managed beets installation.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv
user configuration: /home/pi/.config/beets/config.yaml
data directory: /home/pi/.config/beets
plugin paths:
** error loading plugin autobpm:
Traceback (most recent call last):
  File "/usr/share/beets/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'beetsplug.autobpm'

Sending event: pluginload
library database: /home/pi/.beets/musiclibrary.db
library directory: /media/music
Sending event: library_opened
[help section here]
```

### Setup

* OS: raspberry pi OS based on Debian 12 bookwork
* Python version: 3.11.2
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): yes, the autobpm plugin

My configuration (output of `beet config`) is:

```yaml
threaded: yes
terminal_encoding: utf-8
directory: /media/music
library: ~/.beets/musiclibrary.db

match:
    preferred:
        countries:
        - DE
        - XE
        - XW
        - US
        - GB|UK
        media: [CD, Digital Media|File]
        original_year: yes
duplicate_action: merge
duplicate_verbose_prompt: yes

import:
    copy: no
    write: yes
    move: yes
    incremental: yes
    log: ~/.beets/import.log

plugins: inline convert web chroma replaygain duplicates fromfilename edit lastgenre autobpm
replaygain:
    backend: command
    auto: no
    overwrite: no
    threads: 4
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
    command: ''
    noclip: yes
web:
    host: 0.0.0.0
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    readonly: yes
acoustid:
    apikey: REDACTED
fetchart:
    auto: yes
    cautious: yes
musicbrainz:
    genres: yes
    external_ids:
        discogs: yes
        spotify: yes
        bandcamp: yes
autobpm:
    auto: yes
    overwrite: no
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
pathfields: {}
item_fields: {}
album_fields: {}
convert:
    dest:
    pretend: no
    link: no
    hardlink: no
    threads: 4
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    embed: yes
    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
    delete_originals: no
chroma:
    auto: yes
edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path

```
