### ISSUE TITLE
error: No matching items found. when removing album from library

### ISSUE THREAD

**Issue by trevordavies095** [beetbox/beets#5595]
### Problem

I went to remove an album from my library yesterday and ran into the issue below. It seems to be persistent across many other albums as well.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv remove '/Volumes/Backup/Media/Music/Adele/[2015] 25 [Columbia] (FLAC 16-44kHz)'
```

Led to this problem:

```
user configuration: /Users/ldaviesi/.config/beets/config.yaml
data directory: /Users/ldaviesi/.config/beets
plugin paths:
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
fetchart: To use Spotify as an album art source, you must install the beautifulsoup4 module. See the documentation for further details.
inline: adding item field multidisc
Sending event: pluginload
library database: /Volumes/Backup/Media/Music/beets/musiclibrary.db
library directory: /Volumes/Backup/Media/Music
Sending event: library_opened
Parsed query: AndQuery([PathQuery('path', '/Volumes/Backup/Media/Music/Adele/[2015] 25 [Columbia] (FLAC 16-44kHz)', fast=True, case_sensitive=False)])
Parsed sort: NullSort()
error: No matching items found.
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: macOS 15.2
* Python version: Python 3.12.4
* beets version: beets version 2.2.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /Volumes/Backup/Media/Music
library: /Volumes/Backup/Media/Music/beets/musiclibrary.db
threaded: yes
per_disc_numbering: yes
asciify_paths: yes

plugins: missing lastgenre mbsync describe badfiles yearfixer lastgenre inline copyartifacts fetchart
fetchart:
  minwidth: 1000
  maxwidth: 1000
  cover_names: front back
  sources: itunes *
  cautious: yes


badfiles:
  check_on_import: yes
  commands:
      ogg: myoggchecker --opt1 --opt2
      flac: flac --test --warnings-as-errors --silent
      mp3: mp3val

copyartifacts:
  extensions: .cue .log .jpg .CUE .LOG .JPG

match:
  strong_rec_thresh: 0.05
  max_rec:
    source: strong
    artist: strong
    album: strong
    media: strong
    mediums: strong
    year: strong
    country: strong
    label: strong
    catalognum: strong
    albumdisambig: strong
    album_id: strong
    tracks: strong
    missing_tracks: medium
    unmatched_tracks: medium
    track_title: strong
    track_artist: strong
    track_index: strong
    track_length: strong
    track_id: strong
  preferred:
    media: ['CD|File', 'CD']
    countries: ['DE', 'XW', 'US', 'GB|UK']


item_fields:
  multidisc: 1 if disctotal > 1 else 0

# Display the bitdepth and sample rate if the file is flac
# Directory and naming scheme.
paths:
  default: %if{$albumartist_sort, %asciify{$albumartist_sort}, %asciify{$albumartist}}/%if{$year,[$year] %asciify{$album},%asciify{$album}}%if{$label, [%asciify{$label}]} ($format%if{$bitdepth, $bitdepth-$samplerate})/%if{$multidisc,$disc-}$track %asciify{$title}
  singleton: %if{$albumartist_sort, %asciify{$albumartist_sort}, %asciify{$albumartist}}/Non-Album/%asciify{$title}
  albumtype:soundtrack: Soundtracks/%if{$year,[$year] %asciify{$album},%asciify{$album}}%if{$label, [%asciify{$label}]} ($format%if{$bitdepth, $bitdepth-$samplerate})/%if{$multidisc,$disc-}$track %asciify{$title}
  comp: Compilations/%if{$year,[$year] %asciify{$album},%asciify{$album}}%if{$label, [%asciify{$label}]} ($format%if{$bitdepth, $bitdepth-$samplerate})/%if{$multidisc,$disc-}$track - %asciify{$artist} - %asciify{$title}

import:
  bell: yes
```
