### ISSUE TITLE
`beet convert --format <format>` does not override `convert: never_convert_lossy_files: yes` (it should)

### ISSUE THREAD

**Issue by zacharyburnett** [beetbox/beets#5625]
### Problem

if `never_convert_lossy_files` is set:
```yaml
convert:
  never_convert_lossy_files: yes
```

then even if I run, for instance:
```
beet convert format:mp3 --format opus
```
the MP3 files will not be converted to OPUS, even though I specifically requested that they be converted

### Setup

* OS: linux
* Python version: 3.13.1
* beets version: 2.1.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/Music/
plugins: convert fish duplicates badfiles edit chroma fetchart replaygain unimported

import:
  reflink: auto

chroma:
    auto: no

replaygain:
  auto: no
  backend: ffmpeg

clutter:
  - "*.jpg"
  - "*.nfo"
  - "*.png"
  - "*.lrc"

convert:
  auto: yes
  format: flac
  never_convert_lossy_files: yes
```
