### ISSUE TITLE
Beets uses the full artist name from MusicBrainz when the song in MusicBrainz uses an alias instead

### ISSUE THREAD

**Issue by yunfachi** [beetbox/beets#5633]
### Problem

When importing a song, the full artist name from MusicBrainz is used, whereas the same song in MusicBrainz uses an alias for this artist instead of the full name.

An example of a release where this issue occurs: https://musicbrainz.org/release/8a7cefcc-bbf7-443e-b0e6-216e4bebdc2a  

Initially, the song had the artist set as `アーリャ` (which is correct and used everywhere), but beets replaces it with `アリサ・ミハイロヴナ・九条`:

```sh
beet -vv --plugins= import ./01.秘密の言葉.flac
```
![Image](https://github.com/user-attachments/assets/b3e226d3-5ed7-49a1-b84b-c025819e49aa)

### Setup

* OS: Linux, NixOS
* Python version: 3.12.8
* beets version: 2.1.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    force: yes
    sources:
    - lrclib
    - genius
    - tekstowo
    - google
    synced: yes
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    local: no
    dist_thresh: 0.1
directory: /media/music

import:
    from_scratch: yes
lastgenre:
    count: 3
    whitelist: yes
    min_weight: 10
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
# --------------- Main ---------------

library: /media/music_beets.db
paths:
    comp: Compilations/$album%aunique{}/$track $title
    default: $albumartist - $album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title

# --------------- Plugins ---------------

plugins:
- spotify
- mbsync
- lastgenre
- lyrics
- fetchart
- thumbnails
- embedart
- replaygain
- duplicates
- missing
- subsonicupdate
replaygain:
    backend: ffmpeg
    overwrite: yes
    parallel_on_import: yes
    r128: [flac, mp3]
    r128_targetlevel: 84
    targetlevel: 89
    auto: yes
    threads: 32
    per_disc: no
    peak: 'true'
spotify:
    show_failures: yes
    source_weight: 0.5
    mode: list
    tiebreak: popularity
    artist_field: albumartist
    album_field: album
    track_field: title
    region_filter:
    regex: []
    client_id: 4e414367a1d14c75a5c5129a627fcab8
    client_secret: REDACTED
    tokenfile: spotify_token.json
subsonic:
    auth: password
    pass: REDACTED
    url: http://0.0.0.0:4533
    user: beets_subsonicupdate
missing:
    count: no
    total: no
    album: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
thumbnails:
    auto: yes
    force: no
    dolphin: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
```
