### ISSUE TITLE
Fuzzy Search Plugin not returning sensible results.

### ISSUE THREAD

**Issue by kitizz** [beetbox/beets#5638]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vvv list '%%Pompeya'
```

Led to this problem:

```
user configuration: /home/user/.config/beets/config.yaml
data directory: /home/user/.config/beets
plugin paths:
fetchart: google: Disabling art source due to missing key
Sending event: pluginload
library database: /home/user/.../beets_library_database.blb
library directory: /.../music_raw
Sending event: library_opened
Parsed query: AndQuery([AnyFieldQuery('Pompeya', ('artist', 'title', 'comments', 'album', 'albumartist', 'genre'), FuzzyQuery)])
Parsed sort: NullSort()
Taylor Swift - 1989 (Taylor’s version) (deluxe) - Style (Taylor’s version)
Taylor Swift - Red (Taylor’s version) - 22 (Taylor’s version)
Sending event: cli_exit
```

Whereas I got the expected result from this command:
```sh
beet -vvv list 'Pompeya'
```

Output:
```
<skip config info>
Parsed query: AndQuery([AnyFieldQuery('Pompeya', ('artist', 'title', 'comments', 'album', 'albumartist', 'genre'), SubstringQuery)])
Parsed sort: NullSort()
Pompeya - Real - Anyway
Pompeya - Real - Pasadena
Pompeya - Real - Ooooo (Cry About It)
Pompeya - Real - To the Orient
Pompeya - Real - Real
Pompeya - Real - Liar
Pompeya - Real - Hysteria
Pompeya - Real - Tell Me, Tell Me
Pompeya - Real - To a Kid
Pompeya - Real - Last One
Sending event: cli_exit
```

### Setup

* OS: Debian 12
* Python version: 3.13.2
* beets version: 2.2.0
* Turning off plugins made problem go away (yes/no): NA

My configuration (output of `beet config`) is:

```yaml
# --------------- Main ---------------

library: /home/kit/.../beets_library_database.blb
directory: /.../music_raw

# --------------- Plugins ---------------

plugins: [fuzzy]
fuzzy:
    prefix: '%%'
    threshold: 0.7
```
