### ISSUE TITLE
UserWarning for Autobpm plugin

### ISSUE THREAD

**Issue by nullmonk** [beetbox/beets#5640]
### Problem

Beets is generating a Warning when importing files with the autobpm plugin enabled.

```
/home/user/.local/lib/python3.9/site-packages/beetsplug/autobpm.py:64: UserWarning: PySoundFile failed. Trying audioread instead.                                                                                                           
  y, sr = librosa.load(item.filepath, res_type="kaiser_fast")                                                         
/home/user/.local/lib/python3.9/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread
_load                                                                                                                 
        Deprecated as of librosa version 0.10.0.                                                                      
        It will be removed in librosa version 1.0.
```

Pip versions:

### Setup
* OS: Debian 11 (bullseye)
* Python version: 3.9.2
* beets version: 2.2.0
* Turning off plugins made problem go away (yes/no): Yes

Pip versions:
```
audioread      3.0.1
librosa            0.10.2.post1
```

My configuration (output of `beet config`) is:

```yaml
autobpm:                                                                                                              
    auto: yes                                                                                                         
    overwrite: no                                                                                                     
    beat_track_kwargs: {} 
```
