### ISSUE TITLE
unreadable file on Tenacity WAV file

### ISSUE THREAD

**Issue by WilsontheWolf** [beetbox/beets#5679]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import .
user configuration: /home/shorty/.config/beets/config.yaml
data directory: /home/shorty/.config/beets
plugin paths: 
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
fetchart: To use Spotify as an album art source, you must install the beautifulsoup4 module. See the documentation for further details.
Sending event: pluginload
library database: /home/shorty/Music/musiclibrary.db
library directory: /home/shorty/Music/sorted
Sending event: library_opened
Sending event: import_begin
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/Cutting it Fine.wav
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/Heat of the Moment.wav
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/Here Comes the Feeling.wav
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/One Step Closer.wav
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/Only Time Will Tell.wav
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/Sole Survivor.wav
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/Time Again.wav
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/Wildest Dreams.wav
unreadable file: /home/shorty/Audio/Records/To Import/tmp/Asia/Without You.wav
No files imported from /home/shorty/Audio/Records/To Import/tmp
```

Led to this problem:

I split a record I recorded using Tenacity (Audacity fork). Followed this guide: https://support.audacityteam.org/audio-editing/splitting-a-recording-into-separate-tracks

Here's a link to the music files that trigger the bug (if relevant):

http://shorty.systems/Heat%20of%20the%20Moment.wav

### Setup

* OS: Fedora 41
* Python version: Python 3.13.2
* beets version: 2.2.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/sorted
# --------------- Main ---------------

library: ~/Music/musiclibrary.db

# --------------- Plugins ---------------

plugins: fetchart

import:
    move: yes

match:
    max_rec:
        missing_tracks: none
fetchart:
    maxwidth: 500
    sources: filesystem coverart itunes amazon albumart wikipedia
    auto: yes
    minwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED

```
