### ISSUE TITLE
`beet mod -a` splits a single provided `artists` tag into a multi-tagged `artists` with one `artists` per character

### ISSUE THREAD

**Issue by afontenot** [beetbox/beets#5690]
### Problem

I was trying to fix the `artists` tag that was tagged incorrectly on one of my albums. This album has a single artist, so I only needed to specify one. I'm encountering a strange issue, though. When specifying the tag when in album mode, the track metadata is still set (as expected), but the provided artist name gets split. This doesn't happen when setting the tag directly on the track.

Here's an illustration

```sh
$ beet mod -a -w 'brat' artists='Charli XCX'
Modifying 2 albums.
Charli XCX - BRAT
  artists: Charli xcx -> Charli XCX
Charli XCX - Brat and it’s completely different but also still brat
  artists: Charli xcx -> Charli XCX
Really modify, move and write tags? (Yes/no/select) 

$ beet info 'i might say something' | grep ' artists:'
            artists: C; h; a; r; l; i;  ; X; C; X
            artists: C; h; a; r; l; i;  ; X; C; X
            artists: C; h; a; r; l; i;  ; X; C; X
$ beet mod -w 'I might say something stupid' artists='Charli XCX'
Modifying 3 items.
Charli XCX - BRAT - I might say something stupid
  artists: C\␀h\␀a\␀r\␀l\␀i\␀ \␀X\␀C\␀X -> Charli XCX
Charli XCX - Brat and it’s completely different but also still brat - I might say something stupid
  artists: C\␀h\␀a\␀r\␀l\␀i\␀ \␀X\␀C\␀X -> Charli XCX
Charli XCX - Brat and it’s completely different but also still brat - I might say something stupid
  artists: C\␀h\␀a\␀r\␀l\␀i\␀ \␀X\␀C\␀X -> Charli XCX
Really modify, move and write tags? (Yes/no/select) 

$ beet info 'i might say something' | grep ' artists:'
            artists: Charli XCX
            artists: Charli XCX
            artists: Charli XCX
```

### Setup

* OS: Ubuntu 22.04
* Python version: 3.10.12
* beets version: 2.2.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/data/audio
# --------------- Main ---------------

library: ~/.config/beets/music.blb
pluginpath: ~/.local/share/beets/plugins

# --------------- Plugins ---------------

plugins: convert copyartifacts fetchart inline permissions replaygain zero info mbsync
medium_rec_thresh: -1.0

import:
    detail: yes
    move: yes
    timid: yes
    searchlimit: 8
copyartifacts:
    extensions: .cue .log
    print_ignored: no
zero:
    fields: albumartist_credit albumstatus artist_credit acoustid_id acoustid_fingerprint
    auto: yes
    keep_fields: []
    update_database: no
art_filename: folder

# --------------- Tagging ---------------

per_disc_numbering: yes
incremental: yes
artist_credit: yes
paths:
    albumtype:soundtrack: soundtracks/$authorcredit/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    albumtype:single: singles/$albumartist/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    albumgenre:soundtrack: soundtracks/$authorcredit/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    albumgenre:classical: composers/$authorcredit/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    albumgenre:instrumental: composers/$authorcredit/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    albumgenre:experimental: experimental/$albumartist/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    albumgenre:jazz: jazz/$albumartist/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    comp: music/$albumartist/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    default: music/$albumartist/$album ($year)%aunique{}/%if{$multidisc,Disc $disc/}$track - $title

aunique:
    keys: albumartist album year
    disambiguators: albummediatype albummedia label catalognum
album_fields:
    albummediatype: "m_0 = items[0].get(\"mediatype\")\nif m_0 and all(m_0 == item.get(\"mediatype\") for item in items[1:]):\n    return m_0\nreturn \"\"\n"
    albummedia: "m_0 = items[0].get(\"media\")\nif m_0 and all(m_0 == item.get(\"media\") for item in items[1:]):\n    return m_0\nreturn \"\"\n"
    albumgenre: "try:\n    return classification\nexcept NameError:\n    pass\ntry:\n    return genre.lower()\nexcept NameError:\n    return \"\"\n"
    authorcredit: "c_0 = items[0].get(\"composer\")\nif c_0 and all(c_0 == item.get(\"composer\") for item in items[1:]):\n    return c_0\na_0 = items[0].get(\"artist\")\nif a_0 and all(a_0 == item.get(\"artist\") for item in items[1:]):\n    return a_0\nreturn albumartist\n"
item_fields:
    multidisc: 1 if disctotal > 1 else 0

# --------------- Paths ---------------

path_sep_replace: "\u29F8"
replace:
    \\: "\u29F8"
    ^\.: ''
    '[\x00-\x1f]': ''
    \.$: ''
    \s+$: ''
convert:
    format: opus
    never_convert_lossy_files: yes
    album_art_maxwidth: 1080
    dest:
    pretend: no
    link: no
    hardlink: no
    threads: 8
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate:
    auto: no
    auto_keep: no
    tmpdir:
    quiet: no
    embed: yes
    paths: {}
    no_convert: ''
    copy_album_art: no
    delete_originals: no
    playlist:
replaygain:
    backend: ffmpeg
    overwrite: no
    auto: yes
    threads: 8
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
pathfields: {}
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
permissions:
    file: '644'
    dir: '755'


```

**Comment by caregan2004** [comment]
Hey! I am a UofM university student and for the next 2 weeks I am looking into open source issues for an assignment. I'm current investigating this bug, and will return with a pull request as soon as possible.

**Comment by amelimik** [comment]
> Hey! I am a UofM university student and for the next 2 weeks I am looking into open source issues for an assignment. I'm current investigating this bug, and will return with a pull request as soon as possible.

I have reproduced this bug on my local machine as well, if that helps 😊

OS: MacOS Sonoma 14.6.1
Python version: 3.13.2
beets version: 2.2.0
Turning off plugins made problem go away (yes/no): no

My configuration (output of beet config) is:
```
directory: ~/Music
# --------------- Main ---------------

library: ~/Music/Music.db

import:
    move: yes
    copy: no
    write: no

# --------------- Plugins ---------------

plugins: spotify info
spotify:
    mode: open
    source_weight: 0.5
    tiebreak: popularity
    show_failures: no
    artist_field: albumartist
    album_field: album
    track_field: title
    region_filter:
    regex: []
    client_id: 4e414367a1d14c75a5c5129a627fcab8
    client_secret: REDACTED
    tokenfile: spotify_token.json
```
