### ISSUE TITLE
Beets incorrectly matches track for partially imported album

### ISSUE THREAD

**Issue by laker-93** [beetbox/beets#5715]
When importing tracks piecemeal for an album (e.g. 2 / 11 tracks first, then an additional 1 track), the second import mistags the track title.

### Problem

Current state of an album in my beets collection:

```
root@1ab6c0d68037:/# beet ls Skee -p
/music/Skee Mask/C/02 - Bassline Dub.mp3
/music/Skee Mask/C/04 - Aktif Garbon.mp3
```

Now I attempt to import track 6 on its own with the following single track in my import directory:

```
/downloads/uploads/Skee Mask/C/One For Vertigo.mp3
```

running:

```
beet import --group-albums /downloads/
```

gives:

```
/downloads/uploads/Skee Mask/C/One For Vertigo.mp3 (1 items)

  Match (85.0%):
  Skee Mask - C
  ≠ tracks
  MusicBrainz, Digital Media, 2024, XW, None, None, None
  https://musicbrainz.org/release/9131b04f-c997-4e5a-9273-563e9c67e8b8
  * Artist: Skee Mask
  * Album: C
     ≠ (#0) One For Vertigo.mp3 (4:22) -> (#5) FFB7 Dub (4:24)
Missing tracks (10/11 - 90.9%):
 ! MDP2 (#1) (5:46)
 ! Bassline Dub (#2) (5:00)
 ! Keygruv (#3) (5:37)
 ! Aktif Garbon (#4) (5:34)
 ! One For Vertigo (#6) (4:22)
 ! Minitx (#7) (4:20)
 ! 11616 (#8) (4:56)
 ! Blok (#9) (5:12)
 ! Pitchacid (#10) (4:39)
 ! thnk u (#11) (4:20)
```

As you can see the beet import got the matching badly wrong despite the tags for the track being imported set correctly.
Why doesn't beets correctly match the incoming 'One For Vertigo.mp3'?

### Setup

Running as docker container using latest beets image.



My configuration (output of `beet config`) is:

```yaml
plugins: web fetchart lyrics lastgenre embedart duplicates info subsonicupdate fuzzy                                                                                                                                  
directory: /music                                                                                                                                                                                                     
library: /config/musiclibrary.blb                                                                                                                                                                                     
art_filename: albumart                                                                                                                                                                                                
threaded: no                                                                                                                                                                                                          
original_date: no                                                                                                                                                                                                     
per_disc_numbering: no                                                                                                                                                                                                
                                                                                                                                                                                                                      
  #convert:                                                                                                                                                                                                           
  #    auto: no                                                                                                                                                                                                       
  #    ffmpeg: /usr/bin/ffmpeg                                                                                                                                                                                        
  #    opts: -ab 320k -ac 2 -ar 48000                                                                                                                                                                                 
  #    max_bitrate: 320                                                                                                                                                                                               
  #    threads: 1                                                                                                                                                                                                     
                                                                                                                                                                                                                      
match:                                                                                                                                                                                                                
  # want to accept a match automatically if it is greater than                                                                                                                                                        
  # 80%.                                                                                                                                                                                                              
  # in order to do that must make beets ignore certain                                                                                                                                                                
  # attributes to prevent it downgrading from a strong rec and                                                                                                                                                        
  # therefore not accepting a match in quiet mode.                                                                                                                                                                    
  max_rec:                                                                                                                                                                                                            
    missing_tracks: strong                                                                                                                                                                                            
    unmatched_tracks: strong                                                                                                                                                                                          
  ignored: missing_tracks                                                                                                                                                                                             
  strong_rec_thresh: 0.20                                                                                                                                                                                             
  # don't mind if tracks are missing from an album                                                                                                                                                                    
  distance_weights:                                                                                                                                                                                                   
    missing_tracks: 0                                                                                                                                                                                                 
                                                                                                                                                                                                                      
paths:                                                                                                                                                                                                                
    default: $albumartist/$album/$track - $title                                                                                                                                                                      
    singleton: Non-Album/$artist - $title                                                                                                                                                                             
    comp: Compilations/$album/$track - $title                                                                                                                                                                         
    albumtype_soundtrack: Soundtracks/$album/$track $title                                                                                                                                                            
                                                                                                                                                                                                                      
import:                                                                                                                                                                                                               
    write: yes                                                                                                                                                                                                        
    # we copy so pymix can remove the import src dir when the                                                                                                                                                         
    # process has completed successfully.                                                                                                                                                                             
    copy: yes                                                                                                                                                                                                         
    move: no                                                                                                                                                                                                          
    resume: ask                                                                                                                                                                                                       
    incremental: no                                                                                                                                                                                                   
    incremental_skip_later: no                                                                                                                                                                                        
    # keep and defer to the duplicates plugin for resolving                                                                                                                                                           
    duplicate_action: keep                                                                                                                                                                                            
    quiet_fallback: asis                                                                                                                                                                                              
    timid: no                                                                                                                                                                                                         
    log: /config/beet.log                                                                                                                                                                                             
                                                                                                                                                                                                                      
      #lastgenre:                                                                                                                                                                                                     
      #    auto: yes                                                                                                                                                                                                  
      #    source: album                                                                                                                                                                                              
                                                                                                                                                                                                                      
embedart:                                                                                                                                                                                                             
    auto: yes                                                                                                                                                                                                         
    remove_art_file: yes                                                                                                                                                                                              
                                                                                                                                                                                                                      
fetchart:                                                                                                                                                                                                             
    auto: yes                                                                                                                                                                                                         
                                                                                                                                                                                                                      
replaygain:                                                                                                                                                                                                           
    auto: no                                                                                                                                                                                                          
                             
scrub:                                                                                                                                                                                                                
    auto: yes                                                                                                                                                                                                         
                                                                                                                                                                                                                      
replace:                                                                                                                                                                                                              
    '^\.': _                                                                                                                                                                                                          
    '[\x00-\x1f]': _                                                                                                                                                                                                  
    '[\xE8-\xEB]': e                                                                                                                                                                                                  
    '[\xEC-\xEF]': i                                                                                                                                                                                                  
    '[\xE2-\xE6]': a                                                                                                                                                                                                  
    '[\xF2-\xF6]': o                                                                                                                                                                                                  
    '[\xF8]': o                                                                                                                                                                                                       
    #'\.$': _                                                                                                                                                                                                         
    '\s+$': ''                                                                                                                                                                                                        
                                                                                                                                                                                                                      
web:                                                                                                                                                                                                                  
    host: 0.0.0.0                                                                                                                                                                                                     
    port: 8337                                                                                                                                                                                                        
    readonly: false                                                                                                                                                                                                   
                                                                                                                                                                                                                      
lyrics:                                                                                                                                                                                                               
    auto: no                                                                                                                                                                                                          
                                                                                                                                                                                                                      
duplicates:                                                                                                                                                                                                           
    keys:                                                                                                                                                                                                             
        - mb_trackid                                                                                                                                                                                                  
        - mb_albumid                                                                                                                                                                                                  
        - title                                                                                                                                                                                                       
        - album                                                                                                                                                                                                       
    tag: dup=1 
```
