### ISSUE TITLE
Beets can't find a match.

### ISSUE THREAD

**Issue by Mycah** [beetbox/beets#5805]
### Problem

Beets can't find a match during import even when specifying the musicbrainz url with multiple albums after updating to latest commit.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import .
user configuration: /home/user/.config/beets/config.yaml
data directory: /home/user/.config/beets
plugin paths:
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
inline: adding item field cdtitle
inline: adding item field multidisc
inline: adding item field initial
inline: adding item field nicelength
inline: adding album field cdtype
inline: adding album field notalbum
Sending event: pluginload
library database: /home/user/.beets.db
library directory: /home/user/music/user
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/user/Downloads/music/KMFDM - Hyena (2002) [V0]
Tagging KMFDM - Hyëna
No album ID found.
Search terms: KMFDM - Hyëna
Album might be VA: False
Evaluating 0 candidates.

/home/user/Downloads/music/KMFDM - Hyena (2002) [V0] (11 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
No matching release found for 11 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
➜ [S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort,
Print tracks, Open files with Picard? I
Enter release ID: https://musicbrainz.org/release/6b3229ee-b6b6-420b-bec0-2bdb1a6d1ab5
Tagging KMFDM - Hyëna
Searching for album ID: https://musicbrainz.org/release/6b3229ee-b6b6-420b-bec0-2bdb1a6d1ab5
Evaluating 0 candidates.
Sending event: before_choose_candidate
No matching release found for 11 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
➜ [S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort,
Print tracks, Open files with Picard?

```

Led to this problem:

Unable to identify album for an album that exists. (Fails on all albums I try)

### Setup

* OS: ubuntu 24.04
* Python version: 3.12.3
* beets version: 2.3.1
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
# --------------- Main ---------------

library: ~/.beets.db
directory: ~/music/

# --------------- Plugins ---------------

plugins:
- convert
- duplicates
- fromfilename
- fuzzy
- info
- inline
- lastgenre
- mbsync
- missing
- badfiles
- random
- scrub
- the
- fetchart
- embedart
- web
- mbsubmit
replace:
    "\u201C": '"'
    "\u201D": '"'
    "\u2010": '-'
    "\u2011": '-'
    "\u2012": '-'
    "\u2013": '-'
    "\u2014": '-'
    "\u2015": '-'
    "\u2016": '-'
    "\u2026": '...'
original_date: yes

# --------------- Tagging ---------------

per_disc_numbering: yes

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
    distance_weights:
        missing_tracks: 10.0
    ignore_video_tracks: no
asciify_paths: no
paths:
    default: $albumartist/%if{$year,$year - }$album%aunique{}/$track - $title%aunique{}
    singleton: $albumartist/%if{$year,$year - }$album%aunique{}/$track - $title%aunique{}
    comp: Compilation/%if{$year,$year - }$album%aunique{}/$track - $artist - $title%aunique{}
    albumtype:soundtrack: Soundtracks/%if{$year,$year - }$album%aunique{}/$track - $artist - $title%aunique{}
item_fields:
    cdtitle: u' - %s' % (disctitle) if disctitle else u''
    multidisc: 1 if disctotal > 1 else 0
    initial: artist.lower().lstrip('[]*')[0]
    nicelength: 'm, s = divmod(length, 60)

        h, m = divmod(m, 60)

        return "%d:%02d:%02d" % (h, m, s)

        '
album_fields:
    cdtype: u'[%s]' % (albumtype.lower()) if albumtype else u''
    notalbum: 0 if albumtype and albumtype.lower() == 'album' else 1
pathfields: {}

import:
    log: ~/beets.log
    write: yes
    copy: yes
convert:
    formats:
        alac:
            extension: m4a
            command: ffmpeg -i $source -y -vn -acodec alac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
        mp3: ffmpeg -i $source -y -vn -qscale:a 0 $dest
        aac:
            extension: m4a
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
    max_bitrate: 500
    embed: yes
    dest:
    copy_album_art: yes
    threads: 4
    never_convert_lossy_files: no
    pretend: no
    format: mp3
    tmpdir:
    quiet: no
    paths: {}
    auto: yes
    link: no
    hardlink: no
    id3v23: inherit
    auto_keep: no
    no_convert: ''
    album_art_maxwidth: 0
    delete_originals: no
    playlist:
web:
    include_paths: no
    cors: ''
    port: 8337
    host: 127.0.0.1
    cors_supports_credentials: no
    reverse_proxy: no
    readonly: yes
fetchart:
    auto: yes
    minsize: 350
    maxsize: 700
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    lastfm_key: REDACTED
    fanarttv_key: REDACTED
    google_key: REDACTED
    google_engine: REDACTED
embedart:
    auto: yes
    remove_art_file: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    quality: 0
fuzzy:
    prefix: '~'
    threshold: 0.7
mbsubmit:
    format: $track. $title - $artist ($length)
    threshold: medium
    picard_path: picard
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
missing:
    count: no
    total: no
    album: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: no
    keep_existing: no
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
    extended_debug: no
scrub:
    auto: yes
```

I just ran `python -m pip install --upgrade git+https://github.com/beetbox/beets.git` previous to the failures.  Last time I ran beets it was fine.

Output of the upgrade:
```
python -m pip install --upgrade git+https://github.com/beetbox/beets.git
Collecting git+https://github.com/beetbox/beets.git
  Cloning https://github.com/beetbox/beets.git to /tmp/pip-req-build-fz_1heaz
  Running command git clone --filter=blob:none --quiet https://github.com/beetbox/beets.git /tmp/pip-req-build-fz_1heaz
  Resolved https://github.com/beetbox/beets.git to commit e439c04d89d14d993a2b381ad92ad7dd1b72c733
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: confuse>=1.5.0 in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (2.0.1)
Requirement already satisfied: jellyfish in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (1.1.0)
Requirement already satisfied: lap>=0.5.12 in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (0.5.12)
Requirement already satisfied: mediafile>=0.12.0 in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (0.13.0)
Requirement already satisfied: musicbrainzngs>=0.4 in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (0.7.1)
Requirement already satisfied: numpy>=1.24.4 in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (2.1.1)
Requirement already satisfied: platformdirs>=3.5.0 in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (4.3.6)
Requirement already satisfied: pyyaml in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (6.0.2)
Requirement already satisfied: unidecode>=1.3.6 in ./venv/lib/python3.12/site-packages (from beets==2.3.1) (1.3.8)
Requirement already satisfied: mutagen>=1.46 in ./venv/lib/python3.12/site-packages (from mediafile>=0.12.0->beets==2.3.1) (1.47.0)
Requirement already satisfied: filetype>=1.2.0 in ./venv/lib/python3.12/site-packages (from mediafile>=0.12.0->beets==2.3.1) (1.2.0)
Building wheels for collected packages: beets
  Building wheel for beets (pyproject.toml) ... done
  Created wheel for beets: filename=beets-2.3.1-py3-none-any.whl size=563732 sha256=32df61f71974becd90c06113caff5d30b9924be411461d4516ba3f024d7943fb
  Stored in directory: /tmp/pip-ephem-wheel-cache-8t41gu31/wheels/be/aa/fb/88d1e38db5e53411aa7a67cf321e19dec4304512c947bf950f
Successfully built beets
Installing collected packages: beets
  Attempting uninstall: beets
    Found existing installation: beets 2.3.0
    Uninstalling beets-2.3.0:
      Successfully uninstalled beets-2.3.0
Successfully installed beets-2.3.1
```
