### ISSUE TITLE
ReplayGain Plugin: Add details how to use GStreamer on Ubuntu

### ISSUE THREAD

**Issue by milnak** [beetbox/beets#5817]
I've found that ReplayGain plugin has issues in default config (see #5449 ) so I decided to use GStreamer which seems to work, however, there's no documentation on how to set up and use GStreamer on Ubuntu.

Here's how I got it to work:

```shell
# Install PyGObject (python-gi)
sudo apt-get install python3-gi

# Install gstreamer
sudo apt-get install libcairo2-dev libgirepository-2.0-dev gstreamer-1.0 gstreamer1.0-tools gstreamer1.0-plugins-* --yes
pip install PyGObject
```

Then modify the beets/config.yaml to have (for example):

```yaml
plugins: replaygain
replaygain:
    backend: gstreamer
    auto: no
    overwrite: no
    targetlevel: 89
```

and then run

```shell
beet --verbose  replaygain --write
```
