### ISSUE TITLE
Discogs (and other metadata sources) polluting mb_albumid

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#604]
The discogs plugin sets `album_id` of the `AlbumInfo` class to a discogs identifier, which `beets.autotag.apply_metadata` assigns to `mb_albumid`. The problem is that everywhere else it's assumed to be a MusicBrainz identifier.

**Comment by dengste** [comment]
I just wanted to add that this is also true for the artist_id. If an album is identified via discogs, it will be tagged with discogs' artist-id. I stumbled upon this because when I import my library into Ampache, it will frequently have the same artist twice - one with the Musicbrainz id, and one with Discogs', and I have to manually fix that.

**Comment by skupjoe** [comment]
It's also worth noting that the Dicogs data source does not supply mb_trackid information, so (by default) the Duplicates plugin will flag anything that shares null entries for this field as duplicate. Meaning, all Discogs-tagged tracks will be flagged as a duplicate.

The workaround is to additionally add a third parameter to the Duplicate plugin to lastly analyze Title.

**Comment by nicolahinssen** [comment]
@sampsyo Asked me to leave my thoughts here. #2763 

My suggestion is to create the following fields for Discogs (TXXX is customizable so that wouldn't be a problem).

Old | New
--- | ---
TXXX:MusicBrainz Album Artist Id=_1560798_ | TXXX:Discogs Album Artist Id=_1560798_
TXXX:MusicBrainz Album Id=_3175577_ | TXXX:Discogs Album Id=_3175577_
TXXX:MusicBrainz Album Release Country=_Netherlands_ |  TXXX:Discogs Album Release Country=_Netherlands_
TXXX:MusicBrainz Album Type=_Album_ | TXXX:Discogs Album Type=_Album_
TXXX:MusicBrainz Artist Id=_1560798_ | TXXX:Discogs Artist Id=_1560798_

**Comment by dbogdanov** [comment]
Agreed with @nicolahinssen on adding special fields for Discogs. This is a feature I would love to see. 

More generally, it will be great to store metadata from other sources (Bandcamp, Beatport, etc.) in the same way. The plugins retrieving the metadata should be able to define special fields themselves. Probably there won't be a consensus on naming of the fields, therefore this naming could be configurable by a user.

**Comment by dbogdanov** [comment]
> The only trick is that they should also have some fields that are not just dict keys because some fields are required or need special handling—see the apply_metadata code for those fields.

Should then all ``AlbumInfo`` and ``TrackInfo`` fields be kept, while adding a dict too?

**Comment by sampsyo** [comment]
I would actually be in favor of abandoning all the hand-coded attributes and just moving over complete to an unstructured `dict`-like object. It could simplify changes in the future quite a bit, and I don't think we get anything out of the current approach to the built-in set of fields.

**Comment by bastidest** [comment]
This is causing issues with other software (funkwhale) relying on the MB UUID format. They expect the fields to be valid UUIDs, not integers:

![image](https://user-images.githubusercontent.com/1242917/81539189-2b484c00-9370-11ea-8d92-c18e6f94b919.png)

**Comment by martinkirch** [comment]
Hello,
It seems this bug is still here. It has weird side effects: I discovered it after digging why `absubmit` fails for almost my whole library. The explanation is `absubmit` needs an UUID [to build the submission URL](https://github.com/beetbox/beets/blob/master/beetsplug/absubmit.py#L184). I guess it affects a few other plug-ins.

Maybe the simplest solution would be setting flexible attributes, as previously suggested

> Discogs could set di_albumid, di_trackid, ... Beatport could set bp_albumid, bp_trackid, ...

?

**Comment by Neurrone** [comment]
Another use case that I'm running into is tagging an audiobook collection with metadata from Audible. Because of the hard-coded fields, I don't think its possible for me to store additional metadata that is not already defined in one of the existing fields.

Wondering if there are any plans to fix this in the near / mid term?

**Comment by mikeroll** [comment]
This is still very relevant.

Meanwhile, I have abused the `zero` plugin and the fact that MBIDs are UUIDs while the identifiers from other sources are not and came up with this atrocity:

```yml
zero:
  auto: yes
  update_database: yes
  fields: mb_albumartistid mb_albumartistids mb_albumid mb_artistid mb_artistids mb_releasegroupid mb_releasetrackid mb_trackid mb_workid
  mb_albumartistid:  ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
  mb_albumartistids: ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
  mb_albumid:        ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
  mb_artistid:       ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
  mb_artistids:      ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
  mb_releasegroupid: ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
  mb_releasetrackid: ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
  mb_trackid:        ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
  mb_workid:         ["^(?![0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}).*$"]
```

Could've probably gone easier on the regex, but eh, it's horrible either way. Does the job though!
