### ISSUE TITLE
Mutagen struct.error during import

### ISSUE THREAD

**Issue by smammy** [beetbox/beets#622]
While importing certain tracks in my library, mutagen throws an exception that beets doesn't catch. I was able to isolate one of the handful of tracks that causes the problem. Here's what happens when I try to import it:

```
sam@media:/data/MUSIC2/displaytest$ ls -ls src/Tenacious\ D\ 16
total 1024
1024 -rw-rw-r-- 1 sam media 1045201 Mar 20 14:23 Tenacious D - Tenacious D - 17 Karate.mp3
sam@media:/data/MUSIC2/displaytest$ beet version
beets version 1.3.2
no plugins loaded
sam@media:/data/MUSIC2/displaytest$ beet --verbose import src/Tenacious\ D\ 16
data directory: /home/sam/.config/beets
library database: /data/MUSIC2/DB.sqlite3
library directory: /data/MUSIC2/Library
/home/sam/install/lib/python2.7/site-packages/mutagen/_id3frames.py:124: ID3Warning: Leftover data: RVA2: '\xff' (from '\x10\x10\x00\x00\x00\x00\xe6\xe8\x00\x00\xff\xff')
  ID3Warning)
Sending event: import_task_start
Looking up: /data/MUSIC2/displaytest/src/Tenacious D 16
Tagging Tenacious D - Tenacious D
No album IDs found.
Search terms: Tenacious D - Tenacious D
Album might be VA: False
Evaluating 5 candidates.
Candidate: Tenacious D - Tenacious D
Success. Distance: 0.642857
Candidate: Tenacious D - Tenacious D
Success. Distance: 0.642857
Candidate: Tenacious D - Tenacious D
Success. Distance: 0.642857
Candidate: Tenacious D - Tenacious D
Success. Distance: 0.642857
Candidate: Tenacious D - Tenacious D
Success. Distance: 0.642857

/data/MUSIC2/displaytest/src/Tenacious D 16 (1 items)
Finding tags for album "Tenacious D - Tenacious D".
Candidates:
1. Tenacious D - Tenacious D (35.7%) (missing tracks) (CD, 2003, XE, Epic)
2. Tenacious D - Tenacious D (35.7%) (missing tracks) (CD, 2002, AU, Epic)
3. Tenacious D - Tenacious D (35.7%) (missing tracks) (CD, 2002, SE, Epic)
4. Tenacious D - Tenacious D (35.7%) (missing tracks) (CD, 2001, CA, Epic)
5. Tenacious D - Tenacious D (35.7%) (missing tracks) (CD, 2001, US, Epic)
# selection (default 1), Skip, Use as-is, as Tracks, Enter search,
enter Id, aBort? 5
Tagging:
    Tenacious D - Tenacious D
(Similarity: 35.7%) (missing tracks) (CD, 2001, US, Epic)
Missing tracks:
 ! Kielbasa (#1) (3:00)
 ! One Note Song (#2) (1:23)
 ! Tribute (#3) (4:08)
 ! Wonderboy (#4) (4:06)
 ! Hard Fucking (#5) (0:35)
 ! Fuck Her Gently (#6) (2:03)
 ! Explosivo (#7) (1:55)
 ! Dio (#8) (1:41)
 ! Inward Singing (#9) (2:13)
 ! Kyle Quit the Band (#10) (1:29)
 ! The Road (#11) (2:18)
 ! Cock Pushups (#12) (0:48)
 ! Lee (#13) (1:02)
 ! Friendship Test (#14) (1:30)
 ! Friendship (#15) (1:59)
 ! Karate Schnitzel (#16) (0:36)
 ! Rock Your Socks (#18) (3:32)
 ! Drive-Thru (#19) (3:00)
 ! Double Team (#20) (3:10)
 ! City Hall / Malibu Nights (#21) (9:02)
Apply, More candidates, Skip, Use as-is, as Tracks, Enter search,
enter Id, aBort? a
Sending event: import_task_choice
Sending event: import_task_apply
0 of 1 items replaced
Sending event: database_change
Sending event: database_change
Sending event: item_moved
Sending event: database_change
Sending event: write
Traceback (most recent call last):
  File "/home/sam/install/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.2', 'console_scripts', 'beet')()
  File "/home/sam/install/lib/python2.7/site-packages/beets/ui/__init__.py", line 810, in main
    _raw_main(args)
  File "/home/sam/install/lib/python2.7/site-packages/beets/ui/__init__.py", line 802, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/sam/install/lib/python2.7/site-packages/beets/ui/commands.py", line 845, in import_func
    import_files(lib, paths, query)
  File "/home/sam/install/lib/python2.7/site-packages/beets/ui/commands.py", line 783, in import_files
    session.run()
  File "/home/sam/install/lib/python2.7/site-packages/beets/importer.py", line 343, in run
    pl.run_sequential()
  File "/home/sam/install/lib/python2.7/site-packages/beets/util/pipeline.py", line 330, in run_sequential
    out = coro.send(msg)
  File "/home/sam/install/lib/python2.7/site-packages/beets/importer.py", line 870, in manipulate_files
    item.write()
  File "/home/sam/install/lib/python2.7/site-packages/beets/library.py", line 534, in write
    f.save(id3v23=beets.config['id3v23'].get(bool))
  File "/home/sam/install/lib/python2.7/site-packages/beets/mediafile.py", line 947, in save
    self.mgfile.save()
  File "/home/sam/install/lib/python2.7/site-packages/mutagen/__init__.py", line 155, in save
    return self.tags.save(filename, **kwargs)
  File "/home/sam/install/lib/python2.7/site-packages/mutagen/id3.py", line 435, in save
    for (key, frame) in frames]
  File "/home/sam/install/lib/python2.7/site-packages/mutagen/id3.py", line 547, in __save_frame
    framedata = frame._writeData()
  File "/home/sam/install/lib/python2.7/site-packages/mutagen/_id3frames.py", line 129, in _writeData
    data.append(writer.write(self, getattr(self, writer.name)))
  File "/home/sam/install/lib/python2.7/site-packages/mutagen/_id3specs.py", line 360, in write
    return "\x10" + pack('>H', int(round(value * 32768)))
struct.error: 'H' format requires 0 <= number <= 65535
```

Here's my `beets.yaml`:

```
directory: /data/MUSIC2/Library
library: /data/MUSIC2/DB.sqlite3
threaded: no
list_format_item: $artist » $album » $title
list_format_album: $albumartist » $album
per_disk_numbering: yes
import:
    move: yes
    languages: en
paths:
    default: $albumartist/$album%aunique{}/$albumartist - $album%aunique{} - $track $title
    singleton: $albumartist/Singletons/$artist - $title
    comp: Compilations/$album%aunique{}/$album%aunique{} - $track $artist - $title
    albumtype:soundtrack: Soundtracks/$album%aunique{}/$album%aunique{} - $track $artist - $title
    albumtype:spokenword: Spoken Word/$albumartist/$album%aunique{}/$albumartist - $album%aunique{} - $track $title
    albumtype:audiobook: Audiobooks/$albumartist/$album%aunique{}/$albumartist - $album%aunique{} - $track $title
```

Here's the MP3 file in question: https://docs.google.com/file/d/0Bw3Ni8ANV84ORkZuZ0MwNFdDMnc
