### ISSUE TITLE
Replaygain tags set but always 0

### ISSUE THREAD

**Issue by bossanova808** [beetbox/beets#628]
Ok, so I am using latest stable beets, on Win 7 64 and have installed the various bits all easily enough (including fpcalc, gstreamer etc).

All is going well, but when I import albums, the verbose log only says this about replaygain:

```
replaygain: analyzing 10 files
replaygain: analysis finished
```

...however the resulting tags and tracks are always zero, both track and album tags.

config.yaml being used is:

```
library: C:\Utilities\beets\library.db
directory: F:\TestOut
import:
    copy: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beets.log
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: folder
original_date: yes
plugins: scrub chroma lyrics fetchart embedart replaygain ftintitle missing 
threaded: yes
color: yes
id3v23: yes
paths:
    default: $albumartist/$year - $album%aunique{}/$track $title
    singleton: Singletons/$year/$artist - $title
    comp: Various Artists/$year - $album%aunique{}/$track $title (by $artist)
lastgenre:
    count: 3
replaygain:
    overwrite: yes
    albumgain: yes
    command: C:/Utilities/mp3gain/mp3gain.exe
fetchart:
    cautious: true
    cover_names: front back cover folder
```

I saw someone else on the IRC log talking about this (called it 'flat replaygain' IIRC).  Same issue, also windows I think - was back in January sometime.

Am happy to help however I can...would love to get an auto importing/tag fixing system going on but RG is a very important part of this for me :)
