### ISSUE TITLE
Error on import while converting deletes original file

### ISSUE THREAD

**Issue by heartsucker** [beetbox/beets#659]
Here's my `config.yaml`

``` yaml
directory: ~/beets-music/music
library: ~/beets-music/musiclibrary.blb
log: ~/beets-music/log/
color: yes
original_date: yes
per_disc_numbering: yes
plugins: convert fetchart embedart ftintitle

import:
    write: yes
    copy: yes
    resume: yes

convert:
    auto: yes
    embed: true
    format: mp3
    max_bitrate: 320
    quiet: true
    threads: 8

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: /$artist/$title
    comp: Various Artists/$album%aunique{}/$track $title
```

If I run a `beet import ~/Music` and the processes errors out during conversion, it deletes the files being converted from my original directory.
