### ISSUE TITLE
ffmpeg is single threaded when converting while importing

### ISSUE THREAD

**Issue by heartsucker** [beetbox/beets#661]
Here's my `config.yaml`

``` yaml
directory: ~/beets-music/music
library: ~/beets-music/musiclibrary.blb
log: ~/beets-music/log/
color: yes
original_date: yes
per_disc_numbering: yes
plugins: convert fetchart embedart ftintitle

import:
    write: yes
    copy: yes
    resume: yes

convert:
    auto: yes
    embed: true
    format: mp3
    max_bitrate: 320
    quiet: true
    threads: 8

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: /$artist/$title
    comp: Various Artists/$album%aunique{}/$track $title
```

Running `beet import /path/to/music` produces a single thread on OS X 10.9.2 as seen from `top` and the Activity Monitor.
