### ISSUE TITLE
Beets deletes files when it shouldn't.

### ISSUE THREAD

**Issue by davidmurdoch** [beetbox/beets#721]
When running beets with the following cmd: `beets import -s "D:\Users\David Murdoch\Music"`, **my tracks get deleted one by one.**

```
directory: D:\Users\David Murdoch\Music
plugins: chroma info web inline fetchart lyrics lastgenre duplicates mbsync
id3v23: yes
import:
    copy: no
    move: yes
    write: yes
    group_albums: yes

paths:
    default: $albumartist/$album/$disc_and_track $title

item_fields:
    disc_and_track: u'%02i.%02i' % (disc, track) if
                    disctotal > 1 else u'%02i' % (track)

echonest:
    codegen: C:\Python27\Scripts\ENMFP-codegen
```

_Note: I'm running the above command after previous attempts were aborted (or crashed). When prompted with_ `Import of the directory: D:\Users\David Murdoch\Music was interrupted. Resume (Y/n)?` _I'm selecting `Y`+`{Enter}`._
