### ISSUE TITLE
MPDUpdate and MPDStats could manage multiple servers

### ISSUE THREAD

**Issue by hujuice** [beetbox/beets#785]
I'm using beets for a streaming server with multiple channels, i.e., multiple MPD daemons on different ports.
The solution, now, is to have many beets databases/configurations.

It would be fantastic to have multiple servers.

```
mpd:
    server: myFirst
        host: host1
        port: 6600
        password: mySecret1
    server: mySecond
        host: host2
        port: 6601
        password: mySecret2
```
