### ISSUE TITLE
Convert on import, extension issues

### ISSUE THREAD

**Issue by nijotz** [beetbox/beets#962]
First, I tried configuring the convert plugin simply:

```
convert:
  auto: yes
```

and ran `beet import <new_music_dir>`, but I got an error that transcoding failed:

```
Encoding <longfilename>.flac failed. Cleaning up...
```

I ran the default conversion command myself and saw that it couldn't detect the file type because there wasn't an extension.  So, I configured it like so:

```
convert:
  auto: yes
  formats:
    mp3:
      command: ffmpeg -i $source -y -vn -aq 2 -f mp3 $dest
      extension: mp3
```

Adding the `-f mp3`.  Conversion worked, but afterwords the filenames did not have any extensions.  I had to manually add the ".mp3" to the filenames.
